#pragma once

#include <polyfem/assembler/AssemblerUtils.hpp>
#include <polyfem/basis/Basis.hpp>

namespace polyfem::assembler
{
	class SumModel : public NLAssembler, ElasticityAssembler
	{
	public:
		using NLAssembler::assemble_energy;
		using NLAssembler::assemble_gradient;
		using NLAssembler::assemble_hessian;

		// compute elastic energy
		double compute_energy(const NonLinearAssemblerData &data) const override;
		// necessary for mixing linear model with non-linear collision response
		Eigen::MatrixXd assemble_hessian(const NonLinearAssemblerData &data) const override;
		// compute gradient of elastic energy, as assembler
		Eigen::VectorXd assemble_gradient(const NonLinearAssemblerData &data) const override;

		// uses autodiff to compute the rhs for a fabricated solution
		// uses autogenerated code to compute div(sigma)
		// pt is the evaluation of the solution at a point
		VectorNd compute_rhs(const AutodiffHessianPt &pt) const override;

		// initialize material parameter
		void add_multimaterial(const int index, const json &params, const Units &units) override;

		std::string name() const override { return "MaterialSum"; }
		bool allow_inversion() const override { return true; }
		std::map<std::string, ParamFunc> parameters() const override;

	protected:
		void assign_stress_tensor(const OutputData &data,
								  const int all_size,
								  const ElasticityTensorType &type,
								  Eigen::MatrixXd &all,
								  const std::function<Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const override;

	private:
		std::vector<std::shared_ptr<assembler::NLAssembler>> assemblers_;
	};
} // namespace polyfem::assembler
