var annotated_dup =
[
    [ "cppoptlib", "namespacecppoptlib.html", [
      [ "LBFGSSolver", "classcppoptlib_1_1_l_b_f_g_s_solver.html", "classcppoptlib_1_1_l_b_f_g_s_solver" ],
      [ "NonlinearSolver", "classcppoptlib_1_1_nonlinear_solver.html", "classcppoptlib_1_1_nonlinear_solver" ],
      [ "SparseNewtonDescentSolver", "classcppoptlib_1_1_sparse_newton_descent_solver.html", "classcppoptlib_1_1_sparse_newton_descent_solver" ]
    ] ],
    [ "nlohmann", "namespacenlohmann.html", [
      [ "adl_serializer< RowVector< T, dim, max_dim > >", "structnlohmann_1_1adl__serializer_3_01_row_vector_3_01_t_00_01dim_00_01max__dim_01_4_01_4.html", null ],
      [ "adl_serializer< Vector< T, dim, max_dim > >", "structnlohmann_1_1adl__serializer_3_01_vector_3_01_t_00_01dim_00_01max__dim_01_4_01_4.html", null ]
    ] ],
    [ "p_bases", "namespacep__bases.html", [
      [ "Lagrange", "classp__bases_1_1_lagrange.html", "classp__bases_1_1_lagrange" ],
      [ "ReferenceSimplex", "classp__bases_1_1_reference_simplex.html", "classp__bases_1_1_reference_simplex" ]
    ] ],
    [ "polyfem", "namespacepolyfem.html", [
      [ "assembler", "namespacepolyfem_1_1assembler.html", [
        [ "Assembler", "classpolyfem_1_1assembler_1_1_assembler.html", "classpolyfem_1_1assembler_1_1_assembler" ],
        [ "AssemblerUtils", "classpolyfem_1_1assembler_1_1_assembler_utils.html", "classpolyfem_1_1assembler_1_1_assembler_utils" ],
        [ "AssemblyValsCache", "classpolyfem_1_1assembler_1_1_assembly_vals_cache.html", "classpolyfem_1_1assembler_1_1_assembly_vals_cache" ],
        [ "AssemblyValues", "classpolyfem_1_1assembler_1_1_assembly_values.html", "classpolyfem_1_1assembler_1_1_assembly_values" ],
        [ "BilaplacianAux", "classpolyfem_1_1assembler_1_1_bilaplacian_aux.html", "classpolyfem_1_1assembler_1_1_bilaplacian_aux" ],
        [ "BilaplacianMain", "classpolyfem_1_1assembler_1_1_bilaplacian_main.html", "classpolyfem_1_1assembler_1_1_bilaplacian_main" ],
        [ "BilaplacianMixed", "classpolyfem_1_1assembler_1_1_bilaplacian_mixed.html", "classpolyfem_1_1assembler_1_1_bilaplacian_mixed" ],
        [ "ElementAssemblyValues", "classpolyfem_1_1assembler_1_1_element_assembly_values.html", "classpolyfem_1_1assembler_1_1_element_assembly_values" ],
        [ "GenericScalarProblem", "classpolyfem_1_1assembler_1_1_generic_scalar_problem.html", "classpolyfem_1_1assembler_1_1_generic_scalar_problem" ],
        [ "GenericTensorProblem", "classpolyfem_1_1assembler_1_1_generic_tensor_problem.html", "classpolyfem_1_1assembler_1_1_generic_tensor_problem" ],
        [ "Helmholtz", "classpolyfem_1_1assembler_1_1_helmholtz.html", "classpolyfem_1_1assembler_1_1_helmholtz" ],
        [ "HookeLinearElasticity", "classpolyfem_1_1assembler_1_1_hooke_linear_elasticity.html", "classpolyfem_1_1assembler_1_1_hooke_linear_elasticity" ],
        [ "IncompressibleLinearElasticityDispacement", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_dispacement.html", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_dispacement" ],
        [ "IncompressibleLinearElasticityMixed", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_mixed.html", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_mixed" ],
        [ "IncompressibleLinearElasticityPressure", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_pressure.html", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_pressure" ],
        [ "Interpolation", "classpolyfem_1_1assembler_1_1_interpolation.html", "classpolyfem_1_1assembler_1_1_interpolation" ],
        [ "Laplacian", "classpolyfem_1_1assembler_1_1_laplacian.html", "classpolyfem_1_1assembler_1_1_laplacian" ],
        [ "LinearElasticity", "classpolyfem_1_1assembler_1_1_linear_elasticity.html", "classpolyfem_1_1assembler_1_1_linear_elasticity" ],
        [ "LinearInterpolation", "classpolyfem_1_1assembler_1_1_linear_interpolation.html", "classpolyfem_1_1assembler_1_1_linear_interpolation" ],
        [ "LinearRamp", "classpolyfem_1_1assembler_1_1_linear_ramp.html", "classpolyfem_1_1assembler_1_1_linear_ramp" ],
        [ "MassMatrixAssembler", "classpolyfem_1_1assembler_1_1_mass_matrix_assembler.html", "classpolyfem_1_1assembler_1_1_mass_matrix_assembler" ],
        [ "MixedAssembler", "classpolyfem_1_1assembler_1_1_mixed_assembler.html", "classpolyfem_1_1assembler_1_1_mixed_assembler" ],
        [ "MultiModel", "classpolyfem_1_1assembler_1_1_multi_model.html", "classpolyfem_1_1assembler_1_1_multi_model" ],
        [ "NavierStokesVelocity", "classpolyfem_1_1assembler_1_1_navier_stokes_velocity.html", "classpolyfem_1_1assembler_1_1_navier_stokes_velocity" ],
        [ "NeoHookeanElasticity", "classpolyfem_1_1assembler_1_1_neo_hookean_elasticity.html", "classpolyfem_1_1assembler_1_1_neo_hookean_elasticity" ],
        [ "NLAssembler", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", "classpolyfem_1_1assembler_1_1_n_l_assembler" ],
        [ "NoInterpolation", "classpolyfem_1_1assembler_1_1_no_interpolation.html", "classpolyfem_1_1assembler_1_1_no_interpolation" ],
        [ "OgdenElasticity", "classpolyfem_1_1assembler_1_1_ogden_elasticity.html", "classpolyfem_1_1assembler_1_1_ogden_elasticity" ],
        [ "Problem", "classpolyfem_1_1assembler_1_1_problem.html", "classpolyfem_1_1assembler_1_1_problem" ],
        [ "RhsAssembler", "classpolyfem_1_1assembler_1_1_rhs_assembler.html", "classpolyfem_1_1assembler_1_1_rhs_assembler" ],
        [ "SaintVenantElasticity", "classpolyfem_1_1assembler_1_1_saint_venant_elasticity.html", "classpolyfem_1_1assembler_1_1_saint_venant_elasticity" ],
        [ "StokesMixed", "classpolyfem_1_1assembler_1_1_stokes_mixed.html", "classpolyfem_1_1assembler_1_1_stokes_mixed" ],
        [ "StokesPressure", "classpolyfem_1_1assembler_1_1_stokes_pressure.html", "classpolyfem_1_1assembler_1_1_stokes_pressure" ],
        [ "StokesVelocity", "classpolyfem_1_1assembler_1_1_stokes_velocity.html", "classpolyfem_1_1assembler_1_1_stokes_velocity" ]
      ] ],
      [ "basis", "namespacepolyfem_1_1basis.html", [
        [ "Basis", "classpolyfem_1_1basis_1_1_basis.html", "classpolyfem_1_1basis_1_1_basis" ],
        [ "ElementBases", "classpolyfem_1_1basis_1_1_element_bases.html", "classpolyfem_1_1basis_1_1_element_bases" ],
        [ "FEBasis2d", "classpolyfem_1_1basis_1_1_f_e_basis2d.html", null ],
        [ "FEBasis3d", "classpolyfem_1_1basis_1_1_f_e_basis3d.html", null ],
        [ "InterfaceData", "structpolyfem_1_1basis_1_1_interface_data.html", "structpolyfem_1_1basis_1_1_interface_data" ],
        [ "Local2Global", "classpolyfem_1_1basis_1_1_local2_global.html", "classpolyfem_1_1basis_1_1_local2_global" ],
        [ "MVPolygonalBasis2d", "classpolyfem_1_1basis_1_1_m_v_polygonal_basis2d.html", null ],
        [ "PolygonalBasis2d", "classpolyfem_1_1basis_1_1_polygonal_basis2d.html", null ],
        [ "PolygonalBasis3d", "classpolyfem_1_1basis_1_1_polygonal_basis3d.html", null ],
        [ "QuadraticBSpline", "classpolyfem_1_1basis_1_1_quadratic_b_spline.html", "classpolyfem_1_1basis_1_1_quadratic_b_spline" ],
        [ "QuadraticBSpline2d", "classpolyfem_1_1basis_1_1_quadratic_b_spline2d.html", "classpolyfem_1_1basis_1_1_quadratic_b_spline2d" ],
        [ "QuadraticBSpline3d", "classpolyfem_1_1basis_1_1_quadratic_b_spline3d.html", "classpolyfem_1_1basis_1_1_quadratic_b_spline3d" ],
        [ "RBFWithLinear", "classpolyfem_1_1basis_1_1_r_b_f_with_linear.html", "classpolyfem_1_1basis_1_1_r_b_f_with_linear" ],
        [ "RBFWithQuadratic", "classpolyfem_1_1basis_1_1_r_b_f_with_quadratic.html", "classpolyfem_1_1basis_1_1_r_b_f_with_quadratic" ],
        [ "RBFWithQuadraticLagrange", "classpolyfem_1_1basis_1_1_r_b_f_with_quadratic_lagrange.html", "classpolyfem_1_1basis_1_1_r_b_f_with_quadratic_lagrange" ],
        [ "SpectralBasis2d", "classpolyfem_1_1basis_1_1_spectral_basis2d.html", null ],
        [ "SplineBasis2d", "classpolyfem_1_1basis_1_1_spline_basis2d.html", null ],
        [ "SplineBasis3d", "classpolyfem_1_1basis_1_1_spline_basis3d.html", null ]
      ] ],
      [ "mesh", "namespacepolyfem_1_1mesh.html", [
        [ "Navigation", "namespacepolyfem_1_1mesh_1_1_navigation.html", [
          [ "Index", "structpolyfem_1_1mesh_1_1_navigation_1_1_index.html", "structpolyfem_1_1mesh_1_1_navigation_1_1_index" ]
        ] ],
        [ "Navigation3D", "namespacepolyfem_1_1mesh_1_1_navigation3_d.html", [
          [ "Index", "structpolyfem_1_1mesh_1_1_navigation3_d_1_1_index.html", "structpolyfem_1_1mesh_1_1_navigation3_d_1_1_index" ]
        ] ],
        [ "CMesh2D", "classpolyfem_1_1mesh_1_1_c_mesh2_d.html", "classpolyfem_1_1mesh_1_1_c_mesh2_d" ],
        [ "CMesh3D", "classpolyfem_1_1mesh_1_1_c_mesh3_d.html", "classpolyfem_1_1mesh_1_1_c_mesh3_d" ],
        [ "Edge", "structpolyfem_1_1mesh_1_1_edge.html", "structpolyfem_1_1mesh_1_1_edge" ],
        [ "Element", "structpolyfem_1_1mesh_1_1_element.html", "structpolyfem_1_1mesh_1_1_element" ],
        [ "Face", "structpolyfem_1_1mesh_1_1_face.html", "structpolyfem_1_1mesh_1_1_face" ],
        [ "LocalBoundary", "classpolyfem_1_1mesh_1_1_local_boundary.html", "classpolyfem_1_1mesh_1_1_local_boundary" ],
        [ "Mesh", "classpolyfem_1_1mesh_1_1_mesh.html", "classpolyfem_1_1mesh_1_1_mesh" ],
        [ "Mesh2D", "classpolyfem_1_1mesh_1_1_mesh2_d.html", "classpolyfem_1_1mesh_1_1_mesh2_d" ],
        [ "Mesh3D", "classpolyfem_1_1mesh_1_1_mesh3_d.html", "classpolyfem_1_1mesh_1_1_mesh3_d" ],
        [ "Mesh3DStorage", "structpolyfem_1_1mesh_1_1_mesh3_d_storage.html", "structpolyfem_1_1mesh_1_1_mesh3_d_storage" ],
        [ "Mesh_Quality", "structpolyfem_1_1mesh_1_1_mesh___quality.html", "structpolyfem_1_1mesh_1_1_mesh___quality" ],
        [ "MeshNodes", "classpolyfem_1_1mesh_1_1_mesh_nodes.html", "classpolyfem_1_1mesh_1_1_mesh_nodes" ],
        [ "NCMesh2D", "classpolyfem_1_1mesh_1_1_n_c_mesh2_d.html", "classpolyfem_1_1mesh_1_1_n_c_mesh2_d" ],
        [ "NCMesh3D", "classpolyfem_1_1mesh_1_1_n_c_mesh3_d.html", "classpolyfem_1_1mesh_1_1_n_c_mesh3_d" ],
        [ "Obstacle", "classpolyfem_1_1mesh_1_1_obstacle.html", "classpolyfem_1_1mesh_1_1_obstacle" ],
        [ "Vertex", "structpolyfem_1_1mesh_1_1_vertex.html", "structpolyfem_1_1mesh_1_1_vertex" ],
        [ "VTUWriter", "classpolyfem_1_1mesh_1_1_v_t_u_writer.html", "classpolyfem_1_1mesh_1_1_v_t_u_writer" ]
      ] ],
      [ "problem", "namespacepolyfem_1_1problem.html", [
        [ "Airfoil", "classpolyfem_1_1problem_1_1_airfoil.html", "classpolyfem_1_1problem_1_1_airfoil" ],
        [ "BilaplacianProblemWithSolution", "classpolyfem_1_1problem_1_1_bilaplacian_problem_with_solution.html", "classpolyfem_1_1problem_1_1_bilaplacian_problem_with_solution" ],
        [ "CompressionElasticProblemExact", "classpolyfem_1_1problem_1_1_compression_elastic_problem_exact.html", "classpolyfem_1_1problem_1_1_compression_elastic_problem_exact" ],
        [ "ConstantVelocity", "classpolyfem_1_1problem_1_1_constant_velocity.html", "classpolyfem_1_1problem_1_1_constant_velocity" ],
        [ "CornerFlow", "classpolyfem_1_1problem_1_1_corner_flow.html", "classpolyfem_1_1problem_1_1_corner_flow" ],
        [ "CubicProblem", "classpolyfem_1_1problem_1_1_cubic_problem.html", "classpolyfem_1_1problem_1_1_cubic_problem" ],
        [ "DoubleTorsionElasticProblem", "classpolyfem_1_1problem_1_1_double_torsion_elastic_problem.html", "classpolyfem_1_1problem_1_1_double_torsion_elastic_problem" ],
        [ "DrivenCavity", "classpolyfem_1_1problem_1_1_driven_cavity.html", "classpolyfem_1_1problem_1_1_driven_cavity" ],
        [ "DrivenCavityC0", "classpolyfem_1_1problem_1_1_driven_cavity_c0.html", "classpolyfem_1_1problem_1_1_driven_cavity_c0" ],
        [ "DrivenCavitySmooth", "classpolyfem_1_1problem_1_1_driven_cavity_smooth.html", "classpolyfem_1_1problem_1_1_driven_cavity_smooth" ],
        [ "ElasticCantileverExact", "classpolyfem_1_1problem_1_1_elastic_cantilever_exact.html", "classpolyfem_1_1problem_1_1_elastic_cantilever_exact" ],
        [ "ElasticProblem", "classpolyfem_1_1problem_1_1_elastic_problem.html", "classpolyfem_1_1problem_1_1_elastic_problem" ],
        [ "ElasticProblemExact", "classpolyfem_1_1problem_1_1_elastic_problem_exact.html", "classpolyfem_1_1problem_1_1_elastic_problem_exact" ],
        [ "ElasticProblemZeroBC", "classpolyfem_1_1problem_1_1_elastic_problem_zero_b_c.html", "classpolyfem_1_1problem_1_1_elastic_problem_zero_b_c" ],
        [ "Flow", "classpolyfem_1_1problem_1_1_flow.html", "classpolyfem_1_1problem_1_1_flow" ],
        [ "FlowWithObstacle", "classpolyfem_1_1problem_1_1_flow_with_obstacle.html", "classpolyfem_1_1problem_1_1_flow_with_obstacle" ],
        [ "FrankeProblem", "classpolyfem_1_1problem_1_1_franke_problem.html", "classpolyfem_1_1problem_1_1_franke_problem" ],
        [ "FrankeProblemOld", "classpolyfem_1_1problem_1_1_franke_problem_old.html", "classpolyfem_1_1problem_1_1_franke_problem_old" ],
        [ "GenericScalarProblemExact", "classpolyfem_1_1problem_1_1_generic_scalar_problem_exact.html", "classpolyfem_1_1problem_1_1_generic_scalar_problem_exact" ],
        [ "GravityProblem", "classpolyfem_1_1problem_1_1_gravity_problem.html", "classpolyfem_1_1problem_1_1_gravity_problem" ],
        [ "KernelProblem", "classpolyfem_1_1problem_1_1_kernel_problem.html", "classpolyfem_1_1problem_1_1_kernel_problem" ],
        [ "Kovnaszy", "classpolyfem_1_1problem_1_1_kovnaszy.html", "classpolyfem_1_1problem_1_1_kovnaszy" ],
        [ "LinearElasticProblemExact", "classpolyfem_1_1problem_1_1_linear_elastic_problem_exact.html", "classpolyfem_1_1problem_1_1_linear_elastic_problem_exact" ],
        [ "LinearProblem", "classpolyfem_1_1problem_1_1_linear_problem.html", "classpolyfem_1_1problem_1_1_linear_problem" ],
        [ "Lshape", "classpolyfem_1_1problem_1_1_lshape.html", "classpolyfem_1_1problem_1_1_lshape" ],
        [ "MinSurfProblem", "classpolyfem_1_1problem_1_1_min_surf_problem.html", "classpolyfem_1_1problem_1_1_min_surf_problem" ],
        [ "NodeProblem", "classpolyfem_1_1problem_1_1_node_problem.html", "classpolyfem_1_1problem_1_1_node_problem" ],
        [ "NodeValues", "classpolyfem_1_1problem_1_1_node_values.html", "classpolyfem_1_1problem_1_1_node_values" ],
        [ "PointBasedTensorProblem", "classpolyfem_1_1problem_1_1_point_based_tensor_problem.html", "classpolyfem_1_1problem_1_1_point_based_tensor_problem" ],
        [ "ProblemFactory", "classpolyfem_1_1problem_1_1_problem_factory.html", "classpolyfem_1_1problem_1_1_problem_factory" ],
        [ "ProblemWithSolution", "classpolyfem_1_1problem_1_1_problem_with_solution.html", "classpolyfem_1_1problem_1_1_problem_with_solution" ],
        [ "QuadraticElasticProblemExact", "classpolyfem_1_1problem_1_1_quadratic_elastic_problem_exact.html", "classpolyfem_1_1problem_1_1_quadratic_elastic_problem_exact" ],
        [ "QuadraticProblem", "classpolyfem_1_1problem_1_1_quadratic_problem.html", "classpolyfem_1_1problem_1_1_quadratic_problem" ],
        [ "SimpleStokeProblemExact", "classpolyfem_1_1problem_1_1_simple_stoke_problem_exact.html", "classpolyfem_1_1problem_1_1_simple_stoke_problem_exact" ],
        [ "SineProblem", "classpolyfem_1_1problem_1_1_sine_problem.html", "classpolyfem_1_1problem_1_1_sine_problem" ],
        [ "SineStokeProblemExact", "classpolyfem_1_1problem_1_1_sine_stoke_problem_exact.html", "classpolyfem_1_1problem_1_1_sine_stoke_problem_exact" ],
        [ "StokesLawProblem", "classpolyfem_1_1problem_1_1_stokes_law_problem.html", "classpolyfem_1_1problem_1_1_stokes_law_problem" ],
        [ "TaylorGreenVortexProblem", "classpolyfem_1_1problem_1_1_taylor_green_vortex_problem.html", "classpolyfem_1_1problem_1_1_taylor_green_vortex_problem" ],
        [ "TestProblem", "classpolyfem_1_1problem_1_1_test_problem.html", "classpolyfem_1_1problem_1_1_test_problem" ],
        [ "TimeDependentProblem", "classpolyfem_1_1problem_1_1_time_dependent_problem.html", "classpolyfem_1_1problem_1_1_time_dependent_problem" ],
        [ "TimeDepentendStokesProblem", "classpolyfem_1_1problem_1_1_time_depentend_stokes_problem.html", "classpolyfem_1_1problem_1_1_time_depentend_stokes_problem" ],
        [ "TorsionElasticProblem", "classpolyfem_1_1problem_1_1_torsion_elastic_problem.html", "classpolyfem_1_1problem_1_1_torsion_elastic_problem" ],
        [ "TransientStokeProblemExact", "classpolyfem_1_1problem_1_1_transient_stoke_problem_exact.html", "classpolyfem_1_1problem_1_1_transient_stoke_problem_exact" ],
        [ "TwoSpheres", "classpolyfem_1_1problem_1_1_two_spheres.html", "classpolyfem_1_1problem_1_1_two_spheres" ],
        [ "UnitFlowWithObstacle", "classpolyfem_1_1problem_1_1_unit_flow_with_obstacle.html", "classpolyfem_1_1problem_1_1_unit_flow_with_obstacle" ],
        [ "WalkProblem", "classpolyfem_1_1problem_1_1_walk_problem.html", "classpolyfem_1_1problem_1_1_walk_problem" ],
        [ "ZeroBCProblem", "classpolyfem_1_1problem_1_1_zero_b_c_problem.html", "classpolyfem_1_1problem_1_1_zero_b_c_problem" ]
      ] ],
      [ "quadrature", "namespacepolyfem_1_1quadrature.html", [
        [ "HexQuadrature", "classpolyfem_1_1quadrature_1_1_hex_quadrature.html", "classpolyfem_1_1quadrature_1_1_hex_quadrature" ],
        [ "LineQuadrature", "classpolyfem_1_1quadrature_1_1_line_quadrature.html", "classpolyfem_1_1quadrature_1_1_line_quadrature" ],
        [ "PolygonQuadrature", "classpolyfem_1_1quadrature_1_1_polygon_quadrature.html", "classpolyfem_1_1quadrature_1_1_polygon_quadrature" ],
        [ "PolyhedronQuadrature", "classpolyfem_1_1quadrature_1_1_polyhedron_quadrature.html", null ],
        [ "QuadQuadrature", "classpolyfem_1_1quadrature_1_1_quad_quadrature.html", "classpolyfem_1_1quadrature_1_1_quad_quadrature" ],
        [ "Quadrature", "classpolyfem_1_1quadrature_1_1_quadrature.html", "classpolyfem_1_1quadrature_1_1_quadrature" ],
        [ "TetQuadrature", "classpolyfem_1_1quadrature_1_1_tet_quadrature.html", "classpolyfem_1_1quadrature_1_1_tet_quadrature" ],
        [ "TriQuadrature", "classpolyfem_1_1quadrature_1_1_tri_quadrature.html", "classpolyfem_1_1quadrature_1_1_tri_quadrature" ]
      ] ],
      [ "renderer", "namespacepolyfem_1_1renderer.html", [
        [ "FragmentAttributes", "classpolyfem_1_1renderer_1_1_fragment_attributes.html", "classpolyfem_1_1renderer_1_1_fragment_attributes" ],
        [ "FrameBufferAttributes", "classpolyfem_1_1renderer_1_1_frame_buffer_attributes.html", "classpolyfem_1_1renderer_1_1_frame_buffer_attributes" ],
        [ "Material", "structpolyfem_1_1renderer_1_1_material.html", "structpolyfem_1_1renderer_1_1_material" ],
        [ "Program", "classpolyfem_1_1renderer_1_1_program.html", "classpolyfem_1_1renderer_1_1_program" ],
        [ "UniformAttributes", "classpolyfem_1_1renderer_1_1_uniform_attributes.html", "classpolyfem_1_1renderer_1_1_uniform_attributes" ],
        [ "VertexAttributes", "classpolyfem_1_1renderer_1_1_vertex_attributes.html", "classpolyfem_1_1renderer_1_1_vertex_attributes" ]
      ] ],
      [ "solver", "namespacepolyfem_1_1solver.html", [
        [ "line_search", "namespacepolyfem_1_1solver_1_1line__search.html", [
          [ "ArmijoLineSearch", "classpolyfem_1_1solver_1_1line__search_1_1_armijo_line_search.html", "classpolyfem_1_1solver_1_1line__search_1_1_armijo_line_search" ],
          [ "BacktrackingLineSearch", "classpolyfem_1_1solver_1_1line__search_1_1_backtracking_line_search.html", "classpolyfem_1_1solver_1_1line__search_1_1_backtracking_line_search" ],
          [ "CppOptArmijoLineSearch", "classpolyfem_1_1solver_1_1line__search_1_1_cpp_opt_armijo_line_search.html", "classpolyfem_1_1solver_1_1line__search_1_1_cpp_opt_armijo_line_search" ],
          [ "LineSearch", "classpolyfem_1_1solver_1_1line__search_1_1_line_search.html", "classpolyfem_1_1solver_1_1line__search_1_1_line_search" ],
          [ "MoreThuenteLineSearch", "classpolyfem_1_1solver_1_1line__search_1_1_more_thuente_line_search.html", "classpolyfem_1_1solver_1_1line__search_1_1_more_thuente_line_search" ]
        ] ],
        [ "ALNLProblem", "classpolyfem_1_1solver_1_1_a_l_n_l_problem.html", "classpolyfem_1_1solver_1_1_a_l_n_l_problem" ],
        [ "NavierStokesSolver", "classpolyfem_1_1solver_1_1_navier_stokes_solver.html", "classpolyfem_1_1solver_1_1_navier_stokes_solver" ],
        [ "NLProblem", "classpolyfem_1_1solver_1_1_n_l_problem.html", "classpolyfem_1_1solver_1_1_n_l_problem" ],
        [ "OperatorSplittingSolver", "classpolyfem_1_1solver_1_1_operator_splitting_solver.html", "classpolyfem_1_1solver_1_1_operator_splitting_solver" ],
        [ "TransientNavierStokesSolver", "classpolyfem_1_1solver_1_1_transient_navier_stokes_solver.html", "classpolyfem_1_1solver_1_1_transient_navier_stokes_solver" ]
      ] ],
      [ "time_integrator", "namespacepolyfem_1_1time__integrator.html", [
        [ "BDF", "classpolyfem_1_1time__integrator_1_1_b_d_f.html", "classpolyfem_1_1time__integrator_1_1_b_d_f" ],
        [ "ImplicitEuler", "classpolyfem_1_1time__integrator_1_1_implicit_euler.html", "classpolyfem_1_1time__integrator_1_1_implicit_euler" ],
        [ "ImplicitNewmark", "classpolyfem_1_1time__integrator_1_1_implicit_newmark.html", "classpolyfem_1_1time__integrator_1_1_implicit_newmark" ],
        [ "ImplicitTimeIntegrator", "classpolyfem_1_1time__integrator_1_1_implicit_time_integrator.html", "classpolyfem_1_1time__integrator_1_1_implicit_time_integrator" ]
      ] ],
      [ "utils", "namespacepolyfem_1_1utils.html", [
        [ "AxisPlaneSelection", "classpolyfem_1_1utils_1_1_axis_plane_selection.html", "classpolyfem_1_1utils_1_1_axis_plane_selection" ],
        [ "base64Layer", "classpolyfem_1_1utils_1_1base64_layer.html", "classpolyfem_1_1utils_1_1base64_layer" ],
        [ "BoundarySampler", "classpolyfem_1_1utils_1_1_boundary_sampler.html", null ],
        [ "BoxSelection", "classpolyfem_1_1utils_1_1_box_selection.html", "classpolyfem_1_1utils_1_1_box_selection" ],
        [ "EdgeSampler", "classpolyfem_1_1utils_1_1_edge_sampler.html", null ],
        [ "ExpressionValue", "classpolyfem_1_1utils_1_1_expression_value.html", "classpolyfem_1_1utils_1_1_expression_value" ],
        [ "FEBioReader", "classpolyfem_1_1utils_1_1_f_e_bio_reader.html", null ],
        [ "FileSelection", "classpolyfem_1_1utils_1_1_file_selection.html", "classpolyfem_1_1utils_1_1_file_selection" ],
        [ "HashPair", "structpolyfem_1_1utils_1_1_hash_pair.html", "structpolyfem_1_1utils_1_1_hash_pair" ],
        [ "HashVector", "structpolyfem_1_1utils_1_1_hash_vector.html", "structpolyfem_1_1utils_1_1_hash_vector" ],
        [ "InterpolatedFunction2d", "classpolyfem_1_1utils_1_1_interpolated_function2d.html", "classpolyfem_1_1utils_1_1_interpolated_function2d" ],
        [ "MshReader", "classpolyfem_1_1utils_1_1_msh_reader.html", null ],
        [ "NThread", "classpolyfem_1_1utils_1_1_n_thread.html", "classpolyfem_1_1utils_1_1_n_thread" ],
        [ "OBJReader", "classpolyfem_1_1utils_1_1_o_b_j_reader.html", "classpolyfem_1_1utils_1_1_o_b_j_reader" ],
        [ "OBJWriter", "classpolyfem_1_1utils_1_1_o_b_j_writer.html", "classpolyfem_1_1utils_1_1_o_b_j_writer" ],
        [ "PlaneSelection", "classpolyfem_1_1utils_1_1_plane_selection.html", "classpolyfem_1_1utils_1_1_plane_selection" ],
        [ "RBFInterpolation", "classpolyfem_1_1utils_1_1_r_b_f_interpolation.html", "classpolyfem_1_1utils_1_1_r_b_f_interpolation" ],
        [ "RefElementSampler", "classpolyfem_1_1utils_1_1_ref_element_sampler.html", "classpolyfem_1_1utils_1_1_ref_element_sampler" ],
        [ "Selection", "classpolyfem_1_1utils_1_1_selection.html", "classpolyfem_1_1utils_1_1_selection" ],
        [ "SpareMatrixCache", "classpolyfem_1_1utils_1_1_spare_matrix_cache.html", "classpolyfem_1_1utils_1_1_spare_matrix_cache" ],
        [ "SpecifiedSelection", "classpolyfem_1_1utils_1_1_specified_selection.html", "classpolyfem_1_1utils_1_1_specified_selection" ],
        [ "SphereSelection", "classpolyfem_1_1utils_1_1_sphere_selection.html", "classpolyfem_1_1utils_1_1_sphere_selection" ],
        [ "Timer", "classpolyfem_1_1utils_1_1_timer.html", "classpolyfem_1_1utils_1_1_timer" ],
        [ "UniformSelection", "classpolyfem_1_1utils_1_1_uniform_selection.html", "classpolyfem_1_1utils_1_1_uniform_selection" ]
      ] ],
      [ "AutoDiffAllocator", "classpolyfem_1_1_auto_diff_allocator.html", "classpolyfem_1_1_auto_diff_allocator" ],
      [ "AutoDiffAllocator< double >", "classpolyfem_1_1_auto_diff_allocator_3_01double_01_4.html", "classpolyfem_1_1_auto_diff_allocator_3_01double_01_4" ],
      [ "Density", "classpolyfem_1_1_density.html", "classpolyfem_1_1_density" ],
      [ "ElasticityTensor", "classpolyfem_1_1_elasticity_tensor.html", "classpolyfem_1_1_elasticity_tensor" ],
      [ "LameParameters", "classpolyfem_1_1_lame_parameters.html", "classpolyfem_1_1_lame_parameters" ],
      [ "SolutionFrame", "classpolyfem_1_1_solution_frame.html", "classpolyfem_1_1_solution_frame" ],
      [ "State", "classpolyfem_1_1_state.html", "classpolyfem_1_1_state" ],
      [ "StepData", "classpolyfem_1_1_step_data.html", "classpolyfem_1_1_step_data" ]
    ] ],
    [ "q_bases", "namespaceq__bases.html", [
      [ "Lagrange", "classq__bases_1_1_lagrange.html", "classq__bases_1_1_lagrange" ],
      [ "ReferenceSimplex", "classq__bases_1_1_reference_simplex.html", "classq__bases_1_1_reference_simplex" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Eigen::Matrix< Scalar, Rows, Cols > >", "structstd_1_1hash_3_01_eigen_1_1_matrix_3_01_scalar_00_01_rows_00_01_cols_01_4_01_4.html", "structstd_1_1hash_3_01_eigen_1_1_matrix_3_01_scalar_00_01_rows_00_01_cols_01_4_01_4" ]
    ] ],
    [ "DiffScalarBase", "struct_diff_scalar_base.html", null ],
    [ "DScalar1", "struct_d_scalar1.html", "struct_d_scalar1" ],
    [ "DScalar2", "struct_d_scalar2.html", "struct_d_scalar2" ]
];