PolyFEM: polyfem::basis::FEBasis3d Class Reference
polyfem::basis::FEBasis3d Class Reference
#include <FEBasis3d.hpp>
Static Public Member Functions
static int build_bases (const mesh::Mesh3D &mesh, const int quadrature_order, const int discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector< ElementBases > &bases, std::vector< mesh::LocalBoundary > &local_boundary, std::map< int, InterfaceData > &poly_face_to_data, std::shared_ptr< polyfem::mesh::MeshNodes > &mesh_nodes)
Builds FE basis functions over the entire mesh (P1, P2 over tets, Q1, Q2 over hes).
static int build_bases (const mesh::Mesh3D &mesh, const int quadrature_order, const Eigen::VectorXi &discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector< ElementBases > &bases, std::vector< mesh::LocalBoundary > &local_boundary, std::map< int, InterfaceData > &poly_face_to_data, std::shared_ptr< polyfem::mesh::MeshNodes > &mesh_nodes)
Builds FE basis functions over the entire mesh (P1, P2 over tets, Q1, Q2 over hex).
static Eigen::VectorXi tet_face_local_nodes (const int p, const mesh::Mesh3D &mesh, mesh::Navigation3D::Index index)
static Eigen::VectorXi hex_face_local_nodes (const bool serendipity, const int q, const mesh::Mesh3D &mesh, mesh::Navigation3D::Index index)
Static Private Member Functions
static Eigen::MatrixXd linear_hex_face_local_nodes_coordinates (const mesh::Mesh3D &mesh, mesh::Navigation3D::Index index)
static Eigen::RowVector3d quadr_hex_local_node_coordinates (int local_index)
Detailed Description
Definition at line 18 of file FEBasis3d.hpp.
Member Function Documentation
build_bases() [1/2]
static int polyfem::basis::FEBasis3d::build_bases (const mesh::Mesh3D & mesh, const int quadrature_order, const Eigen::VectorXi & discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector< ElementBases > & bases, std::vector< mesh::LocalBoundary > & local_boundary, std::map< int, InterfaceData > & poly_face_to_data, std::shared_ptr< polyfem::mesh::MeshNodes > & mesh_nodes) static
Builds FE basis functions over the entire mesh (P1, P2 over tets, Q1, Q2 over hex).
Polygonal facets with > 4 vertices are dealt later on by the PolygonalBasis3d class.
Parameters
[in] mesh The input volumetric mesh
[in] quadrature_order The quadrature order
[in] discr_order The order for each element
[in] serendipity Uses serendipity bases or not (only for hex)
[in] has_polys Does the mesh has polygons, if not the interface mapping is not necessary
[in] is_geom_bases Flag to decide if build gemetric mapping or normal bases, used to decide if the ndoes are important
[out] bases List of basis functions per element
[out] local_boundary List of descriptor per element, indicating which edge of the canonical elements lie on the boundary of the mesh
[out] poly_edge_to_data Data for edges at the interface with a polygon (used to build the harmonics inside polygons)
Returns
The number of basis functions created.
build_bases() [2/2]
static int polyfem::basis::FEBasis3d::build_bases (const mesh::Mesh3D & mesh, const int quadrature_order, const int discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector< ElementBases > & bases, std::vector< mesh::LocalBoundary > & local_boundary, std::map< int, InterfaceData > & poly_face_to_data, std::shared_ptr< polyfem::mesh::MeshNodes > & mesh_nodes) static
Builds FE basis functions over the entire mesh (P1, P2 over tets, Q1, Q2 over hes).
Polygonal facets with > 4 vertices are dealt later on by the PolygonalBasis3d class.
Parameters
[in] mesh The input volumetric mesh
[in] quadrature_order The quadrature order
[in] discr_order The order of the elements (1-4)
[in] serendipity Uses serendipity bases or not (only for hex)
[in] has_polys Does the mesh has polygons, if not the interface mapping is not necessary
[in] is_geom_bases Flag to decide if build gemetric mapping or normal bases, used to decide if the ndoes are important
[out] bases List of basis functions per element
[out] local_boundary List of descriptor per element, indicating which edge of the canonical elements lie on the boundary of the mesh
[out] poly_edge_to_data Data for edges at the interface with a polygon (used to build the harmonics inside polygons)
Returns
The number of basis functions created.
hex_face_local_nodes()
Eigen::VectorXi FEBasis3d::hex_face_local_nodes (const bool serendipity, const int q, const mesh::Mesh3D & mesh, mesh::Navigation3D::Index index) static
Definition at line 1188 of file FEBasis3d.cpp.
References polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Mesh3D::get_index_from_element_edge(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh3D::next_around_face(), p_bases::nn, p_bases::nodes, polyfem::autogen::q_nodes_3d(), p_bases::reverse, polyfem::mesh::Mesh3D::switch_vertex(), p_bases::tmp, and polyfem::mesh::Navigation3D::Index::vertex.
linear_hex_face_local_nodes_coordinates()
static Eigen::MatrixXd polyfem::basis::FEBasis3d::linear_hex_face_local_nodes_coordinates (const mesh::Mesh3D & mesh, mesh::Navigation3D::Index index) static private
quadr_hex_local_node_coordinates()
static Eigen::RowVector3d polyfem::basis::FEBasis3d::quadr_hex_local_node_coordinates (int local_index) static private
tet_face_local_nodes()
Eigen::VectorXi FEBasis3d::tet_face_local_nodes (const int p, const mesh::Mesh3D & mesh, mesh::Navigation3D::Index index) static
Definition at line 877 of file FEBasis3d.cpp.
References polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Mesh3D::get_index_from_element_edge(), polyfem::mesh::Mesh3D::get_index_from_element_face(), p_bases::indices, polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh3D::next_around_face(), p_bases::nn, p_bases::nodes, p_bases::norm, polyfem::autogen::p_nodes_3d(), p_bases::reverse, polyfem::mesh::Mesh3D::switch_vertex(), p_bases::tmp, and polyfem::mesh::Navigation3D::Index::vertex.
The documentation for this class was generated from the following files:
src/polyfem/basis/FEBasis3d.hpp
src/polyfem/basis/FEBasis3d.cpp