PolyFEM: polyfem::mesh::NCMesh3D Class Reference
polyfem::mesh::NCMesh3D Class Reference
#include <NCMesh3D.hpp>
Classes
struct ArrayHasher2D
struct ArrayHasher3D
struct follower_edge
struct follower_face
struct ncBoundary
struct ncElem
struct ncVert
Public Member Functions
NCMesh3D ()=default
virtual ~NCMesh3D ()=default
NCMesh3D (NCMesh3D &&)=default
NCMesh3D & operator= (NCMesh3D &&)=default
NCMesh3D (const NCMesh3D &)=default
NCMesh3D & operator= (const NCMesh3D &)=default
void refine (const int n_refinement, const double t) override
refine the mesh
bool is_conforming () const override
if the mesh is conforming
int n_cells () const override
number of cells
int n_faces () const override
number of faces
int n_edges () const override
number of edges
int n_vertices () const override
number of vertices
int n_face_vertices (const int f_id) const override
number of vertices of a face
int n_face_cells (const int f_id) const
int n_edge_cells (const int e_id) const
int n_cell_vertices (const int c_id) const override
int n_cell_edges (const int c_id) const override
int n_cell_faces (const int c_id) const override
int cell_vertex (const int f_id, const int lv_id) const override
id of the vertex of a cell
int cell_face (const int c_id, const int lf_id) const override
int cell_edge (const int c_id, const int le_id) const override
int face_vertex (const int f_id, const int lv_id) const override
id of the face vertex
int face_edge (const int f_id, const int le_id) const
int edge_vertex (const int e_id, const int lv_id) const override
id of the edge vertex
int cell_ref_level (const int c_id) const
bool is_boundary_vertex (const int vertex_global_id) const override
is vertex boundary
bool is_boundary_edge (const int edge_global_id) const override
is edge boundary
bool is_boundary_face (const int face_global_id) const override
is face boundary
bool is_boundary_element (const int element_global_id) const override
is cell boundary
bool build_from_matrices (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F) override
build a mesh from matrices
void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes) override
attach high order nodes
void normalize () override
normalize the mesh
void compute_elements_tag () override
compute element types, see ElementType
void update_elements_tag () override
Update elements types.
double edge_length (const int gid) const override
edge length
RowVectorNd point (const int global_index) const override
point coordinates
RowVectorNd edge_barycenter (const int e) const override
edge barycenter
RowVectorNd face_barycenter (const int f) const override
face barycenter
RowVectorNd cell_barycenter (const int c) const override
cell barycenter
void bounding_box (RowVectorNd &min, RowVectorNd &max) const override
computes the bbox of the mesh
void compute_boundary_ids (const double eps) override
computes the selection based on the bbx of the mesh.
void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker) override
computes boundary selections based on a function
void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void set_boundary_ids (const std::vector< int > &boundary_ids) override
Set the boundary selection from a vector.
void set_body_ids (const std::vector< int > &body_ids) override
Set the volume sections.
void set_body_ids (const Eigen::VectorXi &body_ids) override
Set the volume sections.
int get_boundary_id (const int primitive) const override
Get the boundary selection of an element (face in 3d, edge in 2d)
int get_body_id (const int primitive) const override
Get the volume selection of an element (cell in 3d, face in 2d)
void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const override
generate a triangular representation of every face
RowVectorNd kernel (const int cell_id) const override
Navigation3D::Index get_index_from_element (int hi, int lf, int lv) const override
Navigation3D::Index get_index_from_element (int hi) const override
Navigation3D::Index get_index_from_element_edge (int hi, int v0, int v1) const override
Navigation3D::Index get_index_from_element_face (int hi, int v0, int v1, int v2) const override
std::vector< uint32_t > vertex_neighs (const int v_gid) const override
std::vector< uint32_t > edge_neighs (const int e_gid) const override
int leader_edge_of_vertex (const int v_id) const
int leader_edge_of_edge (const int e_id) const
int leader_face_of_vertex (const int v_id) const
int leader_face_of_edge (const int e_id) const
int leader_face_of_face (const int f_id) const
int n_follower_edges (const int e_id) const
int n_follower_faces (const int e_id) const
Navigation3D::Index switch_vertex (Navigation3D::Index idx) const override
Navigation3D::Index switch_edge (Navigation3D::Index idx) const override
Navigation3D::Index switch_face (Navigation3D::Index idx) const override
Navigation3D::Index switch_element (Navigation3D::Index idx) const override
Navigation3D::Index next_around_edge (Navigation3D::Index idx) const override
Navigation3D::Index next_around_face (Navigation3D::Index idx) const override
void get_vertex_elements_neighs (const int v_id, std::vector< int > &ids) const override
void get_edge_elements_neighs (const int e_id, std::vector< int > &ids) const override
void get_face_elements_neighs (const int f_id, std::vector< int > &ids) const
void refine_element (int id_full)
void refine_elements (const std::vector< int > &ids)
void coarsen_element (int id_full)
void mark_boundary ()
void prepare_mesh () override
method used to finalize the mesh.
void build_index_mapping ()
std::array< int, 4 > get_ordered_vertices_from_tet (const int element_index) const override
Public Member Functions inherited from polyfem::mesh::Mesh3D
Mesh3D ()=default
virtual ~Mesh3D ()=default
Mesh3D (Mesh3D &&)=default
Mesh3D & operator= (Mesh3D &&)=default
Mesh3D (const Mesh3D &)=default
Mesh3D & operator= (const Mesh3D &)=default
bool is_volume () const override
checks if mesh is volume
virtual int n_cell_vertices (const int c_id) const =0
virtual int n_cell_edges (const int c_id) const =0
virtual int n_cell_faces (const int c_id) const =0
virtual int cell_face (const int c_id, const int lf_id) const =0
virtual int cell_edge (const int c_id, const int le_id) const =0
void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const override
constructs a box around every element (3d cell, 2d face)
void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const override
constructs barycentric coodiantes for a point p.
virtual RowVectorNd kernel (const int cell_id) const =0
double tri_area (const int gid) const override
area of a tri face of a tet mesh
RowVectorNd edge_node (const Navigation3D::Index &index, const int n_new_nodes, const int i) const
RowVectorNd face_node (const Navigation3D::Index &index, const int n_new_nodes, const int i, const int j) const
RowVectorNd cell_node (const Navigation3D::Index &index, const int n_new_nodes, const int i, const int j, const int k) const
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const override
Get all the edges.
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const override
Get all the edges according to valid_elements selection.
virtual Navigation3D::Index get_index_from_element (int hi, int lf, int lv) const =0
virtual Navigation3D::Index get_index_from_element (int hi) const =0
virtual Navigation3D::Index get_index_from_element_edge (int hi, int v0, int v1) const =0
virtual Navigation3D::Index get_index_from_element_face (int hi, int v0, int v1, int v2) const =0
virtual std::vector< uint32_t > vertex_neighs (const int v_gid) const =0
virtual std::vector< uint32_t > edge_neighs (const int e_gid) const =0
virtual Navigation3D::Index switch_vertex (Navigation3D::Index idx) const =0
virtual Navigation3D::Index switch_edge (Navigation3D::Index idx) const =0
virtual Navigation3D::Index switch_face (Navigation3D::Index idx) const =0
virtual Navigation3D::Index switch_element (Navigation3D::Index idx) const =0
virtual Navigation3D::Index next_around_edge (Navigation3D::Index idx) const =0
virtual Navigation3D::Index next_around_face (Navigation3D::Index idx) const =0
void to_face_functions (std::array< std::function< Navigation3D::Index(Navigation3D::Index)>, 6 > &to_face) const
void to_vertex_functions (std::array< std::function< Navigation3D::Index(Navigation3D::Index)>, 8 > &to_vertex) const
void to_edge_functions (std::array< std::function< Navigation3D::Index(Navigation3D::Index)>, 12 > &to_edge) const
std::array< int, 8 > get_ordered_vertices_from_hex (const int element_index) const
virtual std::array< int, 4 > get_ordered_vertices_from_tet (const int element_index) const
virtual void get_vertex_elements_neighs (const int v_id, std::vector< int > &ids) const =0
virtual void get_edge_elements_neighs (const int e_id, std::vector< int > &ids) const =0
void compute_element_barycenters (Eigen::MatrixXd &barycenters) const override
utility for 2d/3d.
Public Member Functions inherited from polyfem::mesh::Mesh
virtual ~Mesh ()=default
Destroy the Mesh object.
Mesh (Mesh &&)=default
Construct a new Mesh object.
Mesh & operator= (Mesh &&)=default
Copy constructor.
Mesh (const Mesh &)=default
Construct a new Mesh object.
Mesh & operator= (const Mesh &)=default
virtual void refine (const int n_refinement, const double t)=0
refine the mesh
virtual bool is_volume () const =0
checks if mesh is volume
int dimension () const
utily for dimension
virtual bool is_conforming () const =0
if the mesh is conforming
int n_elements () const
utitlity to return the number of elements, cells or faces in 3d and 2d
virtual int n_cells () const =0
number of cells
virtual int n_faces () const =0
number of faces
virtual int n_edges () const =0
number of edges
virtual int n_vertices () const =0
number of vertices
virtual int n_face_vertices (const int f_id) const =0
number of vertices of a face
virtual int face_vertex (const int f_id, const int lv_id) const =0
id of the face vertex
virtual int edge_vertex (const int e_id, const int lv_id) const =0
id of the edge vertex
virtual int cell_vertex (const int f_id, const int lv_id) const =0
id of the vertex of a cell
virtual bool is_boundary_vertex (const int vertex_global_id) const =0
is vertex boundary
virtual bool is_boundary_edge (const int edge_global_id) const =0
is edge boundary
virtual bool is_boundary_face (const int face_global_id) const =0
is face boundary
virtual bool is_boundary_element (const int element_global_id) const =0
is cell boundary
virtual void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes)=0
attach high order nodes
const Eigen::MatrixXi & orders () const
order of each element
bool is_rational () const
check if curved mesh has rational polynomials elements
void set_is_rational (const bool in_is_rational)
Set the is rational object.
virtual void normalize ()=0
normalize the mesh
virtual void compute_elements_tag ()=0
compute element types, see ElementType
virtual void update_elements_tag ()
Update elements types.
virtual double edge_length (const int gid) const
edge length
virtual double quad_area (const int gid) const
area of a quad face of an hex mesh
virtual double tri_area (const int gid) const
area of a tri face of a tet mesh
virtual RowVectorNd point (const int global_index) const =0
point coordinates
virtual RowVectorNd edge_barycenter (const int e) const =0
edge barycenter
virtual RowVectorNd face_barycenter (const int f) const =0
face barycenter
virtual RowVectorNd cell_barycenter (const int c) const =0
cell barycenter
void edge_barycenters (Eigen::MatrixXd &barycenters) const
all edges barycenters
void face_barycenters (Eigen::MatrixXd &barycenters) const
all face barycenters
void cell_barycenters (Eigen::MatrixXd &barycenters) const
all cells barycenters
virtual void compute_element_barycenters (Eigen::MatrixXd &barycenters) const =0
utility for 2d/3d.
virtual void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const =0
constructs a box around every element (3d cell, 2d face)
virtual void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const =0
constructs barycentric coodiantes for a point p.
virtual void bounding_box (RowVectorNd &min, RowVectorNd &max) const =0
computes the bbox of the mesh
bool is_spline_compatible (const int el_id) const
checks if element is spline compatible
bool is_cube (const int el_id) const
checks if element is cube compatible
bool is_polytope (const int el_id) const
checks if element is polygon compatible
bool is_simplex (const int el_id) const
checks if element is simples compatible
const std::vector< ElementType > & elements_tag () const
Returns the elements types.
void set_tag (const int el, const ElementType type)
changes the element type
virtual void load_boundary_ids (const std::string &path)
loads the boundary selections for a file
virtual void compute_boundary_ids (const double eps)=0
computes the selection based on the bbx of the mesh.
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void set_boundary_ids (const std::vector< int > &boundary_ids)
Set the boundary selection from a vector.
virtual void set_body_ids (const std::vector< int > &body_ids)
Set the volume sections.
virtual void set_body_ids (const Eigen::VectorXi &body_ids)
Set the volume sections.
virtual int get_boundary_id (const int primitive) const
Get the boundary selection of an element (face in 3d, edge in 2d)
virtual int get_body_id (const int primitive) const
Get the volume selection of an element (cell in 3d, face in 2d)
bool has_boundary_ids () const
checks if surface selections are available
virtual bool has_body_ids () const
checks if volumes selections are available
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const =0
Get all the edges.
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const =0
Get all the edges according to valid_elements selection.
virtual void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const =0
generate a triangular representation of every face
const std::vector< double > & cell_weights (const int cell_index) const
weights for rational polynomial meshes
void set_cell_weights (const std::vector< std::vector< double > > &in_cell_weights)
Set the cell weights for rational polynomial meshes.
virtual void prepare_mesh ()
method used to finalize the mesh.
bool has_poly () const
checks if the mesh has polytopes
bool is_linear ()
check if the mesh is linear
std::vector< std::pair< int, int > > edges () const
list of sorted edges.
std::vector< std::vector< int > > faces () const
list of sorted faces.
std::unordered_map< std::pair< int, int >, size_t, polyfem::utils::HashPair > edges_to_ids () const
map from edge (pair of v id) to the id of the edge
std::unordered_map< std::vector< int >, size_t, polyfem::utils::HashVector > faces_to_ids () const
map from face (tuple of v id) to the id of the face
const Eigen::VectorXi & in_ordered_vertices () const
Order of the input vertices.
const Eigen::MatrixXi & in_ordered_edges () const
Order of the input edges.
const Eigen::MatrixXi & in_ordered_faces () const
Order of the input edges.
Protected Member Functions
bool load (const std::string &path) override
loads a mesh from the path
bool load (const GEO::Mesh &M) override
loads a mesh from a geo mesh
int all_to_valid_vertex (const int id) const
int valid_to_all_vertex (const int id) const
int all_to_valid_edge (const int id) const
int valid_to_all_edge (const int id) const
int all_to_valid_face (const int id) const
int valid_to_all_face (const int id) const
int all_to_valid_elem (const int id) const
int valid_to_all_elem (const int id) const
int find_vertex (Eigen::Vector2i v) const
int find_vertex (const int v1, const int v2) const
int get_vertex (Eigen::Vector2i v)
int find_edge (Eigen::Vector2i v) const
int find_edge (const int v1, const int v2) const
int get_edge (Eigen::Vector2i v)
int get_edge (const int v1, const int v2)
int find_face (Eigen::Vector3i v) const
int find_face (const int v1, const int v2, const int v3) const
int get_face (Eigen::Vector3i v)
int get_face (const int v1, const int v2, const int v3)
void traverse_edge (Eigen::Vector2i v, double p1, double p2, int depth, std::vector< follower_edge > &list) const
void build_edge_follower_chain ()
void traverse_face (int v1, int v2, int v3, Eigen::Vector2d p1, Eigen::Vector2d p2, Eigen::Vector2d p3, int depth, std::vector< follower_face > &face_list, std::vector< int > &edge_list) const
void build_face_follower_chain ()
void build_element_vertex_adjacency ()
int add_element (Eigen::Vector4i v, int parent=-1)
Protected Member Functions inherited from polyfem::mesh::Mesh
Mesh ()=default
Construct a new Mesh object.
virtual bool load (const std::string &path)=0
loads a mesh from the path
virtual bool load (const GEO::Mesh &M)=0
loads a mesh from a geo mesh
Protected Attributes
int n_elements = 0
bool index_prepared = false
bool adj_prepared = false
std::vector< ncElem > elements
std::vector< ncVert > vertices
std::vector< ncBoundary > edges
std::vector< ncBoundary > faces
std::unordered_map< Eigen::Vector2i, int, ArrayHasher2D > midpointMap
std::unordered_map< Eigen::Vector2i, int, ArrayHasher2D > edgeMap
std::unordered_map< Eigen::Vector3i, int, ArrayHasher3D > faceMap
std::vector< int > all_to_valid_elemMap
std::vector< int > valid_to_all_elemMap
std::vector< int > all_to_valid_vertexMap
std::vector< int > valid_to_all_vertexMap
std::vector< int > all_to_valid_edgeMap
std::vector< int > valid_to_all_edgeMap
std::vector< int > all_to_valid_faceMap
std::vector< int > valid_to_all_faceMap
std::vector< int > refineHistory
Eigen::SparseMatrix< bool, Eigen::RowMajor > elementAdj
Protected Attributes inherited from polyfem::mesh::Mesh
std::vector< ElementType > elements_tag_
list of element types
std::vector< int > boundary_ids_
list of surface labels
std::vector< int > body_ids_
list of volume labels
Eigen::MatrixXi orders_
list of geometry orders, one per cell
bool is_rational_ = false
stores if the mesh is rational
std::vector< EdgeNodes > edge_nodes_
high-oder nodes associates to edges
std::vector< FaceNodes > face_nodes_
high-oder nodes associates to faces
std::vector< CellNodes > cell_nodes_
high-oder nodes associates to cells
std::vector< std::vector< double > > cell_weights_
weights associates to cells for rational polynomail meshes
Eigen::VectorXi in_ordered_vertices_
Order of the input vertices.
Eigen::MatrixXi in_ordered_edges_
Order of the input edges.
Eigen::MatrixXi in_ordered_faces_
Order of the input faces, TODO: change to std::vector of Eigen::Vector.
Additional Inherited Members
Static Public Member Functions inherited from polyfem::mesh::Mesh
static std::unique_ptr< Mesh > create (const std::string &path, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (GEO::Mesh &M, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (const Eigen::MatrixXd &vertices, const Eigen::MatrixXi &cells, const bool non_conforming=false)
factory to build the proper mesh
Detailed Description
Definition at line 11 of file NCMesh3D.hpp.
Constructor & Destructor Documentation
NCMesh3D() [1/3]
polyfem::mesh::NCMesh3D::NCMesh3D () default
~NCMesh3D()
virtual polyfem::mesh::NCMesh3D::~NCMesh3D () virtual default
NCMesh3D() [2/3]
polyfem::mesh::NCMesh3D::NCMesh3D (NCMesh3D &&) default
NCMesh3D() [3/3]
polyfem::mesh::NCMesh3D::NCMesh3D (const NCMesh3D &) default
Member Function Documentation
add_element()
int polyfem::mesh::NCMesh3D::add_element (Eigen::Vector4i v, int parent = -1) protected
Definition at line 1174 of file NCMesh3D.cpp.
References add_element(), edges, elements, faces, get_edge(), get_face(), n_elements, and vertices.
Referenced by add_element(), build_from_matrices(), load(), and refine_element().
all_to_valid_edge()
int polyfem::mesh::NCMesh3D::all_to_valid_edge (const int id) const inline protected
Definition at line 390 of file NCMesh3D.hpp.
References all_to_valid_edgeMap, and index_prepared.
Referenced by cell_edge(), face_edge(), get_index_from_element_edge(), leader_edge_of_edge(), and leader_edge_of_vertex().
all_to_valid_elem()
int polyfem::mesh::NCMesh3D::all_to_valid_elem (const int id) const inline protected
Definition at line 414 of file NCMesh3D.hpp.
References all_to_valid_elemMap, and index_prepared.
Referenced by edge_neighs(), get_edge_elements_neighs(), get_face_elements_neighs(), get_vertex_elements_neighs(), switch_element(), and vertex_neighs().
all_to_valid_face()
int polyfem::mesh::NCMesh3D::all_to_valid_face (const int id) const inline protected
Definition at line 402 of file NCMesh3D.hpp.
References all_to_valid_faceMap, and index_prepared.
Referenced by cell_face(), get_index_from_element_face(), leader_face_of_edge(), leader_face_of_face(), and leader_face_of_vertex().
all_to_valid_vertex()
int polyfem::mesh::NCMesh3D::all_to_valid_vertex (const int id) const inline protected
Definition at line 378 of file NCMesh3D.hpp.
References all_to_valid_vertexMap, and index_prepared.
Referenced by cell_vertex(), edge_vertex(), and face_vertex().
attach_higher_order_nodes()
void polyfem::mesh::NCMesh3D::attach_higher_order_nodes (const Eigen::MatrixXd & V, const std::vector< std::vector< int > > & nodes) override virtual
attach high order nodes
Parameters
[in] V nodes
[in] nodes list of nodes per element
Implements polyfem::mesh::Mesh.
Definition at line 80 of file NCMesh3D.cpp.
References elasticity_rhs::f, n_cells(), and p_bases::nodes.
bounding_box()
void polyfem::mesh::NCMesh3D::bounding_box (RowVectorNd & min, RowVectorNd & max) const override virtual
computes the bbox of the mesh
Parameters
[out] min min coodiante
[out] max max coodiante
Implements polyfem::mesh::Mesh.
Definition at line 144 of file NCMesh3D.cpp.
Referenced by compute_boundary_ids().
build_edge_follower_chain()
void polyfem::mesh::NCMesh3D::build_edge_follower_chain () protected
Definition at line 1013 of file NCMesh3D.cpp.
References edges, and traverse_edge().
Referenced by prepare_mesh().
build_element_vertex_adjacency()
void polyfem::mesh::NCMesh3D::build_element_vertex_adjacency () protected
Definition at line 1119 of file NCMesh3D.cpp.
References edges, faces, and vertices.
Referenced by prepare_mesh().
build_face_follower_chain()
void polyfem::mesh::NCMesh3D::build_face_follower_chain () protected
Definition at line 1082 of file NCMesh3D.cpp.
References edges, faces, and traverse_face().
Referenced by prepare_mesh().
build_from_matrices()
bool polyfem::mesh::NCMesh3D::build_from_matrices (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F) override virtual
build a mesh from matrices
Parameters
[in] V vertices
[in] F connectivity
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 52 of file NCMesh3D.cpp.
References add_element(), adj_prepared, edgeMap, edges, elements, faceMap, index_prepared, midpointMap, n_elements, prepare_mesh(), refineHistory, and vertices.
build_index_mapping()
void polyfem::mesh::NCMesh3D::build_index_mapping ()
Definition at line 826 of file NCMesh3D.cpp.
References all_to_valid_edgeMap, all_to_valid_elemMap, all_to_valid_faceMap, all_to_valid_vertexMap, edges, elements, faces, index_prepared, n_edges(), n_elements, n_faces(), n_vertices(), valid_to_all_edgeMap, valid_to_all_elemMap, valid_to_all_faceMap, valid_to_all_vertexMap, and vertices.
Referenced by prepare_mesh().
cell_barycenter()
RowVectorNd polyfem::mesh::NCMesh3D::cell_barycenter (const int c) const override virtual
cell barycenter
Parameters
[in] c global cell index
Returns
cell barycenter
Implements polyfem::mesh::Mesh.
Definition at line 135 of file NCMesh3D.cpp.
References face_vertex(), and point().
Referenced by compute_body_ids().
cell_edge()
int polyfem::mesh::NCMesh3D::cell_edge (const int c_id, const int le_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 222 of file NCMesh3D.hpp.
References all_to_valid_edge(), edges, elements, and valid_to_all_elem().
cell_face()
int polyfem::mesh::NCMesh3D::cell_face (const int c_id, const int lf_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 221 of file NCMesh3D.hpp.
References all_to_valid_face(), elements, faces, and valid_to_all_elem().
Referenced by get_index_from_element(), get_index_from_element_edge(), get_index_from_element_face(), switch_element(), switch_face(), and triangulate_faces().
cell_ref_level()
int polyfem::mesh::NCMesh3D::cell_ref_level (const int c_id) const inline
Definition at line 227 of file NCMesh3D.hpp.
References elements, and valid_to_all_elem().
cell_vertex()
int polyfem::mesh::NCMesh3D::cell_vertex (const int f_id, const int lv_id) const inline override virtual
id of the vertex of a cell
Parameters
[in] f_id global cell id
[in] lv_id local vertex id
Returns
vertex id
Implements polyfem::mesh::Mesh.
Definition at line 220 of file NCMesh3D.hpp.
References all_to_valid_vertex(), elements, valid_to_all_elem(), and vertices.
Referenced by get_ordered_vertices_from_tet(), is_boundary_element(), and triangulate_faces().
coarsen_element()
void polyfem::mesh::NCMesh3D::coarsen_element (int id_full)
Definition at line 735 of file NCMesh3D.cpp.
References edges, elements, elasticity_rhs::f, faces, n_elements, refineHistory, and vertices.
compute_body_ids()
void polyfem::mesh::NCMesh3D::compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id and barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 257 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::body_ids_, cell_barycenter(), elements, n_cells(), and valid_to_all_elem().
compute_boundary_ids() [1/5]
void polyfem::mesh::NCMesh3D::compute_boundary_ids (const double eps) override virtual
computes the selection based on the bbx of the mesh.
Left gets 1, bottom 2, right 3, top 4, front 5, back 6
Parameters
[in] eps tolerance for proximity
Implements polyfem::mesh::Mesh.
Definition at line 161 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, bounding_box(), elasticity_rhs::f, face_barycenter(), faces, is_boundary_face(), n_faces(), and valid_to_all_face().
compute_boundary_ids() [2/5]
void polyfem::mesh::NCMesh3D::compute_boundary_ids (const std::function< int(const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 195 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_barycenter(), faces, is_boundary_face(), n_faces(), and valid_to_all_face().
compute_boundary_ids() [3/5]
void polyfem::mesh::NCMesh3D::compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 211 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_barycenter(), faces, is_boundary_face(), n_faces(), and valid_to_all_face().
compute_boundary_ids() [4/5]
void polyfem::mesh::NCMesh3D::compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id, barycenter, and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 225 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_barycenter(), faces, is_boundary_face(), n_faces(), and valid_to_all_face().
compute_boundary_ids() [5/5]
void polyfem::mesh::NCMesh3D::compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the list of vertices and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 239 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_vertex(), faces, is_boundary_face(), n_face_vertices(), n_faces(), and valid_to_all_face().
compute_elements_tag()
void polyfem::mesh::NCMesh3D::compute_elements_tag () override virtual
compute element types, see ElementType
Implements polyfem::mesh::Mesh.
Definition at line 99 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::elements_tag_, n_cells(), and polyfem::mesh::Simplex.
Referenced by prepare_mesh().
edge_barycenter()
RowVectorNd polyfem::mesh::NCMesh3D::edge_barycenter (const int e) const override virtual
edge barycenter
Parameters
[in] e global edge index
Returns
edge barycenter
Implements polyfem::mesh::Mesh.
Definition at line 120 of file NCMesh3D.cpp.
References edge_vertex(), and point().
edge_length()
double polyfem::mesh::NCMesh3D::edge_length (const int gid) const override virtual
edge length
Parameters
[in] gid global edge id
Returns
edge length
Reimplemented from polyfem::mesh::Mesh.
Definition at line 107 of file NCMesh3D.cpp.
References edge_vertex(), and point().
edge_neighs()
std::vector< uint32_t > polyfem::mesh::NCMesh3D::edge_neighs (const int e_gid) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 524 of file NCMesh3D.cpp.
References all_to_valid_elem(), edges, and valid_to_all_edge().
edge_vertex()
int polyfem::mesh::NCMesh3D::edge_vertex (const int e_id, const int lv_id) const inline override virtual
id of the edge vertex
Parameters
[in] e_id global edge id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 225 of file NCMesh3D.hpp.
References all_to_valid_vertex(), edges, valid_to_all_edge(), and vertices.
Referenced by edge_barycenter(), edge_length(), get_index_from_element_face(), and switch_vertex().
face_barycenter()
RowVectorNd polyfem::mesh::NCMesh3D::face_barycenter (const int f) const override virtual
face barycenter
Parameters
[in] f global face index
Returns
face barycenter
Implements polyfem::mesh::Mesh.
Definition at line 127 of file NCMesh3D.cpp.
References elasticity_rhs::f, face_vertex(), and point().
Referenced by compute_boundary_ids().
face_edge()
int polyfem::mesh::NCMesh3D::face_edge (const int f_id, const int le_id) const
Definition at line 18 of file NCMesh3D.cpp.
References all_to_valid_edge(), faces, find_edge(), and valid_to_all_face().
Referenced by get_index_from_element(), get_index_from_element_edge(), get_index_from_element_face(), switch_edge(), and switch_face().
face_vertex()
int polyfem::mesh::NCMesh3D::face_vertex (const int f_id, const int lv_id) const inline override virtual
id of the face vertex
Parameters
[in] f_id global face id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 223 of file NCMesh3D.hpp.
References all_to_valid_vertex(), faces, valid_to_all_face(), and vertices.
Referenced by cell_barycenter(), compute_boundary_ids(), face_barycenter(), get_index_from_element(), get_index_from_element_edge(), get_index_from_element_face(), switch_face(), switch_vertex(), and triangulate_faces().
find_edge() [1/2]
int polyfem::mesh::NCMesh3D::find_edge (const int v1, const int v2) const inline protected
Definition at line 434 of file NCMesh3D.hpp.
References find_edge().
Referenced by find_edge().
find_edge() [2/2]
int polyfem::mesh::NCMesh3D::find_edge (Eigen::Vector2i v) const protected
Definition at line 946 of file NCMesh3D.cpp.
References edgeMap.
Referenced by face_edge(), get_edge(), get_index_from_element_edge(), mark_boundary(), refine_element(), traverse_edge(), and traverse_face().
find_face() [1/2]
int polyfem::mesh::NCMesh3D::find_face (const int v1, const int v2, const int v3) const inline protected
Definition at line 442 of file NCMesh3D.hpp.
References find_face().
Referenced by find_face().
find_face() [2/2]
int polyfem::mesh::NCMesh3D::find_face (Eigen::Vector3i v) const protected
Definition at line 967 of file NCMesh3D.cpp.
References faceMap.
Referenced by get_face(), get_index_from_element_face(), refine_element(), and traverse_face().
find_vertex() [1/2]
int polyfem::mesh::NCMesh3D::find_vertex (const int v1, const int v2) const inline protected
Definition at line 427 of file NCMesh3D.hpp.
References find_vertex().
Referenced by find_vertex().
find_vertex() [2/2]
int polyfem::mesh::NCMesh3D::find_vertex (Eigen::Vector2i v) const protected
Definition at line 924 of file NCMesh3D.cpp.
References midpointMap.
Referenced by get_vertex(), refine_element(), traverse_edge(), and traverse_face().
get_body_id()
int polyfem::mesh::NCMesh3D::get_body_id (const int primitive) const inline override virtual
Get the volume selection of an element (cell in 3d, face in 2d)
Parameters
[in] primitive element id
Returns
label of element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 263 of file NCMesh3D.hpp.
References elements, and valid_to_all_elem().
get_boundary_id()
int polyfem::mesh::NCMesh3D::get_boundary_id (const int primitive) const inline override virtual
Get the boundary selection of an element (face in 3d, edge in 2d)
Parameters
[in] primitive element id
Returns
label of element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 262 of file NCMesh3D.hpp.
References faces, and valid_to_all_face().
get_edge() [1/2]
int polyfem::mesh::NCMesh3D::get_edge (const int v1, const int v2) inline protected
Definition at line 438 of file NCMesh3D.hpp.
References get_edge().
Referenced by get_edge().
get_edge() [2/2]
int polyfem::mesh::NCMesh3D::get_edge (Eigen::Vector2i v) protected
Definition at line 955 of file NCMesh3D.cpp.
References edgeMap, edges, and find_edge().
Referenced by add_element(), and refine_element().
get_edge_elements_neighs()
void polyfem::mesh::NCMesh3D::get_edge_elements_neighs (const int e_id, std::vector< int > & ids) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 609 of file NCMesh3D.cpp.
References all_to_valid_elem(), edges, and valid_to_all_edge().
get_face() [1/2]
int polyfem::mesh::NCMesh3D::get_face (const int v1, const int v2, const int v3) inline protected
Definition at line 445 of file NCMesh3D.hpp.
References get_face().
Referenced by get_face().
get_face() [2/2]
int polyfem::mesh::NCMesh3D::get_face (Eigen::Vector3i v) protected
Definition at line 976 of file NCMesh3D.cpp.
References faceMap, faces, and find_face().
Referenced by add_element(), and refine_element().
get_face_elements_neighs()
void polyfem::mesh::NCMesh3D::get_face_elements_neighs (const int f_id, std::vector< int > & ids) const
Definition at line 615 of file NCMesh3D.cpp.
References all_to_valid_elem(), faces, and valid_to_all_face().
get_index_from_element() [1/2]
Navigation3D::Index polyfem::mesh::NCMesh3D::get_index_from_element (int hi) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 421 of file NCMesh3D.cpp.
References cell_face(), polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, face_edge(), face_vertex(), and polyfem::mesh::Navigation3D::Index::vertex.
get_index_from_element() [2/2]
Navigation3D::Index polyfem::mesh::NCMesh3D::get_index_from_element (int hi, int lf, int lv) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 403 of file NCMesh3D.cpp.
References cell_face(), polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, face_edge(), face_vertex(), and polyfem::mesh::Navigation3D::Index::vertex.
get_index_from_element_edge()
Navigation3D::Index polyfem::mesh::NCMesh3D::get_index_from_element_edge (int hi, int v0, int v1) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 435 of file NCMesh3D.cpp.
References all_to_valid_edge(), cell_face(), polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, face_edge(), face_vertex(), find_edge(), n_face_vertices(), switch_vertex(), valid_to_all_vertex(), and polyfem::mesh::Navigation3D::Index::vertex.
get_index_from_element_face()
Navigation3D::Index polyfem::mesh::NCMesh3D::get_index_from_element_face (int hi, int v0, int v1, int v2) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 468 of file NCMesh3D.cpp.
References all_to_valid_face(), cell_face(), polyfem::mesh::Navigation3D::Index::edge, edge_vertex(), polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, face_edge(), face_vertex(), find_face(), n_face_vertices(), switch_edge(), switch_vertex(), valid_to_all_vertex(), and polyfem::mesh::Navigation3D::Index::vertex.
get_ordered_vertices_from_tet()
std::array< int, 4 > polyfem::mesh::NCMesh3D::get_ordered_vertices_from_tet (const int element_index) const override virtual
Reimplemented from polyfem::mesh::Mesh3D.
Definition at line 1170 of file NCMesh3D.cpp.
References cell_vertex().
get_vertex()
int polyfem::mesh::NCMesh3D::get_vertex (Eigen::Vector2i v) protected
Definition at line 933 of file NCMesh3D.cpp.
References find_vertex(), midpointMap, and vertices.
Referenced by refine_element().
get_vertex_elements_neighs()
void polyfem::mesh::NCMesh3D::get_vertex_elements_neighs (const int v_id, std::vector< int > & ids) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 603 of file NCMesh3D.cpp.
References all_to_valid_elem(), valid_to_all_vertex(), and vertices.
is_boundary_edge()
bool polyfem::mesh::NCMesh3D::is_boundary_edge (const int edge_global_id) const inline override virtual
is edge boundary
Parameters
[in] edge_global_id global edge id
Returns
is edge boundary
Implements polyfem::mesh::Mesh.
Definition at line 230 of file NCMesh3D.hpp.
References edges, and valid_to_all_edge().
is_boundary_element()
bool polyfem::mesh::NCMesh3D::is_boundary_element (const int element_global_id) const override virtual
is cell boundary
Parameters
[in] element_global_id global cell id
Returns
is cell boundary
Implements polyfem::mesh::Mesh.
Definition at line 42 of file NCMesh3D.cpp.
References cell_vertex(), index_prepared, is_boundary_vertex(), and n_cell_edges().
is_boundary_face()
bool polyfem::mesh::NCMesh3D::is_boundary_face (const int face_global_id) const inline override virtual
is face boundary
Parameters
[in] face_global_id global face id
Returns
is face boundary
Implements polyfem::mesh::Mesh.
Definition at line 231 of file NCMesh3D.hpp.
References faces, and valid_to_all_face().
Referenced by compute_boundary_ids().
is_boundary_vertex()
bool polyfem::mesh::NCMesh3D::is_boundary_vertex (const int vertex_global_id) const inline override virtual
is vertex boundary
Parameters
[in] vertex_global_id global vertex id
Returns
is vertex boundary
Implements polyfem::mesh::Mesh.
Definition at line 229 of file NCMesh3D.hpp.
References valid_to_all_vertex(), and vertices.
Referenced by is_boundary_element().
is_conforming()
bool polyfem::mesh::NCMesh3D::is_conforming () const inline override virtual
if the mesh is conforming
Returns
if the mesh is conforming
Implements polyfem::mesh::Mesh.
Definition at line 186 of file NCMesh3D.hpp.
kernel()
RowVectorNd polyfem::mesh::NCMesh3D::kernel (const int cell_id) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 398 of file NCMesh3D.cpp.
leader_edge_of_edge()
int polyfem::mesh::NCMesh3D::leader_edge_of_edge (const int e_id) const inline
Definition at line 283 of file NCMesh3D.hpp.
References adj_prepared, all_to_valid_edge(), edges, and valid_to_all_edge().
leader_edge_of_vertex()
int polyfem::mesh::NCMesh3D::leader_edge_of_vertex (const int v_id) const inline
Definition at line 278 of file NCMesh3D.hpp.
References adj_prepared, all_to_valid_edge(), valid_to_all_vertex(), and vertices.
leader_face_of_edge()
int polyfem::mesh::NCMesh3D::leader_face_of_edge (const int e_id) const inline
Definition at line 295 of file NCMesh3D.hpp.
References adj_prepared, all_to_valid_face(), edges, and valid_to_all_edge().
leader_face_of_face()
int polyfem::mesh::NCMesh3D::leader_face_of_face (const int f_id) const inline
Definition at line 301 of file NCMesh3D.hpp.
References adj_prepared, all_to_valid_face(), faces, and valid_to_all_face().
leader_face_of_vertex()
int polyfem::mesh::NCMesh3D::leader_face_of_vertex (const int v_id) const inline
Definition at line 289 of file NCMesh3D.hpp.
References adj_prepared, all_to_valid_face(), valid_to_all_vertex(), and vertices.
load() [1/2]
bool polyfem::mesh::NCMesh3D::load (const GEO::Mesh & M) override protected virtual
loads a mesh from a geo mesh
Parameters
[in] M geo mesh
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 890 of file NCMesh3D.cpp.
References add_element(), eigs::M, n_elements, prepare_mesh(), and vertices.
load() [2/2]
bool polyfem::mesh::NCMesh3D::load (const std::string & path) override protected virtual
loads a mesh from the path
Parameters
[in] path file location
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 880 of file NCMesh3D.cpp.
References polyfem::utils::StringUtils::endswith(), load(), eigs::M, and eigs::path.
Referenced by load().
mark_boundary()
void polyfem::mesh::NCMesh3D::mark_boundary ()
Definition at line 777 of file NCMesh3D.cpp.
References edges, faces, find_edge(), and vertices.
Referenced by prepare_mesh().
n_cell_edges()
int polyfem::mesh::NCMesh3D::n_cell_edges (const int c_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 218 of file NCMesh3D.hpp.
Referenced by is_boundary_element().
n_cell_faces()
int polyfem::mesh::NCMesh3D::n_cell_faces (const int c_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 219 of file NCMesh3D.hpp.
Referenced by switch_element(), and triangulate_faces().
n_cell_vertices()
int polyfem::mesh::NCMesh3D::n_cell_vertices (const int c_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 217 of file NCMesh3D.hpp.
Referenced by triangulate_faces().
n_cells()
int polyfem::mesh::NCMesh3D::n_cells () const inline override virtual
number of cells
Returns
number of cells
Implements polyfem::mesh::Mesh.
Definition at line 188 of file NCMesh3D.hpp.
References n_elements.
Referenced by attach_higher_order_nodes(), compute_body_ids(), compute_elements_tag(), set_body_ids(), triangulate_faces(), and update_elements_tag().
n_edge_cells()
int polyfem::mesh::NCMesh3D::n_edge_cells (const int e_id) const inline
Definition at line 216 of file NCMesh3D.hpp.
References edges, and valid_to_all_edge().
n_edges()
int polyfem::mesh::NCMesh3D::n_edges () const inline override virtual
number of edges
Returns
number of edges
Implements polyfem::mesh::Mesh.
Definition at line 197 of file NCMesh3D.hpp.
References edges.
Referenced by build_index_mapping().
n_face_cells()
int polyfem::mesh::NCMesh3D::n_face_cells (const int f_id) const inline
Definition at line 215 of file NCMesh3D.hpp.
References faces, and valid_to_all_face().
n_face_vertices()
int polyfem::mesh::NCMesh3D::n_face_vertices (const int f_id) const inline override virtual
number of vertices of a face
Parameters
[in] f_id global face id
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 214 of file NCMesh3D.hpp.
Referenced by compute_boundary_ids(), get_index_from_element_edge(), get_index_from_element_face(), switch_face(), switch_vertex(), and triangulate_faces().
n_faces()
int polyfem::mesh::NCMesh3D::n_faces () const inline override virtual
number of faces
Returns
number of faces
Implements polyfem::mesh::Mesh.
Definition at line 189 of file NCMesh3D.hpp.
References faces.
Referenced by build_index_mapping(), compute_boundary_ids(), set_boundary_ids(), and triangulate_faces().
n_follower_edges()
int polyfem::mesh::NCMesh3D::n_follower_edges (const int e_id) const inline
Definition at line 309 of file NCMesh3D.hpp.
References adj_prepared, edges, and valid_to_all_edge().
n_follower_faces()
int polyfem::mesh::NCMesh3D::n_follower_faces (const int e_id) const inline
Definition at line 314 of file NCMesh3D.hpp.
References adj_prepared, faces, and valid_to_all_face().
n_vertices()
int polyfem::mesh::NCMesh3D::n_vertices () const inline override virtual
number of vertices
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 205 of file NCMesh3D.hpp.
References vertices.
Referenced by build_index_mapping(), and triangulate_faces().
next_around_edge()
Navigation3D::Index polyfem::mesh::NCMesh3D::next_around_edge (Navigation3D::Index idx) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 594 of file NCMesh3D.cpp.
References switch_element(), and switch_face().
next_around_face()
Navigation3D::Index polyfem::mesh::NCMesh3D::next_around_face (Navigation3D::Index idx) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 598 of file NCMesh3D.cpp.
References switch_edge(), and switch_vertex().
normalize()
void polyfem::mesh::NCMesh3D::normalize () override virtual
normalize the mesh
Implements polyfem::mesh::Mesh.
Definition at line 87 of file NCMesh3D.cpp.
operator=() [1/2]
NCMesh3D & polyfem::mesh::NCMesh3D::operator= (const NCMesh3D &) default
operator=() [2/2]
NCMesh3D & polyfem::mesh::NCMesh3D::operator= (NCMesh3D &&) default
point()
RowVectorNd polyfem::mesh::NCMesh3D::point (const int global_index) const override virtual
point coordinates
Parameters
[in] global_index global vertex index
Returns
RowVectorNd
Implements polyfem::mesh::Mesh.
Definition at line 115 of file NCMesh3D.cpp.
References valid_to_all_vertex(), and vertices.
Referenced by cell_barycenter(), edge_barycenter(), edge_length(), face_barycenter(), and triangulate_faces().
prepare_mesh()
void polyfem::mesh::NCMesh3D::prepare_mesh () inline override virtual
method used to finalize the mesh.
It computes the cached stuff used in navigation
Reimplemented from polyfem::mesh::Mesh.
Definition at line 341 of file NCMesh3D.hpp.
References adj_prepared, build_edge_follower_chain(), build_element_vertex_adjacency(), build_face_follower_chain(), build_index_mapping(), compute_elements_tag(), and mark_boundary().
Referenced by build_from_matrices(), and load().
refine()
void polyfem::mesh::NCMesh3D::refine (const int n_refinement, const double t) override virtual
refine the mesh
Parameters
[in] n_refinement number of refinements
[in] t position of the refinement location (0.5 for standard refinement)
Implements polyfem::mesh::Mesh.
Definition at line 26 of file NCMesh3D.cpp.
References elements, tetrahedron::is_valid(), refine(), and refine_element().
Referenced by refine().
refine_element()
void polyfem::mesh::NCMesh3D::refine_element (int id_full)
Definition at line 622 of file NCMesh3D.cpp.
References add_element(), edge_id, edges, elements, elasticity_rhs::f, faces, find_edge(), find_face(), find_vertex(), get_edge(), get_face(), get_vertex(), tetrahedron::is_valid(), n_elements, refineHistory, and vertices.
Referenced by refine(), and refine_elements().
refine_elements()
void polyfem::mesh::NCMesh3D::refine_elements (const std::vector< int > & ids)
Definition at line 725 of file NCMesh3D.cpp.
References refine_element(), and valid_to_all_elem().
set_body_ids() [1/2]
void polyfem::mesh::NCMesh3D::set_body_ids (const Eigen::VectorXi & body_ids) override virtual
Set the volume sections.
Parameters
[in] body_ids matrix of labels, one per element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 285 of file NCMesh3D.cpp.
References elements, n_cells(), and valid_to_all_elem().
set_body_ids() [2/2]
void polyfem::mesh::NCMesh3D::set_body_ids (const std::vector< int > & body_ids) override virtual
Set the volume sections.
Parameters
[in] body_ids vector of labels, one per element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 277 of file NCMesh3D.cpp.
References elements, n_cells(), and valid_to_all_elem().
set_boundary_ids()
void polyfem::mesh::NCMesh3D::set_boundary_ids (const std::vector< int > & boundary_ids) override virtual
Set the boundary selection from a vector.
Parameters
[in] boundary_ids vector one value per element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 269 of file NCMesh3D.cpp.
References faces, n_faces(), and valid_to_all_face().
switch_edge()
Navigation3D::Index polyfem::mesh::NCMesh3D::switch_edge (Navigation3D::Index idx) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 546 of file NCMesh3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, and face_edge().
Referenced by get_index_from_element_face(), and next_around_face().
switch_element()
Navigation3D::Index polyfem::mesh::NCMesh3D::switch_element (Navigation3D::Index idx) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 575 of file NCMesh3D.cpp.
References all_to_valid_elem(), cell_face(), polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, elasticity_rhs::f, polyfem::mesh::Navigation3D::Index::face, faces, n_cell_faces(), and valid_to_all_face().
Referenced by next_around_edge().
switch_face()
Navigation3D::Index polyfem::mesh::NCMesh3D::switch_face (Navigation3D::Index idx) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 554 of file NCMesh3D.cpp.
References cell_face(), polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, face_edge(), face_vertex(), n_face_vertices(), and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by next_around_edge().
switch_vertex()
Navigation3D::Index polyfem::mesh::NCMesh3D::switch_vertex (Navigation3D::Index idx) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 533 of file NCMesh3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, edge_vertex(), polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, face_vertex(), n_face_vertices(), and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by get_index_from_element_edge(), get_index_from_element_face(), and next_around_face().
traverse_edge()
void polyfem::mesh::NCMesh3D::traverse_edge (Eigen::Vector2i v, double p1, double p2, int depth, std::vector< follower_edge > & list) const protected
Definition at line 988 of file NCMesh3D.cpp.
References edges, find_edge(), find_vertex(), and traverse_edge().
Referenced by build_edge_follower_chain(), and traverse_edge().
traverse_face()
void polyfem::mesh::NCMesh3D::traverse_face (int v1, int v2, int v3, Eigen::Vector2d p1, Eigen::Vector2d p2, Eigen::Vector2d p3, int depth, std::vector< follower_face > & face_list, std::vector< int > & edge_list) const protected
Definition at line 1044 of file NCMesh3D.cpp.
References faces, find_edge(), find_face(), find_vertex(), and traverse_face().
Referenced by build_face_follower_chain(), and traverse_face().
triangulate_faces()
void polyfem::mesh::NCMesh3D::triangulate_faces (Eigen::MatrixXi & tris, Eigen::MatrixXd & pts, std::vector< int > & ranges) const override virtual
generate a triangular representation of every face
Parameters
[out] tris triangles connectivity
[out] pts triangles vertices
[out] ranges connection to original faces
Implements polyfem::mesh::Mesh.
Definition at line 294 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::cell_barycenters(), cell_face(), cell_vertex(), polyfem::mesh::Mesh::face_barycenters(), face_vertex(), n_cell_faces(), n_cell_vertices(), n_cells(), n_face_vertices(), n_faces(), n_vertices(), and point().
update_elements_tag()
void polyfem::mesh::NCMesh3D::update_elements_tag () override virtual
Update elements types.
Reimplemented from polyfem::mesh::Mesh.
Definition at line 103 of file NCMesh3D.cpp.
References polyfem::mesh::Mesh::elements_tag_, n_cells(), and polyfem::mesh::Simplex.
valid_to_all_edge()
int polyfem::mesh::NCMesh3D::valid_to_all_edge (const int id) const inline protected
Definition at line 395 of file NCMesh3D.hpp.
References index_prepared, and valid_to_all_edgeMap.
Referenced by edge_neighs(), edge_vertex(), get_edge_elements_neighs(), is_boundary_edge(), leader_edge_of_edge(), leader_face_of_edge(), n_edge_cells(), and n_follower_edges().
valid_to_all_elem()
int polyfem::mesh::NCMesh3D::valid_to_all_elem (const int id) const inline protected
Definition at line 419 of file NCMesh3D.hpp.
References index_prepared, and valid_to_all_elemMap.
Referenced by cell_edge(), cell_face(), cell_ref_level(), cell_vertex(), compute_body_ids(), get_body_id(), refine_elements(), and set_body_ids().
valid_to_all_face()
int polyfem::mesh::NCMesh3D::valid_to_all_face (const int id) const inline protected
Definition at line 407 of file NCMesh3D.hpp.
References index_prepared, and valid_to_all_faceMap.
Referenced by compute_boundary_ids(), face_edge(), face_vertex(), get_boundary_id(), get_face_elements_neighs(), is_boundary_face(), leader_face_of_face(), n_face_cells(), n_follower_faces(), set_boundary_ids(), and switch_element().
valid_to_all_vertex()
int polyfem::mesh::NCMesh3D::valid_to_all_vertex (const int id) const inline protected
Definition at line 383 of file NCMesh3D.hpp.
References index_prepared, and valid_to_all_vertexMap.
Referenced by get_index_from_element_edge(), get_index_from_element_face(), get_vertex_elements_neighs(), is_boundary_vertex(), leader_edge_of_vertex(), leader_face_of_vertex(), point(), and vertex_neighs().
vertex_neighs()
std::vector< uint32_t > polyfem::mesh::NCMesh3D::vertex_neighs (const int v_gid) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 516 of file NCMesh3D.cpp.
References all_to_valid_elem(), valid_to_all_vertex(), and vertices.
Member Data Documentation
adj_prepared
bool polyfem::mesh::NCMesh3D::adj_prepared = false protected
Definition at line 460 of file NCMesh3D.hpp.
Referenced by build_from_matrices(), leader_edge_of_edge(), leader_edge_of_vertex(), leader_face_of_edge(), leader_face_of_face(), leader_face_of_vertex(), n_follower_edges(), n_follower_faces(), and prepare_mesh().
all_to_valid_edgeMap
std::vector<int> polyfem::mesh::NCMesh3D::all_to_valid_edgeMap protected
Definition at line 473 of file NCMesh3D.hpp.
Referenced by all_to_valid_edge(), and build_index_mapping().
all_to_valid_elemMap
std::vector<int> polyfem::mesh::NCMesh3D::all_to_valid_elemMap protected
Definition at line 471 of file NCMesh3D.hpp.
Referenced by all_to_valid_elem(), and build_index_mapping().
all_to_valid_faceMap
std::vector<int> polyfem::mesh::NCMesh3D::all_to_valid_faceMap protected
Definition at line 474 of file NCMesh3D.hpp.
Referenced by all_to_valid_face(), and build_index_mapping().
all_to_valid_vertexMap
std::vector<int> polyfem::mesh::NCMesh3D::all_to_valid_vertexMap protected
Definition at line 472 of file NCMesh3D.hpp.
Referenced by all_to_valid_vertex(), and build_index_mapping().
edgeMap
std::unordered_map<Eigen::Vector2i, int, ArrayHasher2D> polyfem::mesh::NCMesh3D::edgeMap protected
Definition at line 468 of file NCMesh3D.hpp.
Referenced by build_from_matrices(), find_edge(), and get_edge().
edges
std::vector<ncBoundary> polyfem::mesh::NCMesh3D::edges protected
Definition at line 464 of file NCMesh3D.hpp.
Referenced by add_element(), build_edge_follower_chain(), build_element_vertex_adjacency(), build_face_follower_chain(), build_from_matrices(), build_index_mapping(), cell_edge(), coarsen_element(), edge_neighs(), edge_vertex(), get_edge(), get_edge_elements_neighs(), is_boundary_edge(), leader_edge_of_edge(), leader_face_of_edge(), mark_boundary(), n_edge_cells(), n_edges(), n_follower_edges(), refine_element(), and traverse_edge().
elementAdj
Eigen::SparseMatrix<bool, Eigen::RowMajor> polyfem::mesh::NCMesh3D::elementAdj protected
Definition at line 479 of file NCMesh3D.hpp.
elements
std::vector<ncElem> polyfem::mesh::NCMesh3D::elements protected
Definition at line 462 of file NCMesh3D.hpp.
Referenced by add_element(), build_from_matrices(), build_index_mapping(), cell_edge(), cell_face(), cell_ref_level(), cell_vertex(), coarsen_element(), compute_body_ids(), get_body_id(), refine(), refine_element(), and set_body_ids().
faceMap
std::unordered_map<Eigen::Vector3i, int, ArrayHasher3D> polyfem::mesh::NCMesh3D::faceMap protected
Definition at line 469 of file NCMesh3D.hpp.
Referenced by build_from_matrices(), find_face(), and get_face().
faces
std::vector<ncBoundary> polyfem::mesh::NCMesh3D::faces protected
Definition at line 465 of file NCMesh3D.hpp.
Referenced by add_element(), build_element_vertex_adjacency(), build_face_follower_chain(), build_index_mapping(), cell_face(), coarsen_element(), compute_boundary_ids(), face_edge(), face_vertex(), get_boundary_id(), get_face(), get_face_elements_neighs(), is_boundary_face(), leader_face_of_face(), mark_boundary(), n_face_cells(), n_faces(), n_follower_faces(), refine_element(), set_boundary_ids(), switch_element(), and traverse_face().
index_prepared
bool polyfem::mesh::NCMesh3D::index_prepared = false protected
Definition at line 459 of file NCMesh3D.hpp.
Referenced by all_to_valid_edge(), all_to_valid_elem(), all_to_valid_face(), all_to_valid_vertex(), build_from_matrices(), build_index_mapping(), is_boundary_element(), valid_to_all_edge(), valid_to_all_elem(), valid_to_all_face(), and valid_to_all_vertex().
midpointMap
std::unordered_map<Eigen::Vector2i, int, ArrayHasher2D> polyfem::mesh::NCMesh3D::midpointMap protected
Definition at line 467 of file NCMesh3D.hpp.
Referenced by build_from_matrices(), find_vertex(), and get_vertex().
n_elements
int polyfem::mesh::NCMesh3D::n_elements = 0 protected
Definition at line 457 of file NCMesh3D.hpp.
Referenced by add_element(), build_from_matrices(), build_index_mapping(), coarsen_element(), load(), n_cells(), and refine_element().
refineHistory
std::vector<int> polyfem::mesh::NCMesh3D::refineHistory protected
Definition at line 476 of file NCMesh3D.hpp.
Referenced by build_from_matrices(), coarsen_element(), and refine_element().
valid_to_all_edgeMap
std::vector<int> polyfem::mesh::NCMesh3D::valid_to_all_edgeMap protected
Definition at line 473 of file NCMesh3D.hpp.
Referenced by build_index_mapping(), and valid_to_all_edge().
valid_to_all_elemMap
std::vector<int> polyfem::mesh::NCMesh3D::valid_to_all_elemMap protected
Definition at line 471 of file NCMesh3D.hpp.
Referenced by build_index_mapping(), and valid_to_all_elem().
valid_to_all_faceMap
std::vector<int> polyfem::mesh::NCMesh3D::valid_to_all_faceMap protected
Definition at line 474 of file NCMesh3D.hpp.
Referenced by build_index_mapping(), and valid_to_all_face().
valid_to_all_vertexMap
std::vector<int> polyfem::mesh::NCMesh3D::valid_to_all_vertexMap protected
Definition at line 472 of file NCMesh3D.hpp.
Referenced by build_index_mapping(), and valid_to_all_vertex().
vertices
std::vector<ncVert> polyfem::mesh::NCMesh3D::vertices protected
Definition at line 463 of file NCMesh3D.hpp.
Referenced by add_element(), build_element_vertex_adjacency(), build_from_matrices(), build_index_mapping(), cell_vertex(), coarsen_element(), edge_vertex(), face_vertex(), get_vertex(), get_vertex_elements_neighs(), is_boundary_vertex(), leader_edge_of_vertex(), leader_face_of_vertex(), load(), mark_boundary(), n_vertices(), point(), refine_element(), and vertex_neighs().
The documentation for this class was generated from the following files:
src/polyfem/mesh/mesh3D/NCMesh3D.hpp
src/polyfem/mesh/mesh3D/NCMesh3D.cpp