PolyFEM: polyfem::solver::BCLagrangianForm Class Reference
polyfem::solver::BCLagrangianForm Class Reference
Form of the lagrangian in augmented lagrangian.
#include <BCLagrangianForm.hpp>
Public Member Functions
BCLagrangianForm (const int ndof, const std::vector< int > &boundary_nodes, const std::vector< mesh::LocalBoundary > &local_boundary, const std::vector< mesh::LocalBoundary > &local_neumann_boundary, const int n_boundary_samples, const StiffnessMatrix &mass, const assembler::RhsAssembler &rhs_assembler, const mesh::Obstacle &obstacle, const bool is_time_dependent, const double t)
Construct a new BCLagrangianForm object with a time dependent Dirichlet boundary.
BCLagrangianForm (const int ndof, const std::vector< int > &boundary_nodes, const StiffnessMatrix &mass, const mesh::Obstacle &obstacle, const Eigen::MatrixXd &target_x)
Construct a new BCLagrangianForm object with a fixed Dirichlet boundary.
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const override
Compute the second derivative of the value wrt x.
void update_quantities (const double t, const Eigen::VectorXd &x) override
Update time dependent quantities.
void update_lagrangian (const Eigen::VectorXd &x, const double k_al)
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual double value (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x)
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x)
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num)
Update lagged fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC)
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Private Member Functions
void init_masked_lumped_mass (const int ndof, const StiffnessMatrix &mass, const mesh::Obstacle &obstacle)
Initialize the masked lumped mass matrix.
void update_target (const double t)
Update target x to the Dirichlet boundary values at time t.
Private Attributes
const std::vector< int > & boundary_nodes_
const std::vector< mesh::LocalBoundary > * local_boundary_
const std::vector< mesh::LocalBoundary > * local_neumann_boundary_
const int n_boundary_samples_
const assembler::RhsAssembler * rhs_assembler_
Reference to the RHS assembler.
const bool is_time_dependent_
StiffnessMatrix masked_lumped_mass_sqrt_
sqrt mass matrix masked by the AL dofs
Eigen::MatrixXd target_x_
actually a vector with the same size as x with target nodal positions
Eigen::VectorXd lagr_mults_
vector of lagrange multipliers
Additional Inherited Members
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual double value_unweighted (const Eigen::VectorXd &x) const =0
Compute the value of the form.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const =0
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const =0
Compute the second derivative of the value wrt x.
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Form of the lagrangian in augmented lagrangian.
Definition at line 15 of file BCLagrangianForm.hpp.
Constructor & Destructor Documentation
BCLagrangianForm() [1/2]
polyfem::solver::BCLagrangianForm::BCLagrangianForm (const int ndof, const std::vector< int > & boundary_nodes, const std::vector< mesh::LocalBoundary > & local_boundary, const std::vector< mesh::LocalBoundary > & local_neumann_boundary, const int n_boundary_samples, const StiffnessMatrix & mass, const assembler::RhsAssembler & rhs_assembler, const mesh::Obstacle & obstacle, const bool is_time_dependent, const double t)
Construct a new BCLagrangianForm object with a time dependent Dirichlet boundary.
Parameters
ndof Number of degrees of freedom
boundary_nodes DoFs that are part of the Dirichlet boundary
local_boundary
local_neumann_boundary
n_boundary_samples
mass Mass matrix
rhs_assembler Right hand side assembler
obstacle Obstacles
is_time_dependent Whether the problem is time dependent
t Current time
Definition at line 7 of file BCLagrangianForm.cpp.
References init_masked_lumped_mass(), and update_target().
BCLagrangianForm() [2/2]
polyfem::solver::BCLagrangianForm::BCLagrangianForm (const int ndof, const std::vector< int > & boundary_nodes, const StiffnessMatrix & mass, const mesh::Obstacle & obstacle, const Eigen::MatrixXd & target_x)
Construct a new BCLagrangianForm object with a fixed Dirichlet boundary.
Parameters
ndof Number of degrees of freedom
boundary_nodes DoFs that are part of the Dirichlet boundary
mass Mass matrix
obstacle Obstacles
target_x Target values for the boundary DoFs
Definition at line 28 of file BCLagrangianForm.cpp.
References init_masked_lumped_mass().
Member Function Documentation
first_derivative_unweighted()
void polyfem::solver::BCLagrangianForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Implements polyfem::solver::Form.
Definition at line 98 of file BCLagrangianForm.cpp.
References lagr_mults_, and masked_lumped_mass_sqrt_.
init_masked_lumped_mass()
void polyfem::solver::BCLagrangianForm::init_masked_lumped_mass (const int ndof, const StiffnessMatrix & mass, const mesh::Obstacle & obstacle) private
Initialize the masked lumped mass matrix.
Parameters
ndof Number of degrees of freedom
mass Mass matrix
obstacle Obstacles
Definition at line 44 of file BCLagrangianForm.cpp.
References boundary_nodes_, lagr_mults_, polyfem::utils::lump_matrix(), masked_lumped_mass_sqrt_, polyfem::mesh::Obstacle::n_vertices(), polyfem::mesh::Obstacle::ndof(), polyfem::utils::sparse_identity(), and polyfem::solver::Form::value().
Referenced by BCLagrangianForm().
second_derivative_unweighted()
void polyfem::solver::BCLagrangianForm::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const override virtual
Compute the second derivative of the value wrt x.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Implements polyfem::solver::Form.
Definition at line 103 of file BCLagrangianForm.cpp.
References masked_lumped_mass_sqrt_.
update_lagrangian()
void polyfem::solver::BCLagrangianForm::update_lagrangian (const Eigen::VectorXd & x, const double k_al)
Definition at line 126 of file BCLagrangianForm.cpp.
References lagr_mults_, masked_lumped_mass_sqrt_, target_x_, and x.
update_quantities()
void polyfem::solver::BCLagrangianForm::update_quantities (const double t, const Eigen::VectorXd & x) override virtual
Update time dependent quantities.
Parameters
t New time
x Solution at time t
Reimplemented from polyfem::solver::Form.
Definition at line 109 of file BCLagrangianForm.cpp.
References is_time_dependent_, and update_target().
update_target()
void polyfem::solver::BCLagrangianForm::update_target (const double t) private
Update target x to the Dirichlet boundary values at time t.
Parameters
t Current time
Definition at line 115 of file BCLagrangianForm.cpp.
References boundary_nodes_, local_boundary_, local_neumann_boundary_, masked_lumped_mass_sqrt_, n_boundary_samples_, rhs_assembler_, polyfem::assembler::RhsAssembler::set_bc(), and target_x_.
Referenced by BCLagrangianForm(), and update_quantities().
value_unweighted()
double polyfem::solver::BCLagrangianForm::value_unweighted (const Eigen::VectorXd & x) const override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 91 of file BCLagrangianForm.cpp.
References lagr_mults_, masked_lumped_mass_sqrt_, target_x_, and x.
Member Data Documentation
boundary_nodes_
const std::vector<int>& polyfem::solver::BCLagrangianForm::boundary_nodes_ private
Definition at line 76 of file BCLagrangianForm.hpp.
Referenced by init_masked_lumped_mass(), and update_target().
is_time_dependent_
const bool polyfem::solver::BCLagrangianForm::is_time_dependent_ private
Definition at line 82 of file BCLagrangianForm.hpp.
Referenced by update_quantities().
lagr_mults_
Eigen::VectorXd polyfem::solver::BCLagrangianForm::lagr_mults_ private
vector of lagrange multipliers
Definition at line 86 of file BCLagrangianForm.hpp.
Referenced by first_derivative_unweighted(), init_masked_lumped_mass(), update_lagrangian(), and value_unweighted().
local_boundary_
const std::vector<mesh::LocalBoundary>* polyfem::solver::BCLagrangianForm::local_boundary_ private
Definition at line 77 of file BCLagrangianForm.hpp.
Referenced by update_target().
local_neumann_boundary_
const std::vector<mesh::LocalBoundary>* polyfem::solver::BCLagrangianForm::local_neumann_boundary_ private
Definition at line 78 of file BCLagrangianForm.hpp.
Referenced by update_target().
masked_lumped_mass_sqrt_
StiffnessMatrix polyfem::solver::BCLagrangianForm::masked_lumped_mass_sqrt_ private
sqrt mass matrix masked by the AL dofs
Definition at line 84 of file BCLagrangianForm.hpp.
Referenced by first_derivative_unweighted(), init_masked_lumped_mass(), second_derivative_unweighted(), update_lagrangian(), update_target(), and value_unweighted().
n_boundary_samples_
const int polyfem::solver::BCLagrangianForm::n_boundary_samples_ private
Definition at line 79 of file BCLagrangianForm.hpp.
Referenced by update_target().
rhs_assembler_
const assembler::RhsAssembler* polyfem::solver::BCLagrangianForm::rhs_assembler_ private
Reference to the RHS assembler.
Definition at line 81 of file BCLagrangianForm.hpp.
Referenced by update_target().
target_x_
Eigen::MatrixXd polyfem::solver::BCLagrangianForm::target_x_ private
actually a vector with the same size as x with target nodal positions
Definition at line 85 of file BCLagrangianForm.hpp.
Referenced by update_lagrangian(), update_target(), and value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/BCLagrangianForm.hpp
src/polyfem/solver/forms/BCLagrangianForm.cpp