PolyFEM: polyfem::problem::NodeValues Class Reference
polyfem::problem::NodeValues Class Reference
#include <NodeProblem.hpp>
Public Member Functions
NodeValues ()
void load (const std::string &path)
void init (const mesh::Mesh &mesh)
double dirichlet_interpolate (const int p_id, const Eigen::MatrixXd &uv) const
double neumann_interpolate (const int p_id, const Eigen::MatrixXd &uv) const
Private Member Functions
double interpolate (const int p_id, const Eigen::MatrixXd &uv, bool is_dirichlet) const
Private Attributes
std::vector< int > raw_ids_
std::vector< std::vector< double > > raw_data_
std::vector< bool > raw_dirichlet_
std::vector< Eigen::VectorXd > data_
std::vector< bool > dirichlet_
Detailed Description
Definition at line 14 of file NodeProblem.hpp.
Constructor & Destructor Documentation
NodeValues()
polyfem::problem::NodeValues::NodeValues ()
Definition at line 13 of file NodeProblem.cpp.
Member Function Documentation
dirichlet_interpolate()
double polyfem::problem::NodeValues::dirichlet_interpolate (const int p_id, const Eigen::MatrixXd & uv) const inline
Definition at line 22 of file NodeProblem.hpp.
References interpolate().
Referenced by polyfem::problem::NodeProblem::dirichlet_bc().
init()
void polyfem::problem::NodeValues::init (const mesh::Mesh & mesh)
Definition at line 53 of file NodeProblem.cpp.
References data_, dirichlet_, polyfem::mesh::Mesh::is_volume(), polyfem::mesh::Mesh::n_edges(), polyfem::mesh::Mesh::n_faces(), raw_data_, raw_dirichlet_, and raw_ids_.
Referenced by polyfem::problem::NodeProblem::init().
interpolate()
double polyfem::problem::NodeValues::interpolate (const int p_id, const Eigen::MatrixXd & uv, bool is_dirichlet) const private
Definition at line 78 of file NodeProblem.cpp.
References data_, dirichlet_, and vals.
Referenced by dirichlet_interpolate(), and neumann_interpolate().
load()
void polyfem::problem::NodeValues::load (const std::string & path)
Definition at line 17 of file NodeProblem.cpp.
References polyfem::logger(), eigs::path, raw_data_, raw_dirichlet_, and raw_ids_.
Referenced by polyfem::problem::NodeProblem::set_parameters().
neumann_interpolate()
double polyfem::problem::NodeValues::neumann_interpolate (const int p_id, const Eigen::MatrixXd & uv) const inline
Definition at line 26 of file NodeProblem.hpp.
References interpolate().
Referenced by polyfem::problem::NodeProblem::neumann_bc().
Member Data Documentation
data_
std::vector<Eigen::VectorXd> polyfem::problem::NodeValues::data_ private
Definition at line 38 of file NodeProblem.hpp.
Referenced by init(), and interpolate().
dirichlet_
std::vector<bool> polyfem::problem::NodeValues::dirichlet_ private
Definition at line 39 of file NodeProblem.hpp.
Referenced by init(), and interpolate().
raw_data_
std::vector<std::vector<double> > polyfem::problem::NodeValues::raw_data_ private
Definition at line 35 of file NodeProblem.hpp.
Referenced by init(), and load().
raw_dirichlet_
std::vector<bool> polyfem::problem::NodeValues::raw_dirichlet_ private
Definition at line 36 of file NodeProblem.hpp.
Referenced by init(), and load().
raw_ids_
std::vector<int> polyfem::problem::NodeValues::raw_ids_ private
Definition at line 34 of file NodeProblem.hpp.
Referenced by init(), and load().
The documentation for this class was generated from the following files:
src/polyfem/problem/NodeProblem.hpp
src/polyfem/problem/NodeProblem.cpp