PolyFEM: polyfem::solver::FrictionVariableToSimulation Class Reference
polyfem::solver::FrictionVariableToSimulation Class Reference
Maps one friction coefficient to the whole state.
#include <FrictionVariableToSimulation.hpp>
Public Types
using StatePtrs = std::vector< std::shared_ptr< State > >
using DiffCachePtrs = std::vector< std::shared_ptr< DiffCache > >
Public Member Functions
FrictionVariableToSimulation (StatePtrs states, DiffCachePtrs diff_caches, CompositeParametrization parametrizations)
Construct FrictionVariableToSimulation.
std::string name () const override
ParameterType parameter_type () const override
bool affect_state (const State &target) const override
Return true if current var2sim maps to target state.
void update (const Eigen::VectorXd &x) override
Update forward simulation states from optimization variables.
void update_state_variables (const Eigen::VectorXd &x, Eigen::VectorXd &state_variables) const override
Update state variables from optimization variables.
Eigen::VectorXd compute_adjoint_term (const Eigen::VectorXd &x) const override
Compute adjoint contribution of objective gradient.
int inverse_dof () const override
Compute optimization variables dof.
Eigen::VectorXd inverse_eval () const override
Compute optimization variables from forward simulation State.
Eigen::VectorXd apply_parametrization_jacobian (const Eigen::VectorXd &term, const Eigen::VectorXd &x) const override
Apply parametrization jacobian to compute the gradient w.r.t.
Public Member Functions inherited from polyfem::solver::VariableToSimulation
virtual ~VariableToSimulation ()=default
Private Member Functions
int para_out_dof () const
Private Attributes
StatePtrs states_
DiffCachePtrs diff_caches_
CompositeParametrization parametrization_
Detailed Description
Maps one friction coefficient to the whole state.
Definition at line 14 of file FrictionVariableToSimulation.hpp.
Member Typedef Documentation
DiffCachePtrs
using polyfem::solver::FrictionVariableToSimulation::DiffCachePtrs = std::vector<std::shared_ptr<DiffCache> >
Definition at line 18 of file FrictionVariableToSimulation.hpp.
StatePtrs
using polyfem::solver::FrictionVariableToSimulation::StatePtrs = std::vector<std::shared_ptr<State> >
Definition at line 17 of file FrictionVariableToSimulation.hpp.
Constructor & Destructor Documentation
FrictionVariableToSimulation()
polyfem::solver::FrictionVariableToSimulation::FrictionVariableToSimulation (StatePtrs states, DiffCachePtrs diff_caches, CompositeParametrization parametrizations)
Construct FrictionVariableToSimulation.
Parameters
[in] states Shared ptr to all forward sim states.
[in] diff_caches Shared ptr to all diff caches.
[in] parametrizations Parametrizations.
Exceptions
std::runtime_error Throw if input is invalid.
Definition at line 16 of file FrictionVariableToSimulation.cpp.
References diff_caches_, polyfem::log_and_throw_adjoint_error(), and states_.
Member Function Documentation
affect_state()
bool polyfem::solver::FrictionVariableToSimulation::affect_state (const State & target) const override virtual
Return true if current var2sim maps to target state.
Implements polyfem::solver::VariableToSimulation.
Definition at line 45 of file FrictionVariableToSimulation.cpp.
References states_.
apply_parametrization_jacobian()
Eigen::VectorXd polyfem::solver::FrictionVariableToSimulation::apply_parametrization_jacobian (const Eigen::VectorXd & term, const Eigen::VectorXd & x) const override virtual
Apply parametrization jacobian to compute the gradient w.r.t.
to optimization variables.
Parameters
term Gradient w.r.t. to full inherent dof (Ex. all vertices for shape var2sim)
x Optimization variables.
Implements polyfem::solver::VariableToSimulation.
Definition at line 113 of file FrictionVariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error(), and name().
compute_adjoint_term()
Eigen::VectorXd polyfem::solver::FrictionVariableToSimulation::compute_adjoint_term (const Eigen::VectorXd & x) const override virtual
Compute adjoint contribution of objective gradient.
See arXiv:2205.13643.
Let objective function be J and optimization variable be x. This method computes all adjoint related terms in dJ/dx. For static case (E.q. 11), it's the second term. For dynamic case (E.q. 15), it's everything except ∂qJ.
Parameters
x[in] Optimization variables.
Returns
Adjoint contribution of objective gradient.
Implements polyfem::solver::VariableToSimulation.
Definition at line 74 of file FrictionVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::apply_jacobian(), diff_caches_, polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), polyfem::get_adjoint_mat(), para_out_dof(), parametrization_, states_, and x.
inverse_dof()
int polyfem::solver::FrictionVariableToSimulation::inverse_dof () const override virtual
Compute optimization variables dof.
Returns
Optimization variables dof.
Exceptions
std::runtime_error Throw if not implemented.
Implements polyfem::solver::VariableToSimulation.
Definition at line 101 of file FrictionVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::inverse_size(), para_out_dof(), and parametrization_.
inverse_eval()
Eigen::VectorXd polyfem::solver::FrictionVariableToSimulation::inverse_eval () const override virtual
Compute optimization variables from forward simulation State.
Returns
Optimization variables.
Exceptions
std::runtime_error Throw if not implemented.
Implements polyfem::solver::VariableToSimulation.
Definition at line 106 of file FrictionVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::inverse_eval(), para_out_dof(), parametrization_, states_, and y.
name()
std::string polyfem::solver::FrictionVariableToSimulation::name () const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 35 of file FrictionVariableToSimulation.cpp.
Referenced by apply_parametrization_jacobian().
para_out_dof()
int polyfem::solver::FrictionVariableToSimulation::para_out_dof () const private
Definition at line 119 of file FrictionVariableToSimulation.cpp.
Referenced by compute_adjoint_term(), inverse_dof(), inverse_eval(), update(), and update_state_variables().
parameter_type()
ParameterType polyfem::solver::FrictionVariableToSimulation::parameter_type () const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 40 of file FrictionVariableToSimulation.cpp.
References polyfem::solver::FrictionCoefficient.
update()
void polyfem::solver::FrictionVariableToSimulation::update (const Eigen::VectorXd & x) override virtual
Update forward simulation states from optimization variables.
Parameters
[in] x Optimization variables.
Implements polyfem::solver::VariableToSimulation.
Definition at line 57 of file FrictionVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, states_, x, and y.
update_state_variables()
void polyfem::solver::FrictionVariableToSimulation::update_state_variables (const Eigen::VectorXd & x, Eigen::VectorXd & state_variables) const override virtual
Update state variables from optimization variables.
Compared to update() this method update abstract state variables instead of writing directly to state.
Parameters
[in] x Optimization variables.
[out] state_variables Abstract state variables update dst.
Implements polyfem::solver::VariableToSimulation.
Definition at line 68 of file FrictionVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, and x.
Member Data Documentation
diff_caches_
DiffCachePtrs polyfem::solver::FrictionVariableToSimulation::diff_caches_ private
Definition at line 41 of file FrictionVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), and FrictionVariableToSimulation().
parametrization_
CompositeParametrization polyfem::solver::FrictionVariableToSimulation::parametrization_ private
Definition at line 42 of file FrictionVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), inverse_dof(), inverse_eval(), update(), and update_state_variables().
states_
StatePtrs polyfem::solver::FrictionVariableToSimulation::states_ private
Definition at line 40 of file FrictionVariableToSimulation.hpp.
Referenced by affect_state(), compute_adjoint_term(), FrictionVariableToSimulation(), inverse_eval(), and update().
The documentation for this class was generated from the following files:
src/polyfem/optimization/var2sims/FrictionVariableToSimulation.hpp
src/polyfem/optimization/var2sims/FrictionVariableToSimulation.cpp