PolyFEM: polyfem::assembler::ViscousDampingPrev Class Reference
polyfem::assembler::ViscousDampingPrev Class Reference
#include <ViscousDamping.hpp>
Public Member Functions
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const override
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double t, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double t, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double t, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::MatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
double compute_energy (const NonLinearAssemblerData &data) const override
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
Public Member Functions inherited from polyfem::assembler::ViscousDamping
std::string name () const override
std::map< std::string, ParamFunc > parameters () const override
ViscousDamping ()=default
void add_multimaterial (const int index, const json &params, const Units &units) override
void set_params (const double psi, const double phi)
void compute_stress_grad (const OptAssemblerData &data, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
void compute_stress_prev_grad (const OptAssemblerData &data, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const override
double get_psi () const
double get_phi () const
bool is_valid () const
const DampingParameters & damping_params () const
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
Eigen::VectorXd assemble_energy_per_element (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double t, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
virtual bool is_linear () const override
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double t, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual void compute_scalar_value (const OutputData &data, std::vector< NamedMatrix > &result) const
virtual void compute_tensor_value (const OutputData &data, std::vector< NamedMatrix > &result) const
virtual void compute_stiffness_value (const double t, const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const OptAssemblerData &data, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const OptAssemblerData &data, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const OptAssemblerData &data, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const OptAssemblerData &data, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual VectorNd compute_rhs (const AutodiffHessianPt &pt) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params, const Units &units)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_solution_displacement () const
virtual bool is_fluid () const
virtual bool is_tensor () const
Additional Inherited Members
Public Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Static Public Member Functions inherited from polyfem::assembler::ViscousDamping
static void compute_dstress_dpsi_dphi (const OptAssemblerData &data, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &dstress_dpsi, Eigen::MatrixXd &dstress_dphi)
Protected Member Functions inherited from polyfem::assembler::ViscousDamping
void compute_stress_aux (const Eigen::MatrixXd &F, const Eigen::MatrixXd &dFdt, Eigen::MatrixXd &dRdF, Eigen::MatrixXd &dRdFdot) const
void compute_stress_grad_aux (const Eigen::MatrixXd &F, const Eigen::MatrixXd &dFdt, Eigen::MatrixXd &d2RdF2, Eigen::MatrixXd &d2RdFdFdot, Eigen::MatrixXd &d2RdFdot2) const
Protected Attributes inherited from polyfem::assembler::ViscousDamping
DampingParameters damping_params_
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 66 of file ViscousDamping.hpp.
Member Function Documentation
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double t, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const override virtual
Reimplemented from polyfem::assembler::ViscousDamping.
Definition at line 244 of file Assembler.cpp.
assemble_gradient() [1/3]
void polyfem::assembler::NLAssembler::assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double t, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const override virtual
Reimplemented from polyfem::assembler::ViscousDamping.
assemble_gradient() [2/3]
Eigen::VectorXd polyfem::assembler::ViscousDampingPrev::assemble_gradient (const NonLinearAssemblerData & data) const override virtual
Reimplemented from polyfem::assembler::ViscousDamping.
Definition at line 74 of file ViscousDamping.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::ViscousDamping::compute_stress_aux(), polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::NonLinearAssemblerData::dt, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::Assembler::size(), polyfem::assembler::NonLinearAssemblerData::vals, polyfem::assembler::NonLinearAssemblerData::x, and polyfem::assembler::NonLinearAssemblerData::x_prev.
assemble_gradient() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_gradient (const NonLinearAssemblerData & data) const virtual
Reimplemented from polyfem::assembler::ViscousDamping.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double t, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::MatrixCache & mat_cache, StiffnessMatrix & grad) const override virtual
Reimplemented from polyfem::assembler::ViscousDamping.
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::ViscousDampingPrev::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Reimplemented from polyfem::assembler::ViscousDamping.
Definition at line 271 of file ViscousDamping.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::ViscousDamping::compute_stress_grad_aux(), polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::NonLinearAssemblerData::dt, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::Assembler::size(), polyfem::assembler::NonLinearAssemblerData::vals, polyfem::assembler::NonLinearAssemblerData::x, and polyfem::assembler::NonLinearAssemblerData::x_prev.
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Reimplemented from polyfem::assembler::ViscousDamping.
compute_energy() [1/2]
virtual double polyfem::assembler::NLAssembler::compute_energy (const NonLinearAssemblerData & data) const virtual
Reimplemented from polyfem::assembler::ViscousDamping.
compute_energy() [2/2]
double polyfem::assembler::ViscousDamping::compute_energy (const NonLinearAssemblerData & data) const override virtual
Reimplemented from polyfem::assembler::ViscousDamping.
Definition at line 24 of file ViscousDamping.cpp.
References polyfem::F, and polyfem::assembler::Assembler::size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/ViscousDamping.hpp
src/polyfem/assembler/ViscousDamping.cpp