PolyFEM: polyfem::assembler::StokesMixed Class Reference
polyfem::assembler::StokesMixed Class Reference
#include <Stokes.hpp>
Public Member Functions
std::string name () const override
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > assemble (const MixedAssemblerData &data) const override
int rows () const override
int cols () const override
Public Member Functions inherited from polyfem::assembler::MixedAssembler
MixedAssembler ()
virtual ~MixedAssembler ()=default
void assemble (const bool is_volume, const int n_psi_basis, const int n_phi_basis, const std::vector< basis::ElementBases > &psi_bases, const std::vector< basis::ElementBases > &phi_bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &psi_cache, const AssemblyValsCache &phi_cache, const double t, StiffnessMatrix &stiffness) const
int size () const
virtual void set_size (const int size)
Additional Inherited Members
Protected Attributes inherited from polyfem::assembler::MixedAssembler
int size_ = -1
Detailed Description
Definition at line 38 of file Stokes.hpp.
Member Function Documentation
assemble()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::StokesMixed::assemble (const MixedAssemblerData & data) const override virtual
Implements polyfem::assembler::MixedAssembler.
Definition at line 68 of file Stokes.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, cols(), polyfem::assembler::MixedAssemblerData::da, polyfem::assembler::MixedAssemblerData::i, polyfem::assembler::MixedAssemblerData::j, polyfem::assembler::MixedAssemblerData::phi_vals, polyfem::assembler::MixedAssemblerData::psi_vals, and rows().
cols()
int polyfem::assembler::StokesMixed::cols () const inline override virtual
Implements polyfem::assembler::MixedAssembler.
Definition at line 48 of file Stokes.hpp.
Referenced by assemble().
name()
std::string polyfem::assembler::StokesMixed::name () const inline override virtual
Implements polyfem::assembler::MixedAssembler.
Definition at line 41 of file Stokes.hpp.
rows()
int polyfem::assembler::StokesMixed::rows () const inline override virtual
Implements polyfem::assembler::MixedAssembler.
Definition at line 47 of file Stokes.hpp.
References polyfem::assembler::MixedAssembler::size().
Referenced by assemble().
The documentation for this class was generated from the following files:
src/polyfem/assembler/Stokes.hpp
src/polyfem/assembler/Stokes.cpp