PolyFEM: polyfem::solver::MinTargetDistForm Class Reference
polyfem::solver::MinTargetDistForm Class Reference
#include <TargetForms.hpp>
Public Member Functions
MinTargetDistForm (const VariableToSimulationGroup &variable_to_simulations, const std::vector< int > &steps, const Eigen::VectorXd &target, const json &args, const std::shared_ptr< State > &state)
virtual ~MinTargetDistForm ()=default
Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const override
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
virtual void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual void finish ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Private Member Functions
double eval2 (Eigen::VectorXd &x) const
Eigen::VectorXd eval2_grad (Eigen::VectorXd &x) const
Static Private Member Functions
static double eval1 (Eigen::VectorXd &x)
static Eigen::VectorXd eval1_grad (Eigen::VectorXd &x)
Private Attributes
const std::vector< int > steps_
const Eigen::VectorXd target_
int dim
std::vector< std::unique_ptr< StaticForm > > objs
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 141 of file TargetForms.hpp.
Constructor & Destructor Documentation
MinTargetDistForm()
polyfem::solver::MinTargetDistForm::MinTargetDistForm (const VariableToSimulationGroup & variable_to_simulations, const std::vector< int > & steps, const Eigen::VectorXd & target, const json & args, const std::shared_ptr< State > & state)
Definition at line 605 of file TargetForms.cpp.
References dim, and objs.
~MinTargetDistForm()
virtual polyfem::solver::MinTargetDistForm::~MinTargetDistForm () virtual default
Member Function Documentation
compute_adjoint_rhs()
Eigen::MatrixXd polyfem::solver::MinTargetDistForm::compute_adjoint_rhs (const Eigen::VectorXd & x, const State & state) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 617 of file TargetForms.cpp.
References polyfem::State::diff_cached, eval1_grad(), eval2(), eval2_grad(), polyfem::State::ndof(), objs, polyfem::solver::DiffCache::size(), steps_, polyfem::solver::Form::weight(), and x.
compute_partial_gradient()
void polyfem::solver::MinTargetDistForm::compute_partial_gradient (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 647 of file TargetForms.cpp.
References eval1_grad(), eval2(), eval2_grad(), objs, steps_, polyfem::solver::Form::weight(), and x.
eval1()
static double polyfem::solver::MinTargetDistForm::eval1 (Eigen::VectorXd & x) inline static private
Definition at line 154 of file TargetForms.hpp.
References x.
Referenced by eval1_grad(), and value_unweighted().
eval1_grad()
static Eigen::VectorXd polyfem::solver::MinTargetDistForm::eval1_grad (Eigen::VectorXd & x) inline static private
Definition at line 158 of file TargetForms.hpp.
References eval1(), and x.
Referenced by compute_adjoint_rhs(), and compute_partial_gradient().
eval2()
double polyfem::solver::MinTargetDistForm::eval2 (Eigen::VectorXd & x) const inline private
Definition at line 163 of file TargetForms.hpp.
References dim, target_, and x.
Referenced by compute_adjoint_rhs(), compute_partial_gradient(), and value_unweighted().
eval2_grad()
Eigen::VectorXd polyfem::solver::MinTargetDistForm::eval2_grad (Eigen::VectorXd & x) const inline private
Definition at line 171 of file TargetForms.hpp.
References dim, target_, and x.
Referenced by compute_adjoint_rhs(), and compute_partial_gradient().
value_unweighted()
double polyfem::solver::MinTargetDistForm::value_unweighted (const Eigen::VectorXd & x) const override protected virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 677 of file TargetForms.cpp.
References eval1(), eval2(), objs, steps_, and x.
Member Data Documentation
dim
int polyfem::solver::MinTargetDistForm::dim private
Definition at line 186 of file TargetForms.hpp.
Referenced by eval2(), eval2_grad(), and MinTargetDistForm().
objs
std::vector<std::unique_ptr<StaticForm> > polyfem::solver::MinTargetDistForm::objs private
Definition at line 187 of file TargetForms.hpp.
Referenced by compute_adjoint_rhs(), compute_partial_gradient(), MinTargetDistForm(), and value_unweighted().
steps_
const std::vector<int> polyfem::solver::MinTargetDistForm::steps_ private
Definition at line 183 of file TargetForms.hpp.
Referenced by compute_adjoint_rhs(), compute_partial_gradient(), and value_unweighted().
target_
const Eigen::VectorXd polyfem::solver::MinTargetDistForm::target_ private
Definition at line 184 of file TargetForms.hpp.
Referenced by eval2(), and eval2_grad().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/TargetForms.hpp
src/polyfem/solver/forms/adjoint_forms/TargetForms.cpp