PolyFEM: polyfem::problem::ProblemFactory Class Reference
polyfem::problem::ProblemFactory Class Reference
#include <ProblemFactory.hpp>
Public Member Functions
std::shared_ptr< assembler::Problem > get_problem (const std::string &problem) const
const std::vector< std::string > & get_problem_names () const
Static Public Member Functions
static const ProblemFactory & factory ()
Private Member Functions
ProblemFactory ()
Private Attributes
std::map< std::string, std::function< std::shared_ptr< assembler::Problem >()> > problems_
std::vector< std::string > problem_names_
Detailed Description
Definition at line 13 of file ProblemFactory.hpp.
Constructor & Destructor Documentation
ProblemFactory()
polyfem::problem::ProblemFactory::ProblemFactory () private
Definition at line 29 of file ProblemFactory.cpp.
References problem_names_, and problems_.
Member Function Documentation
factory()
const ProblemFactory & polyfem::problem::ProblemFactory::factory () static
Definition at line 22 of file ProblemFactory.cpp.
get_problem()
std::shared_ptr< Problem > polyfem::problem::ProblemFactory::get_problem (const std::string & problem) const
Definition at line 84 of file ProblemFactory.cpp.
References polyfem::logger(), and problems_.
get_problem_names()
const std::vector< std::string > & polyfem::problem::ProblemFactory::get_problem_names () const inline
Definition at line 19 of file ProblemFactory.hpp.
References problem_names_.
Member Data Documentation
problem_names_
std::vector<std::string> polyfem::problem::ProblemFactory::problem_names_ private
Definition at line 24 of file ProblemFactory.hpp.
Referenced by get_problem_names(), and ProblemFactory().
problems_
std::map<std::string, std::function<std::shared_ptr<assembler::Problem>()> > polyfem::problem::ProblemFactory::problems_ private
Definition at line 23 of file ProblemFactory.hpp.
Referenced by get_problem(), and ProblemFactory().
The documentation for this class was generated from the following files:
src/polyfem/problem/ProblemFactory.hpp
src/polyfem/problem/ProblemFactory.cpp