PolyFEM: polyfem::solver::TransientForm Class Reference
polyfem::solver::TransientForm Class Reference
#include <TransientForm.hpp>
Public Member Functions
TransientForm (const VariableToSimulationGroup &variable_to_simulations, const int time_steps, const double dt, const std::string &transient_integral_type, const std::vector< int > &steps, const std::shared_ptr< StaticForm > &obj)
virtual ~TransientForm ()=default
Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const override
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
void init (const Eigen::VectorXd &x) override
Initialize the form.
bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine if a step from solution x0 to solution x1 is allowed.
double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine the maximum step size allowable between the current and next solution.
void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) override
Initialize variables used during the line search.
void line_search_end () override
Clear variables used during the line search.
void post_step (const polysolve::nonlinear::PostStepData &data) override
Update fields after a step in the optimization.
void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Checks if the step is collision free.
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) final override
Set if the Dirichlet boundary conditions should be enforced.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
std::vector< double > get_transient_quadrature_weights () const
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes
int time_steps_
double dt_
std::string transient_integral_type_
std::vector< int > steps_
std::shared_ptr< StaticForm > obj_
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or Δt²)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Detailed Description
Definition at line 7 of file TransientForm.hpp.
Constructor & Destructor Documentation
TransientForm()
polyfem::solver::TransientForm::TransientForm (const VariableToSimulationGroup & variable_to_simulations, const int time_steps, const double dt, const std::string & transient_integral_type, const std::vector< int > & steps, const std::shared_ptr< StaticForm > & obj) inline
Definition at line 10 of file TransientForm.hpp.
~TransientForm()
virtual polyfem::solver::TransientForm::~TransientForm () virtual default
Member Function Documentation
compute_adjoint_rhs()
Eigen::MatrixXd polyfem::solver::TransientForm::compute_adjoint_rhs (const Eigen::VectorXd & x, const State & state) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 101 of file TransientForm.cpp.
References polyfem::utils::create_thread_storage(), polyfem::utils::get_local_thread_storage(), get_transient_quadrature_weights(), polyfem::utils::maybe_parallel_for(), polyfem::State::ndof(), obj_, time_steps_, polyfem::solver::Form::weight(), and x.
compute_partial_gradient()
void polyfem::solver::TransientForm::compute_partial_gradient (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 127 of file TransientForm.cpp.
References polyfem::utils::create_thread_storage(), polyfem::utils::get_local_thread_storage(), get_transient_quadrature_weights(), polyfem::utils::maybe_parallel_for(), obj_, time_steps_, polyfem::solver::Form::weight(), and x.
get_transient_quadrature_weights()
std::vector< double > polyfem::solver::TransientForm::get_transient_quadrature_weights () const protected
Definition at line 33 of file TransientForm.cpp.
References dt_, steps_, time_steps_, and transient_integral_type_.
Referenced by compute_adjoint_rhs(), compute_partial_gradient(), solution_changed(), and value_unweighted().
init()
void polyfem::solver::TransientForm::init (const Eigen::VectorXd & x) override virtual
Initialize the form.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 151 of file TransientForm.cpp.
References obj_, and x.
is_step_collision_free()
bool polyfem::solver::TransientForm::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented from polyfem::solver::Form.
Definition at line 193 of file TransientForm.cpp.
References obj_.
is_step_valid()
bool polyfem::solver::TransientForm::is_step_valid (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine if a step from solution x0 to solution x1 is allowed.
Parameters
x0 Current solution
x1 Proposed next solution
Returns
True if the step is allowed
Reimplemented from polyfem::solver::Form.
Definition at line 156 of file TransientForm.cpp.
References obj_.
line_search_begin()
void polyfem::solver::TransientForm::line_search_begin (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) override virtual
Initialize variables used during the line search.
Parameters
x0 Current solution
x1 Next solution
Reimplemented from polyfem::solver::Form.
Definition at line 166 of file TransientForm.cpp.
References obj_.
line_search_end()
void polyfem::solver::TransientForm::line_search_end () override virtual
Clear variables used during the line search.
Reimplemented from polyfem::solver::Form.
Definition at line 171 of file TransientForm.cpp.
References obj_.
max_step_size()
double polyfem::solver::TransientForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::Form.
Definition at line 161 of file TransientForm.cpp.
References obj_.
post_step()
void polyfem::solver::TransientForm::post_step (const polysolve::nonlinear::PostStepData & data) override virtual
Update fields after a step in the optimization.
Parameters
iter_num Optimization iteration number
x Current solution
data Data containing info about the current iteration
Reimplemented from polyfem::solver::Form.
Definition at line 176 of file TransientForm.cpp.
References obj_.
solution_changed()
void polyfem::solver::TransientForm::solution_changed (const Eigen::VectorXd & new_x) override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 181 of file TransientForm.cpp.
References get_transient_quadrature_weights(), obj_, polyfem::solver::AdjointForm::solution_changed(), and time_steps_.
value_unweighted()
double polyfem::solver::TransientForm::value_unweighted (const Eigen::VectorXd & x) const override protected virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 78 of file TransientForm.cpp.
References polyfem::utils::create_thread_storage(), polyfem::utils::get_local_thread_storage(), get_transient_quadrature_weights(), polyfem::utils::maybe_parallel_for(), obj_, time_steps_, polyfem::solver::AdjointForm::value(), and x.
Member Data Documentation
dt_
double polyfem::solver::TransientForm::dt_ protected
Definition at line 30 of file TransientForm.hpp.
Referenced by get_transient_quadrature_weights().
obj_
std::shared_ptr<StaticForm> polyfem::solver::TransientForm::obj_ mutable protected
Definition at line 33 of file TransientForm.hpp.
Referenced by compute_adjoint_rhs(), compute_partial_gradient(), init(), is_step_collision_free(), is_step_valid(), line_search_begin(), line_search_end(), max_step_size(), post_step(), solution_changed(), and value_unweighted().
steps_
std::vector<int> polyfem::solver::TransientForm::steps_ protected
Definition at line 32 of file TransientForm.hpp.
Referenced by get_transient_quadrature_weights().
time_steps_
int polyfem::solver::TransientForm::time_steps_ protected
Definition at line 29 of file TransientForm.hpp.
Referenced by compute_adjoint_rhs(), compute_partial_gradient(), get_transient_quadrature_weights(), solution_changed(), and value_unweighted().
transient_integral_type_
std::string polyfem::solver::TransientForm::transient_integral_type_ protected
Definition at line 31 of file TransientForm.hpp.
Referenced by get_transient_quadrature_weights().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/TransientForm.hpp
src/polyfem/solver/forms/adjoint_forms/TransientForm.cpp