PolyFEM: polyfem::assembler::NeoHookeanElasticity Class Reference
polyfem::assembler::NeoHookeanElasticity Class Reference
#include <NeoHookeanElasticity.hpp>
Public Member Functions
NeoHookeanElasticity ()
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
VectorNd compute_rhs (const AutodiffHessianPt &pt) const override
void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const override
void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const override
void add_multimaterial (const int index, const json &params) override
void set_params (const LameParameters &params)
const LameParameters & lame_params () const
void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus) override
std::string name () const override
std::map< std::string, ParamFunc > parameters () const override
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const override
template<int n_basis, int dim>
void compute_energy_aux_gradient_fast (const NonLinearAssemblerData &data, Eigen::Matrix< double, Eigen::Dynamic, 1 > &G_flattened) const
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual bool is_linear () const override
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
virtual std::string name () const =0
int size () const
virtual void set_size (const int size)
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
virtual void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual std::map< std::string, ParamFunc > parameters () const =0
virtual VectorNd compute_rhs (const AutodiffHessianPt &pt) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params)
virtual void add_multimaterial (const int index, const json &params)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_linear () const =0
virtual bool is_solution_displacement () const
virtual bool is_fluid () const
virtual bool is_tensor () const
Public Member Functions inherited from polyfem::assembler::ElasticityAssembler
ElasticityAssembler ()
virtual ~ElasticityAssembler ()=default
void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &stresses) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
bool is_solution_displacement () const override
bool is_tensor () const override
Private Member Functions
template<typename T >
T compute_energy_aux (const NonLinearAssemblerData &data) const
template<int n_basis, int dim>
void compute_energy_hessian_aux_fast (const NonLinearAssemblerData &data, Eigen::MatrixXd &H) const
template<int n_basis, int dim>
void compute_energy_aux_gradient_fast (const NonLinearAssemblerData &data, Eigen::VectorXd &G_flattened) const
Private Attributes
LameParameters params_
Additional Inherited Members
Public Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
virtual void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 11 of file NeoHookeanElasticity.hpp.
Constructor & Destructor Documentation
NeoHookeanElasticity()
polyfem::assembler::NeoHookeanElasticity::NeoHookeanElasticity ()
Definition at line 15 of file NeoHookeanElasticity.cpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::NeoHookeanElasticity::add_multimaterial (const int index, const json & params) override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 19 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::LameParameters::add_multimaterial(), params_, and polyfem::assembler::Assembler::size().
Referenced by polyfem::assembler::MultiModel::add_multimaterial().
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
Definition at line 242 of file Assembler.cpp.
assemble_gradient() [1/3]
void polyfem::assembler::NLAssembler::assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
assemble_gradient() [2/3]
Eigen::VectorXd polyfem::assembler::NeoHookeanElasticity::assemble_gradient (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 47 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
Referenced by polyfem::assembler::MultiModel::assemble_gradient().
assemble_gradient() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_gradient (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::SparseMatrixCache & mat_cache, StiffnessMatrix & grad) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::NeoHookeanElasticity::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 170 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
Referenced by polyfem::assembler::MultiModel::assemble_hessian().
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assign_stress_tensor()
void polyfem::assembler::NeoHookeanElasticity::assign_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const int all_size, const ElasticityTensorType & type, Eigen::MatrixXd & all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> & fun) const override virtual
Implements polyfem::assembler::ElasticityAssembler.
Definition at line 247 of file NeoHookeanElasticity.cpp.
References polyfem::compute_diplacement_grad(), polyfem::F, polyfem::assembler::LameParameters::lambda_mu(), params_, polyfem::PK1, polyfem::pk1_from_cauchy(), polyfem::PK2, polyfem::pk2_from_cauchy(), polyfem::assembler::Assembler::size(), and vals.
Referenced by polyfem::assembler::MultiModel::assign_stress_tensor().
compute_dstress_dmu_dlambda()
void polyfem::assembler::NeoHookeanElasticity::compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & global_pts, const Eigen::MatrixXd & grad_u_i, Eigen::MatrixXd & dstress_dmu, Eigen::MatrixXd & dstress_dlambda) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 623 of file NeoHookeanElasticity.cpp.
compute_energy()
double polyfem::assembler::NeoHookeanElasticity::compute_energy (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 285 of file NeoHookeanElasticity.cpp.
Referenced by polyfem::assembler::MultiModel::compute_energy().
compute_energy_aux()
template<typename T > T polyfem::assembler::NeoHookeanElasticity::compute_energy_aux (const NonLinearAssemblerData & data) const private
Definition at line 292 of file NeoHookeanElasticity.cpp.
References polyfem::compute_disp_grad_at_quad(), polyfem::assembler::NonLinearAssemblerData::da, polyfem::utils::determinant(), polyfem::assembler::ElementAssemblyValues::element_id, polyfem::get_local_disp(), polyfem::assembler::LameParameters::lambda_mu(), params_, polyfem::quadrature::Quadrature::points, polyfem::assembler::ElementAssemblyValues::quadrature, polyfem::assembler::Assembler::size(), val, polyfem::assembler::ElementAssemblyValues::val, and polyfem::assembler::NonLinearAssemblerData::vals.
compute_energy_aux_gradient_fast() [1/2]
template<int n_basis, int dim> void polyfem::assembler::NeoHookeanElasticity::compute_energy_aux_gradient_fast (const NonLinearAssemblerData & data, Eigen::Matrix< double, Eigen::Dynamic, 1 > & G_flattened) const
Definition at line 356 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::ElementAssemblyValues::element_id, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::LameParameters::lambda_mu(), params_, polyfem::quadrature::Quadrature::points, polyfem::assembler::ElementAssemblyValues::quadrature, polyfem::assembler::Assembler::size(), val, polyfem::assembler::ElementAssemblyValues::val, polyfem::assembler::NonLinearAssemblerData::vals, and polyfem::assembler::NonLinearAssemblerData::x.
compute_energy_aux_gradient_fast() [2/2]
template<int n_basis, int dim> void polyfem::assembler::NeoHookeanElasticity::compute_energy_aux_gradient_fast (const NonLinearAssemblerData & data, Eigen::VectorXd & G_flattened) const private
compute_energy_hessian_aux_fast()
template<int n_basis, int dim> void polyfem::assembler::NeoHookeanElasticity::compute_energy_hessian_aux_fast (const NonLinearAssemblerData & data, Eigen::MatrixXd & H) const private
Definition at line 447 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::ElementAssemblyValues::element_id, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::LameParameters::lambda_mu(), params_, polyfem::quadrature::Quadrature::points, polyfem::assembler::ElementAssemblyValues::quadrature, polyfem::assembler::Assembler::size(), val, polyfem::assembler::ElementAssemblyValues::val, polyfem::assembler::NonLinearAssemblerData::vals, and polyfem::assembler::NonLinearAssemblerData::x.
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::NeoHookeanElasticity::compute_rhs (const AutodiffHessianPt & pt) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 27 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::LameParameters::lambda_mu(), polyfem::autogen::neo_hookean_2d_function(), polyfem::autogen::neo_hookean_3d_function(), params_, and polyfem::assembler::Assembler::size().
compute_stiffness_value()
void polyfem::assembler::NeoHookeanElasticity::compute_stiffness_value (const assembler::ElementAssemblyValues & vals, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, Eigen::MatrixXd & tensor) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 116 of file NeoHookeanElasticity.cpp.
References polyfem::compute_diplacement_grad(), polyfem::utils::flatten(), polyfem::assembler::LameParameters::lambda_mu(), params_, polyfem::assembler::Assembler::size(), and vals.
compute_stress_grad_multiply_mat()
void polyfem::assembler::NeoHookeanElasticity::compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & global_pts, const Eigen::MatrixXd & grad_u_i, const Eigen::MatrixXd & mat, Eigen::MatrixXd & stress, Eigen::MatrixXd & result) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 558 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::LameParameters::lambda_mu(), mat, and params_.
compute_stress_grad_multiply_stress()
void polyfem::assembler::NeoHookeanElasticity::compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & global_pts, const Eigen::MatrixXd & grad_u_i, Eigen::MatrixXd & stress, Eigen::MatrixXd & result) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 570 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::LameParameters::lambda_mu(), and params_.
compute_stress_grad_multiply_vect()
void polyfem::assembler::NeoHookeanElasticity::compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & global_pts, const Eigen::MatrixXd & grad_u_i, const Eigen::MatrixXd & vect, Eigen::MatrixXd & stress, Eigen::MatrixXd & result) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 582 of file NeoHookeanElasticity.cpp.
References polyfem::assembler::LameParameters::lambda_mu(), params_, and polyfem::assembler::Assembler::size().
lame_params()
const LameParameters & polyfem::assembler::NeoHookeanElasticity::lame_params () const inline
Definition at line 38 of file NeoHookeanElasticity.hpp.
References params_.
name()
std::string polyfem::assembler::NeoHookeanElasticity::name () const inline override virtual
Implements polyfem::assembler::Assembler.
Definition at line 46 of file NeoHookeanElasticity.hpp.
parameters()
std::map< std::string, Assembler::ParamFunc > polyfem::assembler::NeoHookeanElasticity::parameters () const override virtual
Implements polyfem::assembler::Assembler.
Definition at line 631 of file NeoHookeanElasticity.cpp.
References params_, and polyfem::assembler::Assembler::size().
set_params()
void polyfem::assembler::NeoHookeanElasticity::set_params (const LameParameters & params) inline
Definition at line 37 of file NeoHookeanElasticity.hpp.
References params_.
update_lame_params()
void polyfem::assembler::NeoHookeanElasticity::update_lame_params (const Eigen::MatrixXd & lambdas, const Eigen::MatrixXd & mus) inline override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 40 of file NeoHookeanElasticity.hpp.
References polyfem::assembler::LameParameters::lambda_mat_, polyfem::assembler::LameParameters::mu_mat_, and params_.
Member Data Documentation
params_
LameParameters polyfem::assembler::NeoHookeanElasticity::params_ private
Definition at line 52 of file NeoHookeanElasticity.hpp.
Referenced by add_multimaterial(), assign_stress_tensor(), compute_energy_aux(), compute_energy_aux_gradient_fast(), compute_energy_hessian_aux_fast(), compute_rhs(), compute_stiffness_value(), compute_stress_grad_multiply_mat(), compute_stress_grad_multiply_stress(), compute_stress_grad_multiply_vect(), lame_params(), parameters(), set_params(), and update_lame_params().
The documentation for this class was generated from the following files:
src/polyfem/assembler/NeoHookeanElasticity.hpp
src/polyfem/assembler/NeoHookeanElasticity.cpp