PolyFEM: polyfem::mesh::VTUWriter Class Reference
polyfem::mesh::VTUWriter Class Reference
#include <VTUWriter.hpp>
Public Member Functions
VTUWriter (bool binary=true)
bool write_mesh (const std::string &path, const Eigen::MatrixXd &points, const Eigen::MatrixXi &cells)
bool write_mesh (const std::string &path, const Eigen::MatrixXd &points, const std::vector< std::vector< int > > &cells, const bool is_simplicial)
void add_field (const std::string &name, const Eigen::MatrixXd &data)
void add_scalar_field (const std::string &name, const Eigen::MatrixXd &data)
void add_vector_field (const std::string &name, const Eigen::MatrixXd &data)
void clear ()
Private Member Functions
void write_point_data (std::ostream &os)
void write_header (const int n_vertices, const int n_elements, std::ostream &os)
void write_footer (std::ostream &os)
void write_points (const Eigen::MatrixXd &points, std::ostream &os)
void write_cells (const Eigen::MatrixXi &cells, std::ostream &os)
void write_cells (const std::vector< std::vector< int > > &cells, const bool is_simplex, std::ostream &os)
Private Attributes
bool is_volume_
bool binary_
std::vector< VTKDataNode< double > > point_data_
std::vector< VTKDataNode< double > > cell_data_
std::string current_scalar_point_data_
std::string current_vector_point_data_
Detailed Description
Definition at line 79 of file VTUWriter.hpp.
Constructor & Destructor Documentation
VTUWriter()
polyfem::mesh::VTUWriter::VTUWriter (bool binary = true)
Definition at line 67 of file VTUWriter.cpp.
Member Function Documentation
add_field()
void polyfem::mesh::VTUWriter::add_field (const std::string & name, const Eigen::MatrixXd & data)
Definition at line 366 of file VTUWriter.cpp.
References add_scalar_field(), add_vector_field(), and p_bases::tmp.
Referenced by polyfem::State::save_surface(), polyfem::State::save_volume(), and polyfem::State::save_wire().
add_scalar_field()
void polyfem::mesh::VTUWriter::add_scalar_field (const std::string & name, const Eigen::MatrixXd & data)
Definition at line 382 of file VTUWriter.cpp.
References binary_, current_scalar_point_data_, and point_data_.
Referenced by add_field().
add_vector_field()
void polyfem::mesh::VTUWriter::add_vector_field (const std::string & name, const Eigen::MatrixXd & data)
Definition at line 389 of file VTUWriter.cpp.
References binary_, current_vector_point_data_, and point_data_.
Referenced by add_field().
clear()
void polyfem::mesh::VTUWriter::clear ()
Definition at line 360 of file VTUWriter.cpp.
References cell_data_, and point_data_.
Referenced by write_mesh().
write_cells() [1/2]
void polyfem::mesh::VTUWriter::write_cells (const Eigen::MatrixXi & cells, std::ostream & os) private
Definition at line 155 of file VTUWriter.cpp.
References binary_, polyfem::utils::base64Layer::close(), is_volume_, p_bases::tmp, and polyfem::utils::base64Layer::write().
Referenced by write_mesh().
write_cells() [2/2]
void polyfem::mesh::VTUWriter::write_cells (const std::vector< std::vector< int > > & cells, const bool is_simplex, std::ostream & os) private
Definition at line 252 of file VTUWriter.cpp.
References binary_, polyfem::utils::base64Layer::close(), is_volume_, p_bases::tmp, and polyfem::utils::base64Layer::write().
write_footer()
void polyfem::mesh::VTUWriter::write_footer (std::ostream & os) private
Definition at line 98 of file VTUWriter.cpp.
Referenced by write_mesh().
write_header()
void polyfem::mesh::VTUWriter::write_header (const int n_vertices, const int n_elements, std::ostream & os) private
Definition at line 91 of file VTUWriter.cpp.
Referenced by write_mesh().
write_mesh() [1/2]
bool polyfem::mesh::VTUWriter::write_mesh (const std::string & path, const Eigen::MatrixXd & points, const Eigen::MatrixXi & cells)
Definition at line 408 of file VTUWriter.cpp.
References clear(), is_volume_, eigs::path, p_bases::points, write_cells(), write_footer(), write_header(), write_point_data(), and write_points().
Referenced by polyfem::State::save_surface(), polyfem::State::save_volume(), and polyfem::State::save_wire().
write_mesh() [2/2]
bool polyfem::mesh::VTUWriter::write_mesh (const std::string & path, const Eigen::MatrixXd & points, const std::vector< std::vector< int > > & cells, const bool is_simplicial)
Definition at line 431 of file VTUWriter.cpp.
References clear(), is_volume_, eigs::path, p_bases::points, write_cells(), write_footer(), write_header(), write_point_data(), and write_points().
write_point_data()
void polyfem::mesh::VTUWriter::write_point_data (std::ostream & os) private
Definition at line 71 of file VTUWriter.cpp.
References current_scalar_point_data_, current_vector_point_data_, and point_data_.
Referenced by write_mesh().
write_points()
void polyfem::mesh::VTUWriter::write_points (const Eigen::MatrixXd & points, std::ostream & os) private
Definition at line 105 of file VTUWriter.cpp.
References binary_, polyfem::utils::base64Layer::close(), is_volume_, p_bases::points, p_bases::tmp, and polyfem::utils::base64Layer::write().
Referenced by write_mesh().
Member Data Documentation
binary_
bool polyfem::mesh::VTUWriter::binary_ private
Definition at line 95 of file VTUWriter.hpp.
Referenced by add_scalar_field(), add_vector_field(), write_cells(), and write_points().
cell_data_
std::vector<VTKDataNode<double> > polyfem::mesh::VTUWriter::cell_data_ private
Definition at line 98 of file VTUWriter.hpp.
Referenced by clear().
current_scalar_point_data_
std::string polyfem::mesh::VTUWriter::current_scalar_point_data_ private
Definition at line 99 of file VTUWriter.hpp.
Referenced by add_scalar_field(), and write_point_data().
current_vector_point_data_
std::string polyfem::mesh::VTUWriter::current_vector_point_data_ private
Definition at line 100 of file VTUWriter.hpp.
Referenced by add_vector_field(), and write_point_data().
is_volume_
bool polyfem::mesh::VTUWriter::is_volume_ private
Definition at line 94 of file VTUWriter.hpp.
Referenced by write_cells(), write_mesh(), and write_points().
point_data_
std::vector<VTKDataNode<double> > polyfem::mesh::VTUWriter::point_data_ private
Definition at line 97 of file VTUWriter.hpp.
Referenced by add_scalar_field(), add_vector_field(), clear(), and write_point_data().
The documentation for this class was generated from the following files:
src/polyfem/mesh/VTUWriter.hpp
src/polyfem/mesh/VTUWriter.cpp