PolyFEM: polyfem::solver::CompositeParametrization Class Reference
polyfem::solver::CompositeParametrization Class Reference
#include <Parametrization.hpp>
Public Member Functions
CompositeParametrization ()
CompositeParametrization (std::vector< std::shared_ptr< Parametrization > > &&parametrizations)
virtual ~CompositeParametrization ()
Eigen::VectorXd inverse_eval (const Eigen::VectorXd &y) override
int size (const int x_size) const override
Eigen::VectorXd eval (const Eigen::VectorXd &x) const override
Eigen::VectorXd apply_jacobian (const Eigen::VectorXd &grad_full, const Eigen::VectorXd &x) const override
Public Member Functions inherited from polyfem::solver::Parametrization
Parametrization ()
virtual ~Parametrization ()
Private Attributes
const std::vector< std::shared_ptr< Parametrization > > parametrizations_
Detailed Description
Definition at line 26 of file Parametrization.hpp.
Constructor & Destructor Documentation
CompositeParametrization() [1/2]
polyfem::solver::CompositeParametrization::CompositeParametrization () inline
Definition at line 29 of file Parametrization.hpp.
CompositeParametrization() [2/2]
polyfem::solver::CompositeParametrization::CompositeParametrization (std::vector< std::shared_ptr< Parametrization > > && parametrizations) inline
Definition at line 30 of file Parametrization.hpp.
~CompositeParametrization()
virtual polyfem::solver::CompositeParametrization::~CompositeParametrization () inline virtual
Definition at line 31 of file Parametrization.hpp.
Member Function Documentation
apply_jacobian()
Eigen::VectorXd polyfem::solver::CompositeParametrization::apply_jacobian (const Eigen::VectorXd & grad_full, const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 48 of file Parametrization.cpp.
References apply_jacobian(), parametrizations_, x, and y.
Referenced by apply_jacobian(), polyfem::solver::VariableToSimulation::apply_parametrization_jacobian(), polyfem::solver::ParametrizationForm::compute_partial_gradient(), and polyfem::solver::ParametrizationForm::post_step().
eval()
Eigen::VectorXd polyfem::solver::CompositeParametrization::eval (const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 35 of file Parametrization.cpp.
References parametrizations_, x, and y.
Referenced by polyfem::solver::ParametrizationForm::apply_parametrizations(), and polyfem::solver::VariableToSimulation::update().
inverse_eval()
Eigen::VectorXd polyfem::solver::CompositeParametrization::inverse_eval (const Eigen::VectorXd & y) override virtual
Reimplemented from polyfem::solver::Parametrization.
Definition at line 21 of file Parametrization.cpp.
References parametrizations_, x, and y.
Referenced by polyfem::solver::ShapeVariableToSimulation::inverse_eval(), polyfem::solver::ElasticVariableToSimulation::inverse_eval(), polyfem::solver::DirichletVariableToSimulation::inverse_eval(), and polyfem::solver::PressureVariableToSimulation::inverse_eval().
size()
int polyfem::solver::CompositeParametrization::size (const int x_size) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 12 of file Parametrization.cpp.
References parametrizations_.
Referenced by polyfem::solver::VariableToSimulation::get_output_indexing().
Member Data Documentation
parametrizations_
const std::vector<std::shared_ptr<Parametrization> > polyfem::solver::CompositeParametrization::parametrizations_ private
Definition at line 40 of file Parametrization.hpp.
Referenced by apply_jacobian(), eval(), inverse_eval(), and size().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/parametrization/Parametrization.hpp
src/polyfem/solver/forms/parametrization/Parametrization.cpp