PolyFEM: polyfem::varform::BilaplacianVarForm Class Reference
polyfem::varform::BilaplacianVarForm Class Reference
#include <BilaplacianVarForm.hpp>
Public Member Functions
std::string name () const override
Get the name of the variational formulation.
void init (const std::string &formulation, const Units &units, const json &args, const std::string &out_path) override
Initialize the variational formulation with the given parameters.
void save_json (const Eigen::MatrixXd &solution, std::ostream &out) const override
Save the solution to a JSON file, for output purposes.
void export_data (const Eigen::MatrixXd &solution) const override
io::OutputSpace output_space () const override
Get the output space of the variational formulation, for output purposes.
io::OutStatsData compute_errors (const Eigen::MatrixXd &solution) override
Get the error statistics of the variational formulation, for output purposes.
std::vector< io::OutputField > output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options) const override
Get the output fields of the variational formulation, for output purposes.
Public Member Functions inherited from polyfem::varform::VarForm
virtual ~VarForm ()=default
void set_args (const json &args)
Reset the internal state of the variational formulation, e.g.
void set_mesh (std::unique_ptr< mesh::Mesh > mesh, const double loading_mesh_time=0)
Set the mesh for the variational formulation.
void solve (Eigen::MatrixXd &sol)
Solve the variational formulation and store the solution in the given matrix.
void set_time_callback (const std::function< void(int, int, double, double)> &callback)
int problem_dimension () const
Get the problem dimension of the variational formulation, for output purposes.
virtual bool is_contact_enabled () const
Check if contact is enabled for the variational formulation, for output purposes.
const io::OutRuntimeData & output_timings () const
Get the runtime timings of the variational formulation, for output purposes.
void save_json (const Eigen::MatrixXd &solution) const
Save the solution to a JSON file, for output purposes.
Private Member Functions
void reset () override
void load_mesh (const mesh::Mesh &mesh, const json &args) override
void build_basis (mesh::Mesh &mesh, const bool iso_parametric, const json &args) override
void assemble_rhs (const mesh::Mesh &mesh) override
void assemble_mass_mat (const mesh::Mesh &mesh, const json &args) override
void solve_problem (Eigen::MatrixXd &sol) override
int stacked_ndof () const
void prepare_initial_solution (Eigen::MatrixXd &sol) const
void split_solution (const Eigen::MatrixXd &stacked, Eigen::MatrixXd &primary, Eigen::MatrixXd &pressure) const
void build_stiffness_mat (StiffnessMatrix &stiffness)
void solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > &solver, StiffnessMatrix &A, Eigen::VectorXd &b, const bool compute_spectrum, Eigen::MatrixXd &sol)
void solve_static_linear (Eigen::MatrixXd &sol)
void solve_transient_linear (Eigen::MatrixXd &sol)
void build_rhs_assembler () override
std::shared_ptr< assembler::RhsAssembler > build_rhs_assembler (const int n_bases, const std::vector< basis::ElementBases > &bases, const assembler::AssemblyValsCache &ass_vals_cache)
Private Attributes
FESpace space_
FESpace pressure_space_
VarFormBoundaryState boundary_
VarFormBoundaryState pressure_boundary_
assembler::AssemblyValsCache ass_vals_cache_
assembler::AssemblyValsCache pressure_ass_vals_cache_
assembler::AssemblyValsCache mass_ass_vals_cache_
assembler::AssemblyValsCache pure_mass_ass_vals_cache_
std::shared_ptr< assembler::RhsAssembler > rhs_assembler_
StiffnessMatrix mass_
StiffnessMatrix pure_mass_
double avg_mass_ = 0
Eigen::MatrixXd rhs_
std::shared_ptr< assembler::Assembler > primary_assembler_ = nullptr
std::shared_ptr< assembler::Mass > mass_assembler_ = nullptr
std::shared_ptr< assembler::HRZMass > pure_mass_assembler_ = nullptr
std::shared_ptr< assembler::MixedAssembler > mixed_assembler_ = nullptr
std::shared_ptr< assembler::Assembler > pressure_assembler_ = nullptr
double t0 = 0
int time_steps = 0
double dt = 0
std::shared_ptr< time_integrator::ImplicitTimeIntegrator > time_integrator
Friends
class polyfem::test::VarFormTestAccess
Additional Inherited Members
Protected Member Functions inherited from polyfem::varform::VarForm
std::string resolve_output_path (const std::string &path) const
std::string resolve_input_path (const std::string &path, const bool only_if_exists=false) const
void set_materials (assembler::Assembler &assembler, const int size) const
void assign_discr_orders (const json &discr_order, const mesh::Mesh &mesh, Eigen::VectorXi &disc_orders)
void prepare ()
QuadratureOrders n_boundary_samples (const int discr_order, const int gdiscr_order) const
void build_fe_space (mesh::Mesh &mesh, const bool iso_parametric, const Eigen::VectorXi &disc_orders, const std::string &basis_type, const std::string &poly_basis_type, const assembler::Assembler &space_assembler, const int value_dim, const int quadrature_order, const int mass_quadrature_order, const bool use_corner_quadrature, const int n_harmonic_samples, const int integral_constraints, FESpace &space, VarFormBoundaryState &boundary, std::shared_ptr< GeometryMapping > geometry=nullptr)
std::shared_ptr< time_integrator::BDF > make_bdf_time_integrator () const
void save_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator, const bool rest_mesh_written=false) const
void ensure_output_sampler () const
void save_restart_json (const double t0, const double dt, const int t, const bool rest_mesh_written) const
void save_timestep (const double time, const int t, const double t0, const double dt, const Eigen::MatrixXd &solution) const
void save_subsolve (const int i, const int t, const Eigen::MatrixXd &solution) const
int output_file_index (const int t) const
void notify_time_step (const int t, const int time_steps, const double t0, const double dt) const
io::OutGeometryData::ExportOptions export_options (const io::OutputSpace &space) const
io::OutputFieldFunction output_field_function (const Eigen::MatrixXd &solution, const io::OutGeometryData::ExportOptions &opts) const
Static Protected Member Functions inherited from polyfem::varform::VarForm
static bool read_initial_x_from_file (const std::string &state_path, const std::string &x_name, const bool reorder, const Eigen::VectorXi &in_node_to_node, const int dim, Eigen::MatrixXd &x)
static void rebuild_node_positions (const std::vector< basis::ElementBases > &bases, const std::vector< int > &node_ids, std::vector< RowVectorNd > &positions)
Protected Attributes inherited from polyfem::varform::VarForm
std::shared_ptr< assembler::Problem > problem
current problem, it contains rhs and bc
Units units
json args
io::OutStatsData stats
io::OutRuntimeData timings
runtime statistics
std::string root_path
std::string output_path
std::unique_ptr< mesh::Mesh > mesh_
std::function< void(int, int, double, double)> time_callback
io::OutGeometryData output_geometry_
bool output_sampler_initialized_ = false
bool prepared_ = false
Detailed Description
Definition at line 15 of file BilaplacianVarForm.hpp.
Member Function Documentation
assemble_mass_mat()
void polyfem::varform::BilaplacianVarForm::assemble_mass_mat (const mesh::Mesh & mesh, const json & args) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 470 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::io::OutRuntimeData::assembling_mass_mat_time, avg_mass_, polyfem::varform::FESpace::basis_list(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::utils::lump_matrix(), mass_, mass_ass_vals_cache_, mass_assembler_, polyfem::io::OutStatsData::mat_size, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::nn_zero, polyfem::io::OutStatsData::num_dofs, polyfem::varform::VarForm::problem, space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
assemble_rhs()
void polyfem::varform::BilaplacianVarForm::assemble_rhs (const mesh::Mesh & mesh) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 422 of file BilaplacianVarForm.cpp.
References polyfem::io::OutRuntimeData::assigning_rhs_time, polyfem::varform::FESpace::basis_list(), boundary_, polyfem::mesh::Mesh::bounding_box(), build_rhs_assembler(), polyfem::varform::FESpace::disc_orders, polyfem::mesh::Mesh::is_volume(), polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::logger(), mass_assembler_, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::n_boundary_samples(), pressure_ass_vals_cache_, pressure_space_, primary_assembler_, polyfem::varform::VarForm::problem, rhs_, rhs_assembler_, polyfem::varform::VarForm::root_path, space_, and polyfem::varform::VarForm::timings.
build_basis()
void polyfem::varform::BilaplacianVarForm::build_basis (mesh::Mesh & mesh, const bool iso_parametric, const json & args) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 277 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, ass_vals_cache_, polyfem::varform::VarForm::assign_discr_orders(), polyfem::varform::FESpace::bases, polyfem::varform::FESpace::basis_list(), boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, polyfem::varform::VarForm::build_fe_space(), build_rhs_assembler(), polyfem::varform::VarFormBoundaryState::clear_boundary_conditions(), polyfem::io::OutStatsData::compute_mesh_size(), polyfem::io::OutStatsData::count_flipped_elements(), polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::geometry, polyfem::varform::FESpace::geometry_basis_list(), polyfem::assembler::AssemblyValsCache::init(), polyfem::assembler::AssemblyValsCache::init_empty(), polyfem::mesh::Mesh::is_volume(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::varform::VarFormBoundaryState::local_pressure_boundary, polyfem::varform::VarFormBoundaryState::local_pressure_cavity, polyfem::log_and_throw_error(), polyfem::logger(), mass_ass_vals_cache_, mass_assembler_, polyfem::io::OutStatsData::mesh_size, polyfem::varform::FESpace::n_bases, polyfem::mesh::Mesh::n_elements(), polyfem::io::OutStatsData::n_flipped, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, polyfem::varform::VarFormBoundaryState::normalize_boundary_nodes(), polyfem::refinement::APriori::p_refine(), polyfem::varform::FESpace::poly_edge_to_data, pressure_ass_vals_cache_, pressure_boundary_, pressure_space_, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_ass_vals_cache_, pure_mass_assembler_, polyfem::varform::VarForm::rebuild_node_positions(), space_, polyfem::varform::FESpace::space_in_node_to_node, polyfem::varform::VarForm::stats, polyfem::varform::VarFormBoundaryState::total_local_boundary, and polyfem::mesh::Mesh::update_nodes().
build_rhs_assembler() [1/2]
void polyfem::varform::BilaplacianVarForm::build_rhs_assembler () inline override private virtual
Implements polyfem::varform::VarForm.
Definition at line 54 of file BilaplacianVarForm.hpp.
References polyfem::varform::FESpace::basis_list(), build_rhs_assembler(), mass_ass_vals_cache_, polyfem::varform::FESpace::n_bases, rhs_assembler_, and space_.
Referenced by assemble_rhs(), build_basis(), and build_rhs_assembler().
build_rhs_assembler() [2/2]
std::shared_ptr< assembler::RhsAssembler > polyfem::varform::BilaplacianVarForm::build_rhs_assembler (const int n_bases, const std::vector< basis::ElementBases > & bases, const assembler::AssemblyValsCache & ass_vals_cache) private
Definition at line 258 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, boundary_, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, primary_assembler_, polyfem::varform::VarForm::problem, and space_.
build_stiffness_mat()
void polyfem::varform::BilaplacianVarForm::build_stiffness_mat (StiffnessMatrix & stiffness) private
Definition at line 550 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, ass_vals_cache_, polyfem::io::OutRuntimeData::assembling_stiffness_mat_time, polyfem::varform::FESpace::basis_list(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::logger(), polyfem::io::OutStatsData::mat_size, polyfem::assembler::AssemblerUtils::merge_mixed_matrices(), polyfem::varform::VarForm::mesh_, mixed_assembler_, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::nn_zero, polyfem::io::OutStatsData::num_dofs, pressure_ass_vals_cache_, pressure_assembler_, pressure_space_, primary_assembler_, space_, polyfem::varform::VarForm::stats, polyfem::varform::VarForm::timings, and polyfem::varform::internal::write_matrix_market().
Referenced by solve_static_linear(), and solve_transient_linear().
compute_errors()
io::OutStatsData polyfem::varform::BilaplacianVarForm::compute_errors (const Eigen::MatrixXd & solution) override virtual
Get the error statistics of the variational formulation, for output purposes.
Returns
Error statistics
Implements polyfem::varform::VarForm.
Definition at line 144 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::io::OutStatsData::compute_errors(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::problem, space_, split_solution(), and polyfem::varform::VarForm::stats.
export_data()
void polyfem::varform::BilaplacianVarForm::export_data (const Eigen::MatrixXd & solution) const override virtual
Implements polyfem::varform::VarForm.
Definition at line 159 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::io::Evaluator::compute_stress_at_quadrature_points(), polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, dt, polyfem::varform::VarForm::ensure_output_sampler(), polyfem::io::OutGeometryData::export_data(), polyfem::varform::VarForm::export_options(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::logger(), polyfem::io::OutputSpace::mesh, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::output_field_function(), polyfem::varform::VarForm::output_geometry_, output_space(), primary_assembler_, polyfem::varform::VarForm::problem, polyfem::varform::VarForm::resolve_output_path(), space_, polyfem::varform::FESpace::space_in_node_to_node, split_solution(), polyfem::utils::unflatten(), and polyfem::io::write_matrix().
init()
void polyfem::varform::BilaplacianVarForm::init (const std::string & formulation, const Units & units, const json & args, const std::string & out_path) override virtual
Initialize the variational formulation with the given parameters.
Parameters
formulation name of the variational formulation
units unit system to use for the formulation
args json input arguments, used to initialize the formulation
out_path output path for the formulation, used to save intermediate data
Reimplemented from polyfem::varform::VarForm.
Definition at line 53 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, dt, polyfem::problem::ProblemFactory::factory(), polyfem::problem::ProblemFactory::get_problem(), polyfem::varform::VarForm::init(), polyfem::assembler::AssemblerUtils::make_assembler(), polyfem::assembler::AssemblerUtils::make_mixed_assembler(), mass_assembler_, mixed_assembler_, polyfem::assembler::AssemblerUtils::other_assembler_name(), pressure_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_assembler_, polyfem::varform::VarForm::root_path, t0, time_steps, and polyfem::varform::VarForm::units.
load_mesh()
void polyfem::varform::BilaplacianVarForm::load_mesh (const mesh::Mesh & mesh, const json & args) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 245 of file BilaplacianVarForm.cpp.
References mass_assembler_, mixed_assembler_, pressure_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_assembler_, and polyfem::varform::VarForm::set_materials().
name()
std::string polyfem::varform::BilaplacianVarForm::name () const inline override virtual
Get the name of the variational formulation.
Returns
Name of the variational formulation
Implements polyfem::varform::VarForm.
Definition at line 20 of file BilaplacianVarForm.hpp.
Referenced by save_json().
output_fields()
std::vector< io::OutputField > polyfem::varform::BilaplacianVarForm::output_fields (const io::OutputSample & sample, const Eigen::MatrixXd & solution, const io::OutputFieldOptions & options) const override virtual
Get the output fields of the variational formulation, for output purposes.
Parameters
sample Output sample
solution Solution matrix
options Output field options
Returns
Output fields
Implements polyfem::varform::VarForm.
Definition at line 691 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::utils::count_invalid(), polyfem::io::OutputSample::element_ids, polyfem::io::OutputFieldOptions::export_field(), polyfem::io::OutputFieldOptions::fields, polyfem::varform::FESpace::geometry_basis_list(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::io::OutputSample::local_points, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::io::OutputSample::node_ids, polyfem::io::OutputField::Point, polyfem::io::OutputSample::points, polyfem::io::OutputSample::primitive_ids, polyfem::varform::VarForm::problem, space_, split_solution(), and polyfem::io::OutputSample::time.
output_space()
io::OutputSpace polyfem::varform::BilaplacianVarForm::output_space () const override virtual
Get the output space of the variational formulation, for output purposes.
Returns
Output space
Implements polyfem::varform::VarForm.
Definition at line 119 of file BilaplacianVarForm.cpp.
References boundary_, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::polys, polyfem::varform::FESpace::polys_3d, space_, and polyfem::varform::VarFormBoundaryState::total_local_boundary.
Referenced by export_data().
prepare_initial_solution()
void polyfem::varform::BilaplacianVarForm::prepare_initial_solution (Eigen::MatrixXd & sol) const private
Definition at line 507 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::n_bases, pressure_space_, polyfem::varform::VarForm::problem, polyfem::varform::VarForm::read_initial_x_from_file(), polyfem::varform::VarForm::resolve_input_path(), rhs_, rhs_assembler_, space_, polyfem::varform::FESpace::space_in_node_to_node, and stacked_ndof().
Referenced by solve_problem().
reset()
void polyfem::varform::BilaplacianVarForm::reset () override private virtual
Implements polyfem::varform::VarForm.
Definition at line 26 of file BilaplacianVarForm.cpp.
References ass_vals_cache_, avg_mass_, boundary_, dt, polyfem::assembler::AssemblyValsCache::init_empty(), mass_, mass_ass_vals_cache_, mass_assembler_, mixed_assembler_, pressure_ass_vals_cache_, pressure_assembler_, pressure_boundary_, pressure_space_, primary_assembler_, pure_mass_, pure_mass_ass_vals_cache_, pure_mass_assembler_, polyfem::varform::FESpace::reset(), polyfem::varform::VarFormBoundaryState::reset(), polyfem::varform::VarForm::reset(), rhs_, rhs_assembler_, space_, t0, time_integrator, and time_steps.
save_json()
void polyfem::varform::BilaplacianVarForm::save_json (const Eigen::MatrixXd & solution, std::ostream & out) const override virtual
Save the solution to a JSON file, for output purposes.
Parameters
solution Solution matrix to save
out Output stream to save the solution
Implements polyfem::varform::VarForm.
Definition at line 91 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, polyfem::varform::FESpace::is_iso_parametric(), polyfem::logger(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, name(), pressure_space_, primary_assembler_, polyfem::varform::VarForm::problem, polyfem::io::OutStatsData::save_json(), space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
solve_linear_system()
void polyfem::varform::BilaplacianVarForm::solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > & solver, StiffnessMatrix & A, Eigen::VectorXd & b, const bool compute_spectrum, Eigen::MatrixXd & sol) private
Definition at line 574 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::solver_info, space_, polyfem::io::OutStatsData::spectrum, polyfem::varform::VarForm::stats, and x.
Referenced by solve_static_linear(), and solve_transient_linear().
solve_problem()
void polyfem::varform::BilaplacianVarForm::solve_problem (Eigen::MatrixXd & sol) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 672 of file BilaplacianVarForm.cpp.
References polyfem::logger(), prepare_initial_solution(), primary_assembler_, polyfem::varform::VarForm::problem, solve_static_linear(), solve_transient_linear(), polyfem::io::OutRuntimeData::solving_time, polyfem::io::OutStatsData::spectrum, polyfem::varform::VarForm::stats, time_integrator, and polyfem::varform::VarForm::timings.
solve_static_linear()
void polyfem::varform::BilaplacianVarForm::solve_static_linear (Eigen::MatrixXd & sol) private
Definition at line 597 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, build_stiffness_mat(), polyfem::varform::FESpace::disc_orders, polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::logger(), polyfem::varform::VarForm::mesh_, polyfem::varform::VarForm::n_boundary_samples(), primary_assembler_, rhs_, rhs_assembler_, solve_linear_system(), and space_.
Referenced by solve_problem().
solve_transient_linear()
void polyfem::varform::BilaplacianVarForm::solve_transient_linear (Eigen::MatrixXd & sol) private
Definition at line 612 of file BilaplacianVarForm.cpp.
References polyfem::varform::VarForm::args, boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, build_stiffness_mat(), polyfem::varform::FESpace::disc_orders, dt, polyfem::varform::internal::expand_primary_matrix(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::logger(), polyfem::varform::VarForm::make_bdf_time_integrator(), mass_, mass_assembler_, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::n_boundary_samples(), polyfem::varform::VarForm::notify_time_step(), pressure_space_, rhs_, rhs_assembler_, polyfem::varform::VarForm::save_step_state(), polyfem::varform::VarForm::save_timestep(), solve_linear_system(), space_, split_solution(), stacked_ndof(), t0, time_integrator, and time_steps.
Referenced by solve_problem().
split_solution()
void polyfem::varform::BilaplacianVarForm::split_solution (const Eigen::MatrixXd & stacked, Eigen::MatrixXd & primary, Eigen::MatrixXd & pressure) const private
Definition at line 534 of file BilaplacianVarForm.cpp.
References polyfem::varform::FESpace::n_bases, pressure_space_, and space_.
Referenced by compute_errors(), export_data(), output_fields(), and solve_transient_linear().
stacked_ndof()
int polyfem::varform::BilaplacianVarForm::stacked_ndof () const private
Definition at line 502 of file BilaplacianVarForm.cpp.
References polyfem::varform::FESpace::n_bases, pressure_space_, and space_.
Referenced by prepare_initial_solution(), and solve_transient_linear().
Friends And Related Symbol Documentation
polyfem::test::VarFormTestAccess
friend class polyfem::test::VarFormTestAccess friend
Definition at line 17 of file BilaplacianVarForm.hpp.
Member Data Documentation
ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::BilaplacianVarForm::ass_vals_cache_ private
Definition at line 70 of file BilaplacianVarForm.hpp.
Referenced by build_basis(), build_stiffness_mat(), and reset().
avg_mass_
double polyfem::varform::BilaplacianVarForm::avg_mass_ = 0 private
Definition at line 80 of file BilaplacianVarForm.hpp.
Referenced by assemble_mass_mat(), and reset().
boundary_
VarFormBoundaryState polyfem::varform::BilaplacianVarForm::boundary_ private
Definition at line 67 of file BilaplacianVarForm.hpp.
Referenced by assemble_rhs(), build_basis(), build_rhs_assembler(), output_space(), reset(), solve_linear_system(), solve_static_linear(), and solve_transient_linear().
dt
double polyfem::varform::BilaplacianVarForm::dt = 0 private
Definition at line 91 of file BilaplacianVarForm.hpp.
Referenced by export_data(), init(), reset(), and solve_transient_linear().
mass_
StiffnessMatrix polyfem::varform::BilaplacianVarForm::mass_ private
Definition at line 77 of file BilaplacianVarForm.hpp.
Referenced by assemble_mass_mat(), reset(), and solve_transient_linear().
mass_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::BilaplacianVarForm::mass_ass_vals_cache_ private
Definition at line 72 of file BilaplacianVarForm.hpp.
Referenced by assemble_mass_mat(), build_basis(), build_rhs_assembler(), and reset().
mass_assembler_
std::shared_ptr<assembler::Mass> polyfem::varform::BilaplacianVarForm::mass_assembler_ = nullptr private
Definition at line 84 of file BilaplacianVarForm.hpp.
Referenced by assemble_mass_mat(), assemble_rhs(), build_basis(), init(), load_mesh(), reset(), and solve_transient_linear().
mixed_assembler_
std::shared_ptr<assembler::MixedAssembler> polyfem::varform::BilaplacianVarForm::mixed_assembler_ = nullptr private
Definition at line 86 of file BilaplacianVarForm.hpp.
Referenced by build_stiffness_mat(), init(), load_mesh(), and reset().
pressure_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::BilaplacianVarForm::pressure_ass_vals_cache_ private
Definition at line 71 of file BilaplacianVarForm.hpp.
Referenced by assemble_rhs(), build_basis(), build_stiffness_mat(), and reset().
pressure_assembler_
std::shared_ptr<assembler::Assembler> polyfem::varform::BilaplacianVarForm::pressure_assembler_ = nullptr private
Definition at line 87 of file BilaplacianVarForm.hpp.
Referenced by build_stiffness_mat(), init(), load_mesh(), and reset().
pressure_boundary_
VarFormBoundaryState polyfem::varform::BilaplacianVarForm::pressure_boundary_ private
Definition at line 68 of file BilaplacianVarForm.hpp.
Referenced by build_basis(), and reset().
pressure_space_
FESpace polyfem::varform::BilaplacianVarForm::pressure_space_ private
Definition at line 65 of file BilaplacianVarForm.hpp.
Referenced by assemble_rhs(), build_basis(), build_stiffness_mat(), prepare_initial_solution(), reset(), save_json(), solve_transient_linear(), split_solution(), and stacked_ndof().
primary_assembler_
std::shared_ptr<assembler::Assembler> polyfem::varform::BilaplacianVarForm::primary_assembler_ = nullptr private
Definition at line 83 of file BilaplacianVarForm.hpp.
Referenced by assemble_rhs(), build_basis(), build_rhs_assembler(), build_stiffness_mat(), export_data(), init(), load_mesh(), reset(), save_json(), solve_problem(), and solve_static_linear().
pure_mass_
StiffnessMatrix polyfem::varform::BilaplacianVarForm::pure_mass_ private
Definition at line 78 of file BilaplacianVarForm.hpp.
Referenced by reset().
pure_mass_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::BilaplacianVarForm::pure_mass_ass_vals_cache_ private
Definition at line 73 of file BilaplacianVarForm.hpp.
Referenced by build_basis(), and reset().
pure_mass_assembler_
std::shared_ptr<assembler::HRZMass> polyfem::varform::BilaplacianVarForm::pure_mass_assembler_ = nullptr private
Definition at line 85 of file BilaplacianVarForm.hpp.
Referenced by build_basis(), init(), load_mesh(), and reset().
rhs_
Eigen::MatrixXd polyfem::varform::BilaplacianVarForm::rhs_ private
Definition at line 81 of file BilaplacianVarForm.hpp.
Referenced by assemble_rhs(), prepare_initial_solution(), reset(), solve_static_linear(), and solve_transient_linear().
rhs_assembler_
std::shared_ptr<assembler::RhsAssembler> polyfem::varform::BilaplacianVarForm::rhs_assembler_ private
Definition at line 75 of file BilaplacianVarForm.hpp.
Referenced by assemble_rhs(), build_rhs_assembler(), prepare_initial_solution(), reset(), solve_static_linear(), and solve_transient_linear().
space_
FESpace polyfem::varform::BilaplacianVarForm::space_ private
Definition at line 64 of file BilaplacianVarForm.hpp.
Referenced by assemble_mass_mat(), assemble_rhs(), build_basis(), build_rhs_assembler(), build_rhs_assembler(), build_stiffness_mat(), compute_errors(), export_data(), output_fields(), output_space(), prepare_initial_solution(), reset(), save_json(), solve_linear_system(), solve_static_linear(), solve_transient_linear(), split_solution(), and stacked_ndof().
t0
double polyfem::varform::BilaplacianVarForm::t0 = 0 private
Definition at line 89 of file BilaplacianVarForm.hpp.
Referenced by init(), reset(), and solve_transient_linear().
time_integrator
std::shared_ptr<time_integrator::ImplicitTimeIntegrator> polyfem::varform::BilaplacianVarForm::time_integrator private
Definition at line 92 of file BilaplacianVarForm.hpp.
Referenced by reset(), solve_problem(), and solve_transient_linear().
time_steps
int polyfem::varform::BilaplacianVarForm::time_steps = 0 private
Definition at line 90 of file BilaplacianVarForm.hpp.
Referenced by init(), reset(), and solve_transient_linear().
The documentation for this class was generated from the following files:
src/polyfem/varforms/BilaplacianVarForm.hpp
src/polyfem/varforms/BilaplacianVarForm.cpp