PolyFEM: polyfem::assembler::MooneyRivlinElasticity Class Reference
polyfem::assembler::MooneyRivlinElasticity Class Reference
#include <MooneyRivlinElasticity.hpp>
Public Member Functions
MooneyRivlinElasticity ()
void add_multimaterial (const int index, const json &params, const Units &units) override
const GenericMatParam & c1 () const
const GenericMatParam & c2 () const
const GenericMatParam & k () const
std::string name () const override
std::map< std::string, ParamFunc > parameters () const override
template<typename T >
T elastic_energy (const RowVectorNd &p, const int el_id, const DefGradMatrix< T > &def_grad) const
Public Member Functions inherited from polyfem::assembler::GenericElastic< MooneyRivlinElasticity >
GenericElastic ()
virtual ~GenericElastic ()=default
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const =0
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const override
void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const override
MooneyRivlinElasticity & derived ()
Returns this as a reference to derived class.
const MooneyRivlinElasticity & derived () const
Returns this as a const reference to derived class.
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual bool is_linear () const override
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual VectorNd compute_rhs (const AutodiffHessianPt &pt) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params, const Units &units)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_fluid () const
Public Member Functions inherited from polyfem::assembler::ElasticityAssembler
ElasticityAssembler ()
virtual ~ElasticityAssembler ()=default
void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &stresses) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
bool is_solution_displacement () const override
bool is_tensor () const override
Private Attributes
GenericMatParam c1_
GenericMatParam c2_
GenericMatParam k_
Additional Inherited Members
Public Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 9 of file MooneyRivlinElasticity.hpp.
Constructor & Destructor Documentation
MooneyRivlinElasticity()
polyfem::assembler::MooneyRivlinElasticity::MooneyRivlinElasticity ()
Definition at line 5 of file MooneyRivlinElasticity.cpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::MooneyRivlinElasticity::add_multimaterial (const int index, const json & params, const Units & units) override virtual
Implements polyfem::assembler::GenericElastic< MooneyRivlinElasticity >.
Definition at line 10 of file MooneyRivlinElasticity.cpp.
References polyfem::assembler::GenericMatParam::add_multimaterial(), c1_, c2_, k_, and polyfem::Units::stress().
Referenced by polyfem::assembler::MultiModel::add_multimaterial().
c1()
const GenericMatParam & polyfem::assembler::MooneyRivlinElasticity::c1 () const inline
Definition at line 17 of file MooneyRivlinElasticity.hpp.
References c1_.
Referenced by elastic_energy(), and parameters().
c2()
const GenericMatParam & polyfem::assembler::MooneyRivlinElasticity::c2 () const inline
Definition at line 18 of file MooneyRivlinElasticity.hpp.
References c2_.
Referenced by elastic_energy(), and parameters().
elastic_energy()
template<typename T > T polyfem::assembler::MooneyRivlinElasticity::elastic_energy (const RowVectorNd & p, const int el_id, const DefGradMatrix< T > & def_grad) const inline
Definition at line 25 of file MooneyRivlinElasticity.hpp.
References c1(), c1_, c2(), c2_, polyfem::utils::determinant(), polyfem::first_invariant(), k(), k_, polyfem::second_invariant(), polyfem::assembler::Assembler::size(), and val.
k()
const GenericMatParam & polyfem::assembler::MooneyRivlinElasticity::k () const inline
Definition at line 19 of file MooneyRivlinElasticity.hpp.
References k_.
Referenced by elastic_energy(), and parameters().
name()
std::string polyfem::assembler::MooneyRivlinElasticity::name () const inline override virtual
Implements polyfem::assembler::Assembler.
Definition at line 21 of file MooneyRivlinElasticity.hpp.
parameters()
std::map< std::string, Assembler::ParamFunc > polyfem::assembler::MooneyRivlinElasticity::parameters () const override virtual
Implements polyfem::assembler::Assembler.
Definition at line 17 of file MooneyRivlinElasticity.cpp.
References c1(), c2(), and k().
Member Data Documentation
c1_
GenericMatParam polyfem::assembler::MooneyRivlinElasticity::c1_ private
Definition at line 50 of file MooneyRivlinElasticity.hpp.
Referenced by add_multimaterial(), c1(), and elastic_energy().
c2_
GenericMatParam polyfem::assembler::MooneyRivlinElasticity::c2_ private
Definition at line 51 of file MooneyRivlinElasticity.hpp.
Referenced by add_multimaterial(), c2(), and elastic_energy().
k_
GenericMatParam polyfem::assembler::MooneyRivlinElasticity::k_ private
Definition at line 52 of file MooneyRivlinElasticity.hpp.
Referenced by add_multimaterial(), elastic_energy(), and k().
The documentation for this class was generated from the following files:
src/polyfem/assembler/MooneyRivlinElasticity.hpp
src/polyfem/assembler/MooneyRivlinElasticity.cpp