PolyFEM: polyfem::solver::AdjointTools Class Reference
polyfem::solver::AdjointTools Class Reference
#include <AdjointTools.hpp>
Public Member Functions
AdjointTools ()
Static Public Member Functions
static double integrate_objective (const State &state, const IntegrableFunctional &j, const Eigen::MatrixXd &solution, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step=0)
static void dJ_du_step (const State &state, const IntegrableFunctional &j, const Eigen::MatrixXd &solution, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step, Eigen::VectorXd &term)
static void dJ_macro_strain_adjoint_term (const State &state, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
static void compute_macro_strain_derivative_functional_term (const State &state, const Eigen::MatrixXd &solution, const IntegrableFunctional &j, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, Eigen::VectorXd &term, const int cur_time_step)
static void compute_shape_derivative_functional_term (const State &state, const Eigen::MatrixXd &solution, const IntegrableFunctional &j, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, Eigen::VectorXd &term, const int cur_time_step)
static void dJ_shape_static_adjoint_term (const State &state, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
static void dJ_shape_transient_adjoint_term (const State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
static void dJ_material_static_adjoint_term (const State &state, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
static void dJ_material_transient_adjoint_term (const State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
static void dJ_friction_transient_adjoint_term (const State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
static void dJ_damping_transient_adjoint_term (const State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
static void dJ_initial_condition_adjoint_term (const State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
static void dJ_dirichlet_transient_adjoint_term (const State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
static Eigen::VectorXd map_primitive_to_node_order (const State &state, const Eigen::VectorXd &primitives)
static Eigen::VectorXd map_node_to_primitive_order (const State &state, const Eigen::VectorXd &nodes)
static Eigen::MatrixXd edge_normal_gradient (const Eigen::MatrixXd &V)
static Eigen::MatrixXd face_normal_gradient (const Eigen::MatrixXd &V)
static Eigen::MatrixXd edge_velocity_divergence (const Eigen::MatrixXd &V)
static Eigen::MatrixXd face_velocity_divergence (const Eigen::MatrixXd &V)
Detailed Description
Definition at line 32 of file AdjointTools.hpp.
Constructor & Destructor Documentation
AdjointTools()
polyfem::solver::AdjointTools::AdjointTools () inline
Definition at line 35 of file AdjointTools.hpp.
Member Function Documentation
compute_macro_strain_derivative_functional_term()
void polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term (const State & state, const Eigen::MatrixXd & solution, const IntegrableFunctional & j, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, Eigen::VectorXd & term, const int cur_time_step) static
Definition at line 575 of file AdjointTools.cpp.
References polyfem::State::ass_vals_cache, polyfem::State::assembler, polyfem::State::bases, polyfem::assembler::AssemblyValsCache::compute(), polyfem::utils::create_thread_storage(), polyfem::IntegrableFunctional::depend_on_gradu(), polyfem::assembler::ElementAssemblyValues::det, polyfem::IntegrableFunctional::dj_dgradu(), polyfem::State::geom_bases(), polyfem::utils::get_local_thread_storage(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::log_and_throw_adjoint_error(), polyfem::utils::maybe_parallel_for(), polyfem::State::mesh, polyfem::quadrature::Quadrature::points, polyfem::State::problem, polyfem::assembler::ElementAssemblyValues::quadrature, quadrature, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::solver::volume, and polyfem::quadrature::Quadrature::weights.
compute_shape_derivative_functional_term()
void polyfem::solver::AdjointTools::compute_shape_derivative_functional_term (const State & state, const Eigen::MatrixXd & solution, const IntegrableFunctional & j, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, Eigen::VectorXd & term, const int cur_time_step) static
Definition at line 336 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::State::ass_vals_cache, polyfem::State::assembler, polyfem::State::bases, polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::utils::BoundarySampler::boundary_quadrature(), polyfem::assembler::AssemblyValsCache::compute(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::utils::create_thread_storage(), polyfem::IntegrableFunctional::depend_on_gradu(), polyfem::IntegrableFunctional::depend_on_gradx(), polyfem::IntegrableFunctional::depend_on_x(), polyfem::assembler::ElementAssemblyValues::det, polyfem::IntegrableFunctional::dj_dgradu(), polyfem::IntegrableFunctional::dj_dgradx(), polyfem::IntegrableFunctional::dj_dx(), edge_velocity_divergence(), polyfem::IntegrableFunctional::evaluate(), face_velocity_divergence(), polyfem::State::geom_bases(), polyfem::utils::get_local_thread_storage(), polyfem::assembler::AssemblyValues::global, polyfem::assembler::AssemblyValues::grad, polyfem::assembler::AssemblyValues::grad_t_m, gvals, polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::log_and_throw_adjoint_error(), polyfem::utils::maybe_parallel_for(), polyfem::State::mesh, polyfem::State::n_boundary_samples(), polyfem::State::n_geom_bases, polyfem::quadrature::Quadrature::points, polyfem::State::problem, polyfem::assembler::ElementAssemblyValues::quadrature, quadrature, polyfem::solver::surface, polyfem::State::total_local_boundary, V, polyfem::assembler::AssemblyValues::val, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::utils::vector2matrix(), polyfem::solver::volume, and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::solver::SpatialIntegralForm::compute_partial_gradient_unweighted_step().
dJ_damping_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_damping_transient_adjoint_term (const State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form) static
Definition at line 843 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::time_integrator::BDF::betas(), polyfem::State::boundary_nodes, polyfem::utils::create_thread_storage(), polyfem::solver::SolveData::damping_form, polyfem::State::diff_cached, polyfem::utils::get_local_thread_storage(), polyfem::utils::maybe_parallel_for(), polyfem::State::solve_data, and polyfem::solver::DiffCache::u().
Referenced by polyfem::solver::DampingCoeffientVariableToSimulation::compute_adjoint_term().
dJ_dirichlet_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_dirichlet_transient_adjoint_term (const State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form) static
Definition at line 899 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::time_integrator::BDF::betas(), and polyfem::State::boundary_nodes.
Referenced by polyfem::solver::DirichletVariableToSimulation::compute_adjoint_term().
dJ_du_step()
void polyfem::solver::AdjointTools::dJ_du_step (const State & state, const IntegrableFunctional & j, const Eigen::MatrixXd & solution, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step, Eigen::VectorXd & term) static
Definition at line 920 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::State::ass_vals_cache, polyfem::State::assembler, polyfem::State::bases, polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::utils::BoundarySampler::boundary_quadrature(), polyfem::assembler::AssemblyValsCache::compute(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::utils::create_thread_storage(), polyfem::IntegrableFunctional::depend_on_gradu(), polyfem::IntegrableFunctional::depend_on_gradu_local(), polyfem::IntegrableFunctional::depend_on_u(), polyfem::assembler::ElementAssemblyValues::det, polyfem::IntegrableFunctional::dj_dgradu(), polyfem::IntegrableFunctional::dj_dgradu_local(), polyfem::IntegrableFunctional::dj_du(), polyfem::State::geom_bases(), polyfem::utils::get_local_thread_storage(), polyfem::assembler::AssemblyValues::global, polyfem::assembler::AssemblyValues::grad, polyfem::assembler::AssemblyValues::grad_t_m, polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::utils::maybe_parallel_for(), polyfem::State::mesh, polyfem::State::n_bases, polyfem::State::n_boundary_samples(), polyfem::quadrature::Quadrature::points, polyfem::State::problem, polyfem::assembler::ElementAssemblyValues::quadrature, quadrature, polyfem::solver::surface, polyfem::State::total_local_boundary, val, polyfem::assembler::AssemblyValues::val, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::solver::volume, and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::solver::SpatialIntegralForm::compute_adjoint_rhs_unweighted_step().
dJ_friction_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term (const State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form) static
Definition at line 791 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::time_integrator::BDF::betas(), polyfem::State::boundary_nodes, polyfem::State::collision_mesh, polyfem::solver::SolveData::contact_form, polyfem::utils::create_thread_storage(), polyfem::State::diff_cached, polyfem::solver::DiffCache::friction_constraint_set(), polyfem::solver::SolveData::friction_form, polyfem::utils::get_local_thread_storage(), polyfem::utils::maybe_parallel_for(), polyfem::State::mesh, polyfem::State::solve_data, polyfem::solver::DiffCache::u(), and polyfem::utils::unflatten().
Referenced by polyfem::solver::FrictionCoeffientVariableToSimulation::compute_adjoint_term().
dJ_initial_condition_adjoint_term()
void polyfem::solver::AdjointTools::dJ_initial_condition_adjoint_term (const State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form) static
Definition at line 879 of file AdjointTools.cpp.
References polyfem::State::boundary_nodes, and polyfem::State::ndof().
Referenced by polyfem::solver::InitialConditionVariableToSimulation::compute_adjoint_term().
dJ_macro_strain_adjoint_term()
void polyfem::solver::AdjointTools::dJ_macro_strain_adjoint_term (const State & state, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form) static
Definition at line 157 of file AdjointTools.cpp.
References polyfem::State::bases, polyfem::utils::create_thread_storage(), polyfem::State::geom_bases(), polyfem::utils::maybe_parallel_for(), and polyfem::State::mesh.
dJ_material_static_adjoint_term()
void polyfem::solver::AdjointTools::dJ_material_static_adjoint_term (const State & state, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form) static
Definition at line 746 of file AdjointTools.cpp.
References polyfem::solver::SolveData::elastic_form, and polyfem::State::solve_data.
Referenced by polyfem::solver::ElasticVariableToSimulation::compute_adjoint_term().
dJ_material_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_material_transient_adjoint_term (const State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form) static
Definition at line 755 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::State::bases, polyfem::time_integrator::BDF::betas(), polyfem::State::boundary_nodes, polyfem::utils::create_thread_storage(), polyfem::State::diff_cached, polyfem::solver::SolveData::elastic_form, polyfem::utils::get_local_thread_storage(), polyfem::utils::maybe_parallel_for(), polyfem::State::solve_data, and polyfem::solver::DiffCache::u().
Referenced by polyfem::solver::ElasticVariableToSimulation::compute_adjoint_term().
dJ_shape_static_adjoint_term()
void polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term (const State & state, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form) static
Definition at line 635 of file AdjointTools.cpp.
References polyfem::solver::SolveData::body_form, polyfem::solver::SolveData::contact_form, polyfem::solver::DiffCache::contact_set(), polyfem::State::diff_cached, polyfem::solver::SolveData::elastic_form, polyfem::utils::flatten(), polyfem::State::gbasis_nodes_to_basis_nodes, polyfem::State::is_contact_enabled(), polyfem::State::mesh, polyfem::State::n_geom_bases, polyfem::State::primitive_to_node(), polyfem::State::solve_data, and polyfem::utils::unflatten().
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term().
dJ_shape_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term (const State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form) static
Definition at line 666 of file AdjointTools.cpp.
References polyfem::time_integrator::BDF::alphas(), polyfem::State::args, polyfem::State::bases, polyfem::time_integrator::BDF::betas(), polyfem::solver::SolveData::body_form, polyfem::State::boundary_nodes, polyfem::solver::SolveData::contact_form, polyfem::solver::DiffCache::contact_set(), polyfem::solver::SolveData::damping_form, polyfem::State::diff_cached, polyfem::solver::SolveData::elastic_form, polyfem::utils::flatten(), polyfem::solver::DiffCache::friction_constraint_set(), polyfem::solver::SolveData::friction_form, polyfem::State::gbasis_nodes_to_basis_nodes, polyfem::State::geom_bases(), polyfem::solver::SolveData::inertia_form, polyfem::State::is_contact_enabled(), polyfem::State::mass_ass_vals_cache, polyfem::State::mass_matrix_assembler, polyfem::State::mesh, polyfem::State::n_geom_bases, polyfem::State::primitive_to_node(), polyfem::State::solve_data, polyfem::solver::DiffCache::u(), polyfem::utils::unflatten(), and polyfem::solver::DiffCache::v().
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term().
edge_normal_gradient()
Eigen::MatrixXd polyfem::solver::AdjointTools::edge_normal_gradient (const Eigen::MatrixXd & V) static
Definition at line 1178 of file AdjointTools.cpp.
References DiffScalarBase::setVariableCount(), and V.
edge_velocity_divergence()
Eigen::MatrixXd polyfem::solver::AdjointTools::edge_velocity_divergence (const Eigen::MatrixXd & V) static
Definition at line 1210 of file AdjointTools.cpp.
References V.
Referenced by compute_shape_derivative_functional_term().
face_normal_gradient()
Eigen::MatrixXd polyfem::solver::AdjointTools::face_normal_gradient (const Eigen::MatrixXd & V) static
Definition at line 1194 of file AdjointTools.cpp.
References DiffScalarBase::setVariableCount(), and V.
face_velocity_divergence()
Eigen::MatrixXd polyfem::solver::AdjointTools::face_velocity_divergence (const Eigen::MatrixXd & V) static
Definition at line 1215 of file AdjointTools.cpp.
References V.
Referenced by compute_shape_derivative_functional_term().
integrate_objective()
double polyfem::solver::AdjointTools::integrate_objective (const State & state, const IntegrableFunctional & j, const Eigen::MatrixXd & solution, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step = 0) static
Definition at line 202 of file AdjointTools.cpp.
References polyfem::State::args, polyfem::State::ass_vals_cache, polyfem::State::assembler, polyfem::State::bases, polyfem::utils::BoundarySampler::boundary_quadrature(), polyfem::assembler::AssemblyValsCache::compute(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::utils::create_thread_storage(), polyfem::assembler::ElementAssemblyValues::det, polyfem::IntegrableFunctional::evaluate(), polyfem::State::geom_bases(), polyfem::utils::get_local_thread_storage(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::utils::maybe_parallel_for(), polyfem::State::mesh, polyfem::State::n_boundary_samples(), polyfem::quadrature::Quadrature::points, polyfem::State::problem, polyfem::assembler::ElementAssemblyValues::quadrature, quadrature, polyfem::solver::surface, polyfem::State::total_local_boundary, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::solver::volume, and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::solver::SpatialIntegralForm::value_unweighted_step().
map_node_to_primitive_order()
Eigen::VectorXd polyfem::solver::AdjointTools::map_node_to_primitive_order (const State & state, const Eigen::VectorXd & nodes) static
Definition at line 1167 of file AdjointTools.cpp.
References polyfem::State::mesh, polyfem::State::n_geom_bases, and polyfem::State::node_to_primitive().
Referenced by polyfem::solver::AMIPSForm::compute_partial_gradient_unweighted().
map_primitive_to_node_order()
Eigen::VectorXd polyfem::solver::AdjointTools::map_primitive_to_node_order (const State & state, const Eigen::VectorXd & primitives) static
Definition at line 1156 of file AdjointTools.cpp.
References polyfem::State::mesh, polyfem::State::n_geom_bases, and polyfem::State::primitive_to_node().
Referenced by polyfem::solver::AMIPSForm::compute_partial_gradient_unweighted(), polyfem::solver::CollisionBarrierForm::get_updated_mesh_nodes(), polyfem::solver::DeformedCollisionBarrierForm::get_updated_mesh_nodes(), and polyfem::solver::AMIPSForm::value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/AdjointTools.hpp
src/polyfem/solver/AdjointTools.cpp