PolyFEM: polyfem::ElasticityTensor Class Reference
polyfem::ElasticityTensor Class Reference
#include <ElasticityUtils.hpp>
Public Member Functions
void resize (const int size)
double operator() (int i, int j) const
double & operator() (int i, int j)
void set_from_entries (const std::vector< double > &entries)
void set_from_lambda_mu (const double lambda, const double mu)
void set_from_young_poisson (const double young, const double poisson)
void set_orthotropic (double Ex, double Ey, double Ez, double nuYX, double nuZX, double nuZY, double muYZ, double muZX, double muXY)
void set_orthotropic (double Ex, double Ey, double nuYX, double muXY)
template<int DIM>
double compute_stress (const std::array< double, DIM > &strain, const int j) const
Private Attributes
Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, 0, 6, 6 > stifness_tensor_
int size_
Detailed Description
Definition at line 52 of file ElasticityUtils.hpp.
Member Function Documentation
compute_stress()
template<int DIM> template double polyfem::ElasticityTensor::compute_stress< 6 > (const std::array< double, DIM > & strain, const int j) const
Definition at line 469 of file ElasticityUtils.cpp.
Referenced by polyfem::assembler::HookeLinearElasticity::assemble(), and polyfem::assembler::HookeLinearElasticity::assign_stress_tensor().
operator()() [1/2]
double & polyfem::ElasticityTensor::operator() (int i, int j)
Definition at line 287 of file ElasticityUtils.cpp.
References stifness_tensor_.
operator()() [2/2]
double polyfem::ElasticityTensor::operator() (int i, int j) const
Definition at line 276 of file ElasticityUtils.cpp.
References stifness_tensor_.
resize()
void polyfem::ElasticityTensor::resize (const int size)
Definition at line 264 of file ElasticityUtils.cpp.
References size_, and stifness_tensor_.
Referenced by polyfem::assembler::HookeLinearElasticity::set_size(), and polyfem::assembler::SaintVenantElasticity::set_size().
set_from_entries()
void polyfem::ElasticityTensor::set_from_entries (const std::vector< double > & entries)
Definition at line 298 of file ElasticityUtils.cpp.
References entries, set_orthotropic(), and size_.
Referenced by polyfem::assembler::HookeLinearElasticity::add_multimaterial(), and polyfem::assembler::SaintVenantElasticity::add_multimaterial().
set_from_lambda_mu()
void polyfem::ElasticityTensor::set_from_lambda_mu (const double lambda, const double mu)
Definition at line 372 of file ElasticityUtils.cpp.
References size_.
Referenced by polyfem::assembler::HookeLinearElasticity::add_multimaterial(), and polyfem::assembler::SaintVenantElasticity::add_multimaterial().
set_from_young_poisson()
void polyfem::ElasticityTensor::set_from_young_poisson (const double young, const double poisson)
Definition at line 416 of file ElasticityUtils.cpp.
References size_, and stifness_tensor_.
Referenced by polyfem::assembler::HookeLinearElasticity::add_multimaterial(), and polyfem::assembler::SaintVenantElasticity::add_multimaterial().
set_orthotropic() [1/2]
void polyfem::ElasticityTensor::set_orthotropic (double Ex, double Ey, double Ez, double nuYX, double nuZX, double nuZY, double muYZ, double muZX, double muXY)
Definition at line 439 of file ElasticityUtils.cpp.
References size_, and stifness_tensor_.
Referenced by set_from_entries().
set_orthotropic() [2/2]
void polyfem::ElasticityTensor::set_orthotropic (double Ex, double Ey, double nuYX, double muXY)
Definition at line 457 of file ElasticityUtils.cpp.
References size_, and stifness_tensor_.
Member Data Documentation
size_
int polyfem::ElasticityTensor::size_ private
Definition at line 75 of file ElasticityUtils.hpp.
Referenced by resize(), set_from_entries(), set_from_lambda_mu(), set_from_young_poisson(), and set_orthotropic().
stifness_tensor_
Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, 0, 6, 6> polyfem::ElasticityTensor::stifness_tensor_ private
Definition at line 74 of file ElasticityUtils.hpp.
Referenced by operator()(), resize(), set_from_young_poisson(), and set_orthotropic().
The documentation for this class was generated from the following files:
src/polyfem/utils/ElasticityUtils.hpp
src/polyfem/utils/ElasticityUtils.cpp