PolyFEM: polyfem::LameParameters Class Reference
polyfem::LameParameters Class Reference
#include <ElasticityUtils.hpp>
Public Member Functions
LameParameters ()
void add_multimaterial (const int index, const json &params, const bool is_volume)
void lambda_mu (double px, double py, double pz, double x, double y, double z, int el_id, double &lambda, double &mu) const
void lambda_mu (const Eigen::MatrixXd &param, const Eigen::MatrixXd &p, int el_id, double &lambda, double &mu) const
Private Member Functions
void set_e_nu (const int index, const json &E, const json &nu)
Private Attributes
int size_
std::vector< utils::ExpressionValue > lambda_or_E_
std::vector< utils::ExpressionValue > mu_or_nu_
bool is_lambda_mu_
Detailed Description
Definition at line 78 of file ElasticityUtils.hpp.
Constructor & Destructor Documentation
LameParameters()
polyfem::LameParameters::LameParameters ()
Definition at line 479 of file ElasticityUtils.cpp.
References is_lambda_mu_, lambda_or_E_, mu_or_nu_, and size_.
Member Function Documentation
add_multimaterial()
void polyfem::LameParameters::add_multimaterial (const int index, const json & params, const bool is_volume)
Definition at line 519 of file ElasticityUtils.cpp.
References is_lambda_mu_, lambda_or_E_, mu_or_nu_, set_e_nu(), and size_.
Referenced by polyfem::assembler::IncompressibleLinearElasticityDispacement::add_multimaterial(), polyfem::assembler::IncompressibleLinearElasticityPressure::add_multimaterial(), polyfem::assembler::LinearElasticity::add_multimaterial(), and polyfem::assembler::NeoHookeanElasticity::add_multimaterial().
lambda_mu() [1/2]
void polyfem::LameParameters::lambda_mu (const Eigen::MatrixXd & param, const Eigen::MatrixXd & p, int el_id, double & lambda, double & mu) const inline
Definition at line 86 of file ElasticityUtils.hpp.
References lambda_mu().
lambda_mu() [2/2]
void polyfem::LameParameters::lambda_mu (double px, double py, double pz, double x, double y, double z, int el_id, double & lambda, double & mu) const
Definition at line 490 of file ElasticityUtils.cpp.
References polyfem::convert_to_lambda(), polyfem::convert_to_mu(), is_lambda_mu_, lambda_or_E_, mu_or_nu_, size_, x, y, and z.
Referenced by polyfem::assembler::IncompressibleLinearElasticityDispacement::assemble(), polyfem::assembler::IncompressibleLinearElasticityPressure::assemble(), polyfem::assembler::LinearElasticity::assemble(), polyfem::assembler::IncompressibleLinearElasticityDispacement::assign_stress_tensor(), polyfem::assembler::LinearElasticity::assign_stress_tensor(), polyfem::assembler::NeoHookeanElasticity::assign_stress_tensor(), polyfem::assembler::LinearElasticity::compute_dstress_dgradu_multiply_mat(), polyfem::assembler::NeoHookeanElasticity::compute_dstress_dgradu_multiply_mat(), polyfem::assembler::LinearElasticity::compute_energy_aux(), polyfem::assembler::NeoHookeanElasticity::compute_energy_aux(), polyfem::assembler::NeoHookeanElasticity::compute_energy_aux_gradient_fast(), polyfem::assembler::NeoHookeanElasticity::compute_energy_hessian_aux_fast(), polyfem::assembler::LinearElasticity::compute_rhs(), polyfem::assembler::NeoHookeanElasticity::compute_rhs(), polyfem::assembler::LinearElasticity::kernel(), lambda_mu(), polyfem::State::save_surface(), and polyfem::State::save_volume().
set_e_nu()
void polyfem::LameParameters::set_e_nu (const int index, const json & E, const json & nu) private
Definition at line 547 of file ElasticityUtils.cpp.
References is_lambda_mu_, lambda_or_E_, and mu_or_nu_.
Referenced by add_multimaterial().
Member Data Documentation
is_lambda_mu_
bool polyfem::LameParameters::is_lambda_mu_ private
Definition at line 100 of file ElasticityUtils.hpp.
Referenced by add_multimaterial(), lambda_mu(), LameParameters(), and set_e_nu().
lambda_or_E_
std::vector<utils::ExpressionValue> polyfem::LameParameters::lambda_or_E_ private
Definition at line 99 of file ElasticityUtils.hpp.
Referenced by add_multimaterial(), lambda_mu(), LameParameters(), and set_e_nu().
mu_or_nu_
std::vector<utils::ExpressionValue> polyfem::LameParameters::mu_or_nu_ private
Definition at line 99 of file ElasticityUtils.hpp.
Referenced by add_multimaterial(), lambda_mu(), LameParameters(), and set_e_nu().
size_
int polyfem::LameParameters::size_ private
Definition at line 98 of file ElasticityUtils.hpp.
Referenced by add_multimaterial(), lambda_mu(), and LameParameters().
The documentation for this class was generated from the following files:
src/polyfem/utils/ElasticityUtils.hpp
src/polyfem/utils/ElasticityUtils.cpp