PolyFEM: cppoptlib::BFGSSolver< ProblemType > Class Template Reference
cppoptlib::BFGSSolver< ProblemType > Class Template Reference
#include <BFGSSolver.hpp>
Public Types
using Superclass = NonlinearSolver< ProblemType >
Public Types inherited from cppoptlib::NonlinearSolver< ProblemType >
using Superclass = ISolver< ProblemType, -1 >
Public Member Functions
BFGSSolver (const json &solver_params, const double dt, const double characteristic_length)
std::string name () const override
Public Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
NonlinearSolver (const polyfem::json &solver_params, const double dt, const double characteristic_length)
Construct a new Nonlinear Solver object.
virtual double compute_grad_norm (const Eigen::VectorXd &x, const Eigen::VectorXd &grad) const
void set_line_search (const std::string &line_search_name)
void minimize (ProblemType &objFunc, TVector &x) override
double line_search (const TVector &x, const TVector &delta_x, ProblemType &objFunc)
const polyfem::json & get_info () const
ErrorCode error_code () const
const Superclass::TCriteria & getStopCriteria ()
bool converged () const
size_t max_iterations () const
size_t & max_iterations ()
Protected Member Functions
virtual int default_descent_strategy () override
std::string descent_strategy_name (int descent_strategy) const override
void increase_descent_strategy () override
void reset (const int ndof) override
void reset_history (const int ndof)
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x, const TVector &grad, TVector &direction) override
virtual std::string descent_strategy_name (int descent_strategy) const=0
virtual std::string descent_strategy_name () const
Protected Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
virtual void update_solver_info (const double energy)
void reset_times ()
void log_times ()
Protected Attributes
TVector m_prev_x
TVector m_prev_grad
Eigen::MatrixXd hess
Protected Attributes inherited from cppoptlib::NonlinearSolver< ProblemType >
bool normalize_gradient
double use_grad_norm_tol
double first_grad_norm_tol
double dt
std::shared_ptr< polyfem::solver::line_search::LineSearch< ProblemType > > m_line_search
int descent_strategy
polyfem::json solver_info
double total_time
double grad_time
double assembly_time
double inverting_time
double line_search_time
double constraint_set_update_time
double obj_fun_time
ErrorCode m_error_code
Additional Inherited Members
Public Attributes inherited from cppoptlib::NonlinearSolver< ProblemType >
bool allow_out_of_iterations = false
Detailed Description
template<typename ProblemType>
class cppoptlib::BFGSSolver< ProblemType >
Definition at line 19 of file BFGSSolver.hpp.
Member Typedef Documentation
Superclass
template<typename ProblemType > using cppoptlib::BFGSSolver< ProblemType >::Superclass = NonlinearSolver<ProblemType>
Definition at line 22 of file BFGSSolver.hpp.
Constructor & Destructor Documentation
BFGSSolver()
template<typename ProblemType > cppoptlib::BFGSSolver< ProblemType >::BFGSSolver (const json & solver_params, const double dt, const double characteristic_length) inline
Definition at line 26 of file BFGSSolver.hpp.
Member Function Documentation
compute_update_direction()
template<typename ProblemType > virtual bool cppoptlib::BFGSSolver< ProblemType >::compute_update_direction (ProblemType & objFunc, const TVector & x, const TVector & grad, TVector & direction) inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 82 of file BFGSSolver.hpp.
References cppoptlib::BFGSSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::BFGSSolver< ProblemType >::descent_strategy_name(), cppoptlib::BFGSSolver< ProblemType >::hess, cppoptlib::BFGSSolver< ProblemType >::increase_descent_strategy(), polyfem::logger(), cppoptlib::BFGSSolver< ProblemType >::m_prev_grad, cppoptlib::BFGSSolver< ProblemType >::m_prev_x, cppoptlib::BFGSSolver< ProblemType >::reset_history(), x, and y.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction().
default_descent_strategy()
template<typename ProblemType > virtual int cppoptlib::BFGSSolver< ProblemType >::default_descent_strategy () inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 34 of file BFGSSolver.hpp.
descent_strategy_name() [1/3]
template<typename ProblemType > virtual std::string cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name () const inline protected virtual
Reimplemented from cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 92 of file NonlinearSolver.hpp.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction().
descent_strategy_name() [2/3]
template<typename ProblemType > std::string cppoptlib::BFGSSolver< ProblemType >::descent_strategy_name (int descent_strategy) const inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 37 of file BFGSSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy.
descent_strategy_name() [3/3]
template<typename ProblemType > virtual std::string cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name (int descent_strategy) const protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
increase_descent_strategy()
template<typename ProblemType > void cppoptlib::BFGSSolver< ProblemType >::increase_descent_strategy () inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 50 of file BFGSSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction().
name()
template<typename ProblemType > std::string cppoptlib::BFGSSolver< ProblemType >::name () const inline override virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 31 of file BFGSSolver.hpp.
reset()
template<typename ProblemType > void cppoptlib::BFGSSolver< ProblemType >::reset (const int ndof) inline override protected virtual
Reimplemented from cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 64 of file BFGSSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::reset(), and cppoptlib::BFGSSolver< ProblemType >::reset_history().
reset_history()
template<typename ProblemType > void cppoptlib::BFGSSolver< ProblemType >::reset_history (const int ndof) inline protected
Definition at line 71 of file BFGSSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::BFGSSolver< ProblemType >::hess, cppoptlib::BFGSSolver< ProblemType >::m_prev_grad, and cppoptlib::BFGSSolver< ProblemType >::m_prev_x.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction(), and cppoptlib::BFGSSolver< ProblemType >::reset().
Member Data Documentation
hess
template<typename ProblemType > Eigen::MatrixXd cppoptlib::BFGSSolver< ProblemType >::hess protected
Definition at line 62 of file BFGSSolver.hpp.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction(), and cppoptlib::BFGSSolver< ProblemType >::reset_history().
m_prev_grad
template<typename ProblemType > TVector cppoptlib::BFGSSolver< ProblemType >::m_prev_grad protected
Definition at line 60 of file BFGSSolver.hpp.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction(), and cppoptlib::BFGSSolver< ProblemType >::reset_history().
m_prev_x
template<typename ProblemType > TVector cppoptlib::BFGSSolver< ProblemType >::m_prev_x protected
Definition at line 59 of file BFGSSolver.hpp.
Referenced by cppoptlib::BFGSSolver< ProblemType >::compute_update_direction(), and cppoptlib::BFGSSolver< ProblemType >::reset_history().
The documentation for this class was generated from the following file:
src/polyfem/solver/BFGSSolver.hpp