PolyFEM: polyfem::varform::ScalarVarForm Class Reference
polyfem::varform::ScalarVarForm Class Reference
#include <ScalarVarForm.hpp>
Public Member Functions
std::string name () const override
Get the name of the variational formulation.
void init (const std::string &formulation, const Units &units, const json &args, const std::string &out_path) override
Initialize the variational formulation with the given parameters.
void save_json (const Eigen::MatrixXd &solution, std::ostream &out) const override
Save the solution to a JSON file, for output purposes.
void export_data (const Eigen::MatrixXd &solution) const override
io::OutputSpace output_space () const override
Get the output space of the variational formulation, for output purposes.
io::OutStatsData compute_errors (const Eigen::MatrixXd &solution) override
Get the error statistics of the variational formulation, for output purposes.
std::vector< io::OutputField > output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options) const override
Get the output fields of the variational formulation, for output purposes.
Public Member Functions inherited from polyfem::varform::VarForm
virtual ~VarForm ()=default
void set_args (const json &args)
Reset the internal state of the variational formulation, e.g.
void set_mesh (std::unique_ptr< mesh::Mesh > mesh, const double loading_mesh_time=0)
Set the mesh for the variational formulation.
void solve (Eigen::MatrixXd &sol)
Solve the variational formulation and store the solution in the given matrix.
void set_time_callback (const std::function< void(int, int, double, double)> &callback)
int problem_dimension () const
Get the problem dimension of the variational formulation, for output purposes.
virtual bool is_contact_enabled () const
Check if contact is enabled for the variational formulation, for output purposes.
const io::OutRuntimeData & output_timings () const
Get the runtime timings of the variational formulation, for output purposes.
void save_json (const Eigen::MatrixXd &solution) const
Save the solution to a JSON file, for output purposes.
Protected Member Functions
void reset () override
void load_mesh (const mesh::Mesh &mesh, const json &args) override
void build_basis (mesh::Mesh &mesh, const bool iso_parametric, const json &args) override
void assemble_rhs (const mesh::Mesh &mesh) override
void assemble_mass_mat (const mesh::Mesh &mesh, const json &args) override
Protected Member Functions inherited from polyfem::varform::VarForm
std::string resolve_output_path (const std::string &path) const
std::string resolve_input_path (const std::string &path, const bool only_if_exists=false) const
void set_materials (assembler::Assembler &assembler, const int size) const
void assign_discr_orders (const json &discr_order, const mesh::Mesh &mesh, Eigen::VectorXi &disc_orders)
void prepare ()
QuadratureOrders n_boundary_samples (const int discr_order, const int gdiscr_order) const
void build_fe_space (mesh::Mesh &mesh, const bool iso_parametric, const Eigen::VectorXi &disc_orders, const std::string &basis_type, const std::string &poly_basis_type, const assembler::Assembler &space_assembler, const int value_dim, const int quadrature_order, const int mass_quadrature_order, const bool use_corner_quadrature, const int n_harmonic_samples, const int integral_constraints, FESpace &space, VarFormBoundaryState &boundary, std::shared_ptr< GeometryMapping > geometry=nullptr)
std::shared_ptr< time_integrator::BDF > make_bdf_time_integrator () const
void save_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator, const bool rest_mesh_written=false) const
void ensure_output_sampler () const
void save_restart_json (const double t0, const double dt, const int t, const bool rest_mesh_written) const
void save_timestep (const double time, const int t, const double t0, const double dt, const Eigen::MatrixXd &solution) const
void save_subsolve (const int i, const int t, const Eigen::MatrixXd &solution) const
int output_file_index (const int t) const
void notify_time_step (const int t, const int time_steps, const double t0, const double dt) const
io::OutGeometryData::ExportOptions export_options (const io::OutputSpace &space) const
io::OutputFieldFunction output_field_function (const Eigen::MatrixXd &solution, const io::OutGeometryData::ExportOptions &opts) const
Private Member Functions
void build_rhs_assembler () override
void prepare_initial_solution (Eigen::MatrixXd &solution) const
void build_stiffness_mat (StiffnessMatrix &stiffness)
void solve_problem (Eigen::MatrixXd &sol) override
void solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > &solver, StiffnessMatrix &A, Eigen::VectorXd &b, const bool compute_spectrum, Eigen::MatrixXd &sol)
void solve_static (Eigen::MatrixXd &sol)
void solve_transient (Eigen::MatrixXd &sol)
Private Attributes
FESpace space_
VarFormBoundaryState boundary_
assembler::AssemblyValsCache ass_vals_cache_
assembler::AssemblyValsCache mass_ass_vals_cache_
assembler::AssemblyValsCache pure_mass_ass_vals_cache_
std::shared_ptr< assembler::RhsAssembler > rhs_assembler_
StiffnessMatrix mass_
StiffnessMatrix pure_mass_
double avg_mass_ = 0
Eigen::MatrixXd rhs_
std::shared_ptr< assembler::Assembler > primary_assembler_ = nullptr
std::shared_ptr< assembler::Mass > mass_assembler_ = nullptr
std::shared_ptr< assembler::HRZMass > pure_mass_assembler_ = nullptr
double t0 = 0
int time_steps = 0
double dt = 0
std::shared_ptr< time_integrator::ImplicitTimeIntegrator > time_integrator
Friends
class polyfem::test::VarFormTestAccess
Additional Inherited Members
Static Protected Member Functions inherited from polyfem::varform::VarForm
static bool read_initial_x_from_file (const std::string &state_path, const std::string &x_name, const bool reorder, const Eigen::VectorXi &in_node_to_node, const int dim, Eigen::MatrixXd &x)
static void rebuild_node_positions (const std::vector< basis::ElementBases > &bases, const std::vector< int > &node_ids, std::vector< RowVectorNd > &positions)
Protected Attributes inherited from polyfem::varform::VarForm
std::shared_ptr< assembler::Problem > problem
current problem, it contains rhs and bc
Units units
json args
io::OutStatsData stats
io::OutRuntimeData timings
runtime statistics
std::string root_path
std::string output_path
std::unique_ptr< mesh::Mesh > mesh_
std::function< void(int, int, double, double)> time_callback
io::OutGeometryData output_geometry_
bool output_sampler_initialized_ = false
bool prepared_ = false
Detailed Description
Definition at line 14 of file ScalarVarForm.hpp.
Member Function Documentation
assemble_mass_mat()
void polyfem::varform::ScalarVarForm::assemble_mass_mat (const mesh::Mesh & mesh, const json & args) override protected virtual
Implements polyfem::varform::VarForm.
Definition at line 271 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::io::OutRuntimeData::assembling_mass_mat_time, avg_mass_, polyfem::varform::FESpace::basis_list(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::utils::lump_matrix(), mass_, mass_ass_vals_cache_, mass_assembler_, polyfem::io::OutStatsData::mat_size, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::nn_zero, polyfem::io::OutStatsData::num_dofs, polyfem::varform::VarForm::problem, space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
assemble_rhs()
void polyfem::varform::ScalarVarForm::assemble_rhs (const mesh::Mesh & mesh) override protected virtual
Implements polyfem::varform::VarForm.
Definition at line 240 of file ScalarVarForm.cpp.
References polyfem::io::OutRuntimeData::assigning_rhs_time, polyfem::mesh::Mesh::bounding_box(), build_rhs_assembler(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), mass_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, rhs_, rhs_assembler_, polyfem::varform::VarForm::root_path, and polyfem::varform::VarForm::timings.
build_basis()
void polyfem::varform::ScalarVarForm::build_basis (mesh::Mesh & mesh, const bool iso_parametric, const json & args) override protected virtual
Implements polyfem::varform::VarForm.
Definition at line 108 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, ass_vals_cache_, polyfem::varform::VarForm::assign_discr_orders(), polyfem::varform::FESpace::basis_list(), boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, polyfem::varform::VarForm::build_fe_space(), polyfem::varform::VarFormBoundaryState::clear_boundary_conditions(), polyfem::io::OutStatsData::compute_mesh_size(), polyfem::io::OutStatsData::count_flipped_elements(), polyfem::assembler::Dirichlet, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::geometry_basis_list(), polyfem::mesh::Mesh::get_node_id(), polyfem::assembler::AssemblyValsCache::init(), polyfem::assembler::AssemblyValsCache::init_empty(), polyfem::mesh::Mesh::is_volume(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::logger(), mass_ass_vals_cache_, mass_assembler_, polyfem::io::OutStatsData::mesh_size, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::n_flipped, polyfem::assembler::Neumann, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, polyfem::varform::VarFormBoundaryState::normalize_boundary_nodes(), polyfem::refinement::APriori::p_refine(), primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_ass_vals_cache_, pure_mass_assembler_, polyfem::varform::VarForm::rebuild_node_positions(), space_, polyfem::varform::FESpace::space_in_node_to_node, polyfem::varform::VarForm::stats, polyfem::varform::VarFormBoundaryState::total_local_boundary, and polyfem::mesh::Mesh::update_nodes().
build_rhs_assembler()
void polyfem::varform::ScalarVarForm::build_rhs_assembler () override private virtual
Implements polyfem::varform::VarForm.
Definition at line 224 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), boundary_, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::geometry_basis_list(), mass_ass_vals_cache_, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, primary_assembler_, polyfem::varform::VarForm::problem, rhs_assembler_, and space_.
Referenced by assemble_rhs().
build_stiffness_mat()
void polyfem::varform::ScalarVarForm::build_stiffness_mat (StiffnessMatrix & stiffness) private
Definition at line 660 of file ScalarVarForm.cpp.
References polyfem::logger(), space_, and polyfem::varform::internal::write_matrix_market().
compute_errors()
io::OutStatsData polyfem::varform::ScalarVarForm::compute_errors (const Eigen::MatrixXd & solution) override virtual
Get the error statistics of the variational formulation, for output purposes.
Returns
Error statistics
Implements polyfem::varform::VarForm.
Definition at line 391 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::io::OutStatsData::compute_errors(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::problem, space_, and polyfem::varform::VarForm::stats.
export_data()
void polyfem::varform::ScalarVarForm::export_data (const Eigen::MatrixXd & solution) const override virtual
Implements polyfem::varform::VarForm.
Definition at line 404 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::io::Evaluator::compute_stress_at_quadrature_points(), polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, dt, polyfem::varform::VarForm::ensure_output_sampler(), polyfem::io::OutGeometryData::export_data(), polyfem::varform::VarForm::export_options(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::logger(), polyfem::io::OutputSpace::mesh, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::output_field_function(), polyfem::varform::VarForm::output_geometry_, output_space(), primary_assembler_, polyfem::varform::VarForm::problem, polyfem::varform::VarForm::resolve_output_path(), space_, polyfem::varform::FESpace::space_in_node_to_node, polyfem::utils::unflatten(), and polyfem::io::write_matrix().
init()
void polyfem::varform::ScalarVarForm::init (const std::string & formulation, const Units & units, const json & args, const std::string & out_path) override virtual
Initialize the variational formulation with the given parameters.
Parameters
formulation name of the variational formulation
units unit system to use for the formulation
args json input arguments, used to initialize the formulation
out_path output path for the formulation, used to save intermediate data
Reimplemented from polyfem::varform::VarForm.
Definition at line 58 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, dt, polyfem::problem::ProblemFactory::factory(), polyfem::problem::ProblemFactory::get_problem(), polyfem::varform::VarForm::init(), polyfem::assembler::AssemblerUtils::make_assembler(), mass_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_assembler_, polyfem::varform::VarForm::root_path, t0, time_steps, and polyfem::varform::VarForm::units.
load_mesh()
void polyfem::varform::ScalarVarForm::load_mesh (const mesh::Mesh & mesh, const json & args) override protected virtual
Implements polyfem::varform::VarForm.
Definition at line 99 of file ScalarVarForm.cpp.
References mass_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_assembler_, and polyfem::varform::VarForm::set_materials().
name()
std::string polyfem::varform::ScalarVarForm::name () const inline override virtual
Get the name of the variational formulation.
Returns
Name of the variational formulation
Implements polyfem::varform::VarForm.
Definition at line 19 of file ScalarVarForm.hpp.
Referenced by save_json().
output_fields()
std::vector< io::OutputField > polyfem::varform::ScalarVarForm::output_fields (const io::OutputSample & sample, const Eigen::MatrixXd & solution, const io::OutputFieldOptions & options) const override virtual
Get the output fields of the variational formulation, for output purposes.
Parameters
sample Output sample
solution Solution matrix
options Output field options
Returns
Output fields
Implements polyfem::varform::VarForm.
Definition at line 487 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::utils::count_invalid(), polyfem::io::OutputSample::element_ids, polyfem::io::OutputFieldOptions::export_field(), polyfem::io::OutputFieldOptions::fields, polyfem::varform::FESpace::geometry_basis_list(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::io::OutputSample::local_points, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::io::OutputSample::node_ids, polyfem::io::OutputField::Point, polyfem::io::OutputSample::points, polyfem::io::OutputSample::primitive_ids, polyfem::varform::VarForm::problem, space_, and polyfem::io::OutputSample::time.
output_space()
io::OutputSpace polyfem::varform::ScalarVarForm::output_space () const override virtual
Get the output space of the variational formulation, for output purposes.
Returns
Output space
Implements polyfem::varform::VarForm.
Definition at line 366 of file ScalarVarForm.cpp.
References boundary_, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::polys, polyfem::varform::FESpace::polys_3d, space_, and polyfem::varform::VarFormBoundaryState::total_local_boundary.
Referenced by export_data().
prepare_initial_solution()
void polyfem::varform::ScalarVarForm::prepare_initial_solution (Eigen::MatrixXd & solution) const private
Definition at line 316 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::VarForm::problem, polyfem::varform::VarForm::read_initial_x_from_file(), polyfem::varform::VarForm::resolve_input_path(), rhs_, rhs_assembler_, space_, and polyfem::varform::FESpace::space_in_node_to_node.
reset()
void polyfem::varform::ScalarVarForm::reset () override protected virtual
Implements polyfem::varform::VarForm.
Definition at line 36 of file ScalarVarForm.cpp.
References ass_vals_cache_, avg_mass_, boundary_, dt, polyfem::assembler::AssemblyValsCache::init_empty(), mass_, mass_ass_vals_cache_, mass_assembler_, primary_assembler_, pure_mass_, pure_mass_ass_vals_cache_, pure_mass_assembler_, polyfem::varform::FESpace::reset(), polyfem::varform::VarFormBoundaryState::reset(), polyfem::varform::VarForm::reset(), rhs_, rhs_assembler_, space_, t0, time_integrator, and time_steps.
save_json()
void polyfem::varform::ScalarVarForm::save_json (const Eigen::MatrixXd & solution, std::ostream & out) const override virtual
Save the solution to a JSON file, for output purposes.
Parameters
solution Solution matrix to save
out Output stream to save the solution
Implements polyfem::varform::VarForm.
Definition at line 337 of file ScalarVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, polyfem::varform::FESpace::is_iso_parametric(), polyfem::logger(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, name(), primary_assembler_, polyfem::varform::VarForm::problem, polyfem::io::OutStatsData::save_json(), space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
solve_linear_system()
void polyfem::varform::ScalarVarForm::solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > & solver, StiffnessMatrix & A, Eigen::VectorXd & b, const bool compute_spectrum, Eigen::MatrixXd & sol) private
Definition at line 682 of file ScalarVarForm.cpp.
References polyfem::logger(), space_, and x.
solve_problem()
void polyfem::varform::ScalarVarForm::solve_problem (Eigen::MatrixXd & sol) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 784 of file ScalarVarForm.cpp.
References polyfem::logger(), and POLYFEM_SCOPED_TIMER.
solve_static()
void polyfem::varform::ScalarVarForm::solve_static (Eigen::MatrixXd & sol) private
Definition at line 716 of file ScalarVarForm.cpp.
References polyfem::logger(), and space_.
solve_transient()
void polyfem::varform::ScalarVarForm::solve_transient (Eigen::MatrixXd & sol) private
Definition at line 735 of file ScalarVarForm.cpp.
References polyfem::logger(), and space_.
Friends And Related Symbol Documentation
polyfem::test::VarFormTestAccess
friend class polyfem::test::VarFormTestAccess friend
Definition at line 16 of file ScalarVarForm.hpp.
Member Data Documentation
ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::ScalarVarForm::ass_vals_cache_ private
Definition at line 44 of file ScalarVarForm.hpp.
Referenced by build_basis(), and reset().
avg_mass_
double polyfem::varform::ScalarVarForm::avg_mass_ = 0 private
Definition at line 50 of file ScalarVarForm.hpp.
Referenced by assemble_mass_mat(), and reset().
boundary_
VarFormBoundaryState polyfem::varform::ScalarVarForm::boundary_ private
Definition at line 43 of file ScalarVarForm.hpp.
Referenced by build_basis(), build_rhs_assembler(), output_space(), and reset().
dt
double polyfem::varform::ScalarVarForm::dt = 0 private
Definition at line 59 of file ScalarVarForm.hpp.
Referenced by export_data(), init(), and reset().
mass_
StiffnessMatrix polyfem::varform::ScalarVarForm::mass_ private
Definition at line 48 of file ScalarVarForm.hpp.
Referenced by assemble_mass_mat(), and reset().
mass_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::ScalarVarForm::mass_ass_vals_cache_ private
Definition at line 45 of file ScalarVarForm.hpp.
Referenced by assemble_mass_mat(), build_basis(), build_rhs_assembler(), and reset().
mass_assembler_
std::shared_ptr<assembler::Mass> polyfem::varform::ScalarVarForm::mass_assembler_ = nullptr private
Definition at line 54 of file ScalarVarForm.hpp.
Referenced by assemble_mass_mat(), assemble_rhs(), build_basis(), init(), load_mesh(), and reset().
primary_assembler_
std::shared_ptr<assembler::Assembler> polyfem::varform::ScalarVarForm::primary_assembler_ = nullptr private
Definition at line 53 of file ScalarVarForm.hpp.
Referenced by assemble_rhs(), build_basis(), build_rhs_assembler(), export_data(), init(), load_mesh(), reset(), and save_json().
pure_mass_
StiffnessMatrix polyfem::varform::ScalarVarForm::pure_mass_ private
Definition at line 49 of file ScalarVarForm.hpp.
Referenced by reset().
pure_mass_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::ScalarVarForm::pure_mass_ass_vals_cache_ private
Definition at line 46 of file ScalarVarForm.hpp.
Referenced by build_basis(), and reset().
pure_mass_assembler_
std::shared_ptr<assembler::HRZMass> polyfem::varform::ScalarVarForm::pure_mass_assembler_ = nullptr private
Definition at line 55 of file ScalarVarForm.hpp.
Referenced by build_basis(), init(), load_mesh(), and reset().
rhs_
Eigen::MatrixXd polyfem::varform::ScalarVarForm::rhs_ private
Definition at line 51 of file ScalarVarForm.hpp.
Referenced by assemble_rhs(), prepare_initial_solution(), and reset().
rhs_assembler_
std::shared_ptr<assembler::RhsAssembler> polyfem::varform::ScalarVarForm::rhs_assembler_ private
Definition at line 47 of file ScalarVarForm.hpp.
Referenced by assemble_rhs(), build_rhs_assembler(), prepare_initial_solution(), and reset().
space_
FESpace polyfem::varform::ScalarVarForm::space_ private
Definition at line 42 of file ScalarVarForm.hpp.
Referenced by assemble_mass_mat(), build_basis(), build_rhs_assembler(), compute_errors(), export_data(), output_fields(), output_space(), prepare_initial_solution(), reset(), and save_json().
t0
double polyfem::varform::ScalarVarForm::t0 = 0 private
Definition at line 57 of file ScalarVarForm.hpp.
Referenced by init(), and reset().
time_integrator
std::shared_ptr<time_integrator::ImplicitTimeIntegrator> polyfem::varform::ScalarVarForm::time_integrator private
Definition at line 75 of file ScalarVarForm.hpp.
Referenced by reset().
time_steps
int polyfem::varform::ScalarVarForm::time_steps = 0 private
Definition at line 58 of file ScalarVarForm.hpp.
Referenced by init(), and reset().
The documentation for this class was generated from the following files:
src/polyfem/varforms/ScalarVarForm.hpp
src/polyfem/varforms/ScalarVarForm.cpp