PolyFEM: polyfem::assembler::GenericElastic Class Reference
polyfem::assembler::GenericElastic Class Reference abstract
#include <GenericElastic.hpp>
Public Member Functions
GenericElastic ()
virtual ~GenericElastic ()=default
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const override
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > compute_rhs (const AutodiffHessianPt &pt) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &tensor) const
virtual void add_multimaterial (const int index, const json &params)=0
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SpareMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SpareMatrixCache &mat_cache, StiffnessMatrix &grad) const
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
Private Member Functions
template<typename T >
T compute_energy_aux (const NonLinearAssemblerData &data) const
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const
Additional Inherited Members
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 10 of file GenericElastic.hpp.
Constructor & Destructor Documentation
GenericElastic()
polyfem::assembler::GenericElastic::GenericElastic ()
Definition at line 7 of file GenericElastic.cpp.
~GenericElastic()
virtual polyfem::assembler::GenericElastic::~GenericElastic () virtual default
Member Function Documentation
add_multimaterial()
virtual void polyfem::assembler::GenericElastic::add_multimaterial (const int index, const json & params) pure virtual
Implemented in polyfem::assembler::MooneyRivlinElasticity, polyfem::assembler::NeoHookeanAutodiff, polyfem::assembler::UnconstrainedOgdenElasticity, and polyfem::assembler::IncompressibleOgdenElasticity.
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const
Definition at line 88 of file Assembler.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, cache, polyfem::utils::create_thread_storage(), polyfem::assembler::ElementAssemblyValues::det, polyfem::utils::get_local_thread_storage(), polyfem::logger(), polyfem::utils::maybe_parallel_for(), polyfem::assembler::ElementAssemblyValues::quadrature, vals, and polyfem::quadrature::Quadrature::weights.
assemble_grad() [1/3]
void polyfem::assembler::NLAssembler::assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const
assemble_grad() [2/3]
Eigen::VectorXd polyfem::assembler::GenericElastic::assemble_grad (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 101 of file GenericElastic.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::gradient_from_energy(), polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
Referenced by polyfem::assembler::MultiModel::assemble_grad().
assemble_grad() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_grad (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::SpareMatrixCache & mat_cache, StiffnessMatrix & grad) const
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::GenericElastic::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 119 of file GenericElastic.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::hessian_from_energy(), polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
Referenced by polyfem::assembler::MultiModel::assemble_hessian().
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assign_stress_tensor()
void polyfem::assembler::GenericElastic::assign_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const int all_size, const ElasticityTensorType & type, Eigen::MatrixXd & all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> & fun) const private
Definition at line 40 of file GenericElastic.cpp.
References polyfem::compute_diplacement_grad(), polyfem::F, polyfem::PK1, polyfem::pk1_from_cauchy(), polyfem::PK2, polyfem::pk2_from_cauchy(), DiffScalarBase::setVariableCount(), polyfem::assembler::Assembler::size(), val, and vals.
Referenced by compute_stress_tensor(), and compute_von_mises_stresses().
compute_energy()
double polyfem::assembler::GenericElastic::compute_energy (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 96 of file GenericElastic.cpp.
Referenced by polyfem::assembler::MultiModel::compute_energy().
compute_energy_aux()
template<typename T > T polyfem::assembler::GenericElastic::compute_energy_aux (const NonLinearAssemblerData & data) const inline private
Definition at line 44 of file GenericElastic.hpp.
References polyfem::compute_disp_grad_at_quad(), polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::ElementAssemblyValues::element_id, polyfem::get_local_disp(), polyfem::assembler::Assembler::size(), val, polyfem::assembler::ElementAssemblyValues::val, and polyfem::assembler::NonLinearAssemblerData::vals.
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::GenericElastic::compute_rhs (const AutodiffHessianPt & pt) const
Definition at line 12 of file GenericElastic.cpp.
References polyfem::log_and_throw_error(), and polyfem::assembler::Assembler::size().
compute_stress_tensor()
void polyfem::assembler::GenericElastic::compute_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const ElasticityTensorType & type, Eigen::MatrixXd & tensor) const
Definition at line 22 of file GenericElastic.cpp.
References assign_stress_tensor(), and polyfem::assembler::Assembler::size().
Referenced by polyfem::assembler::MultiModel::compute_stress_tensor().
compute_von_mises_stresses()
void polyfem::assembler::GenericElastic::compute_von_mises_stresses (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, Eigen::MatrixXd & stresses) const
Definition at line 31 of file GenericElastic.cpp.
References assign_stress_tensor(), polyfem::CAUCHY, and polyfem::von_mises_stress_for_stress_tensor().
Referenced by polyfem::assembler::MultiModel::compute_von_mises_stresses().
The documentation for this class was generated from the following files:
src/polyfem/assembler/GenericElastic.hpp
src/polyfem/assembler/GenericElastic.cpp