PolyFEM: polyfem::varform::StokesVarForm Class Reference
polyfem::varform::StokesVarForm Class Reference
#include <FluidVarForm.hpp>
Public Member Functions
std::string name () const override
Get the name of the variational formulation.
Public Member Functions inherited from polyfem::varform::FluidVarForm
void init (const std::string &formulation, const Units &units, const json &args, const std::string &out_path) override
Initialize the variational formulation with the given parameters.
void save_json (const Eigen::MatrixXd &solution, std::ostream &out) const override
Save the solution to a JSON file, for output purposes.
void export_data (const Eigen::MatrixXd &solution) const override
io::OutputSpace output_space () const override
Get the output space of the variational formulation, for output purposes.
io::OutStatsData compute_errors (const Eigen::MatrixXd &solution) override
Get the error statistics of the variational formulation, for output purposes.
std::vector< io::OutputField > output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options) const override
Get the output fields of the variational formulation, for output purposes.
Public Member Functions inherited from polyfem::varform::VarForm
virtual ~VarForm ()=default
void set_args (const json &args)
Reset the internal state of the variational formulation, e.g.
void set_mesh (std::unique_ptr< mesh::Mesh > mesh, const double loading_mesh_time=0)
Set the mesh for the variational formulation.
void solve (Eigen::MatrixXd &sol)
Solve the variational formulation and store the solution in the given matrix.
void set_time_callback (const std::function< void(int, int, double, double)> &callback)
int problem_dimension () const
Get the problem dimension of the variational formulation, for output purposes.
virtual bool is_contact_enabled () const
Check if contact is enabled for the variational formulation, for output purposes.
const io::OutRuntimeData & output_timings () const
Get the runtime timings of the variational formulation, for output purposes.
void save_json (const Eigen::MatrixXd &solution) const
Save the solution to a JSON file, for output purposes.
Private Member Functions
void solve_problem (Eigen::MatrixXd &sol) override
void solve_static_linear (Eigen::MatrixXd &sol)
void solve_transient_linear (Eigen::MatrixXd &sol)
Additional Inherited Members
Protected Member Functions inherited from polyfem::varform::FluidVarForm
void reset () override
void load_mesh (const mesh::Mesh &mesh, const json &args) override
void build_basis (mesh::Mesh &mesh, const bool iso_parametric, const json &args) override
void assemble_rhs (const mesh::Mesh &mesh) override
void assemble_mass_mat (const mesh::Mesh &mesh, const json &args) override
int primary_ndof () const
int pressure_block_size () const
int stacked_ndof () const
void prepare_initial_solution (Eigen::MatrixXd &sol) const
void split_solution (const Eigen::MatrixXd &stacked, Eigen::MatrixXd &primary, Eigen::MatrixXd &pressure) const
void build_stiffness_mat (StiffnessMatrix &stiffness)
void solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > &solver, StiffnessMatrix &A, Eigen::VectorXd &b, const bool compute_spectrum, Eigen::MatrixXd &sol)
void build_rhs_assembler () override
Protected Member Functions inherited from polyfem::varform::VarForm
std::string resolve_output_path (const std::string &path) const
std::string resolve_input_path (const std::string &path, const bool only_if_exists=false) const
void set_materials (assembler::Assembler &assembler, const int size) const
void assign_discr_orders (const json &discr_order, const mesh::Mesh &mesh, Eigen::VectorXi &disc_orders)
void prepare ()
QuadratureOrders n_boundary_samples (const int discr_order, const int gdiscr_order) const
void build_fe_space (mesh::Mesh &mesh, const bool iso_parametric, const Eigen::VectorXi &disc_orders, const std::string &basis_type, const std::string &poly_basis_type, const assembler::Assembler &space_assembler, const int value_dim, const int quadrature_order, const int mass_quadrature_order, const bool use_corner_quadrature, const int n_harmonic_samples, const int integral_constraints, FESpace &space, VarFormBoundaryState &boundary, std::shared_ptr< GeometryMapping > geometry=nullptr)
std::shared_ptr< time_integrator::BDF > make_bdf_time_integrator () const
void save_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator, const bool rest_mesh_written=false) const
void ensure_output_sampler () const
void save_restart_json (const double t0, const double dt, const int t, const bool rest_mesh_written) const
void save_timestep (const double time, const int t, const double t0, const double dt, const Eigen::MatrixXd &solution) const
void save_subsolve (const int i, const int t, const Eigen::MatrixXd &solution) const
int output_file_index (const int t) const
void notify_time_step (const int t, const int time_steps, const double t0, const double dt) const
io::OutGeometryData::ExportOptions export_options (const io::OutputSpace &space) const
io::OutputFieldFunction output_field_function (const Eigen::MatrixXd &solution, const io::OutGeometryData::ExportOptions &opts) const
Static Protected Member Functions inherited from polyfem::varform::VarForm
static bool read_initial_x_from_file (const std::string &state_path, const std::string &x_name, const bool reorder, const Eigen::VectorXi &in_node_to_node, const int dim, Eigen::MatrixXd &x)
static void rebuild_node_positions (const std::vector< basis::ElementBases > &bases, const std::vector< int > &node_ids, std::vector< RowVectorNd > &positions)
Protected Attributes inherited from polyfem::varform::FluidVarForm
FESpace space_
FESpace pressure_space_
VarFormBoundaryState boundary_
VarFormBoundaryState pressure_boundary_
assembler::AssemblyValsCache ass_vals_cache_
assembler::AssemblyValsCache pressure_ass_vals_cache_
assembler::AssemblyValsCache mass_ass_vals_cache_
assembler::AssemblyValsCache pure_mass_ass_vals_cache_
std::shared_ptr< assembler::RhsAssembler > rhs_assembler_
StiffnessMatrix mass_
StiffnessMatrix pure_mass_
double avg_mass_ = 0
Eigen::MatrixXd rhs_
std::shared_ptr< assembler::Assembler > primary_assembler_ = nullptr
std::shared_ptr< assembler::Mass > mass_assembler_ = nullptr
std::shared_ptr< assembler::HRZMass > pure_mass_assembler_ = nullptr
std::shared_ptr< assembler::MixedAssembler > mixed_assembler_ = nullptr
std::shared_ptr< assembler::Assembler > pressure_assembler_ = nullptr
bool use_avg_pressure = true
double t0 = 0
int time_steps = 0
double dt = 0
std::shared_ptr< time_integrator::ImplicitTimeIntegrator > time_integrator
Protected Attributes inherited from polyfem::varform::VarForm
std::shared_ptr< assembler::Problem > problem
current problem, it contains rhs and bc
Units units
json args
io::OutStatsData stats
io::OutRuntimeData timings
runtime statistics
std::string root_path
std::string output_path
std::unique_ptr< mesh::Mesh > mesh_
std::function< void(int, int, double, double)> time_callback
io::OutGeometryData output_geometry_
bool output_sampler_initialized_ = false
bool prepared_ = false
Detailed Description
Definition at line 85 of file FluidVarForm.hpp.
Member Function Documentation
name()
std::string polyfem::varform::StokesVarForm::name () const inline override virtual
Get the name of the variational formulation.
Returns
Name of the variational formulation
Implements polyfem::varform::VarForm.
Definition at line 88 of file FluidVarForm.hpp.
solve_problem()
void polyfem::varform::StokesVarForm::solve_problem (Eigen::MatrixXd & sol) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 880 of file FluidVarForm.cpp.
References polyfem::logger().
solve_static_linear()
void polyfem::varform::StokesVarForm::solve_static_linear (Eigen::MatrixXd & sol) private
Definition at line 802 of file FluidVarForm.cpp.
References polyfem::logger(), and space_.
solve_transient_linear()
void polyfem::varform::StokesVarForm::solve_transient_linear (Eigen::MatrixXd & sol) private
Definition at line 819 of file FluidVarForm.cpp.
References polyfem::varform::internal::expand_primary_matrix(), polyfem::logger(), and space_.
The documentation for this class was generated from the following files:
src/polyfem/varforms/FluidVarForm.hpp
src/polyfem/varforms/FluidVarForm.cpp