PolyFEM: polyfem::mesh::Obstacle::Plane Class Reference
polyfem::mesh::Obstacle::Plane Class Reference
#include <Obstacle.hpp>
Public Member Functions
Plane (const VectorNd &origin, const VectorNd &normal)
const VectorNd & origin () const
const VectorNd & normal () const
const Eigen::MatrixXd & vis_v () const
const Eigen::MatrixXi & vis_f () const
const Eigen::MatrixXi & vis_e () const
Protected Member Functions
void construct_vis_mesh ()
Protected Attributes
int dim_
VectorNd origin_
VectorNd normal_
Eigen::MatrixXd vis_v_
Eigen::MatrixXi vis_f_
Eigen::MatrixXi vis_e_
Detailed Description
Definition at line 72 of file Obstacle.hpp.
Constructor & Destructor Documentation
Plane()
polyfem::mesh::Obstacle::Plane::Plane (const VectorNd & origin, const VectorNd & normal) inline
Definition at line 75 of file Obstacle.hpp.
References construct_vis_mesh(), normal(), normal_, and origin().
Member Function Documentation
construct_vis_mesh()
void polyfem::mesh::Obstacle::Plane::construct_vis_mesh () protected
Definition at line 197 of file Obstacle.cpp.
References polyfem::assembler::cross(), dim_, normal(), vis_e_, vis_f_, vis_v_, x, and y.
Referenced by Plane().
normal()
const VectorNd & polyfem::mesh::Obstacle::Plane::normal () const inline
Definition at line 85 of file Obstacle.hpp.
References normal_.
Referenced by construct_vis_mesh(), and Plane().
origin()
const VectorNd & polyfem::mesh::Obstacle::Plane::origin () const inline
Definition at line 84 of file Obstacle.hpp.
References origin_.
Referenced by Plane().
vis_e()
const Eigen::MatrixXi & polyfem::mesh::Obstacle::Plane::vis_e () const inline
Definition at line 89 of file Obstacle.hpp.
References vis_e_.
vis_f()
const Eigen::MatrixXi & polyfem::mesh::Obstacle::Plane::vis_f () const inline
Definition at line 88 of file Obstacle.hpp.
References vis_f_.
vis_v()
const Eigen::MatrixXd & polyfem::mesh::Obstacle::Plane::vis_v () const inline
Definition at line 87 of file Obstacle.hpp.
References vis_v_.
Member Data Documentation
dim_
int polyfem::mesh::Obstacle::Plane::dim_ protected
Definition at line 94 of file Obstacle.hpp.
Referenced by construct_vis_mesh().
normal_
VectorNd polyfem::mesh::Obstacle::Plane::normal_ protected
Definition at line 97 of file Obstacle.hpp.
Referenced by normal(), and Plane().
origin_
VectorNd polyfem::mesh::Obstacle::Plane::origin_ protected
Definition at line 96 of file Obstacle.hpp.
Referenced by origin().
vis_e_
Eigen::MatrixXi polyfem::mesh::Obstacle::Plane::vis_e_ protected
Definition at line 101 of file Obstacle.hpp.
Referenced by construct_vis_mesh(), and vis_e().
vis_f_
Eigen::MatrixXi polyfem::mesh::Obstacle::Plane::vis_f_ protected
Definition at line 100 of file Obstacle.hpp.
Referenced by construct_vis_mesh(), and vis_f().
vis_v_
Eigen::MatrixXd polyfem::mesh::Obstacle::Plane::vis_v_ protected
Definition at line 99 of file Obstacle.hpp.
Referenced by construct_vis_mesh(), and vis_v().
The documentation for this class was generated from the following files:
src/polyfem/mesh/Obstacle.hpp
src/polyfem/mesh/Obstacle.cpp