PolyFEM: polyfem::solver::ParametrizationForm Class Reference
polyfem::solver::ParametrizationForm Class Reference
#include <ParametrizationForm.hpp>
Public Member Functions
ParametrizationForm (const CompositeParametrization &parametrizations)
virtual ~ParametrizationForm ()
virtual void init (const Eigen::VectorXd &x) final override
Initialize the form.
virtual double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const final override
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const final
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) final override
Initialize variables used during the line search.
virtual void line_search_end () final override
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x) final override
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x) final override
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) final override
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const final override
Checks if the step is collision free.
virtual Eigen::MatrixXd compute_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const override
virtual void init_with_param (const Eigen::VectorXd &x)
virtual bool is_step_valid_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
virtual double max_step_size_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
virtual void line_search_begin_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
virtual void line_search_end_with_param ()
virtual void post_step_with_param (const int iter_num, const Eigen::VectorXd &x)
virtual void solution_changed_with_param (const Eigen::VectorXd &new_x)
virtual void update_quantities_with_param (const double t, const Eigen::VectorXd &x)
virtual void init_lagging_with_param (const Eigen::VectorXd &x)
virtual void update_lagging_with_param (const Eigen::VectorXd &x, const int iter_num)
virtual void set_apply_DBC_with_param (const Eigen::VectorXd &x, bool apply_DBC)
virtual bool is_step_collision_free_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
virtual void first_derivative_unweighted_with_param (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
virtual double value_unweighted_with_param (const Eigen::VectorXd &x) const
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
void enable_energy_print (const std::string &print_energy_keyword)
const auto & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const final
virtual void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
virtual void compute_partial_gradient_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Private Member Functions
Eigen::VectorXd apply_parametrizations (const Eigen::VectorXd &x) const
Private Attributes
CompositeParametrization parametrizations_
Additional Inherited Members
Protected Attributes inherited from polyfem::solver::AdjointForm
std::vector< std::shared_ptr< VariableToSimulation > > variable_to_simulations_
int print_energy_ = 0
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 14 of file ParametrizationForm.hpp.
Constructor & Destructor Documentation
ParametrizationForm()
polyfem::solver::ParametrizationForm::ParametrizationForm (const CompositeParametrization & parametrizations) inline
Definition at line 17 of file ParametrizationForm.hpp.
~ParametrizationForm()
virtual polyfem::solver::ParametrizationForm::~ParametrizationForm () inline virtual
Definition at line 18 of file ParametrizationForm.hpp.
Member Function Documentation
apply_parametrizations()
Eigen::VectorXd polyfem::solver::ParametrizationForm::apply_parametrizations (const Eigen::VectorXd & x) const inline private
Definition at line 120 of file ParametrizationForm.hpp.
References polyfem::solver::CompositeParametrization::eval(), parametrizations_, and x.
Referenced by first_derivative_unweighted(), init(), init_lagging(), is_step_collision_free(), is_step_valid(), line_search_begin(), max_step_size(), post_step(), set_apply_DBC(), solution_changed(), update_lagging(), update_quantities(), and value_unweighted().
compute_adjoint_rhs_unweighted()
Eigen::MatrixXd polyfem::solver::ParametrizationForm::compute_adjoint_rhs_unweighted (const Eigen::VectorXd & x, const State & state) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 6 of file ParametrizationForm.cpp.
References polyfem::State::diff_cached, polyfem::State::ndof(), and polyfem::solver::DiffCache::size().
compute_partial_gradient_unweighted()
virtual void polyfem::solver::ParametrizationForm::compute_partial_gradient_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const inline override protected virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 112 of file ParametrizationForm.hpp.
References first_derivative_unweighted(), and x.
first_derivative_unweighted()
virtual void polyfem::solver::ParametrizationForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const inline override virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 31 of file ParametrizationForm.hpp.
References polyfem::solver::CompositeParametrization::apply_jacobian(), apply_parametrizations(), first_derivative_unweighted_with_param(), parametrizations_, x, and y.
Referenced by compute_partial_gradient_unweighted().
first_derivative_unweighted_with_param()
virtual void polyfem::solver::ParametrizationForm::first_derivative_unweighted_with_param (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const inline virtual
Reimplemented in polyfem::solver::ParametrizedProductForm, and polyfem::solver::WeightedVolumeForm.
Definition at line 108 of file ParametrizationForm.hpp.
Referenced by first_derivative_unweighted().
init()
virtual void polyfem::solver::ParametrizationForm::init (const Eigen::VectorXd & x) inline final override virtual
Initialize the form.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 20 of file ParametrizationForm.hpp.
References apply_parametrizations(), init_with_param(), and x.
init_lagging()
virtual void polyfem::solver::ParametrizationForm::init_lagging (const Eigen::VectorXd & x) inline final override virtual
Initialize lagged fields TODO: more than one step.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 74 of file ParametrizationForm.hpp.
References apply_parametrizations(), init_lagging_with_param(), and x.
init_lagging_with_param()
virtual void polyfem::solver::ParametrizationForm::init_lagging_with_param (const Eigen::VectorXd & x) inline virtual
Definition at line 104 of file ParametrizationForm.hpp.
Referenced by init_lagging().
init_with_param()
virtual void polyfem::solver::ParametrizationForm::init_with_param (const Eigen::VectorXd & x) inline virtual
Definition at line 96 of file ParametrizationForm.hpp.
Referenced by init().
is_step_collision_free()
virtual bool polyfem::solver::ParametrizationForm::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline final override virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented from polyfem::solver::Form.
Definition at line 89 of file ParametrizationForm.hpp.
References apply_parametrizations(), and is_step_collision_free_with_param().
is_step_collision_free_with_param()
virtual bool polyfem::solver::ParametrizationForm::is_step_collision_free_with_param (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline virtual
Definition at line 107 of file ParametrizationForm.hpp.
Referenced by is_step_collision_free().
is_step_valid()
virtual bool polyfem::solver::ParametrizationForm::is_step_valid (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline final override virtual
Determine if a step from solution x0 to solution x1 is allowed.
Parameters
x0 Current solution
x1 Proposed next solution
Returns
True if the step is allowed
Reimplemented from polyfem::solver::Form.
Definition at line 39 of file ParametrizationForm.hpp.
References apply_parametrizations(), and is_step_valid_with_param().
is_step_valid_with_param()
virtual bool polyfem::solver::ParametrizationForm::is_step_valid_with_param (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline virtual
Definition at line 97 of file ParametrizationForm.hpp.
Referenced by is_step_valid().
line_search_begin()
virtual void polyfem::solver::ParametrizationForm::line_search_begin (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) inline final override virtual
Initialize variables used during the line search.
Parameters
x0 Current solution
x1 Next solution
Reimplemented from polyfem::solver::Form.
Definition at line 49 of file ParametrizationForm.hpp.
References apply_parametrizations(), and line_search_begin_with_param().
line_search_begin_with_param()
virtual void polyfem::solver::ParametrizationForm::line_search_begin_with_param (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) inline virtual
Definition at line 99 of file ParametrizationForm.hpp.
Referenced by line_search_begin().
line_search_end()
virtual void polyfem::solver::ParametrizationForm::line_search_end () inline final override virtual
Clear variables used during the line search.
Reimplemented from polyfem::solver::Form.
Definition at line 54 of file ParametrizationForm.hpp.
References line_search_end_with_param().
line_search_end_with_param()
virtual void polyfem::solver::ParametrizationForm::line_search_end_with_param () inline virtual
Definition at line 100 of file ParametrizationForm.hpp.
Referenced by line_search_end().
max_step_size()
virtual double polyfem::solver::ParametrizationForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline final virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::Form.
Definition at line 44 of file ParametrizationForm.hpp.
References apply_parametrizations(), and max_step_size_with_param().
max_step_size_with_param()
virtual double polyfem::solver::ParametrizationForm::max_step_size_with_param (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline virtual
Definition at line 98 of file ParametrizationForm.hpp.
Referenced by max_step_size().
post_step()
virtual void polyfem::solver::ParametrizationForm::post_step (const int iter_num, const Eigen::VectorXd & x) inline final override virtual
Update fields after a step in the optimization.
Parameters
iter_num Optimization iteration number
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 59 of file ParametrizationForm.hpp.
References apply_parametrizations(), post_step_with_param(), and x.
post_step_with_param()
virtual void polyfem::solver::ParametrizationForm::post_step_with_param (const int iter_num, const Eigen::VectorXd & x) inline virtual
Definition at line 101 of file ParametrizationForm.hpp.
Referenced by post_step().
set_apply_DBC()
virtual void polyfem::solver::ParametrizationForm::set_apply_DBC (const Eigen::VectorXd & x, bool apply_DBC) inline final override virtual
Set if the Dirichlet boundary conditions should be enforced.
Note
This is specific to the body form.
Parameters
apply_DBC If true, apply Dirichlet boundary conditions to the current RHS.
Reimplemented from polyfem::solver::Form.
Definition at line 84 of file ParametrizationForm.hpp.
References apply_parametrizations(), set_apply_DBC_with_param(), and x.
set_apply_DBC_with_param()
virtual void polyfem::solver::ParametrizationForm::set_apply_DBC_with_param (const Eigen::VectorXd & x, bool apply_DBC) inline virtual
Definition at line 106 of file ParametrizationForm.hpp.
Referenced by set_apply_DBC().
solution_changed()
virtual void polyfem::solver::ParametrizationForm::solution_changed (const Eigen::VectorXd & new_x) inline final override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 64 of file ParametrizationForm.hpp.
References apply_parametrizations(), and solution_changed_with_param().
solution_changed_with_param()
virtual void polyfem::solver::ParametrizationForm::solution_changed_with_param (const Eigen::VectorXd & new_x) inline virtual
Definition at line 102 of file ParametrizationForm.hpp.
Referenced by solution_changed().
update_lagging()
virtual void polyfem::solver::ParametrizationForm::update_lagging (const Eigen::VectorXd & x, const int iter_num) inline final override virtual
Update lagged fields.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 79 of file ParametrizationForm.hpp.
References apply_parametrizations(), update_lagging_with_param(), and x.
update_lagging_with_param()
virtual void polyfem::solver::ParametrizationForm::update_lagging_with_param (const Eigen::VectorXd & x, const int iter_num) inline virtual
Definition at line 105 of file ParametrizationForm.hpp.
Referenced by update_lagging().
update_quantities()
virtual void polyfem::solver::ParametrizationForm::update_quantities (const double t, const Eigen::VectorXd & x) inline final override virtual
Update time-dependent fields.
Parameters
t Current time
x Current solution at time t
Reimplemented from polyfem::solver::Form.
Definition at line 69 of file ParametrizationForm.hpp.
References apply_parametrizations(), update_quantities_with_param(), and x.
update_quantities_with_param()
virtual void polyfem::solver::ParametrizationForm::update_quantities_with_param (const double t, const Eigen::VectorXd & x) inline virtual
Definition at line 103 of file ParametrizationForm.hpp.
Referenced by update_quantities().
value_unweighted()
virtual double polyfem::solver::ParametrizationForm::value_unweighted (const Eigen::VectorXd & x) const inline override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 25 of file ParametrizationForm.hpp.
References apply_parametrizations(), value_unweighted_with_param(), x, and y.
value_unweighted_with_param()
virtual double polyfem::solver::ParametrizationForm::value_unweighted_with_param (const Eigen::VectorXd & x) const inline virtual
Reimplemented in polyfem::solver::ParametrizedProductForm, and polyfem::solver::WeightedVolumeForm.
Definition at line 109 of file ParametrizationForm.hpp.
Referenced by value_unweighted().
Member Data Documentation
parametrizations_
CompositeParametrization polyfem::solver::ParametrizationForm::parametrizations_ private
Definition at line 118 of file ParametrizationForm.hpp.
Referenced by apply_parametrizations(), and first_derivative_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/ParametrizationForm.hpp
src/polyfem/solver/forms/adjoint_forms/ParametrizationForm.cpp