PolyFEM: polyfem::solver::ALNLProblem Class Reference
polyfem::solver::ALNLProblem Class Reference
#include <ALNLProblem.hpp>
Public Types
typedef NLProblem super
typedef StiffnessMatrix THessian
Public Types inherited from polyfem::solver::NLProblem
typedef StiffnessMatrix THessian
Public Member Functions
ALNLProblem (const State &state, const assembler::RhsAssembler &rhs_assembler, const double t, const double dhat, const double weight)
TVector initial_guess ()
void set_weight (const double w)
double value (const TVector &x) override
double value (const TVector &x, const bool only_elastic) override
void gradient_no_rhs (const TVector &x, Eigen::MatrixXd &gradv, const bool only_elastic=false) override
void update_quantities (const double t, const TVector &x) override
void update_target (const double t)
bool stop (const TVector &x) override
void hessian_full (const TVector &x, THessian &gradv) override
Public Member Functions inherited from polyfem::solver::NLProblem
NLProblem (const State &state, const assembler::RhsAssembler &rhs_assembler, const double t, const double dhat, const bool no_reduced=false)
void init (const TVector &displacement)
void init_time_integrator (const TVector &x_prev, const TVector &v_prev, const TVector &a_prev, const double dt)
TVector initial_guess ()
virtual double value (const TVector &x) override
virtual void gradient (const TVector &x, TVector &gradv) override
virtual void gradient_no_rhs (const TVector &x, Eigen::MatrixXd &gradv, const bool only_elastic=false)
virtual double value (const TVector &x, const bool only_elastic)
void gradient (const TVector &x, TVector &gradv, const bool only_elastic)
bool is_step_valid (const TVector &x0, const TVector &x1)
bool is_step_collision_free (const TVector &x0, const TVector &x1)
double max_step_size (const TVector &x0, const TVector &x1)
bool is_intersection_free (const TVector &x)
void line_search_begin (const TVector &x0, const TVector &x1)
void line_search_end ()
void post_step (const int iter_num, const TVector &x)
virtual void hessian (const TVector &x, THessian &hessian)
virtual void hessian_full (const TVector &x, THessian &gradv)
template<class FullVector >
void full_to_reduced (const FullVector &full, TVector &reduced) const
template<class FullVector >
void reduced_to_full (const TVector &reduced, FullVector &full)
void full_hessian_to_reduced_hessian (const THessian &full, THessian &reduced) const
virtual void update_quantities (const double t, const TVector &x)
void substepping (const double t)
void solution_changed (const TVector &newX)
void init_lagging (const TVector &x)
void update_lagging (const TVector &x)
double compute_lagging_error (const TVector &x)
bool lagging_converged (const TVector &x)
const Eigen::MatrixXd & current_rhs ()
virtual bool stop (const TVector &x)
void save_raw (const std::string &x_path, const std::string &v_path, const std::string &a_path) const
double heuristic_max_step (const TVector &dx)
void set_ccd_max_iterations (int v)
void set_project_to_psd (bool val)
bool is_project_to_psd () const
double & lagged_damping_weight ()
void compute_displaced_points (const TVector &full, Eigen::MatrixXd &displaced)
void reduced_to_full_displaced_points (const TVector &reduced, Eigen::MatrixXd &displaced)
double barrier_stiffness () const
const Eigen::MatrixXd & displaced_prev () const
const std::shared_ptr< const time_integrator::ImplicitTimeIntegrator > time_integrator () const
Private Member Functions
void compute_distance (const TVector &x, TVector &res)
Private Attributes
double weight_
double stop_dist_
THessian hessian_AL_
std::vector< int > not_boundary_
Eigen::MatrixXd target_x_
Additional Inherited Members
Static Public Member Functions inherited from polyfem::solver::NLProblem
template<class FullMat , class ReducedMat >
static void full_to_reduced_aux (const State &state, const int full_size, const int reduced_size, const FullMat &full, ReducedMat &reduced)
template<class ReducedMat , class FullMat >
static void reduced_to_full_aux (const State &state, const int full_size, const int reduced_size, const ReducedMat &reduced, const Eigen::MatrixXd &rhs, FullMat &full)
Protected Attributes inherited from polyfem::solver::NLProblem
const State & state
bool use_adaptive_barrier_stiffness
double _barrier_stiffness
const assembler::RhsAssembler & rhs_assembler
bool is_time_dependent
Detailed Description
Definition at line 14 of file ALNLProblem.hpp.
Member Typedef Documentation
super
typedef NLProblem polyfem::solver::ALNLProblem::super
Definition at line 17 of file ALNLProblem.hpp.
THessian
typedef StiffnessMatrix polyfem::solver::NLProblem::THessian
Definition at line 24 of file NLProblem.hpp.
Constructor & Destructor Documentation
ALNLProblem()
polyfem::solver::ALNLProblem::ALNLProblem (const State & state, const assembler::RhsAssembler & rhs_assembler, const double t, const double dhat, const double weight)
Definition at line 25 of file ALNLProblem.cpp.
References polyfem::State::boundary_nodes, entries, hessian_AL_, polyfem::State::mesh, polyfem::State::n_bases, not_boundary_, polyfem::solver::NLProblem::state, polyfem::solver::NLProblem::t, and update_target().
Member Function Documentation
compute_distance()
void polyfem::solver::ALNLProblem::compute_distance (const TVector & x, TVector & res) private
Definition at line 66 of file ALNLProblem.cpp.
References not_boundary_, target_x_, and x.
Referenced by gradient_no_rhs(), and value().
gradient_no_rhs()
void polyfem::solver::ALNLProblem::gradient_no_rhs (const TVector & x, Eigen::MatrixXd & gradv, const bool only_elastic = false) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 105 of file ALNLProblem.cpp.
References compute_distance(), polyfem::solver::NLProblem::gradient_no_rhs(), weight_, and x.
hessian_full()
void polyfem::solver::ALNLProblem::hessian_full (const TVector & x, THessian & gradv) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 118 of file ALNLProblem.cpp.
References polyfem::solver::NLProblem::hessian(), hessian_AL_, polyfem::solver::NLProblem::hessian_full(), weight_, and x.
initial_guess()
TVector polyfem::solver::ALNLProblem::initial_guess ()
set_weight()
void polyfem::solver::ALNLProblem::set_weight (const double w) inline
Definition at line 24 of file ALNLProblem.hpp.
References weight_.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
stop()
bool polyfem::solver::ALNLProblem::stop (const TVector & x) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 125 of file ALNLProblem.cpp.
update_quantities()
void polyfem::solver::ALNLProblem::update_quantities (const double t, const TVector & x) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 57 of file ALNLProblem.cpp.
References polyfem::solver::NLProblem::is_time_dependent, polyfem::solver::NLProblem::t, polyfem::solver::NLProblem::update_quantities(), update_target(), and x.
Referenced by polyfem::State::solve_transient_tensor_non_linear_step().
update_target()
void polyfem::solver::ALNLProblem::update_target (const double t)
Definition at line 51 of file ALNLProblem.cpp.
References polyfem::State::boundary_nodes, hessian_AL_, polyfem::State::local_boundary, polyfem::State::local_neumann_boundary, polyfem::State::n_boundary_samples(), polyfem::solver::NLProblem::rhs_assembler, polyfem::assembler::RhsAssembler::set_bc(), polyfem::solver::NLProblem::state, polyfem::solver::NLProblem::t, and target_x_.
Referenced by ALNLProblem(), and update_quantities().
value() [1/2]
double polyfem::solver::ALNLProblem::value (const TVector & x) inline override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 26 of file ALNLProblem.hpp.
References polyfem::solver::NLProblem::value(), and x.
value() [2/2]
double polyfem::solver::ALNLProblem::value (const TVector & x, const bool only_elastic) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 74 of file ALNLProblem.cpp.
References polyfem::solver::NLProblem::compute_displaced_points(), compute_distance(), polyfem::logger(), eigs::M, polyfem::utils::sparse_identity(), val, polyfem::solver::NLProblem::value(), weight_, and x.
Member Data Documentation
hessian_AL_
THessian polyfem::solver::ALNLProblem::hessian_AL_ private
Definition at line 41 of file ALNLProblem.hpp.
Referenced by ALNLProblem(), hessian_full(), and update_target().
not_boundary_
std::vector<int> polyfem::solver::ALNLProblem::not_boundary_ private
Definition at line 42 of file ALNLProblem.hpp.
Referenced by ALNLProblem(), and compute_distance().
stop_dist_
double polyfem::solver::ALNLProblem::stop_dist_ private
Definition at line 40 of file ALNLProblem.hpp.
target_x_
Eigen::MatrixXd polyfem::solver::ALNLProblem::target_x_ private
Definition at line 43 of file ALNLProblem.hpp.
Referenced by compute_distance(), and update_target().
weight_
double polyfem::solver::ALNLProblem::weight_ private
Definition at line 39 of file ALNLProblem.hpp.
Referenced by gradient_no_rhs(), hessian_full(), set_weight(), and value().
The documentation for this class was generated from the following files:
src/polyfem/solver/ALNLProblem.hpp
src/polyfem/solver/ALNLProblem.cpp