PolyFEM: polyfem::assembler::LinearElasticity Class Reference
polyfem::assembler::LinearElasticity Class Reference
#include <LinearElasticity.hpp>
Public Member Functions
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > assemble (const ElementAssemblyValues &vals, const int i, const int j, const QuadratureVector &da) const
computes local stiffness matrix is R^{dim²} for bases i,j
Eigen::MatrixXd assemble_hessian (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
Eigen::VectorXd assemble_grad (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
double compute_energy (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &r) const
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > compute_rhs (const AutodiffHessianPt &pt) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
void compute_dstress_dgradu_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
void set_size (const int size)
int size () const
void add_multimaterial (const int index, const json &params)
const LameParameters & lame_params () const
void set_params (const LameParameters &params)
Private Member Functions
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const
template<typename T >
T compute_energy_aux (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
Private Attributes
int size_ = -1
LameParameters params_
Detailed Description
Definition at line 19 of file LinearElasticity.hpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::LinearElasticity::add_multimaterial (const int index, const json & params)
Definition at line 14 of file LinearElasticity.cpp.
References polyfem::LameParameters::add_multimaterial(), params_, and size_.
Referenced by polyfem::assembler::MultiModel::add_multimaterial().
assemble()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > polyfem::assembler::LinearElasticity::assemble (const ElementAssemblyValues & vals, const int i, const int j, const QuadratureVector & da) const
computes local stiffness matrix is R^{dim²} for bases i,j
Definition at line 22 of file LinearElasticity.cpp.
References da, polyfem::LameParameters::lambda_mu(), params_, size(), and vals.
assemble_grad()
Eigen::VectorXd polyfem::assembler::LinearElasticity::assemble_grad (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const
Definition at line 61 of file LinearElasticity.cpp.
References da, polyfem::gradient_from_energy(), size(), and vals.
Referenced by polyfem::assembler::MultiModel::assemble_grad().
assemble_hessian()
Eigen::MatrixXd polyfem::assembler::LinearElasticity::assemble_hessian (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const
Definition at line 79 of file LinearElasticity.cpp.
References da, polyfem::hessian_from_energy(), size(), and vals.
Referenced by polyfem::assembler::MultiModel::assemble_hessian().
assign_stress_tensor()
void polyfem::assembler::LinearElasticity::assign_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const int all_size, Eigen::MatrixXd & all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> & fun) const private
Definition at line 209 of file LinearElasticity.cpp.
References polyfem::compute_diplacement_grad(), polyfem::LameParameters::lambda_mu(), params_, size(), and vals.
Referenced by compute_stress_tensor(), and compute_von_mises_stresses().
compute_dstress_dgradu_multiply_mat()
void polyfem::assembler::LinearElasticity::compute_dstress_dgradu_multiply_mat (const int el_id, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & global_pts, const Eigen::MatrixXd & grad_u_i, const Eigen::MatrixXd & mat, Eigen::MatrixXd & stress, Eigen::MatrixXd & result) const
Definition at line 284 of file LinearElasticity.cpp.
References polyfem::LameParameters::lambda_mu(), params_, and size().
compute_dstress_dmu_dlambda()
void polyfem::assembler::LinearElasticity::compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & global_pts, const Eigen::MatrixXd & grad_u_i, Eigen::MatrixXd & dstress_dmu, Eigen::MatrixXd & dstress_dlambda) const
Definition at line 293 of file LinearElasticity.cpp.
compute_energy()
double polyfem::assembler::LinearElasticity::compute_energy (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const
Definition at line 56 of file LinearElasticity.cpp.
References da, and vals.
Referenced by polyfem::assembler::MultiModel::compute_energy().
compute_energy_aux()
template<typename T > T polyfem::assembler::LinearElasticity::compute_energy_aux (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const private
Definition at line 98 of file LinearElasticity.cpp.
References da, elasticity_rhs::def_grad, polyfem::LameParameters::lambda_mu(), params_, DiffScalarBase::setVariableCount(), size(), val, and vals.
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::LinearElasticity::compute_rhs (const AutodiffHessianPt & pt) const
Definition at line 172 of file LinearElasticity.cpp.
References polyfem::LameParameters::lambda_mu(), polyfem::autogen::linear_elasticity_2d_function(), polyfem::autogen::linear_elasticity_3d_function(), params_, size(), and size_.
compute_stress_tensor()
void polyfem::assembler::LinearElasticity::compute_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, Eigen::MatrixXd & tensor) const
Definition at line 191 of file LinearElasticity.cpp.
References assign_stress_tensor(), size(), and p_bases::tmp.
Referenced by polyfem::assembler::MultiModel::compute_stress_tensor().
compute_von_mises_stresses()
void polyfem::assembler::LinearElasticity::compute_von_mises_stresses (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, Eigen::MatrixXd & stresses) const
Definition at line 200 of file LinearElasticity.cpp.
References assign_stress_tensor(), and polyfem::von_mises_stress_for_stress_tensor().
Referenced by polyfem::assembler::MultiModel::compute_von_mises_stresses().
kernel()
Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::LinearElasticity::kernel (const int dim, const AutodiffGradPt & r) const
Definition at line 255 of file LinearElasticity.cpp.
References polyfem::LameParameters::lambda_mu(), and params_.
lame_params()
const LameParameters & polyfem::assembler::LinearElasticity::lame_params () const inline
Definition at line 60 of file LinearElasticity.hpp.
References params_.
Referenced by polyfem::assembler::MultiModel::lame_params().
set_params()
void polyfem::assembler::LinearElasticity::set_params (const LameParameters & params) inline
Definition at line 61 of file LinearElasticity.hpp.
References params_.
Referenced by polyfem::assembler::MultiModel::set_params().
set_size()
void polyfem::assembler::LinearElasticity::set_size (const int size) inline
Definition at line 53 of file LinearElasticity.hpp.
References size(), and size_.
Referenced by polyfem::assembler::MultiModel::set_size().
size()
int polyfem::assembler::LinearElasticity::size () const inline
Definition at line 54 of file LinearElasticity.hpp.
References size_.
Referenced by assemble(), assemble_grad(), assemble_hessian(), assign_stress_tensor(), compute_dstress_dgradu_multiply_mat(), compute_energy_aux(), compute_rhs(), compute_stress_tensor(), and set_size().
Member Data Documentation
params_
LameParameters polyfem::assembler::LinearElasticity::params_ private
Definition at line 66 of file LinearElasticity.hpp.
Referenced by add_multimaterial(), assemble(), assign_stress_tensor(), compute_dstress_dgradu_multiply_mat(), compute_energy_aux(), compute_rhs(), kernel(), lame_params(), and set_params().
size_
int polyfem::assembler::LinearElasticity::size_ = -1 private
Definition at line 64 of file LinearElasticity.hpp.
Referenced by add_multimaterial(), compute_rhs(), set_size(), and size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/LinearElasticity.hpp
src/polyfem/assembler/LinearElasticity.cpp