PolyFEM: cppoptlib::NonlinearSolver< ProblemType > Class Template Reference
cppoptlib::NonlinearSolver< ProblemType > Class Template Reference abstract
#include <NonlinearSolver.hpp>
Public Types
enum class ErrorCode { NanEncountered = -10 , StepTooSmall = -1 , Success = 0 }
using Superclass = ISolver< ProblemType, -1 >
Public Member Functions
NonlinearSolver (const json &solver_params)
virtual std::string name () const =0
void setLineSearch (const std::string &line_search_name)
void minimize (ProblemType &objFunc, TVector &x)
double line_search (const TVector &x, const TVector &delta_x, ProblemType &objFunc)
void getInfo (json &params)
ErrorCode error_code () const
Protected Member Functions
virtual void reset (const ProblemType &objFunc, const TVector &x)
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x_vec, const TVector &grad, TVector &direction)=0
virtual int default_descent_strategy ()=0
virtual void increase_descent_strategy ()=0
virtual std::string descent_strategy_name (int descent_strategy) const =0
virtual std::string descent_strategy_name () const
void reset_times ()
virtual void update_solver_info ()
void log_times ()
Protected Attributes
const json solver_params
std::shared_ptr< polyfem::solver::line_search::LineSearch< ProblemType > > m_line_search
int descent_strategy
ErrorCode m_error_code
bool use_gradient_norm
bool normalize_gradient
double use_grad_norm_tol
json solver_info
double total_time
double grad_time
double assembly_time
double inverting_time
double line_search_time
double constraint_set_update_time
double obj_fun_time
Detailed Description
template<typename ProblemType>
class cppoptlib::NonlinearSolver< ProblemType >
Definition at line 16 of file NonlinearSolver.hpp.
Member Typedef Documentation
Superclass
template<typename ProblemType > using cppoptlib::NonlinearSolver< ProblemType >::Superclass = ISolver<ProblemType, -1>
Definition at line 19 of file NonlinearSolver.hpp.
Member Enumeration Documentation
ErrorCode
template<typename ProblemType > enum class cppoptlib::NonlinearSolver::ErrorCode strong
Enumerator
NanEncountered
StepTooSmall
Success
Definition at line 23 of file NonlinearSolver.hpp.
Constructor & Destructor Documentation
NonlinearSolver()
template<typename ProblemType > cppoptlib::NonlinearSolver< ProblemType >::NonlinearSolver (const json & solver_params) inline
Definition at line 30 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::normalize_gradient, cppoptlib::NonlinearSolver< ProblemType >::setLineSearch(), cppoptlib::NonlinearSolver< ProblemType >::solver_params, cppoptlib::NonlinearSolver< ProblemType >::use_grad_norm_tol, and cppoptlib::NonlinearSolver< ProblemType >::use_gradient_norm.
Member Function Documentation
compute_update_direction()
template<typename ProblemType > virtual bool cppoptlib::NonlinearSolver< ProblemType >::compute_update_direction (ProblemType & objFunc, const TVector & x_vec, const TVector & grad, TVector & direction) protected pure virtual
Implemented in cppoptlib::LBFGSSolver< ProblemType >, and cppoptlib::SparseNewtonDescentSolver< ProblemType >.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize().
default_descent_strategy()
template<typename ProblemType > virtual int cppoptlib::NonlinearSolver< ProblemType >::default_descent_strategy () protected pure virtual
Implemented in cppoptlib::LBFGSSolver< ProblemType >, and cppoptlib::SparseNewtonDescentSolver< ProblemType >.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), and cppoptlib::NonlinearSolver< ProblemType >::reset().
descent_strategy_name() [1/2]
template<typename ProblemType > virtual std::string cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name () const inline protected virtual
Reimplemented in cppoptlib::LBFGSSolver< ProblemType >.
Definition at line 334 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, and cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name().
Referenced by cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name(), cppoptlib::NonlinearSolver< ProblemType >::line_search(), and cppoptlib::NonlinearSolver< ProblemType >::minimize().
descent_strategy_name() [2/2]
template<typename ProblemType > virtual std::string cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name (int descent_strategy) const protected pure virtual
Implemented in cppoptlib::LBFGSSolver< ProblemType >, cppoptlib::SparseNewtonDescentSolver< ProblemType >, and cppoptlib::LBFGSSolver< ProblemType >.
error_code()
template<typename ProblemType > ErrorCode cppoptlib::NonlinearSolver< ProblemType >::error_code () const inline
Definition at line 312 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::m_error_code.
getInfo()
template<typename ProblemType > void cppoptlib::NonlinearSolver< ProblemType >::getInfo (json & params) inline
Definition at line 307 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::solver_info.
increase_descent_strategy()
template<typename ProblemType > virtual void cppoptlib::NonlinearSolver< ProblemType >::increase_descent_strategy () protected pure virtual
Implemented in cppoptlib::LBFGSSolver< ProblemType >, and cppoptlib::SparseNewtonDescentSolver< ProblemType >.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::line_search(), and cppoptlib::NonlinearSolver< ProblemType >::minimize().
line_search()
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::line_search (const TVector & x, const TVector & delta_x, ProblemType & objFunc) inline
Definition at line 280 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name(), cppoptlib::NonlinearSolver< ProblemType >::increase_descent_strategy(), cppoptlib::NonlinearSolver< ProblemType >::line_search_time, polyfem::logger(), cppoptlib::NonlinearSolver< ProblemType >::m_line_search, cppoptlib::NonlinearSolver< ProblemType >::name(), POLYFEM_SCOPED_TIMER, and x.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize().
log_times()
template<typename ProblemType > void cppoptlib::NonlinearSolver< ProblemType >::log_times () inline protected
Definition at line 413 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::assembly_time, cppoptlib::NonlinearSolver< ProblemType >::constraint_set_update_time, cppoptlib::NonlinearSolver< ProblemType >::grad_time, cppoptlib::NonlinearSolver< ProblemType >::inverting_time, cppoptlib::NonlinearSolver< ProblemType >::line_search_time, polyfem::logger(), cppoptlib::NonlinearSolver< ProblemType >::m_line_search, and cppoptlib::NonlinearSolver< ProblemType >::obj_fun_time.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize().
minimize()
template<typename ProblemType > void cppoptlib::NonlinearSolver< ProblemType >::minimize (ProblemType & objFunc, TVector & x) inline
Definition at line 54 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::constraint_set_update_time, cppoptlib::NonlinearSolver< ProblemType >::default_descent_strategy(), cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name(), polyfem::utils::Timer::getElapsedTimeInSec(), cppoptlib::NonlinearSolver< ProblemType >::grad_time, cppoptlib::NonlinearSolver< ProblemType >::increase_descent_strategy(), cppoptlib::NonlinearSolver< ProblemType >::line_search(), cppoptlib::NonlinearSolver< ProblemType >::log_times(), polyfem::logger(), cppoptlib::NonlinearSolver< ProblemType >::m_error_code, cppoptlib::NonlinearSolver< ProblemType >::m_line_search, cppoptlib::NonlinearSolver< ProblemType >::name(), cppoptlib::NonlinearSolver< ProblemType >::NanEncountered, p_bases::norm, cppoptlib::NonlinearSolver< ProblemType >::normalize_gradient, cppoptlib::NonlinearSolver< ProblemType >::obj_fun_time, POLYFEM_SCOPED_TIMER, cppoptlib::NonlinearSolver< ProblemType >::reset(), polyfem::utils::Timer::start(), polyfem::utils::Timer::stop(), cppoptlib::NonlinearSolver< ProblemType >::Success, cppoptlib::NonlinearSolver< ProblemType >::total_time, cppoptlib::NonlinearSolver< ProblemType >::update_solver_info(), cppoptlib::NonlinearSolver< ProblemType >::use_grad_norm_tol, cppoptlib::NonlinearSolver< ProblemType >::use_gradient_norm, and x.
name()
template<typename ProblemType > virtual std::string cppoptlib::NonlinearSolver< ProblemType >::name () const pure virtual
Implemented in cppoptlib::LBFGSSolver< ProblemType >, and cppoptlib::SparseNewtonDescentSolver< ProblemType >.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::line_search(), and cppoptlib::NonlinearSolver< ProblemType >::minimize().
reset()
template<typename ProblemType > virtual void cppoptlib::NonlinearSolver< ProblemType >::reset (const ProblemType & objFunc, const TVector & x) inline protected virtual
Reimplemented in cppoptlib::LBFGSSolver< ProblemType >, and cppoptlib::SparseNewtonDescentSolver< ProblemType >.
Definition at line 316 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::default_descent_strategy(), cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::NonlinearSolver< ProblemType >::m_error_code, cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::Success.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::LBFGSSolver< ProblemType >::reset(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset().
reset_times()
template<typename ProblemType > void cppoptlib::NonlinearSolver< ProblemType >::reset_times () inline protected
Definition at line 355 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::assembly_time, cppoptlib::NonlinearSolver< ProblemType >::constraint_set_update_time, cppoptlib::NonlinearSolver< ProblemType >::grad_time, cppoptlib::NonlinearSolver< ProblemType >::inverting_time, cppoptlib::NonlinearSolver< ProblemType >::line_search_time, cppoptlib::NonlinearSolver< ProblemType >::m_line_search, cppoptlib::NonlinearSolver< ProblemType >::obj_fun_time, and cppoptlib::NonlinearSolver< ProblemType >::total_time.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::reset().
setLineSearch()
template<typename ProblemType > void cppoptlib::NonlinearSolver< ProblemType >::setLineSearch (const std::string & line_search_name) inline
Definition at line 48 of file NonlinearSolver.hpp.
References polyfem::solver::line_search::LineSearch< ProblemType >::construct_line_search(), cppoptlib::NonlinearSolver< ProblemType >::m_line_search, and cppoptlib::NonlinearSolver< ProblemType >::solver_info.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::NonlinearSolver().
update_solver_info()
template<typename ProblemType > virtual void cppoptlib::NonlinearSolver< ProblemType >::update_solver_info () inline protected virtual
Reimplemented in cppoptlib::SparseNewtonDescentSolver< ProblemType >.
Definition at line 370 of file NonlinearSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::assembly_time, cppoptlib::NonlinearSolver< ProblemType >::constraint_set_update_time, cppoptlib::NonlinearSolver< ProblemType >::grad_time, cppoptlib::NonlinearSolver< ProblemType >::inverting_time, cppoptlib::NonlinearSolver< ProblemType >::line_search_time, cppoptlib::NonlinearSolver< ProblemType >::m_error_code, cppoptlib::NonlinearSolver< ProblemType >::m_line_search, cppoptlib::NonlinearSolver< ProblemType >::normalize_gradient, cppoptlib::NonlinearSolver< ProblemType >::obj_fun_time, cppoptlib::NonlinearSolver< ProblemType >::solver_info, cppoptlib::NonlinearSolver< ProblemType >::total_time, and cppoptlib::NonlinearSolver< ProblemType >::use_gradient_norm.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::update_solver_info().
Member Data Documentation
assembly_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::assembly_time protected
Definition at line 349 of file NonlinearSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
constraint_set_update_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::constraint_set_update_time protected
Definition at line 352 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
descent_strategy
template<typename ProblemType > int cppoptlib::NonlinearSolver< ProblemType >::descent_strategy protected
Definition at line 338 of file NonlinearSolver.hpp.
Referenced by cppoptlib::LBFGSSolver< ProblemType >::compute_update_direction(), cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::descent_strategy_name(), cppoptlib::LBFGSSolver< ProblemType >::descent_strategy_name(), cppoptlib::SparseNewtonDescentSolver< ProblemType >::descent_strategy_name(), cppoptlib::LBFGSSolver< ProblemType >::increase_descent_strategy(), cppoptlib::SparseNewtonDescentSolver< ProblemType >::increase_descent_strategy(), cppoptlib::NonlinearSolver< ProblemType >::line_search(), cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset(), and cppoptlib::LBFGSSolver< ProblemType >::reset().
grad_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::grad_time protected
Definition at line 348 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
inverting_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::inverting_time protected
Definition at line 350 of file NonlinearSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
line_search_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::line_search_time protected
Definition at line 351 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::line_search(), cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
m_error_code
template<typename ProblemType > ErrorCode cppoptlib::NonlinearSolver< ProblemType >::m_error_code protected
Definition at line 340 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::error_code(), cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
m_line_search
template<typename ProblemType > std::shared_ptr<polyfem::solver::line_search::LineSearch<ProblemType> > cppoptlib::NonlinearSolver< ProblemType >::m_line_search protected
Definition at line 336 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::line_search(), cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), cppoptlib::NonlinearSolver< ProblemType >::setLineSearch(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
normalize_gradient
template<typename ProblemType > bool cppoptlib::NonlinearSolver< ProblemType >::normalize_gradient protected
Definition at line 342 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::NonlinearSolver(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
obj_fun_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::obj_fun_time protected
Definition at line 353 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::log_times(), cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
solver_info
template<typename ProblemType > json cppoptlib::NonlinearSolver< ProblemType >::solver_info protected
Definition at line 345 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::getInfo(), cppoptlib::NonlinearSolver< ProblemType >::setLineSearch(), cppoptlib::NonlinearSolver< ProblemType >::update_solver_info(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::update_solver_info().
solver_params
template<typename ProblemType > const json cppoptlib::NonlinearSolver< ProblemType >::solver_params protected
Definition at line 328 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::NonlinearSolver(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset().
total_time
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::total_time protected
Definition at line 347 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::reset_times(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
use_grad_norm_tol
template<typename ProblemType > double cppoptlib::NonlinearSolver< ProblemType >::use_grad_norm_tol protected
Definition at line 343 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), and cppoptlib::NonlinearSolver< ProblemType >::NonlinearSolver().
use_gradient_norm
template<typename ProblemType > bool cppoptlib::NonlinearSolver< ProblemType >::use_gradient_norm protected
Definition at line 341 of file NonlinearSolver.hpp.
Referenced by cppoptlib::NonlinearSolver< ProblemType >::minimize(), cppoptlib::NonlinearSolver< ProblemType >::NonlinearSolver(), and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
The documentation for this class was generated from the following file:
src/polyfem/solver/NonlinearSolver.hpp