PolyFEM: polyfem::solver::MeshTiling Class Reference
polyfem::solver::MeshTiling Class Reference
#include <SDFParametrizations.hpp>
Public Member Functions
MeshTiling (const Eigen::VectorXi &nums, const std::string in_path, const std::string out_path)
int size (const int x_size) const override
Eigen::VectorXd eval (const Eigen::VectorXd &x) const override
Eigen::VectorXd apply_jacobian (const Eigen::VectorXd &grad, const Eigen::VectorXd &x) const override
Public Member Functions inherited from polyfem::solver::Parametrization
Parametrization ()
virtual ~Parametrization ()
virtual Eigen::VectorXd inverse_eval (const Eigen::VectorXd &y)
virtual int size (const int x_size) const =0
virtual Eigen::VectorXd eval (const Eigen::VectorXd &x) const =0
virtual Eigen::VectorXd apply_jacobian (const Eigen::VectorXd &grad_full, const Eigen::VectorXd &x) const =0
Private Member Functions
bool tiling (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, Eigen::MatrixXd &Vnew, Eigen::MatrixXi &Fnew) const
Private Attributes
const Eigen::VectorXi nums_
const std::string in_path_
const std::string out_path_
Eigen::MatrixXd last_V
Eigen::VectorXi index_map
Detailed Description
Definition at line 9 of file SDFParametrizations.hpp.
Constructor & Destructor Documentation
MeshTiling()
polyfem::solver::MeshTiling::MeshTiling (const Eigen::VectorXi & nums, const std::string in_path, const std::string out_path)
Definition at line 65 of file SDFParametrizations.cpp.
References nums_.
Member Function Documentation
apply_jacobian()
Eigen::VectorXd polyfem::solver::MeshTiling::apply_jacobian (const Eigen::VectorXd & grad, const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 109 of file SDFParametrizations.cpp.
References index_map, polyfem::io::MshReader::load(), polyfem::log_and_throw_error(), out_path_, and x.
eval()
Eigen::VectorXd polyfem::solver::MeshTiling::eval (const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 80 of file SDFParametrizations.cpp.
References polyfem::utils::flatten(), in_path_, polyfem::io::MshReader::load(), polyfem::log_and_throw_error(), polyfem::logger(), tiling(), polyfem::utils::unflatten(), and x.
size()
int polyfem::solver::MeshTiling::size (const int x_size) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 70 of file SDFParametrizations.cpp.
References polyfem::io::MshReader::load(), and out_path_.
Referenced by tiling().
tiling()
bool polyfem::solver::MeshTiling::tiling (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F, Eigen::MatrixXd & Vnew, Eigen::MatrixXi & Fnew) const private
Definition at line 130 of file SDFParametrizations.cpp.
References polyfem::F, index_map, last_V, polyfem::io::MshReader::load(), polyfem::log_and_throw_error(), polyfem::logger(), nums_, out_path_, and size().
Referenced by eval().
Member Data Documentation
in_path_
const std::string polyfem::solver::MeshTiling::in_path_ private
Definition at line 21 of file SDFParametrizations.hpp.
Referenced by eval().
index_map
Eigen::VectorXi polyfem::solver::MeshTiling::index_map mutable private
Definition at line 26 of file SDFParametrizations.hpp.
Referenced by apply_jacobian(), and tiling().
last_V
Eigen::MatrixXd polyfem::solver::MeshTiling::last_V mutable private
Definition at line 25 of file SDFParametrizations.hpp.
Referenced by tiling().
nums_
const Eigen::VectorXi polyfem::solver::MeshTiling::nums_ private
Definition at line 20 of file SDFParametrizations.hpp.
Referenced by MeshTiling(), and tiling().
out_path_
const std::string polyfem::solver::MeshTiling::out_path_ private
Definition at line 21 of file SDFParametrizations.hpp.
Referenced by apply_jacobian(), size(), and tiling().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/parametrization/SDFParametrizations.hpp
src/polyfem/solver/forms/parametrization/SDFParametrizations.cpp