PolyFEM: polyfem::assembler::MixedAssembler Class Reference
polyfem::assembler::MixedAssembler Class Reference abstract
#include <Assembler.hpp>
Public Member Functions
MixedAssembler ()
virtual ~MixedAssembler ()=default
void assemble (const bool is_volume, const int n_psi_basis, const int n_phi_basis, const std::vector< basis::ElementBases > &psi_bases, const std::vector< basis::ElementBases > &phi_bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &psi_cache, const AssemblyValsCache &phi_cache, StiffnessMatrix &stiffness) const
virtual std::string name () const =0
int size () const
virtual void set_size (const int size)
Protected Member Functions
virtual int rows () const =0
virtual int cols () const =0
virtual Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > assemble (const MixedAssemblerData &data) const =0
Protected Attributes
int size_ = -1
Detailed Description
Definition at line 18 of file Assembler.hpp.
Constructor & Destructor Documentation
MixedAssembler()
polyfem::assembler::MixedAssembler::MixedAssembler ()
Definition at line 356 of file Assembler.cpp.
Referenced by polyfem::assembler::GenericElastic< AMIPSEnergy >::assemble_hessian().
~MixedAssembler()
virtual polyfem::assembler::MixedAssembler::~MixedAssembler () virtual default
Member Function Documentation
assemble() [1/2]
void polyfem::assembler::MixedAssembler::assemble (const bool is_volume, const int n_psi_basis, const int n_phi_basis, const std::vector< basis::ElementBases > & psi_bases, const std::vector< basis::ElementBases > & phi_bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & psi_cache, const AssemblyValsCache & phi_cache, StiffnessMatrix & stiffness) const
Referenced by polyfem::solver::NavierStokesSolver::minimize().
assemble() [2/2]
virtual Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::MixedAssembler::assemble (const MixedAssemblerData & data) const protected pure virtual
Implemented in polyfem::assembler::BilaplacianMixed, polyfem::assembler::IncompressibleLinearElasticityMixed, polyfem::assembler::StokesMixed, and polyfem::assembler::BilaplacianMixed.
cols()
virtual int polyfem::assembler::MixedAssembler::cols () const protected pure virtual
Implemented in polyfem::assembler::BilaplacianMixed, polyfem::assembler::IncompressibleLinearElasticityMixed, and polyfem::assembler::StokesMixed.
name()
virtual std::string polyfem::assembler::MixedAssembler::name () const pure virtual
Implemented in polyfem::assembler::BilaplacianMixed, polyfem::assembler::IncompressibleLinearElasticityMixed, and polyfem::assembler::StokesMixed.
rows()
virtual int polyfem::assembler::MixedAssembler::rows () const protected pure virtual
Implemented in polyfem::assembler::BilaplacianMixed, polyfem::assembler::IncompressibleLinearElasticityMixed, and polyfem::assembler::StokesMixed.
set_size()
virtual void polyfem::assembler::MixedAssembler::set_size (const int size) inline virtual
Definition at line 40 of file Assembler.hpp.
References size(), and size_.
size()
int polyfem::assembler::MixedAssembler::size () const inline
Definition at line 39 of file Assembler.hpp.
References size_.
Referenced by polyfem::assembler::IncompressibleLinearElasticityMixed::assemble(), polyfem::assembler::StokesMixed::rows(), and set_size().
Member Data Documentation
size_
int polyfem::assembler::MixedAssembler::size_ = -1 protected
Definition at line 43 of file Assembler.hpp.
Referenced by polyfem::assembler::IncompressibleLinearElasticityMixed::rows(), set_size(), and size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/Assembler.hpp
src/polyfem/assembler/Assembler.cpp