PolyFEM: polyfem::IntegrableFunctional Class Reference
polyfem::IntegrableFunctional Class Reference
#include <IntegrableFunctional.hpp>
Public Types
typedef std::function< void(const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const assembler::ElementAssemblyValues &, const json &, Eigen::MatrixXd &)> functionalType
Public Member Functions
IntegrableFunctional ()=default
void set_name (const std::string &name_)
std::string get_name () const
void set_j (const functionalType &j_)
void set_dj_dx (const functionalType &dj_dx_)
void set_dj_du (const functionalType &dj_du_)
void set_dj_dgradu (const functionalType &dj_dgradu_)
void set_dj_dgradu_local (const functionalType &dj_dgradu_local_)
void set_dj_dgradx (const functionalType &dj_dgradx_)
void evaluate (const std::map< std::string, Assembler::ParamFunc > &lame_params, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &u, const Eigen::MatrixXd &grad_u, const Eigen::MatrixXd &reference_normals, const assembler::ElementAssemblyValues &vals, json &params, Eigen::MatrixXd &val) const
void dj_dx (const std::map< std::string, Assembler::ParamFunc > &lame_params, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &u, const Eigen::MatrixXd &grad_u, const Eigen::MatrixXd &reference_normals, const assembler::ElementAssemblyValues &vals, json &params, Eigen::MatrixXd &val) const
void dj_du (const std::map< std::string, Assembler::ParamFunc > &lame_params, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &u, const Eigen::MatrixXd &grad_u, const Eigen::MatrixXd &reference_normals, const assembler::ElementAssemblyValues &vals, json &params, Eigen::MatrixXd &val) const
void dj_dgradu (const std::map< std::string, Assembler::ParamFunc > &lame_params, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &u, const Eigen::MatrixXd &grad_u, const Eigen::MatrixXd &reference_normals, const assembler::ElementAssemblyValues &vals, json &params, Eigen::MatrixXd &val) const
void dj_dgradu_local (const std::map< std::string, Assembler::ParamFunc > &lame_params, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &u, const Eigen::MatrixXd &grad_u, const Eigen::MatrixXd &reference_normals, const assembler::ElementAssemblyValues &vals, json &params, Eigen::MatrixXd &val) const
void dj_dgradx (const std::map< std::string, Assembler::ParamFunc > &lame_params, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &u, const Eigen::MatrixXd &grad_u, const Eigen::MatrixXd &reference_normals, const assembler::ElementAssemblyValues &vals, json &params, Eigen::MatrixXd &val) const
bool depend_on_x () const
bool depend_on_u () const
bool depend_on_gradu () const
bool depend_on_gradu_local () const
bool depend_on_gradx () const
Private Member Functions
void lambda_mu (const std::map< std::string, Assembler::ParamFunc > &lame_params, const int e, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &pts, Eigen::MatrixXd &lambda, Eigen::MatrixXd &mu) const
Private Attributes
std::string name = ""
bool has_x = false
bool has_u = false
bool has_gradu = false
bool has_gradu_local = false
bool has_gradx = false
functionalType j_func
functionalType dj_dx_func
functionalType dj_du_func
functionalType dj_dgradu_func
functionalType dj_dgradu_local_func
functionalType dj_dgradx_func
Detailed Description
Definition at line 13 of file IntegrableFunctional.hpp.
Member Typedef Documentation
functionalType
typedef std::function<void(const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const Eigen::MatrixXd &, const assembler::ElementAssemblyValues &, const json &, Eigen::MatrixXd &)> polyfem::IntegrableFunctional::functionalType
Definition at line 16 of file IntegrableFunctional.hpp.
Constructor & Destructor Documentation
IntegrableFunctional()
polyfem::IntegrableFunctional::IntegrableFunctional () default
Member Function Documentation
depend_on_gradu()
bool polyfem::IntegrableFunctional::depend_on_gradu () const inline
Definition at line 135 of file IntegrableFunctional.hpp.
References has_gradu.
Referenced by polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), and polyfem::solver::AdjointTools::dJ_du_step().
depend_on_gradu_local()
bool polyfem::IntegrableFunctional::depend_on_gradu_local () const inline
Definition at line 136 of file IntegrableFunctional.hpp.
References has_gradu_local.
Referenced by polyfem::solver::AdjointTools::dJ_du_step().
depend_on_gradx()
bool polyfem::IntegrableFunctional::depend_on_gradx () const inline
Definition at line 137 of file IntegrableFunctional.hpp.
References has_gradx.
Referenced by polyfem::solver::AdjointTools::compute_shape_derivative_functional_term().
depend_on_u()
bool polyfem::IntegrableFunctional::depend_on_u () const inline
Definition at line 134 of file IntegrableFunctional.hpp.
References has_u.
Referenced by polyfem::solver::AdjointTools::dJ_du_step().
depend_on_x()
bool polyfem::IntegrableFunctional::depend_on_x () const inline
Definition at line 133 of file IntegrableFunctional.hpp.
References has_x.
Referenced by polyfem::solver::AdjointTools::compute_shape_derivative_functional_term().
dj_dgradu()
void polyfem::IntegrableFunctional::dj_dgradu (const std::map< std::string, Assembler::ParamFunc > & lame_params, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & u, const Eigen::MatrixXd & grad_u, const Eigen::MatrixXd & reference_normals, const assembler::ElementAssemblyValues & vals, json & params, Eigen::MatrixXd & val) const inline
Definition at line 88 of file IntegrableFunctional.hpp.
References dj_dgradu_func, has_gradu, lambda_mu(), val, and vals.
Referenced by polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), and polyfem::solver::AdjointTools::dJ_du_step().
dj_dgradu_local()
void polyfem::IntegrableFunctional::dj_dgradu_local (const std::map< std::string, Assembler::ParamFunc > & lame_params, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & u, const Eigen::MatrixXd & grad_u, const Eigen::MatrixXd & reference_normals, const assembler::ElementAssemblyValues & vals, json & params, Eigen::MatrixXd & val) const inline
Definition at line 103 of file IntegrableFunctional.hpp.
References dj_dgradu_local_func, has_gradu_local, lambda_mu(), val, and vals.
Referenced by polyfem::solver::AdjointTools::dJ_du_step().
dj_dgradx()
void polyfem::IntegrableFunctional::dj_dgradx (const std::map< std::string, Assembler::ParamFunc > & lame_params, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & u, const Eigen::MatrixXd & grad_u, const Eigen::MatrixXd & reference_normals, const assembler::ElementAssemblyValues & vals, json & params, Eigen::MatrixXd & val) const inline
Definition at line 118 of file IntegrableFunctional.hpp.
References dj_dgradx_func, has_gradx, lambda_mu(), val, and vals.
Referenced by polyfem::solver::AdjointTools::compute_shape_derivative_functional_term().
dj_du()
void polyfem::IntegrableFunctional::dj_du (const std::map< std::string, Assembler::ParamFunc > & lame_params, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & u, const Eigen::MatrixXd & grad_u, const Eigen::MatrixXd & reference_normals, const assembler::ElementAssemblyValues & vals, json & params, Eigen::MatrixXd & val) const inline
Definition at line 73 of file IntegrableFunctional.hpp.
References dj_du_func, has_u, lambda_mu(), val, and vals.
Referenced by polyfem::solver::AdjointTools::dJ_du_step().
dj_dx()
void polyfem::IntegrableFunctional::dj_dx (const std::map< std::string, Assembler::ParamFunc > & lame_params, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & u, const Eigen::MatrixXd & grad_u, const Eigen::MatrixXd & reference_normals, const assembler::ElementAssemblyValues & vals, json & params, Eigen::MatrixXd & val) const inline
Definition at line 58 of file IntegrableFunctional.hpp.
References dj_dx_func, has_x, lambda_mu(), val, and vals.
Referenced by polyfem::solver::AdjointTools::compute_shape_derivative_functional_term().
evaluate()
void polyfem::IntegrableFunctional::evaluate (const std::map< std::string, Assembler::ParamFunc > & lame_params, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & u, const Eigen::MatrixXd & grad_u, const Eigen::MatrixXd & reference_normals, const assembler::ElementAssemblyValues & vals, json & params, Eigen::MatrixXd & val) const inline
Definition at line 50 of file IntegrableFunctional.hpp.
References j_func, lambda_mu(), val, and vals.
Referenced by polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), and polyfem::solver::AdjointTools::integrate_objective().
get_name()
std::string polyfem::IntegrableFunctional::get_name () const inline
Definition at line 21 of file IntegrableFunctional.hpp.
References name.
lambda_mu()
void polyfem::IntegrableFunctional::lambda_mu (const std::map< std::string, Assembler::ParamFunc > & lame_params, const int e, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & pts, Eigen::MatrixXd & lambda, Eigen::MatrixXd & mu) const inline private
Definition at line 140 of file IntegrableFunctional.hpp.
Referenced by dj_dgradu(), dj_dgradu_local(), dj_dgradx(), dj_du(), dj_dx(), and evaluate().
set_dj_dgradu()
void polyfem::IntegrableFunctional::set_dj_dgradu (const functionalType & dj_dgradu_) inline
Definition at line 34 of file IntegrableFunctional.hpp.
References dj_dgradu_func, and has_gradu.
Referenced by polyfem::solver::ElasticEnergyForm::get_integral_functional(), polyfem::solver::StressNormForm::get_integral_functional(), polyfem::solver::ComplianceForm::get_integral_functional(), and polyfem::solver::StressForm::get_integral_functional().
set_dj_dgradu_local()
void polyfem::IntegrableFunctional::set_dj_dgradu_local (const functionalType & dj_dgradu_local_) inline
Definition at line 39 of file IntegrableFunctional.hpp.
References dj_dgradu_local_func, and has_gradu_local.
set_dj_dgradx()
void polyfem::IntegrableFunctional::set_dj_dgradx (const functionalType & dj_dgradx_) inline
Definition at line 44 of file IntegrableFunctional.hpp.
References dj_dgradx_func, and has_gradx.
set_dj_du()
void polyfem::IntegrableFunctional::set_dj_du (const functionalType & dj_du_) inline
Definition at line 29 of file IntegrableFunctional.hpp.
References dj_du_func, and has_u.
Referenced by polyfem::solver::PositionForm::get_integral_functional(), polyfem::solver::AccelerationForm::get_integral_functional(), polyfem::solver::KineticForm::get_integral_functional(), and polyfem::solver::TargetForm::get_integral_functional().
set_dj_dx()
void polyfem::IntegrableFunctional::set_dj_dx (const functionalType & dj_dx_) inline
Definition at line 24 of file IntegrableFunctional.hpp.
References dj_dx_func, and has_x.
Referenced by polyfem::solver::PositionForm::get_integral_functional(), and polyfem::solver::TargetForm::get_integral_functional().
set_j()
void polyfem::IntegrableFunctional::set_j (const functionalType & j_) inline
Definition at line 23 of file IntegrableFunctional.hpp.
References j_func.
Referenced by polyfem::solver::ElasticEnergyForm::get_integral_functional(), polyfem::solver::StressNormForm::get_integral_functional(), polyfem::solver::ComplianceForm::get_integral_functional(), polyfem::solver::PositionForm::get_integral_functional(), polyfem::solver::AccelerationForm::get_integral_functional(), polyfem::solver::KineticForm::get_integral_functional(), polyfem::solver::StressForm::get_integral_functional(), polyfem::solver::VolumeForm::get_integral_functional(), and polyfem::solver::TargetForm::get_integral_functional().
set_name()
void polyfem::IntegrableFunctional::set_name (const std::string & name_) inline
Definition at line 20 of file IntegrableFunctional.hpp.
References name.
Member Data Documentation
dj_dgradu_func
functionalType polyfem::IntegrableFunctional::dj_dgradu_func private
Definition at line 161 of file IntegrableFunctional.hpp.
Referenced by dj_dgradu(), and set_dj_dgradu().
dj_dgradu_local_func
functionalType polyfem::IntegrableFunctional::dj_dgradu_local_func private
Definition at line 161 of file IntegrableFunctional.hpp.
Referenced by dj_dgradu_local(), and set_dj_dgradu_local().
dj_dgradx_func
functionalType polyfem::IntegrableFunctional::dj_dgradx_func private
Definition at line 161 of file IntegrableFunctional.hpp.
Referenced by dj_dgradx(), and set_dj_dgradx().
dj_du_func
functionalType polyfem::IntegrableFunctional::dj_du_func private
Definition at line 161 of file IntegrableFunctional.hpp.
Referenced by dj_du(), and set_dj_du().
dj_dx_func
functionalType polyfem::IntegrableFunctional::dj_dx_func private
Definition at line 161 of file IntegrableFunctional.hpp.
Referenced by dj_dx(), and set_dj_dx().
has_gradu
bool polyfem::IntegrableFunctional::has_gradu = false private
Definition at line 160 of file IntegrableFunctional.hpp.
Referenced by depend_on_gradu(), dj_dgradu(), and set_dj_dgradu().
has_gradu_local
bool polyfem::IntegrableFunctional::has_gradu_local = false private
Definition at line 160 of file IntegrableFunctional.hpp.
Referenced by depend_on_gradu_local(), dj_dgradu_local(), and set_dj_dgradu_local().
has_gradx
bool polyfem::IntegrableFunctional::has_gradx = false private
Definition at line 160 of file IntegrableFunctional.hpp.
Referenced by depend_on_gradx(), dj_dgradx(), and set_dj_dgradx().
has_u
bool polyfem::IntegrableFunctional::has_u = false private
Definition at line 160 of file IntegrableFunctional.hpp.
Referenced by depend_on_u(), dj_du(), and set_dj_du().
has_x
bool polyfem::IntegrableFunctional::has_x = false private
Definition at line 160 of file IntegrableFunctional.hpp.
Referenced by depend_on_x(), dj_dx(), and set_dj_dx().
j_func
functionalType polyfem::IntegrableFunctional::j_func private
Definition at line 161 of file IntegrableFunctional.hpp.
Referenced by evaluate(), and set_j().
name
std::string polyfem::IntegrableFunctional::name = "" private
Definition at line 159 of file IntegrableFunctional.hpp.
Referenced by get_name(), and set_name().
The documentation for this class was generated from the following file:
src/polyfem/utils/IntegrableFunctional.hpp