PolyFEM: polyfem::utils::PiecewiseInterpolation Class Reference
polyfem::utils::PiecewiseInterpolation Class Reference abstract
#include <Interpolation.hpp>
Public Types
enum class Extend { CONSTANT , EXTRAPOLATE , REPEAT , REPEAT_OFFSET }
Public Member Functions
virtual void init (const json &params) override
double eval (const double t) const override
double extend (const double t) const
Public Member Functions inherited from polyfem::utils::Interpolation
virtual ~Interpolation ()
Public Attributes
std::vector< double > points_
std::vector< double > values_
Extend extend_
Protected Member Functions
virtual double eval_piece (const double t, const int i) const =0
double dy_dt (const double t) const
virtual double dy_dt_piece (const double t, const int i) const =0
Additional Inherited Members
Static Public Member Functions inherited from polyfem::utils::Interpolation
static std::shared_ptr< Interpolation > build (const json &params)
Detailed Description
Definition at line 43 of file Interpolation.hpp.
Member Enumeration Documentation
Extend
enum class polyfem::utils::PiecewiseInterpolation::Extend strong
Enumerator
CONSTANT
EXTRAPOLATE
REPEAT
REPEAT_OFFSET
Definition at line 54 of file Interpolation.hpp.
Member Function Documentation
dy_dt()
double polyfem::utils::PiecewiseInterpolation::dy_dt (const double t) const protected
Definition at line 129 of file Interpolation.cpp.
References dy_dt_piece(), and points_.
Referenced by extend().
dy_dt_piece()
virtual double polyfem::utils::PiecewiseInterpolation::dy_dt_piece (const double t, const int i) const protected pure virtual
Implemented in polyfem::utils::PiecewiseConstantInterpolation, polyfem::utils::PiecewiseLinearInterpolation, and polyfem::utils::PiecewiseCubicInterpolation.
Referenced by dy_dt().
eval()
double polyfem::utils::PiecewiseInterpolation::eval (const double t) const override virtual
Implements polyfem::utils::Interpolation.
Definition at line 73 of file Interpolation.cpp.
References eval_piece(), extend(), points_, and values_.
Referenced by extend().
eval_piece()
virtual double polyfem::utils::PiecewiseInterpolation::eval_piece (const double t, const int i) const protected pure virtual
Implemented in polyfem::utils::PiecewiseConstantInterpolation, polyfem::utils::PiecewiseLinearInterpolation, and polyfem::utils::PiecewiseCubicInterpolation.
Referenced by eval().
extend()
double polyfem::utils::PiecewiseInterpolation::extend (const double t) const
Definition at line 90 of file Interpolation.cpp.
References CONSTANT, dy_dt(), eval(), extend_, EXTRAPOLATE, points_, REPEAT, REPEAT_OFFSET, and values_.
Referenced by eval().
init()
void polyfem::utils::PiecewiseInterpolation::init (const json & params) override virtual
Reimplemented from polyfem::utils::Interpolation.
Reimplemented in polyfem::utils::PiecewiseCubicInterpolation.
Definition at line 58 of file Interpolation.cpp.
References extend_, polyfem::log_and_throw_error(), points_, and values_.
Referenced by polyfem::utils::PiecewiseCubicInterpolation::init().
Member Data Documentation
extend_
Extend polyfem::utils::PiecewiseInterpolation::extend_
Definition at line 61 of file Interpolation.hpp.
Referenced by extend(), init(), and polyfem::utils::PiecewiseCubicInterpolation::init().
points_
std::vector<double> polyfem::utils::PiecewiseInterpolation::points_
Definition at line 51 of file Interpolation.hpp.
Referenced by dy_dt(), polyfem::utils::PiecewiseLinearInterpolation::dy_dt_piece(), eval(), polyfem::utils::PiecewiseLinearInterpolation::eval_piece(), extend(), init(), and polyfem::utils::PiecewiseCubicInterpolation::init().
values_
std::vector<double> polyfem::utils::PiecewiseInterpolation::values_
Definition at line 52 of file Interpolation.hpp.
Referenced by polyfem::utils::PiecewiseLinearInterpolation::dy_dt_piece(), eval(), polyfem::utils::PiecewiseConstantInterpolation::eval_piece(), polyfem::utils::PiecewiseLinearInterpolation::eval_piece(), extend(), init(), and polyfem::utils::PiecewiseCubicInterpolation::init().
The documentation for this class was generated from the following files:
src/polyfem/utils/Interpolation.hpp
src/polyfem/utils/Interpolation.cpp