PolyFEM: polyfem::solver::LayerThicknessForm Class Reference
polyfem::solver::LayerThicknessForm Class Reference
#include <BarrierForms.hpp>
Public Member Functions
LayerThicknessForm (const VariableToSimulationGroup &variable_to_simulations, const State &state, const std::vector< int > &boundary_ids, const double dhat, const bool use_log_barrier=false, const double dmin=0)
std::string name () const override
double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine the maximum step size allowable between the current and next solution.
Public Member Functions inherited from polyfem::solver::CollisionBarrierForm
CollisionBarrierForm (const VariableToSimulationGroup &variable_to_simulation, const State &state, const double dhat, const double dmin=0)
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
void solution_changed (const Eigen::VectorXd &x) override
Update cached fields upon a change in the solution.
bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Checks if the step is collision free.
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual void finish ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
void build_collision_mesh ()
Protected Member Functions inherited from polyfem::solver::CollisionBarrierForm
void build_collision_set (const Eigen::MatrixXd &displaced_surface)
Eigen::VectorXd get_updated_mesh_nodes (const Eigen::VectorXd &x) const
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes
std::vector< int > boundary_ids_
std::map< int, std::set< int > > boundary_ids_to_dof_
Eigen::MatrixXi can_collide_cache_
Protected Attributes inherited from polyfem::solver::CollisionBarrierForm
const State & state_
Eigen::VectorXd X_init
ipc::CollisionMesh collision_mesh_
ipc::NormalCollisions collision_set
const double dhat_
const double dmin_
ipc::BroadPhaseMethod broad_phase_method_
ipc::BarrierPotential barrier_potential_
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Detailed Description
Definition at line 46 of file BarrierForms.hpp.
Constructor & Destructor Documentation
LayerThicknessForm()
polyfem::solver::LayerThicknessForm::LayerThicknessForm (const VariableToSimulationGroup & variable_to_simulations, const State & state, const std::vector< int > & boundary_ids, const double dhat, const bool use_log_barrier = false, const double dmin = 0)
Definition at line 236 of file BarrierForms.cpp.
References polyfem::solver::CollisionBarrierForm::barrier_potential_, boundary_ids_, boundary_ids_to_dof_, and build_collision_mesh().
Member Function Documentation
build_collision_mesh()
void polyfem::solver::LayerThicknessForm::build_collision_mesh () protected
Definition at line 254 of file BarrierForms.cpp.
References boundary_ids_, boundary_ids_to_dof_, polyfem::utils::BoundarySampler::boundary_quadrature(), can_collide_cache_, polyfem::solver::CollisionBarrierForm::collision_mesh_, polyfem::io::OutGeometryData::extract_boundary_mesh(), polyfem::State::geom_bases(), polyfem::assembler::AssemblyValues::global, polyfem::basis::ElementBases::local_nodes_for_primitive(), polyfem::State::mesh, polyfem::State::n_boundary_samples(), polyfem::State::n_geom_bases, polyfem::solver::CollisionBarrierForm::state_, polyfem::State::total_local_boundary, and vals.
Referenced by LayerThicknessForm().
max_step_size()
double polyfem::solver::LayerThicknessForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline override virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::CollisionBarrierForm.
Definition at line 58 of file BarrierForms.hpp.
name()
std::string polyfem::solver::LayerThicknessForm::name () const inline override virtual
Reimplemented from polyfem::solver::CollisionBarrierForm.
Definition at line 56 of file BarrierForms.hpp.
Member Data Documentation
boundary_ids_
std::vector<int> polyfem::solver::LayerThicknessForm::boundary_ids_ protected
Definition at line 63 of file BarrierForms.hpp.
Referenced by build_collision_mesh(), and LayerThicknessForm().
boundary_ids_to_dof_
std::map<int, std::set<int> > polyfem::solver::LayerThicknessForm::boundary_ids_to_dof_ protected
Definition at line 64 of file BarrierForms.hpp.
Referenced by build_collision_mesh(), and LayerThicknessForm().
can_collide_cache_
Eigen::MatrixXi polyfem::solver::LayerThicknessForm::can_collide_cache_ protected
Definition at line 65 of file BarrierForms.hpp.
Referenced by build_collision_mesh().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/BarrierForms.hpp
src/polyfem/solver/forms/adjoint_forms/BarrierForms.cpp