PolyFEM: polyfem::assembler::StokesVelocity Class Reference
polyfem::assembler::StokesVelocity Class Reference
#include <Stokes.hpp>
Public Member Functions
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > assemble (const LinearAssemblerData &data) const override
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > compute_rhs (const AutodiffHessianPt &pt) const
void add_multimaterial (const int index, const json &params)
void compute_norm_velocity (const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &velocity, Eigen::MatrixXd &norms) const
void compute_stress_tensor (const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &velocity, Eigen::MatrixXd &tensor) const
double viscosity () const
void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual LocalBlockMatrix assemble (const LinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::LinearAssembler< LocalBlockMatrix >
LinearAssembler ()
virtual ~LinearAssembler ()=default
void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
Private Attributes
double viscosity_ = 1
Additional Inherited Members
virtual LocalBlockMatrix assemble (const LinearAssemblerData &data) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 9 of file Stokes.hpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::StokesVelocity::add_multimaterial (const int index, const json & params)
Definition at line 5 of file Stokes.cpp.
References polyfem::assembler::Assembler::size(), and viscosity_.
assemble() [1/3]
void polyfem::assembler::LinearAssembler< LocalBlockMatrix >::assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, StiffnessMatrix & stiffness, const bool is_mass = false) const
assemble() [2/3]
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > polyfem::assembler::StokesVelocity::assemble (const LinearAssemblerData & data) const override virtual
Implements polyfem::assembler::LinearAssembler< LocalBlockMatrix >.
Definition at line 16 of file Stokes.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::LinearAssemblerData::da, polyfem::assembler::LinearAssemblerData::i, polyfem::assembler::LinearAssemblerData::j, polyfem::assembler::Assembler::size(), polyfem::assembler::LinearAssemblerData::vals, and viscosity_.
assemble() [3/3]
virtual LocalBlockMatrix polyfem::assembler::LinearAssembler< LocalBlockMatrix >::assemble (const LinearAssemblerData & data) const virtual
Implements polyfem::assembler::LinearAssembler< LocalBlockMatrix >.
compute_norm_velocity()
void polyfem::assembler::StokesVelocity::compute_norm_velocity (const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & velocity, Eigen::MatrixXd & norms) const
Definition at line 53 of file Stokes.cpp.
References polyfem::basis::ElementBases::bases, polyfem::basis::Basis::global(), polyfem::assembler::Assembler::size(), and vals.
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::StokesVelocity::compute_rhs (const AutodiffHessianPt & pt) const
Definition at line 40 of file Stokes.cpp.
References polyfem::assembler::Assembler::size(), and viscosity_.
compute_stress_tensor()
void polyfem::assembler::StokesVelocity::compute_stress_tensor (const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & velocity, Eigen::MatrixXd & tensor) const
Definition at line 89 of file Stokes.cpp.
References polyfem::basis::ElementBases::bases, polyfem::basis::Basis::global(), polyfem::assembler::Assembler::size(), and vals.
viscosity()
double polyfem::assembler::StokesVelocity::viscosity () const inline
Definition at line 27 of file Stokes.hpp.
References viscosity_.
Member Data Documentation
viscosity_
double polyfem::assembler::StokesVelocity::viscosity_ = 1 private
Definition at line 30 of file Stokes.hpp.
Referenced by add_multimaterial(), assemble(), compute_rhs(), and viscosity().
The documentation for this class was generated from the following files:
src/polyfem/assembler/Stokes.hpp
src/polyfem/assembler/Stokes.cpp