PolyFEM: polyfem::solver::StaticForm Class Reference
polyfem::solver::StaticForm Class Reference abstract
#include <AdjointForm.hpp>
Public Member Functions
virtual ~StaticForm ()=default
virtual std::string name () const override
Eigen::MatrixXd compute_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const final override
void compute_partial_gradient_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
double value_unweighted (const Eigen::VectorXd &x) const final override
Compute the value of the form.
virtual Eigen::VectorXd compute_adjoint_rhs_unweighted_step (const int time_step, const Eigen::VectorXd &x, const State &state) const =0
virtual Eigen::VectorXd compute_adjoint_rhs_unweighted_step_prev (const int time_step, const Eigen::VectorXd &x, const State &state) const
virtual void compute_partial_gradient_unweighted_step (const int time_step, const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const =0
virtual double value_unweighted_step (const int time_step, const Eigen::VectorXd &x) const =0
virtual void solution_changed_step (const int time_step, const Eigen::VectorXd &new_x)
virtual bool depends_on_step_prev () const final
AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations)
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations)
virtual ~AdjointForm ()
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
void enable_energy_print (const std::string &print_energy_keyword)
virtual void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
const auto & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const final
virtual void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x)
Update fields after a step in the optimization.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num)
Update lagged fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC)
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Attributes
bool depends_on_step_prev_ = false
Protected Attributes inherited from polyfem::solver::AdjointForm
std::vector< std::shared_ptr< VariableToSimulation > > variable_to_simulations_
int print_energy_ = 0
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or Δt²)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Additional Inherited Members
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Detailed Description
Definition at line 54 of file AdjointForm.hpp.
Constructor & Destructor Documentation
~StaticForm()
virtual polyfem::solver::StaticForm::~StaticForm () virtual default
Member Function Documentation
AdjointForm()
polyfem::solver::AdjointForm::AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > & variable_to_simulations) inline
Definition at line 11 of file AdjointForm.hpp.
compute_adjoint_rhs_unweighted()
Eigen::MatrixXd polyfem::solver::StaticForm::compute_adjoint_rhs_unweighted (const Eigen::VectorXd & x, const State & state) const final override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 91 of file AdjointForm.cpp.
References compute_adjoint_rhs_unweighted_step(), depends_on_step_prev(), polyfem::State::diff_cached, polyfem::State::ndof(), polyfem::solver::DiffCache::size(), and x.
compute_adjoint_rhs_unweighted_step()
virtual Eigen::VectorXd polyfem::solver::StaticForm::compute_adjoint_rhs_unweighted_step (const int time_step, const Eigen::VectorXd & x, const State & state) const pure virtual
Implemented in polyfem::solver::MaxStressForm, polyfem::solver::SpatialIntegralForm, polyfem::solver::NodeTargetForm, and polyfem::solver::BarycenterTargetForm.
Referenced by compute_adjoint_rhs_unweighted().
compute_adjoint_rhs_unweighted_step_prev()
Eigen::VectorXd polyfem::solver::StaticForm::compute_adjoint_rhs_unweighted_step_prev (const int time_step, const Eigen::VectorXd & x, const State & state) const virtual
Definition at line 86 of file AdjointForm.cpp.
References polyfem::State::ndof().
compute_partial_gradient_unweighted()
void polyfem::solver::StaticForm::compute_partial_gradient_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const final override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 81 of file AdjointForm.cpp.
References compute_partial_gradient_unweighted_step(), and x.
compute_partial_gradient_unweighted_step()
virtual void polyfem::solver::StaticForm::compute_partial_gradient_unweighted_step (const int time_step, const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const pure virtual
Implemented in polyfem::solver::MaxStressForm, polyfem::solver::SpatialIntegralForm, polyfem::solver::ElasticEnergyForm, polyfem::solver::StressNormForm, polyfem::solver::ComplianceForm, polyfem::solver::StressForm, polyfem::solver::NodeTargetForm, and polyfem::solver::BarycenterTargetForm.
Referenced by compute_partial_gradient_unweighted().
depends_on_step_prev()
virtual bool polyfem::solver::StaticForm::depends_on_step_prev () const inline final virtual
Definition at line 71 of file AdjointForm.hpp.
References depends_on_step_prev_.
Referenced by compute_adjoint_rhs_unweighted().
name()
virtual std::string polyfem::solver::StaticForm::name () const inline override virtual
Reimplemented from polyfem::solver::AdjointForm.
Reimplemented in polyfem::solver::MaxStressForm, polyfem::solver::SpatialIntegralForm, polyfem::solver::ElasticEnergyForm, polyfem::solver::StressNormForm, polyfem::solver::ComplianceForm, polyfem::solver::StressForm, and polyfem::solver::TargetForm.
Definition at line 60 of file AdjointForm.hpp.
solution_changed_step()
virtual void polyfem::solver::StaticForm::solution_changed_step (const int time_step, const Eigen::VectorXd & new_x) inline virtual
Definition at line 70 of file AdjointForm.hpp.
value_unweighted()
double polyfem::solver::StaticForm::value_unweighted (const Eigen::VectorXd & x) const final override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 76 of file AdjointForm.cpp.
References value_unweighted_step(), and x.
value_unweighted_step()
virtual double polyfem::solver::StaticForm::value_unweighted_step (const int time_step, const Eigen::VectorXd & x) const pure virtual
Implemented in polyfem::solver::MaxStressForm, polyfem::solver::SpatialIntegralForm, polyfem::solver::NodeTargetForm, and polyfem::solver::BarycenterTargetForm.
Referenced by value_unweighted().
Member Data Documentation
depends_on_step_prev_
bool polyfem::solver::StaticForm::depends_on_step_prev_ = false protected
Definition at line 74 of file AdjointForm.hpp.
Referenced by depends_on_step_prev().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/AdjointForm.hpp
src/polyfem/solver/forms/adjoint_forms/AdjointForm.cpp