PolyFEM: polyfem::io::MshReader Class Reference
polyfem::io::MshReader Class Reference
#include <MshReader.hpp>
Static Public Member Functions
static bool load (const std::string &path, Eigen::MatrixXd &vertices, Eigen::MatrixXi &cells, std::vector< std::vector< int > > &elements, std::vector< std::vector< double > > &weights, std::vector< int > &body_ids)
static bool load (const std::string &path, Eigen::MatrixXd &vertices, Eigen::MatrixXi &cells, std::vector< std::vector< int > > &elements, std::vector< std::vector< double > > &weights, std::vector< int > &body_ids, std::vector< std::string > &node_data_name, std::vector< std::vector< double > > &node_data)
Detailed Description
Definition at line 9 of file MshReader.hpp.
Member Function Documentation
load() [1/2]
bool polyfem::io::MshReader::load (const std::string & path, Eigen::MatrixXd & vertices, Eigen::MatrixXi & cells, std::vector< std::vector< int > > & elements, std::vector< std::vector< double > > & weights, std::vector< int > & body_ids) static
Definition at line 29 of file MshReader.cpp.
References load().
Referenced by polyfem::solver::MeshTiling::apply_jacobian(), polyfem::mesh::Mesh::create(), polyfem::solver::MeshTiling::eval(), polyfem::solver::MeshAffine::eval(), load(), polyfem::mesh::read_surface_mesh(), polyfem::solver::MeshTiling::size(), and polyfem::solver::MeshTiling::tiling().
load() [2/2]
bool polyfem::io::MshReader::load (const std::string & path, Eigen::MatrixXd & vertices, Eigen::MatrixXi & cells, std::vector< std::vector< int > > & elements, std::vector< std::vector< double > > & weights, std::vector< int > & body_ids, std::vector< std::string > & node_data_name, std::vector< std::vector< double > > & node_data) static
Definition at line 37 of file MshReader.cpp.
References polyfem::logger(), and polyfem::io::map_entity_tag_to_physical_tag().
The documentation for this class was generated from the following files:
src/polyfem/io/MshReader.hpp
src/polyfem/io/MshReader.cpp