PolyFEM: polyfem::time_integrator::BDFTimeIntegrator Class Reference
polyfem::time_integrator::BDFTimeIntegrator Class Reference
#include <BDFTimeIntegrator.hpp>
Public Member Functions
BDFTimeIntegrator ()
void set_parameters (const nlohmann::json &params) override
void init (const std::vector< Eigen::VectorXd > &x_prevs, const std::vector< Eigen::VectorXd > &v_prevs, const std::vector< Eigen::VectorXd > &a_prevs, double dt)
void update_quantities (const Eigen::VectorXd &x) override
Eigen::VectorXd x_tilde () const override
double acceleration_scaling () const override
virtual void init (const Eigen::VectorXd &x_prev, const Eigen::VectorXd &v_prev, const Eigen::VectorXd &a_prev, double dt)
Public Member Functions inherited from polyfem::time_integrator::ImplicitTimeIntegrator
ImplicitTimeIntegrator ()
virtual ~ImplicitTimeIntegrator ()=default
virtual void set_parameters (const nlohmann::json &params)
virtual void init (const Eigen::VectorXd &x_prev, const Eigen::VectorXd &v_prev, const Eigen::VectorXd &a_prev, double dt)
virtual void update_quantities (const Eigen::VectorXd &x)=0
virtual Eigen::VectorXd x_tilde () const =0
virtual double acceleration_scaling () const =0
const double & dt () const
virtual void save_raw (const std::string &x_path, const std::string &v_path, const std::string &a_path) const
const Eigen::VectorXd & x_prev () const
const Eigen::VectorXd & v_prev () const
const Eigen::VectorXd & a_prev () const
Protected Member Functions
Eigen::VectorXd weighted_sum_x_prevs () const
Eigen::VectorXd weighted_sum_v_prevs () const
Protected Member Functions inherited from polyfem::time_integrator::ImplicitTimeIntegrator
Eigen::VectorXd & x_prev ()
Eigen::VectorXd & v_prev ()
Eigen::VectorXd & a_prev ()
Static Protected Member Functions
static const std::vector< double > & alphas (const int i)
static double betas (const int i)
Protected Attributes
int num_steps
Protected Attributes inherited from polyfem::time_integrator::ImplicitTimeIntegrator
double _dt = 1
std::deque< Eigen::VectorXd > x_prevs
std::deque< Eigen::VectorXd > v_prevs
std::deque< Eigen::VectorXd > a_prevs
Static Protected Attributes
static const std::vector< double > test_betas
Additional Inherited Members
Static Public Member Functions inherited from polyfem::time_integrator::ImplicitTimeIntegrator
static std::shared_ptr< ImplicitTimeIntegrator > construct_time_integrator (const std::string &name)
static const std::vector< std::string > & get_time_integrator_names ()
Detailed Description
Definition at line 9 of file BDFTimeIntegrator.hpp.
Constructor & Destructor Documentation
BDFTimeIntegrator()
polyfem::time_integrator::BDFTimeIntegrator::BDFTimeIntegrator () inline
Definition at line 12 of file BDFTimeIntegrator.hpp.
Member Function Documentation
acceleration_scaling()
double polyfem::time_integrator::BDFTimeIntegrator::acceleration_scaling () const override virtual
Implements polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 124 of file BDFTimeIntegrator.cpp.
References betas(), polyfem::time_integrator::ImplicitTimeIntegrator::dt(), and polyfem::time_integrator::ImplicitTimeIntegrator::x_prevs.
alphas()
const std::vector< double > & polyfem::time_integrator::BDFTimeIntegrator::alphas (const int i) static protected
Definition at line 43 of file BDFTimeIntegrator.cpp.
Referenced by weighted_sum_v_prevs(), and weighted_sum_x_prevs().
betas()
double polyfem::time_integrator::BDFTimeIntegrator::betas (const int i) static protected
Definition at line 57 of file BDFTimeIntegrator.cpp.
Referenced by acceleration_scaling(), update_quantities(), and x_tilde().
init() [1/2]
void polyfem::time_integrator::ImplicitTimeIntegrator::init (const Eigen::VectorXd & x_prev, const Eigen::VectorXd & v_prev, const Eigen::VectorXd & a_prev, double dt) virtual
Reimplemented from polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 22 of file ImplicitTimeIntegrator.cpp.
init() [2/2]
void polyfem::time_integrator::BDFTimeIntegrator::init (const std::vector< Eigen::VectorXd > & x_prevs, const std::vector< Eigen::VectorXd > & v_prevs, const std::vector< Eigen::VectorXd > & a_prevs, double dt)
Definition at line 21 of file BDFTimeIntegrator.cpp.
References polyfem::time_integrator::ImplicitTimeIntegrator::a_prevs, polyfem::time_integrator::ImplicitTimeIntegrator::v_prevs, and polyfem::time_integrator::ImplicitTimeIntegrator::x_prevs.
set_parameters()
void polyfem::time_integrator::BDFTimeIntegrator::set_parameters (const nlohmann::json & params) override virtual
Reimplemented from polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 11 of file BDFTimeIntegrator.cpp.
References polyfem::utils::logger(), and num_steps.
update_quantities()
void polyfem::time_integrator::BDFTimeIntegrator::update_quantities (const Eigen::VectorXd & x) override virtual
Implements polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 97 of file BDFTimeIntegrator.cpp.
References polyfem::time_integrator::ImplicitTimeIntegrator::a_prevs, betas(), polyfem::time_integrator::ImplicitTimeIntegrator::dt(), num_steps, polyfem::time_integrator::ImplicitTimeIntegrator::v_prev(), polyfem::time_integrator::ImplicitTimeIntegrator::v_prevs, weighted_sum_v_prevs(), weighted_sum_x_prevs(), x, polyfem::time_integrator::ImplicitTimeIntegrator::x_prev(), and polyfem::time_integrator::ImplicitTimeIntegrator::x_prevs.
weighted_sum_v_prevs()
Eigen::VectorXd polyfem::time_integrator::BDFTimeIntegrator::weighted_sum_v_prevs () const protected
Definition at line 84 of file BDFTimeIntegrator.cpp.
References alphas(), polyfem::time_integrator::ImplicitTimeIntegrator::v_prev(), and polyfem::time_integrator::ImplicitTimeIntegrator::v_prevs.
Referenced by update_quantities(), and x_tilde().
weighted_sum_x_prevs()
Eigen::VectorXd polyfem::time_integrator::BDFTimeIntegrator::weighted_sum_x_prevs () const protected
Definition at line 71 of file BDFTimeIntegrator.cpp.
References alphas(), polyfem::time_integrator::ImplicitTimeIntegrator::x_prev(), and polyfem::time_integrator::ImplicitTimeIntegrator::x_prevs.
Referenced by update_quantities(), and x_tilde().
x_tilde()
Eigen::VectorXd polyfem::time_integrator::BDFTimeIntegrator::x_tilde () const override virtual
Implements polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 118 of file BDFTimeIntegrator.cpp.
References betas(), polyfem::time_integrator::ImplicitTimeIntegrator::dt(), weighted_sum_v_prevs(), weighted_sum_x_prevs(), and polyfem::time_integrator::ImplicitTimeIntegrator::x_prevs.
Member Data Documentation
num_steps
int polyfem::time_integrator::BDFTimeIntegrator::num_steps protected
Definition at line 30 of file BDFTimeIntegrator.hpp.
Referenced by set_parameters(), and update_quantities().
test_betas
const std::vector<double> polyfem::time_integrator::BDFTimeIntegrator::test_betas static protected
Definition at line 35 of file BDFTimeIntegrator.hpp.
The documentation for this class was generated from the following files:
src/polyfem/time_integrator/BDFTimeIntegrator.hpp
src/polyfem/time_integrator/BDFTimeIntegrator.cpp