PolyFEM: polyfem::assembler::IncompressibleLinearElasticityPressure Class Reference
polyfem::assembler::IncompressibleLinearElasticityPressure Class Reference
#include <IncompressibleLinElast.hpp>
Public Member Functions
Eigen::Matrix< double, 1, 1 > assemble (const ElementAssemblyValues &vals, const int i, const int j, const QuadratureVector &da) const
Eigen::Matrix< double, 1, 1 > compute_rhs (const AutodiffHessianPt &pt) const
int size () const
void set_size (const int size)
void add_multimaterial (const int index, const json &params)
void set_params (const LameParameters &params)
Private Attributes
int size_ = -1
LameParameters params_
Detailed Description
Definition at line 71 of file IncompressibleLinElast.hpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::IncompressibleLinearElasticityPressure::add_multimaterial (const int index, const json & params)
Definition at line 157 of file IncompressibleLinElast.cpp.
References polyfem::LameParameters::add_multimaterial(), params_, and size_.
assemble()
Eigen::Matrix< double, 1, 1 > polyfem::assembler::IncompressibleLinearElasticityPressure::assemble (const ElementAssemblyValues & vals, const int i, const int j, const QuadratureVector & da) const
Definition at line 165 of file IncompressibleLinElast.cpp.
References da, polyfem::LameParameters::lambda_mu(), params_, and vals.
compute_rhs()
Eigen::Matrix< double, 1, 1 > polyfem::assembler::IncompressibleLinearElasticityPressure::compute_rhs (const AutodiffHessianPt & pt) const inline
Definition at line 79 of file IncompressibleLinElast.hpp.
set_params()
void polyfem::assembler::IncompressibleLinearElasticityPressure::set_params (const LameParameters & params) inline
Definition at line 89 of file IncompressibleLinElast.hpp.
References params_.
set_size()
void polyfem::assembler::IncompressibleLinearElasticityPressure::set_size (const int size) inline
Definition at line 86 of file IncompressibleLinElast.hpp.
References size(), and size_.
size()
int polyfem::assembler::IncompressibleLinearElasticityPressure::size () const inline
Definition at line 85 of file IncompressibleLinElast.hpp.
Referenced by set_size().
Member Data Documentation
params_
LameParameters polyfem::assembler::IncompressibleLinearElasticityPressure::params_ private
Definition at line 93 of file IncompressibleLinElast.hpp.
Referenced by add_multimaterial(), assemble(), and set_params().
size_
int polyfem::assembler::IncompressibleLinearElasticityPressure::size_ = -1 private
Definition at line 92 of file IncompressibleLinElast.hpp.
Referenced by add_multimaterial(), and set_size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/IncompressibleLinElast.hpp
src/polyfem/assembler/IncompressibleLinElast.cpp