PolyFEM: polyfem::solver::NLProblem Class Reference
polyfem::solver::NLProblem Class Reference
#include <NLProblem.hpp>
Public Types
typedef StiffnessMatrix THessian
Public Member Functions
NLProblem (const State &state, const assembler::RhsAssembler &rhs_assembler, const double t, const double dhat, const bool no_reduced=false)
void init (const TVector &displacement)
void init_time_integrator (const TVector &x_prev, const TVector &v_prev, const TVector &a_prev, const double dt)
TVector initial_guess ()
virtual double value (const TVector &x) override
virtual void gradient (const TVector &x, TVector &gradv) override
virtual void gradient_no_rhs (const TVector &x, Eigen::MatrixXd &gradv, const bool only_elastic=false)
virtual double value (const TVector &x, const bool only_elastic)
void gradient (const TVector &x, TVector &gradv, const bool only_elastic)
bool is_step_valid (const TVector &x0, const TVector &x1)
bool is_step_collision_free (const TVector &x0, const TVector &x1)
double max_step_size (const TVector &x0, const TVector &x1)
bool is_intersection_free (const TVector &x)
void line_search_begin (const TVector &x0, const TVector &x1)
void line_search_end ()
void post_step (const int iter_num, const TVector &x)
virtual void hessian (const TVector &x, THessian &hessian)
virtual void hessian_full (const TVector &x, THessian &gradv)
template<class FullVector >
void full_to_reduced (const FullVector &full, TVector &reduced) const
template<class FullVector >
void reduced_to_full (const TVector &reduced, FullVector &full)
void full_hessian_to_reduced_hessian (const THessian &full, THessian &reduced) const
virtual void update_quantities (const double t, const TVector &x)
void substepping (const double t)
void solution_changed (const TVector &newX)
void init_lagging (const TVector &x)
void update_lagging (const TVector &x)
double compute_lagging_error (const TVector &x)
bool lagging_converged (const TVector &x)
const Eigen::MatrixXd & current_rhs ()
virtual bool stop (const TVector &x)
void save_raw (const std::string &x_path, const std::string &v_path, const std::string &a_path) const
double heuristic_max_step (const TVector &dx)
void set_ccd_max_iterations (int v)
void set_project_to_psd (bool val)
bool is_project_to_psd () const
double & lagged_damping_weight ()
void compute_displaced_points (const TVector &full, Eigen::MatrixXd &displaced)
void reduced_to_full_displaced_points (const TVector &reduced, Eigen::MatrixXd &displaced)
double barrier_stiffness () const
const Eigen::MatrixXd & displaced_prev () const
const std::shared_ptr< const time_integrator::ImplicitTimeIntegrator > time_integrator () const
Static Public Member Functions
template<class FullMat , class ReducedMat >
static void full_to_reduced_aux (const State &state, const int full_size, const int reduced_size, const FullMat &full, ReducedMat &reduced)
template<class ReducedMat , class FullMat >
static void reduced_to_full_aux (const State &state, const int full_size, const int reduced_size, const ReducedMat &reduced, const Eigen::MatrixXd &rhs, FullMat &full)
Protected Attributes
const State & state
bool use_adaptive_barrier_stiffness
double _barrier_stiffness
const assembler::RhsAssembler & rhs_assembler
bool is_time_dependent
Private Member Functions
double dt () const
void compute_cached_stiffness ()
void update_barrier_stiffness (const TVector &full)
void update_constraint_set (const Eigen::MatrixXd &displaced_surface)
Private Attributes
const assembler::AssemblerUtils & assembler
Eigen::MatrixXd _current_rhs
StiffnessMatrix cached_stiffness
utils::SpareMatrixCache mat_cache
bool ignore_inertia
const int full_size
const int reduced_size
double t
bool rhs_computed
bool project_to_psd
double _dhat
double _prev_distance
double max_barrier_stiffness_
double _epsv
The boundary between static and dynamic friction.
double _mu
Coefficient of friction.
Eigen::MatrixXd _displaced_prev
Displaced vertices at the start of the time-step.
double _lagged_damping_weight
Weight for lagged damping (static solve).
TVector x_lagged
The full variables from the previous lagging solve.
ipc::BroadPhaseMethod _broad_phase_method
double _ccd_tolerance
int _ccd_max_iterations
ipc::Constraints _constraint_set
ipc::FrictionConstraints _friction_constraint_set
ipc::Candidates _candidates
bool _use_cached_candidates = false
std::shared_ptr< time_integrator::ImplicitTimeIntegrator > _time_integrator
Detailed Description
Definition at line 19 of file NLProblem.hpp.
Member Typedef Documentation
THessian
typedef StiffnessMatrix polyfem::solver::NLProblem::THessian
Definition at line 24 of file NLProblem.hpp.
Constructor & Destructor Documentation
NLProblem()
polyfem::solver::NLProblem::NLProblem (const State & state, const assembler::RhsAssembler & rhs_assembler, const double t, const double dhat, const bool no_reduced = false)
Definition at line 74 of file NLProblem.cpp.
References _barrier_stiffness, _broad_phase_method, _ccd_max_iterations, _ccd_tolerance, _dhat, _epsv, _lagged_damping_weight, _mu, _prev_distance, _time_integrator, polyfem::State::args, assembler, polyfem::time_integrator::ImplicitTimeIntegrator::construct_time_integrator(), polyfem::State::formulation(), polyfem::assembler::AssemblerUtils::is_mixed(), polyfem::utils::is_param_valid(), is_time_dependent, polyfem::logger(), state, and use_adaptive_barrier_stiffness.
Member Function Documentation
barrier_stiffness()
double polyfem::solver::NLProblem::barrier_stiffness () const inline
Definition at line 158 of file NLProblem.hpp.
References _barrier_stiffness.
compute_cached_stiffness()
void polyfem::solver::NLProblem::compute_cached_stiffness () private
Definition at line 504 of file NLProblem.cpp.
References polyfem::State::ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_problem(), assembler, polyfem::State::bases, cached_stiffness, polyfem::State::formulation(), polyfem::State::geom_bases, polyfem::assembler::AssemblerUtils::is_linear(), polyfem::State::iso_parametric(), polyfem::State::mesh, polyfem::State::n_bases, and state.
Referenced by hessian_full().
compute_displaced_points()
void polyfem::solver::NLProblem::compute_displaced_points (const TVector & full, Eigen::MatrixXd & displaced)
Definition at line 270 of file NLProblem.cpp.
References polyfem::State::boundary_nodes_pos, full_size, polyfem::State::mesh, state, and polyfem::utils::unflatten().
Referenced by reduced_to_full_displaced_points(), and polyfem::solver::ALNLProblem::value().
compute_lagging_error()
double polyfem::solver::NLProblem::compute_lagging_error (const TVector & x)
Definition at line 192 of file NLProblem.cpp.
References gradient(), and x.
Referenced by lagging_converged(), polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
current_rhs()
const Eigen::MatrixXd & polyfem::solver::NLProblem::current_rhs ()
Definition at line 235 of file NLProblem.cpp.
References _current_rhs, assembler, polyfem::State::boundary_nodes, polyfem::assembler::RhsAssembler::compute_energy_grad(), polyfem::State::density, polyfem::State::formulation(), full_size, ignore_inertia, polyfem::assembler::AssemblerUtils::is_mixed(), is_time_dependent, polyfem::State::local_boundary, polyfem::State::local_neumann_boundary, polyfem::State::mass, polyfem::State::n_boundary_samples(), polyfem::State::n_pressure_bases, reduced_size, polyfem::State::rhs, rhs_assembler, rhs_computed, polyfem::assembler::RhsAssembler::set_bc(), state, t, and time_integrator().
Referenced by gradient(), and reduced_to_full().
displaced_prev()
const Eigen::MatrixXd & polyfem::solver::NLProblem::displaced_prev () const inline
Definition at line 159 of file NLProblem.hpp.
References _displaced_prev.
dt()
double polyfem::solver::NLProblem::dt () const inline private
Definition at line 197 of file NLProblem.hpp.
References _time_integrator, dt(), and time_integrator().
Referenced by dt(), and init_time_integrator().
full_hessian_to_reduced_hessian()
void polyfem::solver::NLProblem::full_hessian_to_reduced_hessian (const THessian & full, THessian & reduced) const
Definition at line 662 of file NLProblem.cpp.
References polyfem::State::boundary_nodes, entries, full_size, p_bases::indices, POLYFEM_SCOPED_TIMER, reduced_size, and state.
Referenced by hessian().
full_to_reduced()
template<class FullVector > void polyfem::solver::NLProblem::full_to_reduced (const FullVector & full, TVector & reduced) const inline
Definition at line 119 of file NLProblem.hpp.
References full_size, full_to_reduced_aux(), reduced_size, and state.
Referenced by gradient(), polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
full_to_reduced_aux()
template<class FullMat , class ReducedMat > static void polyfem::solver::NLProblem::full_to_reduced_aux (const State & state, const int full_size, const int reduced_size, const FullMat & full, ReducedMat & reduced) inline static
Definition at line 53 of file NLProblem.hpp.
References polyfem::State::boundary_nodes, full_size, reduced_size, and state.
Referenced by full_to_reduced().
gradient() [1/2]
void polyfem::solver::NLProblem::gradient (const TVector & x, TVector & gradv) override virtual
Definition at line 516 of file NLProblem.cpp.
References gradient(), and x.
Referenced by compute_lagging_error(), gradient(), and is_step_valid().
gradient() [2/2]
void polyfem::solver::NLProblem::gradient (const TVector & x, TVector & gradv, const bool only_elastic)
Definition at line 521 of file NLProblem.cpp.
References current_rhs(), full_to_reduced(), gradient_no_rhs(), and x.
gradient_no_rhs()
void polyfem::solver::NLProblem::gradient_no_rhs (const TVector & x, Eigen::MatrixXd & gradv, const bool only_elastic = false) virtual
Reimplemented in polyfem::solver::ALNLProblem.
Definition at line 531 of file NLProblem.cpp.
References polyfem::State::ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_energy_gradient(), assembler, polyfem::State::bases, polyfem::assembler::RhsAssembler::formulation(), polyfem::State::geom_bases, ignore_inertia, is_time_dependent, polyfem::State::iso_parametric(), polyfem::State::mass, polyfem::State::mesh, polyfem::State::n_bases, reduced_to_full(), rhs_assembler, state, time_integrator(), and x.
Referenced by gradient(), and polyfem::solver::ALNLProblem::gradient_no_rhs().
hessian()
void polyfem::solver::NLProblem::hessian (const TVector & x, THessian & hessian) virtual
Definition at line 574 of file NLProblem.cpp.
References full_hessian_to_reduced_hessian(), hessian(), hessian_full(), and x.
Referenced by hessian(), and polyfem::solver::ALNLProblem::hessian_full().
hessian_full()
void polyfem::solver::NLProblem::hessian_full (const TVector & x, THessian & gradv) virtual
Reimplemented in polyfem::solver::ALNLProblem.
Definition at line 581 of file NLProblem.cpp.
References polyfem::State::ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_energy_hessian(), assembler, polyfem::State::bases, cached_stiffness, compute_cached_stiffness(), polyfem::assembler::RhsAssembler::formulation(), full_size, polyfem::State::geom_bases, ignore_inertia, polyfem::assembler::AssemblerUtils::is_linear(), is_time_dependent, polyfem::State::iso_parametric(), polyfem::State::mass, mat_cache, polyfem::State::mesh, polyfem::State::n_bases, POLYFEM_SCOPED_TIMER, project_to_psd, reduced_to_full(), rhs_assembler, state, time_integrator(), and x.
Referenced by hessian(), and polyfem::solver::ALNLProblem::hessian_full().
heuristic_max_step()
double polyfem::solver::NLProblem::heuristic_max_step (const TVector & dx)
Definition at line 726 of file NLProblem.cpp.
init()
void polyfem::solver::NLProblem::init (const TVector & displacement)
Definition at line 113 of file NLProblem.cpp.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
init_lagging()
void polyfem::solver::NLProblem::init_lagging (const TVector & x)
Definition at line 167 of file NLProblem.cpp.
References _displaced_prev, reduced_to_full_displaced_points(), update_lagging(), and x.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
init_time_integrator()
void polyfem::solver::NLProblem::init_time_integrator (const TVector & x_prev, const TVector & v_prev, const TVector & a_prev, const double dt)
Definition at line 160 of file NLProblem.cpp.
References _time_integrator, and dt().
Referenced by polyfem::State::solve_transient_tensor_non_linear_init().
initial_guess()
TVector polyfem::solver::NLProblem::initial_guess ()
is_intersection_free()
bool polyfem::solver::NLProblem::is_intersection_free (const TVector & x)
Definition at line 421 of file NLProblem.cpp.
is_project_to_psd()
bool polyfem::solver::NLProblem::is_project_to_psd () const inline
Definition at line 151 of file NLProblem.hpp.
References project_to_psd.
is_step_collision_free()
bool polyfem::solver::NLProblem::is_step_collision_free (const TVector & x0, const TVector & x1)
Definition at line 381 of file NLProblem.cpp.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
is_step_valid()
bool polyfem::solver::NLProblem::is_step_valid (const TVector & x0, const TVector & x1)
Definition at line 432 of file NLProblem.cpp.
References gradient(), and reduced_size.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
lagged_damping_weight()
double & polyfem::solver::NLProblem::lagged_damping_weight () inline
Definition at line 153 of file NLProblem.hpp.
References _lagged_damping_weight.
Referenced by polyfem::State::solve_non_linear().
lagging_converged()
bool polyfem::solver::NLProblem::lagging_converged (const TVector & x)
Definition at line 201 of file NLProblem.cpp.
References polyfem::State::args, compute_lagging_error(), polyfem::logger(), state, and x.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
line_search_begin()
void polyfem::solver::NLProblem::line_search_begin (const TVector & x0, const TVector & x1)
Definition at line 303 of file NLProblem.cpp.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
line_search_end()
void polyfem::solver::NLProblem::line_search_end ()
Definition at line 323 of file NLProblem.cpp.
References _candidates, and _use_cached_candidates.
Referenced by polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
max_step_size()
double polyfem::solver::NLProblem::max_step_size (const TVector & x0, const TVector & x1)
Definition at line 329 of file NLProblem.cpp.
post_step()
void polyfem::solver::NLProblem::post_step (const int iter_num, const TVector & x)
Definition at line 745 of file NLProblem.cpp.
reduced_to_full()
template<class FullVector > void polyfem::solver::NLProblem::reduced_to_full (const TVector & reduced, FullVector & full) inline
Definition at line 124 of file NLProblem.hpp.
References current_rhs(), full_size, reduced_size, reduced_to_full_aux(), and state.
Referenced by gradient_no_rhs(), hessian_full(), reduced_to_full_displaced_points(), polyfem::State::solve_non_linear(), polyfem::State::solve_transient_tensor_non_linear_step(), update_lagging(), and value().
reduced_to_full_aux()
template<class ReducedMat , class FullMat > static void polyfem::solver::NLProblem::reduced_to_full_aux (const State & state, const int full_size, const int reduced_size, const ReducedMat & reduced, const Eigen::MatrixXd & rhs, FullMat & full) inline static
Definition at line 84 of file NLProblem.hpp.
References polyfem::State::boundary_nodes, full_size, reduced_size, and state.
Referenced by reduced_to_full().
reduced_to_full_displaced_points()
void polyfem::solver::NLProblem::reduced_to_full_displaced_points (const TVector & reduced, Eigen::MatrixXd & displaced)
Definition at line 276 of file NLProblem.cpp.
References compute_displaced_points(), and reduced_to_full().
Referenced by init_lagging(), and update_lagging().
save_raw()
void polyfem::solver::NLProblem::save_raw (const std::string & x_path, const std::string & v_path, const std::string & a_path) const
Definition at line 790 of file NLProblem.cpp.
References time_integrator().
Referenced by polyfem::State::solve_transient_tensor_non_linear().
set_ccd_max_iterations()
void polyfem::solver::NLProblem::set_ccd_max_iterations (int v) inline
Definition at line 148 of file NLProblem.hpp.
References _ccd_max_iterations.
set_project_to_psd()
void polyfem::solver::NLProblem::set_project_to_psd (bool val) inline
Definition at line 150 of file NLProblem.hpp.
References project_to_psd, and val.
solution_changed()
void polyfem::solver::NLProblem::solution_changed (const TVector & newX)
Definition at line 715 of file NLProblem.cpp.
stop()
virtual bool polyfem::solver::NLProblem::stop (const TVector & x) inline virtual
Reimplemented in polyfem::solver::ALNLProblem.
Definition at line 142 of file NLProblem.hpp.
substepping()
void polyfem::solver::NLProblem::substepping (const double t)
Definition at line 226 of file NLProblem.cpp.
References is_time_dependent, rhs_computed, and t.
time_integrator()
const std::shared_ptr< const time_integrator::ImplicitTimeIntegrator > polyfem::solver::NLProblem::time_integrator () const inline
Definition at line 160 of file NLProblem.hpp.
References _time_integrator.
Referenced by current_rhs(), dt(), gradient_no_rhs(), hessian_full(), save_raw(), and value().
update_barrier_stiffness()
void polyfem::solver::NLProblem::update_barrier_stiffness (const TVector & full) private
Definition at line 126 of file NLProblem.cpp.
References _barrier_stiffness, and full_size.
Referenced by update_quantities().
update_constraint_set()
void polyfem::solver::NLProblem::update_constraint_set (const Eigen::MatrixXd & displaced_surface) private
Definition at line 283 of file NLProblem.cpp.
References _broad_phase_method, _candidates, _constraint_set, _dhat, _use_cached_candidates, polyfem::State::collision_mesh, and state.
Referenced by update_lagging().
update_lagging()
void polyfem::solver::NLProblem::update_lagging (const TVector & x)
Definition at line 173 of file NLProblem.cpp.
References _barrier_stiffness, _constraint_set, _dhat, _friction_constraint_set, _mu, polyfem::State::collision_mesh, reduced_to_full(), reduced_to_full_displaced_points(), state, update_constraint_set(), x, and x_lagged.
Referenced by init_lagging(), polyfem::State::solve_non_linear(), and polyfem::State::solve_transient_tensor_non_linear_step().
update_quantities()
void polyfem::solver::NLProblem::update_quantities (const double t, const TVector & x) virtual
Reimplemented in polyfem::solver::ALNLProblem.
Definition at line 209 of file NLProblem.cpp.
References _time_integrator, ignore_inertia, is_time_dependent, rhs_computed, t, update_barrier_stiffness(), use_adaptive_barrier_stiffness, and x.
Referenced by polyfem::State::solve_transient_tensor_non_linear_step(), and polyfem::solver::ALNLProblem::update_quantities().
value() [1/2]
double polyfem::solver::NLProblem::value (const TVector & x) override virtual
Reimplemented in polyfem::solver::ALNLProblem.
Definition at line 449 of file NLProblem.cpp.
References value(), and x.
Referenced by polyfem::State::solve_non_linear(), polyfem::State::solve_transient_tensor_non_linear_step(), value(), and polyfem::solver::ALNLProblem::value().
value() [2/2]
double polyfem::solver::NLProblem::value (const TVector & x, const bool only_elastic) virtual
Reimplemented in polyfem::solver::ALNLProblem.
Definition at line 454 of file NLProblem.cpp.
References polyfem::State::ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_energy(), assembler, polyfem::State::bases, polyfem::assembler::RhsAssembler::compute_energy(), polyfem::State::density, polyfem::assembler::RhsAssembler::formulation(), polyfem::State::geom_bases, ignore_inertia, is_time_dependent, polyfem::State::iso_parametric(), polyfem::State::local_neumann_boundary, polyfem::State::mass, polyfem::State::mesh, polyfem::State::n_boundary_samples(), reduced_to_full(), rhs_assembler, state, t, time_integrator(), p_bases::tmp, and x.
Member Data Documentation
_barrier_stiffness
double polyfem::solver::NLProblem::_barrier_stiffness protected
Definition at line 165 of file NLProblem.hpp.
Referenced by barrier_stiffness(), NLProblem(), update_barrier_stiffness(), and update_lagging().
_broad_phase_method
ipc::BroadPhaseMethod polyfem::solver::NLProblem::_broad_phase_method private
Definition at line 193 of file NLProblem.hpp.
Referenced by NLProblem(), and update_constraint_set().
_candidates
ipc::Candidates polyfem::solver::NLProblem::_candidates private
Definition at line 210 of file NLProblem.hpp.
Referenced by line_search_end(), and update_constraint_set().
_ccd_max_iterations
int polyfem::solver::NLProblem::_ccd_max_iterations private
Definition at line 195 of file NLProblem.hpp.
Referenced by NLProblem(), and set_ccd_max_iterations().
_ccd_tolerance
double polyfem::solver::NLProblem::_ccd_tolerance private
Definition at line 194 of file NLProblem.hpp.
Referenced by NLProblem().
_constraint_set
ipc::Constraints polyfem::solver::NLProblem::_constraint_set private
Definition at line 208 of file NLProblem.hpp.
Referenced by update_constraint_set(), and update_lagging().
_current_rhs
Eigen::MatrixXd polyfem::solver::NLProblem::_current_rhs private
Definition at line 171 of file NLProblem.hpp.
Referenced by current_rhs().
_dhat
double polyfem::solver::NLProblem::_dhat private
Definition at line 182 of file NLProblem.hpp.
Referenced by NLProblem(), update_constraint_set(), and update_lagging().
_displaced_prev
Eigen::MatrixXd polyfem::solver::NLProblem::_displaced_prev private
Displaced vertices at the start of the time-step.
Definition at line 189 of file NLProblem.hpp.
Referenced by displaced_prev(), and init_lagging().
_epsv
double polyfem::solver::NLProblem::_epsv private
The boundary between static and dynamic friction.
Definition at line 187 of file NLProblem.hpp.
Referenced by NLProblem().
_friction_constraint_set
ipc::FrictionConstraints polyfem::solver::NLProblem::_friction_constraint_set private
Definition at line 209 of file NLProblem.hpp.
Referenced by update_lagging().
_lagged_damping_weight
double polyfem::solver::NLProblem::_lagged_damping_weight private
Weight for lagged damping (static solve).
Definition at line 190 of file NLProblem.hpp.
Referenced by lagged_damping_weight(), and NLProblem().
_mu
double polyfem::solver::NLProblem::_mu private
Coefficient of friction.
Definition at line 188 of file NLProblem.hpp.
Referenced by NLProblem(), and update_lagging().
_prev_distance
double polyfem::solver::NLProblem::_prev_distance private
Definition at line 183 of file NLProblem.hpp.
Referenced by NLProblem().
_time_integrator
std::shared_ptr<time_integrator::ImplicitTimeIntegrator> polyfem::solver::NLProblem::_time_integrator private
Definition at line 213 of file NLProblem.hpp.
Referenced by dt(), init_time_integrator(), NLProblem(), time_integrator(), and update_quantities().
_use_cached_candidates
bool polyfem::solver::NLProblem::_use_cached_candidates = false private
Definition at line 211 of file NLProblem.hpp.
Referenced by line_search_end(), and update_constraint_set().
assembler
const assembler::AssemblerUtils& polyfem::solver::NLProblem::assembler private
Definition at line 170 of file NLProblem.hpp.
Referenced by compute_cached_stiffness(), current_rhs(), gradient_no_rhs(), hessian_full(), NLProblem(), and value().
cached_stiffness
StiffnessMatrix polyfem::solver::NLProblem::cached_stiffness private
Definition at line 172 of file NLProblem.hpp.
Referenced by compute_cached_stiffness(), and hessian_full().
full_size
const int polyfem::solver::NLProblem::full_size private
Definition at line 177 of file NLProblem.hpp.
Referenced by compute_displaced_points(), current_rhs(), full_hessian_to_reduced_hessian(), full_to_reduced(), full_to_reduced_aux(), hessian_full(), reduced_to_full(), reduced_to_full_aux(), and update_barrier_stiffness().
ignore_inertia
bool polyfem::solver::NLProblem::ignore_inertia private
Definition at line 175 of file NLProblem.hpp.
Referenced by current_rhs(), gradient_no_rhs(), hessian_full(), update_quantities(), and value().
is_time_dependent
bool polyfem::solver::NLProblem::is_time_dependent protected
Definition at line 167 of file NLProblem.hpp.
Referenced by current_rhs(), gradient_no_rhs(), hessian_full(), NLProblem(), substepping(), update_quantities(), polyfem::solver::ALNLProblem::update_quantities(), and value().
mat_cache
utils::SpareMatrixCache polyfem::solver::NLProblem::mat_cache private
Definition at line 173 of file NLProblem.hpp.
Referenced by hessian_full().
max_barrier_stiffness_
double polyfem::solver::NLProblem::max_barrier_stiffness_ private
Definition at line 184 of file NLProblem.hpp.
project_to_psd
bool polyfem::solver::NLProblem::project_to_psd private
Definition at line 180 of file NLProblem.hpp.
Referenced by hessian_full(), is_project_to_psd(), and set_project_to_psd().
reduced_size
const int polyfem::solver::NLProblem::reduced_size private
Definition at line 177 of file NLProblem.hpp.
Referenced by current_rhs(), full_hessian_to_reduced_hessian(), full_to_reduced(), full_to_reduced_aux(), is_step_valid(), reduced_to_full(), and reduced_to_full_aux().
rhs_assembler
const assembler::RhsAssembler& polyfem::solver::NLProblem::rhs_assembler protected
Definition at line 166 of file NLProblem.hpp.
Referenced by current_rhs(), gradient_no_rhs(), hessian_full(), polyfem::solver::ALNLProblem::update_target(), and value().
rhs_computed
bool polyfem::solver::NLProblem::rhs_computed private
Definition at line 179 of file NLProblem.hpp.
Referenced by current_rhs(), substepping(), and update_quantities().
state
const State& polyfem::solver::NLProblem::state protected
Definition at line 163 of file NLProblem.hpp.
Referenced by polyfem::solver::ALNLProblem::ALNLProblem(), compute_cached_stiffness(), compute_displaced_points(), current_rhs(), full_hessian_to_reduced_hessian(), full_to_reduced(), full_to_reduced_aux(), gradient_no_rhs(), hessian_full(), lagging_converged(), NLProblem(), reduced_to_full(), reduced_to_full_aux(), update_constraint_set(), update_lagging(), polyfem::solver::ALNLProblem::update_target(), and value().
t
double polyfem::solver::NLProblem::t private
Definition at line 178 of file NLProblem.hpp.
Referenced by polyfem::solver::ALNLProblem::ALNLProblem(), current_rhs(), substepping(), update_quantities(), polyfem::solver::ALNLProblem::update_quantities(), polyfem::solver::ALNLProblem::update_target(), and value().
use_adaptive_barrier_stiffness
bool polyfem::solver::NLProblem::use_adaptive_barrier_stiffness protected
Definition at line 164 of file NLProblem.hpp.
Referenced by NLProblem(), and update_quantities().
x_lagged
TVector polyfem::solver::NLProblem::x_lagged private
The full variables from the previous lagging solve.
Definition at line 191 of file NLProblem.hpp.
Referenced by update_lagging().
The documentation for this class was generated from the following files:
src/polyfem/solver/NLProblem.hpp
src/polyfem/solver/NLProblem.cpp