PolyFEM: polyfem::solver::AMIPSForm Class Reference
polyfem::solver::AMIPSForm Class Reference
#include <AMIPSForm.hpp>
Public Member Functions
AMIPSForm (const VariableToSimulationGroup &variable_to_simulation, const State &state)
virtual std::string name () const override
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine if a step from solution x0 to solution x1 is allowed.
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
virtual void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual void finish ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Private Member Functions
Eigen::VectorXd get_updated_mesh_nodes (const Eigen::VectorXd &x) const
Private Attributes
const State & state_
Eigen::VectorXd X_rest
Eigen::MatrixXi F
std::vector< polyfem::basis::ElementBases > init_geom_bases_
assembler::AssemblyValsCache init_ass_vals_cache_
std::shared_ptr< assembler::Assembler > amips_energy_
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 41 of file AMIPSForm.hpp.
Constructor & Destructor Documentation
AMIPSForm()
polyfem::solver::AMIPSForm::AMIPSForm (const VariableToSimulationGroup & variable_to_simulation, const State & state)
Definition at line 179 of file AMIPSForm.cpp.
References amips_energy_, polyfem::mesh::Mesh3D::compute_cell_jacobian(), polyfem::mesh::Mesh2D::compute_face_jacobian(), F, polyfem::utils::flatten(), polyfem::State::geom_bases(), polyfem::State::get_elements(), polyfem::State::get_vertices(), init_geom_bases_, polyfem::assembler::AssemblerUtils::make_assembler(), polyfem::State::mesh, state_, polyfem::State::units, V, and X_rest.
Member Function Documentation
compute_partial_gradient()
void polyfem::solver::AMIPSForm::compute_partial_gradient (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 265 of file AMIPSForm.cpp.
References amips_energy_, polyfem::solver::VariableToSimulationGroup::apply_parametrization_jacobian(), get_updated_mesh_nodes(), init_ass_vals_cache_, init_geom_bases_, polyfem::solver::AdjointTools::map_node_to_primitive_order(), polyfem::solver::AdjointTools::map_primitive_to_node_order(), polyfem::State::mesh, polyfem::State::n_geom_bases, polyfem::solver::Shape, state_, polyfem::solver::AdjointForm::variable_to_simulations_, polyfem::solver::Form::weight(), x, and X_rest.
get_updated_mesh_nodes()
Eigen::VectorXd polyfem::solver::AMIPSForm::get_updated_mesh_nodes (const Eigen::VectorXd & x) const inline private
Definition at line 53 of file AMIPSForm.hpp.
References polyfem::solver::VariableToSimulationGroup::compute_state_variable(), polyfem::solver::Shape, state_, polyfem::solver::AdjointForm::variable_to_simulations_, x, and X_rest.
Referenced by compute_partial_gradient(), is_step_valid(), and value_unweighted().
is_step_valid()
bool polyfem::solver::AMIPSForm::is_step_valid (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine if a step from solution x0 to solution x1 is allowed.
Parameters
x0 Current solution
x1 Proposed next solution
Returns
True if the step is allowed
Reimplemented from polyfem::solver::Form.
Definition at line 275 of file AMIPSForm.cpp.
References polyfem::adjoint_logger(), F, get_updated_mesh_nodes(), polyfem::State::mesh, name(), state_, polyfem::utils::unflatten(), and polyfem::mesh::V1.
name()
virtual std::string polyfem::solver::AMIPSForm::name () const inline override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 46 of file AMIPSForm.hpp.
Referenced by is_step_valid().
value_unweighted()
double polyfem::solver::AMIPSForm::value_unweighted (const Eigen::VectorXd & x) const override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 258 of file AMIPSForm.cpp.
References amips_energy_, get_updated_mesh_nodes(), init_ass_vals_cache_, init_geom_bases_, polyfem::solver::AdjointTools::map_primitive_to_node_order(), polyfem::State::mesh, state_, x, and X_rest.
Member Data Documentation
amips_energy_
std::shared_ptr<assembler::Assembler> polyfem::solver::AMIPSForm::amips_energy_ private
Definition at line 66 of file AMIPSForm.hpp.
Referenced by AMIPSForm(), compute_partial_gradient(), and value_unweighted().
F
Eigen::MatrixXi polyfem::solver::AMIPSForm::F private
Definition at line 63 of file AMIPSForm.hpp.
Referenced by AMIPSForm(), and is_step_valid().
init_ass_vals_cache_
assembler::AssemblyValsCache polyfem::solver::AMIPSForm::init_ass_vals_cache_ private
Definition at line 65 of file AMIPSForm.hpp.
Referenced by compute_partial_gradient(), and value_unweighted().
init_geom_bases_
std::vector<polyfem::basis::ElementBases> polyfem::solver::AMIPSForm::init_geom_bases_ private
Definition at line 64 of file AMIPSForm.hpp.
Referenced by AMIPSForm(), compute_partial_gradient(), and value_unweighted().
state_
const State& polyfem::solver::AMIPSForm::state_ private
Definition at line 60 of file AMIPSForm.hpp.
Referenced by AMIPSForm(), compute_partial_gradient(), get_updated_mesh_nodes(), is_step_valid(), and value_unweighted().
X_rest
Eigen::VectorXd polyfem::solver::AMIPSForm::X_rest private
Definition at line 62 of file AMIPSForm.hpp.
Referenced by AMIPSForm(), compute_partial_gradient(), get_updated_mesh_nodes(), and value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/AMIPSForm.hpp
src/polyfem/solver/forms/adjoint_forms/AMIPSForm.cpp