PolyFEM: polyfem::assembler::OgdenElasticity Class Reference
polyfem::assembler::OgdenElasticity Class Reference
#include <OgdenElasticity.hpp>
Public Member Functions
OgdenElasticity ()
Eigen::MatrixXd assemble_hessian (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
Eigen::VectorXd assemble_grad (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
double compute_energy (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > compute_rhs (const AutodiffHessianPt &pt) const
int size () const
void set_size (const int size)
void set_stiffness_tensor (int i, int j, const double val)
double stifness_tensor (int i, int j) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
void add_multimaterial (const int index, const json &params)
Private Member Functions
template<typename T >
T compute_energy_aux (const ElementAssemblyValues &vals, const Eigen::MatrixXd &displacement, const QuadratureVector &da) const
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const
Private Attributes
int size_ = 2
Eigen::VectorXd alphas_
Eigen::VectorXd mus_
Eigen::VectorXd Ds_
Detailed Description
Definition at line 19 of file OgdenElasticity.hpp.
Constructor & Destructor Documentation
OgdenElasticity()
polyfem::assembler::OgdenElasticity::OgdenElasticity ()
Definition at line 27 of file OgdenElasticity.cpp.
References alphas_, Ds_, and mus_.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::OgdenElasticity::add_multimaterial (const int index, const json & params)
Definition at line 38 of file OgdenElasticity.cpp.
References alphas_, Ds_, mus_, size_, and p_bases::tmp.
assemble_grad()
Eigen::VectorXd polyfem::assembler::OgdenElasticity::assemble_grad (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const
Definition at line 84 of file OgdenElasticity.cpp.
References da, polyfem::gradient_from_energy(), size(), and vals.
assemble_hessian()
Eigen::MatrixXd polyfem::assembler::OgdenElasticity::assemble_hessian (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const
Definition at line 106 of file OgdenElasticity.cpp.
References da, polyfem::hessian_from_energy(), size(), and vals.
assign_stress_tensor()
void polyfem::assembler::OgdenElasticity::assign_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const int all_size, Eigen::MatrixXd & all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> & fun) const private
Definition at line 143 of file OgdenElasticity.cpp.
References size(), and vals.
Referenced by compute_stress_tensor(), and compute_von_mises_stresses().
compute_energy()
double polyfem::assembler::OgdenElasticity::compute_energy (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const
Definition at line 196 of file OgdenElasticity.cpp.
References da, and vals.
compute_energy_aux()
template<typename T > T polyfem::assembler::OgdenElasticity::compute_energy_aux (const ElementAssemblyValues & vals, const Eigen::MatrixXd & displacement, const QuadratureVector & da) const private
Definition at line 203 of file OgdenElasticity.cpp.
References alphas_, da, elasticity_rhs::def_grad, polyfem::utils::determinant(), Ds_, mus_, p_bases::N, DiffScalarBase::setVariableCount(), size(), p_bases::tmp, val, and vals.
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::OgdenElasticity::compute_rhs (const AutodiffHessianPt & pt) const
Definition at line 68 of file OgdenElasticity.cpp.
References size().
compute_stress_tensor()
void polyfem::assembler::OgdenElasticity::compute_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, Eigen::MatrixXd & tensor) const
Definition at line 125 of file OgdenElasticity.cpp.
References assign_stress_tensor(), size(), and p_bases::tmp.
compute_von_mises_stresses()
void polyfem::assembler::OgdenElasticity::compute_von_mises_stresses (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, Eigen::MatrixXd & stresses) const
Definition at line 134 of file OgdenElasticity.cpp.
References assign_stress_tensor(), and polyfem::von_mises_stress_for_stress_tensor().
set_size()
void polyfem::assembler::OgdenElasticity::set_size (const int size)
Definition at line 62 of file OgdenElasticity.cpp.
References size(), and size_.
set_stiffness_tensor()
void polyfem::assembler::OgdenElasticity::set_stiffness_tensor (int i, int j, const double val)
size()
int polyfem::assembler::OgdenElasticity::size () const inline
Definition at line 31 of file OgdenElasticity.hpp.
References size_.
Referenced by assemble_grad(), assemble_hessian(), assign_stress_tensor(), compute_energy_aux(), compute_rhs(), compute_stress_tensor(), and set_size().
stifness_tensor()
double polyfem::assembler::OgdenElasticity::stifness_tensor (int i, int j) const
Member Data Documentation
alphas_
Eigen::VectorXd polyfem::assembler::OgdenElasticity::alphas_ private
Definition at line 45 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), compute_energy_aux(), and OgdenElasticity().
Ds_
Eigen::VectorXd polyfem::assembler::OgdenElasticity::Ds_ private
Definition at line 47 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), compute_energy_aux(), and OgdenElasticity().
mus_
Eigen::VectorXd polyfem::assembler::OgdenElasticity::mus_ private
Definition at line 46 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), compute_energy_aux(), and OgdenElasticity().
size_
int polyfem::assembler::OgdenElasticity::size_ = 2 private
Definition at line 43 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), set_size(), and size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/OgdenElasticity.hpp
src/polyfem/assembler/OgdenElasticity.cpp