PolyFEM: polyfem::basis::QuadraticBSpline Class Reference
polyfem::basis::QuadraticBSpline Class Reference
#include <QuadraticBSpline.hpp>
Public Member Functions
QuadraticBSpline ()
QuadraticBSpline (const std::array< double, 4 > &knots)
void init (const std::array< double, 4 > &knots)
void interpolate (const Eigen::MatrixXd &ts, Eigen::MatrixXd &result) const
double interpolate (const double t) const
void derivative (const Eigen::MatrixXd &ts, Eigen::MatrixXd &result) const
double derivative (const double t) const
Private Attributes
std::array< double, 4 > knots_
Detailed Description
Definition at line 11 of file QuadraticBSpline.hpp.
Constructor & Destructor Documentation
QuadraticBSpline() [1/2]
polyfem::basis::QuadraticBSpline::QuadraticBSpline () inline
Definition at line 14 of file QuadraticBSpline.hpp.
QuadraticBSpline() [2/2]
polyfem::basis::QuadraticBSpline::QuadraticBSpline (const std::array< double, 4 > & knots) inline
Definition at line 15 of file QuadraticBSpline.hpp.
Member Function Documentation
derivative() [1/2]
double polyfem::basis::QuadraticBSpline::derivative (const double t) const
Definition at line 51 of file QuadraticBSpline.cpp.
References knots_.
derivative() [2/2]
void polyfem::basis::QuadraticBSpline::derivative (const Eigen::MatrixXd & ts, Eigen::MatrixXd & result) const
Definition at line 43 of file QuadraticBSpline.cpp.
References derivative().
Referenced by derivative(), polyfem::basis::QuadraticBSpline2d::derivative(), and polyfem::basis::QuadraticBSpline3d::derivative().
init()
void polyfem::basis::QuadraticBSpline::init (const std::array< double, 4 > & knots)
Definition at line 9 of file QuadraticBSpline.cpp.
References knots_.
Referenced by polyfem::basis::QuadraticBSpline2d::init(), and polyfem::basis::QuadraticBSpline3d::init().
interpolate() [1/2]
double polyfem::basis::QuadraticBSpline::interpolate (const double t) const
Definition at line 22 of file QuadraticBSpline.cpp.
References knots_.
interpolate() [2/2]
void polyfem::basis::QuadraticBSpline::interpolate (const Eigen::MatrixXd & ts, Eigen::MatrixXd & result) const
Definition at line 14 of file QuadraticBSpline.cpp.
References interpolate().
Referenced by polyfem::basis::QuadraticBSpline2d::derivative(), polyfem::basis::QuadraticBSpline3d::derivative(), polyfem::basis::QuadraticBSpline2d::interpolate(), polyfem::basis::QuadraticBSpline3d::interpolate(), and interpolate().
Member Data Documentation
knots_
std::array<double, 4> polyfem::basis::QuadraticBSpline::knots_ private
Definition at line 29 of file QuadraticBSpline.hpp.
Referenced by derivative(), init(), and interpolate().
The documentation for this class was generated from the following files:
src/polyfem/basis/function/QuadraticBSpline.hpp
src/polyfem/basis/function/QuadraticBSpline.cpp