PolyFEM: polyfem::assembler::MacroStrainValue Class Reference
polyfem::assembler::MacroStrainValue Class Reference
#include <MacroStrain.hpp>
Public Member Functions
MacroStrainValue ()=default
bool is_active () const
int dim () const
const Eigen::VectorXi & get_fixed_entry () const
void init (const int dim, const json &param)
Eigen::MatrixXd eval (const double t) const
double eval (const int i, const int j, const double t) const
Private Attributes
bool _is_active = false
int _dim
Eigen::VectorXi fixed_entry
std::array< utils::ExpressionValue, 9 > value
Detailed Description
Definition at line 11 of file MacroStrain.hpp.
Constructor & Destructor Documentation
MacroStrainValue()
polyfem::assembler::MacroStrainValue::MacroStrainValue () default
Member Function Documentation
dim()
int polyfem::assembler::MacroStrainValue::dim () const inline
Definition at line 22 of file MacroStrain.hpp.
References _dim.
Referenced by polyfem::solver::MacroStrainLagrangianForm::compute_error(), polyfem::solver::MacroStrainLagrangianForm::first_derivative_unweighted(), init(), polyfem::solver::MacroStrainLagrangianForm::second_derivative_unweighted(), polyfem::solver::MacroStrainLagrangianForm::update_lagrangian(), and polyfem::solver::MacroStrainLagrangianForm::value_unweighted().
eval() [1/2]
Eigen::MatrixXd polyfem::assembler::MacroStrainValue::eval (const double t) const inline
Definition at line 49 of file MacroStrain.hpp.
References _dim, and eval().
Referenced by eval(), polyfem::solver::NLHomoProblem::macro_reduced_to_full(), polyfem::State::solve_homogenization_step(), and polyfem::solver::MacroStrainLagrangianForm::update_quantities().
eval() [2/2]
double polyfem::assembler::MacroStrainValue::eval (const int i, const int j, const double t) const inline
Definition at line 59 of file MacroStrain.hpp.
References value.
get_fixed_entry()
const Eigen::VectorXi & polyfem::assembler::MacroStrainValue::get_fixed_entry () const inline
Definition at line 23 of file MacroStrain.hpp.
References fixed_entry.
Referenced by polyfem::solver::MacroStrainLagrangianForm::compute_error(), polyfem::solver::MacroStrainLagrangianForm::first_derivative_unweighted(), polyfem::State::init_homogenization_solve(), polyfem::solver::MacroStrainLagrangianForm::MacroStrainLagrangianForm(), polyfem::solver::MacroStrainLagrangianForm::second_derivative_unweighted(), polyfem::State::solve_homogenization_step(), polyfem::solver::MacroStrainLagrangianForm::update_lagrangian(), polyfem::solver::MacroStrainLagrangianForm::update_quantities(), and polyfem::solver::MacroStrainLagrangianForm::value_unweighted().
init()
void polyfem::assembler::MacroStrainValue::init (const int dim, const json & param) inline
Definition at line 25 of file MacroStrain.hpp.
References _dim, _is_active, dim(), fixed_entry, polyfem::utils::is_param_valid(), and value.
Referenced by polyfem::State::build_basis().
is_active()
bool polyfem::assembler::MacroStrainValue::is_active () const inline
Definition at line 21 of file MacroStrain.hpp.
References _is_active.
Referenced by polyfem::solver::SolveData::init_forms().
Member Data Documentation
_dim
int polyfem::assembler::MacroStrainValue::_dim private
Definition at line 14 of file MacroStrain.hpp.
Referenced by dim(), eval(), and init().
_is_active
bool polyfem::assembler::MacroStrainValue::_is_active = false private
Definition at line 13 of file MacroStrain.hpp.
Referenced by init(), and is_active().
fixed_entry
Eigen::VectorXi polyfem::assembler::MacroStrainValue::fixed_entry private
Definition at line 15 of file MacroStrain.hpp.
Referenced by get_fixed_entry(), and init().
value
std::array<utils::ExpressionValue, 9> polyfem::assembler::MacroStrainValue::value private
Definition at line 16 of file MacroStrain.hpp.
Referenced by eval(), and init().
The documentation for this class was generated from the following file:
src/polyfem/assembler/MacroStrain.hpp