PolyFEM: polyfem::solver::WeightedVolumeForm Class Reference
polyfem::solver::WeightedVolumeForm Class Reference
#include <WeightedVolumeForm.hpp>
Public Member Functions
WeightedVolumeForm (const CompositeParametrization &parametrizations, const State &state)
double value_unweighted_with_param (const Eigen::VectorXd &x) const override
void first_derivative_unweighted_with_param (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Public Member Functions inherited from polyfem::solver::ParametrizationForm
ParametrizationForm (const CompositeParametrization &parametrizations)
virtual ~ParametrizationForm ()
virtual void init (const Eigen::VectorXd &x) final override
Initialize the form.
virtual double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const final override
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const final
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) final override
Initialize variables used during the line search.
virtual void line_search_end () final override
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x) final override
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x) final override
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) final override
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const final override
Checks if the step is collision free.
virtual Eigen::MatrixXd compute_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const override
virtual void init_with_param (const Eigen::VectorXd &x)
virtual bool is_step_valid_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
virtual double max_step_size_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
virtual void line_search_begin_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
virtual void line_search_end_with_param ()
virtual void post_step_with_param (const int iter_num, const Eigen::VectorXd &x)
virtual void solution_changed_with_param (const Eigen::VectorXd &new_x)
virtual void update_quantities_with_param (const double t, const Eigen::VectorXd &x)
virtual void init_lagging_with_param (const Eigen::VectorXd &x)
virtual void update_lagging_with_param (const Eigen::VectorXd &x, const int iter_num)
virtual void set_apply_DBC_with_param (const Eigen::VectorXd &x, bool apply_DBC)
virtual bool is_step_collision_free_with_param (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
void enable_energy_print (const std::string &print_energy_keyword)
const auto & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const final
virtual void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Private Attributes
const State & state_
Additional Inherited Members
Protected Member Functions inherited from polyfem::solver::ParametrizationForm
virtual void compute_partial_gradient_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes inherited from polyfem::solver::AdjointForm
std::vector< std::shared_ptr< VariableToSimulation > > variable_to_simulations_
int print_energy_ = 0
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 8 of file WeightedVolumeForm.hpp.
Constructor & Destructor Documentation
WeightedVolumeForm()
polyfem::solver::WeightedVolumeForm::WeightedVolumeForm (const CompositeParametrization & parametrizations, const State & state) inline
Definition at line 11 of file WeightedVolumeForm.hpp.
Member Function Documentation
first_derivative_unweighted_with_param()
void polyfem::solver::WeightedVolumeForm::first_derivative_unweighted_with_param (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const inline override virtual
Reimplemented from polyfem::solver::ParametrizationForm.
Definition at line 29 of file WeightedVolumeForm.hpp.
References polyfem::State::ass_vals_cache, polyfem::State::bases, polyfem::assembler::AssemblyValsCache::compute(), polyfem::State::geom_bases(), polyfem::State::mesh, state_, vals, and x.
value_unweighted_with_param()
double polyfem::solver::WeightedVolumeForm::value_unweighted_with_param (const Eigen::VectorXd & x) const inline override virtual
Reimplemented from polyfem::solver::ParametrizationForm.
Definition at line 15 of file WeightedVolumeForm.hpp.
References polyfem::State::ass_vals_cache, polyfem::State::bases, polyfem::assembler::AssemblyValsCache::compute(), polyfem::State::geom_bases(), polyfem::State::mesh, state_, val, vals, and x.
Member Data Documentation
state_
const State& polyfem::solver::WeightedVolumeForm::state_ private
Definition at line 43 of file WeightedVolumeForm.hpp.
Referenced by first_derivative_unweighted_with_param(), and value_unweighted_with_param().
The documentation for this class was generated from the following file:
src/polyfem/solver/forms/adjoint_forms/WeightedVolumeForm.hpp