PolyFEM: polyfem::io::Evaluator Class Reference
polyfem::io::Evaluator Class Reference
#include <Evaluator.hpp>
Public Member Functions
bool check_scalar_value (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::VectorXi &disc_orders, const std::map< int, Eigen::MatrixXd > &polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > &polys_3d, const assembler::Assembler &assembler, const utils::RefElementSampler &sampler, const Eigen::MatrixXd &fun, const bool use_sampler, const bool boundary_only)
checks if mises are not nan
Static Public Member Functions
static void compute_vertex_values (const mesh::Mesh &mesh, int actual_dim, const std::vector< basis::ElementBases > &bases, const utils::RefElementSampler &sampler, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result)
evaluates the function fun at the vertices on the mesh
static void compute_stress_at_quadrature_points (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::VectorXi &disc_orders, const assembler::Assembler &assembler, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, Eigen::VectorXd &von_mises)
compute von mises stress at quadrature points for the function fun, also compute the interpolated function
static void interpolate_function (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const Eigen::VectorXi &disc_orders, const std::map< int, Eigen::MatrixXd > &polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > &polys_3d, const utils::RefElementSampler &sampler, const int n_points, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, const bool use_sampler, const bool boundary_only)
interpolate the function fun.
static void interpolate_function (const mesh::Mesh &mesh, const int actual_dim, const std::vector< basis::ElementBases > &basis, const Eigen::VectorXi &disc_orders, const std::map< int, Eigen::MatrixXd > &polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > &polys_3d, const utils::RefElementSampler &sampler, const int n_points, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, const bool use_sampler, const bool boundary_only)
interpolate the function fun.
static void interpolate_at_local_vals (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const int el_index, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, Eigen::MatrixXd &result_grad)
interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
static void interpolate_at_local_vals (const mesh::Mesh &mesh, const int actual_dim, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const int el_index, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, Eigen::MatrixXd &result_grad)
interpolate the function fun and its gradient at in element el_index for the local_pts in the reference element using bases bases interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
static void interpolate_at_local_vals (const int el_index, const int dim, const int actual_dim, const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, Eigen::MatrixXd &result_grad)
static void compute_scalar_value (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::VectorXi &disc_orders, const std::map< int, Eigen::MatrixXd > &polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > &polys_3d, const assembler::Assembler &assembler, const utils::RefElementSampler &sampler, const int n_points, const Eigen::MatrixXd &fun, std::vector< assembler::Assembler::NamedMatrix > &result, const bool use_sampler, const bool boundary_only)
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid)
static void average_grad_based_function (const mesh::Mesh &mesh, const bool is_problem_scalar, const int n_bases, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::VectorXi &disc_orders, const std::map< int, Eigen::MatrixXd > &polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > &polys_3d, const assembler::Assembler &assembler, const utils::RefElementSampler &sampler, const int n_points, const Eigen::MatrixXd &fun, std::vector< assembler::Assembler::NamedMatrix > &result_scalar, std::vector< assembler::Assembler::NamedMatrix > &result_tensor, const bool use_sampler, const bool boundary_only)
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid) the scalar value is averaged around every node to make it continuos
static void compute_tensor_value (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::VectorXi &disc_orders, const std::map< int, Eigen::MatrixXd > &polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > &polys_3d, const assembler::Assembler &assembler, const utils::RefElementSampler &sampler, const int n_points, const Eigen::MatrixXd &fun, std::vector< assembler::Assembler::NamedMatrix > &result, const bool use_sampler, const bool boundary_only)
compute tensor quantity (ie stress tensor or velocy)
static void interpolate_boundary_function (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::MatrixXd &pts, const Eigen::MatrixXi &faces, const Eigen::MatrixXd &fun, const bool compute_avg, Eigen::MatrixXd &result)
computes integrated solution (fun) per surface face.
static void interpolate_boundary_function_at_vertices (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const Eigen::MatrixXd &pts, const Eigen::MatrixXi &faces, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result)
computes integrated solution (fun) per surface face vertex.
static void interpolate_boundary_tensor_function (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const assembler::Assembler &assembler, const Eigen::MatrixXd &pts, const Eigen::MatrixXi &faces, const Eigen::MatrixXd &fun, const Eigen::MatrixXd &disp, const bool compute_avg, Eigen::MatrixXd &result, Eigen::MatrixXd &stresses, Eigen::MatrixXd &mises, bool skip_orientation=false)
computes traction forces for fun (tensor * surface normal) result, stress tensor, and von mises, per surface face.
static void interpolate_boundary_tensor_function (const mesh::Mesh &mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const assembler::Assembler &assembler, const Eigen::MatrixXd &pts, const Eigen::MatrixXi &faces, const Eigen::MatrixXd &fun, const bool compute_avg, Eigen::MatrixXd &result, Eigen::MatrixXd &stresses, Eigen::MatrixXd &mises, const bool skip_orientation=false)
same as interpolate_boundary_tensor_function with disp=0
static void get_sidesets (const mesh::Mesh &mesh, Eigen::MatrixXd &pts, Eigen::MatrixXi &faces, Eigen::MatrixXd &sidesets)
returns a triangulated representation of the sideset.
static Eigen::MatrixXd generate_linear_field (const int n_bases, const std::shared_ptr< mesh::MeshNodes > mesh_nodes, const Eigen::MatrixXd &grad)
static Eigen::MatrixXd get_bases_position (const int n_bases, const std::shared_ptr< mesh::MeshNodes > mesh_nodes)
Private Member Functions
Evaluator ()
Detailed Description
Definition at line 14 of file Evaluator.hpp.
Constructor & Destructor Documentation
Evaluator()
polyfem::io::Evaluator::Evaluator () inline private
Definition at line 17 of file Evaluator.hpp.
Member Function Documentation
average_grad_based_function()
void polyfem::io::Evaluator::average_grad_based_function (const mesh::Mesh & mesh, const bool is_problem_scalar, const int n_bases, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::VectorXi & disc_orders, const std::map< int, Eigen::MatrixXd > & polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > & polys_3d, const assembler::Assembler & assembler, const utils::RefElementSampler & sampler, const int n_points, const Eigen::MatrixXd & fun, std::vector< assembler::Assembler::NamedMatrix > & result_scalar, std::vector< assembler::Assembler::NamedMatrix > & result_tensor, const bool use_sampler, const bool boundary_only) static
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid) the scalar value is averaged around every node to make it continuos
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] n_bases number of bases
[in] bases bases
[in] gbases geom bases
[in] disc_orders discretization orders
[in] polys polygons
[in] polys_3d polyhedra
[in] assembler assembler
[in] sampler sampler for the local element
[in] n_points is the size of the output.
[in] fun function to used
[out] result_scalar scalar value
[out] result_tensor tensor value
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 557 of file Evaluator.cpp.
References polyfem::basis::ElementBases::bases, polyfem::assembler::Assembler::compute_scalar_value(), polyfem::mesh::Mesh::dimension(), polyfem::basis::Basis::global(), interpolate_function(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::logger(), polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), vals, and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::io::OutGeometryData::save_volume().
check_scalar_value()
bool polyfem::io::Evaluator::check_scalar_value (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::VectorXi & disc_orders, const std::map< int, Eigen::MatrixXd > & polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > & polys_3d, const assembler::Assembler & assembler, const utils::RefElementSampler & sampler, const Eigen::MatrixXd & fun, const bool use_sampler, const bool boundary_only)
checks if mises are not nan
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] disc_orders discretization orders
[in] polys polygons
[in] polys_3d polyhedra
[in] assembler assembler
[in] sampler sampler for the local element
[in] fun function to used
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Returns
if mises are nan
Definition at line 1079 of file Evaluator.cpp.
References polyfem::assembler::Assembler::compute_scalar_value(), polyfem::utils::RefElementSampler::cube_points(), polyfem::mesh::Mesh::is_boundary_element(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), polyfem::utils::RefElementSampler::sample_polygon(), polyfem::utils::RefElementSampler::sample_polyhedron(), and polyfem::utils::RefElementSampler::simplex_points().
compute_scalar_value()
void polyfem::io::Evaluator::compute_scalar_value (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::VectorXi & disc_orders, const std::map< int, Eigen::MatrixXd > & polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > & polys_3d, const assembler::Assembler & assembler, const utils::RefElementSampler & sampler, const int n_points, const Eigen::MatrixXd & fun, std::vector< assembler::Assembler::NamedMatrix > & result, const bool use_sampler, const bool boundary_only) static
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid)
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] disc_orders discretization orders
[in] polys polygons
[in] polys_3d polyhedra
[in] assembler assembler
[in] sampler sampler for the local element
[in] n_points is the size of the output.
[in] fun function to used
[out] result scalar value
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 1160 of file Evaluator.cpp.
References polyfem::assembler::Assembler::compute_scalar_value(), polyfem::utils::RefElementSampler::cube_points(), polyfem::mesh::Mesh::is_boundary_element(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), polyfem::utils::RefElementSampler::sample_polygon(), polyfem::utils::RefElementSampler::sample_polyhedron(), and polyfem::utils::RefElementSampler::simplex_points().
Referenced by polyfem::io::OutGeometryData::save_volume(), and polyfem::io::OutGeometryData::save_wire().
compute_stress_at_quadrature_points()
void polyfem::io::Evaluator::compute_stress_at_quadrature_points (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::VectorXi & disc_orders, const assembler::Assembler & assembler, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, Eigen::VectorXd & von_mises) static
compute von mises stress at quadrature points for the function fun, also compute the interpolated function
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] disc_orders discretization orders
[in] assembler assembler
[in] fun function to use
[out] result output displacement
[out] von_mises output von mises
Definition at line 771 of file Evaluator.cpp.
References polyfem::assembler::Assembler::compute_scalar_value(), polyfem::assembler::Assembler::compute_tensor_value(), polyfem::mesh::Mesh::dimension(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::mesh::Mesh::n_elements(), and polyfem::quadrature::Quadrature::points.
Referenced by polyfem::io::OutGeometryData::export_data().
compute_tensor_value()
void polyfem::io::Evaluator::compute_tensor_value (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::VectorXi & disc_orders, const std::map< int, Eigen::MatrixXd > & polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > & polys_3d, const assembler::Assembler & assembler, const utils::RefElementSampler & sampler, const int n_points, const Eigen::MatrixXd & fun, std::vector< assembler::Assembler::NamedMatrix > & result, const bool use_sampler, const bool boundary_only) static
compute tensor quantity (ie stress tensor or velocy)
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] disc_orders discretization orders
[in] polys polygons
[in] polys_3d polyhedra
[in] assembler assembler
[in] sampler sampler for the local element
[in] n_points is the size of the output.
[in] fun function to used
[out] result resulting tensor
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 1257 of file Evaluator.cpp.
References polyfem::assembler::Assembler::compute_tensor_value(), polyfem::utils::RefElementSampler::cube_points(), polyfem::mesh::Mesh::dimension(), polyfem::mesh::Mesh::is_boundary_element(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), polyfem::utils::RefElementSampler::sample_polygon(), polyfem::utils::RefElementSampler::sample_polyhedron(), and polyfem::utils::RefElementSampler::simplex_points().
Referenced by polyfem::io::OutGeometryData::save_volume().
compute_vertex_values()
void polyfem::io::Evaluator::compute_vertex_values (const mesh::Mesh & mesh, int actual_dim, const std::vector< basis::ElementBases > & bases, const utils::RefElementSampler & sampler, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result) static
evaluates the function fun at the vertices on the mesh
Parameters
[in] mesh mesh
[in] actual_dim is the size of the problem (e.g., 1 for Laplace, dim for elasticity)
[in] basis basis function
[in] sampler sampler for the local element
[in] fun function to interpolate
[out] result output
Definition at line 687 of file Evaluator.cpp.
References polyfem::basis::ElementBases::bases, polyfem::utils::RefElementSampler::cube_corners(), polyfem::basis::ElementBases::evaluate_bases(), polyfem::mesh::Mesh3D::get_ordered_vertices_from_hex(), polyfem::mesh::Mesh3D::get_ordered_vertices_from_tet(), polyfem::basis::Basis::global(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::mesh::Mesh::n_vertices(), and polyfem::utils::RefElementSampler::simplex_corners().
generate_linear_field()
Eigen::MatrixXd polyfem::io::Evaluator::generate_linear_field (const int n_bases, const std::shared_ptr< mesh::MeshNodes > mesh_nodes, const Eigen::MatrixXd & grad) static
Definition at line 1368 of file Evaluator.cpp.
References polyfem::utils::flatten(), and get_bases_position().
get_bases_position()
Eigen::MatrixXd polyfem::io::Evaluator::get_bases_position (const int n_bases, const std::shared_ptr< mesh::MeshNodes > mesh_nodes) static
Definition at line 1355 of file Evaluator.cpp.
Referenced by generate_linear_field().
get_sidesets()
void polyfem::io::Evaluator::get_sidesets (const mesh::Mesh & mesh, Eigen::MatrixXd & pts, Eigen::MatrixXi & faces, Eigen::MatrixXd & sidesets) static
returns a triangulated representation of the sideset.
sidesets contains integers mapping to faces
Parameters
[in] mesh mesh
[out] pts boundary points
[out] faces boundary faces
[out] sidesets resulting sidesets
Definition at line 56 of file Evaluator.cpp.
References polyfem::mesh::Mesh::edge_vertex(), polyfem::mesh::Mesh::face_barycenter(), polyfem::mesh::Mesh::face_vertex(), polyfem::mesh::Mesh::get_boundary_id(), polyfem::mesh::Mesh::is_volume(), polyfem::mesh::Mesh::n_edges(), polyfem::mesh::Mesh::n_face_vertices(), polyfem::mesh::Mesh::n_faces(), and polyfem::mesh::Mesh::point().
interpolate_at_local_vals() [1/3]
void polyfem::io::Evaluator::interpolate_at_local_vals (const int el_index, const int dim, const int actual_dim, const assembler::ElementAssemblyValues & vals, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, Eigen::MatrixXd & result_grad) static
Definition at line 1046 of file Evaluator.cpp.
References polyfem::logger(), val, and vals.
interpolate_at_local_vals() [2/3]
void polyfem::io::Evaluator::interpolate_at_local_vals (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const int el_index, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, Eigen::MatrixXd & result_grad) static
interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] el_index element index
[in] local_pts points in the reference element
[in] fun function to use
[out] result output
[out] result_grad output gradients
Definition at line 979 of file Evaluator.cpp.
References polyfem::mesh::Mesh::dimension(), and interpolate_at_local_vals().
Referenced by polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term(), polyfem::solver::ComplianceForm::compute_partial_gradient_unweighted_step(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), polyfem::solver::AdjointTools::dJ_du_step(), polyfem::solver::ElasticForm::force_material_derivative(), polyfem::solver::InertiaForm::force_shape_derivative(), polyfem::solver::BodyForm::force_shape_derivative(), polyfem::solver::ElasticForm::force_shape_derivative(), polyfem::solver::AccelerationForm::get_integral_functional(), polyfem::solver::KineticForm::get_integral_functional(), polyfem::solver::TargetForm::get_integral_functional(), polyfem::solver::AdjointTools::integrate_objective(), interpolate_at_local_vals(), polyfem::io::OutGeometryData::save_surface(), and polyfem::io::OutGeometryData::save_volume().
interpolate_at_local_vals() [3/3]
void polyfem::io::Evaluator::interpolate_at_local_vals (const mesh::Mesh & mesh, const int actual_dim, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const int el_index, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, Eigen::MatrixXd & result_grad) static
interpolate the function fun and its gradient at in element el_index for the local_pts in the reference element using bases bases interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
Parameters
[in] mesh mesh
[in] actual_dim is the size of the problem (e.g., 1 for Laplace, dim for elasticity)
[in] bases bases
[in] gbases geom bases
[in] el_index element index
[in] local_pts points in the reference element
[in] fun function to used
[out] result output
[out] result_grad output gradients
Definition at line 997 of file Evaluator.cpp.
References polyfem::assembler::ElementAssemblyValues::compute(), polyfem::mesh::Mesh::dimension(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), val, and vals.
interpolate_boundary_function()
void polyfem::io::Evaluator::interpolate_boundary_function (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::MatrixXd & pts, const Eigen::MatrixXi & faces, const Eigen::MatrixXd & fun, const bool compute_avg, Eigen::MatrixXd & result) static
computes integrated solution (fun) per surface face.
pts and faces are the boundary are the boundary on the rest configuration
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[in] compute_avg if compute the average across elements
[out] result resulting value
Definition at line 151 of file Evaluator.cpp.
References polyfem::basis::ElementBases::bases, polyfem::mesh::Mesh3D::cell_face(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::mesh::Mesh::face_barycenter(), polyfem::assembler::AssemblyValues::global, polyfem::mesh::Mesh::is_boundary_face(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::mesh::Mesh3D::n_cell_faces(), polyfem::mesh::Mesh::n_elements(), polyfem::utils::BoundarySampler::quadrature_for_quad_face(), polyfem::utils::BoundarySampler::quadrature_for_tri_face(), polyfem::assembler::AssemblyValues::val, and vals.
interpolate_boundary_function_at_vertices()
void polyfem::io::Evaluator::interpolate_boundary_function_at_vertices (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const Eigen::MatrixXd & pts, const Eigen::MatrixXi & faces, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result) static
computes integrated solution (fun) per surface face vertex.
pts and faces are the boundary are the boundary on the rest configuration
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[out] result resulting value
Definition at line 247 of file Evaluator.cpp.
References polyfem::basis::ElementBases::bases, polyfem::mesh::Mesh3D::cell_face(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::mesh::Mesh::face_barycenter(), polyfem::basis::Basis::global(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::mesh::Mesh3D::n_cell_faces(), polyfem::mesh::Mesh::n_elements(), polyfem::autogen::p_nodes_3d(), polyfem::autogen::q_nodes_3d(), polyfem::assembler::AssemblyValues::val, and vals.
interpolate_boundary_tensor_function() [1/2]
void polyfem::io::Evaluator::interpolate_boundary_tensor_function (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const assembler::Assembler & assembler, const Eigen::MatrixXd & pts, const Eigen::MatrixXi & faces, const Eigen::MatrixXd & fun, const bool compute_avg, Eigen::MatrixXd & result, Eigen::MatrixXd & stresses, Eigen::MatrixXd & mises, const bool skip_orientation = false) static
same as interpolate_boundary_tensor_function with disp=0
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] assembler assembler
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[in] compute_avg if compute the average across elements
[out] result resulting value
[out] stresses resulting stresses
[out] mises resulting mises
[in] skip_orientation skip reorientation of surface
Definition at line 352 of file Evaluator.cpp.
References interpolate_boundary_tensor_function().
interpolate_boundary_tensor_function() [2/2]
void polyfem::io::Evaluator::interpolate_boundary_tensor_function (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const assembler::Assembler & assembler, const Eigen::MatrixXd & pts, const Eigen::MatrixXi & faces, const Eigen::MatrixXd & fun, const Eigen::MatrixXd & disp, const bool compute_avg, Eigen::MatrixXd & result, Eigen::MatrixXd & stresses, Eigen::MatrixXd & mises, bool skip_orientation = false) static
computes traction forces for fun (tensor * surface normal) result, stress tensor, and von mises, per surface face.
pts and faces are the boundary on the rest configuration. disp is the displacement of the surface vertices
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] gbases geom bases
[in] assembler assembler
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[in] disp displacement to deform mesh
[in] compute_avg if compute the average across elements
[out] result resulting value
[out] stresses resulting stresses
[out] mises resulting mises
[in] skip_orientation skip reorientation of surface
Definition at line 374 of file Evaluator.cpp.
References polyfem::mesh::Mesh3D::cell_face(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::assembler::Assembler::compute_scalar_value(), polyfem::assembler::Assembler::compute_tensor_value(), polyfem::mesh::Mesh::face_barycenter(), polyfem::utils::BoundarySampler::hex_local_node_coordinates_from_face(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::mesh::Mesh3D::n_cell_faces(), polyfem::mesh::Mesh::n_elements(), polyfem::utils::BoundarySampler::normal_for_quad_face(), polyfem::utils::BoundarySampler::normal_for_tri_face(), polyfem::utils::BoundarySampler::quadrature_for_quad_face(), polyfem::utils::BoundarySampler::quadrature_for_tri_face(), polyfem::utils::BoundarySampler::tet_local_node_coordinates_from_face(), and vals.
Referenced by interpolate_boundary_tensor_function().
interpolate_function() [1/2]
void polyfem::io::Evaluator::interpolate_function (const mesh::Mesh & mesh, const bool is_problem_scalar, const std::vector< basis::ElementBases > & bases, const Eigen::VectorXi & disc_orders, const std::map< int, Eigen::MatrixXd > & polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > & polys_3d, const utils::RefElementSampler & sampler, const int n_points, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, const bool use_sampler, const bool boundary_only) static
interpolate the function fun.
Parameters
[in] mesh mesh
[in] is_problem_scalar if problem is scalar
[in] bases bases
[in] disc_orders discretization orders
[in] polys polygons
[in] polys_3d polyhedra
[in] sampler sampler for the local element
[in] n_points is the size of the output.
[in] fun function to used
[out] result output
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 867 of file Evaluator.cpp.
References polyfem::mesh::Mesh::dimension(), and interpolate_function().
Referenced by average_grad_based_function(), interpolate_function(), polyfem::io::OutGeometryData::save_volume(), polyfem::io::OutGeometryData::save_volume_vector_field(), and polyfem::io::OutGeometryData::save_wire().
interpolate_function() [2/2]
void polyfem::io::Evaluator::interpolate_function (const mesh::Mesh & mesh, const int actual_dim, const std::vector< basis::ElementBases > & basis, const Eigen::VectorXi & disc_orders, const std::map< int, Eigen::MatrixXd > & polys, const std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > & polys_3d, const utils::RefElementSampler & sampler, const int n_points, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, const bool use_sampler, const bool boundary_only) static
interpolate the function fun.
Parameters
[in] mesh mesh
[in] actual_dim is the size of the problem (e.g., 1 for Laplace, dim for elasticity)
[in] bases bases
[in] disc_orders discretization orders
[in] polys polygons
[in] polys_3d polyhedra
[in] sampler sampler for the local element
[in] n_points is the size of the output.
[in] fun function to used
[out] result output
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 889 of file Evaluator.cpp.
References polyfem::basis::ElementBases::bases, polyfem::utils::RefElementSampler::cube_points(), polyfem::basis::ElementBases::evaluate_bases(), polyfem::basis::Basis::global(), polyfem::mesh::Mesh::is_boundary_element(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), polyfem::utils::RefElementSampler::sample_polygon(), polyfem::utils::RefElementSampler::sample_polyhedron(), and polyfem::utils::RefElementSampler::simplex_points().
The documentation for this class was generated from the following files:
src/polyfem/io/Evaluator.hpp
src/polyfem/io/Evaluator.cpp