PolyFEM: polyfem::mesh::CMesh2D Class Reference
polyfem::mesh::CMesh2D Class Reference
#include <CMesh2D.hpp>
Public Member Functions
CMesh2D ()=default
virtual ~CMesh2D ()=default
CMesh2D (CMesh2D &&)=delete
CMesh2D & operator= (CMesh2D &&)=delete
CMesh2D (const CMesh2D &)=delete
CMesh2D & operator= (const CMesh2D &)=delete
void refine (const int n_refinement, const double t) override
refine the mesh
bool is_conforming () const override
if the mesh is conforming
int n_faces () const override
number of faces
int n_edges () const override
number of edges
int n_vertices () const override
number of vertices
int n_face_vertices (const int f_id) const override
number of vertices of a face
int face_vertex (const int f_id, const int lv_id) const override
id of the face vertex
int edge_vertex (const int e_id, const int lv_id) const override
id of the edge vertex
int cell_vertex (const int f_id, const int lv_id) const override
id of the vertex of a cell
bool is_boundary_vertex (const int vertex_global_id) const override
is vertex boundary
bool is_boundary_edge (const int edge_global_id) const override
is edge boundary
bool is_boundary_element (const int element_global_id) const override
is cell boundary
bool build_from_matrices (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F) override
build a mesh from matrices
void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes) override
attach high order nodes
RowVectorNd edge_node (const Navigation::Index &index, const int n_new_nodes, const int i) const override
RowVectorNd face_node (const Navigation::Index &index, const int n_new_nodes, const int i, const int j) const override
void normalize () override
normalize the mesh
double edge_length (const int gid) const override
edge length
void compute_elements_tag () override
compute element types, see ElementType
virtual void update_elements_tag () override
Update elements types.
void set_point (const int global_index, const RowVectorNd &p) override
virtual RowVectorNd point (const int global_index) const override
point coordinates
virtual RowVectorNd edge_barycenter (const int index) const override
edge barycenter
virtual void bounding_box (RowVectorNd &min, RowVectorNd &max) const override
computes the bbox of the mesh
void compute_boundary_ids (const double eps) override
computes the selection based on the bbx of the mesh.
void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker) override
computes boundary selections based on a function
void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker) override
computes boundary selections based on a function
Navigation::Index get_index_from_face (int f, int lv=0) const override
Navigation::Index switch_vertex (Navigation::Index idx) const override
Navigation::Index switch_edge (Navigation::Index idx) const override
Navigation::Index switch_face (Navigation::Index idx) const override
void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const override
generate a triangular representation of every face
Public Member Functions inherited from polyfem::mesh::Mesh2D
Mesh2D ()=default
virtual ~Mesh2D ()=default
Mesh2D (Mesh2D &&)=default
Mesh2D & operator= (Mesh2D &&)=default
Mesh2D (const Mesh2D &)=default
Mesh2D & operator= (const Mesh2D &)=default
bool is_volume () const override
checks if mesh is volume
int n_cells () const override
number of cells
bool is_boundary_face (const int face_global_id) const override
is face boundary
virtual RowVectorNd edge_node (const Navigation::Index &index, const int n_new_nodes, const int i) const =0
virtual RowVectorNd face_node (const Navigation::Index &index, const int n_new_nodes, const int i, const int j) const =0
virtual void set_point (const int global_index, const RowVectorNd &p)=0
RowVectorNd cell_barycenter (const int index) const override
cell barycenter
virtual Navigation::Index get_index_from_face (int f, int lv=0) const =0
virtual Navigation::Index switch_vertex (Navigation::Index idx) const =0
virtual Navigation::Index switch_edge (Navigation::Index idx) const =0
virtual Navigation::Index switch_face (Navigation::Index idx) const =0
void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const override
constructs barycentric coodiantes for a point p.
RowVectorNd face_barycenter (const int index) const override
face barycenter
void compute_element_barycenters (Eigen::MatrixXd &barycenters) const override
utility for 2d/3d.
void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const override
constructs a box around every element (3d cell, 2d face)
Navigation::Index next_around_face (Navigation::Index idx) const
Navigation::Index next_around_vertex (Navigation::Index idx) const
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const override
Get all the edges.
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const override
Get all the edges according to valid_elements selection.
Public Member Functions inherited from polyfem::mesh::Mesh
virtual ~Mesh ()=default
Destroy the Mesh object.
Mesh (Mesh &&)=default
Construct a new Mesh object.
Mesh & operator= (Mesh &&)=default
Copy constructor.
Mesh (const Mesh &)=default
Construct a new Mesh object.
Mesh & operator= (const Mesh &)=default
virtual void refine (const int n_refinement, const double t)=0
refine the mesh
virtual bool is_volume () const =0
checks if mesh is volume
int dimension () const
utily for dimension
virtual bool is_conforming () const =0
if the mesh is conforming
int n_elements () const
utitlity to return the number of elements, cells or faces in 3d and 2d
virtual int n_cells () const =0
number of cells
virtual int n_faces () const =0
number of faces
virtual int n_edges () const =0
number of edges
virtual int n_vertices () const =0
number of vertices
virtual int n_face_vertices (const int f_id) const =0
number of vertices of a face
virtual int face_vertex (const int f_id, const int lv_id) const =0
id of the face vertex
virtual int edge_vertex (const int e_id, const int lv_id) const =0
id of the edge vertex
virtual int cell_vertex (const int f_id, const int lv_id) const =0
id of the vertex of a cell
virtual bool is_boundary_vertex (const int vertex_global_id) const =0
is vertex boundary
virtual bool is_boundary_edge (const int edge_global_id) const =0
is edge boundary
virtual bool is_boundary_face (const int face_global_id) const =0
is face boundary
virtual bool is_boundary_element (const int element_global_id) const =0
is cell boundary
virtual void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes)=0
attach high order nodes
const Eigen::MatrixXi & orders () const
order of each element
bool is_rational () const
check if curved mesh has rational polynomials elements
void set_is_rational (const bool in_is_rational)
Set the is rational object.
virtual void normalize ()=0
normalize the mesh
virtual void compute_elements_tag ()=0
compute element types, see ElementType
virtual void update_elements_tag ()
Update elements types.
virtual double edge_length (const int gid) const
edge length
virtual double quad_area (const int gid) const
area of a quad face of an hex mesh
virtual double tri_area (const int gid) const
area of a tri face of a tet mesh
virtual RowVectorNd point (const int global_index) const =0
point coordinates
virtual RowVectorNd edge_barycenter (const int e) const =0
edge barycenter
virtual RowVectorNd face_barycenter (const int f) const =0
face barycenter
virtual RowVectorNd cell_barycenter (const int c) const =0
cell barycenter
void edge_barycenters (Eigen::MatrixXd &barycenters) const
all edges barycenters
void face_barycenters (Eigen::MatrixXd &barycenters) const
all face barycenters
void cell_barycenters (Eigen::MatrixXd &barycenters) const
all cells barycenters
virtual void compute_element_barycenters (Eigen::MatrixXd &barycenters) const =0
utility for 2d/3d.
virtual void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const =0
constructs a box around every element (3d cell, 2d face)
virtual void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const =0
constructs barycentric coodiantes for a point p.
virtual void bounding_box (RowVectorNd &min, RowVectorNd &max) const =0
computes the bbox of the mesh
bool is_spline_compatible (const int el_id) const
checks if element is spline compatible
bool is_cube (const int el_id) const
checks if element is cube compatible
bool is_polytope (const int el_id) const
checks if element is polygon compatible
bool is_simplex (const int el_id) const
checks if element is simples compatible
const std::vector< ElementType > & elements_tag () const
Returns the elements types.
void set_tag (const int el, const ElementType type)
changes the element type
virtual void load_boundary_ids (const std::string &path)
loads the boundary selections for a file
virtual void compute_boundary_ids (const double eps)=0
computes the selection based on the bbx of the mesh.
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void set_boundary_ids (const std::vector< int > &boundary_ids)
Set the boundary selection from a vector.
virtual void set_body_ids (const std::vector< int > &body_ids)
Set the volume sections.
virtual void set_body_ids (const Eigen::VectorXi &body_ids)
Set the volume sections.
virtual int get_boundary_id (const int primitive) const
Get the boundary selection of an element (face in 3d, edge in 2d)
virtual int get_body_id (const int primitive) const
Get the volume selection of an element (cell in 3d, face in 2d)
bool has_boundary_ids () const
checks if surface selections are available
virtual bool has_body_ids () const
checks if volumes selections are available
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const =0
Get all the edges.
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const =0
Get all the edges according to valid_elements selection.
virtual void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const =0
generate a triangular representation of every face
const std::vector< double > & cell_weights (const int cell_index) const
weights for rational polynomial meshes
void set_cell_weights (const std::vector< std::vector< double > > &in_cell_weights)
Set the cell weights for rational polynomial meshes.
virtual void prepare_mesh ()
method used to finalize the mesh.
bool has_poly () const
checks if the mesh has polytopes
bool is_linear ()
check if the mesh is linear
std::vector< std::pair< int, int > > edges () const
list of sorted edges.
std::vector< std::vector< int > > faces () const
list of sorted faces.
std::unordered_map< std::pair< int, int >, size_t, polyfem::utils::HashPair > edges_to_ids () const
map from edge (pair of v id) to the id of the edge
std::unordered_map< std::vector< int >, size_t, polyfem::utils::HashVector > faces_to_ids () const
map from face (tuple of v id) to the id of the face
const Eigen::VectorXi & in_ordered_vertices () const
Order of the input vertices.
const Eigen::MatrixXi & in_ordered_edges () const
Order of the input edges.
const Eigen::MatrixXi & in_ordered_faces () const
Order of the input edges.
Protected Member Functions
bool load (const std::string &path) override
loads a mesh from the path
bool load (const GEO::Mesh &mesh) override
loads a mesh from a geo mesh
Protected Member Functions inherited from polyfem::mesh::Mesh
Mesh ()=default
Construct a new Mesh object.
virtual bool load (const std::string &path)=0
loads a mesh from the path
virtual bool load (const GEO::Mesh &M)=0
loads a mesh from a geo mesh
Private Attributes
GEO::Mesh mesh_
std::unique_ptr< GEO::Attribute< GEO::index_t > > c2e_
std::unique_ptr< GEO::Attribute< bool > > boundary_vertices_
std::unique_ptr< GEO::Attribute< bool > > boundary_edges_
Additional Inherited Members
Static Public Member Functions inherited from polyfem::mesh::Mesh
static std::unique_ptr< Mesh > create (const std::string &path, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (GEO::Mesh &M, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (const Eigen::MatrixXd &vertices, const Eigen::MatrixXi &cells, const bool non_conforming=false)
factory to build the proper mesh
Protected Attributes inherited from polyfem::mesh::Mesh
std::vector< ElementType > elements_tag_
list of element types
std::vector< int > boundary_ids_
list of surface labels
std::vector< int > body_ids_
list of volume labels
Eigen::MatrixXi orders_
list of geometry orders, one per cell
bool is_rational_ = false
stores if the mesh is rational
std::vector< EdgeNodes > edge_nodes_
high-oder nodes associates to edges
std::vector< FaceNodes > face_nodes_
high-oder nodes associates to faces
std::vector< CellNodes > cell_nodes_
high-oder nodes associates to cells
std::vector< std::vector< double > > cell_weights_
weights associates to cells for rational polynomail meshes
Eigen::VectorXi in_ordered_vertices_
Order of the input vertices.
Eigen::MatrixXi in_ordered_edges_
Order of the input edges.
Eigen::MatrixXi in_ordered_faces_
Order of the input faces, TODO: change to std::vector of Eigen::Vector.
Detailed Description
Definition at line 17 of file CMesh2D.hpp.
Constructor & Destructor Documentation
CMesh2D() [1/3]
polyfem::mesh::CMesh2D::CMesh2D () default
~CMesh2D()
virtual polyfem::mesh::CMesh2D::~CMesh2D () virtual default
CMesh2D() [2/3]
polyfem::mesh::CMesh2D::CMesh2D (CMesh2D &&) delete
CMesh2D() [3/3]
polyfem::mesh::CMesh2D::CMesh2D (const CMesh2D &) delete
Member Function Documentation
attach_higher_order_nodes()
void polyfem::mesh::CMesh2D::attach_higher_order_nodes (const Eigen::MatrixXd & V, const std::vector< std::vector< int > > & nodes) override virtual
attach high order nodes
Parameters
[in] V nodes
[in] nodes list of nodes per element
Implements polyfem::mesh::Mesh.
Definition at line 169 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::cell_nodes_, polyfem::mesh::Mesh::edge_nodes_, elasticity_rhs::f, polyfem::mesh::Mesh::face_nodes_, get_index_from_face(), mesh_, n_edges(), n_faces(), polyfem::mesh::Mesh2D::next_around_face(), p_bases::nodes, polyfem::mesh::Mesh::orders_, switch_vertex(), and polyfem::mesh::Navigation::Index::vertex.
bounding_box()
void polyfem::mesh::CMesh2D::bounding_box (RowVectorNd & min, RowVectorNd & max) const override virtual
computes the bbox of the mesh
Parameters
[out] min min coodiante
[out] max max coodiante
Implements polyfem::mesh::Mesh.
Definition at line 368 of file CMesh2D.cpp.
Referenced by compute_boundary_ids().
build_from_matrices()
bool polyfem::mesh::CMesh2D::build_from_matrices (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F) override virtual
build a mesh from matrices
Parameters
[in] V vertices
[in] F connectivity
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 145 of file CMesh2D.cpp.
References boundary_edges_, boundary_vertices_, c2e_, polyfem::mesh::Mesh::cell_nodes_, compute_elements_tag(), polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Mesh::face_nodes_, mesh_, polyfem::mesh::orient_normals_2d(), polyfem::mesh::Navigation::prepare_mesh(), and polyfem::mesh::to_geogram_mesh().
cell_vertex()
int polyfem::mesh::CMesh2D::cell_vertex (const int f_id, const int lv_id) const inline override virtual
id of the vertex of a cell
Parameters
[in] f_id global cell id
[in] lv_id local vertex id
Returns
vertex id
Implements polyfem::mesh::Mesh.
Definition at line 41 of file CMesh2D.hpp.
References mesh_.
compute_body_ids()
void polyfem::mesh::CMesh2D::compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id and barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 545 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::body_ids_, polyfem::mesh::Mesh2D::face_barycenter(), and polyfem::mesh::Mesh::n_elements().
compute_boundary_ids() [1/5]
void polyfem::mesh::CMesh2D::compute_boundary_ids (const double eps) override virtual
computes the selection based on the bbx of the mesh.
Left gets 1, bottom 2, right 3, top 4, front 5, back 6
Parameters
[in] eps tolerance for proximity
Implements polyfem::mesh::Mesh.
Definition at line 557 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, bounding_box(), edge_barycenter(), is_boundary_edge(), and n_edges().
compute_boundary_ids() [2/5]
void polyfem::mesh::CMesh2D::compute_boundary_ids (const std::function< int(const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 587 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_barycenter(), is_boundary_edge(), and n_edges().
compute_boundary_ids() [3/5]
void polyfem::mesh::CMesh2D::compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 604 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_barycenter(), is_boundary_edge(), and n_edges().
compute_boundary_ids() [4/5]
void polyfem::mesh::CMesh2D::compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id, barycenter, and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 616 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_barycenter(), is_boundary_edge(), and n_edges().
compute_boundary_ids() [5/5]
void polyfem::mesh::CMesh2D::compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the list of vertices and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 628 of file CMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_vertex(), is_boundary_edge(), and n_edges().
compute_elements_tag()
void polyfem::mesh::CMesh2D::compute_elements_tag () override virtual
compute element types, see ElementType
Implements polyfem::mesh::Mesh.
Definition at line 526 of file CMesh2D.cpp.
References polyfem::mesh::compute_element_tags(), polyfem::mesh::Mesh::elements_tag_, and mesh_.
Referenced by build_from_matrices(), load(), and refine().
edge_barycenter()
RowVectorNd polyfem::mesh::CMesh2D::edge_barycenter (const int e) const override virtual
edge barycenter
Parameters
[in] e global edge index
Returns
edge barycenter
Implements polyfem::mesh::Mesh.
Definition at line 537 of file CMesh2D.cpp.
References mesh_, and point().
Referenced by compute_boundary_ids().
edge_length()
double polyfem::mesh::CMesh2D::edge_length (const int gid) const override virtual
edge length
Parameters
[in] gid global edge id
Returns
edge length
Reimplemented from polyfem::mesh::Mesh.
Definition at line 427 of file CMesh2D.cpp.
References mesh_, and point().
edge_node()
RowVectorNd polyfem::mesh::CMesh2D::edge_node (const Navigation::Index & index, const int n_new_nodes, const int i) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 302 of file CMesh2D.cpp.
References polyfem::mesh::Navigation::Index::edge, polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Mesh::orders_, point(), switch_vertex(), and polyfem::mesh::Navigation::Index::vertex.
edge_vertex()
int polyfem::mesh::CMesh2D::edge_vertex (const int e_id, const int lv_id) const inline override virtual
id of the edge vertex
Parameters
[in] e_id global edge id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 40 of file CMesh2D.hpp.
References mesh_.
Referenced by compute_boundary_ids().
face_node()
RowVectorNd polyfem::mesh::CMesh2D::face_node (const Navigation::Index & index, const int n_new_nodes, const int i, const int j) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 324 of file CMesh2D.cpp.
References polyfem::mesh::Navigation::Index::face, polyfem::mesh::Mesh::face_nodes_, polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), polyfem::mesh::Mesh::orders_, point(), switch_edge(), switch_vertex(), and polyfem::mesh::Navigation::Index::vertex.
face_vertex()
int polyfem::mesh::CMesh2D::face_vertex (const int f_id, const int lv_id) const inline override virtual
id of the face vertex
Parameters
[in] f_id global face id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 39 of file CMesh2D.hpp.
References mesh_.
get_index_from_face()
Navigation::Index polyfem::mesh::CMesh2D::get_index_from_face (int f, int lv = 0) const inline override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 85 of file CMesh2D.hpp.
References c2e_, elasticity_rhs::f, polyfem::mesh::Navigation::get_index_from_face(), and mesh_.
Referenced by attach_higher_order_nodes(), is_boundary_element(), polyfem::utils::BoundarySampler::normal_for_polygon_edge(), polyfem::utils::BoundarySampler::quadrature_for_polygon_edge(), and polyfem::utils::BoundarySampler::sample_polygon_edge().
is_boundary_edge()
bool polyfem::mesh::CMesh2D::is_boundary_edge (const int edge_global_id) const inline override virtual
is edge boundary
Parameters
[in] edge_global_id global edge id
Returns
is edge boundary
Implements polyfem::mesh::Mesh.
Definition at line 48 of file CMesh2D.hpp.
References boundary_edges_.
Referenced by compute_boundary_ids(), and is_boundary_element().
is_boundary_element()
bool polyfem::mesh::CMesh2D::is_boundary_element (const int element_global_id) const override virtual
is cell boundary
Parameters
[in] element_global_id global cell id
Returns
is cell boundary
Implements polyfem::mesh::Mesh.
Definition at line 450 of file CMesh2D.cpp.
References get_index_from_face(), is_boundary_edge(), n_face_vertices(), and polyfem::mesh::Mesh2D::next_around_face().
is_boundary_vertex()
bool polyfem::mesh::CMesh2D::is_boundary_vertex (const int vertex_global_id) const inline override virtual
is vertex boundary
Parameters
[in] vertex_global_id global vertex id
Returns
is vertex boundary
Implements polyfem::mesh::Mesh.
Definition at line 43 of file CMesh2D.hpp.
References boundary_vertices_.
is_conforming()
bool polyfem::mesh::CMesh2D::is_conforming () const inline override virtual
if the mesh is conforming
Returns
if the mesh is conforming
Implements polyfem::mesh::Mesh.
Definition at line 31 of file CMesh2D.hpp.
load() [1/2]
bool polyfem::mesh::CMesh2D::load (const GEO::Mesh & M) override protected virtual
loads a mesh from a geo mesh
Parameters
[in] M geo mesh
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 122 of file CMesh2D.cpp.
References boundary_edges_, boundary_vertices_, c2e_, polyfem::mesh::Mesh::cell_nodes_, compute_elements_tag(), polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Mesh::face_nodes_, mesh_, polyfem::mesh::orient_normals_2d(), and polyfem::mesh::Navigation::prepare_mesh().
load() [2/2]
bool polyfem::mesh::CMesh2D::load (const std::string & path) override protected virtual
loads a mesh from the path
Parameters
[in] path file location
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 76 of file CMesh2D.cpp.
n_edges()
int polyfem::mesh::CMesh2D::n_edges () const inline override virtual
number of edges
Returns
number of edges
Implements polyfem::mesh::Mesh.
Definition at line 34 of file CMesh2D.hpp.
References mesh_.
Referenced by attach_higher_order_nodes(), and compute_boundary_ids().
n_face_vertices()
int polyfem::mesh::CMesh2D::n_face_vertices (const int f_id) const inline override virtual
number of vertices of a face
Parameters
[in] f_id global face id
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 37 of file CMesh2D.hpp.
References mesh_.
Referenced by is_boundary_element(), polyfem::utils::BoundarySampler::normal_for_polygon_edge(), polyfem::utils::BoundarySampler::quadrature_for_polygon_edge(), and polyfem::utils::BoundarySampler::sample_polygon_edge().
n_faces()
int polyfem::mesh::CMesh2D::n_faces () const inline override virtual
number of faces
Returns
number of faces
Implements polyfem::mesh::Mesh.
Definition at line 33 of file CMesh2D.hpp.
References mesh_.
Referenced by attach_higher_order_nodes().
n_vertices()
int polyfem::mesh::CMesh2D::n_vertices () const inline override virtual
number of vertices
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 35 of file CMesh2D.hpp.
References mesh_.
Referenced by triangulate_faces().
normalize()
void polyfem::mesh::CMesh2D::normalize () override virtual
normalize the mesh
Implements polyfem::mesh::Mesh.
Definition at line 382 of file CMesh2D.cpp.
References mesh_.
operator=() [1/2]
CMesh2D & polyfem::mesh::CMesh2D::operator= (CMesh2D &&) delete
operator=() [2/2]
CMesh2D & polyfem::mesh::CMesh2D::operator= (const CMesh2D &) delete
point()
RowVectorNd polyfem::mesh::CMesh2D::point (const int global_index) const override virtual
point coordinates
Parameters
[in] global_index global vertex index
Returns
RowVectorNd
Implements polyfem::mesh::Mesh.
Definition at line 441 of file CMesh2D.cpp.
References mesh_.
Referenced by edge_barycenter(), edge_length(), edge_node(), face_node(), polyfem::utils::BoundarySampler::normal_for_polygon_edge(), polyfem::utils::BoundarySampler::quadrature_for_polygon_edge(), and polyfem::utils::BoundarySampler::sample_polygon_edge().
refine()
void polyfem::mesh::CMesh2D::refine (const int n_refinement, const double t) override virtual
refine the mesh
Parameters
[in] n_refinement number of refinements
[in] t position of the refinement location (0.5 for standard refinement)
Implements polyfem::mesh::Mesh.
Definition at line 26 of file CMesh2D.cpp.
References boundary_edges_, boundary_vertices_, c2e_, polyfem::mesh::Polygons::catmul_clark_split_func(), compute_elements_tag(), polyfem::mesh::Mesh::is_simplex(), mesh_, polyfem::mesh::Mesh::n_elements(), polyfem::mesh::Mesh::orders_, polyfem::mesh::Polygons::polar_split_func(), polyfem::mesh::Navigation::prepare_mesh(), polyfem::mesh::refine_polygonal_mesh(), and polyfem::mesh::refine_triangle_mesh().
set_point()
void polyfem::mesh::CMesh2D::set_point (const int global_index, const RowVectorNd & p) override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 435 of file CMesh2D.cpp.
References mesh_.
switch_edge()
Navigation::Index polyfem::mesh::CMesh2D::switch_edge (Navigation::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 89 of file CMesh2D.hpp.
References c2e_, mesh_, and polyfem::mesh::Navigation::switch_edge().
Referenced by face_node(), polyfem::utils::BoundarySampler::normal_for_polygon_edge(), polyfem::utils::BoundarySampler::quadrature_for_polygon_edge(), and polyfem::utils::BoundarySampler::sample_polygon_edge().
switch_face()
Navigation::Index polyfem::mesh::CMesh2D::switch_face (Navigation::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 90 of file CMesh2D.hpp.
References c2e_, mesh_, and polyfem::mesh::Navigation::switch_face().
switch_vertex()
Navigation::Index polyfem::mesh::CMesh2D::switch_vertex (Navigation::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 88 of file CMesh2D.hpp.
References mesh_, and polyfem::mesh::Navigation::switch_vertex().
Referenced by attach_higher_order_nodes(), edge_node(), and face_node().
triangulate_faces()
void polyfem::mesh::CMesh2D::triangulate_faces (Eigen::MatrixXi & tris, Eigen::MatrixXd & pts, std::vector< int > & ranges) const override virtual
generate a triangular representation of every face
Parameters
[out] tris triangles connectivity
[out] pts triangles vertices
[out] ranges connection to original faces
Implements polyfem::mesh::Mesh.
Definition at line 465 of file CMesh2D.cpp.
References elasticity_rhs::f, mesh_, and n_vertices().
update_elements_tag()
void polyfem::mesh::CMesh2D::update_elements_tag () override virtual
Update elements types.
Reimplemented from polyfem::mesh::Mesh.
Definition at line 532 of file CMesh2D.cpp.
References polyfem::mesh::compute_element_tags(), polyfem::mesh::Mesh::elements_tag_, and mesh_.
Member Data Documentation
boundary_edges_
std::unique_ptr<GEO::Attribute<bool> > polyfem::mesh::CMesh2D::boundary_edges_ private
Definition at line 102 of file CMesh2D.hpp.
Referenced by build_from_matrices(), is_boundary_edge(), load(), and refine().
boundary_vertices_
std::unique_ptr<GEO::Attribute<bool> > polyfem::mesh::CMesh2D::boundary_vertices_ private
Definition at line 101 of file CMesh2D.hpp.
Referenced by build_from_matrices(), is_boundary_vertex(), load(), and refine().
c2e_
std::unique_ptr<GEO::Attribute<GEO::index_t> > polyfem::mesh::CMesh2D::c2e_ private
Definition at line 100 of file CMesh2D.hpp.
Referenced by build_from_matrices(), get_index_from_face(), load(), refine(), switch_edge(), and switch_face().
mesh_
GEO::Mesh polyfem::mesh::CMesh2D::mesh_ private
Definition at line 99 of file CMesh2D.hpp.
Referenced by attach_higher_order_nodes(), build_from_matrices(), cell_vertex(), compute_elements_tag(), edge_barycenter(), edge_length(), edge_vertex(), face_vertex(), get_index_from_face(), load(), n_edges(), n_face_vertices(), n_faces(), n_vertices(), normalize(), point(), refine(), set_point(), switch_edge(), switch_face(), switch_vertex(), triangulate_faces(), and update_elements_tag().
The documentation for this class was generated from the following files:
src/polyfem/mesh/mesh2D/CMesh2D.hpp
src/polyfem/mesh/mesh2D/CMesh2D.cpp