PolyFEM: polyfem::problem::PointBasedTensorProblem Class Reference
polyfem::problem::PointBasedTensorProblem Class Reference
#include <PointBasedProblem.hpp>
Classes
class BCValue
Public Member Functions
PointBasedTensorProblem (const std::string &name)
void rhs (const assembler::AssemblerUtils &assembler, const std::string &formulation, const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const override
bool is_rhs_zero () const override
void dirichlet_bc (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &uv, const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const override
void neumann_bc (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &uv, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &normals, const double t, Eigen::MatrixXd &val) const override
bool has_exact_sol () const override
bool is_scalar () const override
void set_parameters (const json &params) override
void add_constant (const int bc_tag, const Eigen::Vector3d &value)
void add_function (const int bc_tag, const Eigen::MatrixXd &func, const Eigen::MatrixXd &pts, const Eigen::MatrixXi &tri, const int coord)
void add_function (const int bc_tag, const Eigen::MatrixXd &func, const Eigen::MatrixXd &pts, const std::string &rbf, const double eps, const int coord)
void add_constant (const int bc_tag, const Eigen::Vector3d &value, const Eigen::Matrix< bool, 3, 1 > &dd, const bool is_neumann=false)
void add_function (const int bc_tag, const Eigen::MatrixXd &func, const Eigen::MatrixXd &pts, const Eigen::MatrixXi &tri, const int coord, const Eigen::Matrix< bool, 3, 1 > &dd, const bool is_neumann=false)
void add_function (const int bc_tag, const Eigen::MatrixXd &func, const Eigen::MatrixXd &pts, const std::string &rbf, const double eps, const int coord, const Eigen::Matrix< bool, 3, 1 > &dd, const bool is_neumann=false)
bool is_dimension_dirichet (const int tag, const int dim) const override
bool all_dimensions_dirichlet () const override
Public Member Functions inherited from polyfem::assembler::Problem
Problem (const std::string &name)
virtual ~Problem ()
virtual void init (const mesh::Mesh &mesh)
const std::string & name () const
virtual bool is_scalar () const =0
virtual void rhs (const assembler::AssemblerUtils &assembler, const std::string &formulation, const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const =0
virtual bool is_rhs_zero () const =0
virtual void dirichlet_bc (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &uv, const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const =0
virtual void neumann_bc (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &uv, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &normals, const double t, Eigen::MatrixXd &val) const
virtual bool has_exact_sol () const =0
virtual void exact (const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const
virtual void exact_grad (const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const
virtual void clear ()
virtual bool is_time_dependent () const
virtual bool is_constant_in_time () const
virtual void initial_solution (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual void initial_velocity (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual void initial_acceleration (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual void initial_density (const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual void set_parameters (const json &params)
virtual bool might_have_no_dirichlet ()
virtual bool is_dimension_dirichet (const int tag, const int dim) const
virtual bool all_dimensions_dirichlet () const
void setup_bc (const mesh::Mesh &mesh, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &pressure_bases, std::vector< mesh::LocalBoundary > &local_boundary, std::vector< int > &boundary_nodes, std::vector< mesh::LocalBoundary > &local_neumann_boundary, std::vector< int > &pressure_boundary_nodes)
Private Attributes
bool initialized_ = false
bool all_dimensions_dirichlet_ = true
double rhs_
double scaling_
Eigen::Vector3d translation_
std::vector< BCValue > bc_
std::vector< BCValue > neumann_bc_
Additional Inherited Members
Protected Attributes inherited from polyfem::assembler::Problem
std::vector< int > boundary_ids_
std::vector< int > neumann_boundary_ids_
std::vector< int > pressure_boundary_ids_
std::vector< int > splitting_pressure_boundary_ids_
Detailed Description
Definition at line 16 of file PointBasedProblem.hpp.
Constructor & Destructor Documentation
PointBasedTensorProblem()
polyfem::problem::PointBasedTensorProblem::PointBasedTensorProblem (const std::string & name)
Definition at line 109 of file PointBasedProblem.cpp.
References translation_.
Member Function Documentation
add_constant() [1/2]
void polyfem::problem::PointBasedTensorProblem::add_constant (const int bc_tag, const Eigen::Vector3d & value) inline
Definition at line 108 of file PointBasedProblem.hpp.
References add_constant().
Referenced by add_constant().
add_constant() [2/2]
void polyfem::problem::PointBasedTensorProblem::add_constant (const int bc_tag, const Eigen::Vector3d & value, const Eigen::Matrix< bool, 3, 1 > & dd, const bool is_neumann = false)
Definition at line 158 of file PointBasedProblem.cpp.
References all_dimensions_dirichlet_, bc_, polyfem::assembler::Problem::boundary_ids_, neumann_bc_, and polyfem::assembler::Problem::neumann_boundary_ids_.
add_function() [1/4]
void polyfem::problem::PointBasedTensorProblem::add_function (const int bc_tag, const Eigen::MatrixXd & func, const Eigen::MatrixXd & pts, const Eigen::MatrixXi & tri, const int coord) inline
Definition at line 115 of file PointBasedProblem.hpp.
References add_function(), and p_bases::func.
Referenced by add_function().
add_function() [2/4]
void polyfem::problem::PointBasedTensorProblem::add_function (const int bc_tag, const Eigen::MatrixXd & func, const Eigen::MatrixXd & pts, const Eigen::MatrixXi & tri, const int coord, const Eigen::Matrix< bool, 3, 1 > & dd, const bool is_neumann = false)
Definition at line 175 of file PointBasedProblem.cpp.
References all_dimensions_dirichlet_, bc_, polyfem::assembler::Problem::boundary_ids_, p_bases::func, neumann_bc_, and polyfem::assembler::Problem::neumann_boundary_ids_.
add_function() [3/4]
void polyfem::problem::PointBasedTensorProblem::add_function (const int bc_tag, const Eigen::MatrixXd & func, const Eigen::MatrixXd & pts, const std::string & rbf, const double eps, const int coord) inline
Definition at line 122 of file PointBasedProblem.hpp.
References add_function(), and p_bases::func.
add_function() [4/4]
void polyfem::problem::PointBasedTensorProblem::add_function (const int bc_tag, const Eigen::MatrixXd & func, const Eigen::MatrixXd & pts, const std::string & rbf, const double eps, const int coord, const Eigen::Matrix< bool, 3, 1 > & dd, const bool is_neumann = false)
Definition at line 193 of file PointBasedProblem.cpp.
References all_dimensions_dirichlet_, bc_, polyfem::assembler::Problem::boundary_ids_, p_bases::func, neumann_bc_, and polyfem::assembler::Problem::neumann_boundary_ids_.
all_dimensions_dirichlet()
bool polyfem::problem::PointBasedTensorProblem::all_dimensions_dirichlet () const inline override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 134 of file PointBasedProblem.hpp.
References all_dimensions_dirichlet_.
Referenced by polyfem::problem::PointBasedTensorProblem::BCValue::init(), and is_dimension_dirichet().
dirichlet_bc()
void polyfem::problem::PointBasedTensorProblem::dirichlet_bc (const mesh::Mesh & mesh, const Eigen::MatrixXi & global_ids, const Eigen::MatrixXd & uv, const Eigen::MatrixXd & pts, const double t, Eigen::MatrixXd & val) const override virtual
Implements polyfem::assembler::Problem.
Definition at line 120 of file PointBasedProblem.cpp.
References bc_, polyfem::assembler::Problem::boundary_ids_, polyfem::mesh::Mesh::dimension(), polyfem::mesh::Mesh::get_boundary_id(), scaling_, translation_, and val.
has_exact_sol()
bool polyfem::problem::PointBasedTensorProblem::has_exact_sol () const inline override virtual
Implements polyfem::assembler::Problem.
Definition at line 103 of file PointBasedProblem.hpp.
is_dimension_dirichet()
bool polyfem::problem::PointBasedTensorProblem::is_dimension_dirichet (const int tag, const int dim) const override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 217 of file PointBasedProblem.cpp.
References all_dimensions_dirichlet(), bc_, and polyfem::assembler::Problem::boundary_ids_.
is_rhs_zero()
bool polyfem::problem::PointBasedTensorProblem::is_rhs_zero () const inline override virtual
Implements polyfem::assembler::Problem.
Definition at line 98 of file PointBasedProblem.hpp.
References rhs_.
is_scalar()
bool polyfem::problem::PointBasedTensorProblem::is_scalar () const inline override virtual
Implements polyfem::assembler::Problem.
Definition at line 104 of file PointBasedProblem.hpp.
neumann_bc()
void polyfem::problem::PointBasedTensorProblem::neumann_bc (const mesh::Mesh & mesh, const Eigen::MatrixXi & global_ids, const Eigen::MatrixXd & uv, const Eigen::MatrixXd & pts, const Eigen::MatrixXd & normals, const double t, Eigen::MatrixXd & val) const override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 139 of file PointBasedProblem.cpp.
References polyfem::mesh::Mesh::dimension(), polyfem::mesh::Mesh::get_boundary_id(), neumann_bc_, polyfem::assembler::Problem::neumann_boundary_ids_, scaling_, translation_, and val.
rhs()
void polyfem::problem::PointBasedTensorProblem::rhs (const assembler::AssemblerUtils & assembler, const std::string & formulation, const Eigen::MatrixXd & pts, const double t, Eigen::MatrixXd & val) const override virtual
Implements polyfem::assembler::Problem.
Definition at line 115 of file PointBasedProblem.cpp.
References rhs_, and val.
set_parameters()
void polyfem::problem::PointBasedTensorProblem::set_parameters (const json & params) override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 234 of file PointBasedProblem.cpp.
References all_dimensions_dirichlet_, bc_, polyfem::assembler::Problem::boundary_ids_, initialized_, neumann_bc_, polyfem::assembler::Problem::neumann_boundary_ids_, rhs_, scaling_, and translation_.
Member Data Documentation
all_dimensions_dirichlet_
bool polyfem::problem::PointBasedTensorProblem::all_dimensions_dirichlet_ = true private
Definition at line 138 of file PointBasedProblem.hpp.
Referenced by add_constant(), add_function(), all_dimensions_dirichlet(), and set_parameters().
bc_
std::vector<BCValue> polyfem::problem::PointBasedTensorProblem::bc_ private
Definition at line 142 of file PointBasedProblem.hpp.
Referenced by add_constant(), add_function(), dirichlet_bc(), is_dimension_dirichet(), and set_parameters().
initialized_
bool polyfem::problem::PointBasedTensorProblem::initialized_ = false private
Definition at line 137 of file PointBasedProblem.hpp.
Referenced by set_parameters().
neumann_bc_
std::vector<BCValue> polyfem::problem::PointBasedTensorProblem::neumann_bc_ private
Definition at line 143 of file PointBasedProblem.hpp.
Referenced by add_constant(), add_function(), neumann_bc(), and set_parameters().
rhs_
double polyfem::problem::PointBasedTensorProblem::rhs_ private
Definition at line 139 of file PointBasedProblem.hpp.
Referenced by is_rhs_zero(), rhs(), and set_parameters().
scaling_
double polyfem::problem::PointBasedTensorProblem::scaling_ private
Definition at line 140 of file PointBasedProblem.hpp.
Referenced by dirichlet_bc(), neumann_bc(), and set_parameters().
translation_
Eigen::Vector3d polyfem::problem::PointBasedTensorProblem::translation_ private
Definition at line 141 of file PointBasedProblem.hpp.
Referenced by dirichlet_bc(), neumann_bc(), PointBasedTensorProblem(), and set_parameters().
The documentation for this class was generated from the following files:
src/polyfem/problem/PointBasedProblem.hpp
src/polyfem/problem/PointBasedProblem.cpp