PolyFEM: polyfem::solver::CollisionBarrierForm Class Reference
polyfem::solver::CollisionBarrierForm Class Reference
#include <BarrierForms.hpp>
Public Member Functions
CollisionBarrierForm (const VariableToSimulationGroup &variable_to_simulation, const State &state, const double dhat, const double dmin=0)
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
void solution_changed (const Eigen::VectorXd &x) override
Update cached fields upon a change in the solution.
bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Checks if the step is collision free.
std::string name () const override
double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine the maximum step size allowable between the current and next solution.
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) final override
Set if the Dirichlet boundary conditions should be enforced.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
void build_collision_set (const Eigen::MatrixXd &displaced_surface)
Eigen::VectorXd get_updated_mesh_nodes (const Eigen::VectorXd &x) const
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes
const State & state_
Eigen::VectorXd X_init
ipc::CollisionMesh collision_mesh_
ipc::Collisions collision_set
const double dhat_
const double dmin_
ipc::BroadPhaseMethod broad_phase_method_
ipc::BarrierPotential barrier_potential_
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Detailed Description
Definition at line 11 of file BarrierForms.hpp.
Constructor & Destructor Documentation
CollisionBarrierForm()
polyfem::solver::CollisionBarrierForm::CollisionBarrierForm (const VariableToSimulationGroup & variable_to_simulation, const State & state, const double dhat, const double dmin = 0)
Definition at line 41 of file BarrierForms.cpp.
References polyfem::State::args, broad_phase_method_, polyfem::State::build_collision_mesh(), collision_mesh_, polyfem::utils::flatten(), polyfem::State::geom_bases(), polyfem::State::get_vertices(), polyfem::State::in_node_to_node, polyfem::State::mesh, polyfem::State::n_geom_bases, polyfem::State::obstacle, state_, polyfem::State::total_local_boundary, V, and X_init.
Member Function Documentation
build_collision_set()
void polyfem::solver::CollisionBarrierForm::build_collision_set (const Eigen::MatrixXd & displaced_surface) protected
Definition at line 116 of file BarrierForms.cpp.
References broad_phase_method_, collision_mesh_, collision_set, dhat_, and dmin_.
Referenced by solution_changed().
compute_partial_gradient()
void polyfem::solver::CollisionBarrierForm::compute_partial_gradient (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 63 of file BarrierForms.cpp.
References polyfem::solver::VariableToSimulationGroup::apply_parametrization_jacobian(), barrier_potential_, collision_mesh_, collision_set, get_updated_mesh_nodes(), polyfem::solver::AdjointTools::map_node_to_primitive_order(), polyfem::State::mesh, polyfem::solver::Shape, state_, polyfem::utils::unflatten(), polyfem::solver::AdjointForm::variable_to_simulations_, polyfem::solver::Form::weight(), and x.
get_updated_mesh_nodes()
Eigen::VectorXd polyfem::solver::CollisionBarrierForm::get_updated_mesh_nodes (const Eigen::VectorXd & x) const protected
Definition at line 127 of file BarrierForms.cpp.
References polyfem::solver::VariableToSimulationGroup::compute_state_variable(), polyfem::solver::AdjointTools::map_primitive_to_node_order(), polyfem::solver::Shape, state_, polyfem::solver::AdjointForm::variable_to_simulations_, x, and X_init.
Referenced by compute_partial_gradient(), is_step_collision_free(), max_step_size(), solution_changed(), and value_unweighted().
is_step_collision_free()
bool polyfem::solver::CollisionBarrierForm::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented from polyfem::solver::Form.
Definition at line 81 of file BarrierForms.cpp.
References broad_phase_method_, collision_mesh_, get_updated_mesh_nodes(), polyfem::State::mesh, state_, polyfem::utils::unflatten(), polyfem::mesh::V0, and polyfem::mesh::V1.
max_step_size()
double polyfem::solver::CollisionBarrierForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::Form.
Reimplemented in polyfem::solver::LayerThicknessForm.
Definition at line 100 of file BarrierForms.cpp.
References polyfem::adjoint_logger(), broad_phase_method_, collision_mesh_, dmin_, get_updated_mesh_nodes(), polyfem::State::mesh, name(), state_, polyfem::utils::unflatten(), polyfem::mesh::V0, and polyfem::mesh::V1.
name()
std::string polyfem::solver::CollisionBarrierForm::name () const inline override virtual
Reimplemented from polyfem::solver::AdjointForm.
Reimplemented in polyfem::solver::LayerThicknessForm.
Definition at line 24 of file BarrierForms.hpp.
Referenced by max_step_size().
solution_changed()
void polyfem::solver::CollisionBarrierForm::solution_changed (const Eigen::VectorXd & new_x) override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 73 of file BarrierForms.cpp.
References build_collision_set(), collision_mesh_, get_updated_mesh_nodes(), polyfem::State::mesh, polyfem::solver::AdjointForm::solution_changed(), state_, polyfem::utils::unflatten(), and x.
value_unweighted()
double polyfem::solver::CollisionBarrierForm::value_unweighted (const Eigen::VectorXd & x) const override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 57 of file BarrierForms.cpp.
References barrier_potential_, collision_mesh_, collision_set, get_updated_mesh_nodes(), polyfem::State::mesh, state_, polyfem::utils::unflatten(), and x.
Member Data Documentation
barrier_potential_
ipc::BarrierPotential polyfem::solver::CollisionBarrierForm::barrier_potential_ protected
Definition at line 43 of file BarrierForms.hpp.
Referenced by compute_partial_gradient(), polyfem::solver::LayerThicknessForm::LayerThicknessForm(), and value_unweighted().
broad_phase_method_
ipc::BroadPhaseMethod polyfem::solver::CollisionBarrierForm::broad_phase_method_ protected
Definition at line 41 of file BarrierForms.hpp.
Referenced by build_collision_set(), CollisionBarrierForm(), is_step_collision_free(), and max_step_size().
collision_mesh_
ipc::CollisionMesh polyfem::solver::CollisionBarrierForm::collision_mesh_ protected
Definition at line 37 of file BarrierForms.hpp.
Referenced by polyfem::solver::LayerThicknessForm::build_collision_mesh(), build_collision_set(), CollisionBarrierForm(), compute_partial_gradient(), is_step_collision_free(), max_step_size(), solution_changed(), and value_unweighted().
collision_set
ipc::Collisions polyfem::solver::CollisionBarrierForm::collision_set protected
Definition at line 38 of file BarrierForms.hpp.
Referenced by build_collision_set(), compute_partial_gradient(), and value_unweighted().
dhat_
const double polyfem::solver::CollisionBarrierForm::dhat_ protected
Definition at line 39 of file BarrierForms.hpp.
Referenced by build_collision_set().
dmin_
const double polyfem::solver::CollisionBarrierForm::dmin_ protected
Definition at line 40 of file BarrierForms.hpp.
Referenced by build_collision_set(), and max_step_size().
state_
const State& polyfem::solver::CollisionBarrierForm::state_ protected
Definition at line 33 of file BarrierForms.hpp.
Referenced by polyfem::solver::LayerThicknessForm::build_collision_mesh(), CollisionBarrierForm(), compute_partial_gradient(), get_updated_mesh_nodes(), is_step_collision_free(), max_step_size(), solution_changed(), and value_unweighted().
X_init
Eigen::VectorXd polyfem::solver::CollisionBarrierForm::X_init protected
Definition at line 35 of file BarrierForms.hpp.
Referenced by CollisionBarrierForm(), and get_updated_mesh_nodes().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/BarrierForms.hpp
src/polyfem/solver/forms/adjoint_forms/BarrierForms.cpp