PolyFEM: polyfem::Units Class Reference
polyfem::Units Class Reference
#include <Units.hpp>
Public Member Functions
void init (const json &json)
const std::string & length () const
const std::string & mass () const
const std::string & time () const
double characteristic_length () const
double & characteristic_length ()
std::string capacitance () const
std::string permittivity () const
std::string stress () const
std::string density () const
std::string velocity () const
std::string acceleration () const
std::string force () const
std::string pressure () const
std::string energy () const
std::string viscosity () const
Static Public Member Functions
static double convert (const json &val, const std::string &unit_type)
static double convert (const double val, const std::string &unit, const std::string &unit_type)
Private Attributes
std::string length_ = "m"
std::string mass_ = "kg"
std::string time_ = "s"
double characteristic_length_ = 1
std::string coulomb_ = "C"
Detailed Description
Definition at line 11 of file Units.hpp.
Member Function Documentation
acceleration()
std::string polyfem::Units::acceleration () const inline
Definition at line 30 of file Units.hpp.
References length_, and time_.
Referenced by force(), pressure(), and polyfem::assembler::GenericTensorProblem::set_units().
capacitance()
std::string polyfem::Units::capacitance () const inline
Definition at line 24 of file Units.hpp.
References coulomb_, force(), and length_.
Referenced by permittivity().
characteristic_length() [1/2]
double & polyfem::Units::characteristic_length () inline
Definition at line 23 of file Units.hpp.
References characteristic_length_.
characteristic_length() [2/2]
double polyfem::Units::characteristic_length () const inline
Definition at line 22 of file Units.hpp.
References characteristic_length_.
Referenced by polyfem::solver::SolveData::init_forms(), polyfem::State::init_time(), polyfem::State::make_nl_solver(), and polyfem::State::solve_tensor_nonlinear().
convert() [1/2]
double polyfem::Units::convert (const double val, const std::string & unit, const std::string & unit_type) static
Definition at line 41 of file Units.cpp.
References polyfem::log_and_throw_error(), and val.
convert() [2/2]
double polyfem::Units::convert (const json & val, const std::string & unit_type) static
Definition at line 31 of file Units.cpp.
References convert(), and val.
Referenced by polyfem::State::build_basis(), convert(), polyfem::State::init_time(), polyfem::mesh::read_fem_mesh(), and polyfem::mesh::read_obstacle_mesh().
density()
std::string polyfem::Units::density () const inline
Definition at line 28 of file Units.hpp.
References length_, and mass_.
Referenced by polyfem::assembler::Mass::add_multimaterial().
energy()
std::string polyfem::Units::energy () const inline
Definition at line 33 of file Units.hpp.
References length_, mass_, and time_.
force()
std::string polyfem::Units::force () const inline
Definition at line 31 of file Units.hpp.
References acceleration(), and mass_.
Referenced by capacitance(), polyfem::assembler::GenericTensorProblem::set_units(), and viscosity().
init()
void polyfem::Units::init (const json & json)
Definition at line 9 of file Units.cpp.
References characteristic_length_, length_, mass_, and time_.
Referenced by polyfem::State::init().
length()
const std::string & polyfem::Units::length () const inline
Definition at line 19 of file Units.hpp.
References length_.
Referenced by polyfem::State::build_basis(), polyfem::mesh::read_fem_mesh(), polyfem::mesh::read_obstacle_mesh(), polyfem::assembler::GenericTensorProblem::set_units(), and polyfem::mesh::Obstacle::set_units().
mass()
const std::string & polyfem::Units::mass () const inline
Definition at line 20 of file Units.hpp.
References mass_.
permittivity()
std::string polyfem::Units::permittivity () const inline
Definition at line 25 of file Units.hpp.
References capacitance(), and length_.
Referenced by polyfem::assembler::Electrostatics::add_multimaterial().
pressure()
std::string polyfem::Units::pressure () const inline
Definition at line 32 of file Units.hpp.
References acceleration(), length_, and mass_.
Referenced by polyfem::assembler::GenericTensorProblem::set_units().
stress()
std::string polyfem::Units::stress () const inline
Definition at line 27 of file Units.hpp.
References length_, mass_, and time_.
Referenced by polyfem::assembler::FixedCorotational::add_multimaterial(), polyfem::assembler::HookeLinearElasticity::add_multimaterial(), polyfem::assembler::IncompressibleLinearElasticityDispacement::add_multimaterial(), polyfem::assembler::IncompressibleLinearElasticityPressure::add_multimaterial(), polyfem::assembler::LinearElasticity::add_multimaterial(), polyfem::assembler::MooneyRivlin3ParamElasticity::add_multimaterial(), polyfem::assembler::MooneyRivlin3ParamSymbolic::add_multimaterial(), polyfem::assembler::MooneyRivlinElasticity::add_multimaterial(), polyfem::assembler::NeoHookeanElasticity::add_multimaterial(), polyfem::assembler::NeoHookeanAutodiff::add_multimaterial(), polyfem::assembler::UnconstrainedOgdenElasticity::add_multimaterial(), polyfem::assembler::IncompressibleOgdenElasticity::add_multimaterial(), and polyfem::assembler::SaintVenantElasticity::add_multimaterial().
time()
const std::string & polyfem::Units::time () const inline
Definition at line 21 of file Units.hpp.
References time_.
Referenced by polyfem::State::init_time().
velocity()
std::string polyfem::Units::velocity () const inline
Definition at line 29 of file Units.hpp.
References length_, and time_.
Referenced by polyfem::State::build_basis(), and polyfem::assembler::GenericTensorProblem::set_units().
viscosity()
std::string polyfem::Units::viscosity () const inline
Definition at line 34 of file Units.hpp.
References force(), length_, and time_.
Referenced by polyfem::assembler::NavierStokesVelocity::add_multimaterial(), and polyfem::assembler::StokesVelocity::add_multimaterial().
Member Data Documentation
characteristic_length_
double polyfem::Units::characteristic_length_ = 1 private
Definition at line 40 of file Units.hpp.
Referenced by characteristic_length(), characteristic_length(), and init().
coulomb_
std::string polyfem::Units::coulomb_ = "C" private
Definition at line 41 of file Units.hpp.
Referenced by capacitance().
length_
std::string polyfem::Units::length_ = "m" private
Definition at line 37 of file Units.hpp.
Referenced by acceleration(), capacitance(), density(), energy(), init(), length(), permittivity(), pressure(), stress(), velocity(), and viscosity().
mass_
std::string polyfem::Units::mass_ = "kg" private
Definition at line 38 of file Units.hpp.
Referenced by density(), energy(), force(), init(), mass(), pressure(), and stress().
time_
std::string polyfem::Units::time_ = "s" private
Definition at line 39 of file Units.hpp.
Referenced by acceleration(), energy(), init(), stress(), time(), velocity(), and viscosity().
The documentation for this class was generated from the following files:
src/polyfem/Units.hpp
src/polyfem/Units.cpp