PolyFEM: polyfem::solver::CompositeForm Class Reference
polyfem::solver::CompositeForm Class Reference abstract
#include <CompositeForm.hpp>
Public Member Functions
CompositeForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations, const std::vector< std::shared_ptr< AdjointForm > > &forms)
CompositeForm (const std::vector< std::shared_ptr< AdjointForm > > &forms)
virtual ~CompositeForm ()
virtual int n_objs () const final
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const override final
virtual void compute_partial_gradient_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override final
virtual double compose (const Eigen::VectorXd &inputs) const =0
virtual Eigen::VectorXd compose_grad (const Eigen::VectorXd &inputs) const =0
Eigen::VectorXd get_inputs (const Eigen::VectorXd &x) const
virtual double value_unweighted (const Eigen::VectorXd &x) const final override
Compute the value of the form.
virtual void init (const Eigen::VectorXd &x) override
Initialize the form.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) override
Initialize variables used during the line search.
virtual void line_search_end () override
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x) override
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) override
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Checks if the step is collision free.
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
void enable_energy_print (const std::string &print_energy_keyword)
const auto & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const final
virtual void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final
virtual Eigen::MatrixXd compute_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Private Attributes
std::vector< std::shared_ptr< AdjointForm > > forms_
Additional Inherited Members
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes inherited from polyfem::solver::AdjointForm
std::vector< std::shared_ptr< VariableToSimulation > > variable_to_simulations_
int print_energy_ = 0
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 9 of file CompositeForm.hpp.
Constructor & Destructor Documentation
CompositeForm() [1/2]
polyfem::solver::CompositeForm::CompositeForm (const std::vector< std::shared_ptr< VariableToSimulation > > & variable_to_simulations, const std::vector< std::shared_ptr< AdjointForm > > & forms) inline
Definition at line 12 of file CompositeForm.hpp.
CompositeForm() [2/2]
polyfem::solver::CompositeForm::CompositeForm (const std::vector< std::shared_ptr< AdjointForm > > & forms) inline
Definition at line 13 of file CompositeForm.hpp.
~CompositeForm()
virtual polyfem::solver::CompositeForm::~CompositeForm () inline virtual
Definition at line 14 of file CompositeForm.hpp.
Member Function Documentation
compose()
virtual double polyfem::solver::CompositeForm::compose (const Eigen::VectorXd & inputs) const pure virtual
Implemented in polyfem::solver::HomoCompositeForm, polyfem::solver::NegativeCompositeForm, polyfem::solver::PlusConstCompositeForm, polyfem::solver::InequalityConstraintForm, polyfem::solver::PowerForm, polyfem::solver::DivideForm, and polyfem::solver::SumCompositeForm.
Referenced by value_unweighted().
compose_grad()
virtual Eigen::VectorXd polyfem::solver::CompositeForm::compose_grad (const Eigen::VectorXd & inputs) const pure virtual
Implemented in polyfem::solver::HomoCompositeForm, polyfem::solver::NegativeCompositeForm, polyfem::solver::PlusConstCompositeForm, polyfem::solver::InequalityConstraintForm, polyfem::solver::PowerForm, polyfem::solver::DivideForm, and polyfem::solver::SumCompositeForm.
Referenced by compute_partial_gradient_unweighted(), and compute_reduced_adjoint_rhs_unweighted().
compute_partial_gradient_unweighted()
virtual void polyfem::solver::CompositeForm::compute_partial_gradient_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const inline final override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 35 of file CompositeForm.hpp.
References compose_grad(), forms_, get_inputs(), and x.
compute_reduced_adjoint_rhs_unweighted()
virtual Eigen::MatrixXd polyfem::solver::CompositeForm::compute_reduced_adjoint_rhs_unweighted (const Eigen::VectorXd & x, const State & state) const inline final override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 18 of file CompositeForm.hpp.
References compose_grad(), forms_, get_inputs(), and x.
get_inputs()
Eigen::VectorXd polyfem::solver::CompositeForm::get_inputs (const Eigen::VectorXd & x) const inline
Definition at line 51 of file CompositeForm.hpp.
References forms_, and x.
Referenced by compute_partial_gradient_unweighted(), compute_reduced_adjoint_rhs_unweighted(), and value_unweighted().
init()
virtual void polyfem::solver::CompositeForm::init (const Eigen::VectorXd & x) inline override virtual
Initialize the form.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 67 of file CompositeForm.hpp.
References forms_, and x.
init_lagging()
virtual void polyfem::solver::CompositeForm::init_lagging (const Eigen::VectorXd & x) inline override virtual
Initialize lagged fields TODO: more than one step.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 124 of file CompositeForm.hpp.
References forms_, and x.
is_step_collision_free()
virtual bool polyfem::solver::CompositeForm::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline override virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented from polyfem::solver::Form.
Definition at line 142 of file CompositeForm.hpp.
References forms_.
is_step_valid()
virtual bool polyfem::solver::CompositeForm::is_step_valid (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline override virtual
Determine if a step from solution x0 to solution x1 is allowed.
Parameters
x0 Current solution
x1 Proposed next solution
Returns
True if the step is allowed
Reimplemented from polyfem::solver::Form.
Definition at line 73 of file CompositeForm.hpp.
References forms_.
line_search_begin()
virtual void polyfem::solver::CompositeForm::line_search_begin (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) inline override virtual
Initialize variables used during the line search.
Parameters
x0 Current solution
x1 Next solution
Reimplemented from polyfem::solver::Form.
Definition at line 93 of file CompositeForm.hpp.
References forms_.
line_search_end()
virtual void polyfem::solver::CompositeForm::line_search_end () inline override virtual
Clear variables used during the line search.
Reimplemented from polyfem::solver::Form.
Definition at line 99 of file CompositeForm.hpp.
References forms_.
max_step_size()
virtual double polyfem::solver::CompositeForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline override virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::Form.
Definition at line 83 of file CompositeForm.hpp.
References forms_.
n_objs()
virtual int polyfem::solver::CompositeForm::n_objs () const inline final virtual
Definition at line 16 of file CompositeForm.hpp.
References forms_.
post_step()
virtual void polyfem::solver::CompositeForm::post_step (const int iter_num, const Eigen::VectorXd & x) inline override virtual
Update fields after a step in the optimization.
Parameters
iter_num Optimization iteration number
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 105 of file CompositeForm.hpp.
References forms_, and x.
set_apply_DBC()
virtual void polyfem::solver::CompositeForm::set_apply_DBC (const Eigen::VectorXd & x, bool apply_DBC) inline override virtual
Set if the Dirichlet boundary conditions should be enforced.
Note
This is specific to the body form.
Parameters
apply_DBC If true, apply Dirichlet boundary conditions to the current RHS.
Reimplemented from polyfem::solver::Form.
Definition at line 136 of file CompositeForm.hpp.
References forms_, and x.
solution_changed()
virtual void polyfem::solver::CompositeForm::solution_changed (const Eigen::VectorXd & new_x) inline override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 111 of file CompositeForm.hpp.
References forms_, and polyfem::solver::AdjointForm::solution_changed().
update_lagging()
virtual void polyfem::solver::CompositeForm::update_lagging (const Eigen::VectorXd & x, const int iter_num) inline override virtual
Update lagged fields.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 130 of file CompositeForm.hpp.
References forms_, and x.
update_quantities()
virtual void polyfem::solver::CompositeForm::update_quantities (const double t, const Eigen::VectorXd & x) inline override virtual
Update time-dependent fields.
Parameters
t Current time
x Current solution at time t
Reimplemented from polyfem::solver::Form.
Definition at line 118 of file CompositeForm.hpp.
References forms_, and x.
value_unweighted()
virtual double polyfem::solver::CompositeForm::value_unweighted (const Eigen::VectorXd & x) const inline final override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 62 of file CompositeForm.hpp.
References compose(), get_inputs(), and x.
Member Data Documentation
forms_
std::vector<std::shared_ptr<AdjointForm> > polyfem::solver::CompositeForm::forms_ private
Definition at line 153 of file CompositeForm.hpp.
Referenced by compute_partial_gradient_unweighted(), compute_reduced_adjoint_rhs_unweighted(), get_inputs(), init(), init_lagging(), is_step_collision_free(), is_step_valid(), line_search_begin(), line_search_end(), max_step_size(), n_objs(), post_step(), set_apply_DBC(), solution_changed(), update_lagging(), and update_quantities().
The documentation for this class was generated from the following file:
src/polyfem/solver/forms/adjoint_forms/CompositeForm.hpp