PolyFEM: polyfem::problem::PointBasedTensorProblem::BCValue Class Reference
polyfem::problem::PointBasedTensorProblem::BCValue Class Reference
Public Member Functions
BCValue ()
Eigen::RowVector3d operator() (const Eigen::RowVector3d &pt) const
bool init (const json &data)
void init (const double x, const double y, const double z, const Eigen::Matrix< bool, 3, 1 > &dd)
void init (const Eigen::Vector3d &v, const Eigen::Matrix< bool, 3, 1 > &dd)
void init (const Eigen::MatrixXd &pts, const Eigen::MatrixXi &tri, const Eigen::MatrixXd &fun, const int coord, const Eigen::Matrix< bool, 3, 1 > &dd)
void init (const Eigen::MatrixXd &pts, const Eigen::MatrixXd &fun, const std::string &rbf, const double eps, const int coord, const Eigen::Matrix< bool, 3, 1 > &dd)
bool is_dirichet_dim (const int d) const
Private Attributes
Eigen::Vector3d val
utils::InterpolatedFunction2d tri_func
utils::RBFInterpolation rbf_func
bool is_val
bool is_tri
int coordiante_0 = 0
int coordiante_1 = 1
Eigen::Matrix< bool, 3, 1 > dirichlet_dims
Detailed Description
Definition at line 19 of file PointBasedProblem.hpp.
Constructor & Destructor Documentation
BCValue()
polyfem::problem::PointBasedTensorProblem::BCValue::BCValue () inline
Definition at line 22 of file PointBasedProblem.hpp.
References init().
Member Function Documentation
init() [1/5]
void polyfem::problem::PointBasedTensorProblem::BCValue::init (const double x, const double y, const double z, const Eigen::Matrix< bool, 3, 1 > & dd) inline
Definition at line 33 of file PointBasedProblem.hpp.
References dirichlet_dims, is_val, val, x, y, and z.
init() [2/5]
void polyfem::problem::PointBasedTensorProblem::BCValue::init (const Eigen::MatrixXd & pts, const Eigen::MatrixXd & fun, const std::string & rbf, const double eps, const int coord, const Eigen::Matrix< bool, 3, 1 > & dd) inline
Definition at line 60 of file PointBasedProblem.hpp.
References coordiante_0, coordiante_1, dirichlet_dims, polyfem::utils::RBFInterpolation::init(), is_tri, is_val, and rbf_func.
init() [3/5]
void polyfem::problem::PointBasedTensorProblem::BCValue::init (const Eigen::MatrixXd & pts, const Eigen::MatrixXi & tri, const Eigen::MatrixXd & fun, const int coord, const Eigen::Matrix< bool, 3, 1 > & dd) inline
Definition at line 47 of file PointBasedProblem.hpp.
References coordiante_0, coordiante_1, dirichlet_dims, polyfem::utils::InterpolatedFunction2d::init(), is_tri, is_val, and tri_func.
init() [4/5]
void polyfem::problem::PointBasedTensorProblem::BCValue::init (const Eigen::Vector3d & v, const Eigen::Matrix< bool, 3, 1 > & dd) inline
Definition at line 40 of file PointBasedProblem.hpp.
References dirichlet_dims, is_val, and val.
init() [5/5]
bool polyfem::problem::PointBasedTensorProblem::BCValue::init (const json & data)
Definition at line 14 of file PointBasedProblem.cpp.
References polyfem::problem::PointBasedTensorProblem::all_dimensions_dirichlet(), init(), is_tri, polyfem::utils::read_matrix(), and p_bases::tmp.
Referenced by BCValue(), and init().
is_dirichet_dim()
bool polyfem::problem::PointBasedTensorProblem::BCValue::is_dirichet_dim (const int d) const inline
Definition at line 81 of file PointBasedProblem.hpp.
References dirichlet_dims.
operator()()
Eigen::RowVector3d polyfem::problem::PointBasedTensorProblem::BCValue::operator() (const Eigen::RowVector3d & pt) const
Definition at line 80 of file PointBasedProblem.cpp.
References val.
Member Data Documentation
coordiante_0
int polyfem::problem::PointBasedTensorProblem::BCValue::coordiante_0 = 0 private
Definition at line 89 of file PointBasedProblem.hpp.
Referenced by init().
coordiante_1
int polyfem::problem::PointBasedTensorProblem::BCValue::coordiante_1 = 1 private
Definition at line 90 of file PointBasedProblem.hpp.
Referenced by init().
dirichlet_dims
Eigen::Matrix<bool, 3, 1> polyfem::problem::PointBasedTensorProblem::BCValue::dirichlet_dims private
Definition at line 91 of file PointBasedProblem.hpp.
Referenced by init(), and is_dirichet_dim().
is_tri
bool polyfem::problem::PointBasedTensorProblem::BCValue::is_tri private
Definition at line 88 of file PointBasedProblem.hpp.
Referenced by init().
is_val
bool polyfem::problem::PointBasedTensorProblem::BCValue::is_val private
Definition at line 87 of file PointBasedProblem.hpp.
Referenced by init().
rbf_func
utils::RBFInterpolation polyfem::problem::PointBasedTensorProblem::BCValue::rbf_func private
Definition at line 86 of file PointBasedProblem.hpp.
Referenced by init().
tri_func
utils::InterpolatedFunction2d polyfem::problem::PointBasedTensorProblem::BCValue::tri_func private
Definition at line 85 of file PointBasedProblem.hpp.
Referenced by init().
val
Eigen::Vector3d polyfem::problem::PointBasedTensorProblem::BCValue::val private
Definition at line 84 of file PointBasedProblem.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
src/polyfem/problem/PointBasedProblem.hpp
src/polyfem/problem/PointBasedProblem.cpp