PolyFEM: polyfem::solver::InitialConditionVariableToSimulation Class Reference
polyfem::solver::InitialConditionVariableToSimulation Class Reference
Maps to initial solution and solution velocity.
#include <InitialConditionVariableToSimulation.hpp>
Public Types
using StatePtrs = std::vector< std::shared_ptr< State > >
using DiffCachePtrs = std::vector< std::shared_ptr< DiffCache > >
Public Member Functions
InitialConditionVariableToSimulation (StatePtrs states, DiffCachePtrs diff_caches, CompositeParametrization parametrizations, Eigen::VectorXi active_dofs)
Construct InitialConditionVariableToSimulation.
std::string name () const override
ParameterType parameter_type () const override
bool affect_state (const State &target) const override
Return true if current var2sim maps to target state.
void update (const Eigen::VectorXd &x) override
Update forward simulation states from optimization variables.
void update_state_variables (const Eigen::VectorXd &x, Eigen::VectorXd &state_variables) const override
Update state variables from optimization variables.
Eigen::VectorXd compute_adjoint_term (const Eigen::VectorXd &x) const override
Compute adjoint contribution of objective gradient.
int inverse_dof () const override
Compute optimization variables dof.
Eigen::VectorXd inverse_eval () const override
Compute optimization variables from forward simulation State.
Eigen::VectorXd apply_parametrization_jacobian (const Eigen::VectorXd &term, const Eigen::VectorXd &x) const override
Apply parametrization jacobian to compute the gradient w.r.t.
Public Member Functions inherited from polyfem::solver::VariableToSimulation
virtual ~VariableToSimulation ()=default
Private Member Functions
int para_out_dof () const
Private Attributes
int dof_num_
StatePtrs states_
DiffCachePtrs diff_caches_
CompositeParametrization parametrization_
Eigen::VectorXi active_dofs_
Detailed Description
Maps to initial solution and solution velocity.
Expect optimization variables with layout: [ initial solution of all dofs .... ] [ initail solution velocity of all dofs ... ]
Definition at line 17 of file InitialConditionVariableToSimulation.hpp.
Member Typedef Documentation
DiffCachePtrs
using polyfem::solver::InitialConditionVariableToSimulation::DiffCachePtrs = std::vector<std::shared_ptr<DiffCache> >
Definition at line 21 of file InitialConditionVariableToSimulation.hpp.
StatePtrs
using polyfem::solver::InitialConditionVariableToSimulation::StatePtrs = std::vector<std::shared_ptr<State> >
Definition at line 20 of file InitialConditionVariableToSimulation.hpp.
Constructor & Destructor Documentation
InitialConditionVariableToSimulation()
polyfem::solver::InitialConditionVariableToSimulation::InitialConditionVariableToSimulation (StatePtrs states, DiffCachePtrs diff_caches, CompositeParametrization parametrizations, Eigen::VectorXi active_dofs)
Construct InitialConditionVariableToSimulation.
Parameters
[in] states Shared ptr to all forward sim states.
[in] diff_caches Shared ptr to all diff caches.
[in] parametrizations Parametrizations.
[in] active_dofs Active solution space dofs. Empty implies all active.
Exceptions
std::runtime_error Throw if input is invalid.
Definition at line 16 of file InitialConditionVariableToSimulation.cpp.
References active_dofs_, diff_caches_, dof_num_, polyfem::solver::is_active_dofs_valid(), polyfem::log_and_throw_adjoint_error(), and states_.
Member Function Documentation
affect_state()
bool polyfem::solver::InitialConditionVariableToSimulation::affect_state (const State & target) const override virtual
Return true if current var2sim maps to target state.
Implements polyfem::solver::VariableToSimulation.
Definition at line 95 of file InitialConditionVariableToSimulation.cpp.
References states_.
apply_parametrization_jacobian()
Eigen::VectorXd polyfem::solver::InitialConditionVariableToSimulation::apply_parametrization_jacobian (const Eigen::VectorXd & term, const Eigen::VectorXd & x) const override virtual
Apply parametrization jacobian to compute the gradient w.r.t.
to optimization variables.
Parameters
term Gradient w.r.t. to full inherent dof (Ex. all vertices for shape var2sim)
x Optimization variables.
Implements polyfem::solver::VariableToSimulation.
Definition at line 204 of file InitialConditionVariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error(), and name().
compute_adjoint_term()
Eigen::VectorXd polyfem::solver::InitialConditionVariableToSimulation::compute_adjoint_term (const Eigen::VectorXd & x) const override virtual
Compute adjoint contribution of objective gradient.
See arXiv:2205.13643.
Let objective function be J and optimization variable be x. This method computes all adjoint related terms in dJ/dx. For static case (E.q. 11), it's the second term. For dynamic case (E.q. 15), it's everything except ∂qJ.
Parameters
x[in] Optimization variables.
Returns
Adjoint contribution of objective gradient.
Implements polyfem::solver::VariableToSimulation.
Definition at line 146 of file InitialConditionVariableToSimulation.cpp.
References active_dofs_, polyfem::solver::CompositeParametrization::apply_jacobian(), diff_caches_, polyfem::solver::AdjointTools::dJ_initial_condition_adjoint_term(), dof_num_, polyfem::get_adjoint_mat(), para_out_dof(), parametrization_, states_, and x.
inverse_dof()
int polyfem::solver::InitialConditionVariableToSimulation::inverse_dof () const override virtual
Compute optimization variables dof.
Returns
Optimization variables dof.
Exceptions
std::runtime_error Throw if not implemented.
Implements polyfem::solver::VariableToSimulation.
Definition at line 182 of file InitialConditionVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::inverse_size(), para_out_dof(), and parametrization_.
inverse_eval()
Eigen::VectorXd polyfem::solver::InitialConditionVariableToSimulation::inverse_eval () const override virtual
Compute optimization variables from forward simulation State.
Returns
Optimization variables.
Exceptions
std::runtime_error Throw if not implemented.
Implements polyfem::solver::VariableToSimulation.
Definition at line 187 of file InitialConditionVariableToSimulation.cpp.
References active_dofs_, diff_caches_, dof_num_, polyfem::solver::CompositeParametrization::inverse_eval(), para_out_dof(), parametrization_, and y.
name()
std::string polyfem::solver::InitialConditionVariableToSimulation::name () const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 85 of file InitialConditionVariableToSimulation.cpp.
Referenced by apply_parametrization_jacobian().
para_out_dof()
int polyfem::solver::InitialConditionVariableToSimulation::para_out_dof () const private
Definition at line 210 of file InitialConditionVariableToSimulation.cpp.
References active_dofs_.
Referenced by compute_adjoint_term(), inverse_dof(), inverse_eval(), update(), and update_state_variables().
parameter_type()
ParameterType polyfem::solver::InitialConditionVariableToSimulation::parameter_type () const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 90 of file InitialConditionVariableToSimulation.cpp.
References polyfem::solver::InitialCondition.
update()
void polyfem::solver::InitialConditionVariableToSimulation::update (const Eigen::VectorXd & x) override virtual
Update forward simulation states from optimization variables.
Parameters
[in] x Optimization variables.
Implements polyfem::solver::VariableToSimulation.
Definition at line 107 of file InitialConditionVariableToSimulation.cpp.
References active_dofs_, diff_caches_, dof_num_, polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, x, and y.
update_state_variables()
void polyfem::solver::InitialConditionVariableToSimulation::update_state_variables (const Eigen::VectorXd & x, Eigen::VectorXd & state_variables) const override virtual
Update state variables from optimization variables.
Compared to update() this method update abstract state variables instead of writing directly to state.
Parameters
[in] x Optimization variables.
[out] state_variables Abstract state variables update dst.
Implements polyfem::solver::VariableToSimulation.
Definition at line 131 of file InitialConditionVariableToSimulation.cpp.
References active_dofs_, dof_num_, polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, x, and y.
Member Data Documentation
active_dofs_
Eigen::VectorXi polyfem::solver::InitialConditionVariableToSimulation::active_dofs_ private
Definition at line 49 of file InitialConditionVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), InitialConditionVariableToSimulation(), inverse_eval(), para_out_dof(), update(), and update_state_variables().
diff_caches_
DiffCachePtrs polyfem::solver::InitialConditionVariableToSimulation::diff_caches_ private
Definition at line 47 of file InitialConditionVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), InitialConditionVariableToSimulation(), inverse_eval(), and update().
dof_num_
int polyfem::solver::InitialConditionVariableToSimulation::dof_num_ private
Definition at line 45 of file InitialConditionVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), InitialConditionVariableToSimulation(), inverse_eval(), update(), and update_state_variables().
parametrization_
CompositeParametrization polyfem::solver::InitialConditionVariableToSimulation::parametrization_ private
Definition at line 48 of file InitialConditionVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), inverse_dof(), inverse_eval(), update(), and update_state_variables().
states_
StatePtrs polyfem::solver::InitialConditionVariableToSimulation::states_ private
Definition at line 46 of file InitialConditionVariableToSimulation.hpp.
Referenced by affect_state(), compute_adjoint_term(), and InitialConditionVariableToSimulation().
The documentation for this class was generated from the following files:
src/polyfem/optimization/var2sims/InitialConditionVariableToSimulation.hpp
src/polyfem/optimization/var2sims/InitialConditionVariableToSimulation.cpp