PolyFEM: polyfem::solver::ScalarVelocityParametrization Class Reference
polyfem::solver::ScalarVelocityParametrization Class Reference
#include <Parametrizations.hpp>
Public Member Functions
ScalarVelocityParametrization (const double start_val, const double dt)
int size (const int x_size) const override
Eigen::VectorXd inverse_eval (const Eigen::VectorXd &y) override
Eigen::VectorXd eval (const Eigen::VectorXd &x) const override
Eigen::VectorXd apply_jacobian (const Eigen::VectorXd &grad, const Eigen::VectorXd &x) const override
Public Member Functions inherited from polyfem::solver::Parametrization
Parametrization ()
virtual ~Parametrization ()
Private Attributes
const double start_val_
const double dt_
Detailed Description
Definition at line 171 of file Parametrizations.hpp.
Constructor & Destructor Documentation
ScalarVelocityParametrization()
polyfem::solver::ScalarVelocityParametrization::ScalarVelocityParametrization (const double start_val, const double dt) inline
Definition at line 174 of file Parametrizations.hpp.
Member Function Documentation
apply_jacobian()
Eigen::VectorXd polyfem::solver::ScalarVelocityParametrization::apply_jacobian (const Eigen::VectorXd & grad, const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 483 of file Parametrizations.cpp.
References dt_, size(), and x.
eval()
Eigen::VectorXd polyfem::solver::ScalarVelocityParametrization::eval (const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 473 of file Parametrizations.cpp.
References dt_, size(), start_val_, x, and y.
inverse_eval()
Eigen::VectorXd polyfem::solver::ScalarVelocityParametrization::inverse_eval (const Eigen::VectorXd & y) override virtual
Reimplemented from polyfem::solver::Parametrization.
Definition at line 463 of file Parametrizations.cpp.
References dt_, size(), start_val_, x, and y.
size()
int polyfem::solver::ScalarVelocityParametrization::size (const int x_size) const inline override virtual
Implements polyfem::solver::Parametrization.
Definition at line 176 of file Parametrizations.hpp.
Referenced by apply_jacobian(), eval(), and inverse_eval().
Member Data Documentation
dt_
const double polyfem::solver::ScalarVelocityParametrization::dt_ private
Definition at line 183 of file Parametrizations.hpp.
Referenced by apply_jacobian(), eval(), and inverse_eval().
start_val_
const double polyfem::solver::ScalarVelocityParametrization::start_val_ private
Definition at line 182 of file Parametrizations.hpp.
Referenced by eval(), and inverse_eval().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/parametrization/Parametrizations.hpp
src/polyfem/solver/forms/parametrization/Parametrizations.cpp