PolyFEM: polyfem::solver::BoundarySmoothingForm Class Reference
polyfem::solver::BoundarySmoothingForm Class Reference
#include <SmoothingForms.hpp>
Public Member Functions
BoundarySmoothingForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations, const State &state, const bool scale_invariant, const int power)
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void compute_partial_gradient_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Eigen::MatrixXd compute_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const override
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const std::vector< std::shared_ptr< VariableToSimulation > > &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
void enable_energy_print (const std::string &print_energy_keyword)
virtual void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
const auto & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const final
virtual void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs_unweighted (const Eigen::VectorXd &x, const State &state) const
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x)
Update fields after a step in the optimization.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num)
Update lagged fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC)
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Private Member Functions
void init_form ()
Private Attributes
const State & state_
const bool scale_invariant_
const int power_
Eigen::SparseMatrix< bool, Eigen::RowMajor > adj
Eigen::SparseMatrix< double, Eigen::RowMajor > L
Additional Inherited Members
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes inherited from polyfem::solver::AdjointForm
std::vector< std::shared_ptr< VariableToSimulation > > variable_to_simulations_
int print_energy_ = 0
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 12 of file SmoothingForms.hpp.
Constructor & Destructor Documentation
BoundarySmoothingForm()
polyfem::solver::BoundarySmoothingForm::BoundarySmoothingForm (const std::vector< std::shared_ptr< VariableToSimulation > > & variable_to_simulations, const State & state, const bool scale_invariant, const int power) inline
Definition at line 15 of file SmoothingForms.hpp.
References init_form().
Member Function Documentation
compute_adjoint_rhs_unweighted()
Eigen::MatrixXd polyfem::solver::BoundarySmoothingForm::compute_adjoint_rhs_unweighted (const Eigen::VectorXd & x, const State & state) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 7 of file SmoothingForms.cpp.
References polyfem::State::diff_cached, polyfem::State::ndof(), and polyfem::solver::DiffCache::size().
compute_partial_gradient_unweighted()
void polyfem::solver::BoundarySmoothingForm::compute_partial_gradient_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 117 of file SmoothingForms.cpp.
References adj, polyfem::utils::flatten(), polyfem::State::get_vertices(), L, polyfem::State::mesh, power_, scale_invariant_, polyfem::solver::Shape, state_, polyfem::solver::AdjointForm::variable_to_simulations_, and x.
init_form()
void polyfem::solver::BoundarySmoothingForm::init_form () private
Definition at line 12 of file SmoothingForms.cpp.
References adj, L, polyfem::State::mesh, scale_invariant_, state_, and val.
Referenced by BoundarySmoothingForm().
value_unweighted()
double polyfem::solver::BoundarySmoothingForm::value_unweighted (const Eigen::VectorXd & x) const override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 76 of file SmoothingForms.cpp.
References adj, polyfem::State::get_vertices(), L, polyfem::State::mesh, power_, scale_invariant_, state_, val, and x.
Member Data Documentation
adj
Eigen::SparseMatrix<bool, Eigen::RowMajor> polyfem::solver::BoundarySmoothingForm::adj private
Definition at line 30 of file SmoothingForms.hpp.
Referenced by compute_partial_gradient_unweighted(), init_form(), and value_unweighted().
L
Eigen::SparseMatrix<double, Eigen::RowMajor> polyfem::solver::BoundarySmoothingForm::L private
Definition at line 31 of file SmoothingForms.hpp.
Referenced by compute_partial_gradient_unweighted(), init_form(), and value_unweighted().
power_
const int polyfem::solver::BoundarySmoothingForm::power_ private
Definition at line 29 of file SmoothingForms.hpp.
Referenced by compute_partial_gradient_unweighted(), and value_unweighted().
scale_invariant_
const bool polyfem::solver::BoundarySmoothingForm::scale_invariant_ private
Definition at line 28 of file SmoothingForms.hpp.
Referenced by compute_partial_gradient_unweighted(), init_form(), and value_unweighted().
state_
const State& polyfem::solver::BoundarySmoothingForm::state_ private
Definition at line 27 of file SmoothingForms.hpp.
Referenced by compute_partial_gradient_unweighted(), init_form(), and value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/SmoothingForms.hpp
src/polyfem/solver/forms/adjoint_forms/SmoothingForms.cpp