PolyFEM: polyfem::solver::ElasticForm Class Reference
polyfem::solver::ElasticForm Class Reference
Form of the elasticity potential and forces.
#include <ElasticForm.hpp>
Public Member Functions
ElasticForm (const int n_bases, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &geom_bases, const assembler::Assembler &assembler, const assembler::AssemblyValsCache &ass_vals_cache, const double dt, const bool is_volume)
Construct a new Elastic Form object.
bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine if a step from solution x0 to solution x1 is allowed.
void update_quantities (const double t, const Eigen::VectorXd &x) override
Update time-dependent fields.
void force_material_derivative (const Eigen::MatrixXd &x, const Eigen::MatrixXd &x_prev, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &term)
Compute the derivative of the force wrt lame/damping parameters, then multiply the resulting matrix with adjoint_sol.
void force_shape_derivative (const int n_verts, const Eigen::MatrixXd &x, const Eigen::MatrixXd &x_prev, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &term)
Compute the derivative of the force wrt vertex positions, then multiply the resulting matrix with adjoint_sol.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual double value (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x)
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x)
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num)
Update lagged fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC)
Set if the Dirichlet boundary conditions should be enforced.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
virtual double value_unweighted (const Eigen::VectorXd &x) const override
Compute the elastic potential value.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual double value_unweighted (const Eigen::VectorXd &x) const =0
Compute the value of the form.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const =0
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const =0
Compute the second derivative of the value wrt x.
Private Member Functions
void compute_cached_stiffness ()
Compute the stiffness matrix (cached)
Private Attributes
const int n_bases_
const std::vector< basis::ElementBases > & bases_
const std::vector< basis::ElementBases > & geom_bases_
const assembler::Assembler & assembler_
Reference to the assembler.
const assembler::AssemblyValsCache & ass_vals_cache_
const double dt_
const bool is_volume_
StiffnessMatrix cached_stiffness_
Cached stiffness matrix for linear elasticity.
utils::SparseMatrixCache mat_cache_
Matrix cache (mutable because it is modified in second_derivative_unweighted)
Eigen::VectorXd x_prev_
Additional Inherited Members
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Form of the elasticity potential and forces.
Definition at line 14 of file ElasticForm.hpp.
Constructor & Destructor Documentation
ElasticForm()
polyfem::solver::ElasticForm::ElasticForm (const int n_bases, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & geom_bases, const assembler::Assembler & assembler, const assembler::AssemblyValsCache & ass_vals_cache, const double dt, const bool is_volume)
Construct a new Elastic Form object.
Parameters
state Reference to the simulation state
Definition at line 34 of file ElasticForm.cpp.
References assembler_, compute_cached_stiffness(), and polyfem::assembler::Assembler::is_linear().
Member Function Documentation
compute_cached_stiffness()
void polyfem::solver::ElasticForm::compute_cached_stiffness () private
Compute the stiffness matrix (cached)
Definition at line 104 of file ElasticForm.cpp.
References ass_vals_cache_, polyfem::assembler::Assembler::assemble(), assembler_, bases_, cached_stiffness_, geom_bases_, polyfem::assembler::Assembler::is_linear(), is_volume_, and n_bases_.
Referenced by ElasticForm().
first_derivative_unweighted()
void polyfem::solver::ElasticForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override protected virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Implements polyfem::solver::Form.
Definition at line 59 of file ElasticForm.cpp.
References ass_vals_cache_, polyfem::assembler::Assembler::assemble_gradient(), assembler_, bases_, dt_, geom_bases_, is_volume_, n_bases_, x, and x_prev_.
force_material_derivative()
void polyfem::solver::ElasticForm::force_material_derivative (const Eigen::MatrixXd & x, const Eigen::MatrixXd & x_prev, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & term)
Compute the derivative of the force wrt lame/damping parameters, then multiply the resulting matrix with adjoint_sol.
Parameters
[in] x Current solution
[in] adjoint Current adjoint solution
[out] term Derivative of force multiplied by the adjoint
Definition at line 113 of file ElasticForm.cpp.
References ass_vals_cache_, assembler_, bases_, polyfem::assembler::AssemblyValsCache::compute(), polyfem::assembler::Assembler::compute_dstress_dmu_dlambda(), polyfem::assembler::ViscousDamping::compute_dstress_dpsi_dphi(), polyfem::utils::create_thread_storage(), polyfem::assembler::ElementAssemblyValues::det, dt_, geom_bases_, polyfem::utils::get_local_thread_storage(), polyfem::io::Evaluator::interpolate_at_local_vals(), is_volume_, polyfem::utils::maybe_parallel_for(), polyfem::assembler::Assembler::name(), polyfem::quadrature::Quadrature::points, polyfem::assembler::ElementAssemblyValues::quadrature, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::utils::vector2matrix(), polyfem::quadrature::Quadrature::weights, and x.
force_shape_derivative()
void polyfem::solver::ElasticForm::force_shape_derivative (const int n_verts, const Eigen::MatrixXd & x, const Eigen::MatrixXd & x_prev, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & term)
Compute the derivative of the force wrt vertex positions, then multiply the resulting matrix with adjoint_sol.
Parameters
[in] n_verts Number of vertices
[in] x Current solution
[in] adjoint Current adjoint solution
[out] term Derivative of force multiplied by the adjoint
Definition at line 203 of file ElasticForm.cpp.
References ass_vals_cache_, assembler_, bases_, polyfem::assembler::AssemblyValsCache::compute(), polyfem::assembler::Assembler::compute_stress_grad(), polyfem::assembler::Assembler::compute_stress_grad_multiply_mat(), polyfem::assembler::Assembler::compute_stress_prev_grad(), polyfem::utils::create_thread_storage(), polyfem::assembler::ElementAssemblyValues::det, dt_, geom_bases_, polyfem::utils::get_local_thread_storage(), gvals, polyfem::io::Evaluator::interpolate_at_local_vals(), is_volume_, polyfem::utils::maybe_parallel_for(), polyfem::assembler::Assembler::name(), polyfem::quadrature::Quadrature::points, polyfem::assembler::ElementAssemblyValues::quadrature, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::utils::vector2matrix(), polyfem::quadrature::Quadrature::weights, and x.
is_step_valid()
bool polyfem::solver::ElasticForm::is_step_valid (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine if a step from solution x0 to solution x1 is allowed.
Parameters
x0 Current solution
x1 Proposed next solution
Returns
True if the step is allowed
Reimplemented from polyfem::solver::Form.
Definition at line 87 of file ElasticForm.cpp.
References polyfem::solver::Form::first_derivative().
second_derivative_unweighted()
void polyfem::solver::ElasticForm::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const override protected virtual
Compute the second derivative of the value wrt x.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Implements polyfem::solver::Form.
Definition at line 67 of file ElasticForm.cpp.
References ass_vals_cache_, polyfem::assembler::Assembler::assemble_hessian(), assembler_, bases_, cached_stiffness_, dt_, geom_bases_, polyfem::assembler::Assembler::is_linear(), is_volume_, mat_cache_, n_bases_, POLYFEM_SCOPED_TIMER, polyfem::solver::Form::project_to_psd_, x, and x_prev_.
update_quantities()
void polyfem::solver::ElasticForm::update_quantities (const double t, const Eigen::VectorXd & x) inline override virtual
Update time-dependent fields.
Parameters
t Current time
x Current solution at time t
Reimplemented from polyfem::solver::Form.
Definition at line 53 of file ElasticForm.hpp.
References x, and x_prev_.
value_unweighted()
double polyfem::solver::ElasticForm::value_unweighted (const Eigen::VectorXd & x) const override protected virtual
Compute the elastic potential value.
Parameters
x Current solution
Returns
Value of the elastic potential
Implements polyfem::solver::Form.
Definition at line 53 of file ElasticForm.cpp.
References ass_vals_cache_, polyfem::assembler::Assembler::assemble_energy(), assembler_, bases_, dt_, geom_bases_, is_volume_, x, and x_prev_.
Member Data Documentation
ass_vals_cache_
const assembler::AssemblyValsCache& polyfem::solver::ElasticForm::ass_vals_cache_ private
Definition at line 74 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), first_derivative_unweighted(), force_material_derivative(), force_shape_derivative(), second_derivative_unweighted(), and value_unweighted().
assembler_
const assembler::Assembler& polyfem::solver::ElasticForm::assembler_ private
Reference to the assembler.
Definition at line 73 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), ElasticForm(), first_derivative_unweighted(), force_material_derivative(), force_shape_derivative(), second_derivative_unweighted(), and value_unweighted().
bases_
const std::vector<basis::ElementBases>& polyfem::solver::ElasticForm::bases_ private
Definition at line 70 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), first_derivative_unweighted(), force_material_derivative(), force_shape_derivative(), second_derivative_unweighted(), and value_unweighted().
cached_stiffness_
StiffnessMatrix polyfem::solver::ElasticForm::cached_stiffness_ private
Cached stiffness matrix for linear elasticity.
Definition at line 78 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), and second_derivative_unweighted().
dt_
const double polyfem::solver::ElasticForm::dt_ private
Definition at line 75 of file ElasticForm.hpp.
Referenced by first_derivative_unweighted(), force_material_derivative(), force_shape_derivative(), second_derivative_unweighted(), and value_unweighted().
geom_bases_
const std::vector<basis::ElementBases>& polyfem::solver::ElasticForm::geom_bases_ private
Definition at line 71 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), first_derivative_unweighted(), force_material_derivative(), force_shape_derivative(), second_derivative_unweighted(), and value_unweighted().
is_volume_
const bool polyfem::solver::ElasticForm::is_volume_ private
Definition at line 76 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), first_derivative_unweighted(), force_material_derivative(), force_shape_derivative(), second_derivative_unweighted(), and value_unweighted().
mat_cache_
utils::SparseMatrixCache polyfem::solver::ElasticForm::mat_cache_ mutable private
Matrix cache (mutable because it is modified in second_derivative_unweighted)
Definition at line 79 of file ElasticForm.hpp.
Referenced by second_derivative_unweighted().
n_bases_
const int polyfem::solver::ElasticForm::n_bases_ private
Definition at line 69 of file ElasticForm.hpp.
Referenced by compute_cached_stiffness(), first_derivative_unweighted(), and second_derivative_unweighted().
x_prev_
Eigen::VectorXd polyfem::solver::ElasticForm::x_prev_ private
Definition at line 84 of file ElasticForm.hpp.
Referenced by first_derivative_unweighted(), second_derivative_unweighted(), update_quantities(), and value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/ElasticForm.hpp
src/polyfem/solver/forms/ElasticForm.cpp