PolyFEM: polyfem::DiffCache Class Reference
polyfem::DiffCache Class Reference
Storage for additional data required by differntial code.
#include <DiffCache.hpp>
Public Member Functions
void cache_adjoints (const Eigen::MatrixXd &adjoint_mat)
void cache_transient (int step, State &state, const Eigen::MatrixXd &sol, const Eigen::MatrixXd *disp_grad, const Eigen::MatrixXd *pressure)
Cache time-dependent adjoint optimization data.
const Eigen::MatrixXd & adjoint_mat () const
const StiffnessMatrix & basis_nodes_to_gbasis_nodes () const
int size () const
int bdf_order (int step) const
Eigen::MatrixXd disp_grad (int step=0) const
Eigen::VectorXd u (int step) const
Eigen::VectorXd v (int step) const
Eigen::VectorXd acc (int step) const
const StiffnessMatrix & gradu_h (int step) const
const ipc::NormalCollisions & collision_set (int step) const
const ipc::SmoothCollisions & smooth_collision_set (int step) const
const ipc::TangentialCollisions & friction_collision_set (int step) const
const ipc::NormalCollisions & normal_adhesion_collision_set (int step) const
const ipc::TangentialCollisions & tangential_adhesion_collision_set (int step) const
Private Member Functions
void init (const int dimension, const int ndof, const int n_time_steps=0)
void cache_quantities_static (const Eigen::MatrixXd &u, const StiffnessMatrix &gradu_h, const ipc::NormalCollisions &collision_set, const ipc::SmoothCollisions &smooth_collision_set, const ipc::TangentialCollisions &friction_constraint_set, const ipc::NormalCollisions &normal_adhesion_set, const ipc::TangentialCollisions &tangential_adhesion_set, const Eigen::MatrixXd &disp_grad)
void cache_quantities_transient (const int cur_step, const int cur_bdf_order, const Eigen::MatrixXd &u, const Eigen::MatrixXd &v, const Eigen::MatrixXd &acc, const StiffnessMatrix &gradu_h, const ipc::NormalCollisions &collision_set, const ipc::SmoothCollisions &smooth_collision_set, const ipc::TangentialCollisions &friction_collision_set)
void cache_quantities_quasistatic (const int cur_step, const Eigen::MatrixXd &u, const StiffnessMatrix &gradu_h, const ipc::NormalCollisions &collision_set, const ipc::SmoothCollisions &smooth_collision_set, const ipc::NormalCollisions &normal_adhesion_set, const Eigen::MatrixXd &disp_grad)
Private Attributes
int n_time_steps_ = 0
int cur_size_ = 0
StiffnessMatrix basis_nodes_to_gbasis_nodes_
std::vector< Eigen::MatrixXd > disp_grad_
Eigen::MatrixXd u_
Eigen::MatrixXd v_
Eigen::MatrixXd acc_
Eigen::VectorXi bdf_order_
std::vector< StiffnessMatrix > gradu_h_
std::vector< ipc::NormalCollisions > collision_set_
std::vector< ipc::SmoothCollisions > smooth_collision_set_
std::vector< ipc::TangentialCollisions > friction_collision_set_
std::vector< ipc::NormalCollisions > normal_adhesion_collision_set_
std::vector< ipc::TangentialCollisions > tangential_adhesion_collision_set_
Eigen::MatrixXd adjoint_mat_
Detailed Description
Storage for additional data required by differntial code.
Definition at line 21 of file DiffCache.hpp.
Member Function Documentation
acc()
Eigen::VectorXd polyfem::DiffCache::acc (int step) const inline
Definition at line 76 of file DiffCache.hpp.
References acc_, and size().
Referenced by cache_quantities_transient(), and cache_transient().
adjoint_mat()
const Eigen::MatrixXd & polyfem::DiffCache::adjoint_mat () const inline
Definition at line 41 of file DiffCache.hpp.
References adjoint_mat_.
Referenced by cache_adjoints(), and polyfem::get_adjoint_mat().
basis_nodes_to_gbasis_nodes()
const StiffnessMatrix & polyfem::DiffCache::basis_nodes_to_gbasis_nodes () const
Definition at line 280 of file DiffCache.cpp.
References basis_nodes_to_gbasis_nodes_.
Referenced by polyfem::solver::AdjointTools::dJ_periodic_shape_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_homogenization_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term(), and polyfem::solver::PeriodicContactForceDerivative::force_shape_derivative().
bdf_order()
int polyfem::DiffCache::bdf_order (int step) const inline
Definition at line 46 of file DiffCache.hpp.
References bdf_order_, and size().
cache_adjoints()
void polyfem::DiffCache::cache_adjoints (const Eigen::MatrixXd & adjoint_mat)
Definition at line 278 of file DiffCache.cpp.
References adjoint_mat(), and adjoint_mat_.
Referenced by polyfem::solve_adjoint_cached().
cache_quantities_quasistatic()
void polyfem::DiffCache::cache_quantities_quasistatic (const int cur_step, const Eigen::MatrixXd & u, const StiffnessMatrix & gradu_h, const ipc::NormalCollisions & collision_set, const ipc::SmoothCollisions & smooth_collision_set, const ipc::NormalCollisions & normal_adhesion_set, const Eigen::MatrixXd & disp_grad) private
Definition at line 259 of file DiffCache.cpp.
References collision_set(), collision_set_, cur_size_, disp_grad(), disp_grad_, gradu_h(), gradu_h_, normal_adhesion_collision_set_, smooth_collision_set(), smooth_collision_set_, u(), and u_.
Referenced by cache_transient().
cache_quantities_static()
void polyfem::DiffCache::cache_quantities_static (const Eigen::MatrixXd & u, const StiffnessMatrix & gradu_h, const ipc::NormalCollisions & collision_set, const ipc::SmoothCollisions & smooth_collision_set, const ipc::TangentialCollisions & friction_constraint_set, const ipc::NormalCollisions & normal_adhesion_set, const ipc::TangentialCollisions & tangential_adhesion_set, const Eigen::MatrixXd & disp_grad) private
Definition at line 208 of file DiffCache.cpp.
References collision_set(), collision_set_, cur_size_, disp_grad(), disp_grad_, friction_collision_set_, gradu_h(), gradu_h_, normal_adhesion_collision_set_, smooth_collision_set(), smooth_collision_set_, tangential_adhesion_collision_set_, u(), and u_.
Referenced by cache_transient().
cache_quantities_transient()
void polyfem::DiffCache::cache_quantities_transient (const int cur_step, const int cur_bdf_order, const Eigen::MatrixXd & u, const Eigen::MatrixXd & v, const Eigen::MatrixXd & acc, const StiffnessMatrix & gradu_h, const ipc::NormalCollisions & collision_set, const ipc::SmoothCollisions & smooth_collision_set, const ipc::TangentialCollisions & friction_collision_set) private
Definition at line 231 of file DiffCache.cpp.
References acc(), acc_, bdf_order_, collision_set(), collision_set_, cur_size_, friction_collision_set(), friction_collision_set_, gradu_h(), gradu_h_, smooth_collision_set(), smooth_collision_set_, u(), u_, v(), and v_.
Referenced by cache_transient().
cache_transient()
void polyfem::DiffCache::cache_transient (int step, State & state, const Eigen::MatrixXd & sol, const Eigen::MatrixXd * disp_grad, const Eigen::MatrixXd * pressure)
Cache time-dependent adjoint optimization data.
Parameters
[in] step Current time step.
[in] state Current forward simulation state. Will mutate it to get latest value.
[in] sol Current solution.
[in] disp_grad Pointer to displacement gradient matrix. Assumes zero if nullptr.
[in] pressure Pointer to pressure matrix. PASS nullptr ONLY.
Warning
We DO NOT support navier stoke problem yet!! Passing non-null pressure triggers exception.
Definition at line 288 of file DiffCache.cpp.
References acc(), basis_nodes_to_gbasis_nodes_, cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), polyfem::solver::Derivatives, disp_grad(), gradu_h(), init(), polyfem::log_and_throw_adjoint_error(), polyfem::log_and_throw_error(), polyfem::time_integrator::ImplicitTimeIntegrator::v_prev(), and polyfem::time_integrator::BDF::weighted_sum_v_prevs().
collision_set()
const ipc::NormalCollisions & polyfem::DiffCache::collision_set (int step) const inline
Definition at line 93 of file DiffCache.hpp.
References collision_set_, and size().
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), polyfem::solver::AdjointTools::dJ_shape_homogenization_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term(), and polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
disp_grad()
Eigen::MatrixXd polyfem::DiffCache::disp_grad (int step = 0) const inline
Definition at line 54 of file DiffCache.hpp.
References disp_grad_, and size().
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_transient(), and polyfem::solver::AdjointTools::dJ_periodic_shape_adjoint_term().
friction_collision_set()
const ipc::TangentialCollisions & polyfem::DiffCache::friction_collision_set (int step) const inline
Definition at line 107 of file DiffCache.hpp.
References friction_collision_set_, and size().
Referenced by cache_quantities_transient(), polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), and polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
gradu_h()
const StiffnessMatrix & polyfem::DiffCache::gradu_h (int step) const inline
Definition at line 84 of file DiffCache.hpp.
References gradu_h_, and size().
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), cache_transient(), and polyfem::solver::AdjointTools::dJ_dirichlet_static_adjoint_term().
init()
void polyfem::DiffCache::init (const int dimension, const int ndof, const int n_time_steps = 0) private
Definition at line 186 of file DiffCache.cpp.
References acc_, bdf_order_, collision_set_, cur_size_, disp_grad_, friction_collision_set_, gradu_h_, n_time_steps_, normal_adhesion_collision_set_, smooth_collision_set_, tangential_adhesion_collision_set_, u_, and v_.
Referenced by cache_transient().
normal_adhesion_collision_set()
const ipc::NormalCollisions & polyfem::DiffCache::normal_adhesion_collision_set (int step) const inline
Definition at line 114 of file DiffCache.hpp.
References normal_adhesion_collision_set_, and size().
Referenced by polyfem::solver::AdjointTools::dJ_shape_homogenization_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term(), and polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
size()
int polyfem::DiffCache::size () const inline
Definition at line 45 of file DiffCache.hpp.
References cur_size_.
Referenced by acc(), bdf_order(), collision_set(), polyfem::solver::AdjointForm::compute_adjoint_rhs(), polyfem::solver::StaticForm::compute_adjoint_rhs(), polyfem::solver::MinTargetDistForm::compute_adjoint_rhs(), polyfem::solver::SpatialIntegralForm::compute_adjoint_rhs_step(), disp_grad(), friction_collision_set(), gradu_h(), normal_adhesion_collision_set(), smooth_collision_set(), tangential_adhesion_collision_set(), u(), and v().
smooth_collision_set()
const ipc::SmoothCollisions & polyfem::DiffCache::smooth_collision_set (int step) const inline
Definition at line 100 of file DiffCache.hpp.
References size(), and smooth_collision_set_.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), polyfem::solver::AdjointTools::dJ_shape_homogenization_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term(), and polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
tangential_adhesion_collision_set()
const ipc::TangentialCollisions & polyfem::DiffCache::tangential_adhesion_collision_set (int step) const inline
Definition at line 121 of file DiffCache.hpp.
References size(), and tangential_adhesion_collision_set_.
Referenced by polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
u()
Eigen::VectorXd polyfem::DiffCache::u (int step) const inline
Definition at line 62 of file DiffCache.hpp.
References size(), and u_.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), polyfem::solver::SpatialIntegralForm::compute_adjoint_rhs_step(), polyfem::solver::NodeTargetForm::compute_adjoint_rhs_step(), polyfem::solver::AdjointTools::dJ_damping_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_material_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_pressure_transient_adjoint_term(), and polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
v()
Eigen::VectorXd polyfem::DiffCache::v (int step) const inline
Definition at line 69 of file DiffCache.hpp.
References size(), and v_.
Referenced by cache_quantities_transient(), and polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term().
Member Data Documentation
acc_
Eigen::MatrixXd polyfem::DiffCache::acc_ private
Definition at line 139 of file DiffCache.hpp.
Referenced by acc(), cache_quantities_transient(), and init().
adjoint_mat_
Eigen::MatrixXd polyfem::DiffCache::adjoint_mat_ private
Definition at line 153 of file DiffCache.hpp.
Referenced by adjoint_mat(), and cache_adjoints().
basis_nodes_to_gbasis_nodes_
StiffnessMatrix polyfem::DiffCache::basis_nodes_to_gbasis_nodes_ private
Definition at line 134 of file DiffCache.hpp.
Referenced by basis_nodes_to_gbasis_nodes(), and cache_transient().
bdf_order_
Eigen::VectorXi polyfem::DiffCache::bdf_order_ private
Definition at line 141 of file DiffCache.hpp.
Referenced by bdf_order(), cache_quantities_transient(), and init().
collision_set_
std::vector<ipc::NormalCollisions> polyfem::DiffCache::collision_set_ private
Definition at line 146 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), collision_set(), and init().
cur_size_
int polyfem::DiffCache::cur_size_ = 0 private
Definition at line 131 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), init(), and size().
disp_grad_
std::vector<Eigen::MatrixXd> polyfem::DiffCache::disp_grad_ private
Definition at line 136 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), disp_grad(), and init().
friction_collision_set_
std::vector<ipc::TangentialCollisions> polyfem::DiffCache::friction_collision_set_ private
Definition at line 148 of file DiffCache.hpp.
Referenced by cache_quantities_static(), cache_quantities_transient(), friction_collision_set(), and init().
gradu_h_
std::vector<StiffnessMatrix> polyfem::DiffCache::gradu_h_ private
Definition at line 143 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), gradu_h(), and init().
n_time_steps_
int polyfem::DiffCache::n_time_steps_ = 0 private
Definition at line 130 of file DiffCache.hpp.
Referenced by init().
normal_adhesion_collision_set_
std::vector<ipc::NormalCollisions> polyfem::DiffCache::normal_adhesion_collision_set_ private
Definition at line 150 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), init(), and normal_adhesion_collision_set().
smooth_collision_set_
std::vector<ipc::SmoothCollisions> polyfem::DiffCache::smooth_collision_set_ private
Definition at line 147 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), init(), and smooth_collision_set().
tangential_adhesion_collision_set_
std::vector<ipc::TangentialCollisions> polyfem::DiffCache::tangential_adhesion_collision_set_ private
Definition at line 151 of file DiffCache.hpp.
Referenced by cache_quantities_static(), init(), and tangential_adhesion_collision_set().
u_
Eigen::MatrixXd polyfem::DiffCache::u_ private
Definition at line 137 of file DiffCache.hpp.
Referenced by cache_quantities_quasistatic(), cache_quantities_static(), cache_quantities_transient(), init(), and u().
v_
Eigen::MatrixXd polyfem::DiffCache::v_ private
Definition at line 138 of file DiffCache.hpp.
Referenced by cache_quantities_transient(), init(), and v().
The documentation for this class was generated from the following files:
src/polyfem/optimization/DiffCache.hpp
src/polyfem/optimization/DiffCache.cpp