PolyFEM: polyfem::solver::FullNLProblem Class Reference
polyfem::solver::FullNLProblem Class Reference
#include <FullNLProblem.hpp>
Public Member Functions
FullNLProblem (const std::vector< std::shared_ptr< Form > > &forms)
virtual ~FullNLProblem ()=default
virtual void init (const TVector &x0) override
virtual double value (const TVector &x) override
virtual void gradient (const TVector &x, TVector &gradv) override
virtual void hessian (const TVector &x, THessian &hessian) override
virtual bool is_step_valid (const TVector &x0, const TVector &x1) override
virtual bool is_step_collision_free (const TVector &x0, const TVector &x1)
virtual double max_step_size (const TVector &x0, const TVector &x1) override
virtual void line_search_begin (const TVector &x0, const TVector &x1) override
virtual void line_search_end () override
virtual void post_step (const polysolve::nonlinear::PostStepData &data) override
virtual void set_project_to_psd (bool val) override
virtual void solution_changed (const TVector &new_x) override
virtual void init_lagging (const TVector &x)
virtual void update_lagging (const TVector &x, const int iter_num)
int max_lagging_iterations () const
bool uses_lagging () const
std::vector< std::shared_ptr< Form > > & forms ()
virtual bool stop (const TVector &x) override
void finish ()
virtual double normalize_forms ()
Protected Attributes
std::vector< std::shared_ptr< Form > > forms_
Detailed Description
Definition at line 11 of file FullNLProblem.hpp.
Constructor & Destructor Documentation
FullNLProblem()
polyfem::solver::FullNLProblem::FullNLProblem (const std::vector< std::shared_ptr< Form > > & forms)
Definition at line 6 of file FullNLProblem.cpp.
~FullNLProblem()
virtual polyfem::solver::FullNLProblem::~FullNLProblem () virtual default
Member Function Documentation
finish()
void polyfem::solver::FullNLProblem::finish () inline
Definition at line 43 of file FullNLProblem.hpp.
References forms_.
Referenced by polyfem::solver::ALSolver::solve_al(), polyfem::solver::ALSolver::solve_reduced(), and polyfem::State::solve_tensor_nonlinear().
forms()
std::vector< std::shared_ptr< Form > > & polyfem::solver::FullNLProblem::forms () inline
Definition at line 39 of file FullNLProblem.hpp.
References forms_.
gradient()
void polyfem::solver::FullNLProblem::gradient (const TVector & x, TVector & gradv) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 111 of file FullNLProblem.cpp.
References forms_, and x.
Referenced by polyfem::solver::NLHomoProblem::gradient(), and polyfem::solver::NLProblem::gradient().
hessian()
void polyfem::solver::FullNLProblem::hessian (const TVector & x, THessian & hessian) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 124 of file FullNLProblem.cpp.
References forms_, hessian(), and x.
Referenced by hessian(), polyfem::solver::NLHomoProblem::hessian(), and polyfem::solver::NLProblem::hessian().
init()
void polyfem::solver::FullNLProblem::init (const TVector & x0) override virtual
Reimplemented in polyfem::solver::NLHomoProblem.
Definition at line 25 of file FullNLProblem.cpp.
References forms_, and x.
Referenced by polyfem::solver::NLHomoProblem::init(), polyfem::solver::ALSolver::solve_al(), polyfem::solver::ALSolver::solve_reduced(), and polyfem::State::solve_tensor_nonlinear().
init_lagging()
void polyfem::solver::FullNLProblem::init_lagging (const TVector & x) virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 37 of file FullNLProblem.cpp.
References forms_, and x.
Referenced by polyfem::solver::NLProblem::init_lagging().
is_step_collision_free()
bool polyfem::solver::FullNLProblem::is_step_collision_free (const TVector & x0, const TVector & x1) virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 94 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::solver::NLProblem::is_step_collision_free().
is_step_valid()
bool polyfem::solver::FullNLProblem::is_step_valid (const TVector & x0, const TVector & x1) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 86 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::solver::NLProblem::is_step_valid().
line_search_begin()
void polyfem::solver::FullNLProblem::line_search_begin (const TVector & x0, const TVector & x1) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 65 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::solver::NLProblem::line_search_begin().
line_search_end()
void polyfem::solver::FullNLProblem::line_search_end () override virtual
Reimplemented in polyfem::solver::AdjointNLProblem.
Definition at line 71 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::solver::ALSolver::solve_al(), and polyfem::solver::ALSolver::solve_reduced().
max_lagging_iterations()
int polyfem::solver::FullNLProblem::max_lagging_iterations () const
Definition at line 49 of file FullNLProblem.cpp.
References forms_, and max_lagging_iterations().
Referenced by max_lagging_iterations(), and polyfem::State::solve_tensor_nonlinear().
max_step_size()
double polyfem::solver::FullNLProblem::max_step_size (const TVector & x0, const TVector & x1) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 77 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::solver::NLProblem::max_step_size().
normalize_forms()
double polyfem::solver::FullNLProblem::normalize_forms () virtual
Reimplemented in polyfem::solver::NLProblem.
Definition at line 11 of file FullNLProblem.cpp.
References forms_, and polyfem::logger().
post_step()
void polyfem::solver::FullNLProblem::post_step (const polysolve::nonlinear::PostStepData & data) override virtual
Reimplemented in polyfem::solver::AdjointNLProblem, polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 143 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::solver::NLProblem::post_step().
set_project_to_psd()
void polyfem::solver::FullNLProblem::set_project_to_psd (bool val) override virtual
Definition at line 31 of file FullNLProblem.cpp.
References forms_.
solution_changed()
void polyfem::solver::FullNLProblem::solution_changed (const TVector & new_x) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 137 of file FullNLProblem.cpp.
References forms_, and x.
Referenced by polyfem::solver::NLProblem::solution_changed().
stop()
virtual bool polyfem::solver::FullNLProblem::stop (const TVector & x) inline override virtual
Reimplemented in polyfem::solver::AdjointNLProblem.
Definition at line 41 of file FullNLProblem.hpp.
update_lagging()
void polyfem::solver::FullNLProblem::update_lagging (const TVector & x, const int iter_num) virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 43 of file FullNLProblem.cpp.
References forms_, and x.
Referenced by polyfem::solver::NLProblem::update_lagging().
uses_lagging()
bool polyfem::solver::FullNLProblem::uses_lagging () const
Definition at line 57 of file FullNLProblem.cpp.
References forms_.
Referenced by polyfem::State::solve_tensor_nonlinear().
value()
double polyfem::solver::FullNLProblem::value (const TVector & x) override virtual
Reimplemented in polyfem::solver::NLHomoProblem, and polyfem::solver::NLProblem.
Definition at line 102 of file FullNLProblem.cpp.
References forms_, val, and x.
Referenced by polyfem::solver::NLHomoProblem::value(), and polyfem::solver::NLProblem::value().
Member Data Documentation
forms_
std::vector<std::shared_ptr<Form> > polyfem::solver::FullNLProblem::forms_ protected
Definition at line 52 of file FullNLProblem.hpp.
Referenced by finish(), forms(), gradient(), hessian(), init(), init_lagging(), is_step_collision_free(), is_step_valid(), line_search_begin(), line_search_end(), max_lagging_iterations(), max_step_size(), normalize_forms(), post_step(), set_project_to_psd(), solution_changed(), update_lagging(), polyfem::solver::NLProblem::update_quantities(), uses_lagging(), and value().
The documentation for this class was generated from the following files:
src/polyfem/solver/FullNLProblem.hpp
src/polyfem/solver/FullNLProblem.cpp