PolyFEM: polyfem::varform::ElasticVarForm Class Reference
polyfem::varform::ElasticVarForm Class Reference
#include <ElasticVarForm.hpp>
Public Member Functions
void init (const std::string &formulation, const Units &units, const json &args, const std::string &out_path) override
Initialize the variational formulation with the given parameters.
void save_json (const Eigen::MatrixXd &solution, std::ostream &out) const override
Save the solution to a JSON file, for output purposes.
void export_data (const Eigen::MatrixXd &solution) const override
io::OutputSpace output_space () const override
Get the output space of the variational formulation, for output purposes.
io::OutStatsData compute_errors (const Eigen::MatrixXd &solution) override
Get the error statistics of the variational formulation, for output purposes.
Public Member Functions inherited from polyfem::varform::VarForm
virtual ~VarForm ()=default
virtual std::string name () const =0
Get the name of the variational formulation.
void set_args (const json &args)
Reset the internal state of the variational formulation, e.g.
void set_mesh (std::unique_ptr< mesh::Mesh > mesh, const double loading_mesh_time=0)
Set the mesh for the variational formulation.
void solve (Eigen::MatrixXd &sol)
Solve the variational formulation and store the solution in the given matrix.
void set_time_callback (const std::function< void(int, int, double, double)> &callback)
int problem_dimension () const
Get the problem dimension of the variational formulation, for output purposes.
virtual bool is_contact_enabled () const
Check if contact is enabled for the variational formulation, for output purposes.
virtual std::vector< io::OutputField > output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options) const =0
Get the output fields of the variational formulation, for output purposes.
const io::OutRuntimeData & output_timings () const
Get the runtime timings of the variational formulation, for output purposes.
void save_json (const Eigen::MatrixXd &solution) const
Save the solution to a JSON file, for output purposes.
Protected Member Functions
void reset () override
void load_mesh (const mesh::Mesh &mesh, const json &args) override
void build_basis (mesh::Mesh &mesh, const bool iso_parametric, const json &args) override
void assemble_rhs (const mesh::Mesh &mesh) override
void assemble_mass_mat (const mesh::Mesh &mesh, const json &args) override
void build_rhs_assembler () override
void initial_velocity (Eigen::MatrixXd &velocity) const
void initial_acceleration (Eigen::MatrixXd &acceleration) const
void initial_elastic_solution (Eigen::MatrixXd &solution) const
QuadratureOrders elastic_boundary_samples () const
std::vector< int > elastic_primitive_to_node () const
std::vector< int > elastic_node_to_primitive () const
void build_mesh_matrices (Eigen::MatrixXd &V, Eigen::MatrixXi &F) const
void save_elastic_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator) const
std::vector< io::OutputField > elastic_output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options, const mesh::Obstacle *obstacle, const time_integrator::ImplicitTimeIntegrator *time_integrator, const std::vector< std::pair< std::string, std::shared_ptr< solver::Form > > > &named_forms, const solver::Form *elastic_form, const solver::ContactForm *contact_form=nullptr) const
void append_primary_output_fields (std::vector< io::OutputField > &fields, const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options, const mesh::Obstacle *obstacle=nullptr) const
Eigen::MatrixXd displaced_output_normals (const io::OutputSample &sample, const Eigen::MatrixXd &solution) const
virtual int n_obstacle_vertices () const
Protected Member Functions inherited from polyfem::varform::VarForm
std::string resolve_output_path (const std::string &path) const
std::string resolve_input_path (const std::string &path, const bool only_if_exists=false) const
void set_materials (assembler::Assembler &assembler, const int size) const
void assign_discr_orders (const json &discr_order, const mesh::Mesh &mesh, Eigen::VectorXi &disc_orders)
virtual void solve_problem (Eigen::MatrixXd &sol)=0
void prepare ()
QuadratureOrders n_boundary_samples (const int discr_order, const int gdiscr_order) const
void build_fe_space (mesh::Mesh &mesh, const bool iso_parametric, const Eigen::VectorXi &disc_orders, const std::string &basis_type, const std::string &poly_basis_type, const assembler::Assembler &space_assembler, const int value_dim, const int quadrature_order, const int mass_quadrature_order, const bool use_corner_quadrature, const int n_harmonic_samples, const int integral_constraints, FESpace &space, VarFormBoundaryState &boundary, std::shared_ptr< GeometryMapping > geometry=nullptr)
std::shared_ptr< time_integrator::BDF > make_bdf_time_integrator () const
void save_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator, const bool rest_mesh_written=false) const
void ensure_output_sampler () const
void save_restart_json (const double t0, const double dt, const int t, const bool rest_mesh_written) const
void save_timestep (const double time, const int t, const double t0, const double dt, const Eigen::MatrixXd &solution) const
void save_subsolve (const int i, const int t, const Eigen::MatrixXd &solution) const
int output_file_index (const int t) const
void notify_time_step (const int t, const int time_steps, const double t0, const double dt) const
io::OutGeometryData::ExportOptions export_options (const io::OutputSpace &space) const
io::OutputFieldFunction output_field_function (const Eigen::MatrixXd &solution, const io::OutGeometryData::ExportOptions &opts) const
Protected Attributes
FESpace space_
VarFormBoundaryState boundary_
assembler::AssemblyValsCache ass_vals_cache_
assembler::AssemblyValsCache mass_ass_vals_cache_
assembler::AssemblyValsCache pure_mass_ass_vals_cache_
std::shared_ptr< assembler::RhsAssembler > rhs_assembler_
StiffnessMatrix mass_
StiffnessMatrix pure_mass_
double avg_mass_ = 0
Eigen::MatrixXd rhs_
std::shared_ptr< assembler::Assembler > primary_assembler_ = nullptr
std::shared_ptr< assembler::Mass > mass_assembler_ = nullptr
std::shared_ptr< assembler::HRZMass > pure_mass_assembler_ = nullptr
double t0 = 0
int time_steps = 0
double dt = 0
Protected Attributes inherited from polyfem::varform::VarForm
std::shared_ptr< assembler::Problem > problem
current problem, it contains rhs and bc
Units units
json args
io::OutStatsData stats
io::OutRuntimeData timings
runtime statistics
std::string root_path
std::string output_path
std::unique_ptr< mesh::Mesh > mesh_
std::function< void(int, int, double, double)> time_callback
io::OutGeometryData output_geometry_
bool output_sampler_initialized_ = false
bool prepared_ = false
Friends
class polyfem::test::VarFormTestAccess
Additional Inherited Members
Static Protected Member Functions inherited from polyfem::varform::VarForm
static bool read_initial_x_from_file (const std::string &state_path, const std::string &x_name, const bool reorder, const Eigen::VectorXi &in_node_to_node, const int dim, Eigen::MatrixXd &x)
static void rebuild_node_positions (const std::vector< basis::ElementBases > &bases, const std::vector< int > &node_ids, std::vector< RowVectorNd > &positions)
Detailed Description
Definition at line 23 of file ElasticVarForm.hpp.
Member Function Documentation
append_primary_output_fields()
void polyfem::varform::ElasticVarForm::append_primary_output_fields (std::vector< io::OutputField > & fields, const io::OutputSample & sample, const Eigen::MatrixXd & solution, const io::OutputFieldOptions & options, const mesh::Obstacle * obstacle = nullptr) const protected
Definition at line 974 of file ElasticVarForm.cpp.
References polyfem::io::OutputSample::element_ids, polyfem::io::OutputFieldOptions::export_field(), polyfem::io::OutputFieldOptions::fields, polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::io::OutputSample::local_points, polyfem::mesh::Obstacle::n_vertices(), polyfem::mesh::Obstacle::ndof(), polyfem::io::OutputSample::node_ids, polyfem::io::OutputField::Point, polyfem::io::OutputSample::points, space_, polyfem::utils::unflatten(), and polyfem::mesh::Obstacle::v().
assemble_mass_mat()
void polyfem::varform::ElasticVarForm::assemble_mass_mat (const mesh::Mesh & mesh, const json & args) override protected virtual
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm.
Definition at line 282 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::io::OutRuntimeData::assembling_mass_mat_time, avg_mass_, polyfem::varform::FESpace::basis_list(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::utils::lump_matrix(), mass_, mass_ass_vals_cache_, mass_assembler_, polyfem::io::OutStatsData::mat_size, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::nn_zero, polyfem::io::OutStatsData::num_dofs, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_, pure_mass_ass_vals_cache_, pure_mass_assembler_, space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
assemble_rhs()
void polyfem::varform::ElasticVarForm::assemble_rhs (const mesh::Mesh & mesh) override protected virtual
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm.
Definition at line 251 of file ElasticVarForm.cpp.
References polyfem::io::OutRuntimeData::assigning_rhs_time, polyfem::mesh::Mesh::bounding_box(), build_rhs_assembler(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), mass_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, rhs_, rhs_assembler_, polyfem::varform::VarForm::root_path, and polyfem::varform::VarForm::timings.
Referenced by polyfem::varform::IncompressibleElasticVarForm::assemble_rhs().
build_basis()
void polyfem::varform::ElasticVarForm::build_basis (mesh::Mesh & mesh, const bool iso_parametric, const json & args) override protected virtual
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm, and polyfem::varform::NonlinearElasticVarForm.
Definition at line 144 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, ass_vals_cache_, polyfem::varform::VarForm::assign_discr_orders(), polyfem::varform::FESpace::basis_list(), boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, polyfem::varform::VarForm::build_fe_space(), polyfem::varform::VarFormBoundaryState::clear_boundary_conditions(), polyfem::io::OutStatsData::compute_mesh_size(), polyfem::io::OutStatsData::count_flipped_elements(), polyfem::mesh::Mesh::dimension(), polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::geometry_basis_list(), polyfem::assembler::AssemblyValsCache::init(), polyfem::assembler::AssemblyValsCache::init_empty(), polyfem::mesh::Mesh::is_volume(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::varform::VarFormBoundaryState::local_pressure_boundary, polyfem::varform::VarFormBoundaryState::local_pressure_cavity, polyfem::logger(), mass_ass_vals_cache_, mass_assembler_, polyfem::io::OutStatsData::mesh_size, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::n_flipped, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, polyfem::refinement::APriori::p_refine(), primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_ass_vals_cache_, pure_mass_assembler_, polyfem::varform::VarForm::rebuild_node_positions(), space_, polyfem::varform::FESpace::space_in_node_to_node, polyfem::varform::VarForm::stats, polyfem::varform::VarFormBoundaryState::total_local_boundary, and polyfem::mesh::Mesh::update_nodes().
Referenced by polyfem::varform::IncompressibleElasticVarForm::build_basis().
build_mesh_matrices()
void polyfem::varform::ElasticVarForm::build_mesh_matrices (Eigen::MatrixXd & V, Eigen::MatrixXi & F) const protected
Definition at line 1282 of file ElasticVarForm.cpp.
References polyfem::basis::ElementBases::bases, polyfem::F, space_, and V.
build_rhs_assembler()
void polyfem::varform::ElasticVarForm::build_rhs_assembler () override protected virtual
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm, and polyfem::varform::NonlinearElasticVarForm.
Definition at line 235 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), boundary_, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::geometry_basis_list(), mass_ass_vals_cache_, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, primary_assembler_, polyfem::varform::VarForm::problem, rhs_assembler_, and space_.
Referenced by assemble_rhs().
compute_errors()
io::OutStatsData polyfem::varform::ElasticVarForm::compute_errors (const Eigen::MatrixXd & solution) override virtual
Get the error statistics of the variational formulation, for output purposes.
Returns
Error statistics
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm.
Definition at line 1130 of file ElasticVarForm.cpp.
References space_.
displaced_output_normals()
Eigen::MatrixXd polyfem::varform::ElasticVarForm::displaced_output_normals (const io::OutputSample & sample, const Eigen::MatrixXd & solution) const protected
Definition at line 1072 of file ElasticVarForm.cpp.
References polyfem::io::OutputSample::element_ids, polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::io::OutputSample::local_points, polyfem::io::OutputSample::normals, and space_.
elastic_boundary_samples()
QuadratureOrders polyfem::varform::ElasticVarForm::elastic_boundary_samples () const protected
Definition at line 376 of file ElasticVarForm.cpp.
References polyfem::varform::FESpace::disc_orders, polyfem::varform::VarForm::mesh_, polyfem::varform::VarForm::n_boundary_samples(), and space_.
Referenced by polyfem::varform::LinearElasticVarForm::init_linear_solve(), polyfem::varform::IncompressibleElasticVarForm::solve_static_linear(), polyfem::varform::LinearElasticVarForm::solve_static_linear(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
elastic_node_to_primitive()
std::vector< int > polyfem::varform::ElasticVarForm::elastic_node_to_primitive () const protected
Definition at line 397 of file ElasticVarForm.cpp.
References elastic_primitive_to_node(), polyfem::varform::FESpace::geometry, and space_.
elastic_output_fields()
std::vector< io::OutputField > polyfem::varform::ElasticVarForm::elastic_output_fields (const io::OutputSample & sample, const Eigen::MatrixXd & solution, const io::OutputFieldOptions & options, const mesh::Obstacle * obstacle, const time_integrator::ImplicitTimeIntegrator * time_integrator, const std::vector< std::pair< std::string, std::shared_ptr< solver::Form > > > & named_forms, const solver::Form * elastic_form, const solver::ContactForm * contact_form = nullptr) const protected
Definition at line 410 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::io::OutputSample::element_ids, polyfem::io::OutputFieldOptions::fields, polyfem::varform::FESpace::geometry_basis_list(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::io::OutputSample::local_points, polyfem::varform::VarForm::mesh_, polyfem::mesh::Obstacle::n_vertices(), polyfem::varform::VarForm::name(), polyfem::mesh::Obstacle::ndof(), polyfem::io::OutputSample::node_ids, polyfem::io::OutputField::Point, polyfem::io::OutputSample::points, polyfem::varform::VarForm::problem, space_, polyfem::utils::unflatten(), and polyfem::mesh::Obstacle::v().
Referenced by polyfem::varform::IncompressibleElasticVarForm::output_fields(), polyfem::varform::LinearElasticVarForm::output_fields(), and polyfem::varform::NonlinearElasticVarForm::output_fields().
elastic_primitive_to_node()
std::vector< int > polyfem::varform::ElasticVarForm::elastic_primitive_to_node () const protected
Definition at line 383 of file ElasticVarForm.cpp.
References polyfem::varform::FESpace::geometry, polyfem::varform::FESpace::is_iso_parametric(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::mesh_nodes, and space_.
Referenced by elastic_node_to_primitive().
export_data()
void polyfem::varform::ElasticVarForm::export_data (const Eigen::MatrixXd & solution) const override virtual
Implements polyfem::varform::VarForm.
Definition at line 1143 of file ElasticVarForm.cpp.
References polyfem::io::Evaluator::compute_stress_at_quadrature_points(), polyfem::logger(), polyfem::io::OutputSpace::mesh, space_, polyfem::utils::unflatten(), and polyfem::io::write_matrix().
init()
void polyfem::varform::ElasticVarForm::init (const std::string & formulation, const Units & units, const json & args, const std::string & out_path) override virtual
Initialize the variational formulation with the given parameters.
Parameters
formulation name of the variational formulation
units unit system to use for the formulation
args json input arguments, used to initialize the formulation
out_path output path for the formulation, used to save intermediate data
Reimplemented from polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm, and polyfem::varform::NonlinearElasticVarForm.
Definition at line 62 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, dt, polyfem::problem::ProblemFactory::factory(), polyfem::problem::ProblemFactory::get_problem(), polyfem::varform::VarForm::init(), polyfem::assembler::AssemblerUtils::make_assembler(), mass_assembler_, primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_assembler_, polyfem::varform::VarForm::root_path, t0, time_steps, and polyfem::varform::VarForm::units.
Referenced by polyfem::varform::IncompressibleElasticVarForm::init(), and polyfem::varform::NonlinearElasticVarForm::init().
initial_acceleration()
void polyfem::varform::ElasticVarForm::initial_acceleration (Eigen::MatrixXd & acceleration) const protected
Definition at line 342 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::VarForm::mesh_, polyfem::varform::VarForm::read_initial_x_from_file(), polyfem::varform::VarForm::resolve_input_path(), rhs_assembler_, space_, and polyfem::varform::FESpace::space_in_node_to_node.
Referenced by polyfem::varform::LinearElasticVarForm::init_linear_solve().
initial_elastic_solution()
void polyfem::varform::ElasticVarForm::initial_elastic_solution (Eigen::MatrixXd & solution) const protected
Definition at line 355 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::VarForm::mesh_, polyfem::varform::VarForm::problem, polyfem::varform::VarForm::read_initial_x_from_file(), polyfem::varform::VarForm::resolve_input_path(), rhs_, rhs_assembler_, space_, and polyfem::varform::FESpace::space_in_node_to_node.
Referenced by polyfem::varform::LinearElasticVarForm::init_linear_solve(), polyfem::varform::IncompressibleElasticVarForm::prepare_initial_solution(), and polyfem::varform::LinearElasticVarForm::solve_problem().
initial_velocity()
void polyfem::varform::ElasticVarForm::initial_velocity (Eigen::MatrixXd & velocity) const protected
Definition at line 329 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::VarForm::mesh_, polyfem::varform::VarForm::read_initial_x_from_file(), polyfem::varform::VarForm::resolve_input_path(), rhs_assembler_, space_, and polyfem::varform::FESpace::space_in_node_to_node.
Referenced by polyfem::varform::LinearElasticVarForm::init_linear_solve().
load_mesh()
void polyfem::varform::ElasticVarForm::load_mesh (const mesh::Mesh & mesh, const json & args) override protected virtual
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm, and polyfem::varform::NonlinearElasticVarForm.
Definition at line 118 of file ElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::mesh::Mesh::dimension(), polyfem::mesh::Mesh::get_body_id(), mass_assembler_, polyfem::mesh::Mesh::n_elements(), primary_assembler_, polyfem::varform::VarForm::problem, pure_mass_assembler_, and polyfem::varform::VarForm::set_materials().
Referenced by polyfem::varform::IncompressibleElasticVarForm::load_mesh(), and polyfem::varform::NonlinearElasticVarForm::load_mesh().
n_obstacle_vertices()
virtual int polyfem::varform::ElasticVarForm::n_obstacle_vertices () const inline protected virtual
Reimplemented in polyfem::varform::NonlinearElasticVarForm.
Definition at line 74 of file ElasticVarForm.hpp.
output_space()
io::OutputSpace polyfem::varform::ElasticVarForm::output_space () const override virtual
Get the output space of the variational formulation, for output purposes.
Returns
Output space
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::NonlinearElasticVarForm.
Definition at line 1105 of file ElasticVarForm.cpp.
References space_.
Referenced by polyfem::varform::NonlinearElasticVarForm::output_space().
reset()
void polyfem::varform::ElasticVarForm::reset () override protected virtual
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm, polyfem::varform::LinearElasticVarForm, and polyfem::varform::NonlinearElasticVarForm.
Definition at line 41 of file ElasticVarForm.cpp.
References ass_vals_cache_, avg_mass_, boundary_, dt, polyfem::assembler::AssemblyValsCache::init_empty(), mass_, mass_ass_vals_cache_, mass_assembler_, primary_assembler_, pure_mass_, pure_mass_ass_vals_cache_, pure_mass_assembler_, polyfem::varform::FESpace::reset(), polyfem::varform::VarFormBoundaryState::reset(), polyfem::varform::VarForm::reset(), rhs_, rhs_assembler_, space_, t0, and time_steps.
Referenced by polyfem::varform::IncompressibleElasticVarForm::reset(), polyfem::varform::LinearElasticVarForm::reset(), and polyfem::varform::NonlinearElasticVarForm::reset().
save_elastic_step_state()
void polyfem::varform::ElasticVarForm::save_elastic_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator * time_integrator) const protected
Definition at line 1256 of file ElasticVarForm.cpp.
References polyfem::F, V, and polyfem::io::MshWriter::write().
Referenced by polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
save_json()
void polyfem::varform::ElasticVarForm::save_json (const Eigen::MatrixXd & solution, std::ostream & out) const override virtual
Save the solution to a JSON file, for output purposes.
Parameters
solution Solution matrix to save
out Output stream to save the solution
Implements polyfem::varform::VarForm.
Reimplemented in polyfem::varform::IncompressibleElasticVarForm.
Definition at line 1227 of file ElasticVarForm.cpp.
References polyfem::logger(), and space_.
Friends And Related Symbol Documentation
polyfem::test::VarFormTestAccess
friend class polyfem::test::VarFormTestAccess friend
Definition at line 25 of file ElasticVarForm.hpp.
Member Data Documentation
ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::ElasticVarForm::ass_vals_cache_ protected
Definition at line 79 of file ElasticVarForm.hpp.
Referenced by build_basis(), polyfem::varform::IncompressibleElasticVarForm::build_stiffness_mat(), polyfem::varform::LinearElasticVarForm::build_stiffness_mat(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), and reset().
avg_mass_
double polyfem::varform::ElasticVarForm::avg_mass_ = 0 protected
Definition at line 88 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), polyfem::varform::IncompressibleElasticVarForm::assemble_mass_mat(), and reset().
boundary_
VarFormBoundaryState polyfem::varform::ElasticVarForm::boundary_ protected
Definition at line 77 of file ElasticVarForm.hpp.
Referenced by build_basis(), polyfem::varform::IncompressibleElasticVarForm::build_basis(), build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_rhs_assembler(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), reset(), polyfem::varform::IncompressibleElasticVarForm::solve_linear_system(), polyfem::varform::LinearElasticVarForm::solve_linear_system(), polyfem::varform::IncompressibleElasticVarForm::solve_static_linear(), polyfem::varform::LinearElasticVarForm::solve_static_linear(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
dt
double polyfem::varform::ElasticVarForm::dt = 0 protected
Definition at line 97 of file ElasticVarForm.hpp.
Referenced by init(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), reset(), polyfem::varform::LinearElasticVarForm::solve_problem(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
mass_
StiffnessMatrix polyfem::varform::ElasticVarForm::mass_ protected
Definition at line 85 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), polyfem::varform::IncompressibleElasticVarForm::assemble_mass_mat(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), reset(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
mass_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::ElasticVarForm::mass_ass_vals_cache_ protected
Definition at line 80 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), polyfem::varform::IncompressibleElasticVarForm::assemble_mass_mat(), build_basis(), build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_rhs_assembler(), and reset().
mass_assembler_
std::shared_ptr<assembler::Mass> polyfem::varform::ElasticVarForm::mass_assembler_ = nullptr protected
Definition at line 92 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), polyfem::varform::IncompressibleElasticVarForm::assemble_mass_mat(), assemble_rhs(), build_basis(), init(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), load_mesh(), reset(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
primary_assembler_
std::shared_ptr<assembler::Assembler> polyfem::varform::ElasticVarForm::primary_assembler_ = nullptr protected
Definition at line 91 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), assemble_rhs(), build_basis(), polyfem::varform::IncompressibleElasticVarForm::build_basis(), build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_stiffness_mat(), polyfem::varform::LinearElasticVarForm::build_stiffness_mat(), init(), polyfem::varform::IncompressibleElasticVarForm::init(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), load_mesh(), reset(), polyfem::varform::IncompressibleElasticVarForm::save_json(), polyfem::varform::LinearElasticVarForm::solve_linear_system(), polyfem::varform::IncompressibleElasticVarForm::solve_problem(), and polyfem::varform::LinearElasticVarForm::solve_problem().
pure_mass_
StiffnessMatrix polyfem::varform::ElasticVarForm::pure_mass_ protected
Definition at line 86 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), and reset().
pure_mass_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::ElasticVarForm::pure_mass_ass_vals_cache_ protected
Definition at line 81 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), build_basis(), and reset().
pure_mass_assembler_
std::shared_ptr<assembler::HRZMass> polyfem::varform::ElasticVarForm::pure_mass_assembler_ = nullptr protected
Definition at line 93 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), build_basis(), init(), load_mesh(), and reset().
rhs_
Eigen::MatrixXd polyfem::varform::ElasticVarForm::rhs_ protected
Definition at line 89 of file ElasticVarForm.hpp.
Referenced by assemble_rhs(), polyfem::varform::IncompressibleElasticVarForm::assemble_rhs(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), initial_elastic_solution(), reset(), polyfem::varform::IncompressibleElasticVarForm::solve_static_linear(), polyfem::varform::LinearElasticVarForm::solve_static_linear(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
rhs_assembler_
std::shared_ptr<assembler::RhsAssembler> polyfem::varform::ElasticVarForm::rhs_assembler_ protected
Definition at line 83 of file ElasticVarForm.hpp.
Referenced by assemble_rhs(), build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_rhs_assembler(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), initial_acceleration(), initial_elastic_solution(), initial_velocity(), reset(), polyfem::varform::LinearElasticVarForm::solve_linear_system(), polyfem::varform::IncompressibleElasticVarForm::solve_static_linear(), polyfem::varform::LinearElasticVarForm::solve_static_linear(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
space_
FESpace polyfem::varform::ElasticVarForm::space_ protected
Definition at line 76 of file ElasticVarForm.hpp.
Referenced by assemble_mass_mat(), polyfem::varform::IncompressibleElasticVarForm::assemble_mass_mat(), build_basis(), polyfem::varform::IncompressibleElasticVarForm::build_basis(), build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_rhs_assembler(), polyfem::varform::IncompressibleElasticVarForm::build_stiffness_mat(), polyfem::varform::LinearElasticVarForm::build_stiffness_mat(), polyfem::varform::IncompressibleElasticVarForm::compute_errors(), elastic_boundary_samples(), elastic_node_to_primitive(), elastic_output_fields(), elastic_primitive_to_node(), polyfem::varform::LinearElasticVarForm::init_linear_solve(), initial_acceleration(), initial_elastic_solution(), initial_velocity(), polyfem::varform::IncompressibleElasticVarForm::output_fields(), polyfem::varform::IncompressibleElasticVarForm::primary_ndof(), reset(), polyfem::varform::IncompressibleElasticVarForm::save_json(), and polyfem::varform::LinearElasticVarForm::solve_linear_system().
t0
double polyfem::varform::ElasticVarForm::t0 = 0 protected
Definition at line 95 of file ElasticVarForm.hpp.
Referenced by init(), reset(), polyfem::varform::LinearElasticVarForm::solve_problem(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
time_steps
int polyfem::varform::ElasticVarForm::time_steps = 0 protected
Definition at line 96 of file ElasticVarForm.hpp.
Referenced by init(), reset(), polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear(), and polyfem::varform::LinearElasticVarForm::solve_transient_linear().
The documentation for this class was generated from the following files:
src/polyfem/varforms/ElasticVarForm.hpp
src/polyfem/varforms/ElasticVarForm.cpp