PolyFEM: cppoptlib::SparseNewtonDescentSolver< ProblemType > Class Template Reference
cppoptlib::SparseNewtonDescentSolver< ProblemType > Class Template Reference
#include <SparseNewtonDescentSolver.hpp>
Public Types
using Superclass = NonlinearSolver< ProblemType >
Public Types inherited from cppoptlib::NonlinearSolver< ProblemType >
enum class ErrorCode { NanEncountered = -10 , StepTooSmall = -1 , Success = 0 }
using Superclass = ISolver< ProblemType, -1 >
Public Member Functions
SparseNewtonDescentSolver (const json &solver_params, const std::string &linear_solver_type, const std::string &linear_precond_type)
std::string name () const override
Public Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
NonlinearSolver (const json &solver_params)
virtual std::string name () const =0
void setLineSearch (const std::string &line_search_name)
void minimize (ProblemType &objFunc, TVector &x)
double line_search (const TVector &x, const TVector &delta_x, ProblemType &objFunc)
void getInfo (json &params)
ErrorCode error_code () const
Protected Member Functions
virtual int default_descent_strategy () override
std::string descent_strategy_name (int descent_strategy) const override
void increase_descent_strategy () override
Protected Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
virtual void reset (const ProblemType &objFunc, const TVector &x)
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x_vec, const TVector &grad, TVector &direction)=0
virtual int default_descent_strategy ()=0
virtual void increase_descent_strategy ()=0
virtual std::string descent_strategy_name (int descent_strategy) const =0
virtual std::string descent_strategy_name () const
void reset_times ()
virtual void update_solver_info ()
void log_times ()
Private Member Functions
void reset (const ProblemType &objFunc, const TVector &x) override
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x, const TVector &grad, TVector &direction) override
void update_solver_info () override
Static Private Member Functions
static bool has_hessian_nans (const polyfem::StiffnessMatrix &hessian)
Private Attributes
std::unique_ptr< polysolve::LinearSolver > linear_solver
const std::string linear_solver_type
const std::string linear_precond_type
json internal_solver_info = json::array()
polyfem::StiffnessMatrix hessian
double reg_weight = 0
Static Private Attributes
static constexpr double reg_weight_min = 1e-8
static constexpr double reg_weight_max = 1e8
static constexpr double reg_weight_inc = 10
static constexpr double reg_weight_dec = 2
Additional Inherited Members
Protected Attributes inherited from cppoptlib::NonlinearSolver< ProblemType >
const json solver_params
std::shared_ptr< polyfem::solver::line_search::LineSearch< ProblemType > > m_line_search
int descent_strategy
ErrorCode m_error_code
bool use_gradient_norm
bool normalize_gradient
double use_grad_norm_tol
json solver_info
double total_time
double grad_time
double assembly_time
double inverting_time
double line_search_time
double constraint_set_update_time
double obj_fun_time
Detailed Description
template<typename ProblemType>
class cppoptlib::SparseNewtonDescentSolver< ProblemType >
Definition at line 14 of file SparseNewtonDescentSolver.hpp.
Member Typedef Documentation
Superclass
template<typename ProblemType > using cppoptlib::SparseNewtonDescentSolver< ProblemType >::Superclass = NonlinearSolver<ProblemType>
Definition at line 17 of file SparseNewtonDescentSolver.hpp.
Constructor & Destructor Documentation
SparseNewtonDescentSolver()
template<typename ProblemType > cppoptlib::SparseNewtonDescentSolver< ProblemType >::SparseNewtonDescentSolver (const json & solver_params, const std::string & linear_solver_type, const std::string & linear_precond_type) inline
Definition at line 21 of file SparseNewtonDescentSolver.hpp.
Member Function Documentation
compute_update_direction()
template<typename ProblemType > virtual bool cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction (ProblemType & objFunc, const TVector & x, const TVector & grad, TVector & direction) inline override private virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 88 of file SparseNewtonDescentSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::assembly_time, cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::SparseNewtonDescentSolver< ProblemType >::hessian, cppoptlib::SparseNewtonDescentSolver< ProblemType >::increase_descent_strategy(), cppoptlib::NonlinearSolver< ProblemType >::inverting_time, cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_solver, polyfem::logger(), p_bases::norm, POLYFEM_SCOPED_TIMER, cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight, polyfem::utils::sparse_identity(), and x.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction().
default_descent_strategy()
template<typename ProblemType > virtual int cppoptlib::SparseNewtonDescentSolver< ProblemType >::default_descent_strategy () inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 34 of file SparseNewtonDescentSolver.hpp.
descent_strategy_name()
template<typename ProblemType > std::string cppoptlib::SparseNewtonDescentSolver< ProblemType >::descent_strategy_name (int descent_strategy) const inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 36 of file SparseNewtonDescentSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, and cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight.
has_hessian_nans()
template<typename ProblemType > static bool cppoptlib::SparseNewtonDescentSolver< ProblemType >::has_hessian_nans (const polyfem::StiffnessMatrix & hessian) inline static private
Definition at line 197 of file SparseNewtonDescentSolver.hpp.
References cppoptlib::SparseNewtonDescentSolver< ProblemType >::hessian.
increase_descent_strategy()
template<typename ProblemType > void cppoptlib::SparseNewtonDescentSolver< ProblemType >::increase_descent_strategy () inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 53 of file SparseNewtonDescentSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight, and cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight_max.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction().
name()
template<typename ProblemType > std::string cppoptlib::SparseNewtonDescentSolver< ProblemType >::name () const inline override virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 31 of file SparseNewtonDescentSolver.hpp.
reset()
template<typename ProblemType > void cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset (const ProblemType & objFunc, const TVector & x) inline override private virtual
Reimplemented from cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 78 of file SparseNewtonDescentSolver.hpp.
References cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_precond_type, cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_solver, cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_solver_type, cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight, cppoptlib::NonlinearSolver< ProblemType >::reset(), cppoptlib::NonlinearSolver< ProblemType >::solver_params, and x.
update_solver_info()
template<typename ProblemType > void cppoptlib::SparseNewtonDescentSolver< ProblemType >::update_solver_info () inline override private virtual
Reimplemented from cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 189 of file SparseNewtonDescentSolver.hpp.
References cppoptlib::SparseNewtonDescentSolver< ProblemType >::internal_solver_info, cppoptlib::NonlinearSolver< ProblemType >::solver_info, and cppoptlib::NonlinearSolver< ProblemType >::update_solver_info().
Member Data Documentation
hessian
template<typename ProblemType > polyfem::StiffnessMatrix cppoptlib::SparseNewtonDescentSolver< ProblemType >::hessian private
Definition at line 69 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::has_hessian_nans().
internal_solver_info
template<typename ProblemType > json cppoptlib::SparseNewtonDescentSolver< ProblemType >::internal_solver_info = json::array() private
Definition at line 67 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::update_solver_info().
linear_precond_type
template<typename ProblemType > const std::string cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_precond_type private
Definition at line 65 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset().
linear_solver
template<typename ProblemType > std::unique_ptr<polysolve::LinearSolver> cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_solver private
Definition at line 63 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset().
linear_solver_type
template<typename ProblemType > const std::string cppoptlib::SparseNewtonDescentSolver< ProblemType >::linear_solver_type private
Definition at line 64 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset().
reg_weight
template<typename ProblemType > double cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight = 0 private
Definition at line 72 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::compute_update_direction(), cppoptlib::SparseNewtonDescentSolver< ProblemType >::descent_strategy_name(), cppoptlib::SparseNewtonDescentSolver< ProblemType >::increase_descent_strategy(), and cppoptlib::SparseNewtonDescentSolver< ProblemType >::reset().
reg_weight_dec
template<typename ProblemType > constexpr double cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight_dec = 2 static constexpr private
Definition at line 76 of file SparseNewtonDescentSolver.hpp.
reg_weight_inc
template<typename ProblemType > constexpr double cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight_inc = 10 static constexpr private
Definition at line 75 of file SparseNewtonDescentSolver.hpp.
reg_weight_max
template<typename ProblemType > constexpr double cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight_max = 1e8 static constexpr private
Definition at line 74 of file SparseNewtonDescentSolver.hpp.
Referenced by cppoptlib::SparseNewtonDescentSolver< ProblemType >::increase_descent_strategy().
reg_weight_min
template<typename ProblemType > constexpr double cppoptlib::SparseNewtonDescentSolver< ProblemType >::reg_weight_min = 1e-8 static constexpr private
Definition at line 73 of file SparseNewtonDescentSolver.hpp.
The documentation for this class was generated from the following file:
src/polyfem/solver/SparseNewtonDescentSolver.hpp