PolyFEM: polyfem::utils::TetrahedronClipping Class Reference
polyfem::utils::TetrahedronClipping Class Reference
#include <ClipperUtils.hpp>
Public Types
typedef std::vector< int > Polygon
typedef std::vector< Polygon > Polygons
Public Member Functions
TetrahedronClipping ()=delete
Static Public Member Functions
static std::vector< Eigen::MatrixXd > clip (const Eigen::MatrixXd &subject_tet, const Eigen::MatrixXd &clipping_tet)
Clip a tetrahedron using tetrahedron.
static PolyClipper::Vector3d toPolyClipperVector (const Eigen::Vector3d &v)
static Eigen::Vector3d fromPolyClipperVector (const PolyClipper::Vector3d &v)
Detailed Description
Definition at line 55 of file ClipperUtils.hpp.
Member Typedef Documentation
Polygon
typedef std::vector<int> polyfem::utils::TetrahedronClipping::Polygon
Definition at line 60 of file ClipperUtils.hpp.
Polygons
typedef std::vector<Polygon> polyfem::utils::TetrahedronClipping::Polygons
Definition at line 61 of file ClipperUtils.hpp.
Constructor & Destructor Documentation
TetrahedronClipping()
polyfem::utils::TetrahedronClipping::TetrahedronClipping () delete
Member Function Documentation
clip()
std::vector< Eigen::MatrixXd > polyfem::utils::TetrahedronClipping::clip (const Eigen::MatrixXd & subject_tet, const Eigen::MatrixXd & clipping_tet) static
Clip a tetrahedron using tetrahedron.
Parameters
[in] subject_tet Tetrahedron to clip.
[in] clipping_tet Tetrahedron to clip.
Returns
Tetrahedralization of the clipped (convex) polyhedron. Each entry is a matrix of size 4×3 containing the four vertices of each tetrahedron.
Definition at line 119 of file ClipperUtils.cpp.
References polyfem::assembler::cross(), fromPolyClipperVector(), polyfem::utils::tetrahedron_volume(), and toPolyClipperVector().
Referenced by polyfem::assembler::MassMatrixAssembler::assemble_cross().
fromPolyClipperVector()
Eigen::Vector3d polyfem::utils::TetrahedronClipping::fromPolyClipperVector (const PolyClipper::Vector3d & v) static
Definition at line 231 of file ClipperUtils.cpp.
Referenced by clip().
toPolyClipperVector()
PolyClipper::Vector3d polyfem::utils::TetrahedronClipping::toPolyClipperVector (const Eigen::Vector3d & v) static
Definition at line 226 of file ClipperUtils.cpp.
Referenced by clip().
The documentation for this class was generated from the following files:
src/polyfem/utils/ClipperUtils.hpp
src/polyfem/utils/ClipperUtils.cpp