PolyFEM: polyfem::assembler::HookeLinearElasticity Class Reference
polyfem::assembler::HookeLinearElasticity Class Reference
#include <HookeLinearElasticity.hpp>
Public Member Functions
HookeLinearElasticity ()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > assemble (const LinearAssemblerData &data) const override
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const override
VectorNd compute_rhs (const AutodiffHessianPt &pt) const override
void set_size (const int size) override
void add_multimaterial (const int index, const json &params, const Units &units) override
const ElasticityTensor & elasticity_tensor () const
virtual bool is_linear () const override
std::string name () const override
std::map< std::string, ParamFunc > parameters () const override
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const override
void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const override
virtual Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > assemble (const LinearAssemblerData &data) const=0
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::LinearAssembler
LinearAssembler ()
virtual ~LinearAssembler ()=default
void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const override
virtual bool is_linear () const override
virtual Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > assemble (const LinearAssemblerData &data) const =0
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
virtual std::string name () const =0
int size () const
virtual void set_size (const int size)
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
virtual void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual std::map< std::string, ParamFunc > parameters () const =0
virtual VectorNd compute_rhs (const AutodiffHessianPt &pt) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params, const Units &units)
virtual void add_multimaterial (const int index, const json &params, const Units &units)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_linear () const =0
virtual bool is_solution_displacement () const
virtual bool is_fluid () const
virtual bool is_tensor () const
Private Member Functions
template<typename T >
T compute_energy_aux (const NonLinearAssemblerData &data) const
Private Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual bool is_linear () const override
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Private Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
virtual std::string name () const =0
int size () const
virtual void set_size (const int size)
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
virtual void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual std::map< std::string, ParamFunc > parameters () const =0
virtual VectorNd compute_rhs (const AutodiffHessianPt &pt) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params, const Units &units)
virtual void add_multimaterial (const int index, const json &params, const Units &units)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_linear () const =0
virtual bool is_solution_displacement () const
virtual bool is_fluid () const
virtual bool is_tensor () const
Private Member Functions inherited from polyfem::assembler::ElasticityAssembler
ElasticityAssembler ()
virtual ~ElasticityAssembler ()=default
void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &stresses) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
bool is_solution_displacement () const override
bool is_tensor () const override
virtual void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const =0
Private Attributes
ElasticityTensor elasticity_tensor_
Private Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Additional Inherited Members
Public Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Private Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Detailed Description
Definition at line 11 of file HookeLinearElasticity.hpp.
Constructor & Destructor Documentation
HookeLinearElasticity()
polyfem::assembler::HookeLinearElasticity::HookeLinearElasticity ()
Definition at line 44 of file HookeLinearElasticity.cpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::HookeLinearElasticity::add_multimaterial (const int index, const json & params, const Units & units) override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 48 of file HookeLinearElasticity.cpp.
References elasticity_tensor_, polyfem::assembler::ElasticityTensor::set_from_entries(), polyfem::assembler::ElasticityTensor::set_from_lambda_mu(), polyfem::assembler::ElasticityTensor::set_from_young_poisson(), polyfem::assembler::Assembler::size(), and polyfem::Units::stress().
Referenced by polyfem::assembler::MultiModel::add_multimaterial().
assemble() [1/3]
void polyfem::assembler::LinearAssembler::assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, StiffnessMatrix & stiffness, const bool is_mass = false) const override virtual
Reimplemented from polyfem::assembler::LinearAssembler.
assemble() [2/3]
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > polyfem::assembler::HookeLinearElasticity::assemble (const LinearAssemblerData & data) const override virtual
Implements polyfem::assembler::LinearAssembler.
Definition at line 84 of file HookeLinearElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::ElasticityTensor::compute_stress(), polyfem::assembler::LinearAssemblerData::da, elasticity_tensor_, polyfem::assembler::LinearAssemblerData::i, polyfem::assembler::LinearAssemblerData::j, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::Assembler::size(), and polyfem::assembler::LinearAssemblerData::vals.
assemble() [3/3]
virtual Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > polyfem::assembler::LinearAssembler::assemble (const LinearAssemblerData & data) const virtual
Implements polyfem::assembler::LinearAssembler.
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
Definition at line 244 of file Assembler.cpp.
assemble_gradient() [1/3]
void polyfem::assembler::NLAssembler::assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
assemble_gradient() [2/3]
Eigen::VectorXd polyfem::assembler::HookeLinearElasticity::assemble_gradient (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 296 of file HookeLinearElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::gradient_from_energy(), polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
Referenced by polyfem::assembler::MultiModel::assemble_gradient().
assemble_gradient() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_gradient (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::SparseMatrixCache & mat_cache, StiffnessMatrix & grad) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::HookeLinearElasticity::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 314 of file HookeLinearElasticity.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::hessian_from_energy(), polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
Referenced by polyfem::assembler::MultiModel::assemble_hessian().
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assign_stress_tensor()
void polyfem::assembler::HookeLinearElasticity::assign_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const int all_size, const ElasticityTensorType & type, Eigen::MatrixXd & all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> & fun) const override virtual
Implements polyfem::assembler::ElasticityAssembler.
Definition at line 199 of file HookeLinearElasticity.cpp.
References polyfem::compute_diplacement_grad(), polyfem::assembler::ElasticityTensor::compute_stress(), elasticity_tensor_, polyfem::F, polyfem::PK1, polyfem::pk1_from_cauchy(), polyfem::PK2, polyfem::pk2_from_cauchy(), polyfem::assembler::Assembler::size(), and vals.
Referenced by polyfem::assembler::MultiModel::assign_stress_tensor().
compute_energy()
double polyfem::assembler::HookeLinearElasticity::compute_energy (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 291 of file HookeLinearElasticity.cpp.
Referenced by polyfem::assembler::MultiModel::compute_energy().
compute_energy_aux()
template<typename T > T polyfem::assembler::HookeLinearElasticity::compute_energy_aux (const NonLinearAssemblerData & data) const private
Definition at line 332 of file HookeLinearElasticity.cpp.
References polyfem::compute_disp_grad_at_quad(), polyfem::assembler::NonLinearAssemblerData::da, elasticity_tensor_, polyfem::get_local_disp(), and polyfem::assembler::Assembler::size().
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::HookeLinearElasticity::compute_rhs (const AutodiffHessianPt & pt) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 258 of file HookeLinearElasticity.cpp.
References elasticity_tensor_, polyfem::autogen::hooke_2d_function(), polyfem::autogen::hooke_3d_function(), and polyfem::assembler::Assembler::size().
elasticity_tensor()
const ElasticityTensor & polyfem::assembler::HookeLinearElasticity::elasticity_tensor () const inline
Definition at line 39 of file HookeLinearElasticity.hpp.
References elasticity_tensor_.
Referenced by parameters().
is_linear()
virtual bool polyfem::assembler::HookeLinearElasticity::is_linear () const inline override virtual
Reimplemented from polyfem::assembler::LinearAssembler.
Definition at line 41 of file HookeLinearElasticity.hpp.
name()
std::string polyfem::assembler::HookeLinearElasticity::name () const inline override virtual
Implements polyfem::assembler::Assembler.
Definition at line 42 of file HookeLinearElasticity.hpp.
parameters()
std::map< std::string, Assembler::ParamFunc > polyfem::assembler::HookeLinearElasticity::parameters () const override virtual
Implements polyfem::assembler::Assembler.
Definition at line 273 of file HookeLinearElasticity.cpp.
References elasticity_tensor(), and polyfem::assembler::Assembler::size().
set_size()
void polyfem::assembler::HookeLinearElasticity::set_size (const int size) override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 77 of file HookeLinearElasticity.cpp.
References elasticity_tensor_, polyfem::assembler::ElasticityTensor::resize(), polyfem::assembler::Assembler::set_size(), and polyfem::assembler::Assembler::size().
Referenced by polyfem::assembler::MultiModel::set_size().
Member Data Documentation
elasticity_tensor_
ElasticityTensor polyfem::assembler::HookeLinearElasticity::elasticity_tensor_ private
Definition at line 48 of file HookeLinearElasticity.hpp.
Referenced by add_multimaterial(), assemble(), assign_stress_tensor(), compute_energy_aux(), compute_rhs(), elasticity_tensor(), and set_size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/HookeLinearElasticity.hpp
src/polyfem/assembler/HookeLinearElasticity.cpp