PolyFEM: polyfem::solver::InsertConstantMap Class Reference
polyfem::solver::InsertConstantMap Class Reference
#include <Parametrizations.hpp>
Public Member Functions
InsertConstantMap (const int size=-1, const double val=0, const int start_index=-1)
InsertConstantMap (const Eigen::VectorXd &values)
int size (const int x_size) const override
Eigen::VectorXd inverse_eval (const Eigen::VectorXd &y) override
Eigen::VectorXd eval (const Eigen::VectorXd &x) const override
Eigen::VectorXd apply_jacobian (const Eigen::VectorXd &grad, const Eigen::VectorXd &x) const override
Public Member Functions inherited from polyfem::solver::Parametrization
Parametrization ()
virtual ~Parametrization ()
Private Attributes
int start_index_ = -1
Eigen::VectorXd values_
Detailed Description
Definition at line 139 of file Parametrizations.hpp.
Constructor & Destructor Documentation
InsertConstantMap() [1/2]
polyfem::solver::InsertConstantMap::InsertConstantMap (const int size = -1, const double val = 0, const int start_index = -1)
Definition at line 352 of file Parametrizations.cpp.
References polyfem::log_and_throw_adjoint_error(), size(), val, and values_.
InsertConstantMap() [2/2]
polyfem::solver::InsertConstantMap::InsertConstantMap (const Eigen::VectorXd & values)
Definition at line 359 of file Parametrizations.cpp.
Member Function Documentation
apply_jacobian()
Eigen::VectorXd polyfem::solver::InsertConstantMap::apply_jacobian (const Eigen::VectorXd & grad, const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 398 of file Parametrizations.cpp.
References start_index_, values_, and x.
eval()
Eigen::VectorXd polyfem::solver::InsertConstantMap::eval (const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 382 of file Parametrizations.cpp.
References size(), start_index_, values_, x, and y.
inverse_eval()
Eigen::VectorXd polyfem::solver::InsertConstantMap::inverse_eval (const Eigen::VectorXd & y) override virtual
Reimplemented from polyfem::solver::Parametrization.
Definition at line 368 of file Parametrizations.cpp.
References start_index_, values_, x, and y.
size()
int polyfem::solver::InsertConstantMap::size (const int x_size) const override virtual
Implements polyfem::solver::Parametrization.
Definition at line 363 of file Parametrizations.cpp.
References values_.
Referenced by eval(), and InsertConstantMap().
Member Data Documentation
start_index_
int polyfem::solver::InsertConstantMap::start_index_ = -1 private
Definition at line 153 of file Parametrizations.hpp.
Referenced by apply_jacobian(), eval(), and inverse_eval().
values_
Eigen::VectorXd polyfem::solver::InsertConstantMap::values_ private
Definition at line 154 of file Parametrizations.hpp.
Referenced by apply_jacobian(), eval(), InsertConstantMap(), inverse_eval(), and size().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/parametrization/Parametrizations.hpp
src/polyfem/solver/forms/parametrization/Parametrizations.cpp