PolyFEM: polyfem::solver::KineticForm Class Reference
polyfem::solver::KineticForm Class Reference
#include <SpatialIntegralForms.hpp>
Public Member Functions
KineticForm (const VariableToSimulationGroup &variable_to_simulations, const State &state, const json &args)
Public Member Functions inherited from polyfem::solver::SpatialIntegralForm
SpatialIntegralForm (const VariableToSimulationGroup &variable_to_simulations, const State &state, const json &args)
std::string name () const override
const State & get_state ()
void set_integral_type (const SpatialIntegralType type)
Eigen::VectorXd compute_adjoint_rhs_step (const int time_step, const Eigen::VectorXd &x, const State &state) const override
double value_unweighted_step (const int time_step, const Eigen::VectorXd &x) const override
void compute_partial_gradient_step (const int time_step, const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Public Member Functions inherited from polyfem::solver::StaticForm
virtual ~StaticForm ()=default
Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const final override
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
double value_unweighted (const Eigen::VectorXd &x) const final override
Compute the value of the form.
virtual Eigen::VectorXd compute_adjoint_rhs_step_prev (const int time_step, const Eigen::VectorXd &x, const State &state) const
virtual void solution_changed (const Eigen::VectorXd &new_x) final override
Update cached fields upon a change in the solution.
virtual void solution_changed_step (const int time_step, const Eigen::VectorXd &new_x)
virtual bool depends_on_step_prev () const final
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) final override
Set if the Dirichlet boundary conditions should be enforced.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
IntegrableFunctional get_integral_functional () const override
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Protected Attributes inherited from polyfem::solver::SpatialIntegralForm
const State & state_
SpatialIntegralType spatial_integral_type_
std::set< int > ids_
Protected Attributes inherited from polyfem::solver::StaticForm
bool depends_on_step_prev_ = false
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 139 of file SpatialIntegralForms.hpp.
Constructor & Destructor Documentation
KineticForm()
polyfem::solver::KineticForm::KineticForm (const VariableToSimulationGroup & variable_to_simulations, const State & state, const json & args) inline
Definition at line 142 of file SpatialIntegralForms.hpp.
References polyfem::solver::SpatialIntegralForm::ids_, polyfem::solver::SpatialIntegralForm::set_integral_type(), and polyfem::solver::Volume.
Member Function Documentation
get_integral_functional()
IntegrableFunctional polyfem::solver::KineticForm::get_integral_functional () const override protected virtual
Implements polyfem::solver::SpatialIntegralForm.
Definition at line 329 of file SpatialIntegralForms.cpp.
References polyfem::State::bases, polyfem::State::diff_cached, polyfem::IntegrableFunctional::ParameterType::elem, polyfem::State::geom_bases(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::log_and_throw_adjoint_error(), polyfem::State::mass_matrix_assembler, polyfem::State::mesh, polyfem::solver::SpatialIntegralForm::name(), polyfem::State::problem, polyfem::IntegrableFunctional::set_dj_du(), polyfem::IntegrableFunctional::set_j(), polyfem::solver::SpatialIntegralForm::state_, polyfem::IntegrableFunctional::ParameterType::step, polyfem::IntegrableFunctional::ParameterType::t, polyfem::solver::DiffCache::v(), val, and vals.
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/SpatialIntegralForms.hpp
src/polyfem/solver/forms/adjoint_forms/SpatialIntegralForms.cpp