PolyFEM: polyfem::varform::IncompressibleElasticVarForm Class Reference
polyfem::varform::IncompressibleElasticVarForm Class Reference
#include <IncompressibleElasticVarForm.hpp>
Public Member Functions
std::string name () const override
Get the name of the variational formulation.
void init (const std::string &formulation, const Units &units, const json &args, const std::string &out_path) override
Initialize the variational formulation with the given parameters.
void save_json (const Eigen::MatrixXd &solution, std::ostream &out) const override
Save the solution to a JSON file, for output purposes.
io::OutStatsData compute_errors (const Eigen::MatrixXd &solution) override
Get the error statistics of the variational formulation, for output purposes.
std::vector< io::OutputField > output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options) const override
Get the output fields of the variational formulation, for output purposes.
Public Member Functions inherited from polyfem::varform::ElasticVarForm
void export_data (const Eigen::MatrixXd &solution) const override
io::OutputSpace output_space () const override
Get the output space of the variational formulation, for output purposes.
Public Member Functions inherited from polyfem::varform::VarForm
virtual ~VarForm ()=default
void set_args (const json &args)
Reset the internal state of the variational formulation, e.g.
void set_mesh (std::unique_ptr< mesh::Mesh > mesh, const double loading_mesh_time=0)
Set the mesh for the variational formulation.
void solve (Eigen::MatrixXd &sol)
Solve the variational formulation and store the solution in the given matrix.
void set_time_callback (const std::function< void(int, int, double, double)> &callback)
int problem_dimension () const
Get the problem dimension of the variational formulation, for output purposes.
virtual bool is_contact_enabled () const
Check if contact is enabled for the variational formulation, for output purposes.
const io::OutRuntimeData & output_timings () const
Get the runtime timings of the variational formulation, for output purposes.
void save_json (const Eigen::MatrixXd &solution) const
Save the solution to a JSON file, for output purposes.
Private Member Functions
void reset () override
void load_mesh (const mesh::Mesh &mesh, const json &args) override
void build_basis (mesh::Mesh &mesh, const bool iso_parametric, const json &args) override
void assemble_rhs (const mesh::Mesh &mesh) override
void assemble_mass_mat (const mesh::Mesh &mesh, const json &args) override
void solve_problem (Eigen::MatrixXd &sol) override
int primary_ndof () const
int stacked_ndof () const
void prepare_initial_solution (Eigen::MatrixXd &sol) const
void split_solution (const Eigen::MatrixXd &stacked, Eigen::MatrixXd &primary, Eigen::MatrixXd &pressure) const
void build_stiffness_mat (StiffnessMatrix &stiffness)
void solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > &solver, StiffnessMatrix &A, Eigen::VectorXd &b, const bool compute_spectrum, Eigen::MatrixXd &sol)
void solve_static_linear (Eigen::MatrixXd &sol)
void solve_transient_linear (Eigen::MatrixXd &sol)
void build_rhs_assembler () override
Private Attributes
FESpace pressure_space_
VarFormBoundaryState pressure_boundary_
std::shared_ptr< assembler::MixedAssembler > mixed_assembler_ = nullptr
std::shared_ptr< assembler::Assembler > pressure_assembler_ = nullptr
assembler::AssemblyValsCache pressure_ass_vals_cache_
std::shared_ptr< time_integrator::ImplicitTimeIntegrator > time_integrator
Additional Inherited Members
Protected Member Functions inherited from polyfem::varform::ElasticVarForm
void initial_velocity (Eigen::MatrixXd &velocity) const
void initial_acceleration (Eigen::MatrixXd &acceleration) const
void initial_elastic_solution (Eigen::MatrixXd &solution) const
QuadratureOrders elastic_boundary_samples () const
std::vector< int > elastic_primitive_to_node () const
std::vector< int > elastic_node_to_primitive () const
void build_mesh_matrices (Eigen::MatrixXd &V, Eigen::MatrixXi &F) const
void save_elastic_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator) const
std::vector< io::OutputField > elastic_output_fields (const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options, const mesh::Obstacle *obstacle, const time_integrator::ImplicitTimeIntegrator *time_integrator, const std::vector< std::pair< std::string, std::shared_ptr< solver::Form > > > &named_forms, const solver::Form *elastic_form, const solver::ContactForm *contact_form=nullptr) const
void append_primary_output_fields (std::vector< io::OutputField > &fields, const io::OutputSample &sample, const Eigen::MatrixXd &solution, const io::OutputFieldOptions &options, const mesh::Obstacle *obstacle=nullptr) const
Eigen::MatrixXd displaced_output_normals (const io::OutputSample &sample, const Eigen::MatrixXd &solution) const
virtual int n_obstacle_vertices () const
Protected Member Functions inherited from polyfem::varform::VarForm
std::string resolve_output_path (const std::string &path) const
std::string resolve_input_path (const std::string &path, const bool only_if_exists=false) const
void set_materials (assembler::Assembler &assembler, const int size) const
void assign_discr_orders (const json &discr_order, const mesh::Mesh &mesh, Eigen::VectorXi &disc_orders)
void prepare ()
QuadratureOrders n_boundary_samples (const int discr_order, const int gdiscr_order) const
void build_fe_space (mesh::Mesh &mesh, const bool iso_parametric, const Eigen::VectorXi &disc_orders, const std::string &basis_type, const std::string &poly_basis_type, const assembler::Assembler &space_assembler, const int value_dim, const int quadrature_order, const int mass_quadrature_order, const bool use_corner_quadrature, const int n_harmonic_samples, const int integral_constraints, FESpace &space, VarFormBoundaryState &boundary, std::shared_ptr< GeometryMapping > geometry=nullptr)
std::shared_ptr< time_integrator::BDF > make_bdf_time_integrator () const
void save_step_state (const double t0, const double dt, const int t, const time_integrator::ImplicitTimeIntegrator *time_integrator, const bool rest_mesh_written=false) const
void ensure_output_sampler () const
void save_restart_json (const double t0, const double dt, const int t, const bool rest_mesh_written) const
void save_timestep (const double time, const int t, const double t0, const double dt, const Eigen::MatrixXd &solution) const
void save_subsolve (const int i, const int t, const Eigen::MatrixXd &solution) const
int output_file_index (const int t) const
void notify_time_step (const int t, const int time_steps, const double t0, const double dt) const
io::OutGeometryData::ExportOptions export_options (const io::OutputSpace &space) const
io::OutputFieldFunction output_field_function (const Eigen::MatrixXd &solution, const io::OutGeometryData::ExportOptions &opts) const
Static Protected Member Functions inherited from polyfem::varform::VarForm
static bool read_initial_x_from_file (const std::string &state_path, const std::string &x_name, const bool reorder, const Eigen::VectorXi &in_node_to_node, const int dim, Eigen::MatrixXd &x)
static void rebuild_node_positions (const std::vector< basis::ElementBases > &bases, const std::vector< int > &node_ids, std::vector< RowVectorNd > &positions)
Protected Attributes inherited from polyfem::varform::ElasticVarForm
FESpace space_
VarFormBoundaryState boundary_
assembler::AssemblyValsCache ass_vals_cache_
assembler::AssemblyValsCache mass_ass_vals_cache_
assembler::AssemblyValsCache pure_mass_ass_vals_cache_
std::shared_ptr< assembler::RhsAssembler > rhs_assembler_
StiffnessMatrix mass_
StiffnessMatrix pure_mass_
double avg_mass_ = 0
Eigen::MatrixXd rhs_
std::shared_ptr< assembler::Assembler > primary_assembler_ = nullptr
std::shared_ptr< assembler::Mass > mass_assembler_ = nullptr
std::shared_ptr< assembler::HRZMass > pure_mass_assembler_ = nullptr
double t0 = 0
int time_steps = 0
double dt = 0
Protected Attributes inherited from polyfem::varform::VarForm
std::shared_ptr< assembler::Problem > problem
current problem, it contains rhs and bc
Units units
json args
io::OutStatsData stats
io::OutRuntimeData timings
runtime statistics
std::string root_path
std::string output_path
std::unique_ptr< mesh::Mesh > mesh_
std::function< void(int, int, double, double)> time_callback
io::OutGeometryData output_geometry_
bool output_sampler_initialized_ = false
bool prepared_ = false
Detailed Description
Definition at line 15 of file IncompressibleElasticVarForm.hpp.
Member Function Documentation
assemble_mass_mat()
void polyfem::varform::IncompressibleElasticVarForm::assemble_mass_mat (const mesh::Mesh & mesh, const json & args) override private virtual
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 211 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::io::OutRuntimeData::assembling_mass_mat_time, polyfem::varform::ElasticVarForm::avg_mass_, polyfem::varform::FESpace::basis_list(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::mesh::Mesh::is_volume(), polyfem::logger(), polyfem::utils::lump_matrix(), polyfem::varform::ElasticVarForm::mass_, polyfem::varform::ElasticVarForm::mass_ass_vals_cache_, polyfem::varform::ElasticVarForm::mass_assembler_, polyfem::io::OutStatsData::mat_size, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::nn_zero, polyfem::io::OutStatsData::num_dofs, polyfem::varform::VarForm::problem, polyfem::varform::ElasticVarForm::space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
assemble_rhs()
void polyfem::varform::IncompressibleElasticVarForm::assemble_rhs (const mesh::Mesh & mesh) override private virtual
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 203 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::ElasticVarForm::assemble_rhs(), polyfem::varform::FESpace::n_bases, pressure_space_, and polyfem::varform::ElasticVarForm::rhs_.
build_basis()
void polyfem::varform::IncompressibleElasticVarForm::build_basis (mesh::Mesh & mesh, const bool iso_parametric, const json & args) override private virtual
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 123 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::bases, polyfem::varform::FESpace::basis_list(), polyfem::varform::ElasticVarForm::boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, polyfem::varform::ElasticVarForm::build_basis(), polyfem::varform::VarForm::build_fe_space(), build_rhs_assembler(), polyfem::varform::VarFormBoundaryState::clear_boundary_conditions(), polyfem::mesh::Mesh::dimension(), polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::geometry, polyfem::varform::FESpace::geometry_basis_list(), polyfem::assembler::AssemblyValsCache::init(), polyfem::assembler::AssemblyValsCache::init_empty(), polyfem::mesh::Mesh::is_volume(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::varform::VarFormBoundaryState::local_pressure_boundary, polyfem::varform::VarFormBoundaryState::local_pressure_cavity, polyfem::log_and_throw_error(), polyfem::logger(), polyfem::varform::FESpace::n_bases, polyfem::mesh::Mesh::n_elements(), polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, polyfem::varform::VarFormBoundaryState::normalize_boundary_nodes(), polyfem::varform::FESpace::poly_edge_to_data, pressure_ass_vals_cache_, pressure_boundary_, pressure_space_, polyfem::varform::ElasticVarForm::primary_assembler_, polyfem::varform::VarForm::problem, polyfem::varform::VarForm::rebuild_node_positions(), polyfem::varform::ElasticVarForm::space_, and polyfem::varform::VarFormBoundaryState::total_local_boundary.
build_rhs_assembler()
void polyfem::varform::IncompressibleElasticVarForm::build_rhs_assembler () override private virtual
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 107 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::varform::ElasticVarForm::boundary_, polyfem::varform::VarFormBoundaryState::dirichlet_nodes, polyfem::varform::VarFormBoundaryState::dirichlet_nodes_position, polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::ElasticVarForm::mass_ass_vals_cache_, polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarFormBoundaryState::neumann_nodes, polyfem::varform::VarFormBoundaryState::neumann_nodes_position, polyfem::varform::ElasticVarForm::primary_assembler_, polyfem::varform::VarForm::problem, polyfem::varform::ElasticVarForm::rhs_assembler_, and polyfem::varform::ElasticVarForm::space_.
Referenced by build_basis().
build_stiffness_mat()
void polyfem::varform::IncompressibleElasticVarForm::build_stiffness_mat (StiffnessMatrix & stiffness) private
Definition at line 269 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::ElasticVarForm::ass_vals_cache_, polyfem::io::OutRuntimeData::assembling_stiffness_mat_time, polyfem::varform::FESpace::basis_list(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::logger(), polyfem::io::OutStatsData::mat_size, polyfem::assembler::AssemblerUtils::merge_mixed_matrices(), polyfem::varform::VarForm::mesh_, mixed_assembler_, polyfem::varform::FESpace::n_bases, polyfem::io::OutStatsData::nn_zero, polyfem::io::OutStatsData::num_dofs, pressure_ass_vals_cache_, pressure_assembler_, pressure_space_, polyfem::varform::ElasticVarForm::primary_assembler_, polyfem::varform::ElasticVarForm::space_, polyfem::varform::VarForm::stats, polyfem::varform::VarForm::timings, and polyfem::varform::internal::write_matrix_market().
Referenced by solve_static_linear(), and solve_transient_linear().
compute_errors()
io::OutStatsData polyfem::varform::IncompressibleElasticVarForm::compute_errors (const Eigen::MatrixXd & solution) override virtual
Get the error statistics of the variational formulation, for output purposes.
Returns
Error statistics
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 73 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::basis_list(), polyfem::io::OutStatsData::compute_errors(), polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::problem, polyfem::varform::ElasticVarForm::space_, split_solution(), and polyfem::varform::VarForm::stats.
init()
void polyfem::varform::IncompressibleElasticVarForm::init (const std::string & formulation, const Units & units, const json & args, const std::string & out_path) override virtual
Initialize the variational formulation with the given parameters.
Parameters
formulation name of the variational formulation
units unit system to use for the formulation
args json input arguments, used to initialize the formulation
out_path output path for the formulation, used to save intermediate data
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 35 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::ElasticVarForm::init(), polyfem::assembler::AssemblerUtils::make_assembler(), polyfem::assembler::AssemblerUtils::make_mixed_assembler(), mixed_assembler_, polyfem::assembler::AssemblerUtils::other_assembler_name(), pressure_assembler_, polyfem::varform::ElasticVarForm::primary_assembler_, and polyfem::varform::VarForm::units.
load_mesh()
void polyfem::varform::IncompressibleElasticVarForm::load_mesh (const mesh::Mesh & mesh, const json & args) override private virtual
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 88 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::mesh::Mesh::dimension(), polyfem::varform::ElasticVarForm::load_mesh(), mixed_assembler_, pressure_assembler_, and polyfem::varform::VarForm::set_materials().
name()
std::string polyfem::varform::IncompressibleElasticVarForm::name () const inline override virtual
Get the name of the variational formulation.
Returns
Name of the variational formulation
Implements polyfem::varform::VarForm.
Definition at line 18 of file IncompressibleElasticVarForm.hpp.
Referenced by save_json().
output_fields()
std::vector< io::OutputField > polyfem::varform::IncompressibleElasticVarForm::output_fields (const io::OutputSample & sample, const Eigen::MatrixXd & solution, const io::OutputFieldOptions & options) const override virtual
Get the output fields of the variational formulation, for output purposes.
Parameters
sample Output sample
solution Solution matrix
options Output field options
Returns
Output fields
Implements polyfem::varform::VarForm.
Definition at line 404 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::FESpace::basis_list(), polyfem::varform::ElasticVarForm::elastic_output_fields(), polyfem::io::OutputFieldOptions::export_field(), polyfem::io::OutputFieldOptions::fields, polyfem::varform::FESpace::geometry_basis_list(), polyfem::varform::VarForm::mesh_, polyfem::io::OutputField::Point, pressure_space_, polyfem::varform::internal::sample_scalar_field(), polyfem::varform::ElasticVarForm::space_, split_solution(), and time_integrator.
prepare_initial_solution()
void polyfem::varform::IncompressibleElasticVarForm::prepare_initial_solution (Eigen::MatrixXd & sol) const private
Definition at line 243 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::ElasticVarForm::initial_elastic_solution(), polyfem::varform::FESpace::n_bases, pressure_space_, and stacked_ndof().
Referenced by solve_problem().
primary_ndof()
int polyfem::varform::IncompressibleElasticVarForm::primary_ndof () const private
Definition at line 97 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, and polyfem::varform::ElasticVarForm::space_.
Referenced by save_json(), solve_linear_system(), solve_transient_linear(), split_solution(), and stacked_ndof().
reset()
void polyfem::varform::IncompressibleElasticVarForm::reset () override private virtual
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 24 of file IncompressibleElasticVarForm.cpp.
References polyfem::assembler::AssemblyValsCache::init_empty(), mixed_assembler_, pressure_ass_vals_cache_, pressure_assembler_, pressure_boundary_, pressure_space_, polyfem::varform::FESpace::reset(), polyfem::varform::VarFormBoundaryState::reset(), polyfem::varform::ElasticVarForm::reset(), and time_integrator.
save_json()
void polyfem::varform::IncompressibleElasticVarForm::save_json (const Eigen::MatrixXd & solution, std::ostream & out) const override virtual
Save the solution to a JSON file, for output purposes.
Parameters
solution Solution matrix to save
out Output stream to save the solution
Reimplemented from polyfem::varform::ElasticVarForm.
Definition at line 44 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::FESpace::disc_orders, polyfem::varform::FESpace::disc_ordersq, polyfem::varform::FESpace::is_iso_parametric(), polyfem::logger(), polyfem::varform::VarForm::mesh_, polyfem::varform::FESpace::n_bases, name(), pressure_space_, polyfem::varform::ElasticVarForm::primary_assembler_, primary_ndof(), polyfem::varform::VarForm::problem, polyfem::io::OutStatsData::save_json(), polyfem::varform::ElasticVarForm::space_, polyfem::varform::VarForm::stats, and polyfem::varform::VarForm::timings.
solve_linear_system()
void polyfem::varform::IncompressibleElasticVarForm::solve_linear_system (const std::unique_ptr< polysolve::linear::Solver > & solver, StiffnessMatrix & A, Eigen::VectorXd & b, const bool compute_spectrum, Eigen::MatrixXd & sol) private
Definition at line 293 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::ElasticVarForm::boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, primary_ndof(), polyfem::io::OutStatsData::solver_info, polyfem::io::OutStatsData::spectrum, polyfem::varform::VarForm::stats, and x.
Referenced by solve_static_linear(), and solve_transient_linear().
solve_problem()
void polyfem::varform::IncompressibleElasticVarForm::solve_problem (Eigen::MatrixXd & sol) override private virtual
Implements polyfem::varform::VarForm.
Definition at line 385 of file IncompressibleElasticVarForm.cpp.
References polyfem::logger(), prepare_initial_solution(), polyfem::varform::ElasticVarForm::primary_assembler_, polyfem::varform::VarForm::problem, solve_static_linear(), solve_transient_linear(), polyfem::io::OutRuntimeData::solving_time, polyfem::io::OutStatsData::spectrum, polyfem::varform::VarForm::stats, time_integrator, and polyfem::varform::VarForm::timings.
solve_static_linear()
void polyfem::varform::IncompressibleElasticVarForm::solve_static_linear (Eigen::MatrixXd & sol) private
Definition at line 316 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::ElasticVarForm::boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, build_stiffness_mat(), polyfem::varform::ElasticVarForm::elastic_boundary_samples(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::logger(), polyfem::varform::ElasticVarForm::rhs_, polyfem::varform::ElasticVarForm::rhs_assembler_, and solve_linear_system().
Referenced by solve_problem().
solve_transient_linear()
void polyfem::varform::IncompressibleElasticVarForm::solve_transient_linear (Eigen::MatrixXd & sol) private
Definition at line 327 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::VarForm::args, polyfem::varform::ElasticVarForm::boundary_, polyfem::varform::VarFormBoundaryState::boundary_nodes, build_stiffness_mat(), polyfem::varform::ElasticVarForm::dt, polyfem::varform::ElasticVarForm::elastic_boundary_samples(), polyfem::varform::internal::expand_primary_matrix(), polyfem::varform::VarFormBoundaryState::local_boundary, polyfem::varform::VarFormBoundaryState::local_neumann_boundary, polyfem::logger(), polyfem::varform::VarForm::make_bdf_time_integrator(), polyfem::varform::ElasticVarForm::mass_, polyfem::varform::ElasticVarForm::mass_assembler_, polyfem::varform::FESpace::n_bases, polyfem::varform::VarForm::notify_time_step(), pressure_space_, primary_ndof(), polyfem::varform::ElasticVarForm::rhs_, polyfem::varform::ElasticVarForm::rhs_assembler_, polyfem::varform::ElasticVarForm::save_elastic_step_state(), polyfem::varform::VarForm::save_timestep(), solve_linear_system(), split_solution(), stacked_ndof(), polyfem::varform::ElasticVarForm::t0, time_integrator, and polyfem::varform::ElasticVarForm::time_steps.
Referenced by solve_problem().
split_solution()
void polyfem::varform::IncompressibleElasticVarForm::split_solution (const Eigen::MatrixXd & stacked, Eigen::MatrixXd & primary, Eigen::MatrixXd & pressure) const private
Definition at line 253 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::FESpace::n_bases, pressure_space_, and primary_ndof().
Referenced by compute_errors(), output_fields(), and solve_transient_linear().
stacked_ndof()
int polyfem::varform::IncompressibleElasticVarForm::stacked_ndof () const private
Definition at line 102 of file IncompressibleElasticVarForm.cpp.
References polyfem::varform::FESpace::n_bases, pressure_space_, and primary_ndof().
Referenced by prepare_initial_solution(), and solve_transient_linear().
Member Data Documentation
mixed_assembler_
std::shared_ptr<assembler::MixedAssembler> polyfem::varform::IncompressibleElasticVarForm::mixed_assembler_ = nullptr private
Definition at line 56 of file IncompressibleElasticVarForm.hpp.
Referenced by build_stiffness_mat(), init(), load_mesh(), and reset().
pressure_ass_vals_cache_
assembler::AssemblyValsCache polyfem::varform::IncompressibleElasticVarForm::pressure_ass_vals_cache_ private
Definition at line 58 of file IncompressibleElasticVarForm.hpp.
Referenced by build_basis(), build_stiffness_mat(), and reset().
pressure_assembler_
std::shared_ptr<assembler::Assembler> polyfem::varform::IncompressibleElasticVarForm::pressure_assembler_ = nullptr private
Definition at line 57 of file IncompressibleElasticVarForm.hpp.
Referenced by build_stiffness_mat(), init(), load_mesh(), and reset().
pressure_boundary_
VarFormBoundaryState polyfem::varform::IncompressibleElasticVarForm::pressure_boundary_ private
Definition at line 54 of file IncompressibleElasticVarForm.hpp.
Referenced by build_basis(), and reset().
pressure_space_
FESpace polyfem::varform::IncompressibleElasticVarForm::pressure_space_ private
Definition at line 53 of file IncompressibleElasticVarForm.hpp.
Referenced by assemble_rhs(), build_basis(), build_stiffness_mat(), output_fields(), prepare_initial_solution(), reset(), save_json(), solve_transient_linear(), split_solution(), and stacked_ndof().
time_integrator
std::shared_ptr<time_integrator::ImplicitTimeIntegrator> polyfem::varform::IncompressibleElasticVarForm::time_integrator private
Definition at line 60 of file IncompressibleElasticVarForm.hpp.
Referenced by output_fields(), reset(), solve_problem(), and solve_transient_linear().
The documentation for this class was generated from the following files:
src/polyfem/varforms/IncompressibleElasticVarForm.hpp
src/polyfem/varforms/IncompressibleElasticVarForm.cpp