PolyFEM: cppoptlib::LBFGSBSolver< ProblemType > Class Template Reference
cppoptlib::LBFGSBSolver< ProblemType > Class Template Reference
#include <LBFGSBSolver.hpp>
Public Types
using Superclass = SolverWithBoxConstraints< ProblemType >
Public Types inherited from cppoptlib::SolverWithBoxConstraints< ProblemType >
using Superclass = NonlinearSolver< ProblemType >
Public Types inherited from cppoptlib::NonlinearSolver< ProblemType >
using Superclass = ISolver< ProblemType, -1 >
Public Member Functions
LBFGSBSolver (const polyfem::json &solver_params, const double dt, const double characteristic_length)
std::string name () const override
Public Member Functions inherited from cppoptlib::SolverWithBoxConstraints< ProblemType >
SolverWithBoxConstraints (const polyfem::json &solver_params, const double dt, const double characteristic_length)
double compute_grad_norm (const Eigen::VectorXd &x, const Eigen::VectorXd &grad) const override
Eigen::VectorXd get_lower_bound (const Eigen::VectorXd &x, bool consider_max_change=true) const
Eigen::VectorXd get_upper_bound (const Eigen::VectorXd &x, bool consider_max_change=true) const
Eigen::VectorXd get_max_change (const Eigen::VectorXd &x) const
Public Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
NonlinearSolver (const polyfem::json &solver_params, const double dt, const double characteristic_length)
Construct a new Nonlinear Solver object.
virtual double compute_grad_norm (const Eigen::VectorXd &x, const Eigen::VectorXd &grad) const
virtual std::string name () const =0
void set_line_search (const std::string &line_search_name)
void minimize (ProblemType &objFunc, TVector &x) override
double line_search (const TVector &x, const TVector &delta_x, ProblemType &objFunc)
void get_info (polyfem::json &params)
ErrorCode error_code () const
const Superclass::TCriteria & getStopCriteria ()
bool converged () const
size_t max_iterations () const
size_t & max_iterations ()
Protected Member Functions
virtual int default_descent_strategy () override
std::string descent_strategy_name (int descent_strategy) const override
void increase_descent_strategy () override
void reset (const int ndof) override
void reset_history (const int ndof)
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x, const TVector &grad, TVector &direction) override
Protected Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
virtual void reset (const int ndof)
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x_vec, const TVector &grad, TVector &direction)=0
virtual int default_descent_strategy ()=0
virtual void increase_descent_strategy ()=0
virtual std::string descent_strategy_name (int descent_strategy) const =0
virtual std::string descent_strategy_name () const
virtual void update_solver_info (const double energy)
void reset_times ()
void log_times ()
Protected Attributes
LBFGSpp::BFGSMat< Scalar, true > m_bfgs
int m_history_size = 6
The number of corrections to approximate the inverse Hessian matrix.
int max_submin = 10
TVector m_prev_x
TVector m_prev_grad
Protected Attributes inherited from cppoptlib::NonlinearSolver< ProblemType >
bool normalize_gradient
double use_grad_norm_tol
double first_grad_norm_tol
double dt
std::shared_ptr< polyfem::solver::line_search::LineSearch< ProblemType > > m_line_search
int descent_strategy
polyfem::json solver_info
double total_time
double grad_time
double assembly_time
double inverting_time
double line_search_time
double constraint_set_update_time
double obj_fun_time
ErrorCode m_error_code
Detailed Description
template<typename ProblemType>
class cppoptlib::LBFGSBSolver< ProblemType >
Definition at line 13 of file LBFGSBSolver.hpp.
Member Typedef Documentation
Superclass
template<typename ProblemType > using cppoptlib::LBFGSBSolver< ProblemType >::Superclass = SolverWithBoxConstraints<ProblemType>
Definition at line 16 of file LBFGSBSolver.hpp.
Constructor & Destructor Documentation
LBFGSBSolver()
template<typename ProblemType > cppoptlib::LBFGSBSolver< ProblemType >::LBFGSBSolver (const polyfem::json & solver_params, const double dt, const double characteristic_length) inline
Definition at line 20 of file LBFGSBSolver.hpp.
References cppoptlib::LBFGSBSolver< ProblemType >::m_history_size.
Member Function Documentation
compute_update_direction()
template<typename ProblemType > virtual bool cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction (ProblemType & objFunc, const TVector & x, const TVector & grad, TVector & direction) inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 87 of file LBFGSBSolver.hpp.
References cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction(), cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::SolverWithBoxConstraints< ProblemType >::get_lower_bound(), cppoptlib::SolverWithBoxConstraints< ProblemType >::get_upper_bound(), cppoptlib::LBFGSBSolver< ProblemType >::increase_descent_strategy(), polyfem::logger(), cppoptlib::LBFGSBSolver< ProblemType >::m_bfgs, cppoptlib::LBFGSBSolver< ProblemType >::m_prev_grad, cppoptlib::LBFGSBSolver< ProblemType >::m_prev_x, cppoptlib::LBFGSBSolver< ProblemType >::max_submin, cppoptlib::LBFGSBSolver< ProblemType >::reset_history(), and x.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction().
default_descent_strategy()
template<typename ProblemType > virtual int cppoptlib::LBFGSBSolver< ProblemType >::default_descent_strategy () inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 29 of file LBFGSBSolver.hpp.
descent_strategy_name()
template<typename ProblemType > std::string cppoptlib::LBFGSBSolver< ProblemType >::descent_strategy_name (int descent_strategy) const inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 32 of file LBFGSBSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy.
increase_descent_strategy()
template<typename ProblemType > void cppoptlib::LBFGSBSolver< ProblemType >::increase_descent_strategy () inline override protected virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 45 of file LBFGSBSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, polyfem::log_and_throw_error(), cppoptlib::LBFGSBSolver< ProblemType >::m_bfgs, cppoptlib::LBFGSBSolver< ProblemType >::m_history_size, and cppoptlib::LBFGSBSolver< ProblemType >::m_prev_x.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction().
name()
template<typename ProblemType > std::string cppoptlib::LBFGSBSolver< ProblemType >::name () const inline override virtual
Implements cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 26 of file LBFGSBSolver.hpp.
reset()
template<typename ProblemType > void cppoptlib::LBFGSBSolver< ProblemType >::reset (const int ndof) inline override protected virtual
Reimplemented from cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 70 of file LBFGSBSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::reset(), and cppoptlib::LBFGSBSolver< ProblemType >::reset_history().
reset_history()
template<typename ProblemType > void cppoptlib::LBFGSBSolver< ProblemType >::reset_history (const int ndof) inline protected
Definition at line 77 of file LBFGSBSolver.hpp.
References cppoptlib::NonlinearSolver< ProblemType >::descent_strategy, cppoptlib::LBFGSBSolver< ProblemType >::m_bfgs, cppoptlib::LBFGSBSolver< ProblemType >::m_history_size, cppoptlib::LBFGSBSolver< ProblemType >::m_prev_grad, and cppoptlib::LBFGSBSolver< ProblemType >::m_prev_x.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction(), and cppoptlib::LBFGSBSolver< ProblemType >::reset().
Member Data Documentation
m_bfgs
template<typename ProblemType > LBFGSpp::BFGSMat<Scalar, true> cppoptlib::LBFGSBSolver< ProblemType >::m_bfgs protected
Definition at line 56 of file LBFGSBSolver.hpp.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction(), cppoptlib::LBFGSBSolver< ProblemType >::increase_descent_strategy(), and cppoptlib::LBFGSBSolver< ProblemType >::reset_history().
m_history_size
template<typename ProblemType > int cppoptlib::LBFGSBSolver< ProblemType >::m_history_size = 6 protected
The number of corrections to approximate the inverse Hessian matrix.
The L-BFGS routine stores the computation results of previous m iterations to approximate the inverse Hessian matrix of the current iteration. This parameter controls the size of the limited memories (corrections). The default value is 6. Values less than 3 are not recommended. Large values will result in excessive computing time.
Definition at line 64 of file LBFGSBSolver.hpp.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::increase_descent_strategy(), cppoptlib::LBFGSBSolver< ProblemType >::LBFGSBSolver(), and cppoptlib::LBFGSBSolver< ProblemType >::reset_history().
m_prev_grad
template<typename ProblemType > TVector cppoptlib::LBFGSBSolver< ProblemType >::m_prev_grad protected
Definition at line 68 of file LBFGSBSolver.hpp.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction(), and cppoptlib::LBFGSBSolver< ProblemType >::reset_history().
m_prev_x
template<typename ProblemType > TVector cppoptlib::LBFGSBSolver< ProblemType >::m_prev_x protected
Definition at line 67 of file LBFGSBSolver.hpp.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction(), cppoptlib::LBFGSBSolver< ProblemType >::increase_descent_strategy(), and cppoptlib::LBFGSBSolver< ProblemType >::reset_history().
max_submin
template<typename ProblemType > int cppoptlib::LBFGSBSolver< ProblemType >::max_submin = 10 protected
Definition at line 65 of file LBFGSBSolver.hpp.
Referenced by cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction().
The documentation for this class was generated from the following file:
src/polyfem/solver/LBFGSBSolver.hpp