PolyFEM: polyfem::solver::NLHomoProblem Class Reference
polyfem::solver::NLHomoProblem Class Reference
#include <NLHomoProblem.hpp>
Public Member Functions
NLHomoProblem (const int full_size, const assembler::MacroStrainValue &macro_strain_constraint, const State &state, const double t, const std::vector< std::shared_ptr< Form > > &forms, const std::vector< std::shared_ptr< AugmentedLagrangianForm > > &penalty_forms, const bool solve_symmetric_macro_strain)
virtual ~NLHomoProblem ()=default
double value (const TVector &x) override
void gradient (const TVector &x, TVector &gradv) override
void hessian (const TVector &x, THessian &hessian) override
void full_hessian_to_reduced_hessian (const THessian &full, THessian &reduced) const override
int macro_reduced_size () const
TVector full_to_reduced (const TVector &full, const Eigen::MatrixXd &disp_grad) const
TVector full_to_reduced (const TVector &full) const override
TVector full_to_reduced_grad (const TVector &full) const override
TVector reduced_to_full (const TVector &reduced) const override
TVector reduced_to_full_shape_derivative (const Eigen::MatrixXd &disp_grad, const TVector &adjoint_full) const
TVector reduced_to_extended (const TVector &reduced, bool homogeneous=false) const
TVector extended_to_reduced (const TVector &extended) const
TVector extended_to_reduced_grad (const TVector &extended) const
void extended_hessian_to_reduced_hessian (const THessian &extended, THessian &reduced) const
Eigen::MatrixXd reduced_to_disp_grad (const TVector &reduced, bool homogeneous=false) const
void set_fixed_entry (const Eigen::VectorXi &fixed_entry)
void init (const TVector &x0) override
bool is_step_valid (const TVector &x0, const TVector &x1) override
bool is_step_collision_free (const TVector &x0, const TVector &x1) override
double max_step_size (const TVector &x0, const TVector &x1) override
void line_search_begin (const TVector &x0, const TVector &x1) override
void post_step (const polysolve::nonlinear::PostStepData &data) override
void solution_changed (const TVector &new_x) override
void init_lagging (const TVector &x) override
void update_lagging (const TVector &x, const int iter_num) override
void update_quantities (const double t, const TVector &x) override
void add_form (const std::shared_ptr< Form > &form)
bool has_symmetry_constraint () const
Public Member Functions inherited from polyfem::solver::NLProblem
NLProblem (const int full_size, const std::shared_ptr< utils::PeriodicBoundary > &periodic_bc, const double t, const std::vector< std::shared_ptr< Form > > &forms, const std::vector< std::shared_ptr< AugmentedLagrangianForm > > &penalty_forms)
virtual ~NLProblem ()=default
void line_search_begin (const TVector &x0, const TVector &x1) override
void solution_changed (const TVector &new_x) override
void init_lagging (const TVector &x) override
void update_lagging (const TVector &x, const int iter_num) override
int full_size () const
int reduced_size () const
void use_full_size ()
void use_reduced_size ()
Public Member Functions inherited from polyfem::solver::FullNLProblem
FullNLProblem (const std::vector< std::shared_ptr< Form > > &forms)
virtual ~FullNLProblem ()=default
virtual void line_search_end () override
virtual void set_project_to_psd (bool val) override
int max_lagging_iterations () const
bool uses_lagging () const
std::vector< std::shared_ptr< Form > > & forms ()
virtual bool stop (const TVector &x) override
void finish ()
Protected Member Functions
Eigen::MatrixXd constraint_values (const TVector &) const override
Protected Member Functions inherited from polyfem::solver::NLProblem
NLProblem (const int full_size, const std::vector< std::shared_ptr< Form > > &forms, const std::vector< std::shared_ptr< AugmentedLagrangianForm > > &penalty_forms)
int current_size () const
Private Member Functions
void init_projection ()
Eigen::MatrixXd constraint_grad () const
TVector macro_full_to_reduced (const TVector &full) const
Eigen::MatrixXd macro_full_to_reduced_grad (const Eigen::MatrixXd &full) const
TVector macro_reduced_to_full (const TVector &reduced, bool homogeneous=false) const
Private Attributes
const State & state_
const bool only_symmetric
const assembler::MacroStrainValue & macro_strain_constraint_
Eigen::VectorXi fixed_mask_
Eigen::MatrixXd macro_mid_to_reduced_
Eigen::MatrixXd macro_full_to_mid_
Eigen::MatrixXd macro_mid_to_full_
std::vector< std::shared_ptr< Form > > homo_forms
Additional Inherited Members
Protected Types inherited from polyfem::solver::NLProblem
enum class CurrentSize { FULL_SIZE , REDUCED_SIZE }
Protected Attributes inherited from polyfem::solver::NLProblem
std::vector< int > constraint_nodes_
const int full_size_
Size of the full problem.
int reduced_size_
Size of the reduced problem.
std::shared_ptr< utils::PeriodicBoundary > periodic_bc_
CurrentSize current_size_
Current size of the problem (either full or reduced size)
double t_
Protected Attributes inherited from polyfem::solver::FullNLProblem
std::vector< std::shared_ptr< Form > > forms_
Detailed Description
Definition at line 16 of file NLHomoProblem.hpp.
Constructor & Destructor Documentation
NLHomoProblem()
polyfem::solver::NLHomoProblem::NLHomoProblem (const int full_size, const assembler::MacroStrainValue & macro_strain_constraint, const State & state, const double t, const std::vector< std::shared_ptr< Form > > & forms, const std::vector< std::shared_ptr< AugmentedLagrangianForm > > & penalty_forms, const bool solve_symmetric_macro_strain)
Definition at line 10 of file NLHomoProblem.cpp.
References init_projection().
~NLHomoProblem()
virtual polyfem::solver::NLHomoProblem::~NLHomoProblem () virtual default
Member Function Documentation
add_form()
void polyfem::solver::NLHomoProblem::add_form (const std::shared_ptr< Form > & form) inline
Definition at line 70 of file NLHomoProblem.hpp.
References homo_forms.
constraint_grad()
Eigen::MatrixXd polyfem::solver::NLHomoProblem::constraint_grad () const private
Definition at line 391 of file NLHomoProblem.cpp.
References polyfem::solver::NLProblem::full_size_, polyfem::io::Evaluator::get_bases_position(), macro_full_to_reduced_grad(), polyfem::State::mesh, polyfem::State::mesh_nodes, polyfem::State::n_bases, and state_.
Referenced by full_hessian_to_reduced_hessian(), and full_to_reduced_grad().
constraint_values()
Eigen::MatrixXd polyfem::solver::NLHomoProblem::constraint_values (const TVector &) const override protected virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 407 of file NLHomoProblem.cpp.
References polyfem::solver::NLProblem::full_size().
extended_hessian_to_reduced_hessian()
void polyfem::solver::NLHomoProblem::extended_hessian_to_reduced_hessian (const THessian & extended, THessian & reduced) const
Definition at line 127 of file NLHomoProblem.cpp.
References entries, polyfem::solver::NLProblem::full_hessian_to_reduced_hessian(), polyfem::solver::NLProblem::full_size_, macro_full_to_reduced_grad(), macro_reduced_size(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), and state_.
Referenced by hessian().
extended_to_reduced()
Eigen::VectorXd polyfem::solver::NLHomoProblem::extended_to_reduced (const TVector & extended) const
Definition at line 53 of file NLHomoProblem.cpp.
References polyfem::solver::NLProblem::full_to_reduced(), macro_full_to_reduced(), macro_reduced_size(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), and state_.
extended_to_reduced_grad()
Eigen::VectorXd polyfem::solver::NLHomoProblem::extended_to_reduced_grad (const TVector & extended) const
Definition at line 81 of file NLHomoProblem.cpp.
References polyfem::solver::NLProblem::full_to_reduced_grad(), macro_full_to_reduced_grad(), macro_reduced_size(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), and state_.
Referenced by gradient().
full_hessian_to_reduced_hessian()
void polyfem::solver::NLHomoProblem::full_hessian_to_reduced_hessian (const THessian & full, THessian & reduced) const override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 215 of file NLHomoProblem.cpp.
References constraint_grad(), entries, polyfem::solver::NLProblem::full_hessian_to_reduced_hessian(), macro_reduced_size(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), and state_.
full_to_reduced() [1/2]
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::full_to_reduced (const TVector & full) const override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 249 of file NLHomoProblem.cpp.
References polyfem::log_and_throw_error().
full_to_reduced() [2/2]
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::full_to_reduced (const TVector & full, const Eigen::MatrixXd & disp_grad) const
Definition at line 255 of file NLHomoProblem.cpp.
References polyfem::utils::flatten(), polyfem::solver::NLProblem::full_to_reduced(), polyfem::io::Evaluator::generate_linear_field(), macro_full_to_reduced(), macro_reduced_size(), polyfem::State::mesh, polyfem::State::mesh_nodes, polyfem::State::n_bases, polyfem::solver::NLProblem::reduced_size(), and state_.
full_to_reduced_grad()
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::full_to_reduced_grad (const TVector & full) const override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 269 of file NLHomoProblem.cpp.
References constraint_grad(), polyfem::solver::NLProblem::full_to_reduced_grad(), macro_reduced_size(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), and state_.
gradient()
void polyfem::solver::NLHomoProblem::gradient (const TVector & x, TVector & gradv) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 115 of file NLHomoProblem.cpp.
References extended_to_reduced_grad(), polyfem::solver::NLProblem::gradient(), homo_forms, reduced_to_extended(), and x.
has_symmetry_constraint()
bool polyfem::solver::NLHomoProblem::has_symmetry_constraint () const inline
Definition at line 71 of file NLHomoProblem.hpp.
References only_symmetric.
hessian()
void polyfem::solver::NLHomoProblem::hessian (const TVector & x, THessian & hessian) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 178 of file NLHomoProblem.cpp.
References extended_hessian_to_reduced_hessian(), hessian(), polyfem::solver::NLProblem::hessian(), homo_forms, reduced_to_extended(), and x.
Referenced by hessian().
init()
void polyfem::solver::NLHomoProblem::init (const TVector & x0) override virtual
Reimplemented from polyfem::solver::FullNLProblem.
Definition at line 316 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::FullNLProblem::init(), reduced_to_extended(), and reduced_to_full().
init_lagging()
void polyfem::solver::NLHomoProblem::init_lagging (const TVector & x) override virtual
Reimplemented from polyfem::solver::FullNLProblem.
Definition at line 371 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::NLProblem::init_lagging(), reduced_to_extended(), and x.
init_projection()
void polyfem::solver::NLHomoProblem::init_projection () private
Definition at line 25 of file NLHomoProblem.cpp.
References macro_full_to_mid_, macro_mid_to_full_, macro_mid_to_reduced_, polyfem::State::mesh, only_symmetric, and state_.
Referenced by NLHomoProblem().
is_step_collision_free()
bool polyfem::solver::NLHomoProblem::is_step_collision_free (const TVector & x0, const TVector & x1) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 332 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::NLProblem::is_step_collision_free(), and reduced_to_extended().
is_step_valid()
bool polyfem::solver::NLHomoProblem::is_step_valid (const TVector & x0, const TVector & x1) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 323 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::NLProblem::is_step_valid(), and reduced_to_extended().
line_search_begin()
void polyfem::solver::NLHomoProblem::line_search_begin (const TVector & x0, const TVector & x1) override virtual
Reimplemented from polyfem::solver::FullNLProblem.
Definition at line 350 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::NLProblem::line_search_begin(), and reduced_to_extended().
macro_full_to_reduced()
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::macro_full_to_reduced (const TVector & full) const private
Definition at line 297 of file NLHomoProblem.cpp.
References macro_full_to_mid_, and macro_mid_to_reduced_.
Referenced by extended_to_reduced(), and full_to_reduced().
macro_full_to_reduced_grad()
Eigen::MatrixXd polyfem::solver::NLHomoProblem::macro_full_to_reduced_grad (const Eigen::MatrixXd & full) const private
Definition at line 301 of file NLHomoProblem.cpp.
References macro_mid_to_full_, and macro_mid_to_reduced_.
Referenced by constraint_grad(), extended_hessian_to_reduced_hessian(), and extended_to_reduced_grad().
macro_reduced_size()
int polyfem::solver::NLHomoProblem::macro_reduced_size () const
Definition at line 293 of file NLHomoProblem.cpp.
References macro_mid_to_reduced_.
Referenced by extended_hessian_to_reduced_hessian(), extended_to_reduced(), extended_to_reduced_grad(), full_hessian_to_reduced_hessian(), full_to_reduced(), full_to_reduced_grad(), reduced_to_disp_grad(), reduced_to_extended(), and reduced_to_full().
macro_reduced_to_full()
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::macro_reduced_to_full (const TVector & reduced, bool homogeneous = false) const private
Definition at line 305 of file NLHomoProblem.cpp.
References polyfem::assembler::MacroStrainValue::eval(), fixed_mask_, polyfem::utils::flatten(), macro_full_to_mid_, macro_mid_to_full_, macro_mid_to_reduced_, macro_strain_constraint_, and polyfem::solver::NLProblem::t_.
Referenced by reduced_to_disp_grad(), reduced_to_extended(), and reduced_to_full().
max_step_size()
double polyfem::solver::NLHomoProblem::max_step_size (const TVector & x0, const TVector & x1) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 341 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::NLProblem::max_step_size(), and reduced_to_extended().
post_step()
void polyfem::solver::NLHomoProblem::post_step (const polysolve::nonlinear::PostStepData & data) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 356 of file NLHomoProblem.cpp.
References homo_forms, polyfem::solver::NLProblem::post_step(), and reduced_to_extended().
reduced_to_disp_grad()
Eigen::MatrixXd polyfem::solver::NLHomoProblem::reduced_to_disp_grad (const TVector & reduced, bool homogeneous = false) const
Definition at line 170 of file NLHomoProblem.cpp.
References macro_reduced_size(), macro_reduced_to_full(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), state_, and polyfem::utils::unflatten().
reduced_to_extended()
Eigen::VectorXd polyfem::solver::NLHomoProblem::reduced_to_extended (const TVector & reduced, bool homogeneous = false) const
Definition at line 66 of file NLHomoProblem.cpp.
References macro_reduced_size(), macro_reduced_to_full(), polyfem::State::mesh, polyfem::solver::NLProblem::reduced_size(), polyfem::solver::NLProblem::reduced_to_full(), and state_.
Referenced by gradient(), hessian(), init(), init_lagging(), is_step_collision_free(), is_step_valid(), line_search_begin(), max_step_size(), post_step(), solution_changed(), update_lagging(), update_quantities(), and value().
reduced_to_full()
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::reduced_to_full (const TVector & reduced) const override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 283 of file NLHomoProblem.cpp.
References polyfem::io::Evaluator::generate_linear_field(), macro_reduced_size(), macro_reduced_to_full(), polyfem::State::mesh, polyfem::State::mesh_nodes, polyfem::State::n_bases, polyfem::solver::NLProblem::reduced_size(), polyfem::solver::NLProblem::reduced_to_full(), state_, and polyfem::utils::unflatten().
Referenced by init().
reduced_to_full_shape_derivative()
NLHomoProblem::TVector polyfem::solver::NLHomoProblem::reduced_to_full_shape_derivative (const Eigen::MatrixXd & disp_grad, const TVector & adjoint_full) const
Definition at line 94 of file NLHomoProblem.cpp.
References polyfem::State::basis_nodes_to_gbasis_nodes, polyfem::State::mesh, polyfem::State::n_bases, and state_.
Referenced by polyfem::solver::SpatialIntegralForm::compute_partial_gradient_step().
set_fixed_entry()
void polyfem::solver::NLHomoProblem::set_fixed_entry (const Eigen::VectorXi & fixed_entry)
Definition at line 194 of file NLHomoProblem.cpp.
References fixed_mask_, macro_full_to_mid_, macro_mid_to_reduced_, polyfem::State::mesh, and state_.
solution_changed()
void polyfem::solver::NLHomoProblem::solution_changed (const TVector & new_x) override virtual
Reimplemented from polyfem::solver::FullNLProblem.
Definition at line 364 of file NLHomoProblem.cpp.
References homo_forms, reduced_to_extended(), and polyfem::solver::NLProblem::solution_changed().
update_lagging()
void polyfem::solver::NLHomoProblem::update_lagging (const TVector & x, const int iter_num) override virtual
Reimplemented from polyfem::solver::FullNLProblem.
Definition at line 377 of file NLHomoProblem.cpp.
References homo_forms, reduced_to_extended(), polyfem::solver::NLProblem::update_lagging(), and x.
update_quantities()
void polyfem::solver::NLHomoProblem::update_quantities (const double t, const TVector & x) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 384 of file NLHomoProblem.cpp.
References homo_forms, reduced_to_extended(), polyfem::solver::NLProblem::update_quantities(), and x.
value()
double polyfem::solver::NLHomoProblem::value (const TVector & x) override virtual
Reimplemented from polyfem::solver::NLProblem.
Definition at line 106 of file NLHomoProblem.cpp.
References homo_forms, reduced_to_extended(), val, polyfem::solver::NLProblem::value(), and x.
Member Data Documentation
fixed_mask_
Eigen::VectorXi polyfem::solver::NLHomoProblem::fixed_mask_ private
Definition at line 88 of file NLHomoProblem.hpp.
Referenced by macro_reduced_to_full(), and set_fixed_entry().
homo_forms
std::vector<std::shared_ptr<Form> > polyfem::solver::NLHomoProblem::homo_forms private
Definition at line 92 of file NLHomoProblem.hpp.
Referenced by add_form(), gradient(), hessian(), init(), init_lagging(), is_step_collision_free(), is_step_valid(), line_search_begin(), max_step_size(), post_step(), solution_changed(), update_lagging(), update_quantities(), and value().
macro_full_to_mid_
Eigen::MatrixXd polyfem::solver::NLHomoProblem::macro_full_to_mid_ private
Definition at line 90 of file NLHomoProblem.hpp.
Referenced by init_projection(), macro_full_to_reduced(), macro_reduced_to_full(), and set_fixed_entry().
macro_mid_to_full_
Eigen::MatrixXd polyfem::solver::NLHomoProblem::macro_mid_to_full_ private
Definition at line 90 of file NLHomoProblem.hpp.
Referenced by init_projection(), macro_full_to_reduced_grad(), and macro_reduced_to_full().
macro_mid_to_reduced_
Eigen::MatrixXd polyfem::solver::NLHomoProblem::macro_mid_to_reduced_ private
Definition at line 89 of file NLHomoProblem.hpp.
Referenced by init_projection(), macro_full_to_reduced(), macro_full_to_reduced_grad(), macro_reduced_size(), macro_reduced_to_full(), and set_fixed_entry().
macro_strain_constraint_
const assembler::MacroStrainValue& polyfem::solver::NLHomoProblem::macro_strain_constraint_ private
Definition at line 86 of file NLHomoProblem.hpp.
Referenced by macro_reduced_to_full().
only_symmetric
const bool polyfem::solver::NLHomoProblem::only_symmetric private
Definition at line 85 of file NLHomoProblem.hpp.
Referenced by has_symmetry_constraint(), and init_projection().
state_
const State& polyfem::solver::NLHomoProblem::state_ private
Definition at line 84 of file NLHomoProblem.hpp.
Referenced by constraint_grad(), extended_hessian_to_reduced_hessian(), extended_to_reduced(), extended_to_reduced_grad(), full_hessian_to_reduced_hessian(), full_to_reduced(), full_to_reduced_grad(), init_projection(), reduced_to_disp_grad(), reduced_to_extended(), reduced_to_full(), reduced_to_full_shape_derivative(), and set_fixed_entry().
The documentation for this class was generated from the following files:
src/polyfem/solver/NLHomoProblem.hpp
src/polyfem/solver/NLHomoProblem.cpp