PolyFEM: polyfem::assembler::AssemblyValsCache Class Reference
polyfem::assembler::AssemblyValsCache Class Reference
#include <AssemblyValsCache.hpp>
Public Member Functions
void init (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases)
void compute (const int el_index, const bool is_volume, const basis::ElementBases &basis, const basis::ElementBases &gbasis, ElementAssemblyValues &vals) const
void clear ()
Private Attributes
std::vector< ElementAssemblyValues > cache
Detailed Description
Definition at line 9 of file AssemblyValsCache.hpp.
Member Function Documentation
clear()
void polyfem::assembler::AssemblyValsCache::clear () inline
Definition at line 15 of file AssemblyValsCache.hpp.
References cache.
compute()
void polyfem::assembler::AssemblyValsCache::compute (const int el_index, const bool is_volume, const basis::ElementBases & basis, const basis::ElementBases & gbasis, ElementAssemblyValues & vals) const
Definition at line 23 of file AssemblyValsCache.cpp.
References cache, and vals.
Referenced by polyfem::assembler::RhsAssembler::assemble(), polyfem::assembler::RhsAssembler::compute_energy(), and polyfem::assembler::RhsAssembler::time_bc().
init()
void polyfem::assembler::AssemblyValsCache::init (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases)
Definition at line 10 of file AssemblyValsCache.cpp.
References cache, and polyfem::utils::maybe_parallel_for().
Member Data Documentation
cache
std::vector<ElementAssemblyValues> polyfem::assembler::AssemblyValsCache::cache private
Definition at line 21 of file AssemblyValsCache.hpp.
Referenced by clear(), compute(), and init().
The documentation for this class was generated from the following files:
src/polyfem/assembler/AssemblyValsCache.hpp
src/polyfem/assembler/AssemblyValsCache.cpp