PolyFEM: polyfem::problem::Airfoil Class Reference
polyfem::problem::Airfoil Class Reference
#include <StokesProblem.hpp>
Public Member Functions
Airfoil (const std::string &name)
bool has_exact_sol () const override
bool is_rhs_zero () const override
bool is_scalar () const override
bool is_time_dependent () const override
void initial_solution (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const override
void set_parameters (const json &params) override
void exact (const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const override
void exact_grad (const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const override
void rhs (const assembler::Assembler &assembler, const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const override
void dirichlet_bc (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &uv, const Eigen::MatrixXd &pts, const double t, Eigen::MatrixXd &val) const override
Public Member Functions inherited from polyfem::assembler::Problem
Problem (const std::string &name)
virtual void set_units (const assembler::Assembler &assembler, const Units &units)
virtual ~Problem ()
virtual void init (const mesh::Mesh &mesh)
const std::string & name () const
virtual void neumann_bc (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &uv, const Eigen::MatrixXd &pts, const Eigen::MatrixXd &normals, const double t, Eigen::MatrixXd &val) const
virtual bool is_boundary_pressure (const int boundary_id) const
virtual void dirichlet_nodal_value (const mesh::Mesh &mesh, const int node_id, const RowVectorNd &pt, const double t, Eigen::MatrixXd &val) const
virtual void neumann_nodal_value (const mesh::Mesh &mesh, const int node_id, const RowVectorNd &pt, const Eigen::MatrixXd &normal, const double t, Eigen::MatrixXd &val) const
virtual bool is_nodal_dirichlet_boundary (const int n_id, const int tag)
virtual bool is_nodal_neumann_boundary (const int n_id, const int tag)
virtual bool has_nodal_dirichlet ()
virtual bool has_nodal_neumann ()
virtual void clear ()
virtual bool is_constant_in_time () const
virtual void initial_velocity (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual void initial_acceleration (const mesh::Mesh &mesh, const Eigen::MatrixXi &global_ids, const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual void initial_density (const Eigen::MatrixXd &pts, Eigen::MatrixXd &val) const
virtual bool might_have_no_dirichlet ()
virtual bool is_dimension_dirichet (const int tag, const int dim) const
virtual bool is_nodal_dimension_dirichlet (const int n_id, const int tag, const int dim) const
virtual bool all_dimensions_dirichlet () const
void setup_bc (const mesh::Mesh &mesh, const int n_bases, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &geom_bases, const std::vector< basis::ElementBases > &pressure_bases, std::vector< mesh::LocalBoundary > &local_boundary, std::vector< int > &boundary_nodes, std::vector< mesh::LocalBoundary > &local_neumann_boundary, std::vector< int > &pressure_boundary_nodes, std::vector< int > &dirichlet_nodes, std::vector< int > &neumann_nodes)
virtual void update_nodes (const Eigen::VectorXi &in_node_to_node)
Public Attributes
bool is_time_dependent_
Additional Inherited Members
Protected Attributes inherited from polyfem::assembler::Problem
std::vector< int > boundary_ids_
std::vector< int > neumann_boundary_ids_
std::vector< int > pressure_boundary_ids_
std::vector< int > splitting_pressure_boundary_ids_
Detailed Description
Definition at line 250 of file StokesProblem.hpp.
Constructor & Destructor Documentation
Airfoil()
polyfem::problem::Airfoil::Airfoil (const std::string & name)
Definition at line 750 of file StokesProblem.cpp.
References polyfem::assembler::Problem::boundary_ids_, and is_time_dependent_.
Member Function Documentation
dirichlet_bc()
void polyfem::problem::Airfoil::dirichlet_bc (const mesh::Mesh & mesh, const Eigen::MatrixXi & global_ids, const Eigen::MatrixXd & uv, const Eigen::MatrixXd & pts, const double t, Eigen::MatrixXd & val) const override virtual
Implements polyfem::assembler::Problem.
Definition at line 798 of file StokesProblem.cpp.
References polyfem::mesh::Mesh::get_boundary_id(), is_time_dependent_, val, x, and y.
exact()
void polyfem::problem::Airfoil::exact (const Eigen::MatrixXd & pts, const double t, Eigen::MatrixXd & val) const override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 770 of file StokesProblem.cpp.
References is_time_dependent_, val, x, and y.
Referenced by initial_solution().
exact_grad()
void polyfem::problem::Airfoil::exact_grad (const Eigen::MatrixXd & pts, const double t, Eigen::MatrixXd & val) const override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 786 of file StokesProblem.cpp.
References val.
has_exact_sol()
bool polyfem::problem::Airfoil::has_exact_sol () const inline override virtual
Implements polyfem::assembler::Problem.
Definition at line 255 of file StokesProblem.hpp.
initial_solution()
void polyfem::problem::Airfoil::initial_solution (const mesh::Mesh & mesh, const Eigen::MatrixXi & global_ids, const Eigen::MatrixXd & pts, Eigen::MatrixXd & val) const override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 757 of file StokesProblem.cpp.
References exact(), and val.
is_rhs_zero()
bool polyfem::problem::Airfoil::is_rhs_zero () const inline override virtual
Implements polyfem::assembler::Problem.
Definition at line 256 of file StokesProblem.hpp.
is_scalar()
bool polyfem::problem::Airfoil::is_scalar () const inline override virtual
Implements polyfem::assembler::Problem.
Definition at line 257 of file StokesProblem.hpp.
is_time_dependent()
bool polyfem::problem::Airfoil::is_time_dependent () const inline override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 258 of file StokesProblem.hpp.
References is_time_dependent_.
rhs()
void polyfem::problem::Airfoil::rhs (const assembler::Assembler & assembler, const Eigen::MatrixXd & pts, const double t, Eigen::MatrixXd & val) const override virtual
Implements polyfem::assembler::Problem.
Definition at line 792 of file StokesProblem.cpp.
References val.
set_parameters()
void polyfem::problem::Airfoil::set_parameters (const json & params) override virtual
Reimplemented from polyfem::assembler::Problem.
Definition at line 762 of file StokesProblem.cpp.
References is_time_dependent_.
Member Data Documentation
is_time_dependent_
bool polyfem::problem::Airfoil::is_time_dependent_
Definition at line 271 of file StokesProblem.hpp.
Referenced by Airfoil(), dirichlet_bc(), exact(), is_time_dependent(), and set_parameters().
The documentation for this class was generated from the following files:
src/polyfem/problem/StokesProblem.hpp
src/polyfem/problem/StokesProblem.cpp