PolyFEM: cppoptlib::SolverWithBoxConstraints< ProblemType > Class Template Reference
cppoptlib::SolverWithBoxConstraints< ProblemType > Class Template Reference
#include <SolverWithBoxConstraints.hpp>
Public Types
using Superclass = NonlinearSolver< ProblemType >
Public Types inherited from cppoptlib::NonlinearSolver< ProblemType >
using Superclass = ISolver< ProblemType, -1 >
Public Member Functions
SolverWithBoxConstraints (const polyfem::json &solver_params, const double dt, const double characteristic_length)
double compute_grad_norm (const Eigen::VectorXd &x, const Eigen::VectorXd &grad) const override
Eigen::VectorXd get_lower_bound (const Eigen::VectorXd &x, bool consider_max_change=true) const
Eigen::VectorXd get_upper_bound (const Eigen::VectorXd &x, bool consider_max_change=true) const
Eigen::VectorXd get_max_change (const Eigen::VectorXd &x) const
Public Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
NonlinearSolver (const polyfem::json &solver_params, const double dt, const double characteristic_length)
Construct a new Nonlinear Solver object.
virtual std::string name () const =0
void set_line_search (const std::string &line_search_name)
void minimize (ProblemType &objFunc, TVector &x) override
double line_search (const TVector &x, const TVector &delta_x, ProblemType &objFunc)
void get_info (polyfem::json &params)
ErrorCode error_code () const
const Superclass::TCriteria & getStopCriteria ()
bool converged () const
size_t max_iterations () const
size_t & max_iterations ()
Private Attributes
Eigen::MatrixXd bounds_
double max_change_val_ = 0
Eigen::VectorXd max_change_
Additional Inherited Members
Protected Member Functions inherited from cppoptlib::NonlinearSolver< ProblemType >
virtual void reset (const int ndof)
virtual bool compute_update_direction (ProblemType &objFunc, const TVector &x_vec, const TVector &grad, TVector &direction)=0
virtual int default_descent_strategy ()=0
virtual void increase_descent_strategy ()=0
virtual std::string descent_strategy_name (int descent_strategy) const =0
virtual std::string descent_strategy_name () const
virtual void update_solver_info (const double energy)
void reset_times ()
void log_times ()
Protected Attributes inherited from cppoptlib::NonlinearSolver< ProblemType >
bool normalize_gradient
double use_grad_norm_tol
double first_grad_norm_tol
double dt
std::shared_ptr< polyfem::solver::line_search::LineSearch< ProblemType > > m_line_search
int descent_strategy
polyfem::json solver_info
double total_time
double grad_time
double assembly_time
double inverting_time
double line_search_time
double constraint_set_update_time
double obj_fun_time
ErrorCode m_error_code
Detailed Description
template<typename ProblemType>
class cppoptlib::SolverWithBoxConstraints< ProblemType >
Definition at line 12 of file SolverWithBoxConstraints.hpp.
Member Typedef Documentation
Superclass
template<typename ProblemType > using cppoptlib::SolverWithBoxConstraints< ProblemType >::Superclass = NonlinearSolver<ProblemType>
Definition at line 15 of file SolverWithBoxConstraints.hpp.
Constructor & Destructor Documentation
SolverWithBoxConstraints()
template<typename ProblemType > cppoptlib::SolverWithBoxConstraints< ProblemType >::SolverWithBoxConstraints (const polyfem::json & solver_params, const double dt, const double characteristic_length) inline
Definition at line 19 of file SolverWithBoxConstraints.hpp.
References cppoptlib::SolverWithBoxConstraints< ProblemType >::bounds_, cppoptlib::SolverWithBoxConstraints< ProblemType >::max_change_, cppoptlib::SolverWithBoxConstraints< ProblemType >::max_change_val_, and polyfem::io::read_matrix().
Member Function Documentation
compute_grad_norm()
template<typename ProblemType > double cppoptlib::SolverWithBoxConstraints< ProblemType >::compute_grad_norm (const Eigen::VectorXd & x, const Eigen::VectorXd & grad) const inline override virtual
Reimplemented from cppoptlib::NonlinearSolver< ProblemType >.
Definition at line 57 of file SolverWithBoxConstraints.hpp.
References cppoptlib::SolverWithBoxConstraints< ProblemType >::get_lower_bound(), cppoptlib::SolverWithBoxConstraints< ProblemType >::get_upper_bound(), and x.
get_lower_bound()
template<typename ProblemType > Eigen::VectorXd cppoptlib::SolverWithBoxConstraints< ProblemType >::get_lower_bound (const Eigen::VectorXd & x, bool consider_max_change = true) const inline
Definition at line 71 of file SolverWithBoxConstraints.hpp.
References cppoptlib::SolverWithBoxConstraints< ProblemType >::bounds_, cppoptlib::SolverWithBoxConstraints< ProblemType >::get_max_change(), polyfem::log_and_throw_error(), and x.
Referenced by cppoptlib::SolverWithBoxConstraints< ProblemType >::compute_grad_norm(), and cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction().
get_max_change()
template<typename ProblemType > Eigen::VectorXd cppoptlib::SolverWithBoxConstraints< ProblemType >::get_max_change (const Eigen::VectorXd & x) const inline
Definition at line 102 of file SolverWithBoxConstraints.hpp.
References cppoptlib::SolverWithBoxConstraints< ProblemType >::max_change_, cppoptlib::SolverWithBoxConstraints< ProblemType >::max_change_val_, and x.
Referenced by cppoptlib::SolverWithBoxConstraints< ProblemType >::get_lower_bound(), and cppoptlib::SolverWithBoxConstraints< ProblemType >::get_upper_bound().
get_upper_bound()
template<typename ProblemType > Eigen::VectorXd cppoptlib::SolverWithBoxConstraints< ProblemType >::get_upper_bound (const Eigen::VectorXd & x, bool consider_max_change = true) const inline
Definition at line 86 of file SolverWithBoxConstraints.hpp.
References cppoptlib::SolverWithBoxConstraints< ProblemType >::bounds_, cppoptlib::SolverWithBoxConstraints< ProblemType >::get_max_change(), polyfem::log_and_throw_error(), and x.
Referenced by cppoptlib::SolverWithBoxConstraints< ProblemType >::compute_grad_norm(), and cppoptlib::LBFGSBSolver< ProblemType >::compute_update_direction().
Member Data Documentation
bounds_
template<typename ProblemType > Eigen::MatrixXd cppoptlib::SolverWithBoxConstraints< ProblemType >::bounds_ private
Definition at line 115 of file SolverWithBoxConstraints.hpp.
Referenced by cppoptlib::SolverWithBoxConstraints< ProblemType >::get_lower_bound(), cppoptlib::SolverWithBoxConstraints< ProblemType >::get_upper_bound(), and cppoptlib::SolverWithBoxConstraints< ProblemType >::SolverWithBoxConstraints().
max_change_
template<typename ProblemType > Eigen::VectorXd cppoptlib::SolverWithBoxConstraints< ProblemType >::max_change_ private
Definition at line 118 of file SolverWithBoxConstraints.hpp.
Referenced by cppoptlib::SolverWithBoxConstraints< ProblemType >::get_max_change(), and cppoptlib::SolverWithBoxConstraints< ProblemType >::SolverWithBoxConstraints().
max_change_val_
template<typename ProblemType > double cppoptlib::SolverWithBoxConstraints< ProblemType >::max_change_val_ = 0 private
Definition at line 117 of file SolverWithBoxConstraints.hpp.
Referenced by cppoptlib::SolverWithBoxConstraints< ProblemType >::get_max_change(), and cppoptlib::SolverWithBoxConstraints< ProblemType >::SolverWithBoxConstraints().
The documentation for this class was generated from the following file:
src/polyfem/solver/SolverWithBoxConstraints.hpp