PolyFEM: polyfem::mesh::Mesh Class Reference
polyfem::mesh::Mesh Class Reference abstract
Abstract mesh class to capture 2d/3d conforming and non-conforming meshes.
#include <Mesh.hpp>
Classes
class CellNodes
Class to store the high-order cells nodes.
class EdgeNodes
Class to store the high-order edge nodes.
class FaceNodes
Class to store the high-order face nodes.
Public Member Functions
virtual ~Mesh ()=default
Destroy the Mesh object.
Mesh (Mesh &&)=default
Construct a new Mesh object.
Mesh & operator= (Mesh &&)=default
Copy constructor.
Mesh (const Mesh &)=default
Construct a new Mesh object.
Mesh & operator= (const Mesh &)=default
virtual void refine (const int n_refinement, const double t)=0
refine the mesh
virtual bool is_volume () const =0
checks if mesh is volume
int dimension () const
utily for dimension
virtual bool is_conforming () const =0
if the mesh is conforming
int n_elements () const
utitlity to return the number of elements, cells or faces in 3d and 2d
virtual int n_cells () const =0
number of cells
virtual int n_faces () const =0
number of faces
virtual int n_edges () const =0
number of edges
virtual int n_vertices () const =0
number of vertices
virtual int n_face_vertices (const int f_id) const =0
number of vertices of a face
virtual int face_vertex (const int f_id, const int lv_id) const =0
id of the face vertex
virtual int edge_vertex (const int e_id, const int lv_id) const =0
id of the edge vertex
virtual int cell_vertex (const int f_id, const int lv_id) const =0
id of the vertex of a cell
virtual bool is_boundary_vertex (const int vertex_global_id) const =0
is vertex boundary
virtual bool is_boundary_edge (const int edge_global_id) const =0
is edge boundary
virtual bool is_boundary_face (const int face_global_id) const =0
is face boundary
virtual bool is_boundary_element (const int element_global_id) const =0
is cell boundary
virtual void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes)=0
attach high order nodes
const Eigen::MatrixXi & orders () const
order of each element
bool is_rational () const
check if curved mesh has rational polynomials elements
void set_is_rational (const bool in_is_rational)
Set the is rational object.
virtual void normalize ()=0
normalize the mesh
virtual void compute_elements_tag ()=0
compute element types, see ElementType
virtual void update_elements_tag ()
Update elements types.
virtual double edge_length (const int gid) const
edge length
virtual double quad_area (const int gid) const
area of a quad face of an hex mesh
virtual double tri_area (const int gid) const
area of a tri face of a tet mesh
virtual RowVectorNd point (const int global_index) const =0
point coordinates
virtual RowVectorNd edge_barycenter (const int e) const =0
edge barycenter
virtual RowVectorNd face_barycenter (const int f) const =0
face barycenter
virtual RowVectorNd cell_barycenter (const int c) const =0
cell barycenter
void edge_barycenters (Eigen::MatrixXd &barycenters) const
all edges barycenters
void face_barycenters (Eigen::MatrixXd &barycenters) const
all face barycenters
void cell_barycenters (Eigen::MatrixXd &barycenters) const
all cells barycenters
virtual void compute_element_barycenters (Eigen::MatrixXd &barycenters) const =0
utility for 2d/3d.
virtual void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const =0
constructs a box around every element (3d cell, 2d face)
virtual void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const =0
constructs barycentric coodiantes for a point p.
virtual void bounding_box (RowVectorNd &min, RowVectorNd &max) const =0
computes the bbox of the mesh
bool is_spline_compatible (const int el_id) const
checks if element is spline compatible
bool is_cube (const int el_id) const
checks if element is cube compatible
bool is_polytope (const int el_id) const
checks if element is polygon compatible
bool is_simplex (const int el_id) const
checks if element is simples compatible
const std::vector< ElementType > & elements_tag () const
Returns the elements types.
void set_tag (const int el, const ElementType type)
changes the element type
virtual void load_boundary_ids (const std::string &path)
loads the boundary selections for a file
virtual void compute_boundary_ids (const double eps)=0
computes the selection based on the bbx of the mesh.
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void set_boundary_ids (const std::vector< int > &boundary_ids)
Set the boundary selection from a vector.
virtual void set_body_ids (const std::vector< int > &body_ids)
Set the volume sections.
virtual void set_body_ids (const Eigen::VectorXi &body_ids)
Set the volume sections.
virtual int get_boundary_id (const int primitive) const
Get the boundary selection of an element (face in 3d, edge in 2d)
virtual int get_body_id (const int primitive) const
Get the volume selection of an element (cell in 3d, face in 2d)
bool has_boundary_ids () const
checks if surface selections are available
virtual bool has_body_ids () const
checks if volumes selections are available
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const =0
Get all the edges.
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const =0
Get all the edges according to valid_elements selection.
virtual void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const =0
generate a triangular representation of every face
const std::vector< double > & cell_weights (const int cell_index) const
weights for rational polynomial meshes
void set_cell_weights (const std::vector< std::vector< double > > &in_cell_weights)
Set the cell weights for rational polynomial meshes.
virtual void prepare_mesh ()
method used to finalize the mesh.
bool has_poly () const
checks if the mesh has polytopes
bool is_linear ()
check if the mesh is linear
std::vector< std::pair< int, int > > edges () const
list of sorted edges.
std::vector< std::vector< int > > faces () const
list of sorted faces.
std::unordered_map< std::pair< int, int >, size_t, polyfem::utils::HashPair > edges_to_ids () const
map from edge (pair of v id) to the id of the edge
std::unordered_map< std::vector< int >, size_t, polyfem::utils::HashVector > faces_to_ids () const
map from face (tuple of v id) to the id of the face
const Eigen::VectorXi & in_ordered_vertices () const
Order of the input vertices.
const Eigen::MatrixXi & in_ordered_edges () const
Order of the input edges.
const Eigen::MatrixXi & in_ordered_faces () const
Order of the input edges.
Static Public Member Functions
static std::unique_ptr< Mesh > create (const std::string &path, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (GEO::Mesh &M, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (const Eigen::MatrixXd &vertices, const Eigen::MatrixXi &cells, const bool non_conforming=false)
factory to build the proper mesh
Protected Member Functions
Mesh ()=default
Construct a new Mesh object.
virtual bool load (const std::string &path)=0
loads a mesh from the path
virtual bool load (const GEO::Mesh &M)=0
loads a mesh from a geo mesh
Protected Attributes
std::vector< ElementType > elements_tag_
list of element types
std::vector< int > boundary_ids_
list of surface labels
std::vector< int > body_ids_
list of volume labels
Eigen::MatrixXi orders_
list of geometry orders, one per cell
bool is_rational_ = false
stores if the mesh is rational
std::vector< EdgeNodes > edge_nodes_
high-oder nodes associates to edges
std::vector< FaceNodes > face_nodes_
high-oder nodes associates to faces
std::vector< CellNodes > cell_nodes_
high-oder nodes associates to cells
std::vector< std::vector< double > > cell_weights_
weights associates to cells for rational polynomail meshes
Eigen::VectorXi in_ordered_vertices_
Order of the input vertices.
Eigen::MatrixXi in_ordered_edges_
Order of the input edges.
Eigen::MatrixXi in_ordered_faces_
Order of the input faces, TODO: change to std::vector of Eigen::Vector.
Private Member Functions
virtual bool build_from_matrices (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F)=0
build a mesh from matrices
Detailed Description
Abstract mesh class to capture 2d/3d conforming and non-conforming meshes.
Definition at line 36 of file Mesh.hpp.
Constructor & Destructor Documentation
Mesh() [1/3]
polyfem::mesh::Mesh::Mesh () protected default
Construct a new Mesh object.
~Mesh()
virtual polyfem::mesh::Mesh::~Mesh () virtual default
Destroy the Mesh object.
Mesh() [2/3]
polyfem::mesh::Mesh::Mesh (Mesh &&) default
Construct a new Mesh object.
Mesh() [3/3]
polyfem::mesh::Mesh::Mesh (const Mesh &) default
Construct a new Mesh object.
Member Function Documentation
attach_higher_order_nodes()
virtual void polyfem::mesh::Mesh::attach_higher_order_nodes (const Eigen::MatrixXd & V, const std::vector< std::vector< int > > & nodes) pure virtual
attach high order nodes
Parameters
[in] V nodes
[in] nodes list of nodes per element
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
barycentric_coords()
virtual void polyfem::mesh::Mesh::barycentric_coords (const RowVectorNd & p, const int el_id, Eigen::MatrixXd & coord) const pure virtual
constructs barycentric coodiantes for a point p.
WARNING works only for simplices
Parameters
[in] p query point
[in] el_id element id
[out] coord matrix containing the barycentric coodinates
Implemented in polyfem::mesh::Mesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::Mesh3D.
bounding_box()
virtual void polyfem::mesh::Mesh::bounding_box (RowVectorNd & min, RowVectorNd & max) const pure virtual
computes the bbox of the mesh
Parameters
[out] min min coodiante
[out] max max coodiante
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::solver::OperatorSplittingSolver::initialize_mesh().
build_from_matrices()
virtual bool polyfem::mesh::Mesh::build_from_matrices (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F) private pure virtual
build a mesh from matrices
Parameters
[in] V vertices
[in] F connectivity
Returns
if success
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
cell_barycenter()
virtual RowVectorNd polyfem::mesh::Mesh::cell_barycenter (const int c) const pure virtual
cell barycenter
Parameters
[in] c global cell index
Returns
cell barycenter
Implemented in polyfem::mesh::CMesh3D, polyfem::mesh::NCMesh3D, and polyfem::mesh::Mesh2D.
Referenced by cell_barycenters(), polyfem::mesh::Mesh3D::cell_node(), and polyfem::mesh::MeshNodes::node_id_from_primitive().
cell_barycenters()
void polyfem::mesh::Mesh::cell_barycenters (Eigen::MatrixXd & barycenters) const
all cells barycenters
Parameters
[out] barycenters
Definition at line 332 of file Mesh.cpp.
References cell_barycenter(), dimension(), and n_cells().
Referenced by polyfem::mesh::Mesh3D::compute_element_barycenters(), polyfem::mesh::CMesh3D::triangulate_faces(), and polyfem::mesh::NCMesh3D::triangulate_faces().
cell_vertex()
virtual int polyfem::mesh::Mesh::cell_vertex (const int f_id, const int lv_id) const pure virtual
id of the vertex of a cell
Parameters
[in] f_id global cell id
[in] lv_id local vertex id
Returns
vertex id
Implemented in polyfem::mesh::CMesh3D, polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::solver::OperatorSplittingSolver::advection_PIC(), and polyfem::solver::OperatorSplittingSolver::initialize_mesh().
cell_weights()
const std::vector< double > & polyfem::mesh::Mesh::cell_weights (const int cell_index) const inline
weights for rational polynomial meshes
Parameters
[in] cell_index index of the cell
Returns
list of weights
Definition at line 450 of file Mesh.hpp.
References cell_weights_.
compute_body_ids()
virtual void polyfem::mesh::Mesh::compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> & marker) pure virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id and barycenter and returns an integer
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
compute_boundary_ids() [1/5]
virtual void polyfem::mesh::Mesh::compute_boundary_ids (const double eps) pure virtual
computes the selection based on the bbx of the mesh.
Left gets 1, bottom 2, right 3, top 4, front 5, back 6
Parameters
[in] eps tolerance for proximity
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
compute_boundary_ids() [2/5]
virtual void polyfem::mesh::Mesh::compute_boundary_ids (const std::function< int(const RowVectorNd &)> & marker) pure virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and returns an integer
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
compute_boundary_ids() [3/5]
virtual void polyfem::mesh::Mesh::compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> & marker) pure virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and true/false if the element is on the boundary and returns an integer
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
compute_boundary_ids() [4/5]
virtual void polyfem::mesh::Mesh::compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> & marker) pure virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id, barycenter, and true/false if the element is on the boundary and returns an integer
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
compute_boundary_ids() [5/5]
virtual void polyfem::mesh::Mesh::compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> & marker) pure virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the list of vertices and true/false if the element is on the boundary and returns an integer
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
compute_element_barycenters()
virtual void polyfem::mesh::Mesh::compute_element_barycenters (Eigen::MatrixXd & barycenters) const pure virtual
utility for 2d/3d.
In 2d it returns face_barycenters, in 3d it returns cell_barycenters
Parameters
[out] barycenters the barycenters
Implemented in polyfem::mesh::Mesh2D, and polyfem::mesh::Mesh3D.
compute_elements_tag()
virtual void polyfem::mesh::Mesh::compute_elements_tag () pure virtual
compute element types, see ElementType
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
create() [1/3]
std::unique_ptr< Mesh > polyfem::mesh::Mesh::create (const Eigen::MatrixXd & vertices, const Eigen::MatrixXi & cells, const bool non_conforming = false) static
factory to build the proper mesh
Parameters
[in] vertices list of vertices
[in] cells list of cells
[in] non_conforming yes or no for non conforming mesh
Returns
pointer to the mesh
Definition at line 244 of file Mesh.cpp.
References edges(), elasticity_rhs::f, and p_bases::vertices.
create() [2/3]
std::unique_ptr< Mesh > polyfem::mesh::Mesh::create (const std::string & path, const bool non_conforming = false) static
factory to build the proper mesh
Parameters
[in] path mesh path
[in] non_conforming yes or no for non conforming mesh
Returns
pointer to the mesh
Definition at line 163 of file Mesh.cpp.
References create(), polyfem::utils::StringUtils::endswith(), polyfem::utils::MshReader::load(), polyfem::logger(), eigs::path, p_bases::tmp, and p_bases::vertices.
Referenced by create(), and polyfem::State::load_mesh().
create() [3/3]
std::unique_ptr< Mesh > polyfem::mesh::Mesh::create (GEO::Mesh & M, const bool non_conforming = false) static
factory to build the proper mesh
Parameters
[in] M geo mesh
[in] non_conforming yes or no for non conforming mesh
Returns
pointer to the mesh
Definition at line 82 of file Mesh.cpp.
References elasticity_rhs::f, polyfem::mesh::is_planar(), and polyfem::logger().
dimension()
int polyfem::mesh::Mesh::dimension () const inline
utily for dimension
Returns
int 2 or 3
Definition at line 132 of file Mesh.hpp.
References is_volume().
Referenced by cell_barycenters(), polyfem::assembler::GenericTensorProblem::dirichlet_bc(), polyfem::problem::ElasticProblem::dirichlet_bc(), polyfem::problem::TorsionElasticProblem::dirichlet_bc(), polyfem::problem::DoubleTorsionElasticProblem::dirichlet_bc(), polyfem::problem::ElasticProblemZeroBC::dirichlet_bc(), polyfem::problem::WalkProblem::dirichlet_bc(), polyfem::problem::PointBasedTensorProblem::dirichlet_bc(), edge_barycenters(), face_barycenters(), polyfem::solver::OperatorSplittingSolver::initialize_mesh(), polyfem::assembler::RhsAssembler::integrate_bc(), polyfem::assembler::RhsAssembler::lsq_bc(), polyfem::mesh::MeshNodes::MeshNodes(), polyfem::assembler::GenericTensorProblem::neumann_bc(), polyfem::problem::ElasticCantileverExact::neumann_bc(), polyfem::problem::PointBasedTensorProblem::neumann_bc(), polyfem::assembler::RhsAssembler::sample_bc(), and polyfem::assembler::Problem::setup_bc().
edge_barycenter()
virtual RowVectorNd polyfem::mesh::Mesh::edge_barycenter (const int e) const pure virtual
edge barycenter
Parameters
[in] e global edge index
Returns
edge barycenter
Implemented in polyfem::mesh::CMesh3D, polyfem::mesh::NCMesh3D, polyfem::mesh::CMesh2D, and polyfem::mesh::NCMesh2D.
Referenced by edge_barycenters(), and polyfem::mesh::MeshNodes::node_id_from_primitive().
edge_barycenters()
void polyfem::mesh::Mesh::edge_barycenters (Eigen::MatrixXd & barycenters) const
all edges barycenters
Parameters
[out] barycenters
Definition at line 314 of file Mesh.cpp.
References dimension(), edge_barycenter(), and n_edges().
edge_length()
virtual double polyfem::mesh::Mesh::edge_length (const int gid) const inline virtual
edge length
Parameters
[in] gid global edge id
Returns
edge length
Reimplemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 248 of file Mesh.hpp.
Referenced by polyfem::utils::BoundarySampler::quadrature_for_polygon_edge(), polyfem::utils::BoundarySampler::quadrature_for_quad_edge(), and polyfem::utils::BoundarySampler::quadrature_for_tri_edge().
edge_vertex()
virtual int polyfem::mesh::Mesh::edge_vertex (const int e_id, const int lv_id) const pure virtual
id of the edge vertex
Parameters
[in] e_id global edge id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by edges(), edges_to_ids(), polyfem::mesh::Mesh2D::get_edges(), polyfem::mesh::Mesh3D::get_edges(), and polyfem::State::get_sidesets().
edges()
std::vector< std::pair< int, int > > polyfem::mesh::Mesh::edges () const
list of sorted edges.
Used to map to input vertices
Returns
ist of sorted edges
Definition at line 411 of file Mesh.cpp.
References edge_vertex(), and n_edges().
Referenced by create().
edges_to_ids()
std::unordered_map< std::pair< int, int >, size_t, HashPair > polyfem::mesh::Mesh::edges_to_ids () const
map from edge (pair of v id) to the id of the edge
Returns
map
Definition at line 443 of file Mesh.cpp.
References edge_vertex(), and n_edges().
elements_boxes()
virtual void polyfem::mesh::Mesh::elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > & boxes) const pure virtual
constructs a box around every element (3d cell, 2d face)
Parameters
[out] boxes axis aligned bounding boxes
Implemented in polyfem::mesh::Mesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::Mesh3D.
elements_tag()
const std::vector< ElementType > & polyfem::mesh::Mesh::elements_tag () const inline
Returns the elements types.
Returns
vector of element types
Definition at line 351 of file Mesh.hpp.
References elements_tag_.
Referenced by polyfem::mesh::CMesh3D::refine().
face_barycenter()
virtual RowVectorNd polyfem::mesh::Mesh::face_barycenter (const int f) const pure virtual
face barycenter
Parameters
[in] f global face index
Returns
face barycenter
Implemented in polyfem::mesh::CMesh3D, polyfem::mesh::NCMesh3D, and polyfem::mesh::Mesh2D.
Referenced by face_barycenters(), polyfem::State::get_sidesets(), polyfem::State::interpolate_boundary_function(), polyfem::State::interpolate_boundary_function_at_vertices(), polyfem::State::interpolate_boundary_tensor_function(), and polyfem::mesh::MeshNodes::node_id_from_primitive().
face_barycenters()
void polyfem::mesh::Mesh::face_barycenters (Eigen::MatrixXd & barycenters) const
all face barycenters
Parameters
[out] barycenters
Definition at line 323 of file Mesh.cpp.
References dimension(), elasticity_rhs::f, face_barycenter(), and n_faces().
Referenced by polyfem::mesh::Mesh2D::compute_element_barycenters(), polyfem::mesh::CMesh3D::triangulate_faces(), and polyfem::mesh::NCMesh3D::triangulate_faces().
face_vertex()
virtual int polyfem::mesh::Mesh::face_vertex (const int f_id, const int lv_id) const pure virtual
id of the face vertex
Parameters
[in] f_id global face id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::basis::MVPolygonalBasis2d::build_bases(), faces(), faces_to_ids(), polyfem::State::get_sidesets(), polyfem::mesh::to_geogram_mesh(), and polyfem::mesh::Mesh3D::tri_area().
faces()
std::vector< std::vector< int > > polyfem::mesh::Mesh::faces () const
list of sorted faces.
Used to map to input vertices
Returns
ist of sorted faces
Definition at line 427 of file Mesh.cpp.
References face_vertex(), n_face_vertices(), n_faces(), and p_bases::tmp.
Referenced by polyfem::mesh::CMesh3D::attach_higher_order_nodes().
faces_to_ids()
std::unordered_map< std::vector< int >, size_t, HashVector > polyfem::mesh::Mesh::faces_to_ids () const
map from face (tuple of v id) to the id of the face
Returns
map
Definition at line 459 of file Mesh.cpp.
References elasticity_rhs::f, face_vertex(), n_face_vertices(), and n_faces().
get_body_id()
virtual int polyfem::mesh::Mesh::get_body_id (const int primitive) const inline virtual
Get the volume selection of an element (cell in 3d, face in 2d)
Parameters
[in] primitive element id
Returns
label of element
Reimplemented in polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 412 of file Mesh.hpp.
References body_ids_, and has_body_ids().
Referenced by polyfem::assembler::GenericTensorProblem::initial_acceleration(), polyfem::assembler::GenericTensorProblem::initial_solution(), polyfem::assembler::GenericScalarProblem::initial_solution(), and polyfem::assembler::GenericTensorProblem::initial_velocity().
get_boundary_id()
virtual int polyfem::mesh::Mesh::get_boundary_id (const int primitive) const inline virtual
Get the boundary selection of an element (face in 3d, edge in 2d)
Parameters
[in] primitive element id
Returns
label of element
Reimplemented in polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 407 of file Mesh.hpp.
References boundary_ids_.
Referenced by polyfem::assembler::GenericTensorProblem::dirichlet_bc(), polyfem::assembler::GenericScalarProblem::dirichlet_bc(), polyfem::problem::ElasticProblem::dirichlet_bc(), polyfem::problem::TorsionElasticProblem::dirichlet_bc(), polyfem::problem::DoubleTorsionElasticProblem::dirichlet_bc(), polyfem::problem::ElasticProblemZeroBC::dirichlet_bc(), polyfem::problem::WalkProblem::dirichlet_bc(), polyfem::problem::NodeProblem::dirichlet_bc(), polyfem::problem::PointBasedTensorProblem::dirichlet_bc(), polyfem::problem::ConstantVelocity::dirichlet_bc(), polyfem::problem::DrivenCavity::dirichlet_bc(), polyfem::problem::DrivenCavityC0::dirichlet_bc(), polyfem::problem::DrivenCavitySmooth::dirichlet_bc(), polyfem::problem::Flow::dirichlet_bc(), polyfem::problem::FlowWithObstacle::dirichlet_bc(), polyfem::problem::CornerFlow::dirichlet_bc(), polyfem::problem::Lshape::dirichlet_bc(), polyfem::problem::UnitFlowWithObstacle::dirichlet_bc(), polyfem::problem::StokesLawProblem::dirichlet_bc(), polyfem::problem::Airfoil::dirichlet_bc(), polyfem::State::get_sidesets(), polyfem::assembler::GenericTensorProblem::neumann_bc(), polyfem::assembler::GenericScalarProblem::neumann_bc(), polyfem::problem::ElasticCantileverExact::neumann_bc(), polyfem::problem::NodeProblem::neumann_bc(), polyfem::problem::PointBasedTensorProblem::neumann_bc(), and polyfem::assembler::Problem::setup_bc().
get_edges() [1/2]
virtual void polyfem::mesh::Mesh::get_edges (Eigen::MatrixXd & p0, Eigen::MatrixXd & p1) const pure virtual
Get all the edges.
Parameters
[out] p0 edge first vertex
[out] p1 edge second vertex
Implemented in polyfem::mesh::Mesh2D, and polyfem::mesh::Mesh3D.
Referenced by polyfem::solver::OperatorSplittingSolver::initialize_hashtable().
get_edges() [2/2]
virtual void polyfem::mesh::Mesh::get_edges (Eigen::MatrixXd & p0, Eigen::MatrixXd & p1, const std::vector< bool > & valid_elements) const pure virtual
Get all the edges according to valid_elements selection.
Parameters
[out] p0 edge first vertex
[out] p1 edge second vertex
[in] valid_elements flag to compute the edge
Implemented in polyfem::mesh::Mesh2D, and polyfem::mesh::Mesh3D.
has_body_ids()
virtual bool polyfem::mesh::Mesh::has_body_ids () const inline virtual
checks if volumes selections are available
Returns
volumes selections are available
Definition at line 426 of file Mesh.hpp.
References body_ids_.
Referenced by get_body_id().
has_boundary_ids()
bool polyfem::mesh::Mesh::has_boundary_ids () const inline
checks if surface selections are available
Returns
surface selections are available
Definition at line 422 of file Mesh.hpp.
References boundary_ids_.
has_poly()
bool polyfem::mesh::Mesh::has_poly () const inline
checks if the mesh has polytopes
Returns
if the mesh has polytopes
Definition at line 463 of file Mesh.hpp.
References is_polytope(), and n_elements().
in_ordered_edges()
const Eigen::MatrixXi & polyfem::mesh::Mesh::in_ordered_edges () const inline
Order of the input edges.
Returns
matrix of indices one per edge, pointing to the two vertices
Definition at line 504 of file Mesh.hpp.
References in_ordered_edges_.
in_ordered_faces()
const Eigen::MatrixXi & polyfem::mesh::Mesh::in_ordered_faces () const inline
Order of the input edges.
Returns
matrix of indices one per faces, pointing to the face vertices
Definition at line 508 of file Mesh.hpp.
References in_ordered_faces_.
in_ordered_vertices()
const Eigen::VectorXi & polyfem::mesh::Mesh::in_ordered_vertices () const inline
Order of the input vertices.
Returns
vector of indices, one per vertex
Definition at line 500 of file Mesh.hpp.
References in_ordered_vertices_.
is_boundary_edge()
virtual bool polyfem::mesh::Mesh::is_boundary_edge (const int edge_global_id) const pure virtual
is edge boundary
Parameters
[in] edge_global_id global edge id
Returns
is edge boundary
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::mesh::MeshNodes::MeshNodes(), and polyfem::mesh::MeshNodes::node_ids_from_edge().
is_boundary_element()
virtual bool polyfem::mesh::Mesh::is_boundary_element (const int element_global_id) const pure virtual
is cell boundary
Parameters
[in] element_global_id global cell id
Returns
is cell boundary
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
is_boundary_face()
virtual bool polyfem::mesh::Mesh::is_boundary_face (const int face_global_id) const pure virtual
is face boundary
Parameters
[in] face_global_id global face id
Returns
is face boundary
Implemented in polyfem::mesh::Mesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::State::interpolate_boundary_function(), polyfem::mesh::MeshNodes::MeshNodes(), polyfem::mesh::MeshNodes::node_ids_from_face(), and polyfem::mesh::to_geogram_mesh().
is_boundary_vertex()
virtual bool polyfem::mesh::Mesh::is_boundary_vertex (const int vertex_global_id) const pure virtual
is vertex boundary
Parameters
[in] vertex_global_id global vertex id
Returns
is vertex boundary
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::mesh::MeshNodes::MeshNodes().
is_conforming()
virtual bool polyfem::mesh::Mesh::is_conforming () const pure virtual
if the mesh is conforming
Returns
if the mesh is conforming
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::State::extract_boundary_mesh().
is_cube()
bool polyfem::mesh::Mesh::is_cube (const int el_id) const
checks if element is cube compatible
Parameters
[in] el_id element id
Returns
is cube compatible
Definition at line 364 of file Mesh.cpp.
References elements_tag_, polyfem::mesh::InterfaceCube, polyfem::mesh::MultiSingularBoundaryCube, polyfem::mesh::MultiSingularInteriorCube, polyfem::mesh::RegularBoundaryCube, polyfem::mesh::RegularInteriorCube, polyfem::mesh::SimpleSingularBoundaryCube, and polyfem::mesh::SimpleSingularInteriorCube.
Referenced by polyfem::mesh::Mesh3D::cell_node(), polyfem::mesh::Mesh3D::face_node(), polyfem::mesh::CMesh2D::face_node(), polyfem::mesh::Mesh3D::get_ordered_vertices_from_hex(), polyfem::basis::FEBasis3d::hex_face_local_nodes(), polyfem::State::interpolate_boundary_function(), polyfem::State::interpolate_boundary_function_at_vertices(), polyfem::basis::FEBasis2d::quad_edge_local_nodes(), and polyfem::mesh::to_geogram_mesh().
is_linear()
bool polyfem::mesh::Mesh::is_linear () inline
check if the mesh is linear
Returns
if the mesh is linear
Definition at line 477 of file Mesh.hpp.
References orders_.
is_polytope()
bool polyfem::mesh::Mesh::is_polytope (const int el_id) const
checks if element is polygon compatible
Parameters
[in] el_id element id
Returns
is polygon compatible
Definition at line 377 of file Mesh.cpp.
References polyfem::mesh::BoundaryPolytope, elements_tag_, and polyfem::mesh::InteriorPolytope.
Referenced by polyfem::basis::PolygonalBasis2d::build_bases(), polyfem::basis::PolygonalBasis3d::build_bases(), polyfem::basis::MVPolygonalBasis2d::build_bases(), polyfem::basis::PolygonalBasis2d::compute_integral_constraints(), polyfem::basis::PolygonalBasis3d::compute_integral_constraints(), polyfem::mesh::extract_polyhedra(), and has_poly().
is_rational()
bool polyfem::mesh::Mesh::is_rational () const inline
check if curved mesh has rational polynomials elements
Returns
if mesh is rational
Definition at line 229 of file Mesh.hpp.
References is_rational_.
is_simplex()
bool polyfem::mesh::Mesh::is_simplex (const int el_id) const
checks if element is simples compatible
Parameters
[in] el_id element id
Returns
is simples compatible
Definition at line 406 of file Mesh.cpp.
References elements_tag_, and polyfem::mesh::Simplex.
Referenced by polyfem::mesh::Mesh2D::barycentric_coords(), polyfem::mesh::CMesh3D::barycentric_coords(), polyfem::mesh::Mesh3D::barycentric_coords(), polyfem::mesh::Mesh3D::cell_node(), polyfem::mesh::Mesh3D::face_node(), polyfem::mesh::CMesh2D::face_node(), polyfem::State::interpolate_boundary_function(), polyfem::State::interpolate_boundary_function_at_vertices(), polyfem::mesh::MeshNodes::node_ids_from_cell(), polyfem::mesh::MeshNodes::node_ids_from_face(), polyfem::mesh::CMesh2D::refine(), polyfem::basis::FEBasis3d::tet_face_local_nodes(), and polyfem::basis::FEBasis2d::tri_edge_local_nodes().
is_spline_compatible()
bool polyfem::mesh::Mesh::is_spline_compatible (const int el_id) const
checks if element is spline compatible
Parameters
[in] el_id element id
Returns
is spline compatible
Definition at line 344 of file Mesh.cpp.
References elements_tag_, is_volume(), polyfem::mesh::RegularBoundaryCube, and polyfem::mesh::RegularInteriorCube.
is_volume()
virtual bool polyfem::mesh::Mesh::is_volume () const pure virtual
checks if mesh is volume
Returns
if mesh is volumetric
Implemented in polyfem::mesh::Mesh2D, and polyfem::mesh::Mesh3D.
Referenced by polyfem::assembler::RhsAssembler::assemble(), polyfem::assembler::RhsAssembler::compute_energy(), dimension(), polyfem::problem::NodeValues::init(), polyfem::assembler::RhsAssembler::integrate_bc(), is_spline_compatible(), load_boundary_ids(), polyfem::mesh::MeshNodes::MeshNodes(), n_elements(), polyfem::utils::BoundarySampler::normal_for_polygon_edge(), polyfem::utils::BoundarySampler::quadrature_for_polygon_edge(), polyfem::utils::BoundarySampler::sample_polygon_edge(), and polyfem::assembler::RhsAssembler::time_bc().
load() [1/2]
virtual bool polyfem::mesh::Mesh::load (const GEO::Mesh & M) protected pure virtual
loads a mesh from a geo mesh
Parameters
[in] M geo mesh
Returns
if success
Implemented in polyfem::mesh::CMesh3D, polyfem::mesh::NCMesh3D, polyfem::mesh::CMesh2D, and polyfem::mesh::NCMesh2D.
load() [2/2]
virtual bool polyfem::mesh::Mesh::load (const std::string & path) protected pure virtual
loads a mesh from the path
Parameters
[in] path file location
Returns
if success
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
load_boundary_ids()
void polyfem::mesh::Mesh::load_boundary_ids (const std::string & path) virtual
loads the boundary selections for a file
Parameters
[in] path file's path
Definition at line 383 of file Mesh.cpp.
References boundary_ids_, is_volume(), n_edges(), n_faces(), and eigs::path.
n_cells()
virtual int polyfem::mesh::Mesh::n_cells () const pure virtual
number of cells
Returns
number of cells
Implemented in polyfem::mesh::Mesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by cell_barycenters(), polyfem::mesh::extract_polyhedra(), polyfem::mesh::MeshNodes::MeshNodes(), n_elements(), and polyfem::mesh::to_geogram_mesh().
n_edges()
virtual int polyfem::mesh::Mesh::n_edges () const pure virtual
number of edges
Returns
number of edges
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by edge_barycenters(), edges(), edges_to_ids(), polyfem::mesh::Mesh2D::get_edges(), polyfem::mesh::Mesh3D::get_edges(), polyfem::State::get_sidesets(), polyfem::problem::NodeValues::init(), load_boundary_ids(), and polyfem::mesh::MeshNodes::MeshNodes().
n_elements()
int polyfem::mesh::Mesh::n_elements () const inline
utitlity to return the number of elements, cells or faces in 3d and 2d
Returns
number of elements
Definition at line 142 of file Mesh.hpp.
References is_volume(), n_cells(), and n_faces().
Referenced by polyfem::basis::PolygonalBasis2d::build_bases(), polyfem::basis::PolygonalBasis3d::build_bases(), polyfem::basis::MVPolygonalBasis2d::build_bases(), polyfem::mesh::CMesh2D::compute_body_ids(), polyfem::mesh::CMesh3D::compute_body_ids(), polyfem::basis::PolygonalBasis2d::compute_integral_constraints(), polyfem::basis::PolygonalBasis3d::compute_integral_constraints(), polyfem::compute_integral_constraints(), polyfem::mesh::Mesh2D::elements_boxes(), polyfem::mesh::CMesh3D::elements_boxes(), polyfem::mesh::Mesh3D::elements_boxes(), has_poly(), polyfem::State::interpolate_boundary_function(), polyfem::State::interpolate_boundary_function_at_vertices(), polyfem::State::interpolate_boundary_tensor_function(), and polyfem::mesh::CMesh2D::refine().
n_face_vertices()
virtual int polyfem::mesh::Mesh::n_face_vertices (const int f_id) const pure virtual
number of vertices of a face
Parameters
[in] f_id global face id
Returns
number of vertices
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::basis::MVPolygonalBasis2d::build_bases(), polyfem::basis::compute_epsilon(), polyfem::mesh::extract_polyhedra(), polyfem::mesh::Mesh2D::face_barycenter(), faces(), faces_to_ids(), polyfem::mesh::Mesh2D::get_edges(), polyfem::State::get_sidesets(), polyfem::mesh::to_geogram_mesh(), and polyfem::mesh::Mesh3D::tri_area().
n_faces()
virtual int polyfem::mesh::Mesh::n_faces () const pure virtual
number of faces
Returns
number of faces
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::mesh::extract_polyhedra(), face_barycenters(), faces(), faces_to_ids(), polyfem::State::get_sidesets(), polyfem::problem::NodeValues::init(), load_boundary_ids(), polyfem::mesh::MeshNodes::MeshNodes(), n_elements(), and polyfem::mesh::to_geogram_mesh().
n_vertices()
virtual int polyfem::mesh::Mesh::n_vertices () const pure virtual
number of vertices
Returns
number of vertices
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
Referenced by polyfem::State::compute_vertex_values(), polyfem::mesh::extract_polyhedra(), polyfem::mesh::Mesh2D::face_barycenter(), polyfem::solver::OperatorSplittingSolver::initialize_mesh(), polyfem::mesh::MeshNodes::MeshNodes(), polyfem::mesh::to_geogram_mesh(), and polyfem::mesh::Mesh3D::tri_area().
normalize()
virtual void polyfem::mesh::Mesh::normalize () pure virtual
normalize the mesh
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
operator=() [1/2]
Mesh & polyfem::mesh::Mesh::operator= (const Mesh &) default
Returns
Mesh&
operator=() [2/2]
Mesh & polyfem::mesh::Mesh::operator= (Mesh &&) default
Copy constructor.
Returns
Mesh&
orders()
const Eigen::MatrixXi & polyfem::mesh::Mesh::orders () const inline
order of each element
Returns
matrix containing order
Definition at line 225 of file Mesh.hpp.
References orders_.
point()
virtual RowVectorNd polyfem::mesh::Mesh::point (const int global_index) const pure virtual
point coordinates
Parameters
[in] global_index global vertex index
Returns
RowVectorNd
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::NCMesh3D, and polyfem::mesh::CMesh3D.
Referenced by polyfem::solver::OperatorSplittingSolver::advection_PIC(), polyfem::mesh::Mesh2D::barycentric_coords(), polyfem::mesh::Mesh3D::barycentric_coords(), polyfem::basis::MVPolygonalBasis2d::build_bases(), polyfem::mesh::Mesh3D::cell_node(), polyfem::basis::compute_epsilon(), polyfem::mesh::Mesh3D::edge_node(), polyfem::mesh::extract_polyhedra(), polyfem::mesh::Mesh2D::face_barycenter(), polyfem::mesh::Mesh3D::face_node(), polyfem::mesh::Mesh2D::get_edges(), polyfem::mesh::Mesh3D::get_edges(), polyfem::State::get_sidesets(), polyfem::solver::OperatorSplittingSolver::initialize_mesh(), polyfem::mesh::MeshNodes::node_id_from_primitive(), polyfem::mesh::to_geogram_mesh(), and polyfem::mesh::Mesh3D::tri_area().
prepare_mesh()
virtual void polyfem::mesh::Mesh::prepare_mesh () inline virtual
method used to finalize the mesh.
It computes the cached stuff used in navigation
Reimplemented in polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 458 of file Mesh.hpp.
quad_area()
virtual double polyfem::mesh::Mesh::quad_area (const int gid) const inline virtual
area of a quad face of an hex mesh
Parameters
[in] gid global face id
Returns
face area
Reimplemented in polyfem::mesh::CMesh3D.
Definition at line 257 of file Mesh.hpp.
Referenced by polyfem::utils::BoundarySampler::quadrature_for_quad_face().
refine()
virtual void polyfem::mesh::Mesh::refine (const int n_refinement, const double t) pure virtual
refine the mesh
Parameters
[in] n_refinement number of refinements
[in] t position of the refinement location (0.5 for standard refinement)
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
set_body_ids() [1/2]
virtual void polyfem::mesh::Mesh::set_body_ids (const Eigen::VectorXi & body_ids) inline virtual
Set the volume sections.
Parameters
[in] body_ids matrix of labels, one per element
Reimplemented in polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 398 of file Mesh.hpp.
References body_ids_.
set_body_ids() [2/2]
virtual void polyfem::mesh::Mesh::set_body_ids (const std::vector< int > & body_ids) inline virtual
Set the volume sections.
Parameters
[in] body_ids vector of labels, one per element
Reimplemented in polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 394 of file Mesh.hpp.
References body_ids_.
set_boundary_ids()
virtual void polyfem::mesh::Mesh::set_boundary_ids (const std::vector< int > & boundary_ids) inline virtual
Set the boundary selection from a vector.
Parameters
[in] boundary_ids vector one value per element
Reimplemented in polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 390 of file Mesh.hpp.
References boundary_ids_.
set_cell_weights()
void polyfem::mesh::Mesh::set_cell_weights (const std::vector< std::vector< double > > & in_cell_weights) inline
Set the cell weights for rational polynomial meshes.
Parameters
[in] in_cell_weights vector of vector containing the weights, one per cell
Definition at line 454 of file Mesh.hpp.
References cell_weights_.
set_is_rational()
void polyfem::mesh::Mesh::set_is_rational (const bool in_is_rational) inline
Set the is rational object.
Parameters
[in] in_is_rational flag to enable/disable rational polynomials
Definition at line 233 of file Mesh.hpp.
References is_rational_.
set_tag()
void polyfem::mesh::Mesh::set_tag (const int el, const ElementType type) inline
changes the element type
Parameters
[in] el element id
[in] type type of the element
Definition at line 356 of file Mesh.hpp.
References elements_tag_.
tri_area()
virtual double polyfem::mesh::Mesh::tri_area (const int gid) const inline virtual
area of a tri face of a tet mesh
Parameters
[in] gid global face id
Returns
tet area
Reimplemented in polyfem::mesh::Mesh3D.
Definition at line 266 of file Mesh.hpp.
Referenced by polyfem::utils::BoundarySampler::quadrature_for_tri_face().
triangulate_faces()
virtual void polyfem::mesh::Mesh::triangulate_faces (Eigen::MatrixXi & tris, Eigen::MatrixXd & pts, std::vector< int > & ranges) const pure virtual
generate a triangular representation of every face
Parameters
[out] tris triangles connectivity
[out] pts triangles vertices
[out] ranges connection to original faces
Implemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, polyfem::mesh::CMesh3D, and polyfem::mesh::NCMesh3D.
update_elements_tag()
virtual void polyfem::mesh::Mesh::update_elements_tag () inline virtual
Update elements types.
Reimplemented in polyfem::mesh::CMesh2D, polyfem::mesh::NCMesh2D, and polyfem::mesh::NCMesh3D.
Definition at line 242 of file Mesh.hpp.
Member Data Documentation
body_ids_
std::vector<int> polyfem::mesh::Mesh::body_ids_ protected
list of volume labels
Definition at line 527 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::compute_body_ids(), polyfem::mesh::NCMesh2D::compute_body_ids(), polyfem::mesh::CMesh3D::compute_body_ids(), polyfem::mesh::NCMesh3D::compute_body_ids(), get_body_id(), has_body_ids(), and set_body_ids().
boundary_ids_
std::vector<int> polyfem::mesh::Mesh::boundary_ids_ protected
list of surface labels
Definition at line 525 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::compute_boundary_ids(), polyfem::mesh::NCMesh2D::compute_boundary_ids(), polyfem::mesh::NCMesh3D::compute_boundary_ids(), polyfem::mesh::CMesh3D::compute_boundary_ids(), get_boundary_id(), has_boundary_ids(), load_boundary_ids(), and set_boundary_ids().
cell_nodes_
std::vector<CellNodes> polyfem::mesh::Mesh::cell_nodes_ protected
high-oder nodes associates to cells
Definition at line 538 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::attach_higher_order_nodes(), polyfem::mesh::CMesh3D::attach_higher_order_nodes(), polyfem::mesh::CMesh2D::build_from_matrices(), polyfem::mesh::CMesh3D::build_from_matrices(), polyfem::mesh::Mesh3D::cell_node(), polyfem::mesh::CMesh2D::load(), polyfem::mesh::CMesh3D::load(), and polyfem::mesh::CMesh3D::normalize().
cell_weights_
std::vector<std::vector<double> > polyfem::mesh::Mesh::cell_weights_ protected
weights associates to cells for rational polynomail meshes
Definition at line 540 of file Mesh.hpp.
Referenced by cell_weights(), and set_cell_weights().
edge_nodes_
std::vector<EdgeNodes> polyfem::mesh::Mesh::edge_nodes_ protected
high-oder nodes associates to edges
Definition at line 534 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::attach_higher_order_nodes(), polyfem::mesh::CMesh3D::attach_higher_order_nodes(), polyfem::mesh::CMesh2D::build_from_matrices(), polyfem::mesh::CMesh3D::build_from_matrices(), polyfem::mesh::Mesh3D::edge_node(), polyfem::mesh::CMesh2D::edge_node(), polyfem::mesh::CMesh2D::load(), polyfem::mesh::CMesh3D::load(), and polyfem::mesh::CMesh3D::normalize().
elements_tag_
std::vector<ElementType> polyfem::mesh::Mesh::elements_tag_ protected
list of element types
Definition at line 523 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::compute_elements_tag(), polyfem::mesh::NCMesh2D::compute_elements_tag(), polyfem::mesh::CMesh3D::compute_elements_tag(), polyfem::mesh::NCMesh3D::compute_elements_tag(), elements_tag(), is_cube(), is_polytope(), is_simplex(), is_spline_compatible(), set_tag(), polyfem::mesh::CMesh2D::update_elements_tag(), polyfem::mesh::NCMesh2D::update_elements_tag(), and polyfem::mesh::NCMesh3D::update_elements_tag().
face_nodes_
std::vector<FaceNodes> polyfem::mesh::Mesh::face_nodes_ protected
high-oder nodes associates to faces
Definition at line 536 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::attach_higher_order_nodes(), polyfem::mesh::CMesh3D::attach_higher_order_nodes(), polyfem::mesh::CMesh2D::build_from_matrices(), polyfem::mesh::CMesh3D::build_from_matrices(), polyfem::mesh::Mesh3D::face_node(), polyfem::mesh::CMesh2D::face_node(), polyfem::mesh::CMesh2D::load(), polyfem::mesh::CMesh3D::load(), and polyfem::mesh::CMesh3D::normalize().
in_ordered_edges_
Eigen::MatrixXi polyfem::mesh::Mesh::in_ordered_edges_ protected
Order of the input edges.
Definition at line 545 of file Mesh.hpp.
Referenced by in_ordered_edges().
in_ordered_faces_
Eigen::MatrixXi polyfem::mesh::Mesh::in_ordered_faces_ protected
Order of the input faces, TODO: change to std::vector of Eigen::Vector.
Definition at line 547 of file Mesh.hpp.
Referenced by in_ordered_faces().
in_ordered_vertices_
Eigen::VectorXi polyfem::mesh::Mesh::in_ordered_vertices_ protected
Order of the input vertices.
Definition at line 543 of file Mesh.hpp.
Referenced by in_ordered_vertices().
is_rational_
bool polyfem::mesh::Mesh::is_rational_ = false protected
stores if the mesh is rational
Definition at line 531 of file Mesh.hpp.
Referenced by is_rational(), and set_is_rational().
orders_
Eigen::MatrixXi polyfem::mesh::Mesh::orders_ protected
list of geometry orders, one per cell
Definition at line 529 of file Mesh.hpp.
Referenced by polyfem::mesh::CMesh2D::attach_higher_order_nodes(), polyfem::mesh::CMesh3D::attach_higher_order_nodes(), polyfem::mesh::Mesh3D::cell_node(), polyfem::mesh::Mesh3D::edge_node(), polyfem::mesh::CMesh2D::edge_node(), polyfem::mesh::Mesh3D::face_node(), polyfem::mesh::CMesh2D::face_node(), is_linear(), orders(), polyfem::mesh::CMesh2D::refine(), and polyfem::mesh::CMesh3D::refine().
The documentation for this class was generated from the following files:
src/polyfem/mesh/Mesh.hpp
src/polyfem/mesh/Mesh.cpp