PolyFEM: polyfem::time_integrator::ImplicitNewmark Class Reference
polyfem::time_integrator::ImplicitNewmark Class Reference
Implicit Newmark-beta method.
#include <ImplicitNewmark.hpp>
Public Member Functions
ImplicitNewmark ()
void set_parameters (const nlohmann::json &params) override
Set the gamma and beta parameters from a json object.
void update_quantities (const Eigen::VectorXd &x) override
Update the time integration quantaties (i.e., \(x\), \(v\), and \(a\)).
Eigen::VectorXd x_tilde () const override
Compute the predicted solution to be used in the inertia term \((x-\tilde{x})^TM(x-\tilde{x})\).
double acceleration_scaling () const override
Compute the acceleration scaling used to scale forces when integrating a second order ODE.
double beta () const
\(\beta\) parameter for blending accelerations in the solution update.
double gamma () const
\(\gamma\) parameter for blending accelerations in the velocity update.
Public Member Functions inherited from polyfem::time_integrator::ImplicitTimeIntegrator
ImplicitTimeIntegrator ()
virtual ~ImplicitTimeIntegrator ()=default
virtual void set_parameters (const nlohmann::json &params)
Set the time integrator parameters from a json object.
virtual void init (const Eigen::VectorXd &x_prev, const Eigen::VectorXd &v_prev, const Eigen::VectorXd &a_prev, double dt)
Initialize the time integrator with the previous values for \(x\), \(v\), and \(a\).
virtual void update_quantities (const Eigen::VectorXd &x)=0
Update the time integration quantaties (i.e., \(x\), \(v\), and \(a\)).
virtual Eigen::VectorXd x_tilde () const =0
Compute the predicted solution to be used in the inertia term \((x-\tilde{x})^TM(x-\tilde{x})\).
virtual double acceleration_scaling () const =0
Compute the acceleration scaling used to scale forces when integrating a second order ODE.
const double & dt () const
Access the time step size.
virtual void save_raw (const std::string &x_path, const std::string &v_path, const std::string &a_path) const
Save the values of $x$, \(v\), and \(a\).
const Eigen::VectorXd & x_prev () const
Get the most recent previous solution value.
const Eigen::VectorXd & v_prev () const
Get the most recent previous velocity value.
const Eigen::VectorXd & a_prev () const
Get the most recent previous acceleration value.
Protected Attributes
double m_beta = 0.25
\(\beta\) parameter for blending accelerations in the solution update.
double m_gamma = 0.5
\(\gamma\) parameter for blending accelerations in the velocity update.
Protected Attributes inherited from polyfem::time_integrator::ImplicitTimeIntegrator
double _dt = 1
Time step size.
std::deque< Eigen::VectorXd > x_prevs
Store the necessary previous values of the solution for single or multi-step integration.
std::deque< Eigen::VectorXd > v_prevs
Store the necessary previous values of the velocity for single or multi-step integration.
std::deque< Eigen::VectorXd > a_prevs
Store the necessary previous values of the acceleration for single or multi-step integration.
Additional Inherited Members
Static Public Member Functions inherited from polyfem::time_integrator::ImplicitTimeIntegrator
static std::shared_ptr< ImplicitTimeIntegrator > construct_time_integrator (const std::string &name)
Factory method for constructing implicit time integrators from the name of the integrator.
static const std::vector< std::string > & get_time_integrator_names ()
Get a vector of the names of possible ImplicitTimeIntegrators.
Protected Member Functions inherited from polyfem::time_integrator::ImplicitTimeIntegrator
Eigen::VectorXd & x_prev ()
Convenience functions for getting a mutable reference to the most recent previous solution.
Eigen::VectorXd & v_prev ()
Convenience functions for getting a mutable reference to the most recent previous velocity.
Eigen::VectorXd & a_prev ()
Convenience functions for getting a mutable reference to the most recent previous acceleration.
Detailed Description
Implicit Newmark-beta method.
\[ x^{t+1} = x^t + \Delta t v^t + \frac{\Delta t^2}{2}((1-2\beta)a^t + 2 \beta a^{t+1})\\ v^{t+1} = v^t + (1-\gamma)\Delta ta^t + \gamma \Delta ta^{t+1} \]
See also
https://en.wikipedia.org/wiki/Newmark-beta_method
Definition at line 13 of file ImplicitNewmark.hpp.
Constructor & Destructor Documentation
ImplicitNewmark()
polyfem::time_integrator::ImplicitNewmark::ImplicitNewmark () inline
Definition at line 16 of file ImplicitNewmark.hpp.
Member Function Documentation
acceleration_scaling()
double polyfem::time_integrator::ImplicitNewmark::acceleration_scaling () const override virtual
Compute the acceleration scaling used to scale forces when integrating a second order ODE.
\[ \beta \Delta t^2 \]
Implements polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 25 of file ImplicitNewmark.cpp.
References beta(), and polyfem::time_integrator::ImplicitTimeIntegrator::dt().
beta()
double polyfem::time_integrator::ImplicitNewmark::beta () const inline
\(\beta\) parameter for blending accelerations in the solution update.
Definition at line 40 of file ImplicitNewmark.hpp.
References m_beta.
Referenced by acceleration_scaling(), update_quantities(), and x_tilde().
gamma()
double polyfem::time_integrator::ImplicitNewmark::gamma () const inline
\(\gamma\) parameter for blending accelerations in the velocity update.
Definition at line 42 of file ImplicitNewmark.hpp.
References m_gamma.
Referenced by update_quantities().
set_parameters()
void polyfem::time_integrator::ImplicitNewmark::set_parameters (const nlohmann::json & params) override virtual
Set the gamma and beta parameters from a json object.
Parameters
params json containing {"gamma": 0.5, "beta": 0.25}
Reimplemented from polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 5 of file ImplicitNewmark.cpp.
References m_beta, and m_gamma.
update_quantities()
void polyfem::time_integrator::ImplicitNewmark::update_quantities (const Eigen::VectorXd & x) override virtual
Update the time integration quantaties (i.e., \(x\), \(v\), and \(a\)).
Parameters
x new solution vector
Implements polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 11 of file ImplicitNewmark.cpp.
References polyfem::time_integrator::ImplicitTimeIntegrator::a_prev(), beta(), polyfem::time_integrator::ImplicitTimeIntegrator::dt(), gamma(), p_bases::tmp, polyfem::time_integrator::ImplicitTimeIntegrator::v_prev(), x, and polyfem::time_integrator::ImplicitTimeIntegrator::x_prev().
x_tilde()
Eigen::VectorXd polyfem::time_integrator::ImplicitNewmark::x_tilde () const override virtual
Compute the predicted solution to be used in the inertia term \((x-\tilde{x})^TM(x-\tilde{x})\).
\[ \tilde{x} = x^t + \Delta t (v^t + (0.5 - \beta) \Delta t a^t) \]
Returns
value for \(\tilde{x}\)
Implements polyfem::time_integrator::ImplicitTimeIntegrator.
Definition at line 20 of file ImplicitNewmark.cpp.
References polyfem::time_integrator::ImplicitTimeIntegrator::a_prev(), beta(), polyfem::time_integrator::ImplicitTimeIntegrator::dt(), polyfem::time_integrator::ImplicitTimeIntegrator::v_prev(), and polyfem::time_integrator::ImplicitTimeIntegrator::x_prev().
Member Data Documentation
m_beta
double polyfem::time_integrator::ImplicitNewmark::m_beta = 0.25 protected
\(\beta\) parameter for blending accelerations in the solution update.
Definition at line 46 of file ImplicitNewmark.hpp.
Referenced by beta(), and set_parameters().
m_gamma
double polyfem::time_integrator::ImplicitNewmark::m_gamma = 0.5 protected
\(\gamma\) parameter for blending accelerations in the velocity update.
Definition at line 48 of file ImplicitNewmark.hpp.
Referenced by gamma(), and set_parameters().
The documentation for this class was generated from the following files:
src/polyfem/time_integrator/ImplicitNewmark.hpp
src/polyfem/time_integrator/ImplicitNewmark.cpp