PolyFEM: polyfem::State Class Reference
polyfem::State Class Reference
main class that contains the polyfem solver and all its state
#include <State.hpp>
Public Member Functions
~State ()=default
State (const unsigned int max_threads=std::numeric_limits< unsigned int >::max())
Constructor.
void init (const json &args, const std::string &output_dir="")
initialize the polyfem solver with a json settings
void init_time ()
initialize time settings if args contains "time"
void init_logger (const std::string &log_file, const spdlog::level::level_enum log_level, const bool is_quiet)
initalizing the logger
void init_logger (std::ostream &os, const spdlog::level::level_enum log_level)
initalizing the logger writes to an output stream
void set_log_level (const spdlog::level::level_enum log_level)
change log level
std::string get_log ()
gets the output log as json this is not what gets printed but more informative information, eg it contains runtimes, errors, etc.
std::string formulation () const
return the formulation (checks if the problem is scalar or not and delas wih multiphisics)
bool iso_parametric () const
check if using iso parametric bases
void build_basis ()
builds the bases step 2 of solve
void assemble_rhs ()
compute rhs, step 3 of solve
void assemble_stiffness_mat ()
assemble matrices, step 4 of solve
int n_boundary_samples () const
quadrature used for projecting boundary conditions
void p_refinement (const mesh::Mesh2D &mesh2d)
compute a priori prefinement in 2d, fills disc_orders
void p_refinement (const mesh::Mesh3D &mesh3d)
compute a priori prefinement in 3d, fills disc_orders
void solve_problem ()
solves the proble, step 5
void solve ()
solves the problem, call other methods
void init_transient (Eigen::VectorXd &c_sol)
initialize transient solver
void solve_transient_navier_stokes_split (const int time_steps, const double dt, const assembler::RhsAssembler &rhs_assembler)
solves transient navier stokes with operator splitting
void solve_transient_navier_stokes (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler &rhs_assembler, Eigen::VectorXd &c_sol)
solves transient navier stokes with FEM
void solve_transient_scalar (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler &rhs_assembler, Eigen::VectorXd &x)
solves transient scalar problem
void solve_transient_tensor_linear (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler &rhs_assembler)
solves transient linear problem
void solve_transient_tensor_non_linear (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler &rhs_assembler)
solves transient tensor non linear problem
void solve_transient_tensor_non_linear_init (const double t0, const double dt, const assembler::RhsAssembler &rhs_assembler)
initialized the non linear solver
void solve_transient_tensor_non_linear_step (const double t0, const double dt, const int t, json &solver_info)
steps trought time
void solve_linear ()
solves a linear problem
void solve_navier_stokes ()
solves a navier stokes
void solve_non_linear ()
solves nonlinear problems
template<typename ProblemType >
std::shared_ptr< cppoptlib::NonlinearSolver< ProblemType > > make_nl_solver () const
factory to create the nl solver depdending on input
void compute_mesh_size (const mesh::Mesh &mesh, const std::vector< ElementBases > &bases, const int n_samples)
computes the mesh size, it samples every edges n_samples times uses curved_mesh_size (false by default) to compute the size of the linear mesh
void load_mesh (bool non_conforming=false, const std::vector< std::string > &names=std::vector< std::string >(), const std::vector< Eigen::MatrixXi > &cells=std::vector< Eigen::MatrixXi >(), const std::vector< Eigen::MatrixXd > &vertices=std::vector< Eigen::MatrixXd >())
loads the mesh from the json arguments
void load_febio (const std::string &path, const json &args_in)
loads a febio file, uses args_in for default, [DEPRECATED]
void load_mesh (GEO::Mesh &meshin, const std::function< int(const RowVectorNd &)> &boundary_marker, bool non_conforming=false, bool skip_boundary_sideset=false)
loads the mesh from a geogram mesh
void load_mesh (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, bool non_conforming=false)
loads the mesh from V and F,
void set_boundary_side_set (const std::function< int(const RowVectorNd &)> &boundary_marker)
set the boundary sideset from a lambda that takes the face/edge barycenter
void set_boundary_side_set (const std::function< int(const RowVectorNd &, bool)> &boundary_marker)
set the boundary sideset from a lambda that takes the face/edge barycenter and a flag if the face/edge is boundary or not (used to set internal boundaries)
void set_boundary_side_set (const std::function< int(const std::vector< int > &, bool)> &boundary_marker)
set the boundary sideset from a lambda that takes the face/edge vertices and a flag if the face/edge is boundary or not (used to set internal boundaries)
void reset_mesh ()
Resets the mesh.
void build_collision_mesh ()
extracts the boundary mesh for collision, called in build_basis
void extract_boundary_mesh (const std::vector< ElementBases > &bases, Eigen::MatrixXd &boundary_nodes_pos, Eigen::MatrixXi &boundary_edges, Eigen::MatrixXi &boundary_triangles) const
extracts the boundary mesh
bool is_obstacle_vertex (const size_t vi) const
checks if vertex is obstacle
void extract_vis_boundary_mesh ()
extracts the boundary mesh for visualization, called in build_basis
void compute_errors ()
compute the errors, not part of solve
void export_data ()
saves all data on the disk according to the input params
void save_json (std::ostream &out)
saves the output statistic to a stream
void save_json (nlohmann::json &j)
saves the output statistic to a json object
void save_json ()
saves the output statistic to disc accoding to params
void compute_vertex_values (int actual_dim, const std::vector< ElementBases > &basis, const MatrixXd &fun, Eigen::MatrixXd &result)
evaluates the function fun at the vertices on the mesh
void compute_stress_at_quadrature_points (const MatrixXd &fun, Eigen::MatrixXd &result, Eigen::VectorXd &von_mises)
compute von mises stress at quadrature points for the function fun, also compute the interpolated function
void interpolate_function (const int n_points, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, const bool use_sampler, const bool boundary_only)
interpolate the function fun.
void interpolate_function (const int n_points, const int actual_dim, const std::vector< ElementBases > &basis, const MatrixXd &fun, MatrixXd &result, const bool use_sampler, const bool boundary_only)
interpolate the function fun.
void interpolate_at_local_vals (const int el_index, const MatrixXd &local_pts, MatrixXd &result, MatrixXd &result_grad)
interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
void interpolate_at_local_vals (const int el_index, const MatrixXd &local_pts, const MatrixXd &fun, MatrixXd &result, MatrixXd &result_grad)
interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
void interpolate_at_local_vals (const int el_index, const int actual_dim, const std::vector< ElementBases > &bases, const MatrixXd &local_pts, const MatrixXd &fun, MatrixXd &result, MatrixXd &result_grad)
interpolate the function fun and its gradient at in element el_index for the local_pts in the reference element using bases bases interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
bool check_scalar_value (const Eigen::MatrixXd &fun, const bool use_sampler, const bool boundary_only)
checks if mises are not nan
void compute_scalar_value (const int n_points, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, const bool use_sampler, const bool boundary_only)
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid)
void average_grad_based_function (const int n_points, const MatrixXd &fun, MatrixXd &result_scalar, MatrixXd &result_tensor, const bool use_sampler, const bool boundary_only)
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid) the scalar value is averaged around every node to make it continuos
void compute_tensor_value (const int n_points, const Eigen::MatrixXd &fun, Eigen::MatrixXd &result, const bool use_sampler, const bool boundary_only)
compute tensor quantity (ie stress tensor or velocy)
void interpolate_boundary_function (const MatrixXd &pts, const MatrixXi &faces, const MatrixXd &fun, const bool compute_avg, MatrixXd &result)
computes integrated solution (fun) per surface face.
void interpolate_boundary_function_at_vertices (const MatrixXd &pts, const MatrixXi &faces, const MatrixXd &fun, MatrixXd &result)
computes integrated solution (fun) per surface face vertex.
void interpolate_boundary_tensor_function (const MatrixXd &pts, const MatrixXi &faces, const MatrixXd &fun, const MatrixXd &disp, const bool compute_avg, MatrixXd &result, MatrixXd &stresses, MatrixXd &mises, const bool skip_orientation=false)
computes traction foces for fun (tensor * surface normal) result, stress tensor, and von mises, per surface face.
void interpolate_boundary_tensor_function (const MatrixXd &pts, const MatrixXi &faces, const MatrixXd &fun, const bool compute_avg, MatrixXd &result, MatrixXd &stresses, MatrixXd &mises, const bool skip_orientation=false)
same as interpolate_boundary_tensor_function with disp=0
void get_sidesets (Eigen::MatrixXd &pts, Eigen::MatrixXi &faces, Eigen::MatrixXd &sidesets)
returns a triangulated representation of the sideset.
std::string root_path () const
Get the root path for the state (e.g., args["root_path"] or ".")
std::string resolve_input_path (const std::string &path, const bool only_if_exists=false) const
Resolve input path relative to root_path() if the path is not absolute.
std::string resolve_output_path (const std::string &path) const
Resolve output path relative to output_dir if the path is not absolute.
void compute_mesh_stats ()
compute stats (counts els type, mesh lenght, etc), step 1 of solve
void build_vis_mesh (Eigen::MatrixXd &points, Eigen::MatrixXi &tets, Eigen::MatrixXi &el_id, Eigen::MatrixXd &discr)
builds visualzation mesh, upsampled mesh used for visualization the visualization mesh is a dense mesh per element all disconnected it also retuns the mapping to element id and discretization of every elment works in 2 and 3d.
void build_high_oder_vis_mesh (Eigen::MatrixXd &points, std::vector< std::vector< int > > &elements, Eigen::MatrixXi &el_id, Eigen::MatrixXd &discr)
builds high-der visualzation mesh per element all disconnected it also retuns the mapping to element id and discretization of every elment works in 2 and 3d.
void save_vtu (const std::string &name, const double t)
saves the vtu file for time t
void save_volume (const std::string &path, const double t)
saves the volume vtu file
void save_surface (const std::string &name)
saves the surface vtu file for for surface quantites, eg traction forces
void save_wire (const std::string &name, const double t)
saves the wireframe
void save_pvd (const std::string &name, const std::function< std::string(int)> &vtu_names, int time_steps, double t0, double dt, int skip_frame=1)
save a PVD of a time dependent simulation
void save_timestep (const double time, const int t, const double t0, const double dt)
saves a timestep
void save_subsolve (const int i, const int t)
saves a subsolve when save_solve_sequence_debug is true
void get_sampled_solution (Eigen::MatrixXd &points, Eigen::MatrixXi &tets, Eigen::MatrixXd &fun, bool boundary_only=false)
samples to solution on the visualization mesh and return the vis mesh (points and tets) and the interpolated values (fun)
void get_stresses (Eigen::MatrixXd &fun, bool boundary_only=false)
samples to stess tensor on the visualization mesh and return them (fun)
void get_sampled_mises (Eigen::MatrixXd &fun, bool boundary_only=false)
samples to von mises stesses on the visualization mesh and return them (fun)
void get_sampled_mises_avg (Eigen::MatrixXd &fun, Eigen::MatrixXd &tfun, bool boundary_only=false)
samples to averaged von mises stesses on the visualization mesh and return them (fun)
Public Attributes
json args
main input arguments containing all defaults
std::string output_dir
Directory for output files.
Density density
density of the input, default=1.
double avg_mass
average system mass, used for contact with IPC
Eigen::VectorXi in_node_to_node
Inpute nodes (including high-order) to polyfem nodes, only for isoparametric.
Eigen::VectorXi in_primitive_to_primitive
maps in vertices/edges/faces/cells to polyfem vertices/edges/faces/cells
assembler::AssemblerUtils assembler
assembler, it dispatches call to the differnt assembers based on the formulation
std::shared_ptr< assembler::Problem > problem
current problem, it contains rhs and bc
std::vector< ElementBases > bases
FE bases, the size is #elements.
std::vector< ElementBases > pressure_bases
FE pressure bases for mixed elements, the size is #elements.
std::vector< ElementBases > geom_bases
Geometric mapping bases, if the elements are isoparametric, this list is empty.
std::map< int, Eigen::MatrixXd > polys
polygons, used since poly have no geom mapping
std::map< int, std::pair< Eigen::MatrixXd, Eigen::MatrixXi > > polys_3d
polyhedra, used since poly have no geom mapping
Eigen::VectorXi disc_orders
vector of discretization oders, used when not all elements have the same degree, one per element
std::shared_ptr< polyfem::mesh::MeshNodes > mesh_nodes
Mapping from input nodes to FE nodes.
assembler::AssemblyValsCache ass_vals_cache
used to store assembly values for small problems
assembler::AssemblyValsCache pressure_ass_vals_cache
used to store assembly values for pressure for small problems
StiffnessMatrix stiffness
stiffness and mass matrix.
StiffnessMatrix mass
Mass matrix, it is computed only for time dependent problems.
Eigen::MatrixXd rhs
System righ-hand side.
Eigen::MatrixXd sol
solution
Eigen::MatrixXd pressure
pressure solution, if the problem is not mixed, pressure is empty
bool use_avg_pressure
use average pressure for stokes problem to fix the additional dofs, true by default if false, it will fix one pressure node to zero
int n_bases
number of bases
int n_pressure_bases
number of pressure bases
StepData step_data
timedependent stuff cached
std::vector< int > boundary_nodes
list of boundary nodes
std::vector< int > pressure_boundary_nodes
list of neumann boundary nodes
std::vector< mesh::LocalBoundary > total_local_boundary
mapping from elements to nodes for all mesh
std::vector< mesh::LocalBoundary > local_boundary
mapping from elements to nodes for dirichlet boundary conditions
std::vector< mesh::LocalBoundary > local_neumann_boundary
mapping from elements to nodes for neumann boundary conditions
std::map< int, InterfaceData > poly_edge_to_data
nodes on the boundary of polygonal elements, used for harmonic bases
std::vector< Eigen::MatrixXd > input_dirichelt
Matrices containing the input per node dirichelt.
bool has_dhat = false
stores if input json contains dhat
std::unique_ptr< mesh::Mesh > mesh
current mesh, it can be a Mesh2D or Mesh3D
mesh::Obstacle obstacle
Obstacles used in collisions.
utils::RefElementSampler ref_element_sampler
used to sample the solution
Eigen::MatrixXd boundary_nodes_pos
boundary mesh used for collision boundary_nodes_pos contains the total number of nodes, the internal ones are zero for high-order fem the faces are triangulated this is currently supported only for tri and tet meshes
Eigen::MatrixXi boundary_edges
edge indices into full vertices
Eigen::MatrixXi boundary_triangles
triangle indices into full vertices
ipc::CollisionMesh collision_mesh
ipc collision mesh into surface vertices
Eigen::MatrixXd boundary_vis_vertices
boundary visualization mesh vertices
Eigen::MatrixXd boundary_vis_local_vertices
boundary visualization mesh vertices pre image in ref element
Eigen::MatrixXi boundary_vis_elements
boundary visualization mesh connectivity
Eigen::MatrixXi boundary_vis_elements_ids
boundary visualization mesh elements ids
Eigen::MatrixXi boundary_vis_primitive_ids
boundary visualization mesh edge/face id
Eigen::MatrixXd boundary_vis_normals
boundary visualization mesh normals
Eigen::MatrixXd grid_points
grid mesh points to export solution sampled on a grid
Eigen::MatrixXi grid_points_to_elements
grid mesh mapping to fe elements
Eigen::MatrixXd grid_points_bc
grid mesh boundaries
Eigen::Vector4d spectrum
spectrum of the stiffness matrix, enable only if POLYSOLVE_WITH_SPECTRA is ON (off by default)
json solver_info
information of the solver, eg num iteration, time, errors, etc the informations varies depending on the solver
double mesh_size
max edge lenght
double min_edge_length
min edge lenght
double average_edge_length
avg edge lenght
double l2_err
errors, lp_err is in fact an L8 error
double linf_err
double lp_err
double h1_err
double h1_semi_err
double grad_max_err
long long nn_zero
non zeros and sytem matrix size num dof is the total dof in the system
long long mat_size
long long num_dofs
double building_basis_time
time to construct the basis
double loading_mesh_time
time to load the mesh
double computing_poly_basis_time
time to build the polygonal/polyhedral bases
double assembling_stiffness_mat_time
time to assembly
double assigning_rhs_time
time to computing the rhs
double solving_time
time to solve
double computing_errors_time
time to compute error
double max_angle
statiscs on angle, compute only when using p_ref (false by default)
double sigma_max
statiscs on tri/tet quality, compute only when using p_ref (false by default)
double sigma_min
double sigma_avg
int n_flipped
number of flipped elements, compute only when using count_flipped_els (false by default)
int simplex_count
statiscs on the mesh (simplices)
int regular_count
statiscs on the mesh (regular quad/hex part of the mesh), see Polyspline paper for desciption
int regular_boundary_count
statiscs on the mesh (regular quad/hex boundary part of the mesh), see Polyspline paper for desciption
int simple_singular_count
statiscs on the mesh (irregular quad/hex part of the mesh), see Polyspline paper for desciption
int multi_singular_count
statiscs on the mesh (irregular quad/hex part of the mesh), see Polyspline paper for desciption
int boundary_count
statiscs on the mesh (boundary quads/hexs), see Polyspline paper for desciption
int non_regular_boundary_count
statiscs on the mesh (irregular boundary quad/hex part of the mesh), see Polyspline paper for desciption
int non_regular_count
statiscs on the mesh (irregular quad/hex part of the mesh), see Polyspline paper for desciption
int undefined_count
statiscs on the mesh (not quad/hex simplex), see Polyspline paper for desciption
int multi_singular_boundary_count
statiscs on the mesh (irregular boundary quad/hex part of the mesh), see Polyspline paper for desciption
bool solve_export_to_file = true
flag to decide if exporting the time dependent solution to files or save it in the solution_frames array
std::vector< SolutionFrame > solution_frames
saves the frames in a vector instead of VTU
Private Member Functions
void init_logger (const std::vector< spdlog::sink_ptr > &sinks, const spdlog::level::level_enum log_level)
initalizing the logger meant for internal usage
void build_node_mapping ()
void sol_to_pressure ()
splits the solution in solution and pressure for mixed problems
void build_polygonal_basis ()
builds bases for polygons, called inside build_basis
void set_materials ()
set the multimaterial, this is mean for internal usage.
Detailed Description
main class that contains the polyfem solver and all its state
Definition at line 79 of file State.hpp.
Constructor & Destructor Documentation
~State()
polyfem::State::~State () default
State()
polyfem::State::State (const unsigned int max_threads = std::numeric_limits<unsigned int>::max())
Constructor.
Parameters
[in] max_threads max number of threads
Definition at line 79 of file StateInit.cpp.
Member Function Documentation
assemble_rhs()
void polyfem::State::assemble_rhs ()
compute rhs, step 3 of solve
Definition at line 1270 of file State.cpp.
References formulation(), polyfem::logger(), mesh, and n_bases.
Referenced by solve().
assemble_stiffness_mat()
void polyfem::State::assemble_stiffness_mat ()
assemble matrices, step 4 of solve
Definition at line 1149 of file State.cpp.
References args, ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_mass_matrix(), polyfem::assembler::AssemblerUtils::assemble_mixed_problem(), polyfem::assembler::AssemblerUtils::assemble_pressure_problem(), polyfem::assembler::AssemblerUtils::assemble_problem(), assembler, assembling_stiffness_mat_time, avg_mass, bases, density, formulation(), geom_bases, polyfem::assembler::AssemblerUtils::is_fluid(), polyfem::assembler::AssemblerUtils::is_linear(), polyfem::assembler::AssemblerUtils::is_mixed(), iso_parametric(), polyfem::logger(), mass, mat_size, polyfem::assembler::AssemblerUtils::merge_mixed_matrices(), mesh, n_bases, n_pressure_bases, nn_zero, num_dofs, pressure, pressure_ass_vals_cache, pressure_bases, problem, sol, stiffness, and use_avg_pressure.
Referenced by solve().
average_grad_based_function()
void polyfem::State::average_grad_based_function (const int n_points, const MatrixXd & fun, MatrixXd & result_scalar, MatrixXd & result_tensor, const bool use_sampler, const bool boundary_only)
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid) the scalar value is averaged around every node to make it continuos
Parameters
[in] n_points is the size of the output.
[in] fun function to used
[out] result_scalar scalar value
[out] result_tensor tensor value
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 399 of file StateInterpolation.cpp.
References assembler, polyfem::basis::ElementBases::bases, bases, polyfem::assembler::AssemblerUtils::compute_scalar_value(), disc_orders, formulation(), geom_bases, polyfem::basis::Basis::global(), interpolate_function(), iso_parametric(), polyfem::logger(), mesh, n_bases, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), problem, polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), vals, and polyfem::quadrature::Quadrature::weights.
Referenced by save_volume().
build_basis()
void polyfem::State::build_basis ()
builds the bases step 2 of solve
Definition at line 582 of file State.cpp.
References args, assembler, bases, boundary_nodes, disc_orders, formulation(), geom_bases, input_dirichelt, polyfem::assembler::AssemblerUtils::is_mixed(), iso_parametric(), local_boundary, local_neumann_boundary, polyfem::logger(), mesh, n_bases, n_pressure_bases, non_regular_boundary_count, non_regular_count, p_refinement(), poly_edge_to_data, polys, pressure, pressure_bases, problem, polyfem::utils::read_matrix(), rhs, sigma_avg, sigma_max, sigma_min, sol, stiffness, p_bases::tmp, total_local_boundary, and undefined_count.
Referenced by solve().
build_collision_mesh()
void polyfem::State::build_collision_mesh ()
extracts the boundary mesh for collision, called in build_basis
Definition at line 1101 of file State.cpp.
References bases, boundary_edges, boundary_nodes_pos, boundary_triangles, polyfem::mesh::Obstacle::codim_v(), collision_mesh, polyfem::mesh::Obstacle::e(), extract_boundary_mesh(), polyfem::mesh::Obstacle::f(), is_obstacle_vertex(), polyfem::mesh::Obstacle::n_vertices(), obstacle, and polyfem::mesh::Obstacle::v().
build_high_oder_vis_mesh()
void polyfem::State::build_high_oder_vis_mesh (Eigen::MatrixXd & points, std::vector< std::vector< int > > & elements, Eigen::MatrixXi & el_id, Eigen::MatrixXd & discr)
builds high-der visualzation mesh per element all disconnected it also retuns the mapping to element id and discretization of every elment works in 2 and 3d.
if the mesh is not simplicial it gets tri/tet halized
Parameters
[out] points mesh points
[out] elements mesh high-order cells
[out] el_id mapping from points to elements id
[out] discr mapping from points to discretization order
Definition at line 949 of file StateOutput.cpp.
References bases, disc_orders, polyfem::logger(), mesh, n_bases, p_bases::nodes, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), p_bases::points, polyfem::autogen::q_nodes_2d(), and polyfem::autogen::q_nodes_3d().
Referenced by save_volume().
build_node_mapping()
void polyfem::State::build_node_mapping () private
Definition at line 182 of file State.cpp.
References in_node_to_node, in_primitive_to_primitive, mesh, and mesh_nodes.
build_polygonal_basis()
void polyfem::State::build_polygonal_basis () private
builds bases for polygons, called inside build_basis
Definition at line 1027 of file State.cpp.
References args, assembler, bases, polyfem::basis::PolygonalBasis2d::build_bases(), polyfem::basis::PolygonalBasis3d::build_bases(), polyfem::basis::MVPolygonalBasis2d::build_bases(), computing_poly_basis_time, formulation(), geom_bases, iso_parametric(), local_boundary, polyfem::logger(), mesh, n_bases, n_pressure_bases, poly_edge_to_data, polys, polys_3d, pressure, rhs, sol, and stiffness.
build_vis_mesh()
void polyfem::State::build_vis_mesh (Eigen::MatrixXd & points, Eigen::MatrixXi & tets, Eigen::MatrixXi & el_id, Eigen::MatrixXd & discr)
builds visualzation mesh, upsampled mesh used for visualization the visualization mesh is a dense mesh per element all disconnected it also retuns the mapping to element id and discretization of every elment works in 2 and 3d.
if the mesh is not simplicial it gets tri/tet halized
Parameters
[out] points mesh points
[out] tets mesh cells
[out] el_id mapping from points to elements id
[out] discr mapping from points to discretization order
Definition at line 814 of file StateOutput.cpp.
References args, bases, disc_orders, geom_bases, iso_parametric(), polyfem::logger(), mesh, n_bases, p_bases::points, polys, polys_3d, ref_element_sampler, and p_bases::tmp.
Referenced by save_volume().
check_scalar_value()
bool polyfem::State::check_scalar_value (const Eigen::MatrixXd & fun, const bool use_sampler, const bool boundary_only)
checks if mises are not nan
Parameters
[in] fun function to used
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Returns
if mises are nan
Definition at line 833 of file StateInterpolation.cpp.
References assembler, bases, polyfem::assembler::AssemblerUtils::compute_scalar_value(), disc_orders, formulation(), geom_bases, iso_parametric(), polyfem::logger(), mesh, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polys, polys_3d, problem, polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), and ref_element_sampler.
compute_errors()
void polyfem::State::compute_errors ()
compute the errors, not part of solve
Definition at line 1446 of file State.cpp.
References args, polyfem::logger(), mesh, n_bases, problem, rhs, and sol.
compute_mesh_size()
void polyfem::State::compute_mesh_size (const mesh::Mesh & mesh, const std::vector< ElementBases > & bases, const int n_samples)
computes the mesh size, it samples every edges n_samples times uses curved_mesh_size (false by default) to compute the size of the linear mesh
Parameters
[in] mesh to compute stats
[in] bases geom bases
[in] n_samples used for curved meshes
Definition at line 329 of file State.cpp.
References average_edge_length, mesh_size, and min_edge_length.
compute_mesh_stats()
void polyfem::State::compute_mesh_stats ()
compute stats (counts els type, mesh lenght, etc), step 1 of solve
Definition at line 171 of file StateLoad.cpp.
References bases, boundary_count, boundary_nodes, geom_bases, local_boundary, local_neumann_boundary, polyfem::logger(), mesh, multi_singular_boundary_count, multi_singular_count, n_bases, n_pressure_bases, non_regular_boundary_count, non_regular_count, poly_edge_to_data, polys, pressure, pressure_bases, regular_boundary_count, regular_count, rhs, simple_singular_count, simplex_count, sol, stiffness, and undefined_count.
Referenced by solve().
compute_scalar_value()
void polyfem::State::compute_scalar_value (const int n_points, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, const bool use_sampler, const bool boundary_only)
computes scalar quantity of funtion (ie von mises for elasticity and norm of velocity for fluid)
Parameters
[in] n_points is the size of the output.
[in] fun function to used
[out] result scalar value
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 908 of file StateInterpolation.cpp.
References assembler, bases, polyfem::assembler::AssemblerUtils::compute_scalar_value(), disc_orders, formulation(), geom_bases, iso_parametric(), polyfem::logger(), mesh, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polys, polys_3d, problem, polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), and ref_element_sampler.
Referenced by save_volume(), and save_wire().
compute_stress_at_quadrature_points()
void polyfem::State::compute_stress_at_quadrature_points (const MatrixXd & fun, Eigen::MatrixXd & result, Eigen::VectorXd & von_mises)
compute von mises stress at quadrature points for the function fun, also compute the interpolated function
Parameters
[in] fun function to used
[out] result output displacement
[out] von_mises output von mises
Definition at line 597 of file StateInterpolation.cpp.
References assembler, bases, polyfem::assembler::AssemblerUtils::compute_scalar_value(), polyfem::assembler::AssemblerUtils::compute_tensor_value(), disc_orders, elasticity_rhs::f, formulation(), geom_bases, iso_parametric(), polyfem::logger(), mesh, polyfem::quadrature::Quadrature::points, and problem.
Referenced by export_data().
compute_tensor_value()
void polyfem::State::compute_tensor_value (const int n_points, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, const bool use_sampler, const bool boundary_only)
compute tensor quantity (ie stress tensor or velocy)
Parameters
[in] n_points is the size of the output.
[in] fun function to used
[out] result resulting tensor
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 983 of file StateInterpolation.cpp.
References assembler, bases, polyfem::assembler::AssemblerUtils::compute_tensor_value(), disc_orders, formulation(), geom_bases, iso_parametric(), polyfem::logger(), mesh, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polys, polys_3d, problem, polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), and ref_element_sampler.
Referenced by save_volume().
compute_vertex_values()
void polyfem::State::compute_vertex_values (int actual_dim, const std::vector< ElementBases > & basis, const MatrixXd & fun, Eigen::MatrixXd & result)
evaluates the function fun at the vertices on the mesh
Parameters
[in] actual_dim is the size of the problem (e.g., 1 for Laplace, dim for elasticity)
[in] basis basis function
[in] fun function to interpolate
[out] result output
Definition at line 481 of file StateInterpolation.cpp.
References polyfem::basis::ElementBases::bases, polyfem::basis::ElementBases::evaluate_bases(), polyfem::mesh::Mesh3D::get_ordered_vertices_from_hex(), polyfem::mesh::Mesh3D::get_ordered_vertices_from_tet(), polyfem::basis::Basis::global(), polyfem::logger(), mesh, polyfem::mesh::Mesh::n_vertices(), ref_element_sampler, p_bases::tmp, and p_bases::vertices.
Referenced by export_data().
export_data()
void polyfem::State::export_data ()
saves all data on the disk according to the input params
Definition at line 684 of file StateOutput.cpp.
References args, bases, compute_stress_at_quadrature_points(), compute_vertex_values(), polyfem::basis::Basis::global(), in_node_to_node, polyfem::logger(), mesh, n_bases, p_bases::nodes, problem, resolve_output_path(), rhs, save_vtu(), sol, p_bases::tmp, and polyfem::utils::unflatten().
extract_boundary_mesh()
void polyfem::State::extract_boundary_mesh (const std::vector< ElementBases > & bases, Eigen::MatrixXd & boundary_nodes_pos, Eigen::MatrixXi & boundary_edges, Eigen::MatrixXi & boundary_triangles) const
extracts the boundary mesh
Parameters
[in] bases geom bases
[out] boundary_nodes_pos nodes positions
[out] boundary_edges edges
[out] boundary_triangles triangles
Definition at line 356 of file StateOutput.cpp.
References polyfem::basis::ElementBases::bases, bases, boundary_edges, boundary_nodes_pos, boundary_triangles, polyfem::mesh::Mesh::is_conforming(), polyfem::basis::ElementBases::local_nodes_for_primitive(), polyfem::logger(), mesh, n_bases, p_bases::nodes, and total_local_boundary.
Referenced by build_collision_mesh().
extract_vis_boundary_mesh()
void polyfem::State::extract_vis_boundary_mesh ()
extracts the boundary mesh for visualization, called in build_basis
Definition at line 152 of file StateOutput.cpp.
References bases, boundary_vis_elements, boundary_vis_elements_ids, boundary_vis_local_vertices, boundary_vis_normals, boundary_vis_primitive_ids, boundary_vis_vertices, geom_bases, iso_parametric(), mesh, p_bases::nn, polyfem::utils::BoundarySampler::normal_for_polygon_edge(), polyfem::utils::BoundarySampler::normal_for_quad_edge(), polyfem::utils::BoundarySampler::normal_for_quad_face(), polyfem::utils::BoundarySampler::normal_for_tri_edge(), polyfem::utils::BoundarySampler::normal_for_tri_face(), polyfem::utils::RefElementSampler::num_samples(), ref_element_sampler, polyfem::utils::BoundarySampler::sample_parametric_quad_edge(), polyfem::utils::BoundarySampler::sample_parametric_quad_face(), polyfem::utils::BoundarySampler::sample_parametric_tri_edge(), polyfem::utils::BoundarySampler::sample_parametric_tri_face(), polyfem::utils::BoundarySampler::sample_polygon_edge(), total_local_boundary, polyfem::mesh::Tri, vals, and p_bases::vertices.
formulation()
std::string polyfem::State::formulation () const
return the formulation (checks if the problem is scalar or not and delas wih multiphisics)
Returns
fomulation
Definition at line 272 of file State.cpp.
References args, polyfem::logger(), and p_bases::tmp.
Referenced by assemble_rhs(), assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_polygonal_basis(), check_scalar_value(), polyfem::solver::NLProblem::compute_cached_stiffness(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), polyfem::solver::NLProblem::current_rhs(), init_transient(), interpolate_boundary_tensor_function(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), polyfem::solver::NLProblem::NLProblem(), save_surface(), save_volume(), sol_to_pressure(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_init().
get_log()
std::string polyfem::State::get_log () inline
gets the output log as json this is not what gets printed but more informative information, eg it contains runtimes, errors, etc.
Definition at line 129 of file State.hpp.
References save_json().
get_sampled_mises()
void polyfem::State::get_sampled_mises (Eigen::MatrixXd & fun, bool boundary_only = false) inline
samples to von mises stesses on the visualization mesh and return them (fun)
Definition at line 789 of file State.hpp.
get_sampled_mises_avg()
void polyfem::State::get_sampled_mises_avg (Eigen::MatrixXd & fun, Eigen::MatrixXd & tfun, bool boundary_only = false) inline
samples to averaged von mises stesses on the visualization mesh and return them (fun)
Definition at line 806 of file State.hpp.
get_sampled_solution()
void polyfem::State::get_sampled_solution (Eigen::MatrixXd & points, Eigen::MatrixXi & tets, Eigen::MatrixXd & fun, bool boundary_only = false) inline
samples to solution on the visualization mesh and return the vis mesh (points and tets) and the interpolated values (fun)
Definition at line 757 of file State.hpp.
get_sidesets()
void polyfem::State::get_sidesets (Eigen::MatrixXd & pts, Eigen::MatrixXi & faces, Eigen::MatrixXd & sidesets)
returns a triangulated representation of the sideset.
sidesets contains integers mapping to faces
Parameters
[in] pts boundary points
[in] faces boundary faces
[out] sidesets resulting sidesets
Definition at line 61 of file StateOutput.cpp.
References polyfem::mesh::Mesh::edge_vertex(), elasticity_rhs::f, polyfem::mesh::Mesh::face_barycenter(), polyfem::mesh::Mesh::face_vertex(), polyfem::mesh::Mesh::get_boundary_id(), polyfem::logger(), mesh, polyfem::mesh::Mesh::n_edges(), polyfem::mesh::Mesh::n_face_vertices(), polyfem::mesh::Mesh::n_faces(), and polyfem::mesh::Mesh::point().
get_stresses()
void polyfem::State::get_stresses (Eigen::MatrixXd & fun, bool boundary_only = false) inline
samples to stess tensor on the visualization mesh and return them (fun)
Definition at line 772 of file State.hpp.
init()
void polyfem::State::init (const json & args, const std::string & output_dir = "")
initialize the polyfem solver with a json settings
Parameters
[in] args input arguments
[in] output_dir output directory
Definition at line 328 of file StateInit.cpp.
References polyfem::utils::apply_default_params(), args, polyfem::utils::check_for_unknown_args(), has_dhat, init_time(), and polyfem::logger().
init_logger() [1/3]
void polyfem::State::init_logger (const std::string & log_file, const spdlog::level::level_enum log_level, const bool is_quiet)
initalizing the logger
Parameters
[in] log_file is to write it to a file (use log_file="") to output to stdout
[in] log_level 0 all message, 6 no message. 2 is info, 1 is debug
[in] is_quit quiets the log
Definition at line 289 of file StateInit.cpp.
References init_logger().
Referenced by init_logger().
init_logger() [2/3]
void polyfem::State::init_logger (const std::vector< spdlog::sink_ptr > & sinks, const spdlog::level::level_enum log_level) private
initalizing the logger meant for internal usage
Definition at line 310 of file StateInit.cpp.
References polyfem::logger(), and polyfem::set_logger().
init_logger() [3/3]
void polyfem::State::init_logger (std::ostream & os, const spdlog::level::level_enum log_level)
initalizing the logger writes to an output stream
Parameters
[in] os output stream
[in] log_level 0 all message, 6 no message. 2 is info, 1 is debug
Definition at line 303 of file StateInit.cpp.
References init_logger().
init_time()
void polyfem::State::init_time ()
initialize time settings if args contains "time"
Definition at line 407 of file StateInit.cpp.
References args, polyfem::utils::check_for_unknown_args(), polyfem::utils::is_param_valid(), polyfem::logger(), and p_bases::tmp.
Referenced by init().
init_transient()
void polyfem::State::init_transient (Eigen::VectorXd & c_sol)
initialize transient solver
Parameters
[in] c_sol current solution
Definition at line 75 of file StateSolve.cpp.
References args, ass_vals_cache, assembler, bases, formulation(), geom_bases, polyfem::assembler::RhsAssembler::initial_solution(), input_dirichelt, polyfem::assembler::AssemblerUtils::is_mixed(), iso_parametric(), polyfem::logger(), mesh, n_bases, n_pressure_bases, obstacle, pressure, problem, polyfem::utils::read_matrix(), resolve_input_path(), rhs, polyfem::StepData::rhs_assembler, save_timestep(), sol, sol_to_pressure(), and step_data.
Referenced by solve_problem().
interpolate_at_local_vals() [1/3]
void polyfem::State::interpolate_at_local_vals (const int el_index, const int actual_dim, const std::vector< ElementBases > & bases, const MatrixXd & local_pts, const MatrixXd & fun, MatrixXd & result, MatrixXd & result_grad)
interpolate the function fun and its gradient at in element el_index for the local_pts in the reference element using bases bases interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
Parameters
[in] el_index element index
[in] actual_dim is the size of the problem (e.g., 1 for Laplace, dim for elasticity)
[in] bases basis function
[in] local_pts points in the reference element
[in] fun function to used
[out] result output
[out] result_grad output gradients
Definition at line 787 of file StateInterpolation.cpp.
References bases, geom_bases, iso_parametric(), polyfem::logger(), mesh, val, and vals.
interpolate_at_local_vals() [2/3]
void polyfem::State::interpolate_at_local_vals (const int el_index, const MatrixXd & local_pts, const MatrixXd & fun, MatrixXd & result, MatrixXd & result_grad)
interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
Parameters
[in] el_index element index
[in] local_pts points in the reference element
[in] fun function to used
[out] result output
[out] result_grad output gradients
Definition at line 779 of file StateInterpolation.cpp.
References bases, interpolate_at_local_vals(), mesh, and problem.
interpolate_at_local_vals() [3/3]
void polyfem::State::interpolate_at_local_vals (const int el_index, const MatrixXd & local_pts, MatrixXd & result, MatrixXd & result_grad)
interpolate solution and gradient at element (calls interpolate_at_local_vals with sol)
Parameters
[in] el_index element index
[in] local_pts points in the reference element
[out] result output
[out] result_grad output gradients
Definition at line 774 of file StateInterpolation.cpp.
References interpolate_at_local_vals(), and sol.
Referenced by interpolate_at_local_vals(), save_surface(), and save_volume().
interpolate_boundary_function()
void polyfem::State::interpolate_boundary_function (const MatrixXd & pts, const MatrixXi & faces, const MatrixXd & fun, const bool compute_avg, MatrixXd & result)
computes integrated solution (fun) per surface face.
pts and faces are the boundary are the boundary on the rest configuration
Parameters
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[in] compute_avg if compute the average across elements
[out] result resulting value
Definition at line 25 of file StateInterpolation.cpp.
References polyfem::basis::ElementBases::bases, bases, polyfem::mesh::Mesh3D::cell_face(), polyfem::mesh::Mesh::face_barycenter(), geom_bases, polyfem::assembler::AssemblyValues::global, polyfem::mesh::Mesh::is_boundary_face(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), iso_parametric(), polyfem::logger(), mesh, polyfem::mesh::Mesh3D::n_cell_faces(), polyfem::mesh::Mesh::n_elements(), p_bases::points, problem, polyfem::utils::BoundarySampler::quadrature_for_quad_face(), polyfem::utils::BoundarySampler::quadrature_for_tri_face(), polyfem::assembler::AssemblyValues::val, and vals.
interpolate_boundary_function_at_vertices()
void polyfem::State::interpolate_boundary_function_at_vertices (const MatrixXd & pts, const MatrixXi & faces, const MatrixXd & fun, MatrixXd & result)
computes integrated solution (fun) per surface face vertex.
pts and faces are the boundary are the boundary on the rest configuration
Parameters
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[out] result resulting value
Definition at line 118 of file StateInterpolation.cpp.
References polyfem::basis::ElementBases::bases, bases, polyfem::mesh::Mesh3D::cell_face(), polyfem::mesh::Mesh::face_barycenter(), geom_bases, polyfem::basis::Basis::global(), polyfem::mesh::Mesh::is_cube(), polyfem::mesh::Mesh::is_simplex(), iso_parametric(), polyfem::logger(), mesh, polyfem::mesh::Mesh3D::n_cell_faces(), polyfem::mesh::Mesh::n_elements(), polyfem::autogen::p_nodes_3d(), p_bases::points, problem, polyfem::autogen::q_nodes_3d(), polyfem::assembler::AssemblyValues::val, and vals.
interpolate_boundary_tensor_function() [1/2]
void polyfem::State::interpolate_boundary_tensor_function (const MatrixXd & pts, const MatrixXi & faces, const MatrixXd & fun, const bool compute_avg, MatrixXd & result, MatrixXd & stresses, MatrixXd & mises, const bool skip_orientation = false)
same as interpolate_boundary_tensor_function with disp=0
Parameters
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[in] compute_avg if compute the average across elements
[out] result resulting value
[out] stresses resulting stresses
[out] mises resulting mises
[in] skip_orientation skip reorientation of surface
Definition at line 221 of file StateInterpolation.cpp.
References interpolate_boundary_tensor_function().
interpolate_boundary_tensor_function() [2/2]
void polyfem::State::interpolate_boundary_tensor_function (const MatrixXd & pts, const MatrixXi & faces, const MatrixXd & fun, const MatrixXd & disp, const bool compute_avg, MatrixXd & result, MatrixXd & stresses, MatrixXd & mises, const bool skip_orientation = false)
computes traction foces for fun (tensor * surface normal) result, stress tensor, and von mises, per surface face.
pts and faces are the boundary on the rest configuration. disp is the displacement of the surface vertices
Parameters
[in] pts boundary points
[in] faces boundary faces
[in] fun function to used
[in] disp displacement to deform mesh
[in] compute_avg if compute the average across elements
[out] result resulting value
[out] stresses resulting stresses
[out] mises resulting mises
[in] skip_orientation skip reorientation of surface
Definition at line 226 of file StateInterpolation.cpp.
References assembler, bases, polyfem::mesh::Mesh3D::cell_face(), polyfem::assembler::AssemblerUtils::compute_scalar_value(), polyfem::assembler::AssemblerUtils::compute_tensor_value(), polyfem::mesh::Mesh::face_barycenter(), formulation(), geom_bases, polyfem::utils::BoundarySampler::hex_local_node_coordinates_from_face(), iso_parametric(), polyfem::logger(), mesh, polyfem::mesh::Mesh3D::n_cell_faces(), polyfem::mesh::Mesh::n_elements(), polyfem::utils::BoundarySampler::normal_for_quad_face(), polyfem::utils::BoundarySampler::normal_for_tri_face(), p_bases::points, problem, polyfem::utils::BoundarySampler::quadrature_for_quad_face(), polyfem::utils::BoundarySampler::quadrature_for_tri_face(), polyfem::utils::BoundarySampler::tet_local_node_coordinates_from_face(), p_bases::tmp, and vals.
Referenced by interpolate_boundary_tensor_function().
interpolate_function() [1/2]
void polyfem::State::interpolate_function (const int n_points, const Eigen::MatrixXd & fun, Eigen::MatrixXd & result, const bool use_sampler, const bool boundary_only)
interpolate the function fun.
Parameters
[in] n_points is the size of the output.
[in] fun function to used
[out] result output
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Referenced by average_grad_based_function(), save_volume(), and save_wire().
interpolate_function() [2/2]
void polyfem::State::interpolate_function (const int n_points, const int actual_dim, const std::vector< ElementBases > & basis, const MatrixXd & fun, MatrixXd & result, const bool use_sampler, const bool boundary_only)
interpolate the function fun.
Parameters
[in] n_points is the size of the output.
[in] actual_dim is the size of the problem (e.g., 1 for Laplace, dim for elasticity)
[in] basis basis function
[in] fun function to used
[out] result output
[in] use_sampler uses the sampler or not
[in] boundary_only interpolates only at boundary elements
Definition at line 690 of file StateInterpolation.cpp.
References polyfem::basis::ElementBases::bases, disc_orders, polyfem::basis::ElementBases::evaluate_bases(), polyfem::basis::Basis::global(), polyfem::logger(), mesh, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), polys, polys_3d, polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), ref_element_sampler, and p_bases::tmp.
is_obstacle_vertex()
bool polyfem::State::is_obstacle_vertex (const size_t vi) const inline
checks if vertex is obstacle
Parameters
[in] vi vertex index
Returns
if vertex is obstalce
Definition at line 445 of file State.hpp.
References boundary_nodes_pos, polyfem::mesh::Obstacle::n_vertices(), and obstacle.
Referenced by build_collision_mesh().
iso_parametric()
bool polyfem::State::iso_parametric () const
check if using iso parametric bases
Returns
if basis are isoparametric
Definition at line 547 of file State.cpp.
References args, mesh, non_regular_boundary_count, non_regular_count, and undefined_count.
Referenced by assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_polygonal_basis(), build_vis_mesh(), check_scalar_value(), polyfem::solver::NLProblem::compute_cached_stiffness(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), extract_vis_boundary_mesh(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), init_transient(), interpolate_at_local_vals(), interpolate_boundary_function(), interpolate_boundary_function_at_vertices(), interpolate_boundary_tensor_function(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), save_json(), save_surface(), save_volume(), save_wire(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), and polyfem::solver::NLProblem::value().
load_febio()
void polyfem::State::load_febio (const std::string & path, const json & args_in)
loads a febio file, uses args_in for default, [DEPRECATED]
Definition at line 157 of file StateLoad.cpp.
References args, polyfem::utils::FEBioReader::load(), polyfem::logger(), mesh, obstacle, eigs::path, and polyfem::mesh::read_obstacle_geometry().
load_mesh() [1/3]
void polyfem::State::load_mesh (bool non_conforming = false, const std::vector< std::string > & names = std::vector<std::string>(), const std::vector< Eigen::MatrixXi > & cells = std::vector<Eigen::MatrixXi>(), const std::vector< Eigen::MatrixXd > & vertices = std::vector<Eigen::MatrixXd>())
loads the mesh from the json arguments
Parameters
[in] non_conforming creates a conforming/non conforming mesh
[in] names keys in the hdf5
[in] cells list of cells from hdf5
[in] vertices list of vertices from hdf5
Definition at line 99 of file StateLoad.cpp.
References args, polyfem::utils::is_param_valid(), polyfem::logger(), mesh, elasticity_rhs::names, polyfem::mesh::read_fem_geometry(), reset_mesh(), and p_bases::vertices.
Referenced by load_mesh().
load_mesh() [2/3]
void polyfem::State::load_mesh (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F, bool non_conforming = false) inline
loads the mesh from V and F,
Parameters
[in] V is #vertices x dim
[in] F is #elements x size (size = 3 for triangle mesh, size=4 for a quaud mesh if dim is 2)
[in] non_conforming creates a conforming/non conforming mesh
Definition at line 393 of file State.hpp.
References polyfem::mesh::Mesh::create(), load_mesh(), and mesh.
load_mesh() [3/3]
void polyfem::State::load_mesh (GEO::Mesh & meshin, const std::function< int(const RowVectorNd &)> & boundary_marker, bool non_conforming = false, bool skip_boundary_sideset = false)
loads the mesh from a geogram mesh
Parameters
[in] meshin geo mesh
[in] boundary_marker the input of the lambda is the face barycenter, the output is the sideset id
[in] non_conforming creates a conforming/non conforming mesh
[in] skip_boundary_sideset skip_boundary_sideset = false it uses the lambda boundary_marker to assign the sideset
Definition at line 43 of file StateLoad.cpp.
References polyfem::mesh::Mesh::create(), polyfem::logger(), mesh, and reset_mesh().
make_nl_solver()
template<typename ProblemType > template std::shared_ptr< cppoptlib::NonlinearSolver< ALNLProblem > > polyfem::State::make_nl_solver () const
factory to create the nl solver depdending on input
Returns
non linear solver (eg newton or LBFGS)
Definition at line 56 of file StateSolve.cpp.
References args.
n_boundary_samples()
int polyfem::State::n_boundary_samples () const inline
quadrature used for projecting boundary conditions
Returns
the quadrature used for projecting boundary conditions
Definition at line 229 of file State.hpp.
References args, and mesh.
Referenced by polyfem::solver::NLProblem::current_rhs(), solve_linear(), solve_navier_stokes(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), polyfem::solver::ALNLProblem::update_target(), and polyfem::solver::NLProblem::value().
p_refinement() [1/2]
void polyfem::State::p_refinement (const mesh::Mesh2D & mesh2d)
compute a priori prefinement in 2d, fills disc_orders
Parameters
[in] mesh2d mesh
Definition at line 44 of file StatePref.cpp.
References args, polyfem::mesh::Mesh2D::get_edges(), max_angle, and p_bases::tmp.
Referenced by build_basis().
p_refinement() [2/2]
void polyfem::State::p_refinement (const mesh::Mesh3D & mesh3d)
compute a priori prefinement in 3d, fills disc_orders
Parameters
[in] mesh2d mesh
Definition at line 133 of file StatePref.cpp.
References args, polyfem::mesh::Mesh3D::get_edges(), max_angle, and p_bases::tmp.
reset_mesh()
void polyfem::State::reset_mesh ()
Resets the mesh.
Definition at line 22 of file StateLoad.cpp.
References bases, boundary_nodes, polyfem::mesh::Obstacle::clear(), geom_bases, local_boundary, local_neumann_boundary, n_bases, n_pressure_bases, obstacle, poly_edge_to_data, polys, pressure, pressure_bases, rhs, sol, and stiffness.
Referenced by load_mesh().
resolve_input_path()
std::string polyfem::State::resolve_input_path (const std::string & path, const bool only_if_exists = false) const
Resolve input path relative to root_path() if the path is not absolute.
Parameters
[in] path path to resolve
[in] only_if_exists resolve only if relative path exists
Returns
path
Definition at line 1639 of file State.cpp.
References eigs::path, polyfem::utils::resolve_path(), and root_path().
Referenced by init_transient(), solve_non_linear(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_init().
resolve_output_path()
std::string polyfem::State::resolve_output_path (const std::string & path) const
Resolve output path relative to output_dir if the path is not absolute.
Parameters
[in] path path to resolve
Returns
resolvedpath
Definition at line 1644 of file State.cpp.
References output_dir, and eigs::path.
Referenced by export_data(), save_json(), save_subsolve(), save_timestep(), solve_non_linear(), solve_problem(), solve_transient_tensor_linear(), solve_transient_tensor_non_linear(), and solve_transient_tensor_non_linear_init().
root_path()
std::string polyfem::State::root_path () const
Get the root path for the state (e.g., args["root_path"] or ".")
Returns
root path
Definition at line 1632 of file State.cpp.
References args, and polyfem::utils::is_param_valid().
Referenced by resolve_input_path().
save_json() [1/3]
void polyfem::State::save_json ()
saves the output statistic to disc accoding to params
Definition at line 526 of file StateOutput.cpp.
References args, polyfem::logger(), resolve_output_path(), and save_json().
Referenced by get_log(), and save_json().
save_json() [2/3]
void polyfem::State::save_json (nlohmann::json & j)
saves the output statistic to a json object
Parameters
[in] j output json
Definition at line 550 of file StateOutput.cpp.
References args, assembling_stiffness_mat_time, assigning_rhs_time, average_edge_length, boundary_count, building_basis_time, computing_errors_time, computing_poly_basis_time, disc_orders, getPeakRSS(), grad_max_err, h1_err, h1_semi_err, iso_parametric(), l2_err, linf_err, loading_mesh_time, polyfem::logger(), lp_err, mat_size, max_angle, mesh, mesh_size, min_edge_length, multi_singular_boundary_count, multi_singular_count, n_bases, n_flipped, n_pressure_bases, nn_zero, non_regular_boundary_count, non_regular_count, num_dofs, problem, regular_boundary_count, regular_count, sigma_avg, sigma_max, sigma_min, simple_singular_count, simplex_count, sol, solver_info, solving_time, spectrum, and undefined_count.
save_json() [3/3]
void polyfem::State::save_json (std::ostream & out)
saves the output statistic to a stream
Parameters
[in] out stream to write output
Definition at line 542 of file StateOutput.cpp.
References save_json().
save_pvd()
void polyfem::State::save_pvd (const std::string & name, const std::function< std::string(int)> & vtu_names, int time_steps, double t0, double dt, int skip_frame = 1)
save a PVD of a time dependent simulation
Parameters
[in] name filename
[in] vtu_names names of the vtu files
[in] time_steps total time stesp
[in] t0 initial time
[in] dt delta t
[in] skip_frame every which frame to skip
Definition at line 1997 of file StateOutput.cpp.
Referenced by save_timestep().
save_subsolve()
void polyfem::State::save_subsolve (const int i, const int t)
saves a subsolve when save_solve_sequence_debug is true
Parameters
[in] i sub solve index
[in] t time index
Definition at line 2025 of file StateOutput.cpp.
References args, resolve_output_path(), save_vtu(), solution_frames, and solve_export_to_file.
save_surface()
void polyfem::State::save_surface (const std::string & name)
saves the surface vtu file for for surface quantites, eg traction forces
Parameters
[in] name filename
[in] t time
Definition at line 1629 of file StateOutput.cpp.
References polyfem::mesh::VTUWriter::add_field(), args, assembler, bases, boundary_nodes_pos, boundary_vis_elements, boundary_vis_elements_ids, boundary_vis_local_vertices, boundary_vis_normals, boundary_vis_primitive_ids, boundary_vis_vertices, collision_mesh, polyfem::assembler::AssemblerUtils::compute_tensor_value(), density, disc_orders, formulation(), geom_bases, interpolate_at_local_vals(), polyfem::assembler::AssemblerUtils::is_mixed(), iso_parametric(), polyfem::LameParameters::lambda_mu(), eigs::lambdas, polyfem::assembler::AssemblerUtils::lame_params(), mesh, polyfem::StepData::nl_problem, pressure, pressure_bases, problem, sol, solution_frames, solve_export_to_file, step_data, polyfem::utils::unflatten(), and polyfem::mesh::VTUWriter::write_mesh().
Referenced by save_vtu().
save_timestep()
void polyfem::State::save_timestep (const double time, const int t, const double t0, const double dt)
saves a timestep
Parameters
[in] time time in secs
[in] t time index
[in] t0 initial time
[in] dt delta t
Definition at line 41 of file StateOutput.cpp.
References args, polyfem::logger(), POLYFEM_SCOPED_TIMER, resolve_output_path(), save_pvd(), save_vtu(), solution_frames, and solve_export_to_file.
Referenced by init_transient(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_step().
save_volume()
void polyfem::State::save_volume (const std::string & path, const double t)
saves the volume vtu file
Parameters
[in] name filename
[in] t time
Definition at line 1180 of file StateOutput.cpp.
References polyfem::mesh::VTUWriter::add_field(), args, assembler, average_grad_based_function(), bases, build_high_oder_vis_mesh(), build_vis_mesh(), compute_scalar_value(), compute_tensor_value(), density, disc_orders, formulation(), geom_bases, polyfem::mesh::Obstacle::get_edge_connectivity(), polyfem::mesh::Obstacle::get_face_connectivity(), polyfem::mesh::Obstacle::get_vertex_connectivity(), grid_points, grid_points_bc, grid_points_to_elements, interpolate_at_local_vals(), interpolate_function(), polyfem::assembler::AssemblerUtils::is_mixed(), iso_parametric(), polyfem::LameParameters::lambda_mu(), eigs::lambdas, polyfem::assembler::AssemblerUtils::lame_params(), mesh, polyfem::mesh::Obstacle::n_vertices(), polyfem::StepData::nl_problem, obstacle, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), eigs::path, p_bases::points, polys, polys_3d, pressure, pressure_bases, problem, polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), ref_element_sampler, polyfem::mesh::Obstacle::set_zero(), sol, solution_frames, solve_export_to_file, step_data, p_bases::tmp, polyfem::mesh::Obstacle::update_displacement(), polyfem::mesh::Obstacle::v(), vals, and polyfem::mesh::VTUWriter::write_mesh().
Referenced by save_vtu().
save_vtu()
void polyfem::State::save_vtu (const std::string & name, const double t)
saves the vtu file for time t
Parameters
[in] name filename
[in] t time
Definition at line 1073 of file StateOutput.cpp.
References args, polyfem::logger(), mesh, n_bases, eigs::path, problem, rhs, save_surface(), save_volume(), save_wire(), sol, solve_export_to_file, and p_bases::tmp.
Referenced by export_data(), save_subsolve(), save_timestep(), and solve_non_linear().
save_wire()
void polyfem::State::save_wire (const std::string & name, const double t)
saves the wireframe
Parameters
[in] name filename
[in] t time
Definition at line 1852 of file StateOutput.cpp.
References polyfem::mesh::VTUWriter::add_field(), bases, compute_scalar_value(), geom_bases, interpolate_function(), iso_parametric(), mesh, p_bases::points, problem, ref_element_sampler, sol, solve_export_to_file, p_bases::tmp, and polyfem::mesh::VTUWriter::write_mesh().
Referenced by save_vtu().
set_boundary_side_set() [1/3]
void polyfem::State::set_boundary_side_set (const std::function< int(const RowVectorNd &)> & boundary_marker) inline
set the boundary sideset from a lambda that takes the face/edge barycenter
Parameters
[in] boundary_marker function from face/edge barycenter that returns the sideset id
Definition at line 401 of file State.hpp.
References mesh.
set_boundary_side_set() [2/3]
void polyfem::State::set_boundary_side_set (const std::function< int(const RowVectorNd &, bool)> & boundary_marker) inline
set the boundary sideset from a lambda that takes the face/edge barycenter and a flag if the face/edge is boundary or not (used to set internal boundaries)
Parameters
[in] boundary_marker function from face/edge barycenter and a flag if the face/edge is boundary that returns the sideset id
Definition at line 404 of file State.hpp.
References mesh.
set_boundary_side_set() [3/3]
void polyfem::State::set_boundary_side_set (const std::function< int(const std::vector< int > &, bool)> & boundary_marker) inline
set the boundary sideset from a lambda that takes the face/edge vertices and a flag if the face/edge is boundary or not (used to set internal boundaries)
Parameters
[in] boundary_marker function from face/edge vertices and a flag if the face/edge is boundary that returns the sideset id
Definition at line 407 of file State.hpp.
References mesh.
set_log_level()
void polyfem::State::set_log_level (const spdlog::level::level_enum log_level) inline
change log level
Parameters
[in] log_level 0 all message, 6 no message. 2 is info, 1 is debug
Definition at line 119 of file State.hpp.
References polyfem::logger().
set_materials()
void polyfem::State::set_materials () private
set the multimaterial, this is mean for internal usage.
Definition at line 407 of file State.cpp.
References polyfem::assembler::AssemblerUtils::add_multimaterial(), polyfem::Density::add_multimaterial(), args, assembler, density, polyfem::utils::is_param_valid(), polyfem::logger(), mesh, and p_bases::tmp.
sol_to_pressure()
void polyfem::State::sol_to_pressure () private
splits the solution in solution and pressure for mixed problems
Definition at line 310 of file State.cpp.
References formulation(), polyfem::assembler::AssemblerUtils::is_fluid(), polyfem::assembler::AssemblerUtils::is_mixed(), polyfem::logger(), mesh, n_bases, n_pressure_bases, pressure, problem, sol, p_bases::tmp, and use_avg_pressure.
Referenced by init_transient(), solve_linear(), solve_navier_stokes(), solve_transient_navier_stokes(), and solve_transient_scalar().
solve()
void polyfem::State::solve () inline
solves the problem, call other methods
Definition at line 253 of file State.hpp.
References assemble_rhs(), assemble_stiffness_mat(), build_basis(), compute_mesh_stats(), solution_frames, solve_export_to_file, and solve_problem().
solve_linear()
void polyfem::State::solve_linear ()
solves a linear problem
Definition at line 692 of file StateSolve.cpp.
References args, ass_vals_cache, assembler, bases, boundary_nodes, formulation(), geom_bases, input_dirichelt, polyfem::assembler::AssemblerUtils::is_fluid(), polyfem::assembler::AssemblerUtils::is_linear(), polyfem::assembler::AssemblerUtils::is_mixed(), iso_parametric(), local_boundary, local_neumann_boundary, polyfem::logger(), mesh, n_bases, n_boundary_samples(), p_bases::norm, obstacle, problem, rhs, polyfem::assembler::RhsAssembler::set_bc(), sol, sol_to_pressure(), solver_info, spectrum, stiffness, use_avg_pressure, and x.
Referenced by solve_problem().
solve_navier_stokes()
void polyfem::State::solve_navier_stokes ()
solves a navier stokes
Definition at line 740 of file StateSolve.cpp.
References args, ass_vals_cache, assembler, bases, boundary_nodes, formulation(), geom_bases, input_dirichelt, iso_parametric(), local_boundary, local_neumann_boundary, mesh, polyfem::solver::NavierStokesSolver::minimize(), n_bases, n_boundary_samples(), obstacle, problem, rhs, polyfem::assembler::RhsAssembler::set_bc(), sol, sol_to_pressure(), and x.
Referenced by solve_problem().
solve_non_linear()
void polyfem::State::solve_non_linear ()
solves nonlinear problems
Definition at line 764 of file StateSolve.cpp.
References polyfem::StepData::alnl_problem, args, ass_vals_cache, assembler, bases, boundary_nodes, polyfem::solver::NLProblem::compute_lagging_error(), formulation(), polyfem::solver::NLProblem::full_to_reduced(), geom_bases, polyfem::solver::NLProblem::init(), polyfem::solver::NLProblem::init_lagging(), input_dirichelt, polyfem::assembler::AssemblerUtils::is_linear(), polyfem::solver::NLProblem::is_step_collision_free(), polyfem::solver::NLProblem::is_step_valid(), iso_parametric(), polyfem::solver::NLProblem::lagged_damping_weight(), polyfem::solver::NLProblem::lagging_converged(), polyfem::solver::NLProblem::line_search_begin(), polyfem::solver::NLProblem::line_search_end(), polyfem::logger(), mesh, n_bases, polyfem::StepData::nl_problem, obstacle, problem, polyfem::solver::NLProblem::reduced_to_full(), resolve_input_path(), resolve_output_path(), rhs, save_vtu(), polyfem::solver::ALNLProblem::set_weight(), sol, solution_frames, solve_export_to_file, solver_info, step_data, polyfem::solver::NLProblem::update_lagging(), polyfem::solver::NLProblem::value(), and polyfem::utils::write_matrix().
Referenced by solve_problem().
solve_problem()
void polyfem::State::solve_problem ()
solves the proble, step 5
Definition at line 1365 of file State.cpp.
References args, assembler, formulation(), init_transient(), polyfem::assembler::AssemblerUtils::is_linear(), polyfem::assembler::AssemblerUtils::is_mixed(), polyfem::logger(), mesh, n_bases, pressure, problem, resolve_output_path(), rhs, polyfem::StepData::rhs_assembler, sol, solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), solve_transient_tensor_non_linear(), solving_time, spectrum, step_data, and stiffness.
Referenced by solve().
solve_transient_navier_stokes()
void polyfem::State::solve_transient_navier_stokes (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler & rhs_assembler, Eigen::VectorXd & c_sol)
solves transient navier stokes with FEM
Parameters
[in] time_steps number of time steps
[in] t0 initial times
[in] dt timestep size
[in] rhs_assembler rhs assembler
[out] c_sol solution
Definition at line 221 of file StateSolve.cpp.
References polyfem::time_integrator::BDF::acceleration_scaling(), args, ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_mass_matrix(), polyfem::assembler::AssemblerUtils::assemble_mixed_problem(), polyfem::assembler::AssemblerUtils::assemble_pressure_problem(), polyfem::assembler::AssemblerUtils::assemble_problem(), assembler, bases, boundary_nodes, polyfem::assembler::RhsAssembler::compute_energy_grad(), density, formulation(), geom_bases, polyfem::time_integrator::BDF::init(), iso_parametric(), local_boundary, local_neumann_boundary, polyfem::logger(), mesh, polyfem::solver::TransientNavierStokesSolver::minimize(), n_bases, n_boundary_samples(), n_pressure_bases, pressure_ass_vals_cache, pressure_bases, problem, rhs, save_timestep(), polyfem::assembler::RhsAssembler::set_bc(), polyfem::time_integrator::BDF::set_parameters(), sol, sol_to_pressure(), polyfem::time_integrator::BDF::update_quantities(), use_avg_pressure, and polyfem::time_integrator::BDF::weighted_sum_x_prevs().
Referenced by solve_problem().
solve_transient_navier_stokes_split()
void polyfem::State::solve_transient_navier_stokes_split (const int time_steps, const double dt, const assembler::RhsAssembler & rhs_assembler)
solves transient navier stokes with operator splitting
Parameters
[in] time_steps number of time steps
[in] dt timestep size
[in] rhs_assembler rhs assembler
Definition at line 123 of file StateSolve.cpp.
References polyfem::solver::OperatorSplittingSolver::advection(), polyfem::solver::OperatorSplittingSolver::advection_FLIP(), args, ass_vals_cache, polyfem::assembler::AssemblerUtils::assemble_mass_matrix(), polyfem::assembler::AssemblerUtils::assemble_mixed_problem(), polyfem::assembler::AssemblerUtils::assemble_problem(), assembler, bases, boundary_nodes, density, polyfem::solver::OperatorSplittingSolver::external_force(), formulation(), geom_bases, iso_parametric(), local_boundary, local_neumann_boundary, polyfem::logger(), mass, mesh, n_bases, n_boundary_samples(), n_pressure_bases, polyfem::autogen::p_nodes_2d(), polyfem::autogen::p_nodes_3d(), pressure, pressure_ass_vals_cache, pressure_bases, pressure_boundary_nodes, problem, polyfem::solver::OperatorSplittingSolver::projection(), polyfem::autogen::q_nodes_2d(), polyfem::autogen::q_nodes_3d(), save_timestep(), polyfem::assembler::RhsAssembler::set_bc(), sol, polyfem::solver::OperatorSplittingSolver::solve_diffusion_1st(), polyfem::solver::OperatorSplittingSolver::solve_pressure(), and stiffness.
Referenced by solve_problem().
solve_transient_scalar()
void polyfem::State::solve_transient_scalar (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler & rhs_assembler, Eigen::VectorXd & x)
solves transient scalar problem
Parameters
[in] time_steps number of time steps
[in] t0 initial times
[in] dt timestep size
[in] rhs_assembler rhs assembler
[out] x solution
Definition at line 277 of file StateSolve.cpp.
References args, assembler, polyfem::time_integrator::BDF::beta_dt(), boundary_nodes, polyfem::assembler::RhsAssembler::compute_energy_grad(), density, formulation(), polyfem::time_integrator::BDF::init(), polyfem::assembler::AssemblerUtils::is_fluid(), polyfem::assembler::AssemblerUtils::is_mixed(), local_boundary, local_neumann_boundary, polyfem::logger(), mass, mesh, n_bases, n_boundary_samples(), n_pressure_bases, p_bases::norm, problem, rhs, save_timestep(), polyfem::assembler::RhsAssembler::set_bc(), polyfem::time_integrator::BDF::set_parameters(), sol, sol_to_pressure(), spectrum, stiffness, polyfem::time_integrator::BDF::update_quantities(), use_avg_pressure, polyfem::time_integrator::BDF::weighted_sum_x_prevs(), and x.
Referenced by solve_problem().
solve_transient_tensor_linear()
void polyfem::State::solve_transient_tensor_linear (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler & rhs_assembler)
solves transient linear problem
Parameters
[in] time_steps number of time steps
[in] t0 initial times
[in] dt timestep size
[in] rhs_assembler rhs assembler
[out] x solution
Definition at line 340 of file StateSolve.cpp.
References args, polyfem::assembler::RhsAssembler::assemble(), assembler, boundary_nodes, polyfem::time_integrator::ImplicitTimeIntegrator::construct_time_integrator(), density, formulation(), polyfem::assembler::RhsAssembler::initial_acceleration(), polyfem::assembler::RhsAssembler::initial_velocity(), polyfem::assembler::AssemblerUtils::is_fluid(), polyfem::assembler::AssemblerUtils::is_linear(), polyfem::assembler::AssemblerUtils::is_mixed(), local_boundary, local_neumann_boundary, polyfem::logger(), mass, mesh, n_bases, n_boundary_samples(), p_bases::norm, problem, resolve_input_path(), resolve_output_path(), rhs, save_timestep(), polyfem::assembler::RhsAssembler::set_bc(), sol, spectrum, stiffness, use_avg_pressure, polyfem::utils::write_matrix(), and x.
Referenced by solve_problem().
solve_transient_tensor_non_linear()
void polyfem::State::solve_transient_tensor_non_linear (const int time_steps, const double t0, const double dt, const assembler::RhsAssembler & rhs_assembler)
solves transient tensor non linear problem
Parameters
[in] time_steps number of time steps
[in] t0 initial times
[in] dt timestep size
[in] rhs_assembler rhs assembler
Definition at line 424 of file StateSolve.cpp.
References args, polyfem::logger(), polyfem::StepData::nl_problem, resolve_output_path(), polyfem::solver::NLProblem::save_raw(), solve_transient_tensor_non_linear_init(), solve_transient_tensor_non_linear_step(), solver_info, and step_data.
Referenced by solve_problem().
solve_transient_tensor_non_linear_init()
void polyfem::State::solve_transient_tensor_non_linear_init (const double t0, const double dt, const assembler::RhsAssembler & rhs_assembler)
initialized the non linear solver
Parameters
[in] t0 initial times
[in] dt timestep size
[in] rhs_assembler rhs assembler
Definition at line 442 of file StateSolve.cpp.
References polyfem::StepData::alnl_problem, args, assembler, boundary_nodes, boundary_nodes_pos, collision_mesh, formulation(), polyfem::solver::NLProblem::init_time_integrator(), polyfem::assembler::RhsAssembler::initial_acceleration(), polyfem::assembler::RhsAssembler::initial_velocity(), polyfem::assembler::AssemblerUtils::is_linear(), polyfem::assembler::AssemblerUtils::is_mixed(), polyfem::logger(), mesh, n_bases, polyfem::StepData::nl_problem, problem, resolve_input_path(), resolve_output_path(), sol, solver_info, step_data, and polyfem::utils::unflatten().
Referenced by solve_transient_tensor_non_linear().
solve_transient_tensor_non_linear_step()
void polyfem::State::solve_transient_tensor_non_linear_step (const double t0, const double dt, const int t, json & solver_info)
steps trought time
Parameters
[in] t0 initial times
[in] dt timestep size
[in] t time
[out] solver_info output solver stats
Definition at line 578 of file StateSolve.cpp.
References polyfem::StepData::alnl_problem, args, polyfem::solver::NLProblem::compute_lagging_error(), polyfem::solver::NLProblem::full_to_reduced(), polyfem::solver::NLProblem::init(), polyfem::solver::NLProblem::init_lagging(), polyfem::solver::NLProblem::is_step_collision_free(), polyfem::solver::NLProblem::is_step_valid(), polyfem::solver::NLProblem::lagging_converged(), polyfem::solver::NLProblem::line_search_begin(), polyfem::solver::NLProblem::line_search_end(), polyfem::logger(), polyfem::StepData::nl_problem, POLYFEM_SCOPED_TIMER, polyfem::solver::NLProblem::reduced_to_full(), rhs, save_timestep(), polyfem::solver::ALNLProblem::set_weight(), sol, solver_info, step_data, polyfem::solver::NLProblem::update_lagging(), polyfem::solver::NLProblem::update_quantities(), polyfem::solver::ALNLProblem::update_quantities(), and polyfem::solver::NLProblem::value().
Referenced by solve_transient_tensor_non_linear().
Member Data Documentation
args
json polyfem::State::args
main input arguments containing all defaults
Definition at line 100 of file State.hpp.
Referenced by assemble_stiffness_mat(), build_basis(), build_polygonal_basis(), build_vis_mesh(), compute_errors(), export_data(), formulation(), init(), init_time(), init_transient(), iso_parametric(), polyfem::solver::NLProblem::lagging_converged(), polyfem::utils::FEBioReader::load(), load_febio(), load_mesh(), make_nl_solver(), n_boundary_samples(), polyfem::solver::NLProblem::NLProblem(), p_refinement(), root_path(), save_json(), save_subsolve(), save_surface(), save_timestep(), save_volume(), save_vtu(), set_materials(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), solve_transient_tensor_non_linear(), solve_transient_tensor_non_linear_init(), and solve_transient_tensor_non_linear_step().
ass_vals_cache
assembler::AssemblyValsCache polyfem::State::ass_vals_cache
used to store assembly values for small problems
Definition at line 186 of file State.hpp.
Referenced by assemble_stiffness_mat(), polyfem::solver::NLProblem::compute_cached_stiffness(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), init_transient(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), and polyfem::solver::NLProblem::value().
assembler
assembler::AssemblerUtils polyfem::State::assembler
assembler, it dispatches call to the differnt assembers based on the formulation
Definition at line 163 of file State.hpp.
Referenced by assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_polygonal_basis(), check_scalar_value(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), polyfem::problem::KernelProblem::eval_fun(), init_transient(), interpolate_boundary_tensor_function(), polyfem::problem::KernelProblem::is_scalar(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), save_surface(), save_volume(), set_materials(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_init().
assembling_stiffness_mat_time
double polyfem::State::assembling_stiffness_mat_time
time to assembly
Definition at line 502 of file State.hpp.
Referenced by assemble_stiffness_mat(), and save_json().
assigning_rhs_time
double polyfem::State::assigning_rhs_time
time to computing the rhs
Definition at line 504 of file State.hpp.
Referenced by save_json().
average_edge_length
double polyfem::State::average_edge_length
avg edge lenght
Definition at line 486 of file State.hpp.
Referenced by compute_mesh_size(), and save_json().
avg_mass
double polyfem::State::avg_mass
average system mass, used for contact with IPC
Definition at line 147 of file State.hpp.
Referenced by assemble_stiffness_mat().
bases
std::vector<ElementBases> polyfem::State::bases
FE bases, the size is #elements.
Definition at line 168 of file State.hpp.
Referenced by assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_collision_mesh(), build_high_oder_vis_mesh(), build_polygonal_basis(), build_vis_mesh(), check_scalar_value(), polyfem::solver::NLProblem::compute_cached_stiffness(), compute_mesh_stats(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), export_data(), extract_boundary_mesh(), extract_vis_boundary_mesh(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), init_transient(), interpolate_at_local_vals(), interpolate_boundary_function(), interpolate_boundary_function_at_vertices(), interpolate_boundary_tensor_function(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), reset_mesh(), save_surface(), save_volume(), save_wire(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), and polyfem::solver::NLProblem::value().
boundary_count
int polyfem::State::boundary_count
statiscs on the mesh (boundary quads/hexs), see Polyspline paper for desciption
Definition at line 529 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
boundary_edges
Eigen::MatrixXi polyfem::State::boundary_edges
edge indices into full vertices
Definition at line 422 of file State.hpp.
Referenced by build_collision_mesh(), and extract_boundary_mesh().
boundary_nodes
std::vector<int> polyfem::State::boundary_nodes
list of boundary nodes
Definition at line 333 of file State.hpp.
Referenced by polyfem::solver::ALNLProblem::ALNLProblem(), build_basis(), compute_mesh_stats(), polyfem::solver::NLProblem::current_rhs(), polyfem::solver::NLProblem::full_hessian_to_reduced_hessian(), polyfem::solver::NLProblem::full_to_reduced_aux(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), polyfem::solver::NLProblem::reduced_to_full_aux(), reset_mesh(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), solve_transient_tensor_non_linear_init(), and polyfem::solver::ALNLProblem::update_target().
boundary_nodes_pos
Eigen::MatrixXd polyfem::State::boundary_nodes_pos
boundary mesh used for collision boundary_nodes_pos contains the total number of nodes, the internal ones are zero for high-order fem the faces are triangulated this is currently supported only for tri and tet meshes
Definition at line 420 of file State.hpp.
Referenced by build_collision_mesh(), polyfem::solver::NLProblem::compute_displaced_points(), extract_boundary_mesh(), is_obstacle_vertex(), save_surface(), and solve_transient_tensor_non_linear_init().
boundary_triangles
Eigen::MatrixXi polyfem::State::boundary_triangles
triangle indices into full vertices
Definition at line 424 of file State.hpp.
Referenced by build_collision_mesh(), and extract_boundary_mesh().
boundary_vis_elements
Eigen::MatrixXi polyfem::State::boundary_vis_elements
boundary visualization mesh connectivity
Definition at line 459 of file State.hpp.
Referenced by extract_vis_boundary_mesh(), and save_surface().
boundary_vis_elements_ids
Eigen::MatrixXi polyfem::State::boundary_vis_elements_ids
boundary visualization mesh elements ids
Definition at line 461 of file State.hpp.
Referenced by extract_vis_boundary_mesh(), and save_surface().
boundary_vis_local_vertices
Eigen::MatrixXd polyfem::State::boundary_vis_local_vertices
boundary visualization mesh vertices pre image in ref element
Definition at line 457 of file State.hpp.
Referenced by extract_vis_boundary_mesh(), and save_surface().
boundary_vis_normals
Eigen::MatrixXd polyfem::State::boundary_vis_normals
boundary visualization mesh normals
Definition at line 465 of file State.hpp.
Referenced by extract_vis_boundary_mesh(), and save_surface().
boundary_vis_primitive_ids
Eigen::MatrixXi polyfem::State::boundary_vis_primitive_ids
boundary visualization mesh edge/face id
Definition at line 463 of file State.hpp.
Referenced by extract_vis_boundary_mesh(), and save_surface().
boundary_vis_vertices
Eigen::MatrixXd polyfem::State::boundary_vis_vertices
boundary visualization mesh vertices
Definition at line 455 of file State.hpp.
Referenced by extract_vis_boundary_mesh(), and save_surface().
building_basis_time
double polyfem::State::building_basis_time
time to construct the basis
Definition at line 496 of file State.hpp.
Referenced by save_json().
collision_mesh
ipc::CollisionMesh polyfem::State::collision_mesh
ipc collision mesh into surface vertices
Definition at line 426 of file State.hpp.
Referenced by build_collision_mesh(), save_surface(), solve_transient_tensor_non_linear_init(), polyfem::solver::NLProblem::update_constraint_set(), and polyfem::solver::NLProblem::update_lagging().
computing_errors_time
double polyfem::State::computing_errors_time
time to compute error
Definition at line 508 of file State.hpp.
Referenced by save_json().
computing_poly_basis_time
double polyfem::State::computing_poly_basis_time
time to build the polygonal/polyhedral bases
Definition at line 500 of file State.hpp.
Referenced by build_polygonal_basis(), and save_json().
density
Density polyfem::State::density
density of the input, default=1.
Definition at line 144 of file State.hpp.
Referenced by assemble_stiffness_mat(), polyfem::solver::NLProblem::current_rhs(), save_surface(), save_volume(), set_materials(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and polyfem::solver::NLProblem::value().
disc_orders
Eigen::VectorXi polyfem::State::disc_orders
vector of discretization oders, used when not all elements have the same degree, one per element
Definition at line 180 of file State.hpp.
Referenced by average_grad_based_function(), build_basis(), build_high_oder_vis_mesh(), build_vis_mesh(), check_scalar_value(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), interpolate_function(), save_json(), save_surface(), and save_volume().
geom_bases
std::vector<ElementBases> polyfem::State::geom_bases
Geometric mapping bases, if the elements are isoparametric, this list is empty.
Definition at line 172 of file State.hpp.
Referenced by assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_polygonal_basis(), build_vis_mesh(), check_scalar_value(), polyfem::solver::NLProblem::compute_cached_stiffness(), compute_mesh_stats(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), extract_vis_boundary_mesh(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), init_transient(), interpolate_at_local_vals(), interpolate_boundary_function(), interpolate_boundary_function_at_vertices(), interpolate_boundary_tensor_function(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), reset_mesh(), save_surface(), save_volume(), save_wire(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), and polyfem::solver::NLProblem::value().
grad_max_err
double polyfem::State::grad_max_err
Definition at line 489 of file State.hpp.
Referenced by save_json().
grid_points
Eigen::MatrixXd polyfem::State::grid_points
grid mesh points to export solution sampled on a grid
Definition at line 468 of file State.hpp.
Referenced by save_volume().
grid_points_bc
Eigen::MatrixXd polyfem::State::grid_points_bc
grid mesh boundaries
Definition at line 472 of file State.hpp.
Referenced by save_volume().
grid_points_to_elements
Eigen::MatrixXi polyfem::State::grid_points_to_elements
grid mesh mapping to fe elements
Definition at line 470 of file State.hpp.
Referenced by save_volume().
h1_err
double polyfem::State::h1_err
Definition at line 489 of file State.hpp.
Referenced by save_json().
h1_semi_err
double polyfem::State::h1_semi_err
Definition at line 489 of file State.hpp.
Referenced by save_json().
has_dhat
bool polyfem::State::has_dhat = false
stores if input json contains dhat
Definition at line 348 of file State.hpp.
Referenced by init(), and polyfem::utils::FEBioReader::load().
in_node_to_node
Eigen::VectorXi polyfem::State::in_node_to_node
Inpute nodes (including high-order) to polyfem nodes, only for isoparametric.
Definition at line 154 of file State.hpp.
Referenced by build_node_mapping(), and export_data().
in_primitive_to_primitive
Eigen::VectorXi polyfem::State::in_primitive_to_primitive
maps in vertices/edges/faces/cells to polyfem vertices/edges/faces/cells
Definition at line 156 of file State.hpp.
Referenced by build_node_mapping().
input_dirichelt
std::vector<Eigen::MatrixXd> polyfem::State::input_dirichelt
Matrices containing the input per node dirichelt.
Definition at line 345 of file State.hpp.
Referenced by build_basis(), init_transient(), solve_linear(), solve_navier_stokes(), and solve_non_linear().
l2_err
double polyfem::State::l2_err
errors, lp_err is in fact an L8 error
Definition at line 489 of file State.hpp.
Referenced by save_json().
linf_err
double polyfem::State::linf_err
Definition at line 489 of file State.hpp.
Referenced by save_json().
loading_mesh_time
double polyfem::State::loading_mesh_time
time to load the mesh
Definition at line 498 of file State.hpp.
Referenced by save_json().
local_boundary
std::vector<mesh::LocalBoundary> polyfem::State::local_boundary
mapping from elements to nodes for dirichlet boundary conditions
Definition at line 339 of file State.hpp.
Referenced by build_basis(), build_polygonal_basis(), compute_mesh_stats(), polyfem::solver::NLProblem::current_rhs(), reset_mesh(), solve_linear(), solve_navier_stokes(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and polyfem::solver::ALNLProblem::update_target().
local_neumann_boundary
std::vector<mesh::LocalBoundary> polyfem::State::local_neumann_boundary
mapping from elements to nodes for neumann boundary conditions
Definition at line 341 of file State.hpp.
Referenced by build_basis(), compute_mesh_stats(), polyfem::solver::NLProblem::current_rhs(), reset_mesh(), solve_linear(), solve_navier_stokes(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), polyfem::solver::ALNLProblem::update_target(), and polyfem::solver::NLProblem::value().
lp_err
double polyfem::State::lp_err
Definition at line 489 of file State.hpp.
Referenced by save_json().
mass
StiffnessMatrix polyfem::State::mass
Mass matrix, it is computed only for time dependent problems.
Definition at line 194 of file State.hpp.
Referenced by assemble_stiffness_mat(), polyfem::solver::NLProblem::current_rhs(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and polyfem::solver::NLProblem::value().
mat_size
long long polyfem::State::mat_size
Definition at line 493 of file State.hpp.
Referenced by assemble_stiffness_mat(), and save_json().
max_angle
double polyfem::State::max_angle
statiscs on angle, compute only when using p_ref (false by default)
Definition at line 511 of file State.hpp.
Referenced by p_refinement(), and save_json().
mesh
std::unique_ptr<mesh::Mesh> polyfem::State::mesh
current mesh, it can be a Mesh2D or Mesh3D
Definition at line 355 of file State.hpp.
Referenced by polyfem::solver::ALNLProblem::ALNLProblem(), assemble_rhs(), assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_high_oder_vis_mesh(), build_node_mapping(), build_polygonal_basis(), build_vis_mesh(), check_scalar_value(), polyfem::solver::NLProblem::compute_cached_stiffness(), polyfem::solver::NLProblem::compute_displaced_points(), compute_errors(), compute_mesh_stats(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), compute_vertex_values(), export_data(), extract_boundary_mesh(), extract_vis_boundary_mesh(), get_sidesets(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), init_transient(), interpolate_at_local_vals(), interpolate_boundary_function(), interpolate_boundary_function_at_vertices(), interpolate_boundary_tensor_function(), interpolate_function(), iso_parametric(), load_febio(), load_mesh(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), n_boundary_samples(), save_json(), save_surface(), save_volume(), save_vtu(), save_wire(), set_boundary_side_set(), set_materials(), sol_to_pressure(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), solve_transient_tensor_non_linear_init(), and polyfem::solver::NLProblem::value().
mesh_nodes
std::shared_ptr<polyfem::mesh::MeshNodes> polyfem::State::mesh_nodes
Mapping from input nodes to FE nodes.
Definition at line 183 of file State.hpp.
Referenced by build_node_mapping().
mesh_size
double polyfem::State::mesh_size
max edge lenght
Definition at line 482 of file State.hpp.
Referenced by compute_mesh_size(), and save_json().
min_edge_length
double polyfem::State::min_edge_length
min edge lenght
Definition at line 484 of file State.hpp.
Referenced by compute_mesh_size(), and save_json().
multi_singular_boundary_count
int polyfem::State::multi_singular_boundary_count
statiscs on the mesh (irregular boundary quad/hex part of the mesh), see Polyspline paper for desciption
Definition at line 537 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
multi_singular_count
int polyfem::State::multi_singular_count
statiscs on the mesh (irregular quad/hex part of the mesh), see Polyspline paper for desciption
Definition at line 527 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
n_bases
int polyfem::State::n_bases
number of bases
Definition at line 208 of file State.hpp.
Referenced by polyfem::solver::ALNLProblem::ALNLProblem(), assemble_rhs(), assemble_stiffness_mat(), average_grad_based_function(), build_basis(), build_high_oder_vis_mesh(), build_polygonal_basis(), build_vis_mesh(), polyfem::solver::NLProblem::compute_cached_stiffness(), compute_errors(), compute_mesh_stats(), export_data(), extract_boundary_mesh(), polyfem::solver::NLProblem::gradient_no_rhs(), polyfem::solver::NLProblem::hessian_full(), init_transient(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), reset_mesh(), save_json(), save_vtu(), sol_to_pressure(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_init().
n_flipped
int polyfem::State::n_flipped
number of flipped elements, compute only when using count_flipped_els (false by default)
Definition at line 516 of file State.hpp.
Referenced by save_json().
n_pressure_bases
int polyfem::State::n_pressure_bases
number of pressure bases
Definition at line 210 of file State.hpp.
Referenced by assemble_stiffness_mat(), build_basis(), build_polygonal_basis(), compute_mesh_stats(), polyfem::solver::NLProblem::current_rhs(), init_transient(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), reset_mesh(), save_json(), sol_to_pressure(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), and solve_transient_scalar().
nn_zero
long long polyfem::State::nn_zero
non zeros and sytem matrix size num dof is the total dof in the system
Definition at line 493 of file State.hpp.
Referenced by assemble_stiffness_mat(), and save_json().
non_regular_boundary_count
int polyfem::State::non_regular_boundary_count
statiscs on the mesh (irregular boundary quad/hex part of the mesh), see Polyspline paper for desciption
Definition at line 531 of file State.hpp.
Referenced by build_basis(), compute_mesh_stats(), iso_parametric(), and save_json().
non_regular_count
int polyfem::State::non_regular_count
statiscs on the mesh (irregular quad/hex part of the mesh), see Polyspline paper for desciption
Definition at line 533 of file State.hpp.
Referenced by build_basis(), compute_mesh_stats(), iso_parametric(), and save_json().
num_dofs
long long polyfem::State::num_dofs
Definition at line 493 of file State.hpp.
Referenced by assemble_stiffness_mat(), and save_json().
obstacle
mesh::Obstacle polyfem::State::obstacle
Obstacles used in collisions.
Definition at line 357 of file State.hpp.
Referenced by build_collision_mesh(), init_transient(), is_obstacle_vertex(), load_febio(), reset_mesh(), save_volume(), solve_linear(), solve_navier_stokes(), and solve_non_linear().
output_dir
std::string polyfem::State::output_dir
Directory for output files.
Definition at line 142 of file State.hpp.
Referenced by resolve_output_path().
poly_edge_to_data
std::map<int, InterfaceData> polyfem::State::poly_edge_to_data
nodes on the boundary of polygonal elements, used for harmonic bases
Definition at line 343 of file State.hpp.
Referenced by build_basis(), build_polygonal_basis(), compute_mesh_stats(), and reset_mesh().
polys
std::map<int, Eigen::MatrixXd> polyfem::State::polys
polygons, used since poly have no geom mapping
Definition at line 175 of file State.hpp.
Referenced by build_basis(), build_polygonal_basis(), build_vis_mesh(), check_scalar_value(), compute_mesh_stats(), compute_scalar_value(), compute_tensor_value(), interpolate_function(), reset_mesh(), and save_volume().
polys_3d
std::map<int, std::pair<Eigen::MatrixXd, Eigen::MatrixXi> > polyfem::State::polys_3d
polyhedra, used since poly have no geom mapping
Definition at line 177 of file State.hpp.
Referenced by build_polygonal_basis(), build_vis_mesh(), check_scalar_value(), compute_scalar_value(), compute_tensor_value(), interpolate_function(), and save_volume().
pressure
Eigen::MatrixXd polyfem::State::pressure
pressure solution, if the problem is not mixed, pressure is empty
Definition at line 201 of file State.hpp.
Referenced by assemble_stiffness_mat(), build_basis(), build_polygonal_basis(), compute_mesh_stats(), init_transient(), reset_mesh(), save_surface(), save_volume(), sol_to_pressure(), solve_problem(), and solve_transient_navier_stokes_split().
pressure_ass_vals_cache
assembler::AssemblyValsCache polyfem::State::pressure_ass_vals_cache
used to store assembly values for pressure for small problems
Definition at line 188 of file State.hpp.
Referenced by assemble_stiffness_mat(), polyfem::solver::NavierStokesSolver::minimize(), solve_transient_navier_stokes(), and solve_transient_navier_stokes_split().
pressure_bases
std::vector<ElementBases> polyfem::State::pressure_bases
FE pressure bases for mixed elements, the size is #elements.
Definition at line 170 of file State.hpp.
Referenced by assemble_stiffness_mat(), build_basis(), compute_mesh_stats(), polyfem::solver::NavierStokesSolver::minimize(), reset_mesh(), save_surface(), save_volume(), solve_transient_navier_stokes(), and solve_transient_navier_stokes_split().
pressure_boundary_nodes
std::vector<int> polyfem::State::pressure_boundary_nodes
list of neumann boundary nodes
Definition at line 335 of file State.hpp.
Referenced by solve_transient_navier_stokes_split().
problem
std::shared_ptr<assembler::Problem> polyfem::State::problem
current problem, it contains rhs and bc
Definition at line 165 of file State.hpp.
Referenced by assemble_stiffness_mat(), average_grad_based_function(), build_basis(), check_scalar_value(), compute_errors(), compute_scalar_value(), compute_stress_at_quadrature_points(), compute_tensor_value(), export_data(), init_transient(), interpolate_at_local_vals(), interpolate_boundary_function(), interpolate_boundary_function_at_vertices(), interpolate_boundary_tensor_function(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), save_json(), save_surface(), save_volume(), save_vtu(), save_wire(), sol_to_pressure(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_init().
ref_element_sampler
utils::RefElementSampler polyfem::State::ref_element_sampler
used to sample the solution
Definition at line 359 of file State.hpp.
Referenced by build_vis_mesh(), check_scalar_value(), compute_scalar_value(), compute_tensor_value(), compute_vertex_values(), extract_vis_boundary_mesh(), interpolate_function(), save_volume(), and save_wire().
regular_boundary_count
int polyfem::State::regular_boundary_count
statiscs on the mesh (regular quad/hex boundary part of the mesh), see Polyspline paper for desciption
Definition at line 523 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
regular_count
int polyfem::State::regular_count
statiscs on the mesh (regular quad/hex part of the mesh), see Polyspline paper for desciption
Definition at line 521 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
rhs
Eigen::MatrixXd polyfem::State::rhs
System righ-hand side.
Definition at line 196 of file State.hpp.
Referenced by build_basis(), build_polygonal_basis(), compute_errors(), compute_mesh_stats(), polyfem::solver::NLProblem::current_rhs(), export_data(), init_transient(), reset_mesh(), save_vtu(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_scalar(), solve_transient_tensor_linear(), and solve_transient_tensor_non_linear_step().
sigma_avg
double polyfem::State::sigma_avg
Definition at line 513 of file State.hpp.
Referenced by build_basis(), and save_json().
sigma_max
double polyfem::State::sigma_max
statiscs on tri/tet quality, compute only when using p_ref (false by default)
Definition at line 513 of file State.hpp.
Referenced by build_basis(), and save_json().
sigma_min
double polyfem::State::sigma_min
Definition at line 513 of file State.hpp.
Referenced by build_basis(), and save_json().
simple_singular_count
int polyfem::State::simple_singular_count
statiscs on the mesh (irregular quad/hex part of the mesh), see Polyspline paper for desciption
Definition at line 525 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
simplex_count
int polyfem::State::simplex_count
statiscs on the mesh (simplices)
Definition at line 519 of file State.hpp.
Referenced by compute_mesh_stats(), and save_json().
sol
Eigen::MatrixXd polyfem::State::sol
solution
Definition at line 199 of file State.hpp.
Referenced by assemble_stiffness_mat(), build_basis(), build_polygonal_basis(), compute_errors(), compute_mesh_stats(), export_data(), init_transient(), interpolate_at_local_vals(), reset_mesh(), save_json(), save_surface(), save_volume(), save_vtu(), save_wire(), sol_to_pressure(), solve_linear(), solve_navier_stokes(), solve_non_linear(), solve_problem(), solve_transient_navier_stokes(), solve_transient_navier_stokes_split(), solve_transient_scalar(), solve_transient_tensor_linear(), solve_transient_tensor_non_linear_init(), and solve_transient_tensor_non_linear_step().
solution_frames
std::vector<SolutionFrame> polyfem::State::solution_frames
saves the frames in a vector instead of VTU
Definition at line 543 of file State.hpp.
Referenced by save_subsolve(), save_surface(), save_timestep(), save_volume(), solve(), and solve_non_linear().
solve_export_to_file
bool polyfem::State::solve_export_to_file = true
flag to decide if exporting the time dependent solution to files or save it in the solution_frames array
Definition at line 541 of file State.hpp.
Referenced by save_subsolve(), save_surface(), save_timestep(), save_volume(), save_vtu(), save_wire(), solve(), and solve_non_linear().
solver_info
json polyfem::State::solver_info
information of the solver, eg num iteration, time, errors, etc the informations varies depending on the solver
Definition at line 479 of file State.hpp.
Referenced by save_json(), solve_linear(), solve_non_linear(), solve_transient_tensor_non_linear(), solve_transient_tensor_non_linear_init(), and solve_transient_tensor_non_linear_step().
solving_time
double polyfem::State::solving_time
time to solve
Definition at line 506 of file State.hpp.
Referenced by save_json(), and solve_problem().
spectrum
Eigen::Vector4d polyfem::State::spectrum
spectrum of the stiffness matrix, enable only if POLYSOLVE_WITH_SPECTRA is ON (off by default)
Definition at line 475 of file State.hpp.
Referenced by save_json(), solve_linear(), solve_problem(), solve_transient_scalar(), and solve_transient_tensor_linear().
step_data
StepData polyfem::State::step_data
timedependent stuff cached
Definition at line 269 of file State.hpp.
Referenced by init_transient(), save_surface(), save_volume(), solve_non_linear(), solve_problem(), solve_transient_tensor_non_linear(), solve_transient_tensor_non_linear_init(), and solve_transient_tensor_non_linear_step().
stiffness
StiffnessMatrix polyfem::State::stiffness
stiffness and mass matrix.
Stiffness is not compute for non linear problems
Definition at line 192 of file State.hpp.
Referenced by assemble_stiffness_mat(), build_basis(), build_polygonal_basis(), compute_mesh_stats(), reset_mesh(), solve_linear(), solve_problem(), solve_transient_navier_stokes_split(), solve_transient_scalar(), and solve_transient_tensor_linear().
total_local_boundary
std::vector<mesh::LocalBoundary> polyfem::State::total_local_boundary
mapping from elements to nodes for all mesh
Definition at line 337 of file State.hpp.
Referenced by build_basis(), extract_boundary_mesh(), and extract_vis_boundary_mesh().
undefined_count
int polyfem::State::undefined_count
statiscs on the mesh (not quad/hex simplex), see Polyspline paper for desciption
Definition at line 535 of file State.hpp.
Referenced by build_basis(), compute_mesh_stats(), iso_parametric(), and save_json().
use_avg_pressure
bool polyfem::State::use_avg_pressure
use average pressure for stokes problem to fix the additional dofs, true by default if false, it will fix one pressure node to zero
Definition at line 205 of file State.hpp.
Referenced by assemble_stiffness_mat(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), sol_to_pressure(), solve_linear(), solve_transient_navier_stokes(), solve_transient_scalar(), and solve_transient_tensor_linear().
The documentation for this class was generated from the following files:
src/polyfem/State.hpp
src/polyfem/State.cpp
src/polyfem/state/StateInit.cpp
src/polyfem/state/StateInterpolation.cpp
src/polyfem/state/StateLoad.cpp
src/polyfem/state/StateOutput.cpp
src/polyfem/state/StatePref.cpp
src/polyfem/state/StateSolve.cpp