PolyFEM: polyfem::solver::ALForm Class Reference
polyfem::solver::ALForm Class Reference
Form of the augmented lagrangian.
#include <ALForm.hpp>
Public Member Functions
ALForm (const State &state, const assembler::RhsAssembler &rhs_assembler, const double t)
Construct a new AL Form object.
void update_quantities (const double t, const Eigen::VectorXd &x) override
Update time dependent quantities.
void set_enabled (const bool val)
bool enabled () const override
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
double value (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian)
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const int iter_num, const Eigen::VectorXd &x)
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x)
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields.
virtual void update_lagging (const Eigen::VectorXd &x)
Update lagged fields.
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
virtual bool enabled () const
void set_weight (const double val)
Protected Member Functions
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) override
Compute the second derivative of the value wrt x.
virtual double value_unweighted (const Eigen::VectorXd &x) const =0
Compute the value of the form.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const =0
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian)=0
Compute the second derivative of the value wrt x.
Private Member Functions
void update_target (const double t)
Private Attributes
const State & state_
Reference to the simulation state.
const assembler::RhsAssembler & rhs_assembler_
Reference to the RHS assembler.
StiffnessMatrix masked_lumped_mass_
mass matrix masked by the AL dofs
Eigen::MatrixXd target_x_
actually a vector with the same size as x with target nodal positions
bool enabled_
enable/disable the AL
Additional Inherited Members
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form, eg barrier stiffness, AL, d^2
Detailed Description
Form of the augmented lagrangian.
Definition at line 12 of file ALForm.hpp.
Constructor & Destructor Documentation
ALForm()
polyfem::solver::ALForm::ALForm (const State & state, const assembler::RhsAssembler & rhs_assembler, const double t)
Construct a new AL Form object.
Parameters
state Reference to the simulation state
rhs_assembler Reference to the right hand side assembler
t current time
Definition at line 5 of file ALForm.cpp.
References polyfem::State::boundary_nodes, polyfem::utils::lump_matrix(), masked_lumped_mass_, polyfem::State::mass, polyfem::State::mesh, polyfem::State::n_bases, polyfem::mesh::Obstacle::n_vertices(), polyfem::mesh::Obstacle::ndof(), polyfem::State::obstacle, polyfem::utils::sparse_identity(), update_target(), and polyfem::solver::Form::value().
Member Function Documentation
enabled()
bool polyfem::solver::ALForm::enabled () const inline override virtual
Reimplemented from polyfem::solver::Form.
Definition at line 44 of file ALForm.hpp.
References enabled_.
first_derivative_unweighted()
void polyfem::solver::ALForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override protected virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Implements polyfem::solver::Form.
Definition at line 52 of file ALForm.cpp.
References masked_lumped_mass_, target_x_, and x.
second_derivative_unweighted()
void polyfem::solver::ALForm::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) override protected virtual
Compute the second derivative of the value wrt x.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Implements polyfem::solver::Form.
Definition at line 57 of file ALForm.cpp.
References masked_lumped_mass_.
set_enabled()
void polyfem::solver::ALForm::set_enabled (const bool val) inline
Definition at line 43 of file ALForm.hpp.
References enabled_, and val.
update_quantities()
void polyfem::solver::ALForm::update_quantities (const double t, const Eigen::VectorXd & x) override virtual
Update time dependent quantities.
Parameters
t New time
x Solution at time t
Reimplemented from polyfem::solver::Form.
Definition at line 62 of file ALForm.cpp.
References polyfem::State::problem, state_, and update_target().
update_target()
void polyfem::solver::ALForm::update_target (const double t) private
Definition at line 68 of file ALForm.cpp.
References polyfem::State::boundary_nodes, polyfem::State::local_boundary, polyfem::State::local_neumann_boundary, masked_lumped_mass_, polyfem::State::n_boundary_samples(), rhs_assembler_, polyfem::assembler::RhsAssembler::set_bc(), state_, and target_x_.
Referenced by ALForm(), and update_quantities().
value_unweighted()
double polyfem::solver::ALForm::value_unweighted (const Eigen::VectorXd & x) const override protected virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 37 of file ALForm.cpp.
References polyfem::logger(), masked_lumped_mass_, target_x_, and x.
Member Data Documentation
enabled_
bool polyfem::solver::ALForm::enabled_ private
enable/disable the AL
Definition at line 53 of file ALForm.hpp.
Referenced by enabled(), and set_enabled().
masked_lumped_mass_
StiffnessMatrix polyfem::solver::ALForm::masked_lumped_mass_ private
mass matrix masked by the AL dofs
Definition at line 50 of file ALForm.hpp.
Referenced by ALForm(), first_derivative_unweighted(), second_derivative_unweighted(), update_target(), and value_unweighted().
rhs_assembler_
const assembler::RhsAssembler& polyfem::solver::ALForm::rhs_assembler_ private
Reference to the RHS assembler.
Definition at line 48 of file ALForm.hpp.
Referenced by update_target().
state_
const State& polyfem::solver::ALForm::state_ private
Reference to the simulation state.
Definition at line 47 of file ALForm.hpp.
Referenced by update_quantities(), and update_target().
target_x_
Eigen::MatrixXd polyfem::solver::ALForm::target_x_ private
actually a vector with the same size as x with target nodal positions
Definition at line 51 of file ALForm.hpp.
Referenced by first_derivative_unweighted(), update_target(), and value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/ALForm.hpp
src/polyfem/solver/forms/ALForm.cpp