PolyFEM: polyfem::assembler::ElementAssemblyValues Class Reference
polyfem::assembler::ElementAssemblyValues Class Reference
#include <ElementAssemblyValues.hpp>
Public Member Functions
void compute (const int el_index, const bool is_volume, const basis::ElementBases &basis, const basis::ElementBases &gbasis)
void compute (const int el_index, const bool is_volume, const Eigen::MatrixXd &pts, const basis::ElementBases &basis, const basis::ElementBases &gbasis)
bool is_geom_mapping_positive (const bool is_volume, const basis::ElementBases &gbasis) const
Public Attributes
std::vector< AssemblyValues > basis_values
std::vector< Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > > jac_it
quadrature::Quadrature quadrature
int element_id
Eigen::MatrixXd val
Eigen::VectorXd det
bool has_parameterization = true
Private Member Functions
void finalize_global_element (const Eigen::MatrixXd &v)
void finalize2d (const basis::ElementBases &gbasis, const std::vector< AssemblyValues > &gbasis_values)
void finalize3d (const basis::ElementBases &gbasis, const std::vector< AssemblyValues > &gbasis_values)
bool is_geom_mapping_positive (const Eigen::MatrixXd &dx, const Eigen::MatrixXd &dy, const Eigen::MatrixXd &dz) const
bool is_geom_mapping_positive (const Eigen::MatrixXd &dx, const Eigen::MatrixXd &dy) const
Private Attributes
std::vector< AssemblyValues > g_basis_values_cache_
Detailed Description
Definition at line 13 of file ElementAssemblyValues.hpp.
Member Function Documentation
compute() [1/2]
void polyfem::assembler::ElementAssemblyValues::compute (const int el_index, const bool is_volume, const basis::ElementBases & basis, const basis::ElementBases & gbasis)
Definition at line 199 of file ElementAssemblyValues.cpp.
References compute(), polyfem::basis::ElementBases::compute_quadrature(), polyfem::quadrature::Quadrature::points, and quadrature.
Referenced by polyfem::solver::OperatorSplittingSolver::advection_PIC(), compute(), polyfem::compute_integral_constraints(), and polyfem::assembler::NavierStokesVelocity< full_gradient >::compute_stress_tensor().
compute() [2/2]
void polyfem::assembler::ElementAssemblyValues::compute (const int el_index, const bool is_volume, const Eigen::MatrixXd & pts, const basis::ElementBases & basis, const basis::ElementBases & gbasis)
Definition at line 205 of file ElementAssemblyValues.cpp.
References polyfem::basis::ElementBases::bases, basis_values, element_id, polyfem::basis::ElementBases::evaluate_bases(), polyfem::basis::ElementBases::evaluate_grads(), finalize2d(), finalize3d(), finalize_global_element(), g_basis_values_cache_, polyfem::assembler::AssemblyValues::global, polyfem::basis::Basis::global(), polyfem::assembler::AssemblyValues::grad, polyfem::basis::ElementBases::has_parameterization, p_bases::tmp, polyfem::assembler::AssemblyValues::val, and val.
finalize2d()
void polyfem::assembler::ElementAssemblyValues::finalize2d (const basis::ElementBases & gbasis, const std::vector< AssemblyValues > & gbasis_values) private
Definition at line 161 of file ElementAssemblyValues.cpp.
References polyfem::basis::ElementBases::bases, basis_values, det, polyfem::basis::Basis::global(), polyfem::basis::ElementBases::has_parameterization, jac_it, p_bases::tmp, and val.
Referenced by compute().
finalize3d()
void polyfem::assembler::ElementAssemblyValues::finalize3d (const basis::ElementBases & gbasis, const std::vector< AssemblyValues > & gbasis_values) private
Definition at line 94 of file ElementAssemblyValues.cpp.
References polyfem::basis::ElementBases::bases, basis_values, det, polyfem::basis::Basis::global(), polyfem::basis::ElementBases::has_parameterization, jac_it, p_bases::tmp, and val.
Referenced by compute().
finalize_global_element()
void polyfem::assembler::ElementAssemblyValues::finalize_global_element (const Eigen::MatrixXd & v) private
Definition at line 14 of file ElementAssemblyValues.cpp.
References basis_values, det, has_parameterization, jac_it, and val.
Referenced by compute().
is_geom_mapping_positive() [1/3]
bool polyfem::assembler::ElementAssemblyValues::is_geom_mapping_positive (const bool is_volume, const basis::ElementBases & gbasis) const
Definition at line 353 of file ElementAssemblyValues.cpp.
References polyfem::basis::ElementBases::bases, polyfem::basis::ElementBases::compute_quadrature(), polyfem::basis::ElementBases::evaluate_grads(), polyfem::basis::Basis::global(), polyfem::basis::ElementBases::has_parameterization, is_geom_mapping_positive(), polyfem::quadrature::Quadrature::points, and p_bases::tmp.
Referenced by is_geom_mapping_positive().
is_geom_mapping_positive() [2/3]
bool polyfem::assembler::ElementAssemblyValues::is_geom_mapping_positive (const Eigen::MatrixXd & dx, const Eigen::MatrixXd & dy) const private
Definition at line 49 of file ElementAssemblyValues.cpp.
References p_bases::tmp.
is_geom_mapping_positive() [3/3]
bool polyfem::assembler::ElementAssemblyValues::is_geom_mapping_positive (const Eigen::MatrixXd & dx, const Eigen::MatrixXd & dy, const Eigen::MatrixXd & dz) const private
Definition at line 30 of file ElementAssemblyValues.cpp.
References p_bases::tmp.
Member Data Documentation
basis_values
std::vector<AssemblyValues> polyfem::assembler::ElementAssemblyValues::basis_values
Definition at line 17 of file ElementAssemblyValues.hpp.
Referenced by polyfem::solver::OperatorSplittingSolver::advection_PIC(), polyfem::assembler::BilaplacianMixed::assemble(), polyfem::assembler::IncompressibleLinearElasticityMixed::assemble(), polyfem::assembler::StokesMixed::assemble(), polyfem::assembler::NavierStokesVelocity< full_gradient >::assemble_grad(), compute(), polyfem::basis::RBFWithQuadratic::compute_constraints_matrix_2d(), polyfem::basis::RBFWithQuadraticLagrange::compute_constraints_matrix_2d(), polyfem::compute_diplacement_grad(), polyfem::compute_integral_constraints(), polyfem::assembler::NavierStokesVelocity< full_gradient >::compute_N(), polyfem::assembler::NavierStokesVelocity< full_gradient >::compute_stress_tensor(), polyfem::assembler::NavierStokesVelocity< false >::compute_W(), polyfem::assembler::NavierStokesVelocity< full_gradient >::compute_W(), finalize2d(), finalize3d(), finalize_global_element(), and polyfem::basis::RBFWithQuadratic::setup_monomials_vals_2d().
det
Eigen::VectorXd polyfem::assembler::ElementAssemblyValues::det
Definition at line 28 of file ElementAssemblyValues.hpp.
Referenced by polyfem::compute_integral_constraints(), finalize2d(), finalize3d(), and finalize_global_element().
element_id
int polyfem::assembler::ElementAssemblyValues::element_id
Definition at line 22 of file ElementAssemblyValues.hpp.
Referenced by compute().
g_basis_values_cache_
std::vector<AssemblyValues> polyfem::assembler::ElementAssemblyValues::g_basis_values_cache_ private
Definition at line 41 of file ElementAssemblyValues.hpp.
Referenced by compute().
has_parameterization
bool polyfem::assembler::ElementAssemblyValues::has_parameterization = true
Definition at line 31 of file ElementAssemblyValues.hpp.
Referenced by polyfem::basis::RBFWithQuadratic::compute_constraints_matrix_2d(), polyfem::basis::RBFWithQuadraticLagrange::compute_constraints_matrix_2d(), and finalize_global_element().
jac_it
std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3> > polyfem::assembler::ElementAssemblyValues::jac_it
Definition at line 19 of file ElementAssemblyValues.hpp.
Referenced by polyfem::compute_diplacement_grad(), polyfem::assembler::NavierStokesVelocity< full_gradient >::compute_N(), polyfem::assembler::NavierStokesVelocity< full_gradient >::compute_W(), finalize2d(), finalize3d(), and finalize_global_element().
quadrature
quadrature::Quadrature polyfem::assembler::ElementAssemblyValues::quadrature
Definition at line 21 of file ElementAssemblyValues.hpp.
Referenced by compute(), and polyfem::compute_integral_constraints().
val
Eigen::MatrixXd polyfem::assembler::ElementAssemblyValues::val
Definition at line 25 of file ElementAssemblyValues.hpp.
Referenced by compute(), polyfem::compute_integral_constraints(), finalize2d(), finalize3d(), and finalize_global_element().
The documentation for this class was generated from the following files:
src/polyfem/assembler/ElementAssemblyValues.hpp
src/polyfem/assembler/ElementAssemblyValues.cpp