PolyFEM: polyfem::solver::DeformedCollisionBarrierForm Class Reference
polyfem::solver::DeformedCollisionBarrierForm Class Reference
#include <BarrierForms.hpp>
Public Member Functions
DeformedCollisionBarrierForm (const VariableToSimulationGroup &variable_to_simulation, const State &state, const double dhat)
std::string name () const override
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
void solution_changed (const Eigen::VectorXd &x) override
Update cached fields upon a change in the solution.
bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Checks if the step is collision free.
double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine the maximum step size allowable between the current and next solution.
Public Member Functions inherited from polyfem::solver::AdjointForm
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual void finish ()
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
virtual void set_scale (const double scale)
sets the scale for the form
Private Member Functions
void build_collision_set (const Eigen::MatrixXd &displaced_surface)
Eigen::VectorXd get_updated_mesh_nodes (const Eigen::VectorXd &x) const
Private Attributes
const State & state_
Eigen::VectorXd X_init
ipc::CollisionMesh collision_mesh_
ipc::NormalCollisions collision_set
const double dhat_
ipc::BroadPhaseMethod broad_phase_method_
const ipc::BarrierPotential barrier_potential_
Additional Inherited Members
Protected Types inherited from polyfem::solver::AdjointForm
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Protected Member Functions inherited from polyfem::solver::AdjointForm
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes inherited from polyfem::solver::AdjointForm
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 71 of file BarrierForms.hpp.
Constructor & Destructor Documentation
DeformedCollisionBarrierForm()
polyfem::solver::DeformedCollisionBarrierForm::DeformedCollisionBarrierForm (const VariableToSimulationGroup & variable_to_simulation, const State & state, const double dhat)
Definition at line 281 of file BarrierForms.cpp.
References polyfem::State::args, broad_phase_method_, polyfem::State::build_collision_mesh(), collision_mesh_, polyfem::utils::flatten(), polyfem::State::geom_bases(), polyfem::State::get_vertices(), polyfem::State::in_node_to_node, polyfem::log_and_throw_adjoint_error(), polyfem::State::mesh, polyfem::State::n_bases, polyfem::State::n_geom_bases, name(), polyfem::State::obstacle, state_, polyfem::State::total_local_boundary, V, and X_init.
Member Function Documentation
build_collision_set()
void polyfem::solver::DeformedCollisionBarrierForm::build_collision_set (const Eigen::MatrixXd & displaced_surface) private
Definition at line 357 of file BarrierForms.cpp.
References broad_phase_method_, collision_mesh_, collision_set, and dhat_.
Referenced by solution_changed().
compute_partial_gradient()
void polyfem::solver::DeformedCollisionBarrierForm::compute_partial_gradient (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 307 of file BarrierForms.cpp.
References polyfem::solver::VariableToSimulationGroup::apply_parametrization_jacobian(), barrier_potential_, collision_mesh_, collision_set, get_updated_mesh_nodes(), polyfem::solver::AdjointTools::map_node_to_primitive_order(), polyfem::State::mesh, polyfem::solver::Shape, state_, polyfem::utils::unflatten(), polyfem::solver::AdjointForm::variable_to_simulations_, polyfem::solver::Form::weight(), and x.
get_updated_mesh_nodes()
Eigen::VectorXd polyfem::solver::DeformedCollisionBarrierForm::get_updated_mesh_nodes (const Eigen::VectorXd & x) const private
Definition at line 368 of file BarrierForms.cpp.
References polyfem::solver::VariableToSimulationGroup::compute_state_variable(), polyfem::State::diff_cached, polyfem::solver::AdjointTools::map_primitive_to_node_order(), polyfem::solver::Shape, state_, polyfem::solver::DiffCache::u(), polyfem::solver::AdjointForm::variable_to_simulations_, x, and X_init.
Referenced by compute_partial_gradient(), solution_changed(), and value_unweighted().
is_step_collision_free()
bool polyfem::solver::DeformedCollisionBarrierForm::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented from polyfem::solver::Form.
Definition at line 324 of file BarrierForms.cpp.
max_step_size()
double polyfem::solver::DeformedCollisionBarrierForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::Form.
Definition at line 343 of file BarrierForms.cpp.
name()
std::string polyfem::solver::DeformedCollisionBarrierForm::name () const inline override virtual
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 76 of file BarrierForms.hpp.
Referenced by DeformedCollisionBarrierForm().
solution_changed()
void polyfem::solver::DeformedCollisionBarrierForm::solution_changed (const Eigen::VectorXd & new_x) override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::AdjointForm.
Definition at line 316 of file BarrierForms.cpp.
References build_collision_set(), collision_mesh_, get_updated_mesh_nodes(), polyfem::State::mesh, polyfem::solver::AdjointForm::solution_changed(), state_, polyfem::utils::unflatten(), and x.
value_unweighted()
double polyfem::solver::DeformedCollisionBarrierForm::value_unweighted (const Eigen::VectorXd & x) const override virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 300 of file BarrierForms.cpp.
References barrier_potential_, collision_mesh_, collision_set, get_updated_mesh_nodes(), polyfem::State::mesh, state_, polyfem::utils::unflatten(), and x.
Member Data Documentation
barrier_potential_
const ipc::BarrierPotential polyfem::solver::DeformedCollisionBarrierForm::barrier_potential_ private
Definition at line 102 of file BarrierForms.hpp.
Referenced by compute_partial_gradient(), and value_unweighted().
broad_phase_method_
ipc::BroadPhaseMethod polyfem::solver::DeformedCollisionBarrierForm::broad_phase_method_ private
Definition at line 100 of file BarrierForms.hpp.
Referenced by build_collision_set(), and DeformedCollisionBarrierForm().
collision_mesh_
ipc::CollisionMesh polyfem::solver::DeformedCollisionBarrierForm::collision_mesh_ private
Definition at line 97 of file BarrierForms.hpp.
Referenced by build_collision_set(), compute_partial_gradient(), DeformedCollisionBarrierForm(), solution_changed(), and value_unweighted().
collision_set
ipc::NormalCollisions polyfem::solver::DeformedCollisionBarrierForm::collision_set private
Definition at line 98 of file BarrierForms.hpp.
Referenced by build_collision_set(), compute_partial_gradient(), and value_unweighted().
dhat_
const double polyfem::solver::DeformedCollisionBarrierForm::dhat_ private
Definition at line 99 of file BarrierForms.hpp.
Referenced by build_collision_set().
state_
const State& polyfem::solver::DeformedCollisionBarrierForm::state_ private
Definition at line 93 of file BarrierForms.hpp.
Referenced by compute_partial_gradient(), DeformedCollisionBarrierForm(), get_updated_mesh_nodes(), solution_changed(), and value_unweighted().
X_init
Eigen::VectorXd polyfem::solver::DeformedCollisionBarrierForm::X_init private
Definition at line 95 of file BarrierForms.hpp.
Referenced by DeformedCollisionBarrierForm(), and get_updated_mesh_nodes().
The documentation for this class was generated from the following files:
src/polyfem/optimization/forms/BarrierForms.hpp
src/polyfem/optimization/forms/BarrierForms.cpp