PolyFEM: polyfem::solver::AdjointForm Class Reference
polyfem::solver::AdjointForm Class Reference
#include <AdjointForm.hpp>
Public Member Functions
AdjointForm (const VariableToSimulationGroup &variable_to_simulations)
virtual ~AdjointForm ()
virtual std::string name () const override
void enable_energy_print (const std::string &print_energy_keyword)
double value (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied with the weigth.
virtual void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
const VariableToSimulationGroup & get_variable_to_simulations () const
virtual Eigen::MatrixXd compute_reduced_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
virtual void compute_partial_gradient (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x multiplied with the weigth.
virtual void update_quantities (const double t, const Eigen::VectorXd &x) final override
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x) final override
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num) final override
Update lagged fields.
virtual void set_apply_DBC (const Eigen::VectorXd &x, bool apply_DBC) final override
Set if the Dirichlet boundary conditions should be enforced.
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Types
enum class PrintStage { Inactive , AlreadyPrinted , ToPrint }
Protected Member Functions
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const final override
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const final override
Compute the second derivative of the value wrt x.
virtual Eigen::MatrixXd compute_adjoint_rhs (const Eigen::VectorXd &x, const State &state) const
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual double value_unweighted (const Eigen::VectorXd &x) const =0
Compute the value of the form.
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Protected Attributes
const VariableToSimulationGroup variable_to_simulations_
PrintStage print_energy_ = PrintStage::Inactive
std::string print_energy_keyword_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or Δt²)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 8 of file AdjointForm.hpp.
Member Enumeration Documentation
PrintStage
enum class polyfem::solver::AdjointForm::PrintStage strong protected
Enumerator
Inactive
AlreadyPrinted
ToPrint
Definition at line 39 of file AdjointForm.hpp.
Constructor & Destructor Documentation
AdjointForm()
polyfem::solver::AdjointForm::AdjointForm (const VariableToSimulationGroup & variable_to_simulations) inline
Definition at line 11 of file AdjointForm.hpp.
~AdjointForm()
virtual polyfem::solver::AdjointForm::~AdjointForm () inline virtual
Definition at line 12 of file AdjointForm.hpp.
Member Function Documentation
compute_adjoint_rhs()
Eigen::MatrixXd polyfem::solver::AdjointForm::compute_adjoint_rhs (const Eigen::VectorXd & x, const State & state) const protected virtual
Reimplemented in polyfem::solver::StaticForm, and polyfem::solver::TransientForm.
Definition at line 73 of file AdjointForm.cpp.
References polyfem::State::diff_cached, polyfem::State::ndof(), and polyfem::solver::DiffCache::size().
Referenced by compute_reduced_adjoint_rhs().
compute_partial_gradient()
void polyfem::solver::AdjointForm::compute_partial_gradient (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const virtual
Reimplemented in polyfem::solver::StaticForm, polyfem::solver::ParametrizationForm, polyfem::solver::AMIPSForm, polyfem::solver::CollisionBarrierForm, polyfem::solver::DeformedCollisionBarrierForm, polyfem::solver::BoundarySmoothingForm, polyfem::solver::TransientForm, and polyfem::solver::CompositeForm.
Definition at line 68 of file AdjointForm.cpp.
References x.
Referenced by first_derivative().
compute_reduced_adjoint_rhs()
Eigen::MatrixXd polyfem::solver::AdjointForm::compute_reduced_adjoint_rhs (const Eigen::VectorXd & x, const State & state) const virtual
Reimplemented in polyfem::solver::CompositeForm.
Definition at line 37 of file AdjointForm.cpp.
References compute_adjoint_rhs(), polyfem::State::lin_solver_cached, polyfem::solver::SolveData::nl_problem, polyfem::State::problem, polyfem::State::solve_data, and x.
enable_energy_print()
void polyfem::solver::AdjointForm::enable_energy_print (const std::string & print_energy_keyword)
Definition at line 20 of file AdjointForm.cpp.
References print_energy_, print_energy_keyword_, and ToPrint.
first_derivative()
void polyfem::solver::AdjointForm::first_derivative (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const final override virtual
Compute the first derivative of the value wrt x multiplied with the weigth.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Reimplemented from polyfem::solver::Form.
Definition at line 56 of file AdjointForm.cpp.
References polyfem::solver::VariableToSimulationGroup::compute_adjoint_term(), compute_partial_gradient(), variable_to_simulations_, and x.
first_derivative_unweighted()
void polyfem::solver::AdjointForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const final override protected virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Implements polyfem::solver::Form.
Reimplemented in polyfem::solver::AMIPSForm.
Definition at line 63 of file AdjointForm.cpp.
References polyfem::log_and_throw_adjoint_error().
get_variable_to_simulations()
const VariableToSimulationGroup & polyfem::solver::AdjointForm::get_variable_to_simulations () const inline
Definition at line 20 of file AdjointForm.hpp.
References variable_to_simulations_.
init_lagging()
void polyfem::solver::AdjointForm::init_lagging (const Eigen::VectorXd & x) final override virtual
Initialize lagged fields TODO: more than one step.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 82 of file AdjointForm.cpp.
name()
virtual std::string polyfem::solver::AdjointForm::name () const inline override virtual
Implements polyfem::solver::Form.
Reimplemented in polyfem::solver::StaticForm, polyfem::solver::MaxStressForm, polyfem::solver::AMIPSForm, polyfem::solver::DeformedCollisionBarrierForm, polyfem::solver::SpatialIntegralForm, polyfem::solver::ElasticEnergyForm, polyfem::solver::StressNormForm, polyfem::solver::ComplianceForm, polyfem::solver::StressForm, and polyfem::solver::TargetForm.
Definition at line 14 of file AdjointForm.hpp.
Referenced by second_derivative_unweighted().
second_derivative_unweighted()
void polyfem::solver::AdjointForm::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const final override protected virtual
Compute the second derivative of the value wrt x.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Implements polyfem::solver::Form.
Reimplemented in polyfem::solver::AMIPSForm.
Definition at line 32 of file AdjointForm.cpp.
References polyfem::log_and_throw_adjoint_error(), and name().
set_apply_DBC()
void polyfem::solver::AdjointForm::set_apply_DBC (const Eigen::VectorXd & x, bool apply_DBC) final override virtual
Set if the Dirichlet boundary conditions should be enforced.
Note
This is specific to the body form.
Parameters
apply_DBC If true, apply Dirichlet boundary conditions to the current RHS.
Reimplemented from polyfem::solver::Form.
Definition at line 90 of file AdjointForm.cpp.
solution_changed()
void polyfem::solver::AdjointForm::solution_changed (const Eigen::VectorXd & new_x) override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::Form.
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::TransientForm, polyfem::solver::CollisionBarrierForm, and polyfem::solver::DeformedCollisionBarrierForm.
Definition at line 26 of file AdjointForm.cpp.
References AlreadyPrinted, print_energy_, and ToPrint.
Referenced by polyfem::solver::CompositeForm::solution_changed(), polyfem::solver::TransientForm::solution_changed(), polyfem::solver::CollisionBarrierForm::solution_changed(), and polyfem::solver::DeformedCollisionBarrierForm::solution_changed().
update_lagging()
void polyfem::solver::AdjointForm::update_lagging (const Eigen::VectorXd & x, const int iter_num) final override virtual
Update lagged fields.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 86 of file AdjointForm.cpp.
update_quantities()
void polyfem::solver::AdjointForm::update_quantities (const double t, const Eigen::VectorXd & x) final override virtual
Update time-dependent fields.
Parameters
t Current time
x Current solution at time t
Reimplemented from polyfem::solver::Form.
Definition at line 78 of file AdjointForm.cpp.
value()
double polyfem::solver::AdjointForm::value (const Eigen::VectorXd & x) const override virtual
Compute the value of the form multiplied with the weigth.
Parameters
x Current solution
Returns
Computed value
Reimplemented from polyfem::solver::Form.
Definition at line 9 of file AdjointForm.cpp.
References AlreadyPrinted, polyfem::logger(), print_energy_, print_energy_keyword_, ToPrint, val, polyfem::solver::Form::value(), and x.
Referenced by polyfem::solver::BarycenterTargetForm::compute_adjoint_rhs_step(), polyfem::solver::BarycenterTargetForm::compute_partial_gradient_step(), and polyfem::solver::TransientForm::value_unweighted().
Member Data Documentation
print_energy_
PrintStage polyfem::solver::AdjointForm::print_energy_ = PrintStage::Inactive mutable protected
Definition at line 46 of file AdjointForm.hpp.
Referenced by enable_energy_print(), solution_changed(), and value().
print_energy_keyword_
std::string polyfem::solver::AdjointForm::print_energy_keyword_ protected
Definition at line 47 of file AdjointForm.hpp.
Referenced by enable_energy_print(), and value().
variable_to_simulations_
const VariableToSimulationGroup polyfem::solver::AdjointForm::variable_to_simulations_ protected
Definition at line 37 of file AdjointForm.hpp.
Referenced by polyfem::solver::AMIPSForm::compute_partial_gradient(), polyfem::solver::CollisionBarrierForm::compute_partial_gradient(), polyfem::solver::DeformedCollisionBarrierForm::compute_partial_gradient(), polyfem::solver::BoundarySmoothingForm::compute_partial_gradient(), polyfem::solver::SpatialIntegralForm::compute_partial_gradient_step(), polyfem::solver::ElasticEnergyForm::compute_partial_gradient_step(), polyfem::solver::StressNormForm::compute_partial_gradient_step(), polyfem::solver::ComplianceForm::compute_partial_gradient_step(), polyfem::solver::StressForm::compute_partial_gradient_step(), polyfem::solver::NodeTargetForm::compute_partial_gradient_step(), first_derivative(), polyfem::solver::AMIPSForm::get_updated_mesh_nodes(), polyfem::solver::CollisionBarrierForm::get_updated_mesh_nodes(), polyfem::solver::DeformedCollisionBarrierForm::get_updated_mesh_nodes(), and get_variable_to_simulations().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/AdjointForm.hpp
src/polyfem/solver/forms/adjoint_forms/AdjointForm.cpp