PolyFEM: polyfem::assembler::UnconstrainedOgdenElasticity Class Reference
polyfem::assembler::UnconstrainedOgdenElasticity Class Reference
#include <OgdenElasticity.hpp>
Public Member Functions
UnconstrainedOgdenElasticity ()
void add_multimaterial (const int index, const json &params) override
const GenericMatParams & alphas () const
const GenericMatParams & mus () const
const GenericMatParams & Ds () const
Public Member Functions inherited from polyfem::assembler::GenericElastic
GenericElastic ()
virtual ~GenericElastic ()=default
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const override
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > compute_rhs (const AutodiffHessianPt &pt) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &tensor) const
virtual void add_multimaterial (const int index, const json &params)=0
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SpareMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SpareMatrixCache &mat_cache, StiffnessMatrix &grad) const
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
Private Member Functions
template<typename T >
T elastic_energy_T (const RowVectorNd &p, const int el_id, const DefGradMatrix< T > &def_grad) const
Private Attributes
GenericMatParams alphas_
GenericMatParams mus_
GenericMatParams Ds_
Additional Inherited Members
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 8 of file OgdenElasticity.hpp.
Constructor & Destructor Documentation
UnconstrainedOgdenElasticity()
polyfem::assembler::UnconstrainedOgdenElasticity::UnconstrainedOgdenElasticity ()
Definition at line 7 of file OgdenElasticity.cpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::UnconstrainedOgdenElasticity::add_multimaterial (const int index, const json & params) override virtual
Implements polyfem::assembler::GenericElastic.
Definition at line 12 of file OgdenElasticity.cpp.
References polyfem::assembler::GenericMatParams::add_multimaterial(), alphas_, Ds_, mus_, and polyfem::assembler::GenericMatParams::size().
Referenced by polyfem::assembler::MultiModel::add_multimaterial().
alphas()
const GenericMatParams & polyfem::assembler::UnconstrainedOgdenElasticity::alphas () const inline
Definition at line 16 of file OgdenElasticity.hpp.
References alphas_.
Ds()
const GenericMatParams & polyfem::assembler::UnconstrainedOgdenElasticity::Ds () const inline
Definition at line 18 of file OgdenElasticity.hpp.
References Ds_.
elastic_energy_T()
template<typename T > T polyfem::assembler::UnconstrainedOgdenElasticity::elastic_energy_T (const RowVectorNd & p, const int el_id, const DefGradMatrix< T > & def_grad) const private
Definition at line 22 of file OgdenElasticity.cpp.
References alphas_, polyfem::utils::determinant(), Ds_, mus_, polyfem::assembler::Assembler::size(), polyfem::assembler::GenericMatParams::size(), and val.
mus()
const GenericMatParams & polyfem::assembler::UnconstrainedOgdenElasticity::mus () const inline
Definition at line 17 of file OgdenElasticity.hpp.
References mus_.
Member Data Documentation
alphas_
GenericMatParams polyfem::assembler::UnconstrainedOgdenElasticity::alphas_ private
Definition at line 32 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), alphas(), and elastic_energy_T().
Ds_
GenericMatParams polyfem::assembler::UnconstrainedOgdenElasticity::Ds_ private
Definition at line 34 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), Ds(), and elastic_energy_T().
mus_
GenericMatParams polyfem::assembler::UnconstrainedOgdenElasticity::mus_ private
Definition at line 33 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), elastic_energy_T(), and mus().
The documentation for this class was generated from the following files:
src/polyfem/assembler/OgdenElasticity.hpp
src/polyfem/assembler/OgdenElasticity.cpp