PolyFEM: polyfem::assembler::ViscousDamping Class Reference
polyfem::assembler::ViscousDamping Class Reference
#include <ViscousDamping.hpp>
Public Member Functions
ViscousDamping ()=default
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const override
void add_multimaterial (const int index, const json &params)
void set_params (const double psi, const double phi)
double get_psi () const
double get_phi () const
bool is_valid () const
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
Private Member Functions
void compute_stress_aux (const Eigen::MatrixXd &F, const Eigen::MatrixXd &dFdt, Eigen::MatrixXd &dRdF, Eigen::MatrixXd &dRdFdot) const
void compute_stress_grad_aux (const Eigen::MatrixXd &F, const Eigen::MatrixXd &dFdt, Eigen::MatrixXd &d2RdF2, Eigen::MatrixXd &d2RdFdFdot, Eigen::MatrixXd &d2RdFdot2) const
Private Attributes
double psi_ = 0
double phi_ = 0
Additional Inherited Members
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 10 of file ViscousDamping.hpp.
Constructor & Destructor Documentation
ViscousDamping()
polyfem::assembler::ViscousDamping::ViscousDamping () default
Member Function Documentation
add_multimaterial()
void polyfem::assembler::ViscousDamping::add_multimaterial (const int index, const json & params)
Definition at line 61 of file ViscousDamping.cpp.
References phi_, psi_, and polyfem::assembler::Assembler::size().
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const
Definition at line 88 of file Assembler.cpp.
assemble_grad() [1/3]
void polyfem::assembler::NLAssembler::assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const
assemble_grad() [2/3]
Eigen::VectorXd polyfem::assembler::ViscousDamping::assemble_grad (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 73 of file ViscousDamping.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::NonLinearAssemblerData::dt, polyfem::assembler::ElementAssemblyValues::jac_it, phi_, psi_, polyfem::assembler::Assembler::size(), polyfem::assembler::NonLinearAssemblerData::vals, polyfem::assembler::NonLinearAssemblerData::x, and polyfem::assembler::NonLinearAssemblerData::x_prev.
assemble_grad() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_grad (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::SparseMatrixCache & mat_cache, StiffnessMatrix & grad) const
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::ViscousDamping::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 133 of file ViscousDamping.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, compute_stress_grad_aux(), polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::NonLinearAssemblerData::dt, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::Assembler::size(), polyfem::assembler::NonLinearAssemblerData::vals, polyfem::assembler::NonLinearAssemblerData::x, and polyfem::assembler::NonLinearAssemblerData::x_prev.
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
compute_energy()
double polyfem::assembler::ViscousDamping::compute_energy (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 206 of file ViscousDamping.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::NonLinearAssemblerData::dt, polyfem::assembler::ElementAssemblyValues::jac_it, phi_, psi_, polyfem::assembler::Assembler::size(), val, polyfem::assembler::NonLinearAssemblerData::vals, polyfem::assembler::NonLinearAssemblerData::x, and polyfem::assembler::NonLinearAssemblerData::x_prev.
compute_stress_aux()
void polyfem::assembler::ViscousDamping::compute_stress_aux (const Eigen::MatrixXd & F, const Eigen::MatrixXd & dFdt, Eigen::MatrixXd & dRdF, Eigen::MatrixXd & dRdFdot) const private
Definition at line 5 of file ViscousDamping.cpp.
References polyfem::F, phi_, psi_, and polyfem::assembler::Assembler::size().
compute_stress_grad_aux()
void polyfem::assembler::ViscousDamping::compute_stress_grad_aux (const Eigen::MatrixXd & F, const Eigen::MatrixXd & dFdt, Eigen::MatrixXd & d2RdF2, Eigen::MatrixXd & d2RdFdFdot, Eigen::MatrixXd & d2RdFdot2) const private
Definition at line 16 of file ViscousDamping.cpp.
References polyfem::F, phi_, psi_, and polyfem::assembler::Assembler::size().
Referenced by assemble_hessian().
get_phi()
double polyfem::assembler::ViscousDamping::get_phi () const inline
Definition at line 32 of file ViscousDamping.hpp.
References phi_.
get_psi()
double polyfem::assembler::ViscousDamping::get_psi () const inline
Definition at line 31 of file ViscousDamping.hpp.
References psi_.
is_valid()
bool polyfem::assembler::ViscousDamping::is_valid () const inline
Definition at line 34 of file ViscousDamping.hpp.
References phi_, and psi_.
set_params()
void polyfem::assembler::ViscousDamping::set_params (const double psi, const double phi) inline
Definition at line 26 of file ViscousDamping.hpp.
References phi_, and psi_.
Member Data Documentation
phi_
double polyfem::assembler::ViscousDamping::phi_ = 0 private
Definition at line 38 of file ViscousDamping.hpp.
Referenced by add_multimaterial(), assemble_grad(), compute_energy(), compute_stress_aux(), compute_stress_grad_aux(), get_phi(), is_valid(), and set_params().
psi_
double polyfem::assembler::ViscousDamping::psi_ = 0 private
Definition at line 38 of file ViscousDamping.hpp.
Referenced by add_multimaterial(), assemble_grad(), compute_energy(), compute_stress_aux(), compute_stress_grad_aux(), get_psi(), is_valid(), and set_params().
The documentation for this class was generated from the following files:
src/polyfem/assembler/ViscousDamping.hpp
src/polyfem/assembler/ViscousDamping.cpp