PolyFEM: polyfem::solver::VariableToSimulation Class Reference
polyfem::solver::VariableToSimulation Class Reference abstract
Maps the optimization variable to the state variable.
#include <VariableToSimulation.hpp>
Public Member Functions
VariableToSimulation (const std::vector< std::shared_ptr< State > > &states, const CompositeParametrization &parametrization)
VariableToSimulation (const std::shared_ptr< State > &state, const CompositeParametrization &parametrization)
virtual ~VariableToSimulation ()
virtual void update (const Eigen::VectorXd &x)
virtual std::string name () const =0
int n_states () const
const std::vector< std::shared_ptr< State > > & get_states () const
CompositeParametrization & get_parametrization ()
virtual ParameterType get_parameter_type () const =0
virtual Eigen::VectorXd compute_adjoint_term (const Eigen::VectorXd &x) const =0
virtual Eigen::VectorXd inverse_eval ()
virtual void set_output_indexing (const json &args)
Eigen::VectorXi get_output_indexing (const Eigen::VectorXd &x) const
virtual Eigen::VectorXd apply_parametrization_jacobian (const Eigen::VectorXd &term, const Eigen::VectorXd &x) const
Static Public Member Functions
static std::unique_ptr< VariableToSimulation > create (const std::string &type, const std::vector< std::shared_ptr< State > > &states, CompositeParametrization &&parametrization)
Protected Member Functions
virtual void update_state (const Eigen::VectorXd &state_variable, const Eigen::VectorXi &indices)
Protected Attributes
const std::vector< std::shared_ptr< State > > states_
CompositeParametrization parametrization_
Eigen::VectorXi output_indexing_
Detailed Description
Maps the optimization variable to the state variable.
Definition at line 12 of file VariableToSimulation.hpp.
Constructor & Destructor Documentation
VariableToSimulation() [1/2]
polyfem::solver::VariableToSimulation::VariableToSimulation (const std::vector< std::shared_ptr< State > > & states, const CompositeParametrization & parametrization) inline
Definition at line 15 of file VariableToSimulation.hpp.
VariableToSimulation() [2/2]
polyfem::solver::VariableToSimulation::VariableToSimulation (const std::shared_ptr< State > & state, const CompositeParametrization & parametrization) inline
Definition at line 16 of file VariableToSimulation.hpp.
~VariableToSimulation()
virtual polyfem::solver::VariableToSimulation::~VariableToSimulation () inline virtual
Definition at line 17 of file VariableToSimulation.hpp.
Member Function Documentation
apply_parametrization_jacobian()
Eigen::VectorXd polyfem::solver::VariableToSimulation::apply_parametrization_jacobian (const Eigen::VectorXd & term, const Eigen::VectorXd & x) const virtual
Reimplemented in polyfem::solver::PeriodicShapeVariableToSimulation.
Definition at line 80 of file VariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::apply_jacobian(), get_output_indexing(), parametrization_, and x.
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term(), polyfem::solver::ElasticVariableToSimulation::compute_adjoint_term(), polyfem::solver::FrictionCoeffientVariableToSimulation::compute_adjoint_term(), polyfem::solver::DampingCoeffientVariableToSimulation::compute_adjoint_term(), polyfem::solver::InitialConditionVariableToSimulation::compute_adjoint_term(), polyfem::solver::DirichletVariableToSimulation::compute_adjoint_term(), polyfem::solver::DirichletNodesVariableToSimulation::compute_adjoint_term(), polyfem::solver::PressureVariableToSimulation::compute_adjoint_term(), and polyfem::solver::PeriodicShapeVariableToSimulation::compute_adjoint_term().
compute_adjoint_term()
virtual Eigen::VectorXd polyfem::solver::VariableToSimulation::compute_adjoint_term (const Eigen::VectorXd & x) const pure virtual
Implemented in polyfem::solver::ShapeVariableToSimulation, polyfem::solver::ElasticVariableToSimulation, polyfem::solver::FrictionCoeffientVariableToSimulation, polyfem::solver::DampingCoeffientVariableToSimulation, polyfem::solver::InitialConditionVariableToSimulation, polyfem::solver::DirichletVariableToSimulation, polyfem::solver::DirichletNodesVariableToSimulation, polyfem::solver::PressureVariableToSimulation, and polyfem::solver::PeriodicShapeVariableToSimulation.
create()
std::unique_ptr< VariableToSimulation > polyfem::solver::VariableToSimulation::create (const std::string & type, const std::vector< std::shared_ptr< State > > & states, CompositeParametrization && parametrization) static
Definition at line 14 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error().
Referenced by polyfem::solver::AdjointOptUtils::create_simple_form(), and polyfem::solver::AdjointOptUtils::create_variable_to_simulation().
get_output_indexing()
Eigen::VectorXi polyfem::solver::VariableToSimulation::get_output_indexing (const Eigen::VectorXd & x) const
Definition at line 64 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error(), name(), output_indexing_, parametrization_, polyfem::solver::CompositeParametrization::size(), and x.
Referenced by apply_parametrization_jacobian(), polyfem::solver::ShapeVariableToSimulation::inverse_eval(), and update().
get_parameter_type()
virtual ParameterType polyfem::solver::VariableToSimulation::get_parameter_type () const pure virtual
Implemented in polyfem::solver::ShapeVariableToSimulation, polyfem::solver::ElasticVariableToSimulation, polyfem::solver::FrictionCoeffientVariableToSimulation, polyfem::solver::DampingCoeffientVariableToSimulation, polyfem::solver::InitialConditionVariableToSimulation, polyfem::solver::DirichletVariableToSimulation, polyfem::solver::DirichletNodesVariableToSimulation, polyfem::solver::PressureVariableToSimulation, and polyfem::solver::PeriodicShapeVariableToSimulation.
get_parametrization()
CompositeParametrization & polyfem::solver::VariableToSimulation::get_parametrization () inline
Definition at line 31 of file VariableToSimulation.hpp.
References parametrization_.
get_states()
const std::vector< std::shared_ptr< State > > & polyfem::solver::VariableToSimulation::get_states () const inline
Definition at line 29 of file VariableToSimulation.hpp.
References states_.
inverse_eval()
Eigen::VectorXd polyfem::solver::VariableToSimulation::inverse_eval () virtual
Reimplemented in polyfem::solver::ShapeVariableToSimulation, polyfem::solver::ElasticVariableToSimulation, polyfem::solver::FrictionCoeffientVariableToSimulation, polyfem::solver::DampingCoeffientVariableToSimulation, polyfem::solver::InitialConditionVariableToSimulation, polyfem::solver::DirichletVariableToSimulation, polyfem::solver::DirichletNodesVariableToSimulation, polyfem::solver::PressureVariableToSimulation, and polyfem::solver::PeriodicShapeVariableToSimulation.
Definition at line 85 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error(), and name().
n_states()
int polyfem::solver::VariableToSimulation::n_states () const inline
Definition at line 28 of file VariableToSimulation.hpp.
References states_.
name()
virtual std::string polyfem::solver::VariableToSimulation::name () const pure virtual
Implemented in polyfem::solver::ShapeVariableToSimulation, polyfem::solver::ElasticVariableToSimulation, polyfem::solver::FrictionCoeffientVariableToSimulation, polyfem::solver::DampingCoeffientVariableToSimulation, polyfem::solver::InitialConditionVariableToSimulation, polyfem::solver::DirichletVariableToSimulation, polyfem::solver::DirichletNodesVariableToSimulation, polyfem::solver::PressureVariableToSimulation, and polyfem::solver::PeriodicShapeVariableToSimulation.
Referenced by get_output_indexing(), inverse_eval(), and update_state().
set_output_indexing()
void polyfem::solver::VariableToSimulation::set_output_indexing (const json & args) virtual
Reimplemented in polyfem::solver::ShapeVariableToSimulation, polyfem::solver::DirichletVariableToSimulation, polyfem::solver::DirichletNodesVariableToSimulation, and polyfem::solver::PressureVariableToSimulation.
Definition at line 39 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error(), output_indexing_, polyfem::io::read_matrix(), polyfem::State::resolve_input_path(), states_, and tmp_mat.
Referenced by polyfem::solver::ShapeVariableToSimulation::set_output_indexing(), polyfem::solver::DirichletVariableToSimulation::set_output_indexing(), polyfem::solver::DirichletNodesVariableToSimulation::set_output_indexing(), and polyfem::solver::PressureVariableToSimulation::set_output_indexing().
update()
virtual void polyfem::solver::VariableToSimulation::update (const Eigen::VectorXd & x) inline virtual
Reimplemented in polyfem::solver::PeriodicShapeVariableToSimulation.
Definition at line 21 of file VariableToSimulation.hpp.
References polyfem::solver::CompositeParametrization::eval(), get_output_indexing(), parametrization_, update_state(), and x.
update_state()
void polyfem::solver::VariableToSimulation::update_state (const Eigen::VectorXd & state_variable, const Eigen::VectorXi & indices) protected virtual
Reimplemented in polyfem::solver::ShapeVariableToSimulation, polyfem::solver::ElasticVariableToSimulation, polyfem::solver::FrictionCoeffientVariableToSimulation, polyfem::solver::DampingCoeffientVariableToSimulation, polyfem::solver::InitialConditionVariableToSimulation, polyfem::solver::DirichletVariableToSimulation, polyfem::solver::DirichletNodesVariableToSimulation, and polyfem::solver::PressureVariableToSimulation.
Definition at line 91 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_adjoint_error(), and name().
Referenced by update().
Member Data Documentation
output_indexing_
Eigen::VectorXi polyfem::solver::VariableToSimulation::output_indexing_ protected
Definition at line 46 of file VariableToSimulation.hpp.
Referenced by get_output_indexing(), set_output_indexing(), polyfem::solver::ShapeVariableToSimulation::set_output_indexing(), polyfem::solver::DirichletVariableToSimulation::set_output_indexing(), and polyfem::solver::PressureVariableToSimulation::set_output_indexing().
parametrization_
CompositeParametrization polyfem::solver::VariableToSimulation::parametrization_ protected
Definition at line 44 of file VariableToSimulation.hpp.
Referenced by apply_parametrization_jacobian(), polyfem::solver::PeriodicShapeVariableToSimulation::apply_parametrization_jacobian(), get_output_indexing(), get_parametrization(), polyfem::solver::ShapeVariableToSimulation::inverse_eval(), polyfem::solver::ElasticVariableToSimulation::inverse_eval(), polyfem::solver::DirichletVariableToSimulation::inverse_eval(), polyfem::solver::PressureVariableToSimulation::inverse_eval(), polyfem::solver::PeriodicShapeVariableToSimulation::inverse_eval(), update(), and polyfem::solver::PeriodicShapeVariableToSimulation::update().
states_
const std::vector<std::shared_ptr<State> > polyfem::solver::VariableToSimulation::states_ protected
Definition at line 43 of file VariableToSimulation.hpp.
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term(), polyfem::solver::ElasticVariableToSimulation::compute_adjoint_term(), polyfem::solver::FrictionCoeffientVariableToSimulation::compute_adjoint_term(), polyfem::solver::DampingCoeffientVariableToSimulation::compute_adjoint_term(), polyfem::solver::InitialConditionVariableToSimulation::compute_adjoint_term(), polyfem::solver::DirichletVariableToSimulation::compute_adjoint_term(), polyfem::solver::DirichletNodesVariableToSimulation::compute_adjoint_term(), polyfem::solver::PressureVariableToSimulation::compute_adjoint_term(), polyfem::solver::PeriodicShapeVariableToSimulation::compute_adjoint_term(), get_states(), polyfem::solver::ShapeVariableToSimulation::inverse_eval(), polyfem::solver::ElasticVariableToSimulation::inverse_eval(), polyfem::solver::InitialConditionVariableToSimulation::inverse_eval(), polyfem::solver::DirichletVariableToSimulation::inverse_eval(), polyfem::solver::PressureVariableToSimulation::inverse_eval(), polyfem::solver::PeriodicShapeVariableToSimulation::inverse_eval(), n_states(), set_output_indexing(), polyfem::solver::ShapeVariableToSimulation::set_output_indexing(), polyfem::solver::DirichletVariableToSimulation::set_output_indexing(), polyfem::solver::PressureVariableToSimulation::set_output_indexing(), polyfem::solver::PeriodicShapeVariableToSimulation::update(), polyfem::solver::ShapeVariableToSimulation::update_state(), polyfem::solver::ElasticVariableToSimulation::update_state(), polyfem::solver::FrictionCoeffientVariableToSimulation::update_state(), polyfem::solver::DampingCoeffientVariableToSimulation::update_state(), polyfem::solver::InitialConditionVariableToSimulation::update_state(), polyfem::solver::DirichletVariableToSimulation::update_state(), polyfem::solver::DirichletNodesVariableToSimulation::update_state(), and polyfem::solver::PressureVariableToSimulation::update_state().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/VariableToSimulation.hpp
src/polyfem/solver/forms/adjoint_forms/VariableToSimulation.cpp