PolyFEM: polyfem::solver::PeriodicShapeVariableToSimulation Class Reference
polyfem::solver::PeriodicShapeVariableToSimulation Class Reference
#include <PeriodicShapeVariableToSimulation.hpp>
Public Types
using StatePtrs = std::vector< std::shared_ptr< legacy::State > >
using DiffCachePtrs = std::vector< std::shared_ptr< DiffCache > >
Public Member Functions
PeriodicShapeVariableToSimulation (StatePtrs states, DiffCachePtrs diff_caches, CompositeParametrization parametrizations)
Construct PeriodicShapeVariableToSimulation.
std::string name () const override
ParameterType parameter_type () const override
bool affect_state (const legacy::State &target) const override
Return true if current var2sim maps to target state.
void update (const Eigen::VectorXd &x) override
Update forward simulation states from optimization variables.
void update_state_variables (const Eigen::VectorXd &x, Eigen::VectorXd &state_variables) const override
Update state variables from optimization variables.
Eigen::VectorXd compute_adjoint_term (const Eigen::VectorXd &x) const override
Compute adjoint contribution of objective gradient.
int inverse_dof () const override
Compute optimization variables dof.
Eigen::VectorXd inverse_eval () const override
Compute optimization variables from forward simulation legacy::State.
Eigen::VectorXd apply_parametrization_jacobian (const Eigen::VectorXd &term, const Eigen::VectorXd &x) const override
Apply parametrization jacobian to compute the gradient w.r.t.
Public Member Functions inherited from polyfem::solver::VariableToSimulation
virtual ~VariableToSimulation ()=default
Private Member Functions
int para_out_dof () const
Private Attributes
int dim_
int vertex_num_
StatePtrs states_
DiffCachePtrs diff_caches_
CompositeParametrization parametrization_
std::unique_ptr< PeriodicMeshToMesh > periodic_mesh_map_
Detailed Description
Definition at line 14 of file PeriodicShapeVariableToSimulation.hpp.
Member Typedef Documentation
DiffCachePtrs
using polyfem::solver::PeriodicShapeVariableToSimulation::DiffCachePtrs = std::vector<std::shared_ptr<DiffCache> >
Definition at line 18 of file PeriodicShapeVariableToSimulation.hpp.
StatePtrs
using polyfem::solver::PeriodicShapeVariableToSimulation::StatePtrs = std::vector<std::shared_ptr<legacy::State> >
Definition at line 17 of file PeriodicShapeVariableToSimulation.hpp.
Constructor & Destructor Documentation
PeriodicShapeVariableToSimulation()
polyfem::solver::PeriodicShapeVariableToSimulation::PeriodicShapeVariableToSimulation (StatePtrs states, DiffCachePtrs diff_caches, CompositeParametrization parametrizations)
Construct PeriodicShapeVariableToSimulation.
Parameters
[in] states Shared ptr to all forward sim states.
[in] diff_caches Shared ptr to all diff caches.
[in] parametrizations Parametrizations.
Exceptions
std::runtime_error Throw if input is invalid.
Definition at line 17 of file PeriodicShapeVariableToSimulation.cpp.
References diff_caches_, dim_, polyfem::log_and_throw_adjoint_error(), periodic_mesh_map_, states_, V, and vertex_num_.
Member Function Documentation
affect_state()
bool polyfem::solver::PeriodicShapeVariableToSimulation::affect_state (const legacy::State & target) const override virtual
Return true if current var2sim maps to target state.
Implements polyfem::solver::VariableToSimulation.
Definition at line 73 of file PeriodicShapeVariableToSimulation.cpp.
References states_.
apply_parametrization_jacobian()
Eigen::VectorXd polyfem::solver::PeriodicShapeVariableToSimulation::apply_parametrization_jacobian (const Eigen::VectorXd & term, const Eigen::VectorXd & x) const override virtual
Apply parametrization jacobian to compute the gradient w.r.t.
to optimization variables.
Parameters
term Gradient w.r.t. to full inherent dof (Ex. all vertices for shape var2sim)
x Optimization variables.
Implements polyfem::solver::VariableToSimulation.
Definition at line 153 of file PeriodicShapeVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::apply_jacobian(), dim_, polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, periodic_mesh_map_, vertex_num_, x, and y.
compute_adjoint_term()
Eigen::VectorXd polyfem::solver::PeriodicShapeVariableToSimulation::compute_adjoint_term (const Eigen::VectorXd & x) const override virtual
Compute adjoint contribution of objective gradient.
See arXiv:2205.13643.
Let objective function be J and optimization variable be x. This method computes all adjoint related terms in dJ/dx. For static case (E.q. 11), it's the second term. For dynamic case (E.q. 15), it's everything except ∂qJ.
Parameters
x[in] Optimization variables.
Returns
Adjoint contribution of objective gradient.
Implements polyfem::solver::VariableToSimulation.
Definition at line 103 of file PeriodicShapeVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::apply_jacobian(), diff_caches_, polyfem::solver::AdjointTools::dJ_periodic_shape_adjoint_term(), polyfem::solver::CompositeParametrization::eval(), polyfem::get_adjoint_mat(), para_out_dof(), parametrization_, periodic_mesh_map_, states_, x, and y.
inverse_dof()
int polyfem::solver::PeriodicShapeVariableToSimulation::inverse_dof () const override virtual
Compute optimization variables dof.
Returns
Optimization variables dof.
Exceptions
std::runtime_error Throw if not implemented.
Implements polyfem::solver::VariableToSimulation.
Definition at line 139 of file PeriodicShapeVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::inverse_size(), para_out_dof(), and parametrization_.
inverse_eval()
Eigen::VectorXd polyfem::solver::PeriodicShapeVariableToSimulation::inverse_eval () const override virtual
Compute optimization variables from forward simulation legacy::State.
Returns
Optimization variables.
Exceptions
std::runtime_error Throw if not implemented.
Implements polyfem::solver::VariableToSimulation.
Definition at line 144 of file PeriodicShapeVariableToSimulation.cpp.
References polyfem::utils::flatten(), polyfem::solver::CompositeParametrization::inverse_eval(), parametrization_, periodic_mesh_map_, states_, V, and y.
name()
std::string polyfem::solver::PeriodicShapeVariableToSimulation::name () const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 63 of file PeriodicShapeVariableToSimulation.cpp.
para_out_dof()
int polyfem::solver::PeriodicShapeVariableToSimulation::para_out_dof () const private
Definition at line 166 of file PeriodicShapeVariableToSimulation.cpp.
References periodic_mesh_map_.
Referenced by apply_parametrization_jacobian(), compute_adjoint_term(), inverse_dof(), update(), and update_state_variables().
parameter_type()
ParameterType polyfem::solver::PeriodicShapeVariableToSimulation::parameter_type () const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 68 of file PeriodicShapeVariableToSimulation.cpp.
References polyfem::solver::PeriodicShape.
update()
void polyfem::solver::PeriodicShapeVariableToSimulation::update (const Eigen::VectorXd & x) override virtual
Update forward simulation states from optimization variables.
Parameters
[in] x Optimization variables.
Implements polyfem::solver::VariableToSimulation.
Definition at line 83 of file PeriodicShapeVariableToSimulation.cpp.
References dim_, polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, periodic_mesh_map_, states_, polyfem::utils::unflatten(), V, vertex_num_, x, and y.
update_state_variables()
void polyfem::solver::PeriodicShapeVariableToSimulation::update_state_variables (const Eigen::VectorXd & x, Eigen::VectorXd & state_variables) const override virtual
Update state variables from optimization variables.
Compared to update() this method update abstract state variables instead of writing directly to state.
Parameters
[in] x Optimization variables.
[out] state_variables Abstract state variables update dst.
Implements polyfem::solver::VariableToSimulation.
Definition at line 97 of file PeriodicShapeVariableToSimulation.cpp.
References polyfem::solver::CompositeParametrization::eval(), para_out_dof(), parametrization_, and x.
Member Data Documentation
diff_caches_
DiffCachePtrs polyfem::solver::PeriodicShapeVariableToSimulation::diff_caches_ private
Definition at line 43 of file PeriodicShapeVariableToSimulation.hpp.
Referenced by compute_adjoint_term(), and PeriodicShapeVariableToSimulation().
dim_
int polyfem::solver::PeriodicShapeVariableToSimulation::dim_ private
Definition at line 40 of file PeriodicShapeVariableToSimulation.hpp.
Referenced by apply_parametrization_jacobian(), PeriodicShapeVariableToSimulation(), and update().
parametrization_
CompositeParametrization polyfem::solver::PeriodicShapeVariableToSimulation::parametrization_ private
Definition at line 44 of file PeriodicShapeVariableToSimulation.hpp.
Referenced by apply_parametrization_jacobian(), compute_adjoint_term(), inverse_dof(), inverse_eval(), update(), and update_state_variables().
periodic_mesh_map_
std::unique_ptr<PeriodicMeshToMesh> polyfem::solver::PeriodicShapeVariableToSimulation::periodic_mesh_map_ private
Definition at line 47 of file PeriodicShapeVariableToSimulation.hpp.
Referenced by apply_parametrization_jacobian(), compute_adjoint_term(), inverse_eval(), para_out_dof(), PeriodicShapeVariableToSimulation(), and update().
states_
StatePtrs polyfem::solver::PeriodicShapeVariableToSimulation::states_ private
Definition at line 42 of file PeriodicShapeVariableToSimulation.hpp.
Referenced by affect_state(), compute_adjoint_term(), inverse_eval(), PeriodicShapeVariableToSimulation(), and update().
vertex_num_
int polyfem::solver::PeriodicShapeVariableToSimulation::vertex_num_ private
Definition at line 41 of file PeriodicShapeVariableToSimulation.hpp.
Referenced by apply_parametrization_jacobian(), PeriodicShapeVariableToSimulation(), and update().
The documentation for this class was generated from the following files:
src/polyfem/optimization/var2sims/PeriodicShapeVariableToSimulation.hpp
src/polyfem/optimization/var2sims/PeriodicShapeVariableToSimulation.cpp