PolyFEM: polyfem::solver::DirichletVariableToSimulation Class Reference
polyfem::solver::DirichletVariableToSimulation Class Reference
#include <VariableToSimulation.hpp>
Public Member Functions
virtual ~DirichletVariableToSimulation ()
ParameterType get_parameter_type () const override
Eigen::VectorXd compute_adjoint_term (const Eigen::VectorXd &x) const override
virtual Eigen::VectorXd inverse_eval () override
VariableToSimulation (const std::vector< std::shared_ptr< State > > &states, const CompositeParametrization &parametrization)
VariableToSimulation (const std::shared_ptr< State > &state, const CompositeParametrization &parametrization)
Public Member Functions inherited from polyfem::solver::VariableToSimulation
VariableToSimulation (const std::vector< std::shared_ptr< State > > &states, const CompositeParametrization &parametrization)
VariableToSimulation (const std::shared_ptr< State > &state, const CompositeParametrization &parametrization)
virtual ~VariableToSimulation ()
virtual void update (const Eigen::VectorXd &x)
int n_states () const
const std::vector< std::shared_ptr< State > > & get_states () const
CompositeParametrization & get_parametrization ()
void set_output_indexing (const Eigen::VectorXi &output_indexing)
Eigen::VectorXi get_output_indexing (const Eigen::VectorXd &x) const
virtual Eigen::VectorXd apply_parametrization_jacobian (const Eigen::VectorXd &term, const Eigen::VectorXd &x) const
Protected Member Functions
void update_state (const Eigen::VectorXd &state_variable, const Eigen::VectorXi &indices) override
Private Member Functions
std::string variable_to_string (const Eigen::VectorXd &variable)
Additional Inherited Members
Protected Attributes inherited from polyfem::solver::VariableToSimulation
std::vector< std::shared_ptr< State > > states_
CompositeParametrization parametrization_
Eigen::VectorXi output_indexing_
Detailed Description
Definition at line 127 of file VariableToSimulation.hpp.
Constructor & Destructor Documentation
~DirichletVariableToSimulation()
virtual polyfem::solver::DirichletVariableToSimulation::~DirichletVariableToSimulation () inline virtual
Definition at line 131 of file VariableToSimulation.hpp.
Member Function Documentation
compute_adjoint_term()
Eigen::VectorXd polyfem::solver::DirichletVariableToSimulation::compute_adjoint_term (const Eigen::VectorXd & x) const override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 328 of file VariableToSimulation.cpp.
References polyfem::solver::VariableToSimulation::apply_parametrization_jacobian(), polyfem::solver::AdjointTools::dJ_dirichlet_transient_adjoint_term(), polyfem::log_and_throw_error(), polyfem::solver::VariableToSimulation::states_, and x.
get_parameter_type()
ParameterType polyfem::solver::DirichletVariableToSimulation::get_parameter_type () const inline override virtual
Implements polyfem::solver::VariableToSimulation.
Definition at line 133 of file VariableToSimulation.hpp.
References polyfem::solver::DirichletBC.
inverse_eval()
Eigen::VectorXd polyfem::solver::DirichletVariableToSimulation::inverse_eval () override virtual
Reimplemented from polyfem::solver::VariableToSimulation.
Definition at line 355 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_error().
update_state()
void polyfem::solver::DirichletVariableToSimulation::update_state (const Eigen::VectorXd & state_variable, const Eigen::VectorXi & indices) override protected virtual
Reimplemented from polyfem::solver::VariableToSimulation.
Definition at line 312 of file VariableToSimulation.cpp.
References polyfem::log_and_throw_error().
variable_to_string()
std::string polyfem::solver::DirichletVariableToSimulation::variable_to_string (const Eigen::VectorXd & variable) private
Definition at line 351 of file VariableToSimulation.cpp.
VariableToSimulation() [1/2]
polyfem::solver::VariableToSimulation::VariableToSimulation (const std::shared_ptr< State > & state, const CompositeParametrization & parametrization) inline
Definition at line 12 of file VariableToSimulation.hpp.
VariableToSimulation() [2/2]
polyfem::solver::VariableToSimulation::VariableToSimulation (const std::vector< std::shared_ptr< State > > & states, const CompositeParametrization & parametrization) inline
Definition at line 11 of file VariableToSimulation.hpp.
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/adjoint_forms/VariableToSimulation.hpp
src/polyfem/solver/forms/adjoint_forms/VariableToSimulation.cpp