PolyFEM: polyfem::assembler::NavierStokesVelocity Class Reference
polyfem::assembler::NavierStokesVelocity Class Reference
#include <NavierStokes.hpp>
Public Member Functions
std::string name () const override
std::map< std::string, ParamFunc > parameters () const override
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
VectorNd compute_rhs (const AutodiffHessianPt &pt) const override
void add_multimaterial (const int index, const json &params) override
bool is_fluid () const override
void set_picard (const bool val)
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual bool is_linear () const override
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
virtual std::string name () const =0
int size () const
virtual void set_size (const int size)
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
virtual void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual std::map< std::string, ParamFunc > parameters () const =0
virtual VectorNd compute_rhs (const AutodiffHessianPt &pt) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params)
virtual void add_multimaterial (const int index, const json &params)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_linear () const =0
virtual bool is_solution_displacement () const
virtual bool is_fluid () const
virtual bool is_tensor () const
Private Member Functions
Eigen::MatrixXd compute_N (const NonLinearAssemblerData &data) const
Eigen::MatrixXd compute_W (const NonLinearAssemblerData &data) const
Private Attributes
double viscosity_ = 1
bool full_gradient_ = true
Additional Inherited Members
Public Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 9 of file NavierStokes.hpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::NavierStokesVelocity::add_multimaterial (const int index, const json & params) override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 6 of file NavierStokes.cpp.
References polyfem::assembler::Assembler::size(), and viscosity_.
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
Definition at line 242 of file Assembler.cpp.
assemble_gradient() [1/3]
void polyfem::assembler::NLAssembler::assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
assemble_gradient() [2/3]
Eigen::VectorXd polyfem::assembler::NavierStokesVelocity::assemble_gradient (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 35 of file NavierStokes.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::Assembler::size(), and polyfem::assembler::NonLinearAssemblerData::vals.
assemble_gradient() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_gradient (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::SparseMatrixCache & mat_cache, StiffnessMatrix & grad) const override virtual
Reimplemented from polyfem::assembler::NLAssembler.
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::NavierStokesVelocity::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 42 of file NavierStokes.cpp.
References compute_N(), compute_W(), and full_gradient_.
Referenced by polyfem::solver::NavierStokesSolver::minimize_aux(), and polyfem::solver::TransientNavierStokesSolver::minimize_aux().
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
compute_energy()
double polyfem::assembler::NavierStokesVelocity::compute_energy (const NonLinearAssemblerData & data) const inline override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 20 of file NavierStokes.hpp.
compute_N()
Eigen::MatrixXd polyfem::assembler::NavierStokesVelocity::compute_N (const NonLinearAssemblerData & data) const private
Definition at line 55 of file NavierStokes.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::Assembler::size(), val, polyfem::assembler::NonLinearAssemblerData::vals, and polyfem::assembler::NonLinearAssemblerData::x.
Referenced by assemble_hessian().
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::NavierStokesVelocity::compute_rhs (const AutodiffHessianPt & pt) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 17 of file NavierStokes.cpp.
References polyfem::assembler::Assembler::size(), val, and viscosity_.
compute_W()
Eigen::MatrixXd polyfem::assembler::NavierStokesVelocity::compute_W (const NonLinearAssemblerData & data) const private
Definition at line 133 of file NavierStokes.cpp.
References polyfem::assembler::ElementAssemblyValues::basis_values, polyfem::assembler::NonLinearAssemblerData::da, polyfem::assembler::ElementAssemblyValues::jac_it, polyfem::assembler::Assembler::size(), polyfem::assembler::NonLinearAssemblerData::vals, and polyfem::assembler::NonLinearAssemblerData::x.
Referenced by assemble_hessian().
is_fluid()
bool polyfem::assembler::NavierStokesVelocity::is_fluid () const inline override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 42 of file NavierStokes.hpp.
name()
std::string polyfem::assembler::NavierStokesVelocity::name () const inline override virtual
Implements polyfem::assembler::Assembler.
Definition at line 16 of file NavierStokes.hpp.
Referenced by polyfem::solver::TransientNavierStokesSolver::minimize(), and polyfem::solver::NavierStokesSolver::minimize().
parameters()
std::map< std::string, Assembler::ParamFunc > polyfem::assembler::NavierStokesVelocity::parameters () const override virtual
Implements polyfem::assembler::Assembler.
Definition at line 213 of file NavierStokes.cpp.
References viscosity_.
set_picard()
void polyfem::assembler::NavierStokesVelocity::set_picard (const bool val) inline
Definition at line 44 of file NavierStokes.hpp.
References full_gradient_, and val.
Referenced by polyfem::solver::NavierStokesSolver::minimize_aux(), and polyfem::solver::TransientNavierStokesSolver::minimize_aux().
Member Data Documentation
full_gradient_
bool polyfem::assembler::NavierStokesVelocity::full_gradient_ = true private
Definition at line 50 of file NavierStokes.hpp.
Referenced by assemble_hessian(), and set_picard().
viscosity_
double polyfem::assembler::NavierStokesVelocity::viscosity_ = 1 private
Definition at line 47 of file NavierStokes.hpp.
Referenced by add_multimaterial(), compute_rhs(), and parameters().
The documentation for this class was generated from the following files:
src/polyfem/assembler/NavierStokes.hpp
src/polyfem/assembler/NavierStokes.cpp