PolyFEM: polyfem::utils::base64Layer Class Reference
polyfem::utils::base64Layer Class Reference
#include <base64Layer.hpp>
Public Member Functions
base64Layer (std::ostream &os)
~base64Layer ()
void write (const char *s, std::streamsize n)
void write (const uint64_t v)
void write (const int64_t v)
void write (const int8_t v)
void write (const uint8_t v)
void write (const int64_t *v, const int n)
void write (const double *v, const int n)
void write (const float *v, const int n)
void reset ()
bool close ()
Private Member Functions
unsigned char encode0 () const
unsigned char encode1 () const
unsigned char encode2 () const
unsigned char encode3 () const
base64Layer (const base64Layer &)=delete
void operator= (const base64Layer &)=delete
void add (char c)
Static Private Member Functions
static std::size_t encodedLength (std::size_t n)
Private Attributes
std::ostream & os_
unsigned char group_ [3]
unsigned char groupLen_
bool dirty_
Detailed Description
Definition at line 9 of file base64Layer.hpp.
Constructor & Destructor Documentation
base64Layer() [1/2]
polyfem::utils::base64Layer::base64Layer (const base64Layer &) private delete
base64Layer() [2/2]
polyfem::utils::base64Layer::base64Layer (std::ostream & os)
Definition at line 72 of file base64Layer.cpp.
~base64Layer()
polyfem::utils::base64Layer::~base64Layer ()
Definition at line 80 of file base64Layer.cpp.
References close().
Member Function Documentation
add()
void polyfem::utils::base64Layer::add (char c) private
Definition at line 53 of file base64Layer.cpp.
References dirty_, encode0(), encode1(), encode2(), encode3(), group_, groupLen_, and os_.
Referenced by write().
close()
bool polyfem::utils::base64Layer::close ()
Definition at line 99 of file base64Layer.cpp.
References dirty_, encode0(), encode1(), encode2(), group_, groupLen_, and os_.
Referenced by polyfem::mesh::VTUWriter::write_cells(), polyfem::mesh::VTUWriter::write_points(), and ~base64Layer().
encode0()
unsigned char polyfem::utils::base64Layer::encode0 () const inline private
Definition at line 29 of file base64Layer.cpp.
References group_.
Referenced by add(), and close().
encode1()
unsigned char polyfem::utils::base64Layer::encode1 () const inline private
Definition at line 35 of file base64Layer.cpp.
References group_.
Referenced by add(), and close().
encode2()
unsigned char polyfem::utils::base64Layer::encode2 () const inline private
Definition at line 41 of file base64Layer.cpp.
References group_.
Referenced by add(), and close().
encode3()
unsigned char polyfem::utils::base64Layer::encode3 () const inline private
Definition at line 47 of file base64Layer.cpp.
References group_.
Referenced by add().
encodedLength()
std::size_t polyfem::utils::base64Layer::encodedLength (std::size_t n) static private
Definition at line 24 of file base64Layer.cpp.
operator=()
void polyfem::utils::base64Layer::operator= (const base64Layer &) private delete
reset()
void polyfem::utils::base64Layer::reset ()
Definition at line 93 of file base64Layer.cpp.
References dirty_, and groupLen_.
write() [1/8]
void polyfem::utils::base64Layer::write (const char * s, std::streamsize n)
Definition at line 85 of file base64Layer.cpp.
References add().
Referenced by polyfem::mesh::VTUWriter::write_cells(), and polyfem::mesh::VTUWriter::write_points().
write() [2/8]
void polyfem::utils::base64Layer::write (const double * v, const int n) inline
Definition at line 51 of file base64Layer.hpp.
References write().
Referenced by write().
write() [3/8]
void polyfem::utils::base64Layer::write (const float * v, const int n) inline
Definition at line 52 of file base64Layer.hpp.
References write().
Referenced by write().
write() [4/8]
void polyfem::utils::base64Layer::write (const int64_t * v, const int n) inline
Definition at line 50 of file base64Layer.hpp.
References write().
Referenced by write().
write() [5/8]
void polyfem::utils::base64Layer::write (const int64_t v) inline
Definition at line 46 of file base64Layer.hpp.
References write().
Referenced by write().
write() [6/8]
void polyfem::utils::base64Layer::write (const int8_t v) inline
Definition at line 47 of file base64Layer.hpp.
References write().
Referenced by write().
write() [7/8]
void polyfem::utils::base64Layer::write (const uint64_t v) inline
Definition at line 45 of file base64Layer.hpp.
References write().
Referenced by write().
write() [8/8]
void polyfem::utils::base64Layer::write (const uint8_t v) inline
Definition at line 48 of file base64Layer.hpp.
References write().
Referenced by write().
Member Data Documentation
dirty_
bool polyfem::utils::base64Layer::dirty_ private
Definition at line 22 of file base64Layer.hpp.
Referenced by add(), close(), and reset().
group_
unsigned char polyfem::utils::base64Layer::group_[3] private
Definition at line 16 of file base64Layer.hpp.
Referenced by add(), close(), encode0(), encode1(), encode2(), and encode3().
groupLen_
unsigned char polyfem::utils::base64Layer::groupLen_ private
Definition at line 19 of file base64Layer.hpp.
Referenced by add(), close(), and reset().
os_
std::ostream& polyfem::utils::base64Layer::os_ private
Definition at line 13 of file base64Layer.hpp.
Referenced by add(), and close().
The documentation for this class was generated from the following files:
src/polyfem/utils/base64Layer.hpp
src/polyfem/utils/base64Layer.cpp