PolyFEM: polyfem::assembler::IncompressibleOgdenElasticity Class Reference
polyfem::assembler::IncompressibleOgdenElasticity Class Reference
#include <OgdenElasticity.hpp>
Public Member Functions
IncompressibleOgdenElasticity ()
void add_multimaterial (const int index, const json &params) override
const GenericMatParams & coefficients () const
Coefficient of nth term, where n can range from 1 to 6.
const GenericMatParams & expoenents () const
Exponent of nth term, where n can range from 1 to 6.
const GenericMatParam & bulk_modulus () const
Bulk modulus.
int num_terms () const
Number of terms in the Ogden model.
Public Member Functions inherited from polyfem::assembler::GenericElastic
GenericElastic ()
virtual ~GenericElastic ()=default
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const override
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > compute_rhs (const AutodiffHessianPt &pt) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &tensor) const
virtual void add_multimaterial (const int index, const json &params)=0
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_grad (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &grad) const
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void set_size (const int size)
Private Member Functions
template<typename T >
T elastic_energy_T (const RowVectorNd &p, const int el_id, const DefGradMatrix< T > &def_grad) const
Private Attributes
GenericMatParams coefficients_
GenericMatParams expoenents_
GenericMatParam bulk_modulus_
Additional Inherited Members
virtual double compute_energy (const NonLinearAssemblerData &data) const =0
virtual Eigen::VectorXd assemble_grad (const NonLinearAssemblerData &data) const =0
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const =0
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Detailed Description
Definition at line 37 of file OgdenElasticity.hpp.
Constructor & Destructor Documentation
IncompressibleOgdenElasticity()
polyfem::assembler::IncompressibleOgdenElasticity::IncompressibleOgdenElasticity ()
Definition at line 75 of file OgdenElasticity.cpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::IncompressibleOgdenElasticity::add_multimaterial (const int index, const json & params) override virtual
Implements polyfem::assembler::GenericElastic.
Definition at line 80 of file OgdenElasticity.cpp.
References polyfem::assembler::GenericMatParam::add_multimaterial(), polyfem::assembler::GenericMatParams::add_multimaterial(), bulk_modulus_, coefficients_, expoenents_, and polyfem::assembler::GenericMatParams::size().
Referenced by polyfem::assembler::MultiModel::add_multimaterial().
bulk_modulus()
const GenericMatParam & polyfem::assembler::IncompressibleOgdenElasticity::bulk_modulus () const inline
Bulk modulus.
Definition at line 50 of file OgdenElasticity.hpp.
References bulk_modulus_.
coefficients()
const GenericMatParams & polyfem::assembler::IncompressibleOgdenElasticity::coefficients () const inline
Coefficient of nth term, where n can range from 1 to 6.
Definition at line 46 of file OgdenElasticity.hpp.
References coefficients_.
elastic_energy_T()
template<typename T > T polyfem::assembler::IncompressibleOgdenElasticity::elastic_energy_T (const RowVectorNd & p, const int el_id, const DefGradMatrix< T > & def_grad) const private
Definition at line 89 of file OgdenElasticity.cpp.
References bulk_modulus_, coefficients_, polyfem::utils::determinant(), expoenents_, num_terms(), polyfem::assembler::Assembler::size(), and val.
expoenents()
const GenericMatParams & polyfem::assembler::IncompressibleOgdenElasticity::expoenents () const inline
Exponent of nth term, where n can range from 1 to 6.
Definition at line 48 of file OgdenElasticity.hpp.
References expoenents_.
num_terms()
int polyfem::assembler::IncompressibleOgdenElasticity::num_terms () const inline
Number of terms in the Ogden model.
Definition at line 53 of file OgdenElasticity.hpp.
References coefficients_, and polyfem::assembler::GenericMatParams::size().
Referenced by elastic_energy_T().
Member Data Documentation
bulk_modulus_
GenericMatParam polyfem::assembler::IncompressibleOgdenElasticity::bulk_modulus_ private
Definition at line 69 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), bulk_modulus(), and elastic_energy_T().
coefficients_
GenericMatParams polyfem::assembler::IncompressibleOgdenElasticity::coefficients_ private
Definition at line 67 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), coefficients(), elastic_energy_T(), and num_terms().
expoenents_
GenericMatParams polyfem::assembler::IncompressibleOgdenElasticity::expoenents_ private
Definition at line 68 of file OgdenElasticity.hpp.
Referenced by add_multimaterial(), elastic_energy_T(), and expoenents().
The documentation for this class was generated from the following files:
src/polyfem/assembler/OgdenElasticity.hpp
src/polyfem/assembler/OgdenElasticity.cpp