PolyFEM: polyfem::assembler::AssemblerUtils Class Reference
polyfem::assembler::AssemblerUtils Class Reference
#include <AssemblerUtils.hpp>
Public Types
enum class BasisType { SIMPLEX_LAGRANGE , CUBE_LAGRANGE , SPLINE , POLY }
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Public Member Functions
AssemblerUtils ()
~AssemblerUtils ()
void assemble_problem (const std::string &assembler, const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness) const
void assemble_mass_matrix (const std::string &assembler, const bool is_volume, const int n_basis, const bool use_density, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &mass) const
void assemble_mixed_problem (const std::string &assembler, const bool is_volume, const int n_psi_basis, const int n_phi_basis, const std::vector< basis::ElementBases > &psi_bases, const std::vector< basis::ElementBases > &phi_bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &psi_cache, const AssemblyValsCache &phi_cache, StiffnessMatrix &stiffness) const
void assemble_pressure_problem (const std::string &assembler, const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness) const
double assemble_energy (const std::string &assembler, const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const
void assemble_energy_gradient (const std::string &assembler, const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &grad) const
void assemble_energy_hessian (const std::string &assembler, const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::SparseMatrixCache &mat_cache, StiffnessMatrix &hessian) const
void compute_scalar_value (const std::string &assembler, const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
void compute_tensor_value (const std::string &assembler, const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const
VectorNd compute_rhs (const std::string &assembler, const AutodiffHessianPt &pt) const
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > local_assemble (const std::string &assembler, const ElementAssemblyValues &vals, const int i, const int j, const QuadratureVector &da) const
Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const std::string &assembler, const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params)
void add_multimaterial (const int index, const json &params)
void set_size (const std::string &assembler, const int dim)
void init_multimodels (const std::vector< std::string > &materials)
std::map< std::string, ParamFunc > parameters (const std::string &assembler) const
const Density & density () const
bool has_damping () const
Static Public Member Functions
static bool is_linear (const std::string &assembler)
static bool is_solution_displacement (const std::string &assembler)
static bool is_scalar (const std::string &assembler)
static bool is_tensor (const std::string &assembler)
static bool is_mixed (const std::string &assembler)
static bool is_fluid (const std::string &assembler)
static std::vector< std::string > scalar_assemblers ()
static std::vector< std::string > tensor_assemblers ()
static void merge_mixed_matrices (const int n_bases, const int n_pressure_bases, const int problem_dim, const bool add_average, const StiffnessMatrix &velocity_stiffness, const StiffnessMatrix &mixed_stiffness, const StiffnessMatrix &pressure_stiffness, StiffnessMatrix &stiffness)
static int quadrature_order (const std::string &assembler, const int basis_degree, const BasisType &b_type, const int dim)
Private Attributes
std::unique_ptr< Mass > mass_mat_
std::unique_ptr< Mass > mass_mat_no_density_
std::unique_ptr< Laplacian > laplacian_
std::unique_ptr< Helmholtz > helmholtz_
std::unique_ptr< BilaplacianMain > bilaplacian_main_
std::unique_ptr< BilaplacianMixed > bilaplacian_mixed_
std::unique_ptr< BilaplacianAux > bilaplacian_aux_
std::unique_ptr< LinearElasticity > linear_elasticity_
std::unique_ptr< HookeLinearElasticity > hooke_linear_elasticity_
std::unique_ptr< SaintVenantElasticity > saint_venant_elasticity_
std::unique_ptr< NeoHookeanElasticity > neo_hookean_elasticity_
std::unique_ptr< MooneyRivlinElasticity > mooney_rivlin_elasticity_
std::unique_ptr< MultiModel > multi_models_elasticity_
std::unique_ptr< UnconstrainedOgdenElasticity > unconstrained_ogden_elasticity_
std::unique_ptr< IncompressibleOgdenElasticity > incompressible_ogden_elasticity_
std::unique_ptr< ViscousDamping > damping_
std::unique_ptr< StokesVelocity > stokes_velocity_
std::unique_ptr< StokesMixed > stokes_mixed_
std::unique_ptr< StokesPressure > stokes_pressure_
std::unique_ptr< NavierStokesVelocity< false > > navier_stokes_velocity_picard_
std::unique_ptr< NavierStokesVelocity< true > > navier_stokes_velocity_
std::unique_ptr< IncompressibleLinearElasticityDispacement > incompressible_lin_elast_displacement_
std::unique_ptr< IncompressibleLinearElasticityMixed > incompressible_lin_elast_mixed_
std::unique_ptr< IncompressibleLinearElasticityPressure > incompressible_lin_elast_pressure_
Detailed Description
Definition at line 37 of file AssemblerUtils.hpp.
Member Typedef Documentation
NamedMatrix
typedef std::pair<std::string, Eigen::MatrixXd> polyfem::assembler::AssemblerUtils::NamedMatrix
Definition at line 40 of file AssemblerUtils.hpp.
ParamFunc
typedef std::function<double(const RowVectorNd &, const RowVectorNd &, double, int)> polyfem::assembler::AssemblerUtils::ParamFunc
Definition at line 50 of file AssemblerUtils.hpp.
Member Enumeration Documentation
BasisType
enum class polyfem::assembler::AssemblerUtils::BasisType strong
Enumerator
SIMPLEX_LAGRANGE
CUBE_LAGRANGE
SPLINE
POLY
Definition at line 42 of file AssemblerUtils.hpp.
Constructor & Destructor Documentation
AssemblerUtils()
polyfem::assembler::AssemblerUtils::AssemblerUtils ()
Definition at line 64 of file AssemblerUtils.cpp.
References bilaplacian_aux_, bilaplacian_main_, bilaplacian_mixed_, damping_, helmholtz_, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, incompressible_lin_elast_mixed_, incompressible_lin_elast_pressure_, incompressible_ogden_elasticity_, laplacian_, linear_elasticity_, mass_mat_, mass_mat_no_density_, mooney_rivlin_elasticity_, multi_models_elasticity_, navier_stokes_velocity_, navier_stokes_velocity_picard_, neo_hookean_elasticity_, saint_venant_elasticity_, stokes_mixed_, stokes_pressure_, stokes_velocity_, and unconstrained_ogden_elasticity_.
~AssemblerUtils()
polyfem::assembler::AssemblerUtils::~AssemblerUtils ()
Definition at line 100 of file AssemblerUtils.cpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::AssemblerUtils::add_multimaterial (const int index, const json & params)
Definition at line 722 of file AssemblerUtils.cpp.
References bilaplacian_aux_, bilaplacian_main_, bilaplacian_mixed_, damping_, helmholtz_, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, incompressible_lin_elast_mixed_, incompressible_lin_elast_pressure_, incompressible_ogden_elasticity_, laplacian_, linear_elasticity_, mass_mat_, mooney_rivlin_elasticity_, multi_models_elasticity_, navier_stokes_velocity_, navier_stokes_velocity_picard_, neo_hookean_elasticity_, saint_venant_elasticity_, stokes_mixed_, stokes_pressure_, stokes_velocity_, and unconstrained_ogden_elasticity_.
Referenced by set_materials().
assemble_energy()
double polyfem::assembler::AssemblerUtils::assemble_energy (const std::string & assembler, const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const
Definition at line 274 of file AssemblerUtils.cpp.
References cache, damping_, hooke_linear_elasticity_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_models_elasticity_, neo_hookean_elasticity_, saint_venant_elasticity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::solver::ElasticForm::value_unweighted().
assemble_energy_gradient()
void polyfem::assembler::AssemblerUtils::assemble_energy_gradient (const std::string & assembler, const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & grad) const
Definition at line 306 of file AssemblerUtils.cpp.
References cache, damping_, hooke_linear_elasticity_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_models_elasticity_, navier_stokes_velocity_, neo_hookean_elasticity_, saint_venant_elasticity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::solver::ElasticForm::first_derivative_unweighted().
assemble_energy_hessian()
void polyfem::assembler::AssemblerUtils::assemble_energy_hessian (const std::string & assembler, const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::SparseMatrixCache & mat_cache, StiffnessMatrix & hessian) const
Definition at line 341 of file AssemblerUtils.cpp.
References cache, damping_, hooke_linear_elasticity_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_models_elasticity_, navier_stokes_velocity_, navier_stokes_velocity_picard_, neo_hookean_elasticity_, saint_venant_elasticity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::solver::NavierStokesSolver::minimize_aux(), polyfem::solver::TransientNavierStokesSolver::minimize_aux(), and polyfem::solver::ElasticForm::second_derivative_unweighted().
assemble_mass_matrix()
void polyfem::assembler::AssemblerUtils::assemble_mass_matrix (const std::string & assembler, const bool is_volume, const int n_basis, const bool use_density, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, StiffnessMatrix & mass) const
Definition at line 206 of file AssemblerUtils.cpp.
References cache, mass_mat_, and mass_mat_no_density_.
Referenced by polyfem::State::assemble_stiffness_mat(), polyfem::State::solve_transient_navier_stokes(), polyfem::State::solve_transient_navier_stokes_split(), and polyfem::assembler::RhsAssembler::time_bc().
assemble_mixed_problem()
void polyfem::assembler::AssemblerUtils::assemble_mixed_problem (const std::string & assembler, const bool is_volume, const int n_psi_basis, const int n_phi_basis, const std::vector< basis::ElementBases > & psi_bases, const std::vector< basis::ElementBases > & phi_bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & psi_cache, const AssemblyValsCache & phi_cache, StiffnessMatrix & stiffness) const
Definition at line 222 of file AssemblerUtils.cpp.
References bilaplacian_mixed_, incompressible_lin_elast_mixed_, polyfem::logger(), and stokes_mixed_.
Referenced by polyfem::State::assemble_stiffness_mat(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::State::solve_transient_navier_stokes(), and polyfem::State::solve_transient_navier_stokes_split().
assemble_pressure_problem()
void polyfem::assembler::AssemblerUtils::assemble_pressure_problem (const std::string & assembler, const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, StiffnessMatrix & stiffness) const
Definition at line 250 of file AssemblerUtils.cpp.
References bilaplacian_aux_, cache, incompressible_lin_elast_pressure_, polyfem::logger(), and stokes_pressure_.
Referenced by polyfem::State::assemble_stiffness_mat(), polyfem::solver::NavierStokesSolver::minimize(), and polyfem::State::solve_transient_navier_stokes().
assemble_problem()
void polyfem::assembler::AssemblerUtils::assemble_problem (const std::string & assembler, const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, StiffnessMatrix & stiffness) const
Definition at line 160 of file AssemblerUtils.cpp.
References bilaplacian_main_, cache, helmholtz_, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, laplacian_, linear_elasticity_, polyfem::logger(), and stokes_velocity_.
Referenced by polyfem::State::assemble_stiffness_mat(), polyfem::solver::ElasticForm::compute_cached_stiffness(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::State::solve_transient_navier_stokes(), and polyfem::State::solve_transient_navier_stokes_split().
compute_rhs()
VectorNd polyfem::assembler::AssemblerUtils::compute_rhs (const std::string & assembler, const AutodiffHessianPt & pt) const
Definition at line 524 of file AssemblerUtils.cpp.
References bilaplacian_main_, helmholtz_, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, incompressible_ogden_elasticity_, laplacian_, linear_elasticity_, polyfem::logger(), mooney_rivlin_elasticity_, multi_models_elasticity_, navier_stokes_velocity_, neo_hookean_elasticity_, saint_venant_elasticity_, stokes_velocity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::problem::ElasticCantileverExact::rhs(), polyfem::problem::ProblemWithSolution::rhs(), and polyfem::basis::RBFWithQuadratic::setup_monomials_strong_2d().
compute_scalar_value()
void polyfem::assembler::AssemblerUtils::compute_scalar_value (const std::string & assembler, const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & fun, std::vector< NamedMatrix > & result) const
Definition at line 381 of file AssemblerUtils.cpp.
References hooke_linear_elasticity_, incompressible_lin_elast_displacement_, incompressible_ogden_elasticity_, linear_elasticity_, polyfem::logger(), mooney_rivlin_elasticity_, multi_models_elasticity_, neo_hookean_elasticity_, saint_venant_elasticity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::io::Evaluator::average_grad_based_function(), polyfem::io::Evaluator::check_scalar_value(), polyfem::io::Evaluator::compute_scalar_value(), polyfem::io::Evaluator::compute_stress_at_quadrature_points(), and polyfem::io::Evaluator::interpolate_boundary_tensor_function().
compute_tensor_value()
void polyfem::assembler::AssemblerUtils::compute_tensor_value (const std::string & assembler, const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & fun, std::vector< NamedMatrix > & result) const
Definition at line 429 of file AssemblerUtils.cpp.
References polyfem::CAUCHY, polyfem::F, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, incompressible_ogden_elasticity_, linear_elasticity_, polyfem::logger(), mooney_rivlin_elasticity_, multi_models_elasticity_, neo_hookean_elasticity_, polyfem::PK1, polyfem::PK2, saint_venant_elasticity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::io::Evaluator::compute_stress_at_quadrature_points(), polyfem::io::Evaluator::compute_tensor_value(), polyfem::io::Evaluator::interpolate_boundary_tensor_function(), and polyfem::io::OutGeometryData::save_surface().
density()
const Density & polyfem::assembler::AssemblerUtils::density () const
Definition at line 158 of file AssemblerUtils.cpp.
References mass_mat_.
Referenced by polyfem::State::assemble_rhs(), polyfem::solver::SolveData::init_forms(), polyfem::io::OutGeometryData::save_surface(), polyfem::io::OutGeometryData::save_volume(), polyfem::State::solve_transient_linear(), and polyfem::State::solve_transient_navier_stokes().
has_damping()
bool polyfem::assembler::AssemblerUtils::has_damping () const
Definition at line 153 of file AssemblerUtils.cpp.
References damping_.
Referenced by polyfem::solver::SolveData::init_forms().
init_multimodels()
void polyfem::assembler::AssemblerUtils::init_multimodels (const std::vector< std::string > & materials)
Definition at line 670 of file AssemblerUtils.cpp.
References multi_models_elasticity_.
Referenced by polyfem::State::build_basis().
is_fluid()
bool polyfem::assembler::AssemblerUtils::is_fluid (const std::string & assembler) static
Definition at line 129 of file AssemblerUtils.cpp.
Referenced by polyfem::State::assemble_rhs(), polyfem::State::assemble_stiffness_mat(), polyfem::State::sol_to_pressure(), polyfem::State::solve_linear(), and polyfem::State::solve_transient_linear().
is_linear()
bool polyfem::assembler::AssemblerUtils::is_linear (const std::string & assembler) static
Definition at line 148 of file AssemblerUtils.cpp.
Referenced by polyfem::State::assemble_stiffness_mat(), polyfem::solver::ElasticForm::compute_cached_stiffness(), polyfem::solver::ElasticForm::ElasticForm(), polyfem::State::init_nonlinear_tensor_solve(), polyfem::solver::ElasticForm::second_derivative_unweighted(), polyfem::State::solve_linear(), polyfem::State::solve_problem(), and polyfem::State::solve_transient_linear().
is_mixed()
bool polyfem::assembler::AssemblerUtils::is_mixed (const std::string & assembler) static
Definition at line 138 of file AssemblerUtils.cpp.
Referenced by polyfem::State::assemble_rhs(), polyfem::State::assemble_stiffness_mat(), polyfem::State::build_basis(), polyfem::State::init_nonlinear_tensor_solve(), polyfem::State::init_solve(), polyfem::io::OutGeometryData::save_surface(), polyfem::io::OutGeometryData::save_volume(), polyfem::State::sol_to_pressure(), polyfem::State::solve_linear(), and polyfem::State::solve_transient_linear().
is_scalar()
bool polyfem::assembler::AssemblerUtils::is_scalar (const std::string & assembler) static
Definition at line 124 of file AssemblerUtils.cpp.
Referenced by polyfem::State::init(), and polyfem::problem::KernelProblem::is_scalar().
is_solution_displacement()
bool polyfem::assembler::AssemblerUtils::is_solution_displacement (const std::string & assembler) static
Definition at line 143 of file AssemblerUtils.cpp.
is_tensor()
bool polyfem::assembler::AssemblerUtils::is_tensor (const std::string & assembler) static
Definition at line 134 of file AssemblerUtils.cpp.
Referenced by polyfem::basis::PolygonalBasis2d::build_bases(), polyfem::basis::BarycentricBasis2d::build_bases(), polyfem::basis::RBFWithQuadratic::compute_constraints_matrix_2d(), polyfem::basis::RBFWithQuadraticLagrange::compute_constraints_matrix_2d(), and polyfem::basis::PolygonalBasis2d::compute_integral_constraints().
kernel()
Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::AssemblerUtils::kernel (const std::string & assembler, const int dim, const AutodiffGradPt & rvect, const AutodiffScalarGrad & r) const
Definition at line 607 of file AssemblerUtils.cpp.
References helmholtz_, laplacian_, linear_elasticity_, and polyfem::logger().
Referenced by polyfem::problem::KernelProblem::eval_fun().
local_assemble()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 9, 1 > polyfem::assembler::AssemblerUtils::local_assemble (const std::string & assembler, const ElementAssemblyValues & vals, const int i, const int j, const QuadratureVector & da) const
Definition at line 568 of file AssemblerUtils.cpp.
References bilaplacian_main_, da, helmholtz_, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, laplacian_, linear_elasticity_, polyfem::logger(), stokes_velocity_, and vals.
Referenced by polyfem::basis::RBFWithQuadratic::compute_constraints_matrix_2d(), polyfem::basis::RBFWithQuadraticLagrange::compute_constraints_matrix_2d(), and polyfem::basis::PolygonalBasis2d::compute_integral_constraints().
merge_mixed_matrices()
void polyfem::assembler::AssemblerUtils::merge_mixed_matrices (const int n_bases, const int n_pressure_bases, const int problem_dim, const bool add_average, const StiffnessMatrix & velocity_stiffness, const StiffnessMatrix & mixed_stiffness, const StiffnessMatrix & pressure_stiffness, StiffnessMatrix & stiffness) static
Definition at line 757 of file AssemblerUtils.cpp.
References val.
Referenced by polyfem::State::assemble_stiffness_mat(), polyfem::solver::TransientNavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize(), polyfem::solver::NavierStokesSolver::minimize_aux(), and polyfem::solver::TransientNavierStokesSolver::minimize_aux().
parameters()
std::map< std::string, AssemblerUtils::ParamFunc > polyfem::assembler::AssemblerUtils::parameters (const std::string & assembler) const
Definition at line 851 of file AssemblerUtils.cpp.
References helmholtz_, hooke_linear_elasticity_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, stokes_velocity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::io::OutGeometryData::save_surface(), and polyfem::io::OutGeometryData::save_volume().
quadrature_order()
int polyfem::assembler::AssemblerUtils::quadrature_order (const std::string & assembler, const int basis_degree, const BasisType & b_type, const int dim) static
Definition at line 822 of file AssemblerUtils.cpp.
References CUBE_LAGRANGE, and SIMPLEX_LAGRANGE.
Referenced by polyfem::basis::PolygonalBasis2d::build_bases(), polyfem::basis::PolygonalBasis3d::build_bases(), polyfem::basis::SplineBasis2d::build_bases(), polyfem::basis::SplineBasis3d::build_bases(), polyfem::basis::BarycentricBasis2d::build_bases(), and polyfem::State::n_boundary_samples().
scalar_assemblers()
std::vector< std::string > polyfem::assembler::AssemblerUtils::scalar_assemblers () static
Definition at line 102 of file AssemblerUtils.cpp.
set_materials()
void polyfem::assembler::AssemblerUtils::set_materials (const std::vector< int > & body_ids, const json & body_params)
Definition at line 675 of file AssemblerUtils.cpp.
References add_multimaterial(), and polyfem::logger().
Referenced by polyfem::State::set_materials().
set_size()
void polyfem::assembler::AssemblerUtils::set_size (const std::string & assembler, const int dim)
Definition at line 638 of file AssemblerUtils.cpp.
References damping_, hooke_linear_elasticity_, incompressible_lin_elast_displacement_, incompressible_lin_elast_mixed_, incompressible_lin_elast_pressure_, incompressible_ogden_elasticity_, linear_elasticity_, mass_mat_, mass_mat_no_density_, mooney_rivlin_elasticity_, multi_models_elasticity_, navier_stokes_velocity_, navier_stokes_velocity_picard_, neo_hookean_elasticity_, saint_venant_elasticity_, stokes_mixed_, stokes_velocity_, and unconstrained_ogden_elasticity_.
Referenced by polyfem::State::load_mesh().
tensor_assemblers()
std::vector< std::string > polyfem::assembler::AssemblerUtils::tensor_assemblers () static
Definition at line 113 of file AssemblerUtils.cpp.
Member Data Documentation
bilaplacian_aux_
std::unique_ptr<BilaplacianAux> polyfem::assembler::AssemblerUtils::bilaplacian_aux_ private
Definition at line 213 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_pressure_problem(), and AssemblerUtils().
bilaplacian_main_
std::unique_ptr<BilaplacianMain> polyfem::assembler::AssemblerUtils::bilaplacian_main_ private
Definition at line 211 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_problem(), AssemblerUtils(), compute_rhs(), and local_assemble().
bilaplacian_mixed_
std::unique_ptr<BilaplacianMixed> polyfem::assembler::AssemblerUtils::bilaplacian_mixed_ private
Definition at line 212 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_mixed_problem(), and AssemblerUtils().
damping_
std::unique_ptr<ViscousDamping> polyfem::assembler::AssemblerUtils::damping_ private
Definition at line 225 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), has_damping(), and set_size().
helmholtz_
std::unique_ptr<Helmholtz> polyfem::assembler::AssemblerUtils::helmholtz_ private
Definition at line 209 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_problem(), AssemblerUtils(), compute_rhs(), kernel(), local_assemble(), and parameters().
hooke_linear_elasticity_
std::unique_ptr<HookeLinearElasticity> polyfem::assembler::AssemblerUtils::hooke_linear_elasticity_ private
Definition at line 216 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), assemble_problem(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), local_assemble(), parameters(), and set_size().
incompressible_lin_elast_displacement_
std::unique_ptr<IncompressibleLinearElasticityDispacement> polyfem::assembler::AssemblerUtils::incompressible_lin_elast_displacement_ private
Definition at line 234 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_problem(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), local_assemble(), and set_size().
incompressible_lin_elast_mixed_
std::unique_ptr<IncompressibleLinearElasticityMixed> polyfem::assembler::AssemblerUtils::incompressible_lin_elast_mixed_ private
Definition at line 235 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_mixed_problem(), AssemblerUtils(), and set_size().
incompressible_lin_elast_pressure_
std::unique_ptr<IncompressibleLinearElasticityPressure> polyfem::assembler::AssemblerUtils::incompressible_lin_elast_pressure_ private
Definition at line 236 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_pressure_problem(), AssemblerUtils(), and set_size().
incompressible_ogden_elasticity_
std::unique_ptr<IncompressibleOgdenElasticity> polyfem::assembler::AssemblerUtils::incompressible_ogden_elasticity_ private
Definition at line 223 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), parameters(), and set_size().
laplacian_
std::unique_ptr<Laplacian> polyfem::assembler::AssemblerUtils::laplacian_ private
Definition at line 208 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_problem(), AssemblerUtils(), compute_rhs(), kernel(), and local_assemble().
linear_elasticity_
std::unique_ptr<LinearElasticity> polyfem::assembler::AssemblerUtils::linear_elasticity_ private
Definition at line 215 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), assemble_problem(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), kernel(), local_assemble(), parameters(), and set_size().
mass_mat_
std::unique_ptr<Mass> polyfem::assembler::AssemblerUtils::mass_mat_ private
Definition at line 205 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_mass_matrix(), AssemblerUtils(), density(), and set_size().
mass_mat_no_density_
std::unique_ptr<Mass> polyfem::assembler::AssemblerUtils::mass_mat_no_density_ private
Definition at line 206 of file AssemblerUtils.hpp.
Referenced by assemble_mass_matrix(), AssemblerUtils(), and set_size().
mooney_rivlin_elasticity_
std::unique_ptr<MooneyRivlinElasticity> polyfem::assembler::AssemblerUtils::mooney_rivlin_elasticity_ private
Definition at line 220 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), parameters(), and set_size().
multi_models_elasticity_
std::unique_ptr<MultiModel> polyfem::assembler::AssemblerUtils::multi_models_elasticity_ private
Definition at line 221 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), init_multimodels(), and set_size().
navier_stokes_velocity_
std::unique_ptr<NavierStokesVelocity<true> > polyfem::assembler::AssemblerUtils::navier_stokes_velocity_ private
Definition at line 232 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), and set_size().
navier_stokes_velocity_picard_
std::unique_ptr<NavierStokesVelocity<false> > polyfem::assembler::AssemblerUtils::navier_stokes_velocity_picard_ private
Definition at line 231 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy_hessian(), AssemblerUtils(), and set_size().
neo_hookean_elasticity_
std::unique_ptr<NeoHookeanElasticity> polyfem::assembler::AssemblerUtils::neo_hookean_elasticity_ private
Definition at line 219 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), and set_size().
saint_venant_elasticity_
std::unique_ptr<SaintVenantElasticity> polyfem::assembler::AssemblerUtils::saint_venant_elasticity_ private
Definition at line 218 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), and set_size().
stokes_mixed_
std::unique_ptr<StokesMixed> polyfem::assembler::AssemblerUtils::stokes_mixed_ private
Definition at line 228 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_mixed_problem(), AssemblerUtils(), and set_size().
stokes_pressure_
std::unique_ptr<StokesPressure> polyfem::assembler::AssemblerUtils::stokes_pressure_ private
Definition at line 229 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_pressure_problem(), and AssemblerUtils().
stokes_velocity_
std::unique_ptr<StokesVelocity> polyfem::assembler::AssemblerUtils::stokes_velocity_ private
Definition at line 227 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_problem(), AssemblerUtils(), compute_rhs(), local_assemble(), parameters(), and set_size().
unconstrained_ogden_elasticity_
std::unique_ptr<UnconstrainedOgdenElasticity> polyfem::assembler::AssemblerUtils::unconstrained_ogden_elasticity_ private
Definition at line 222 of file AssemblerUtils.hpp.
Referenced by add_multimaterial(), assemble_energy(), assemble_energy_gradient(), assemble_energy_hessian(), AssemblerUtils(), compute_rhs(), compute_scalar_value(), compute_tensor_value(), parameters(), and set_size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/AssemblerUtils.hpp
src/polyfem/assembler/AssemblerUtils.cpp