PolyFEM: polyfem::basis::QuadraticBSpline2d Class Reference
polyfem::basis::QuadraticBSpline2d Class Reference
#include <QuadraticBSpline2d.hpp>
Public Member Functions
QuadraticBSpline2d ()
QuadraticBSpline2d (const std::array< double, 4 > &knots_u, const std::array< double, 4 > &knots_v)
void init (const std::array< double, 4 > &knots_u, const std::array< double, 4 > &knots_v)
void interpolate (const Eigen::MatrixXd &ts, Eigen::MatrixXd &result) const
double interpolate (const double u, const double v) const
void derivative (const Eigen::MatrixXd &ts, Eigen::MatrixXd &result) const
Private Attributes
QuadraticBSpline spline_u_
QuadraticBSpline spline_v_
Detailed Description
Definition at line 14 of file QuadraticBSpline2d.hpp.
Constructor & Destructor Documentation
QuadraticBSpline2d() [1/2]
polyfem::basis::QuadraticBSpline2d::QuadraticBSpline2d () inline
Definition at line 17 of file QuadraticBSpline2d.hpp.
QuadraticBSpline2d() [2/2]
polyfem::basis::QuadraticBSpline2d::QuadraticBSpline2d (const std::array< double, 4 > & knots_u, const std::array< double, 4 > & knots_v) inline
Definition at line 21 of file QuadraticBSpline2d.hpp.
Member Function Documentation
derivative()
void polyfem::basis::QuadraticBSpline2d::derivative (const Eigen::MatrixXd & ts, Eigen::MatrixXd & result) const
Definition at line 29 of file QuadraticBSpline2d.cpp.
References polyfem::basis::QuadraticBSpline::derivative(), polyfem::basis::QuadraticBSpline::interpolate(), spline_u_, and spline_v_.
init()
void polyfem::basis::QuadraticBSpline2d::init (const std::array< double, 4 > & knots_u, const std::array< double, 4 > & knots_v)
Definition at line 7 of file QuadraticBSpline2d.cpp.
References polyfem::basis::QuadraticBSpline::init(), spline_u_, and spline_v_.
interpolate() [1/2]
double polyfem::basis::QuadraticBSpline2d::interpolate (const double u, const double v) const
Definition at line 24 of file QuadraticBSpline2d.cpp.
References polyfem::basis::QuadraticBSpline::interpolate(), spline_u_, and spline_v_.
interpolate() [2/2]
void polyfem::basis::QuadraticBSpline2d::interpolate (const Eigen::MatrixXd & ts, Eigen::MatrixXd & result) const
Definition at line 13 of file QuadraticBSpline2d.cpp.
References interpolate().
Referenced by interpolate().
Member Data Documentation
spline_u_
QuadraticBSpline polyfem::basis::QuadraticBSpline2d::spline_u_ private
Definition at line 34 of file QuadraticBSpline2d.hpp.
Referenced by derivative(), init(), and interpolate().
spline_v_
QuadraticBSpline polyfem::basis::QuadraticBSpline2d::spline_v_ private
Definition at line 35 of file QuadraticBSpline2d.hpp.
Referenced by derivative(), init(), and interpolate().
The documentation for this class was generated from the following files:
src/polyfem/basis/function/QuadraticBSpline2d.hpp
src/polyfem/basis/function/QuadraticBSpline2d.cpp