PolyFEM: polyfem::solver::PeriodicContactForm Class Reference
polyfem::solver::PeriodicContactForm Class Reference
Form representing the contact potential and forces on a periodic mesh This form has a different input format of [fluctuation, affine], only can be used in NLHomoProblem.
#include <PeriodicContactForm.hpp>
Public Member Functions
PeriodicContactForm (const ipc::CollisionMesh &periodic_collision_mesh, const Eigen::VectorXi &tiled_to_single, const double dhat, const double avg_mass, const bool use_area_weighting, const bool use_improved_max_operator, const bool use_physical_barrier, const bool use_adaptive_barrier_stiffness, const bool is_time_dependent, const bool enable_shape_derivatives, const ipc::BroadPhaseMethod broad_phase_method, const double ccd_tolerance, const int ccd_max_iterations)
Construct a new Contact Form object.
void init (const Eigen::VectorXd &x) override
Initialize the form.
void force_periodic_shape_derivative (const State &state, const PeriodicMeshToMesh &periodic_mesh_map, const Eigen::VectorXd &periodic_mesh_representation, const ipc::NormalCollisions &contact_set, const Eigen::VectorXd &solution, const Eigen::VectorXd &adjoint_sol, Eigen::VectorXd &term)
Eigen::VectorXd single_to_tiled (const Eigen::VectorXd &x) const
Eigen::VectorXd tiled_to_single_grad (const Eigen::VectorXd &grad) const
void update_quantities (const double t, const Eigen::VectorXd &x) override
Update time-dependent fields.
double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Determine the maximum step size allowable between the current and next solution.
void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) override
Initialize variables used during the line search.
void solution_changed (const Eigen::VectorXd &new_x) override
Update cached fields upon a change in the solution.
void post_step (const polysolve::nonlinear::PostStepData &data) override
Update fields after a step in the optimization.
bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const override
Checks if the step is collision free.
void update_barrier_stiffness (const Eigen::VectorXd &x, const Eigen::MatrixXd &grad_energy) override
Update the barrier stiffness based on the current elasticity energy.
Public Member Functions inherited from polyfem::solver::ContactForm
ContactForm (const ipc::CollisionMesh &collision_mesh, const double dhat, const double avg_mass, const bool use_area_weighting, const bool use_improved_max_operator, const bool use_physical_barrier, const bool use_adaptive_barrier_stiffness, const bool is_time_dependent, const bool enable_shape_derivatives, const ipc::BroadPhaseMethod broad_phase_method, const double ccd_tolerance, const int ccd_max_iterations)
Construct a new Contact Form object.
virtual ~ContactForm ()=default
std::string name () const override
virtual void force_shape_derivative (const ipc::NormalCollisions &collision_set, const Eigen::MatrixXd &solution, const Eigen::VectorXd &adjoint_sol, Eigen::VectorXd &term)
void line_search_end () override
Clear variables used during the line search.
Eigen::MatrixXd compute_displaced_surface (const Eigen::VectorXd &x) const
Compute the displaced positions of the surface nodes.
double barrier_stiffness () const
Get the current barrier stiffness.
void set_barrier_stiffness (const double barrier_stiffness)
Get the current barrier stiffness.
bool use_adaptive_barrier_stiffness () const
Get use_adaptive_barrier_stiffness.
bool use_convergent_formulation () const
Get use_convergent_formulation.
bool use_area_weighting () const
Get use_area_weighting.
bool use_improved_max_operator () const
Get use_improved_max_operator.
bool use_physical_barrier () const
Get use_physical_barrier.
bool enable_shape_derivatives () const
double weight () const override
Get the form's multiplicative constant weight.
double dhat () const
const ipc::NormalCollisions & collision_set () const
const ipc::BarrierPotential & barrier_potential () const
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void finish ()
virtual double value (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num)
Update lagged fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the contact barrier potential value.
void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::ContactForm
Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form multiplied per element.
void update_collision_set (const Eigen::MatrixXd &displaced_surface)
Update the cached candidate set for the current solution.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
Private Member Functions
void update_projection () const
Private Attributes
const Eigen::VectorXi tiled_to_single_
const int n_single_dof_
StiffnessMatrix proj
Additional Inherited Members
Public Attributes inherited from polyfem::solver::ContactForm
bool save_ccd_debug_meshes = false
If true, output debug files.
Protected Attributes inherited from polyfem::solver::ContactForm
const ipc::CollisionMesh & collision_mesh_
Collision mesh.
const double dhat_
Barrier activation distance.
const double dmin_ = 0
Minimum distance between elements.
const bool use_adaptive_barrier_stiffness_
If true, use an adaptive barrier stiffness.
double barrier_stiffness_
Barrier stiffness.
double max_barrier_stiffness_
Maximum barrier stiffness to use when using adaptive barrier stiffness.
const double avg_mass_
Average mass of the mesh (used for adaptive barrier stiffness)
const bool is_time_dependent_
Is the simulation time dependent?
const bool enable_shape_derivatives_
Enable shape derivatives computation.
const ipc::BroadPhaseMethod broad_phase_method_
Broad phase method to use for distance and CCD evaluations.
const ipc::TightInclusionCCD tight_inclusion_ccd_
Continuous collision detection specification object.
double prev_distance_
Previous minimum distance between all elements.
bool use_cached_candidates_ = false
If true, use the cached candidate set for the current solution.
ipc::NormalCollisions collision_set_
Cached constraint set for the current solution.
ipc::Candidates candidates_
Cached candidate set for the current solution.
const ipc::BarrierPotential barrier_potential_
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or t)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Form representing the contact potential and forces on a periodic mesh This form has a different input format of [fluctuation, affine], only can be used in NLHomoProblem.
Definition at line 18 of file PeriodicContactForm.hpp.
Constructor & Destructor Documentation
PeriodicContactForm()
polyfem::solver::PeriodicContactForm::PeriodicContactForm (const ipc::CollisionMesh & periodic_collision_mesh, const Eigen::VectorXi & tiled_to_single, const double dhat, const double avg_mass, const bool use_area_weighting, const bool use_improved_max_operator, const bool use_physical_barrier, const bool use_adaptive_barrier_stiffness, const bool is_time_dependent, const bool enable_shape_derivatives, const ipc::BroadPhaseMethod broad_phase_method, const double ccd_tolerance, const int ccd_max_iterations)
Construct a new Contact Form object.
Parameters
periodic_collision_mesh 3x3 tiling of a periodic mesh
tiled_to_single Index mapping from the tiled mesh to the original periodic mesh
Definition at line 12 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::collision_mesh_, tiled_to_single_, and update_projection().
Member Function Documentation
first_derivative_unweighted()
void polyfem::solver::PeriodicContactForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override protected virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Reimplemented from polyfem::solver::ContactForm.
Definition at line 113 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::first_derivative_unweighted(), single_to_tiled(), tiled_to_single_grad(), and x.
force_periodic_shape_derivative()
void polyfem::solver::PeriodicContactForm::force_periodic_shape_derivative (const State & state, const PeriodicMeshToMesh & periodic_mesh_map, const Eigen::VectorXd & periodic_mesh_representation, const ipc::NormalCollisions & contact_set, const Eigen::VectorXd & solution, const Eigen::VectorXd & adjoint_sol, Eigen::VectorXd & term)
Definition at line 171 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::barrier_potential_, polyfem::State::basis_nodes_to_gbasis_nodes, polyfem::solver::ContactForm::collision_mesh_, polyfem::solver::ContactForm::compute_displaced_surface(), polyfem::utils::flatten(), polyfem::solver::PeriodicMeshToMesh::full_to_periodic(), polyfem::State::n_geom_bases, n_single_dof_, polyfem::State::primitive_to_node(), proj, polyfem::solver::ContactForm::second_derivative_unweighted(), single_to_tiled(), polyfem::utils::unflatten(), and polyfem::solver::ContactForm::weight().
init()
void polyfem::solver::PeriodicContactForm::init (const Eigen::VectorXd & x) override virtual
Initialize the form.
Parameters
x Current solution
Reimplemented from polyfem::solver::ContactForm.
Definition at line 103 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::init(), single_to_tiled(), and x.
is_step_collision_free()
bool polyfem::solver::PeriodicContactForm::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented from polyfem::solver::ContactForm.
Definition at line 161 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::is_step_collision_free(), and single_to_tiled().
line_search_begin()
void polyfem::solver::PeriodicContactForm::line_search_begin (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) override virtual
Initialize variables used during the line search.
Parameters
x0 Current solution
x1 Next solution
Reimplemented from polyfem::solver::ContactForm.
Definition at line 144 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::line_search_begin(), and single_to_tiled().
max_step_size()
double polyfem::solver::PeriodicContactForm::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const override virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented from polyfem::solver::ContactForm.
Definition at line 139 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::max_step_size(), and single_to_tiled().
post_step()
void polyfem::solver::PeriodicContactForm::post_step (const polysolve::nonlinear::PostStepData & data) override virtual
Update fields after a step in the optimization.
Parameters
iter_num Optimization iteration number
x Current solution
Reimplemented from polyfem::solver::ContactForm.
Definition at line 154 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::post_step(), and single_to_tiled().
second_derivative_unweighted()
void polyfem::solver::PeriodicContactForm::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const override protected virtual
Compute the second derivative of the value wrt x.
Parameters
x Current solution
hessian Output Hessian of the value wrt x
Reimplemented from polyfem::solver::ContactForm.
Definition at line 119 of file PeriodicContactForm.cpp.
References proj, polyfem::solver::ContactForm::second_derivative_unweighted(), single_to_tiled(), update_projection(), and x.
single_to_tiled()
Eigen::VectorXd polyfem::solver::PeriodicContactForm::single_to_tiled (const Eigen::VectorXd & x) const
Definition at line 60 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::collision_mesh_, n_single_dof_, tiled_to_single_, and x.
Referenced by first_derivative_unweighted(), force_periodic_shape_derivative(), init(), is_step_collision_free(), line_search_begin(), max_step_size(), post_step(), second_derivative_unweighted(), solution_changed(), update_barrier_stiffness(), update_quantities(), and value_unweighted().
solution_changed()
void polyfem::solver::PeriodicContactForm::solution_changed (const Eigen::VectorXd & new_x) override virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented from polyfem::solver::ContactForm.
Definition at line 149 of file PeriodicContactForm.cpp.
References single_to_tiled(), and polyfem::solver::ContactForm::solution_changed().
tiled_to_single_grad()
Eigen::VectorXd polyfem::solver::PeriodicContactForm::tiled_to_single_grad (const Eigen::VectorXd & grad) const
Definition at line 81 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::collision_mesh_, n_single_dof_, and tiled_to_single_.
Referenced by first_derivative_unweighted().
update_barrier_stiffness()
void polyfem::solver::PeriodicContactForm::update_barrier_stiffness (const Eigen::VectorXd & x, const Eigen::MatrixXd & grad_energy) override virtual
Update the barrier stiffness based on the current elasticity energy.
Parameters
x Current solution
Reimplemented from polyfem::solver::ContactForm.
Definition at line 166 of file PeriodicContactForm.cpp.
References single_to_tiled(), polyfem::solver::ContactForm::update_barrier_stiffness(), and x.
update_projection()
void polyfem::solver::PeriodicContactForm::update_projection () const private
Definition at line 38 of file PeriodicContactForm.cpp.
References polyfem::solver::ContactForm::collision_mesh_, entries, n_single_dof_, proj, and tiled_to_single_.
Referenced by PeriodicContactForm(), and second_derivative_unweighted().
update_quantities()
void polyfem::solver::PeriodicContactForm::update_quantities (const double t, const Eigen::VectorXd & x) override virtual
Update time-dependent fields.
Parameters
t Current time
x Current solution at time t
Reimplemented from polyfem::solver::ContactForm.
Definition at line 134 of file PeriodicContactForm.cpp.
References single_to_tiled(), polyfem::solver::ContactForm::update_quantities(), and x.
value_unweighted()
double polyfem::solver::PeriodicContactForm::value_unweighted (const Eigen::VectorXd & x) const override protected virtual
Compute the contact barrier potential value.
Parameters
x Current solution
Returns
Value of the contact barrier potential
Reimplemented from polyfem::solver::ContactForm.
Definition at line 108 of file PeriodicContactForm.cpp.
References single_to_tiled(), polyfem::solver::ContactForm::value_unweighted(), and x.
Member Data Documentation
n_single_dof_
const int polyfem::solver::PeriodicContactForm::n_single_dof_ private
Definition at line 99 of file PeriodicContactForm.hpp.
Referenced by force_periodic_shape_derivative(), single_to_tiled(), tiled_to_single_grad(), and update_projection().
proj
StiffnessMatrix polyfem::solver::PeriodicContactForm::proj mutable private
Definition at line 100 of file PeriodicContactForm.hpp.
Referenced by force_periodic_shape_derivative(), second_derivative_unweighted(), and update_projection().
tiled_to_single_
const Eigen::VectorXi polyfem::solver::PeriodicContactForm::tiled_to_single_ private
Definition at line 98 of file PeriodicContactForm.hpp.
Referenced by PeriodicContactForm(), single_to_tiled(), tiled_to_single_grad(), and update_projection().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/PeriodicContactForm.hpp
src/polyfem/solver/forms/PeriodicContactForm.cpp