PolyFEM: polyfem::assembler::MultiModel Class Reference
polyfem::assembler::MultiModel Class Reference
#include <MultiModel.hpp>
Public Member Functions
double compute_energy (const NonLinearAssemblerData &data) const override
Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const override
Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const override
VectorNd compute_rhs (const AutodiffHessianPt &pt) const override
void set_size (const int size) override
void add_multimaterial (const int index, const json &params, const Units &units) override
void init_multimodels (const std::vector< std::string > &mats)
std::string name () const override
std::map< std::string, ParamFunc > parameters () const override
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
virtual Eigen::VectorXd assemble_gradient (const NonLinearAssemblerData &data) const=0
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::MatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual Eigen::MatrixXd assemble_hessian (const NonLinearAssemblerData &data) const=0
Public Member Functions inherited from polyfem::assembler::NLAssembler
virtual ~NLAssembler ()=default
double assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
Eigen::VectorXd assemble_energy_per_element (const bool is_volume, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev) const override
void assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, Eigen::MatrixXd &rhs) const override
void assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, const double dt, const Eigen::MatrixXd &displacement, const Eigen::MatrixXd &displacement_prev, utils::MatrixCache &mat_cache, StiffnessMatrix &grad) const override
virtual bool is_linear () const override
Public Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params, const Units &units)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_fluid () const
Protected Member Functions
void assign_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const int all_size, const ElasticityTensorType &type, Eigen::MatrixXd &all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> &fun) const override
Private Attributes
std::vector< std::string > multi_material_models_
SaintVenantElasticity saint_venant_
NeoHookeanElasticity neo_hookean_
LinearElasticity linear_elasticity_
HookeLinearElasticity hooke_
MooneyRivlinElasticity mooney_rivlin_elasticity_
MooneyRivlin3ParamElasticity mooney_rivlin_3_param_elasticity_
UnconstrainedOgdenElasticity unconstrained_ogden_elasticity_
IncompressibleOgdenElasticity incompressible_ogden_elasticity_
Private Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Additional Inherited Members
Public Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Protected Attributes inherited from polyfem::assembler::Assembler
int size_ = -1
Private Types inherited from polyfem::assembler::Assembler
typedef std::pair< std::string, Eigen::MatrixXd > NamedMatrix
typedef std::function< double(const RowVectorNd &, const RowVectorNd &, double, int)> ParamFunc
Private Member Functions inherited from polyfem::assembler::ElasticityAssembler
ElasticityAssembler ()
virtual ~ElasticityAssembler ()=default
void compute_scalar_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_tensor_value (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &fun, std::vector< NamedMatrix > &result) const override
void compute_stress_tensor (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, const ElasticityTensorType &type, Eigen::MatrixXd &stresses) const
void compute_von_mises_stresses (const int el_id, const basis::ElementBases &bs, const basis::ElementBases &gbs, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &stresses) const
bool is_solution_displacement () const override
bool is_tensor () const override
Private Member Functions inherited from polyfem::assembler::Assembler
virtual ~Assembler ()=default
int size () const
virtual void assemble (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > &bases, const std::vector< basis::ElementBases > &gbases, const AssemblyValsCache &cache, StiffnessMatrix &stiffness, const bool is_mass=false) const
virtual void compute_stiffness_value (const assembler::ElementAssemblyValues &vals, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &displacement, Eigen::MatrixXd &tensor) const
virtual void compute_dstress_dmu_dlambda (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &dstress_dmu, Eigen::MatrixXd &dstress_dlambda) const
virtual void compute_stress_grad_multiply_mat (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &mat, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_stress (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad_multiply_vect (const int el_id, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &vect, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &stress, Eigen::MatrixXd &result) const
virtual void compute_stress_prev_grad (const int el_id, const double dt, const Eigen::MatrixXd &local_pts, const Eigen::MatrixXd &global_pts, const Eigen::MatrixXd &grad_u_i, const Eigen::MatrixXd &prev_grad_u_i, Eigen::MatrixXd &result) const
virtual Eigen::Matrix< AutodiffScalarGrad, Eigen::Dynamic, 1, 0, 3, 1 > kernel (const int dim, const AutodiffGradPt &rvect, const AutodiffScalarGrad &r) const
void set_materials (const std::vector< int > &body_ids, const json &body_params, const Units &units)
virtual void update_lame_params (const Eigen::MatrixXd &lambdas, const Eigen::MatrixXd &mus)
virtual bool is_fluid () const
Detailed Description
Definition at line 14 of file MultiModel.hpp.
Member Function Documentation
add_multimaterial()
void polyfem::assembler::MultiModel::add_multimaterial (const int index, const json & params, const Units & units) override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 24 of file MultiModel.cpp.
References polyfem::assembler::HookeLinearElasticity::add_multimaterial(), polyfem::assembler::LinearElasticity::add_multimaterial(), polyfem::assembler::MooneyRivlinElasticity::add_multimaterial(), polyfem::assembler::NeoHookeanElasticity::add_multimaterial(), polyfem::assembler::UnconstrainedOgdenElasticity::add_multimaterial(), polyfem::assembler::IncompressibleOgdenElasticity::add_multimaterial(), polyfem::assembler::SaintVenantElasticity::add_multimaterial(), hooke_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, neo_hookean_, saint_venant_, polyfem::assembler::Assembler::size(), and unconstrained_ogden_elasticity_.
assemble_energy()
double polyfem::assembler::NLAssembler::assemble_energy (const bool is_volume, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 253 of file Assembler.cpp.
assemble_gradient() [1/3]
void polyfem::assembler::NLAssembler::assemble_gradient (const bool is_volume, const int n_basis, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, Eigen::MatrixXd & rhs) const override virtual
Reimplemented from polyfem::assembler::Assembler.
assemble_gradient() [2/3]
Eigen::VectorXd polyfem::assembler::MultiModel::assemble_gradient (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 49 of file MultiModel.cpp.
References polyfem::assembler::GenericElastic< Derived >::assemble_gradient(), polyfem::assembler::HookeLinearElasticity::assemble_gradient(), polyfem::assembler::LinearElasticity::assemble_gradient(), polyfem::assembler::NeoHookeanElasticity::assemble_gradient(), polyfem::assembler::SaintVenantElasticity::assemble_gradient(), polyfem::assembler::ElementAssemblyValues::element_id, hooke_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_material_models_, neo_hookean_, saint_venant_, unconstrained_ogden_elasticity_, and polyfem::assembler::NonLinearAssemblerData::vals.
assemble_gradient() [3/3]
virtual Eigen::VectorXd polyfem::assembler::NLAssembler::assemble_gradient (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assemble_hessian() [1/3]
void polyfem::assembler::NLAssembler::assemble_hessian (const bool is_volume, const int n_basis, const bool project_to_psd, const std::vector< basis::ElementBases > & bases, const std::vector< basis::ElementBases > & gbases, const AssemblyValsCache & cache, const double dt, const Eigen::MatrixXd & displacement, const Eigen::MatrixXd & displacement_prev, utils::MatrixCache & mat_cache, StiffnessMatrix & grad) const override virtual
Reimplemented from polyfem::assembler::Assembler.
assemble_hessian() [2/3]
Eigen::MatrixXd polyfem::assembler::MultiModel::assemble_hessian (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 76 of file MultiModel.cpp.
References polyfem::assembler::GenericElastic< Derived >::assemble_hessian(), polyfem::assembler::HookeLinearElasticity::assemble_hessian(), polyfem::assembler::LinearElasticity::assemble_hessian(), polyfem::assembler::NeoHookeanElasticity::assemble_hessian(), polyfem::assembler::SaintVenantElasticity::assemble_hessian(), polyfem::assembler::ElementAssemblyValues::element_id, hooke_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_material_models_, neo_hookean_, saint_venant_, unconstrained_ogden_elasticity_, and polyfem::assembler::NonLinearAssemblerData::vals.
assemble_hessian() [3/3]
virtual Eigen::MatrixXd polyfem::assembler::NLAssembler::assemble_hessian (const NonLinearAssemblerData & data) const virtual
Implements polyfem::assembler::NLAssembler.
assign_stress_tensor()
void polyfem::assembler::MultiModel::assign_stress_tensor (const int el_id, const basis::ElementBases & bs, const basis::ElementBases & gbs, const Eigen::MatrixXd & local_pts, const Eigen::MatrixXd & displacement, const int all_size, const ElasticityTensorType & type, Eigen::MatrixXd & all, const std::function< Eigen::MatrixXd(const Eigen::MatrixXd &)> & fun) const override protected virtual
Implements polyfem::assembler::ElasticityAssembler.
Definition at line 128 of file MultiModel.cpp.
References polyfem::assembler::GenericElastic< Derived >::assign_stress_tensor(), polyfem::assembler::HookeLinearElasticity::assign_stress_tensor(), polyfem::assembler::LinearElasticity::assign_stress_tensor(), polyfem::assembler::NeoHookeanElasticity::assign_stress_tensor(), polyfem::assembler::SaintVenantElasticity::assign_stress_tensor(), hooke_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_material_models_, neo_hookean_, saint_venant_, and unconstrained_ogden_elasticity_.
compute_energy()
double polyfem::assembler::MultiModel::compute_energy (const NonLinearAssemblerData & data) const override virtual
Implements polyfem::assembler::NLAssembler.
Definition at line 102 of file MultiModel.cpp.
References polyfem::assembler::GenericElastic< Derived >::compute_energy(), polyfem::assembler::HookeLinearElasticity::compute_energy(), polyfem::assembler::LinearElasticity::compute_energy(), polyfem::assembler::NeoHookeanElasticity::compute_energy(), polyfem::assembler::SaintVenantElasticity::compute_energy(), polyfem::assembler::ElementAssemblyValues::element_id, hooke_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, multi_material_models_, neo_hookean_, saint_venant_, unconstrained_ogden_elasticity_, and polyfem::assembler::NonLinearAssemblerData::vals.
compute_rhs()
Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > polyfem::assembler::MultiModel::compute_rhs (const AutodiffHessianPt & pt) const override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 39 of file MultiModel.cpp.
References polyfem::assembler::Assembler::size().
init_multimodels()
void polyfem::assembler::MultiModel::init_multimodels (const std::vector< std::string > & mats) inline
Definition at line 38 of file MultiModel.hpp.
References multi_material_models_.
name()
std::string polyfem::assembler::MultiModel::name () const inline override virtual
Implements polyfem::assembler::Assembler.
Definition at line 40 of file MultiModel.hpp.
parameters()
std::map< std::string, Assembler::ParamFunc > polyfem::assembler::MultiModel::parameters () const override virtual
Implements polyfem::assembler::Assembler.
Definition at line 152 of file MultiModel.cpp.
set_size()
void polyfem::assembler::MultiModel::set_size (const int size) override virtual
Reimplemented from polyfem::assembler::Assembler.
Definition at line 10 of file MultiModel.cpp.
References hooke_, incompressible_ogden_elasticity_, linear_elasticity_, mooney_rivlin_elasticity_, neo_hookean_, saint_venant_, polyfem::assembler::Assembler::set_size(), polyfem::assembler::HookeLinearElasticity::set_size(), polyfem::assembler::SaintVenantElasticity::set_size(), polyfem::assembler::Assembler::size(), and unconstrained_ogden_elasticity_.
Member Data Documentation
hooke_
HookeLinearElasticity polyfem::assembler::MultiModel::hooke_ private
Definition at line 52 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
incompressible_ogden_elasticity_
IncompressibleOgdenElasticity polyfem::assembler::MultiModel::incompressible_ogden_elasticity_ private
Definition at line 56 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
linear_elasticity_
LinearElasticity polyfem::assembler::MultiModel::linear_elasticity_ private
Definition at line 51 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
mooney_rivlin_3_param_elasticity_
MooneyRivlin3ParamElasticity polyfem::assembler::MultiModel::mooney_rivlin_3_param_elasticity_ private
Definition at line 54 of file MultiModel.hpp.
mooney_rivlin_elasticity_
MooneyRivlinElasticity polyfem::assembler::MultiModel::mooney_rivlin_elasticity_ private
Definition at line 53 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
multi_material_models_
std::vector<std::string> polyfem::assembler::MultiModel::multi_material_models_ private
Definition at line 47 of file MultiModel.hpp.
Referenced by assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and init_multimodels().
neo_hookean_
NeoHookeanElasticity polyfem::assembler::MultiModel::neo_hookean_ private
Definition at line 50 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
saint_venant_
SaintVenantElasticity polyfem::assembler::MultiModel::saint_venant_ private
Definition at line 49 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
unconstrained_ogden_elasticity_
UnconstrainedOgdenElasticity polyfem::assembler::MultiModel::unconstrained_ogden_elasticity_ private
Definition at line 55 of file MultiModel.hpp.
Referenced by add_multimaterial(), assemble_gradient(), assemble_hessian(), assign_stress_tensor(), compute_energy(), and set_size().
The documentation for this class was generated from the following files:
src/polyfem/assembler/MultiModel.hpp
src/polyfem/assembler/MultiModel.cpp