PolyFEM: polyfem::solver::LaggedRegForm Class Reference
polyfem::solver::LaggedRegForm Class Reference
Tikonov regularization form between x and x_lagged.
#include <LaggedRegForm.hpp>
Public Member Functions
LaggedRegForm (const int n_lagging_iters)
Construct a new Lagged Regularization Form object.
std::string name () const override
void init_lagging (const Eigen::VectorXd &x) override
Initialize lagged fields.
void update_lagging (const Eigen::VectorXd &x, const int iter_num) override
Update lagged fields.
bool uses_lagging () const override
Does this form require lagging?
Public Member Functions inherited from polyfem::solver::Form
virtual ~Form ()
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual double value (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x)
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
double value_unweighted (const Eigen::VectorXd &x) const override
Compute the value of the form.
void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const override
Compute the first derivative of the value wrt x.
void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const override
Compute the second derivative of the value wrt x.
Protected Member Functions inherited from polyfem::solver::Form
std::string resolve_output_path (const std::string &path) const
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
Private Attributes
int n_lagging_iters_
Number of iterations to lag for.
Eigen::VectorXd x_lagged_
The full variables from the previous lagging solve.
Additional Inherited Members
Protected Attributes inherited from polyfem::solver::Form
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or Δt²)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Tikonov regularization form between x and x_lagged.
Definition at line 10 of file LaggedRegForm.hpp.
Constructor & Destructor Documentation
LaggedRegForm()
polyfem::solver::LaggedRegForm::LaggedRegForm (const int n_lagging_iters)
Construct a new Lagged Regularization Form object.
Definition at line 9 of file LaggedRegForm.cpp.
References polyfem::solver::Form::disable(), and n_lagging_iters_.
Member Function Documentation
first_derivative_unweighted()
void polyfem::solver::LaggedRegForm::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const override protected virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Implements polyfem::solver::Form.
Definition at line 21 of file LaggedRegForm.cpp.
References x, and x_lagged_.
init_lagging()
void polyfem::solver::LaggedRegForm::init_lagging (const Eigen::VectorXd & x) override virtual
Initialize lagged fields.
Parameters
x Current solution
Reimplemented from polyfem::solver::Form.
Definition at line 32 of file LaggedRegForm.cpp.
References update_lagging(), and x.
name()
std::string polyfem::solver::LaggedRegForm::name () const inline override virtual
Implements polyfem::solver::Form.
Definition at line 16 of file LaggedRegForm.hpp.
second_derivative_unweighted()
void polyfem::solver::LaggedRegForm::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const override protected virtual
Compute the second derivative of the value wrt x.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Implements polyfem::solver::Form.
Definition at line 26 of file LaggedRegForm.cpp.
References x.
update_lagging()
void polyfem::solver::LaggedRegForm::update_lagging (const Eigen::VectorXd & x, const int iter_num) override virtual
Update lagged fields.
Parameters
x Current solution
Returns
True if the lagged fields have been updated
Reimplemented from polyfem::solver::Form.
Definition at line 37 of file LaggedRegForm.cpp.
References polyfem::solver::Form::enabled(), polyfem::logger(), n_lagging_iters_, polyfem::solver::Form::set_enabled(), x, and x_lagged_.
Referenced by init_lagging().
uses_lagging()
bool polyfem::solver::LaggedRegForm::uses_lagging () const inline override virtual
Does this form require lagging?
Returns
True if the form requires lagging
Reimplemented from polyfem::solver::Form.
Definition at line 46 of file LaggedRegForm.hpp.
value_unweighted()
double polyfem::solver::LaggedRegForm::value_unweighted (const Eigen::VectorXd & x) const override protected virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implements polyfem::solver::Form.
Definition at line 16 of file LaggedRegForm.cpp.
References x, and x_lagged_.
Member Data Documentation
n_lagging_iters_
int polyfem::solver::LaggedRegForm::n_lagging_iters_ private
Number of iterations to lag for.
Definition at line 49 of file LaggedRegForm.hpp.
Referenced by LaggedRegForm(), and update_lagging().
x_lagged_
Eigen::VectorXd polyfem::solver::LaggedRegForm::x_lagged_ private
The full variables from the previous lagging solve.
Definition at line 50 of file LaggedRegForm.hpp.
Referenced by first_derivative_unweighted(), update_lagging(), and value_unweighted().
The documentation for this class was generated from the following files:
src/polyfem/solver/forms/LaggedRegForm.hpp
src/polyfem/solver/forms/LaggedRegForm.cpp