PolyFEM: polyfem::solver::Form Class Reference
polyfem::solver::Form Class Reference abstract
#include <Form.hpp>
Public Member Functions
virtual ~Form ()
virtual std::string name () const =0
virtual void init (const Eigen::VectorXd &x)
Initialize the form.
virtual void finish ()
virtual double value (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
Eigen::VectorXd value_per_element (const Eigen::VectorXd &x) const
Compute the value of the form multiplied with the weigth.
virtual void first_derivative (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const
Compute the first derivative of the value wrt x multiplied with the weigth.
void second_derivative (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const
Compute the second derivative of the value wrt x multiplied with the weigth.
virtual bool is_step_valid (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine if a step from solution x0 to solution x1 is allowed.
virtual double max_step_size (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Determine the maximum step size allowable between the current and next solution.
virtual void line_search_begin (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1)
Initialize variables used during the line search.
virtual void line_search_end ()
Clear variables used during the line search.
virtual void post_step (const polysolve::nonlinear::PostStepData &data)
Update fields after a step in the optimization.
virtual void solution_changed (const Eigen::VectorXd &new_x)
Update cached fields upon a change in the solution.
virtual void update_quantities (const double t, const Eigen::VectorXd &x)
Update time-dependent fields.
virtual void init_lagging (const Eigen::VectorXd &x)
Initialize lagged fields TODO: more than one step.
virtual void update_lagging (const Eigen::VectorXd &x, const int iter_num)
Update lagged fields.
virtual int max_lagging_iterations () const
Get the maximum number of lagging iteration allowable.
virtual bool uses_lagging () const
Does this form require lagging?
void set_project_to_psd (bool val)
Set project to psd.
bool is_project_to_psd () const
Get if the form's second derivative is projected to psd.
void enable ()
Enable the form.
void disable ()
Disable the form.
void set_enabled (const bool enabled)
Set if the form is enabled.
bool enabled () const
Determine if the form is enabled.
virtual double weight () const
Get the form's multiplicative constant weight.
void set_weight (const double weight)
Set the form's multiplicative constant weight.
virtual bool is_step_collision_free (const Eigen::VectorXd &x0, const Eigen::VectorXd &x1) const
Checks if the step is collision free.
void set_output_dir (const std::string &output_dir)
Protected Member Functions
std::string resolve_output_path (const std::string &path) const
virtual double value_unweighted (const Eigen::VectorXd &x) const =0
Compute the value of the form.
virtual Eigen::VectorXd value_per_element_unweighted (const Eigen::VectorXd &x) const
Compute the value of the form multiplied per element.
virtual void first_derivative_unweighted (const Eigen::VectorXd &x, Eigen::VectorXd &gradv) const =0
Compute the first derivative of the value wrt x.
virtual void second_derivative_unweighted (const Eigen::VectorXd &x, StiffnessMatrix &hessian) const =0
Compute the second derivative of the value wrt x.
Protected Attributes
bool project_to_psd_ = false
If true, the form's second derivative is projected to be positive semidefinite.
double weight_ = 1
weight of the form (e.g., AL penalty weight or Δt²)
bool enabled_ = true
If true, the form is enabled.
std::string output_dir_
Detailed Description
Definition at line 10 of file Form.hpp.
Constructor & Destructor Documentation
~Form()
virtual polyfem::solver::Form::~Form () inline virtual
Definition at line 13 of file Form.hpp.
Member Function Documentation
disable()
void polyfem::solver::Form::disable () inline
Disable the form.
Definition at line 119 of file Form.hpp.
References enabled_.
Referenced by polyfem::solver::LaggedRegForm::LaggedRegForm().
enable()
void polyfem::solver::Form::enable () inline
Enable the form.
Definition at line 117 of file Form.hpp.
References enabled_.
enabled()
bool polyfem::solver::Form::enabled () const inline
Determine if the form is enabled.
Returns
True if the form is enabled else false
Definition at line 125 of file Form.hpp.
References enabled_.
Referenced by set_enabled(), and polyfem::solver::LaggedRegForm::update_lagging().
finish()
virtual void polyfem::solver::Form::finish () inline virtual
Definition at line 21 of file Form.hpp.
first_derivative()
virtual void polyfem::solver::Form::first_derivative (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const inline virtual
Compute the first derivative of the value wrt x multiplied with the weigth.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Reimplemented in polyfem::solver::AdjointForm.
Definition at line 42 of file Form.hpp.
References first_derivative_unweighted(), weight(), and x.
first_derivative_unweighted()
virtual void polyfem::solver::Form::first_derivative_unweighted (const Eigen::VectorXd & x, Eigen::VectorXd & gradv) const protected pure virtual
Compute the first derivative of the value wrt x.
Parameters
[in] x Current solution
[out] gradv Output gradient of the value wrt x
Implemented in polyfem::solver::AdjointForm, polyfem::solver::BodyForm, polyfem::solver::ContactForm, polyfem::solver::FrictionForm, polyfem::solver::InertiaForm, polyfem::solver::InversionBarrierForm, polyfem::solver::L2ProjectionForm, polyfem::solver::LaggedRegForm, polyfem::solver::BCLagrangianForm, polyfem::solver::GenericLagrangianForm, polyfem::solver::MacroStrainLagrangianForm, polyfem::solver::PeriodicContactForm, polyfem::solver::PressureForm, and polyfem::solver::RayleighDampingForm.
Referenced by first_derivative().
init()
virtual void polyfem::solver::Form::init (const Eigen::VectorXd & x) inline virtual
Initialize the form.
Parameters
x Current solution
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::TransientForm, polyfem::solver::ContactForm, and polyfem::solver::PeriodicContactForm.
Definition at line 19 of file Form.hpp.
Referenced by polyfem::solver::TargetForm::set_reference().
init_lagging()
virtual void polyfem::solver::Form::init_lagging (const Eigen::VectorXd & x) inline virtual
Initialize lagged fields TODO: more than one step.
Parameters
x Current solution
Reimplemented in polyfem::solver::AdjointForm, polyfem::solver::FrictionForm, polyfem::solver::LaggedRegForm, and polyfem::solver::RayleighDampingForm.
Definition at line 96 of file Form.hpp.
is_project_to_psd()
bool polyfem::solver::Form::is_project_to_psd () const inline
Get if the form's second derivative is projected to psd.
Definition at line 114 of file Form.hpp.
References project_to_psd_.
is_step_collision_free()
virtual bool polyfem::solver::Form::is_step_collision_free (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline virtual
Checks if the step is collision free.
Returns
True if the step is collision free else false
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::CollisionBarrierForm, polyfem::solver::DeformedCollisionBarrierForm, polyfem::solver::TransientForm, polyfem::solver::ContactForm, and polyfem::solver::PeriodicContactForm.
Definition at line 138 of file Form.hpp.
is_step_valid()
virtual bool polyfem::solver::Form::is_step_valid (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline virtual
Determine if a step from solution x0 to solution x1 is allowed.
Parameters
x0 Current solution
x1 Proposed next solution
Returns
True if the step is allowed
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::AMIPSForm, polyfem::solver::TransientForm, and polyfem::solver::InversionBarrierForm.
Definition at line 62 of file Form.hpp.
line_search_begin()
virtual void polyfem::solver::Form::line_search_begin (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) inline virtual
Initialize variables used during the line search.
Parameters
x0 Current solution
x1 Next solution
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::TransientForm, polyfem::solver::ContactForm, and polyfem::solver::PeriodicContactForm.
Definition at line 73 of file Form.hpp.
line_search_end()
virtual void polyfem::solver::Form::line_search_end () inline virtual
Clear variables used during the line search.
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::TransientForm, and polyfem::solver::ContactForm.
Definition at line 76 of file Form.hpp.
max_lagging_iterations()
virtual int polyfem::solver::Form::max_lagging_iterations () const inline virtual
Get the maximum number of lagging iteration allowable.
Reimplemented in polyfem::solver::FrictionForm, and polyfem::solver::RayleighDampingForm.
Definition at line 103 of file Form.hpp.
max_step_size()
virtual double polyfem::solver::Form::max_step_size (const Eigen::VectorXd & x0, const Eigen::VectorXd & x1) const inline virtual
Determine the maximum step size allowable between the current and next solution.
Parameters
x0 Current solution (step size = 0)
x1 Next solution (step size = 1)
Returns
Maximum allowable step size
Reimplemented in polyfem::solver::ParametrizationForm, polyfem::solver::CompositeForm, polyfem::solver::CollisionBarrierForm, polyfem::solver::LayerThicknessForm, polyfem::solver::DeformedCollisionBarrierForm, polyfem::solver::TransientForm, polyfem::solver::ContactForm, and polyfem::solver::PeriodicContactForm.
Definition at line 68 of file Form.hpp.
name()
virtual std::string polyfem::solver::Form::name () const pure virtual
Implemented in polyfem::solver::AdjointForm, polyfem::solver::StaticForm, polyfem::solver::MaxStressForm, polyfem::solver::MinJacobianForm, polyfem::solver::AMIPSForm, polyfem::solver::CollisionBarrierForm, polyfem::solver::LayerThicknessForm, polyfem::solver::DeformedCollisionBarrierForm, polyfem::solver::SpatialIntegralForm, polyfem::solver::ElasticEnergyForm, polyfem::solver::StressNormForm, polyfem::solver::ComplianceForm, polyfem::solver::StressForm, polyfem::solver::TargetForm, polyfem::solver::SDFTargetForm, polyfem::solver::MeshTargetForm, polyfem::solver::NodeTargetForm, polyfem::solver::BodyForm, polyfem::solver::ContactForm, polyfem::solver::FrictionForm, polyfem::solver::InertiaForm, polyfem::solver::InversionBarrierForm, polyfem::solver::L2ProjectionForm, polyfem::solver::LaggedRegForm, polyfem::solver::BCLagrangianForm, polyfem::solver::GenericLagrangianForm, polyfem::solver::MacroStrainLagrangianForm, polyfem::solver::PressureForm, and polyfem::solver::RayleighDampingForm.
post_step()
virtual void polyfem::solver::Form::post_step (const polysolve::nonlinear::PostStepData & data) inline virtual
Update fields after a step in the optimization.
Parameters
iter_num Optimization iteration number
x Current solution
data Data containing info about the current iteration
Reimplemented in polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::TransientForm, polyfem::solver::ContactForm, and polyfem::solver::PeriodicContactForm.
Definition at line 82 of file Form.hpp.
resolve_output_path()
std::string polyfem::solver::Form::resolve_output_path (const std::string & path) const inline protected
Definition at line 151 of file Form.hpp.
References output_dir_.
Referenced by polyfem::solver::ContactForm::max_step_size().
second_derivative()
void polyfem::solver::Form::second_derivative (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const inline
Compute the second derivative of the value wrt x multiplied with the weigth.
Note
This is not marked const because ElasticForm needs to cache the matrix assembly.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Definition at line 52 of file Form.hpp.
References second_derivative_unweighted(), weight(), and x.
Referenced by polyfem::solver::RayleighDampingForm::update_lagging().
second_derivative_unweighted()
virtual void polyfem::solver::Form::second_derivative_unweighted (const Eigen::VectorXd & x, StiffnessMatrix & hessian) const protected pure virtual
Compute the second derivative of the value wrt x.
Parameters
[in] x Current solution
[out] hessian Output Hessian of the value wrt x
Implemented in polyfem::solver::AdjointForm, polyfem::solver::BodyForm, polyfem::solver::ContactForm, polyfem::solver::FrictionForm, polyfem::solver::InertiaForm, polyfem::solver::InversionBarrierForm, polyfem::solver::L2ProjectionForm, polyfem::solver::LaggedRegForm, polyfem::solver::BCLagrangianForm, polyfem::solver::GenericLagrangianForm, polyfem::solver::MacroStrainLagrangianForm, polyfem::solver::PeriodicContactForm, polyfem::solver::PressureForm, and polyfem::solver::RayleighDampingForm.
Referenced by second_derivative().
set_enabled()
void polyfem::solver::Form::set_enabled (const bool enabled) inline
Set if the form is enabled.
Definition at line 121 of file Form.hpp.
References enabled(), and enabled_.
Referenced by polyfem::solver::LaggedRegForm::update_lagging().
set_output_dir()
void polyfem::solver::Form::set_output_dir (const std::string & output_dir) inline
Definition at line 140 of file Form.hpp.
References output_dir_.
set_project_to_psd()
void polyfem::solver::Form::set_project_to_psd (bool val) inline
Set project to psd.
Parameters
val If true, the form's second derivative is projected to be positive semidefinite
Definition at line 111 of file Form.hpp.
References project_to_psd_, and val.
set_weight()
void polyfem::solver::Form::set_weight (const double weight) inline
Set the form's multiplicative constant weight.
Parameters
weight New weight to use
Definition at line 132 of file Form.hpp.
References weight(), and weight_.
solution_changed()
virtual void polyfem::solver::Form::solution_changed (const Eigen::VectorXd & new_x) inline virtual
Update cached fields upon a change in the solution.
Parameters
new_x New solution
Reimplemented in polyfem::solver::StaticForm, polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::AdjointForm, polyfem::solver::TransientForm, polyfem::solver::ContactForm, polyfem::solver::PeriodicContactForm, polyfem::solver::CollisionBarrierForm, and polyfem::solver::DeformedCollisionBarrierForm.
Definition at line 86 of file Form.hpp.
update_lagging()
virtual void polyfem::solver::Form::update_lagging (const Eigen::VectorXd & x, const int iter_num) inline virtual
Update lagged fields.
Parameters
x Current solution
Reimplemented in polyfem::solver::AdjointForm, polyfem::solver::FrictionForm, polyfem::solver::LaggedRegForm, and polyfem::solver::RayleighDampingForm.
Definition at line 100 of file Form.hpp.
update_quantities()
virtual void polyfem::solver::Form::update_quantities (const double t, const Eigen::VectorXd & x) inline virtual
Update time-dependent fields.
Parameters
t Current time
x Current solution at time t
Reimplemented in polyfem::solver::AdjointForm, polyfem::solver::BodyForm, polyfem::solver::ContactForm, polyfem::solver::BCLagrangianForm, polyfem::solver::MacroStrainLagrangianForm, polyfem::solver::PeriodicContactForm, and polyfem::solver::PressureForm.
Definition at line 91 of file Form.hpp.
uses_lagging()
virtual bool polyfem::solver::Form::uses_lagging () const inline virtual
Does this form require lagging?
Returns
True if the form requires lagging
Reimplemented in polyfem::solver::FrictionForm, polyfem::solver::LaggedRegForm, and polyfem::solver::RayleighDampingForm.
Definition at line 107 of file Form.hpp.
value()
virtual double polyfem::solver::Form::value (const Eigen::VectorXd & x) const inline virtual
Compute the value of the form multiplied with the weigth.
Parameters
x Current solution
Returns
Computed value
Reimplemented in polyfem::solver::AdjointForm.
Definition at line 26 of file Form.hpp.
References value_unweighted(), weight(), and x.
Referenced by polyfem::solver::InertiaForm::force_shape_derivative(), polyfem::solver::BodyForm::force_shape_derivative(), polyfem::solver::BCLagrangianForm::init_masked_lumped_mass(), and polyfem::solver::AdjointForm::value().
value_per_element()
Eigen::VectorXd polyfem::solver::Form::value_per_element (const Eigen::VectorXd & x) const inline
Compute the value of the form multiplied with the weigth.
Parameters
x Current solution
Returns
Computed value
Definition at line 34 of file Form.hpp.
References value_per_element_unweighted(), weight_, and x.
value_per_element_unweighted()
virtual Eigen::VectorXd polyfem::solver::Form::value_per_element_unweighted (const Eigen::VectorXd & x) const inline protected virtual
Compute the value of the form multiplied per element.
Parameters
x Current solution
Returns
Computed value per element
Reimplemented in polyfem::solver::ContactForm.
Definition at line 166 of file Form.hpp.
Referenced by value_per_element().
value_unweighted()
virtual double polyfem::solver::Form::value_unweighted (const Eigen::VectorXd & x) const protected pure virtual
Compute the value of the form.
Parameters
x Current solution
Returns
Computed value
Implemented in polyfem::solver::StaticForm, polyfem::solver::CompositeForm, polyfem::solver::ParametrizationForm, polyfem::solver::MinJacobianForm, polyfem::solver::AMIPSForm, polyfem::solver::CollisionBarrierForm, polyfem::solver::DeformedCollisionBarrierForm, polyfem::solver::BoundarySmoothingForm, polyfem::solver::MinTargetDistForm, polyfem::solver::TransientForm, polyfem::solver::ProxyTransientForm, polyfem::solver::BodyForm, polyfem::solver::ContactForm, polyfem::solver::FrictionForm, polyfem::solver::InertiaForm, polyfem::solver::InversionBarrierForm, polyfem::solver::L2ProjectionForm, polyfem::solver::LaggedRegForm, polyfem::solver::BCLagrangianForm, polyfem::solver::GenericLagrangianForm, polyfem::solver::MacroStrainLagrangianForm, polyfem::solver::PeriodicContactForm, polyfem::solver::PressureForm, and polyfem::solver::RayleighDampingForm.
Referenced by value().
weight()
virtual double polyfem::solver::Form::weight () const inline virtual
Get the form's multiplicative constant weight.
Reimplemented in polyfem::solver::ContactForm.
Definition at line 128 of file Form.hpp.
References weight_.
Referenced by polyfem::solver::MinTargetDistForm::compute_adjoint_rhs(), polyfem::solver::TransientForm::compute_adjoint_rhs(), polyfem::solver::ProxyTransientForm::compute_adjoint_rhs(), polyfem::solver::SpatialIntegralForm::compute_adjoint_rhs_step(), polyfem::solver::ProxyContactForceForm::compute_adjoint_rhs_step(), polyfem::solver::NodeTargetForm::compute_adjoint_rhs_step(), polyfem::solver::BarycenterTargetForm::compute_adjoint_rhs_step(), polyfem::solver::AMIPSForm::compute_partial_gradient(), polyfem::solver::CollisionBarrierForm::compute_partial_gradient(), polyfem::solver::DeformedCollisionBarrierForm::compute_partial_gradient(), polyfem::solver::BoundarySmoothingForm::compute_partial_gradient(), polyfem::solver::MinTargetDistForm::compute_partial_gradient(), polyfem::solver::TransientForm::compute_partial_gradient(), polyfem::solver::ProxyTransientForm::compute_partial_gradient(), polyfem::solver::CompositeForm::compute_partial_gradient(), polyfem::solver::SpatialIntegralForm::compute_partial_gradient_step(), polyfem::solver::ElasticEnergyForm::compute_partial_gradient_step(), polyfem::solver::StressNormForm::compute_partial_gradient_step(), polyfem::solver::ComplianceForm::compute_partial_gradient_step(), polyfem::solver::StressForm::compute_partial_gradient_step(), polyfem::solver::ProxyContactForceForm::compute_partial_gradient_step(), polyfem::solver::NodeTargetForm::compute_partial_gradient_step(), polyfem::solver::BarycenterTargetForm::compute_partial_gradient_step(), polyfem::solver::ParametrizedProductForm::compute_partial_gradient_with_param(), polyfem::solver::WeightedVolumeForm::compute_partial_gradient_with_param(), polyfem::solver::CompositeForm::compute_reduced_adjoint_rhs(), first_derivative(), second_derivative(), set_weight(), polyfem::solver::RayleighDampingForm::update_lagging(), and value().
Member Data Documentation
enabled_
bool polyfem::solver::Form::enabled_ = true protected
If true, the form is enabled.
Definition at line 147 of file Form.hpp.
Referenced by disable(), enable(), enabled(), and set_enabled().
output_dir_
std::string polyfem::solver::Form::output_dir_ protected
Definition at line 149 of file Form.hpp.
Referenced by resolve_output_path(), and set_output_dir().
project_to_psd_
bool polyfem::solver::Form::project_to_psd_ = false protected
If true, the form's second derivative is projected to be positive semidefinite.
Definition at line 143 of file Form.hpp.
Referenced by is_project_to_psd(), polyfem::solver::ContactForm::second_derivative_unweighted(), polyfem::solver::FrictionForm::second_derivative_unweighted(), polyfem::solver::PressureForm::second_derivative_unweighted(), and set_project_to_psd().
weight_
double polyfem::solver::Form::weight_ = 1 protected
weight of the form (e.g., AL penalty weight or Δt²)
Definition at line 145 of file Form.hpp.
Referenced by set_weight(), polyfem::solver::ContactForm::update_barrier_stiffness(), value_per_element(), weight(), and polyfem::solver::ContactForm::weight().
The documentation for this class was generated from the following file:
src/polyfem/solver/forms/Form.hpp