PolyFEM: polyfem::mesh::NCMesh2D Class Reference
polyfem::mesh::NCMesh2D Class Reference
#include <NCMesh2D.hpp>
Classes
struct ArrayHasher2D
struct follower_edge
struct follower_face
struct ncBoundary
struct ncElem
struct ncVert
Public Member Functions
NCMesh2D ()=default
virtual ~NCMesh2D ()=default
NCMesh2D (NCMesh2D &&)=default
NCMesh2D & operator= (NCMesh2D &&)=default
NCMesh2D (const NCMesh2D &)=default
NCMesh2D & operator= (const NCMesh2D &)=default
bool is_conforming () const override
if the mesh is conforming
int n_faces () const override
number of faces
int n_edges () const override
number of edges
int n_vertices () const override
number of vertices
int n_face_vertices (const int f_id) const override
number of vertices of a face
int face_ref_level (const int f_id) const
int face_vertex (const int f_id, const int lv_id) const override
id of the face vertex
int edge_vertex (const int e_id, const int lv_id) const override
id of the edge vertex
int cell_vertex (const int f_id, const int lv_id) const override
id of the vertex of a cell
int face_edge (const int f_id, const int le_id) const
int leader_edge_of_vertex (const int v_id) const
int leader_edge_of_edge (const int e_id) const
int n_follower_edges (const int e_id) const
int n_face_neighbors (const int e_id) const
int face_neighbor (const int e_id) const
bool is_boundary_vertex (const int vertex_global_id) const override
is vertex boundary
bool is_boundary_edge (const int edge_global_id) const override
is edge boundary
bool is_boundary_element (const int element_global_id) const override
is cell boundary
void refine (const int n_refinement, const double t) override
refine the mesh
bool build_from_matrices (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F) override
build a mesh from matrices
void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes) override
attach high order nodes
RowVectorNd edge_node (const Navigation::Index &index, const int n_new_nodes, const int i) const override
RowVectorNd face_node (const Navigation::Index &index, const int n_new_nodes, const int i, const int j) const override
void normalize () override
normalize the mesh
double edge_length (const int gid) const override
edge length
void compute_elements_tag () override
compute element types, see ElementType
void update_elements_tag () override
Update elements types.
void set_point (const int global_index, const RowVectorNd &p) override
RowVectorNd point (const int global_index) const override
point coordinates
RowVectorNd edge_barycenter (const int index) const override
edge barycenter
void bounding_box (RowVectorNd &min, RowVectorNd &max) const override
computes the bbox of the mesh
void compute_boundary_ids (const double eps) override
computes the selection based on the bbx of the mesh.
void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker) override
computes boundary selections based on a function
void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void set_boundary_ids (const std::vector< int > &boundary_ids) override
Set the boundary selection from a vector.
void set_body_ids (const std::vector< int > &body_ids) override
Set the volume sections.
void set_body_ids (const Eigen::VectorXi &body_ids) override
Set the volume sections.
int get_boundary_id (const int primitive) const override
Get the boundary selection of an element (face in 3d, edge in 2d)
int get_body_id (const int primitive) const override
Get the volume selection of an element (cell in 3d, face in 2d)
Navigation::Index get_index_from_face (int f, int lv=0) const override
Navigation::Index switch_vertex (Navigation::Index idx) const override
Navigation::Index switch_edge (Navigation::Index idx) const override
Navigation::Index switch_face (Navigation::Index idx) const override
void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const override
generate a triangular representation of every face
void refine_element (int id_full)
void refine_elements (const std::vector< int > &ids)
void coarsen_element (int id_full)
void mark_boundary ()
void prepare_mesh () override
method used to finalize the mesh.
void build_index_mapping ()
Public Member Functions inherited from polyfem::mesh::Mesh2D
Mesh2D ()=default
virtual ~Mesh2D ()=default
Mesh2D (Mesh2D &&)=default
Mesh2D & operator= (Mesh2D &&)=default
Mesh2D (const Mesh2D &)=default
Mesh2D & operator= (const Mesh2D &)=default
bool is_volume () const override
checks if mesh is volume
int n_cells () const override
number of cells
bool is_boundary_face (const int face_global_id) const override
is face boundary
virtual RowVectorNd edge_node (const Navigation::Index &index, const int n_new_nodes, const int i) const =0
virtual RowVectorNd face_node (const Navigation::Index &index, const int n_new_nodes, const int i, const int j) const =0
virtual void set_point (const int global_index, const RowVectorNd &p)=0
RowVectorNd cell_barycenter (const int index) const override
cell barycenter
virtual Navigation::Index get_index_from_face (int f, int lv=0) const =0
virtual Navigation::Index switch_vertex (Navigation::Index idx) const =0
virtual Navigation::Index switch_edge (Navigation::Index idx) const =0
virtual Navigation::Index switch_face (Navigation::Index idx) const =0
void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const override
constructs barycentric coodiantes for a point p.
RowVectorNd face_barycenter (const int index) const override
face barycenter
void compute_element_barycenters (Eigen::MatrixXd &barycenters) const override
utility for 2d/3d.
void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const override
constructs a box around every element (3d cell, 2d face)
Navigation::Index next_around_face (Navigation::Index idx) const
Navigation::Index next_around_vertex (Navigation::Index idx) const
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const override
Get all the edges.
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const override
Get all the edges according to valid_elements selection.
Public Member Functions inherited from polyfem::mesh::Mesh
virtual ~Mesh ()=default
Destroy the Mesh object.
Mesh (Mesh &&)=default
Construct a new Mesh object.
Mesh & operator= (Mesh &&)=default
Copy constructor.
Mesh (const Mesh &)=default
Construct a new Mesh object.
Mesh & operator= (const Mesh &)=default
virtual void refine (const int n_refinement, const double t)=0
refine the mesh
virtual bool is_volume () const =0
checks if mesh is volume
int dimension () const
utily for dimension
virtual bool is_conforming () const =0
if the mesh is conforming
int n_elements () const
utitlity to return the number of elements, cells or faces in 3d and 2d
virtual int n_cells () const =0
number of cells
virtual int n_faces () const =0
number of faces
virtual int n_edges () const =0
number of edges
virtual int n_vertices () const =0
number of vertices
virtual int n_face_vertices (const int f_id) const =0
number of vertices of a face
virtual int face_vertex (const int f_id, const int lv_id) const =0
id of the face vertex
virtual int edge_vertex (const int e_id, const int lv_id) const =0
id of the edge vertex
virtual int cell_vertex (const int f_id, const int lv_id) const =0
id of the vertex of a cell
virtual bool is_boundary_vertex (const int vertex_global_id) const =0
is vertex boundary
virtual bool is_boundary_edge (const int edge_global_id) const =0
is edge boundary
virtual bool is_boundary_face (const int face_global_id) const =0
is face boundary
virtual bool is_boundary_element (const int element_global_id) const =0
is cell boundary
virtual void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes)=0
attach high order nodes
const Eigen::MatrixXi & orders () const
order of each element
bool is_rational () const
check if curved mesh has rational polynomials elements
void set_is_rational (const bool in_is_rational)
Set the is rational object.
virtual void normalize ()=0
normalize the mesh
virtual void compute_elements_tag ()=0
compute element types, see ElementType
virtual void update_elements_tag ()
Update elements types.
virtual double edge_length (const int gid) const
edge length
virtual double quad_area (const int gid) const
area of a quad face of an hex mesh
virtual double tri_area (const int gid) const
area of a tri face of a tet mesh
virtual RowVectorNd point (const int global_index) const =0
point coordinates
virtual RowVectorNd edge_barycenter (const int e) const =0
edge barycenter
virtual RowVectorNd face_barycenter (const int f) const =0
face barycenter
virtual RowVectorNd cell_barycenter (const int c) const =0
cell barycenter
void edge_barycenters (Eigen::MatrixXd &barycenters) const
all edges barycenters
void face_barycenters (Eigen::MatrixXd &barycenters) const
all face barycenters
void cell_barycenters (Eigen::MatrixXd &barycenters) const
all cells barycenters
virtual void compute_element_barycenters (Eigen::MatrixXd &barycenters) const =0
utility for 2d/3d.
virtual void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const =0
constructs a box around every element (3d cell, 2d face)
virtual void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const =0
constructs barycentric coodiantes for a point p.
virtual void bounding_box (RowVectorNd &min, RowVectorNd &max) const =0
computes the bbox of the mesh
bool is_spline_compatible (const int el_id) const
checks if element is spline compatible
bool is_cube (const int el_id) const
checks if element is cube compatible
bool is_polytope (const int el_id) const
checks if element is polygon compatible
bool is_simplex (const int el_id) const
checks if element is simples compatible
const std::vector< ElementType > & elements_tag () const
Returns the elements types.
void set_tag (const int el, const ElementType type)
changes the element type
virtual void load_boundary_ids (const std::string &path)
loads the boundary selections for a file
virtual void compute_boundary_ids (const double eps)=0
computes the selection based on the bbx of the mesh.
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void set_boundary_ids (const std::vector< int > &boundary_ids)
Set the boundary selection from a vector.
virtual void set_body_ids (const std::vector< int > &body_ids)
Set the volume sections.
virtual void set_body_ids (const Eigen::VectorXi &body_ids)
Set the volume sections.
virtual int get_boundary_id (const int primitive) const
Get the boundary selection of an element (face in 3d, edge in 2d)
virtual int get_body_id (const int primitive) const
Get the volume selection of an element (cell in 3d, face in 2d)
bool has_boundary_ids () const
checks if surface selections are available
virtual bool has_body_ids () const
checks if volumes selections are available
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const =0
Get all the edges.
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const =0
Get all the edges according to valid_elements selection.
virtual void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const =0
generate a triangular representation of every face
const std::vector< double > & cell_weights (const int cell_index) const
weights for rational polynomial meshes
void set_cell_weights (const std::vector< std::vector< double > > &in_cell_weights)
Set the cell weights for rational polynomial meshes.
virtual void prepare_mesh ()
method used to finalize the mesh.
bool has_poly () const
checks if the mesh has polytopes
bool is_linear ()
check if the mesh is linear
std::vector< std::pair< int, int > > edges () const
list of sorted edges.
std::vector< std::vector< int > > faces () const
list of sorted faces.
std::unordered_map< std::pair< int, int >, size_t, polyfem::utils::HashPair > edges_to_ids () const
map from edge (pair of v id) to the id of the edge
std::unordered_map< std::vector< int >, size_t, polyfem::utils::HashVector > faces_to_ids () const
map from face (tuple of v id) to the id of the face
const Eigen::VectorXi & in_ordered_vertices () const
Order of the input vertices.
const Eigen::MatrixXi & in_ordered_edges () const
Order of the input edges.
const Eigen::MatrixXi & in_ordered_faces () const
Order of the input edges.
Static Public Member Functions
static double element_weight_to_edge_weight (const int l, const Eigen::Vector2d &pos)
Static Public Member Functions inherited from polyfem::mesh::Mesh
static std::unique_ptr< Mesh > create (const std::string &path, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (GEO::Mesh &M, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (const Eigen::MatrixXd &vertices, const Eigen::MatrixXi &cells, const bool non_conforming=false)
factory to build the proper mesh
Protected Member Functions
bool load (const std::string &path) override
loads a mesh from the path
bool load (const GEO::Mesh &mesh) override
loads a mesh from a geo mesh
int all_to_valid_vertex (const int id) const
int valid_to_all_vertex (const int id) const
int all_to_valid_edge (const int id) const
int valid_to_all_edge (const int id) const
int all_to_valid_elem (const int id) const
int valid_to_all_elem (const int id) const
int find_vertex (Eigen::Vector2i v) const
int find_vertex (const int v1, const int v2) const
int get_vertex (Eigen::Vector2i v)
int find_edge (Eigen::Vector2i v) const
int find_edge (const int v1, const int v2) const
int get_edge (Eigen::Vector2i v)
int get_edge (const int v1, const int v2)
void traverse_edge (Eigen::Vector2i v, double p1, double p2, int depth, std::vector< follower_edge > &list) const
void build_edge_follower_chain ()
void build_element_vertex_adjacency ()
int add_element (Eigen::Vector3i v, int parent=-1)
Protected Member Functions inherited from polyfem::mesh::Mesh
Mesh ()=default
Construct a new Mesh object.
virtual bool load (const std::string &path)=0
loads a mesh from the path
virtual bool load (const GEO::Mesh &M)=0
loads a mesh from a geo mesh
Protected Attributes
int n_elements = 0
bool index_prepared = false
bool adj_prepared = false
std::vector< ncElem > elements
std::vector< ncVert > vertices
std::vector< ncBoundary > edges
std::unordered_map< Eigen::Vector2i, int, ArrayHasher2D > midpointMap
std::unordered_map< Eigen::Vector2i, int, ArrayHasher2D > edgeMap
std::vector< int > all_to_valid_elemMap
std::vector< int > valid_to_all_elemMap
std::vector< int > all_to_valid_vertexMap
std::vector< int > valid_to_all_vertexMap
std::vector< int > all_to_valid_edgeMap
std::vector< int > valid_to_all_edgeMap
std::vector< int > refineHistory
Eigen::SparseMatrix< bool, Eigen::RowMajor > elementAdj
Protected Attributes inherited from polyfem::mesh::Mesh
std::vector< ElementType > elements_tag_
list of element types
std::vector< int > boundary_ids_
list of surface labels
std::vector< int > body_ids_
list of volume labels
Eigen::MatrixXi orders_
list of geometry orders, one per cell
bool is_rational_ = false
stores if the mesh is rational
std::vector< EdgeNodes > edge_nodes_
high-oder nodes associates to edges
std::vector< FaceNodes > face_nodes_
high-oder nodes associates to faces
std::vector< CellNodes > cell_nodes_
high-oder nodes associates to cells
std::vector< std::vector< double > > cell_weights_
weights associates to cells for rational polynomail meshes
Eigen::VectorXi in_ordered_vertices_
Order of the input vertices.
Eigen::MatrixXi in_ordered_edges_
Order of the input edges.
Eigen::MatrixXi in_ordered_faces_
Order of the input faces, TODO: change to std::vector of Eigen::Vector.
Detailed Description
Definition at line 9 of file NCMesh2D.hpp.
Constructor & Destructor Documentation
NCMesh2D() [1/3]
polyfem::mesh::NCMesh2D::NCMesh2D () default
~NCMesh2D()
virtual polyfem::mesh::NCMesh2D::~NCMesh2D () virtual default
NCMesh2D() [2/3]
polyfem::mesh::NCMesh2D::NCMesh2D (NCMesh2D &&) default
NCMesh2D() [3/3]
polyfem::mesh::NCMesh2D::NCMesh2D (const NCMesh2D &) default
Member Function Documentation
add_element()
int polyfem::mesh::NCMesh2D::add_element (Eigen::Vector3i v, int parent = -1) protected
Definition at line 148 of file NCMesh2D.cpp.
References adj_prepared, edges, elements, get_edge(), index_prepared, n_elements, and vertices.
Referenced by build_from_matrices(), load(), and refine_element().
all_to_valid_edge()
int polyfem::mesh::NCMesh2D::all_to_valid_edge (const int id) const inline protected
Definition at line 323 of file NCMesh2D.hpp.
References all_to_valid_edgeMap, and index_prepared.
Referenced by face_edge(), get_index_from_face(), leader_edge_of_edge(), leader_edge_of_vertex(), and switch_edge().
all_to_valid_elem()
int polyfem::mesh::NCMesh2D::all_to_valid_elem (const int id) const inline protected
Definition at line 337 of file NCMesh2D.hpp.
References all_to_valid_elemMap, and index_prepared.
Referenced by face_neighbor().
all_to_valid_vertex()
int polyfem::mesh::NCMesh2D::all_to_valid_vertex (const int id) const inline protected
Definition at line 311 of file NCMesh2D.hpp.
References all_to_valid_vertexMap, and index_prepared.
Referenced by cell_vertex(), edge_vertex(), face_vertex(), get_index_from_face(), and switch_vertex().
attach_higher_order_nodes()
void polyfem::mesh::NCMesh2D::attach_higher_order_nodes (const Eigen::MatrixXd & V, const std::vector< std::vector< int > > & nodes) override virtual
attach high order nodes
Parameters
[in] V nodes
[in] nodes list of nodes per element
Implements polyfem::mesh::Mesh.
Definition at line 71 of file NCMesh2D.cpp.
References elasticity_rhs::f, n_faces(), and p_bases::nodes.
bounding_box()
void polyfem::mesh::NCMesh2D::bounding_box (RowVectorNd & min, RowVectorNd & max) const override virtual
computes the bbox of the mesh
Parameters
[out] min min coodiante
[out] max max coodiante
Implements polyfem::mesh::Mesh.
Definition at line 560 of file NCMesh2D.cpp.
Referenced by compute_boundary_ids().
build_edge_follower_chain()
void polyfem::mesh::NCMesh2D::build_edge_follower_chain () protected
Definition at line 299 of file NCMesh2D.cpp.
References edges, elements, and traverse_edge().
Referenced by prepare_mesh().
build_element_vertex_adjacency()
void polyfem::mesh::NCMesh2D::build_element_vertex_adjacency () protected
Definition at line 375 of file NCMesh2D.cpp.
References edges, elements, polyfem::mesh::find(), polyfem::mesh::line_weight(), and vertices.
Referenced by prepare_mesh().
build_from_matrices()
bool polyfem::mesh::NCMesh2D::build_from_matrices (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F) override virtual
build a mesh from matrices
Parameters
[in] V vertices
[in] F connectivity
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 39 of file NCMesh2D.cpp.
References add_element(), adj_prepared, edgeMap, edges, elements, index_prepared, midpointMap, n_elements, polyfem::mesh::orient_normals_2d(), prepare_mesh(), refineHistory, polyfem::mesh::to_geogram_mesh(), and vertices.
build_index_mapping()
void polyfem::mesh::NCMesh2D::build_index_mapping ()
Definition at line 450 of file NCMesh2D.cpp.
References all_to_valid_edgeMap, all_to_valid_elemMap, all_to_valid_vertexMap, edges, elements, index_prepared, n_edges(), n_elements, n_vertices(), valid_to_all_edgeMap, valid_to_all_elemMap, valid_to_all_vertexMap, and vertices.
Referenced by prepare_mesh().
cell_vertex()
int polyfem::mesh::NCMesh2D::cell_vertex (const int f_id, const int lv_id) const inline override virtual
id of the vertex of a cell
Parameters
[in] f_id global cell id
[in] lv_id local vertex id
Returns
vertex id
Implements polyfem::mesh::Mesh.
Definition at line 193 of file NCMesh2D.hpp.
References all_to_valid_vertex(), elements, valid_to_all_elem(), and vertices.
coarsen_element()
void polyfem::mesh::NCMesh2D::coarsen_element (int id_full)
Definition at line 254 of file NCMesh2D.cpp.
References adj_prepared, edges, elements, index_prepared, n_elements, refineHistory, and vertices.
compute_body_ids()
void polyfem::mesh::NCMesh2D::compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id and barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 778 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::body_ids_, elements, polyfem::mesh::Mesh2D::face_barycenter(), n_faces(), and valid_to_all_elem().
compute_boundary_ids() [1/5]
void polyfem::mesh::NCMesh2D::compute_boundary_ids (const double eps) override virtual
computes the selection based on the bbx of the mesh.
Left gets 1, bottom 2, right 3, top 4, front 5, back 6
Parameters
[in] eps tolerance for proximity
Implements polyfem::mesh::Mesh.
Definition at line 791 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, bounding_box(), edge_barycenter(), edges, is_boundary_edge(), n_edges(), and valid_to_all_edge().
compute_boundary_ids() [2/5]
void polyfem::mesh::NCMesh2D::compute_boundary_ids (const std::function< int(const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 823 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_barycenter(), edges, is_boundary_edge(), n_edges(), and valid_to_all_edge().
compute_boundary_ids() [3/5]
void polyfem::mesh::NCMesh2D::compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 841 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_barycenter(), edges, is_boundary_edge(), n_edges(), and valid_to_all_edge().
compute_boundary_ids() [4/5]
void polyfem::mesh::NCMesh2D::compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id, barycenter, and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 854 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_barycenter(), edges, is_boundary_edge(), n_edges(), and valid_to_all_edge().
compute_boundary_ids() [5/5]
void polyfem::mesh::NCMesh2D::compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the list of vertices and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 867 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, edge_vertex(), edges, is_boundary_edge(), n_edges(), and valid_to_all_edge().
compute_elements_tag()
void polyfem::mesh::NCMesh2D::compute_elements_tag () override virtual
compute element types, see ElementType
Implements polyfem::mesh::Mesh.
Definition at line 673 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::elements_tag_, n_faces(), and polyfem::mesh::Simplex.
Referenced by prepare_mesh().
edge_barycenter()
RowVectorNd polyfem::mesh::NCMesh2D::edge_barycenter (const int e) const override virtual
edge barycenter
Parameters
[in] e global edge index
Returns
edge barycenter
Implements polyfem::mesh::Mesh.
Definition at line 687 of file NCMesh2D.cpp.
References edge_vertex(), and point().
Referenced by compute_boundary_ids().
edge_length()
double polyfem::mesh::NCMesh2D::edge_length (const int gid) const override virtual
edge length
Parameters
[in] gid global edge id
Returns
edge length
Reimplemented from polyfem::mesh::Mesh.
Definition at line 665 of file NCMesh2D.cpp.
References edge_vertex(), and point().
edge_node()
RowVectorNd polyfem::mesh::NCMesh2D::edge_node (const Navigation::Index & index, const int n_new_nodes, const int i) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 77 of file NCMesh2D.cpp.
References point(), switch_vertex(), and polyfem::mesh::Navigation::Index::vertex.
edge_vertex()
int polyfem::mesh::NCMesh2D::edge_vertex (const int e_id, const int lv_id) const inline override virtual
id of the edge vertex
Parameters
[in] e_id global edge id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 192 of file NCMesh2D.hpp.
References all_to_valid_vertex(), edges, valid_to_all_edge(), and vertices.
Referenced by compute_boundary_ids(), edge_barycenter(), and edge_length().
element_weight_to_edge_weight()
double polyfem::mesh::NCMesh2D::element_weight_to_edge_weight (const int l, const Eigen::Vector2d & pos) static
Definition at line 427 of file NCMesh2D.cpp.
face_edge()
int polyfem::mesh::NCMesh2D::face_edge (const int f_id, const int le_id) const inline
Definition at line 195 of file NCMesh2D.hpp.
References all_to_valid_edge(), edges, elements, and valid_to_all_elem().
Referenced by is_boundary_element().
face_neighbor()
int polyfem::mesh::NCMesh2D::face_neighbor (const int e_id) const inline
Definition at line 216 of file NCMesh2D.hpp.
References all_to_valid_elem(), edges, and valid_to_all_edge().
face_node()
RowVectorNd polyfem::mesh::NCMesh2D::face_node (const Navigation::Index & index, const int n_new_nodes, const int i, const int j) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 86 of file NCMesh2D.cpp.
References point(), switch_edge(), switch_vertex(), and polyfem::mesh::Navigation::Index::vertex.
face_ref_level()
int polyfem::mesh::NCMesh2D::face_ref_level (const int f_id) const inline
Definition at line 189 of file NCMesh2D.hpp.
References elements, and valid_to_all_elem().
face_vertex()
int polyfem::mesh::NCMesh2D::face_vertex (const int f_id, const int lv_id) const inline override virtual
id of the face vertex
Parameters
[in] f_id global face id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 191 of file NCMesh2D.hpp.
References all_to_valid_vertex(), elements, valid_to_all_elem(), and vertices.
Referenced by triangulate_faces().
find_edge() [1/2]
int polyfem::mesh::NCMesh2D::find_edge (const int v1, const int v2) const inline protected
Definition at line 357 of file NCMesh2D.hpp.
References find_edge().
Referenced by find_edge().
find_edge() [2/2]
int polyfem::mesh::NCMesh2D::find_edge (Eigen::Vector2i v) const protected
Definition at line 125 of file NCMesh2D.cpp.
References edgeMap.
Referenced by get_edge(), refine_element(), and traverse_edge().
find_vertex() [1/2]
int polyfem::mesh::NCMesh2D::find_vertex (const int v1, const int v2) const inline protected
Definition at line 350 of file NCMesh2D.hpp.
References find_vertex().
Referenced by find_vertex().
find_vertex() [2/2]
int polyfem::mesh::NCMesh2D::find_vertex (Eigen::Vector2i v) const protected
Definition at line 101 of file NCMesh2D.cpp.
References midpointMap.
Referenced by get_vertex(), refine_element(), and traverse_edge().
get_body_id()
int polyfem::mesh::NCMesh2D::get_body_id (const int primitive) const inline override virtual
Get the volume selection of an element (cell in 3d, face in 2d)
Parameters
[in] primitive element id
Returns
label of element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 259 of file NCMesh2D.hpp.
References elements, and valid_to_all_elem().
get_boundary_id()
int polyfem::mesh::NCMesh2D::get_boundary_id (const int primitive) const inline override virtual
Get the boundary selection of an element (face in 3d, edge in 2d)
Parameters
[in] primitive element id
Returns
label of element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 258 of file NCMesh2D.hpp.
References edges, and valid_to_all_edge().
get_edge() [1/2]
int polyfem::mesh::NCMesh2D::get_edge (const int v1, const int v2) inline protected
Definition at line 361 of file NCMesh2D.hpp.
References get_edge().
Referenced by get_edge().
get_edge() [2/2]
int polyfem::mesh::NCMesh2D::get_edge (Eigen::Vector2i v) protected
Definition at line 135 of file NCMesh2D.cpp.
References edgeMap, edges, and find_edge().
Referenced by add_element(), and refine_element().
get_index_from_face()
Navigation::Index polyfem::mesh::NCMesh2D::get_index_from_face (int f, int lv = 0) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 577 of file NCMesh2D.cpp.
References all_to_valid_edge(), all_to_valid_vertex(), polyfem::mesh::Navigation::Index::edge, elements, elasticity_rhs::f, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, valid_to_all_elem(), and polyfem::mesh::Navigation::Index::vertex.
get_vertex()
int polyfem::mesh::NCMesh2D::get_vertex (Eigen::Vector2i v) protected
Definition at line 111 of file NCMesh2D.cpp.
References find_vertex(), midpointMap, and vertices.
Referenced by refine_element().
is_boundary_edge()
bool polyfem::mesh::NCMesh2D::is_boundary_edge (const int edge_global_id) const inline override virtual
is edge boundary
Parameters
[in] edge_global_id global edge id
Returns
is edge boundary
Implements polyfem::mesh::Mesh.
Definition at line 219 of file NCMesh2D.hpp.
References edges, and valid_to_all_edge().
Referenced by compute_boundary_ids(), and is_boundary_element().
is_boundary_element()
bool polyfem::mesh::NCMesh2D::is_boundary_element (const int element_global_id) const override virtual
is cell boundary
Parameters
[in] element_global_id global cell id
Returns
is cell boundary
Implements polyfem::mesh::Mesh.
Definition at line 13 of file NCMesh2D.cpp.
References face_edge(), index_prepared, is_boundary_edge(), and n_face_vertices().
is_boundary_vertex()
bool polyfem::mesh::NCMesh2D::is_boundary_vertex (const int vertex_global_id) const inline override virtual
is vertex boundary
Parameters
[in] vertex_global_id global vertex id
Returns
is vertex boundary
Implements polyfem::mesh::Mesh.
Definition at line 218 of file NCMesh2D.hpp.
References valid_to_all_vertex(), and vertices.
is_conforming()
bool polyfem::mesh::NCMesh2D::is_conforming () const inline override virtual
if the mesh is conforming
Returns
if the mesh is conforming
Implements polyfem::mesh::Mesh.
Definition at line 166 of file NCMesh2D.hpp.
leader_edge_of_edge()
int polyfem::mesh::NCMesh2D::leader_edge_of_edge (const int e_id) const inline
Definition at line 201 of file NCMesh2D.hpp.
References adj_prepared, all_to_valid_edge(), edges, and valid_to_all_edge().
leader_edge_of_vertex()
int polyfem::mesh::NCMesh2D::leader_edge_of_vertex (const int v_id) const inline
Definition at line 196 of file NCMesh2D.hpp.
References adj_prepared, all_to_valid_edge(), valid_to_all_vertex(), and vertices.
load() [1/2]
bool polyfem::mesh::NCMesh2D::load (const GEO::Mesh & M) override protected virtual
loads a mesh from a geo mesh
Parameters
[in] M geo mesh
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 524 of file NCMesh2D.cpp.
References add_element(), elasticity_rhs::f, n_elements, polyfem::mesh::orient_normals_2d(), prepare_mesh(), and vertices.
load() [2/2]
bool polyfem::mesh::NCMesh2D::load (const std::string & path) override protected virtual
loads a mesh from the path
Parameters
[in] path file location
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 518 of file NCMesh2D.cpp.
mark_boundary()
void polyfem::mesh::NCMesh2D::mark_boundary ()
Definition at line 332 of file NCMesh2D.cpp.
References edges, and vertices.
Referenced by prepare_mesh().
n_edges()
int polyfem::mesh::NCMesh2D::n_edges () const inline override virtual
number of edges
Returns
number of edges
Implements polyfem::mesh::Mesh.
Definition at line 169 of file NCMesh2D.hpp.
References edges.
Referenced by build_index_mapping(), compute_boundary_ids(), and set_boundary_ids().
n_face_neighbors()
int polyfem::mesh::NCMesh2D::n_face_neighbors (const int e_id) const inline
Definition at line 214 of file NCMesh2D.hpp.
References edges, and valid_to_all_edge().
n_face_vertices()
int polyfem::mesh::NCMesh2D::n_face_vertices (const int f_id) const inline override virtual
number of vertices of a face
Parameters
[in] f_id global face id
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 187 of file NCMesh2D.hpp.
Referenced by is_boundary_element(), and triangulate_faces().
n_faces()
int polyfem::mesh::NCMesh2D::n_faces () const inline override virtual
number of faces
Returns
number of faces
Implements polyfem::mesh::Mesh.
Definition at line 168 of file NCMesh2D.hpp.
References n_elements.
Referenced by attach_higher_order_nodes(), compute_body_ids(), compute_elements_tag(), set_body_ids(), triangulate_faces(), and update_elements_tag().
n_follower_edges()
int polyfem::mesh::NCMesh2D::n_follower_edges (const int e_id) const inline
Definition at line 208 of file NCMesh2D.hpp.
References adj_prepared, edges, and valid_to_all_edge().
n_vertices()
int polyfem::mesh::NCMesh2D::n_vertices () const inline override virtual
number of vertices
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 177 of file NCMesh2D.hpp.
References vertices.
Referenced by build_index_mapping(), and triangulate_faces().
normalize()
void polyfem::mesh::NCMesh2D::normalize () override virtual
normalize the mesh
Implements polyfem::mesh::Mesh.
Definition at line 653 of file NCMesh2D.cpp.
operator=() [1/2]
NCMesh2D & polyfem::mesh::NCMesh2D::operator= (const NCMesh2D &) default
operator=() [2/2]
NCMesh2D & polyfem::mesh::NCMesh2D::operator= (NCMesh2D &&) default
point()
RowVectorNd polyfem::mesh::NCMesh2D::point (const int global_index) const inline override virtual
point coordinates
Parameters
[in] global_index global vertex index
Returns
RowVectorNd
Implements polyfem::mesh::Mesh.
Definition at line 239 of file NCMesh2D.hpp.
References index_prepared, valid_to_all_vertex(), and vertices.
Referenced by edge_barycenter(), edge_length(), edge_node(), face_node(), and triangulate_faces().
prepare_mesh()
void polyfem::mesh::NCMesh2D::prepare_mesh () inline override virtual
method used to finalize the mesh.
It computes the cached stuff used in navigation
Reimplemented from polyfem::mesh::Mesh.
Definition at line 285 of file NCMesh2D.hpp.
References adj_prepared, build_edge_follower_chain(), build_element_vertex_adjacency(), build_index_mapping(), compute_elements_tag(), and mark_boundary().
Referenced by build_from_matrices(), and load().
refine()
void polyfem::mesh::NCMesh2D::refine (const int n_refinement, const double t) override virtual
refine the mesh
Parameters
[in] n_refinement number of refinements
[in] t position of the refinement location (0.5 for standard refinement)
Implements polyfem::mesh::Mesh.
Definition at line 23 of file NCMesh2D.cpp.
References elements, tetrahedron::is_valid(), refine(), and refine_element().
Referenced by refine().
refine_element()
void polyfem::mesh::NCMesh2D::refine_element (int id_full)
Definition at line 178 of file NCMesh2D.cpp.
References add_element(), adj_prepared, edge_id, edges, elements, find_edge(), find_vertex(), get_edge(), get_vertex(), index_prepared, n_elements, refineHistory, and vertices.
Referenced by refine(), and refine_elements().
refine_elements()
void polyfem::mesh::NCMesh2D::refine_elements (const std::vector< int > & ids)
Definition at line 244 of file NCMesh2D.cpp.
References refine_element(), and valid_to_all_elem().
set_body_ids() [1/2]
void polyfem::mesh::NCMesh2D::set_body_ids (const Eigen::VectorXi & body_ids) override virtual
Set the volume sections.
Parameters
[in] body_ids matrix of labels, one per element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 760 of file NCMesh2D.cpp.
References elements, n_faces(), and valid_to_all_elem().
set_body_ids() [2/2]
void polyfem::mesh::NCMesh2D::set_body_ids (const std::vector< int > & body_ids) override virtual
Set the volume sections.
Parameters
[in] body_ids vector of labels, one per element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 751 of file NCMesh2D.cpp.
References elements, n_faces(), and valid_to_all_elem().
set_boundary_ids()
void polyfem::mesh::NCMesh2D::set_boundary_ids (const std::vector< int > & boundary_ids) override virtual
Set the boundary selection from a vector.
Parameters
[in] boundary_ids vector one value per element
Reimplemented from polyfem::mesh::Mesh.
Definition at line 769 of file NCMesh2D.cpp.
References edges, n_edges(), and valid_to_all_edge().
set_point()
void polyfem::mesh::NCMesh2D::set_point (const int global_index, const RowVectorNd & p) override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 682 of file NCMesh2D.cpp.
References valid_to_all_vertex(), and vertices.
switch_edge()
Navigation::Index polyfem::mesh::NCMesh2D::switch_edge (Navigation::Index idx) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 614 of file NCMesh2D.cpp.
References all_to_valid_edge(), polyfem::mesh::Navigation::Index::edge, edges, elements, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, polyfem::mesh::find(), valid_to_all_elem(), and polyfem::mesh::Navigation::Index::vertex.
Referenced by face_node().
switch_face()
Navigation::Index polyfem::mesh::NCMesh2D::switch_face (Navigation::Index idx) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 637 of file NCMesh2D.cpp.
References polyfem::mesh::Navigation::Index::edge, edges, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, valid_to_all_edge(), valid_to_all_elem(), and polyfem::mesh::Navigation::Index::vertex.
switch_vertex()
Navigation::Index polyfem::mesh::NCMesh2D::switch_vertex (Navigation::Index idx) const override virtual
Implements polyfem::mesh::Mesh2D.
Definition at line 590 of file NCMesh2D.cpp.
References all_to_valid_vertex(), polyfem::mesh::Navigation::Index::edge, edges, elements, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, valid_to_all_edge(), valid_to_all_elem(), valid_to_all_vertex(), and polyfem::mesh::Navigation::Index::vertex.
Referenced by edge_node(), and face_node().
traverse_edge()
void polyfem::mesh::NCMesh2D::traverse_edge (Eigen::Vector2i v, double p1, double p2, int depth, std::vector< follower_edge > & list) const protected
Definition at line 492 of file NCMesh2D.cpp.
References edges, find_edge(), find_vertex(), and traverse_edge().
Referenced by build_edge_follower_chain(), and traverse_edge().
triangulate_faces()
void polyfem::mesh::NCMesh2D::triangulate_faces (Eigen::MatrixXi & tris, Eigen::MatrixXd & pts, std::vector< int > & ranges) const override virtual
generate a triangular representation of every face
Parameters
[out] tris triangles connectivity
[out] pts triangles vertices
[out] ranges connection to original faces
Implements polyfem::mesh::Mesh.
Definition at line 695 of file NCMesh2D.cpp.
References elasticity_rhs::f, face_vertex(), n_face_vertices(), n_faces(), n_vertices(), and point().
update_elements_tag()
void polyfem::mesh::NCMesh2D::update_elements_tag () override virtual
Update elements types.
Reimplemented from polyfem::mesh::Mesh.
Definition at line 677 of file NCMesh2D.cpp.
References polyfem::mesh::Mesh::elements_tag_, n_faces(), and polyfem::mesh::Simplex.
valid_to_all_edge()
int polyfem::mesh::NCMesh2D::valid_to_all_edge (const int id) const inline protected
Definition at line 329 of file NCMesh2D.hpp.
References index_prepared, and valid_to_all_edgeMap.
Referenced by compute_boundary_ids(), edge_vertex(), face_neighbor(), get_boundary_id(), is_boundary_edge(), leader_edge_of_edge(), n_face_neighbors(), n_follower_edges(), set_boundary_ids(), switch_face(), and switch_vertex().
valid_to_all_elem()
int polyfem::mesh::NCMesh2D::valid_to_all_elem (const int id) const inline protected
Definition at line 342 of file NCMesh2D.hpp.
References index_prepared, and valid_to_all_elemMap.
Referenced by cell_vertex(), compute_body_ids(), face_edge(), face_ref_level(), face_vertex(), get_body_id(), get_index_from_face(), refine_elements(), set_body_ids(), switch_edge(), switch_face(), and switch_vertex().
valid_to_all_vertex()
int polyfem::mesh::NCMesh2D::valid_to_all_vertex (const int id) const inline protected
Definition at line 316 of file NCMesh2D.hpp.
References index_prepared, and valid_to_all_vertexMap.
Referenced by is_boundary_vertex(), leader_edge_of_vertex(), point(), set_point(), and switch_vertex().
Member Data Documentation
adj_prepared
bool polyfem::mesh::NCMesh2D::adj_prepared = false protected
Definition at line 379 of file NCMesh2D.hpp.
Referenced by add_element(), build_from_matrices(), coarsen_element(), leader_edge_of_edge(), leader_edge_of_vertex(), n_follower_edges(), prepare_mesh(), and refine_element().
all_to_valid_edgeMap
std::vector<int> polyfem::mesh::NCMesh2D::all_to_valid_edgeMap protected
Definition at line 390 of file NCMesh2D.hpp.
Referenced by all_to_valid_edge(), and build_index_mapping().
all_to_valid_elemMap
std::vector<int> polyfem::mesh::NCMesh2D::all_to_valid_elemMap protected
Definition at line 388 of file NCMesh2D.hpp.
Referenced by all_to_valid_elem(), and build_index_mapping().
all_to_valid_vertexMap
std::vector<int> polyfem::mesh::NCMesh2D::all_to_valid_vertexMap protected
Definition at line 389 of file NCMesh2D.hpp.
Referenced by all_to_valid_vertex(), and build_index_mapping().
edgeMap
std::unordered_map<Eigen::Vector2i, int, ArrayHasher2D> polyfem::mesh::NCMesh2D::edgeMap protected
Definition at line 386 of file NCMesh2D.hpp.
Referenced by build_from_matrices(), find_edge(), and get_edge().
edges
std::vector<ncBoundary> polyfem::mesh::NCMesh2D::edges protected
Definition at line 383 of file NCMesh2D.hpp.
Referenced by add_element(), build_edge_follower_chain(), build_element_vertex_adjacency(), build_from_matrices(), build_index_mapping(), coarsen_element(), compute_boundary_ids(), edge_vertex(), face_edge(), face_neighbor(), get_boundary_id(), get_edge(), is_boundary_edge(), leader_edge_of_edge(), mark_boundary(), n_edges(), n_face_neighbors(), n_follower_edges(), refine_element(), set_boundary_ids(), switch_edge(), switch_face(), switch_vertex(), and traverse_edge().
elementAdj
Eigen::SparseMatrix<bool, Eigen::RowMajor> polyfem::mesh::NCMesh2D::elementAdj protected
Definition at line 395 of file NCMesh2D.hpp.
elements
std::vector<ncElem> polyfem::mesh::NCMesh2D::elements protected
Definition at line 381 of file NCMesh2D.hpp.
Referenced by add_element(), build_edge_follower_chain(), build_element_vertex_adjacency(), build_from_matrices(), build_index_mapping(), cell_vertex(), coarsen_element(), compute_body_ids(), face_edge(), face_ref_level(), face_vertex(), get_body_id(), get_index_from_face(), refine(), refine_element(), set_body_ids(), switch_edge(), and switch_vertex().
index_prepared
bool polyfem::mesh::NCMesh2D::index_prepared = false protected
Definition at line 378 of file NCMesh2D.hpp.
Referenced by add_element(), all_to_valid_edge(), all_to_valid_elem(), all_to_valid_vertex(), build_from_matrices(), build_index_mapping(), coarsen_element(), is_boundary_element(), point(), refine_element(), valid_to_all_edge(), valid_to_all_elem(), and valid_to_all_vertex().
midpointMap
std::unordered_map<Eigen::Vector2i, int, ArrayHasher2D> polyfem::mesh::NCMesh2D::midpointMap protected
Definition at line 385 of file NCMesh2D.hpp.
Referenced by build_from_matrices(), find_vertex(), and get_vertex().
n_elements
int polyfem::mesh::NCMesh2D::n_elements = 0 protected
Definition at line 376 of file NCMesh2D.hpp.
Referenced by add_element(), build_from_matrices(), build_index_mapping(), coarsen_element(), load(), n_faces(), and refine_element().
refineHistory
std::vector<int> polyfem::mesh::NCMesh2D::refineHistory protected
Definition at line 392 of file NCMesh2D.hpp.
Referenced by build_from_matrices(), coarsen_element(), and refine_element().
valid_to_all_edgeMap
std::vector<int> polyfem::mesh::NCMesh2D::valid_to_all_edgeMap protected
Definition at line 390 of file NCMesh2D.hpp.
Referenced by build_index_mapping(), and valid_to_all_edge().
valid_to_all_elemMap
std::vector<int> polyfem::mesh::NCMesh2D::valid_to_all_elemMap protected
Definition at line 388 of file NCMesh2D.hpp.
Referenced by build_index_mapping(), and valid_to_all_elem().
valid_to_all_vertexMap
std::vector<int> polyfem::mesh::NCMesh2D::valid_to_all_vertexMap protected
Definition at line 389 of file NCMesh2D.hpp.
Referenced by build_index_mapping(), and valid_to_all_vertex().
vertices
std::vector<ncVert> polyfem::mesh::NCMesh2D::vertices protected
Definition at line 382 of file NCMesh2D.hpp.
Referenced by add_element(), build_element_vertex_adjacency(), build_from_matrices(), build_index_mapping(), cell_vertex(), coarsen_element(), edge_vertex(), face_vertex(), get_vertex(), is_boundary_vertex(), leader_edge_of_vertex(), load(), mark_boundary(), n_vertices(), point(), refine_element(), and set_point().
The documentation for this class was generated from the following files:
src/polyfem/mesh/mesh2D/NCMesh2D.hpp
src/polyfem/mesh/mesh2D/NCMesh2D.cpp