PolyFEM: polyfem::mesh::CMesh3D Class Reference
polyfem::mesh::CMesh3D Class Reference
#include <CMesh3D.hpp>
Public Member Functions
CMesh3D ()=default
virtual ~CMesh3D ()=default
CMesh3D (CMesh3D &&)=default
CMesh3D & operator= (CMesh3D &&)=default
CMesh3D (const CMesh3D &)=default
CMesh3D & operator= (const CMesh3D &)=default
bool is_conforming () const override
if the mesh is conforming
void refine (const int n_refinement, const double t) override
refine the mesh
int n_cells () const override
number of cells
int n_faces () const override
number of faces
int n_edges () const override
number of edges
int n_vertices () const override
number of vertices
int n_face_vertices (const int f_id) const override
number of vertices of a face
int n_cell_vertices (const int c_id) const override
int n_cell_edges (const int c_id) const override
int n_cell_faces (const int c_id) const override
int cell_vertex (const int c_id, const int lv_id) const override
id of the vertex of a cell
int cell_face (const int c_id, const int lf_id) const override
int cell_edge (const int c_id, const int le_id) const override
int face_vertex (const int f_id, const int lv_id) const override
id of the face vertex
int edge_vertex (const int e_id, const int lv_id) const override
id of the edge vertex
void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const override
constructs a box around every element (3d cell, 2d face)
void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const override
constructs barycentric coodiantes for a point p.
bool is_boundary_vertex (const int vertex_global_id) const override
is vertex boundary
bool is_boundary_edge (const int edge_global_id) const override
is edge boundary
bool is_boundary_face (const int face_global_id) const override
is face boundary
bool is_boundary_element (const int element_global_id) const override
is cell boundary
bool build_from_matrices (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F) override
build a mesh from matrices
void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes) override
attach high order nodes
void normalize () override
normalize the mesh
double quad_area (const int gid) const override
area of a quad face of an hex mesh
void compute_elements_tag () override
compute element types, see ElementType
RowVectorNd kernel (const int cell_id) const override
RowVectorNd point (const int vertex_id) const override
point coordinates
RowVectorNd edge_barycenter (const int e) const override
edge barycenter
RowVectorNd face_barycenter (const int f) const override
face barycenter
RowVectorNd cell_barycenter (const int c) const override
cell barycenter
void bounding_box (RowVectorNd &min, RowVectorNd &max) const override
computes the bbox of the mesh
Navigation3D::Index get_index_from_element (int hi, int lf, int lv) const override
Navigation3D::Index get_index_from_element (int hi) const override
Navigation3D::Index get_index_from_element_edge (int hi, int v0, int v1) const override
Navigation3D::Index get_index_from_element_face (int hi, int v0, int v1, int v2) const override
std::vector< uint32_t > vertex_neighs (const int v_gid) const override
std::vector< uint32_t > edge_neighs (const int e_gid) const override
Navigation3D::Index switch_vertex (Navigation3D::Index idx) const override
Navigation3D::Index switch_edge (Navigation3D::Index idx) const override
Navigation3D::Index switch_face (Navigation3D::Index idx) const override
Navigation3D::Index switch_element (Navigation3D::Index idx) const override
Navigation3D::Index next_around_edge (Navigation3D::Index idx) const override
Navigation3D::Index next_around_face (Navigation3D::Index idx) const override
void get_vertex_elements_neighs (const int v_id, std::vector< int > &ids) const override
void get_edge_elements_neighs (const int e_id, std::vector< int > &ids) const override
void compute_boundary_ids (const double eps) override
computes the selection based on the bbx of the mesh.
void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker) override
computes boundary selections based on a function
void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker) override
computes boundary selections based on a function
void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker) override
computes boundary selections based on a function
void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const override
generate a triangular representation of every face
Mesh3DStorage & mesh_storge ()
Public Member Functions inherited from polyfem::mesh::Mesh3D
Mesh3D ()=default
virtual ~Mesh3D ()=default
Mesh3D (Mesh3D &&)=default
Mesh3D & operator= (Mesh3D &&)=default
Mesh3D (const Mesh3D &)=default
Mesh3D & operator= (const Mesh3D &)=default
bool is_volume () const override
checks if mesh is volume
virtual int n_cell_vertices (const int c_id) const =0
virtual int n_cell_edges (const int c_id) const =0
virtual int n_cell_faces (const int c_id) const =0
virtual int cell_face (const int c_id, const int lf_id) const =0
virtual int cell_edge (const int c_id, const int le_id) const =0
void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const override
constructs a box around every element (3d cell, 2d face)
void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const override
constructs barycentric coodiantes for a point p.
virtual RowVectorNd kernel (const int cell_id) const =0
double tri_area (const int gid) const override
area of a tri face of a tet mesh
RowVectorNd edge_node (const Navigation3D::Index &index, const int n_new_nodes, const int i) const
RowVectorNd face_node (const Navigation3D::Index &index, const int n_new_nodes, const int i, const int j) const
RowVectorNd cell_node (const Navigation3D::Index &index, const int n_new_nodes, const int i, const int j, const int k) const
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const override
Get all the edges.
void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const override
Get all the edges according to valid_elements selection.
virtual Navigation3D::Index get_index_from_element (int hi, int lf, int lv) const =0
virtual Navigation3D::Index get_index_from_element (int hi) const =0
virtual Navigation3D::Index get_index_from_element_edge (int hi, int v0, int v1) const =0
virtual Navigation3D::Index get_index_from_element_face (int hi, int v0, int v1, int v2) const =0
virtual std::vector< uint32_t > vertex_neighs (const int v_gid) const =0
virtual std::vector< uint32_t > edge_neighs (const int e_gid) const =0
virtual Navigation3D::Index switch_vertex (Navigation3D::Index idx) const =0
virtual Navigation3D::Index switch_edge (Navigation3D::Index idx) const =0
virtual Navigation3D::Index switch_face (Navigation3D::Index idx) const =0
virtual Navigation3D::Index switch_element (Navigation3D::Index idx) const =0
virtual Navigation3D::Index next_around_edge (Navigation3D::Index idx) const =0
virtual Navigation3D::Index next_around_face (Navigation3D::Index idx) const =0
void to_face_functions (std::array< std::function< Navigation3D::Index(Navigation3D::Index)>, 6 > &to_face) const
void to_vertex_functions (std::array< std::function< Navigation3D::Index(Navigation3D::Index)>, 8 > &to_vertex) const
void to_edge_functions (std::array< std::function< Navigation3D::Index(Navigation3D::Index)>, 12 > &to_edge) const
std::array< int, 8 > get_ordered_vertices_from_hex (const int element_index) const
virtual std::array< int, 4 > get_ordered_vertices_from_tet (const int element_index) const
virtual void get_vertex_elements_neighs (const int v_id, std::vector< int > &ids) const =0
virtual void get_edge_elements_neighs (const int e_id, std::vector< int > &ids) const =0
void compute_element_barycenters (Eigen::MatrixXd &barycenters) const override
utility for 2d/3d.
Public Member Functions inherited from polyfem::mesh::Mesh
virtual ~Mesh ()=default
Destroy the Mesh object.
Mesh (Mesh &&)=default
Construct a new Mesh object.
Mesh & operator= (Mesh &&)=default
Copy constructor.
Mesh (const Mesh &)=default
Construct a new Mesh object.
Mesh & operator= (const Mesh &)=default
virtual void refine (const int n_refinement, const double t)=0
refine the mesh
virtual bool is_volume () const =0
checks if mesh is volume
int dimension () const
utily for dimension
virtual bool is_conforming () const =0
if the mesh is conforming
int n_elements () const
utitlity to return the number of elements, cells or faces in 3d and 2d
virtual int n_cells () const =0
number of cells
virtual int n_faces () const =0
number of faces
virtual int n_edges () const =0
number of edges
virtual int n_vertices () const =0
number of vertices
virtual int n_face_vertices (const int f_id) const =0
number of vertices of a face
virtual int face_vertex (const int f_id, const int lv_id) const =0
id of the face vertex
virtual int edge_vertex (const int e_id, const int lv_id) const =0
id of the edge vertex
virtual int cell_vertex (const int f_id, const int lv_id) const =0
id of the vertex of a cell
virtual bool is_boundary_vertex (const int vertex_global_id) const =0
is vertex boundary
virtual bool is_boundary_edge (const int edge_global_id) const =0
is edge boundary
virtual bool is_boundary_face (const int face_global_id) const =0
is face boundary
virtual bool is_boundary_element (const int element_global_id) const =0
is cell boundary
virtual void attach_higher_order_nodes (const Eigen::MatrixXd &V, const std::vector< std::vector< int > > &nodes)=0
attach high order nodes
const Eigen::MatrixXi & orders () const
order of each element
bool is_rational () const
check if curved mesh has rational polynomials elements
void set_is_rational (const bool in_is_rational)
Set the is rational object.
virtual void normalize ()=0
normalize the mesh
virtual void compute_elements_tag ()=0
compute element types, see ElementType
virtual void update_elements_tag ()
Update elements types.
virtual double edge_length (const int gid) const
edge length
virtual double quad_area (const int gid) const
area of a quad face of an hex mesh
virtual double tri_area (const int gid) const
area of a tri face of a tet mesh
virtual RowVectorNd point (const int global_index) const =0
point coordinates
virtual RowVectorNd edge_barycenter (const int e) const =0
edge barycenter
virtual RowVectorNd face_barycenter (const int f) const =0
face barycenter
virtual RowVectorNd cell_barycenter (const int c) const =0
cell barycenter
void edge_barycenters (Eigen::MatrixXd &barycenters) const
all edges barycenters
void face_barycenters (Eigen::MatrixXd &barycenters) const
all face barycenters
void cell_barycenters (Eigen::MatrixXd &barycenters) const
all cells barycenters
virtual void compute_element_barycenters (Eigen::MatrixXd &barycenters) const =0
utility for 2d/3d.
virtual void elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > &boxes) const =0
constructs a box around every element (3d cell, 2d face)
virtual void barycentric_coords (const RowVectorNd &p, const int el_id, Eigen::MatrixXd &coord) const =0
constructs barycentric coodiantes for a point p.
virtual void bounding_box (RowVectorNd &min, RowVectorNd &max) const =0
computes the bbox of the mesh
bool is_spline_compatible (const int el_id) const
checks if element is spline compatible
bool is_cube (const int el_id) const
checks if element is cube compatible
bool is_polytope (const int el_id) const
checks if element is polygon compatible
bool is_simplex (const int el_id) const
checks if element is simples compatible
const std::vector< ElementType > & elements_tag () const
Returns the elements types.
void set_tag (const int el, const ElementType type)
changes the element type
virtual void load_boundary_ids (const std::string &path)
loads the boundary selections for a file
virtual void compute_boundary_ids (const double eps)=0
computes the selection based on the bbx of the mesh.
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> &marker)=0
computes boundary selections based on a function
virtual void compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> &marker)=0
computes boundary selections based on a function
virtual void set_boundary_ids (const std::vector< int > &boundary_ids)
Set the boundary selection from a vector.
virtual void set_body_ids (const std::vector< int > &body_ids)
Set the volume sections.
virtual void set_body_ids (const Eigen::VectorXi &body_ids)
Set the volume sections.
virtual int get_boundary_id (const int primitive) const
Get the boundary selection of an element (face in 3d, edge in 2d)
virtual int get_body_id (const int primitive) const
Get the volume selection of an element (cell in 3d, face in 2d)
bool has_boundary_ids () const
checks if surface selections are available
virtual bool has_body_ids () const
checks if volumes selections are available
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1) const =0
Get all the edges.
virtual void get_edges (Eigen::MatrixXd &p0, Eigen::MatrixXd &p1, const std::vector< bool > &valid_elements) const =0
Get all the edges according to valid_elements selection.
virtual void triangulate_faces (Eigen::MatrixXi &tris, Eigen::MatrixXd &pts, std::vector< int > &ranges) const =0
generate a triangular representation of every face
const std::vector< double > & cell_weights (const int cell_index) const
weights for rational polynomial meshes
void set_cell_weights (const std::vector< std::vector< double > > &in_cell_weights)
Set the cell weights for rational polynomial meshes.
virtual void prepare_mesh ()
method used to finalize the mesh.
bool has_poly () const
checks if the mesh has polytopes
bool is_linear ()
check if the mesh is linear
std::vector< std::pair< int, int > > edges () const
list of sorted edges.
std::vector< std::vector< int > > faces () const
list of sorted faces.
std::unordered_map< std::pair< int, int >, size_t, polyfem::utils::HashPair > edges_to_ids () const
map from edge (pair of v id) to the id of the edge
std::unordered_map< std::vector< int >, size_t, polyfem::utils::HashVector > faces_to_ids () const
map from face (tuple of v id) to the id of the face
const Eigen::VectorXi & in_ordered_vertices () const
Order of the input vertices.
const Eigen::MatrixXi & in_ordered_edges () const
Order of the input edges.
const Eigen::MatrixXi & in_ordered_faces () const
Order of the input edges.
Static Public Member Functions
static void geomesh_2_mesh_storage (const GEO::Mesh &gm, Mesh3DStorage &m)
Static Public Member Functions inherited from polyfem::mesh::Mesh
static std::unique_ptr< Mesh > create (const std::string &path, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (GEO::Mesh &M, const bool non_conforming=false)
factory to build the proper mesh
static std::unique_ptr< Mesh > create (const Eigen::MatrixXd &vertices, const Eigen::MatrixXi &cells, const bool non_conforming=false)
factory to build the proper mesh
Protected Member Functions
bool load (const std::string &path) override
loads a mesh from the path
bool load (const GEO::Mesh &M) override
loads a mesh from a geo mesh
Protected Member Functions inherited from polyfem::mesh::Mesh
Mesh ()=default
Construct a new Mesh object.
virtual bool load (const std::string &path)=0
loads a mesh from the path
virtual bool load (const GEO::Mesh &M)=0
loads a mesh from a geo mesh
Private Attributes
Mesh3DStorage mesh_
Additional Inherited Members
Protected Attributes inherited from polyfem::mesh::Mesh
std::vector< ElementType > elements_tag_
list of element types
std::vector< int > boundary_ids_
list of surface labels
std::vector< int > body_ids_
list of volume labels
Eigen::MatrixXi orders_
list of geometry orders, one per cell
bool is_rational_ = false
stores if the mesh is rational
std::vector< EdgeNodes > edge_nodes_
high-oder nodes associates to edges
std::vector< FaceNodes > face_nodes_
high-oder nodes associates to faces
std::vector< CellNodes > cell_nodes_
high-oder nodes associates to cells
std::vector< std::vector< double > > cell_weights_
weights associates to cells for rational polynomail meshes
Eigen::VectorXi in_ordered_vertices_
Order of the input vertices.
Eigen::MatrixXi in_ordered_edges_
Order of the input edges.
Eigen::MatrixXi in_ordered_faces_
Order of the input faces, TODO: change to std::vector of Eigen::Vector.
Detailed Description
Definition at line 18 of file CMesh3D.hpp.
Constructor & Destructor Documentation
CMesh3D() [1/3]
polyfem::mesh::CMesh3D::CMesh3D () default
~CMesh3D()
virtual polyfem::mesh::CMesh3D::~CMesh3D () virtual default
CMesh3D() [2/3]
polyfem::mesh::CMesh3D::CMesh3D (CMesh3D &&) default
CMesh3D() [3/3]
polyfem::mesh::CMesh3D::CMesh3D (const CMesh3D &) default
Member Function Documentation
attach_higher_order_nodes()
void polyfem::mesh::CMesh3D::attach_higher_order_nodes (const Eigen::MatrixXd & V, const std::vector< std::vector< int > > & nodes) override virtual
attach high order nodes
Parameters
[in] V nodes
[in] nodes list of nodes per element
Implements polyfem::mesh::Mesh.
Definition at line 427 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::cell_nodes_, cell_vertex(), polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Navigation3D::Index::element, elasticity_rhs::f, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Mesh::face_nodes_, face_vertex(), polyfem::mesh::Mesh::faces(), get_index_from_element(), p_bases::indices, n_cells(), n_edges(), n_faces(), next_around_face(), p_bases::nodes, polyfem::mesh::Mesh::orders_, switch_edge(), switch_face(), switch_vertex(), p_bases::tmp, and polyfem::mesh::Navigation3D::Index::vertex.
barycentric_coords()
void polyfem::mesh::CMesh3D::barycentric_coords (const RowVectorNd & p, const int el_id, Eigen::MatrixXd & coord) const override virtual
constructs barycentric coodiantes for a point p.
WARNING works only for simplices
Parameters
[in] p query point
[in] el_id element id
[out] coord matrix containing the barycentric coodinates
Implements polyfem::mesh::Mesh.
Definition at line 1548 of file CMesh3D.cpp.
References polyfem::mesh::Mesh3D::get_ordered_vertices_from_tet(), p_bases::indices, polyfem::mesh::Mesh::is_simplex(), and point().
bounding_box()
void polyfem::mesh::CMesh3D::bounding_box (RowVectorNd & min, RowVectorNd & max) const override virtual
computes the bbox of the mesh
Parameters
[out] min min coodiante
[out] max max coodiante
Implements polyfem::mesh::Mesh.
Definition at line 919 of file CMesh3D.cpp.
Referenced by compute_boundary_ids(), and normalize().
build_from_matrices()
bool polyfem::mesh::CMesh3D::build_from_matrices (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F) override virtual
build a mesh from matrices
Parameters
[in] V vertices
[in] F connectivity
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 384 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::cell_nodes_, polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Mesh::face_nodes_, load(), and eigs::M.
cell_barycenter()
RowVectorNd polyfem::mesh::CMesh3D::cell_barycenter (const int c) const override virtual
cell barycenter
Parameters
[in] c global cell index
Returns
cell barycenter
Implements polyfem::mesh::Mesh.
Definition at line 1471 of file CMesh3D.cpp.
References polyfem::mesh::Mesh3DStorage::elements, mesh_, n_cell_vertices(), n_vertices(), point(), and p_bases::vertices.
Referenced by compute_body_ids(), and load().
cell_edge()
int polyfem::mesh::CMesh3D::cell_edge (const int c_id, const int le_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 43 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
cell_face()
int polyfem::mesh::CMesh3D::cell_face (const int c_id, const int lf_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 42 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
cell_vertex()
int polyfem::mesh::CMesh3D::cell_vertex (const int f_id, const int lv_id) const inline override virtual
id of the vertex of a cell
Parameters
[in] f_id global cell id
[in] lv_id local vertex id
Returns
vertex id
Implements polyfem::mesh::Mesh.
Definition at line 41 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
Referenced by attach_higher_order_nodes().
compute_body_ids()
void polyfem::mesh::CMesh3D::compute_body_ids (const std::function< int(const size_t, const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id and barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 1202 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::body_ids_, cell_barycenter(), and polyfem::mesh::Mesh::n_elements().
compute_boundary_ids() [1/5]
void polyfem::mesh::CMesh3D::compute_boundary_ids (const double eps) override virtual
computes the selection based on the bbx of the mesh.
Left gets 1, bottom 2, right 3, top 4, front 5, back 6
Parameters
[in] eps tolerance for proximity
Implements polyfem::mesh::Mesh.
Definition at line 1169 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, bounding_box(), elasticity_rhs::f, face_barycenter(), is_boundary_face(), and n_faces().
compute_boundary_ids() [2/5]
void polyfem::mesh::CMesh3D::compute_boundary_ids (const std::function< int(const RowVectorNd &)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 1114 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_barycenter(), is_boundary_face(), and n_faces().
compute_boundary_ids() [3/5]
void polyfem::mesh::CMesh3D::compute_boundary_ids (const std::function< int(const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the barycenter and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 1129 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_barycenter(), is_boundary_face(), and n_faces().
compute_boundary_ids() [4/5]
void polyfem::mesh::CMesh3D::compute_boundary_ids (const std::function< int(const size_t, const RowVectorNd &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the id, barycenter, and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 1141 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_barycenter(), is_boundary_face(), and n_faces().
compute_boundary_ids() [5/5]
void polyfem::mesh::CMesh3D::compute_boundary_ids (const std::function< int(const std::vector< int > &, bool)> & marker) override virtual
computes boundary selections based on a function
Parameters
[in] marker lambda function that takes the list of vertices and true/false if the element is on the boundary and returns an integer
Implements polyfem::mesh::Mesh.
Definition at line 1153 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::boundary_ids_, elasticity_rhs::f, face_vertex(), is_boundary_face(), n_face_vertices(), and n_faces().
compute_elements_tag()
void polyfem::mesh::CMesh3D::compute_elements_tag () override virtual
compute element types, see ElementType
Implements polyfem::mesh::Mesh.
Definition at line 1227 of file CMesh3D.cpp.
References polyfem::mesh::BoundaryPolytope, polyfem::mesh::Mesh3DStorage::edges, polyfem::mesh::Mesh3DStorage::elements, polyfem::mesh::Mesh::elements_tag_, elasticity_rhs::f, polyfem::mesh::Mesh3DStorage::faces, polyfem::mesh::InterfaceCube, polyfem::mesh::InteriorPolytope, mesh_, polyfem::mesh::MultiSingularBoundaryCube, polyfem::mesh::MultiSingularInteriorCube, polyfem::mesh::RegularBoundaryCube, polyfem::mesh::RegularInteriorCube, polyfem::mesh::SimpleSingularBoundaryCube, polyfem::mesh::SimpleSingularInteriorCube, polyfem::mesh::Simplex, and polyfem::mesh::Mesh3DStorage::vertices.
Referenced by load(), and refine().
edge_barycenter()
RowVectorNd polyfem::mesh::CMesh3D::edge_barycenter (const int e) const override virtual
edge barycenter
Parameters
[in] e global edge index
Returns
edge barycenter
Implements polyfem::mesh::Mesh.
Definition at line 1450 of file CMesh3D.cpp.
References polyfem::mesh::Mesh3DStorage::edges, mesh_, and point().
edge_neighs()
std::vector< uint32_t > polyfem::mesh::CMesh3D::edge_neighs (const int e_gid) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 81 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::edges, and mesh_.
edge_vertex()
int polyfem::mesh::CMesh3D::edge_vertex (const int e_id, const int lv_id) const inline override virtual
id of the edge vertex
Parameters
[in] e_id global edge id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 45 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::edges, and mesh_.
elements_boxes()
void polyfem::mesh::CMesh3D::elements_boxes (std::vector< std::array< Eigen::Vector3d, 2 > > & boxes) const override virtual
constructs a box around every element (3d cell, 2d face)
Parameters
[out] boxes axis aligned bounding boxes
Implements polyfem::mesh::Mesh.
Definition at line 1526 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::n_elements().
face_barycenter()
RowVectorNd polyfem::mesh::CMesh3D::face_barycenter (const int f) const override virtual
face barycenter
Parameters
[in] f global face index
Returns
face barycenter
Implements polyfem::mesh::Mesh.
Definition at line 1457 of file CMesh3D.cpp.
References elasticity_rhs::f, polyfem::mesh::Mesh3DStorage::faces, mesh_, n_face_vertices(), n_vertices(), point(), and p_bases::vertices.
Referenced by compute_boundary_ids().
face_vertex()
int polyfem::mesh::CMesh3D::face_vertex (const int f_id, const int lv_id) const inline override virtual
id of the face vertex
Parameters
[in] f_id global face id
[in] lv_id local vertex index
Returns
int id of the face vertex
Implements polyfem::mesh::Mesh.
Definition at line 44 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::faces, and mesh_.
Referenced by attach_higher_order_nodes(), and compute_boundary_ids().
geomesh_2_mesh_storage()
void polyfem::mesh::CMesh3D::geomesh_2_mesh_storage (const GEO::Mesh & gm, Mesh3DStorage & m) static
Definition at line 1485 of file CMesh3D.cpp.
References polyfem::mesh::MeshProcessing3D::build_connectivity(), polyfem::mesh::Mesh3DStorage::edges, elasticity_rhs::f, polyfem::mesh::Mesh3DStorage::faces, polyfem::mesh::HSur, polyfem::mesh::Vertex::id, polyfem::mesh::Mesh3DStorage::points, polyfem::mesh::Qua, polyfem::mesh::Tri, polyfem::mesh::Mesh3DStorage::type, polyfem::mesh::Vertex::v, and polyfem::mesh::Mesh3DStorage::vertices.
get_edge_elements_neighs()
void polyfem::mesh::CMesh3D::get_edge_elements_neighs (const int e_id, std::vector< int > & ids) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 98 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::edges, and mesh_.
get_index_from_element() [1/2]
Navigation3D::Index polyfem::mesh::CMesh3D::get_index_from_element (int hi) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 75 of file CMesh3D.hpp.
References polyfem::mesh::Navigation3D::get_index_from_element_face(), and mesh_.
get_index_from_element() [2/2]
Navigation3D::Index polyfem::mesh::CMesh3D::get_index_from_element (int hi, int lf, int lv) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 74 of file CMesh3D.hpp.
References polyfem::mesh::Navigation3D::get_index_from_element_face(), and mesh_.
Referenced by attach_higher_order_nodes().
get_index_from_element_edge()
Navigation3D::Index polyfem::mesh::CMesh3D::get_index_from_element_edge (int hi, int v0, int v1) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 77 of file CMesh3D.hpp.
References polyfem::mesh::Navigation3D::get_index_from_element_edge(), and mesh_.
get_index_from_element_face()
Navigation3D::Index polyfem::mesh::CMesh3D::get_index_from_element_face (int hi, int v0, int v1, int v2) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 78 of file CMesh3D.hpp.
References polyfem::mesh::Navigation3D::get_index_from_element_tri(), and mesh_.
get_vertex_elements_neighs()
void polyfem::mesh::CMesh3D::get_vertex_elements_neighs (const int v_id, std::vector< int > & ids) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 93 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Mesh3DStorage::vertices.
is_boundary_edge()
bool polyfem::mesh::CMesh3D::is_boundary_edge (const int edge_global_id) const inline override virtual
is edge boundary
Parameters
[in] edge_global_id global edge id
Returns
is edge boundary
Implements polyfem::mesh::Mesh.
Definition at line 51 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::edges, and mesh_.
is_boundary_element()
bool polyfem::mesh::CMesh3D::is_boundary_element (const int element_global_id) const override virtual
is cell boundary
Parameters
[in] element_global_id global cell id
Returns
is cell boundary
Implements polyfem::mesh::Mesh.
Definition at line 1093 of file CMesh3D.cpp.
References polyfem::mesh::Mesh3DStorage::elements, is_boundary_face(), is_boundary_vertex(), and mesh_.
is_boundary_face()
bool polyfem::mesh::CMesh3D::is_boundary_face (const int face_global_id) const inline override virtual
is face boundary
Parameters
[in] face_global_id global face id
Returns
is face boundary
Implements polyfem::mesh::Mesh.
Definition at line 52 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::faces, and mesh_.
Referenced by compute_boundary_ids(), and is_boundary_element().
is_boundary_vertex()
bool polyfem::mesh::CMesh3D::is_boundary_vertex (const int vertex_global_id) const inline override virtual
is vertex boundary
Parameters
[in] vertex_global_id global vertex id
Returns
is vertex boundary
Implements polyfem::mesh::Mesh.
Definition at line 50 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Mesh3DStorage::vertices.
Referenced by is_boundary_element().
is_conforming()
bool polyfem::mesh::CMesh3D::is_conforming () const inline override virtual
if the mesh is conforming
Returns
if the mesh is conforming
Implements polyfem::mesh::Mesh.
Definition at line 28 of file CMesh3D.hpp.
kernel()
RowVectorNd polyfem::mesh::CMesh3D::kernel (const int cell_id) const override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 1220 of file CMesh3D.cpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
load() [1/2]
bool polyfem::mesh::CMesh3D::load (const GEO::Mesh & M) override protected virtual
loads a mesh from a geo mesh
Parameters
[in] M geo mesh
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 172 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::cell_nodes_, compute_elements_tag(), polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Mesh3DStorage::elements, polyfem::mesh::Mesh::face_nodes_, polyfem::mesh::Mesh3DStorage::faces, polyfem::mesh::Element::fs, polyfem::mesh::Element::fs_flag, polyfem::mesh::Element::hex, polyfem::mesh::Hex, polyfem::mesh::Hyb, polyfem::mesh::Vertex::id, polyfem::mesh::Face::id, polyfem::mesh::Element::id, eigs::M, mesh_, polyfem::mesh::Mesh3DStorage::points, polyfem::mesh::Navigation3D::prepare_mesh(), polyfem::mesh::Tet, polyfem::mesh::Mesh3DStorage::type, polyfem::mesh::Element::v_in_Kernel, polyfem::mesh::Mesh3DStorage::vertices, polyfem::mesh::Face::vs, and polyfem::mesh::Element::vs.
load() [2/2]
bool polyfem::mesh::CMesh3D::load (const std::string & path) override protected virtual
loads a mesh from the path
Parameters
[in] path file location
Returns
if success
Implements polyfem::mesh::Mesh.
Definition at line 48 of file CMesh3D.cpp.
References cell_barycenter(), polyfem::mesh::Mesh::cell_nodes_, compute_elements_tag(), polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Mesh3DStorage::elements, polyfem::utils::StringUtils::endswith(), elasticity_rhs::f, polyfem::mesh::Mesh::face_nodes_, polyfem::mesh::Mesh3DStorage::faces, polyfem::mesh::find(), polyfem::mesh::Element::fs, polyfem::mesh::Element::fs_flag, polyfem::mesh::Vertex::id, polyfem::mesh::Face::id, polyfem::mesh::Element::id, load(), eigs::M, mesh_, n_cells(), eigs::path, polyfem::mesh::Mesh3DStorage::points, polyfem::mesh::Navigation3D::prepare_mesh(), p_bases::tmp, polyfem::mesh::Mesh3DStorage::vertices, polyfem::mesh::Face::vs, polyfem::mesh::Element::vs, x, y, and z.
Referenced by build_from_matrices(), and load().
mesh_storge()
Mesh3DStorage & polyfem::mesh::CMesh3D::mesh_storge () inline
Definition at line 114 of file CMesh3D.hpp.
References mesh_.
n_cell_edges()
int polyfem::mesh::CMesh3D::n_cell_edges (const int c_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 39 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
n_cell_faces()
int polyfem::mesh::CMesh3D::n_cell_faces (const int c_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 40 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
n_cell_vertices()
int polyfem::mesh::CMesh3D::n_cell_vertices (const int c_id) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 38 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
Referenced by cell_barycenter().
n_cells()
int polyfem::mesh::CMesh3D::n_cells () const inline override virtual
number of cells
Returns
number of cells
Implements polyfem::mesh::Mesh.
Definition at line 32 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::elements, and mesh_.
Referenced by attach_higher_order_nodes(), load(), and normalize().
n_edges()
int polyfem::mesh::CMesh3D::n_edges () const inline override virtual
number of edges
Returns
number of edges
Implements polyfem::mesh::Mesh.
Definition at line 34 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::edges, and mesh_.
Referenced by attach_higher_order_nodes().
n_face_vertices()
int polyfem::mesh::CMesh3D::n_face_vertices (const int f_id) const inline override virtual
number of vertices of a face
Parameters
[in] f_id global face id
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 37 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::faces, and mesh_.
Referenced by compute_boundary_ids(), face_barycenter(), quad_area(), and triangulate_faces().
n_faces()
int polyfem::mesh::CMesh3D::n_faces () const inline override virtual
number of faces
Returns
number of faces
Implements polyfem::mesh::Mesh.
Definition at line 33 of file CMesh3D.hpp.
References polyfem::mesh::Mesh3DStorage::faces, and mesh_.
Referenced by attach_higher_order_nodes(), compute_boundary_ids(), and triangulate_faces().
n_vertices()
int polyfem::mesh::CMesh3D::n_vertices () const inline override virtual
number of vertices
Returns
number of vertices
Implements polyfem::mesh::Mesh.
Definition at line 35 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Mesh3DStorage::points.
Referenced by cell_barycenter(), face_barycenter(), quad_area(), and triangulate_faces().
next_around_edge()
Navigation3D::Index polyfem::mesh::CMesh3D::next_around_edge (Navigation3D::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 90 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Navigation3D::next_around_3Dedge().
next_around_face()
Navigation3D::Index polyfem::mesh::CMesh3D::next_around_face (Navigation3D::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 91 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Navigation3D::next_around_2Dface().
Referenced by attach_higher_order_nodes().
normalize()
void polyfem::mesh::CMesh3D::normalize () override virtual
normalize the mesh
Implements polyfem::mesh::Mesh.
Definition at line 926 of file CMesh3D.cpp.
References bounding_box(), polyfem::mesh::Mesh::cell_nodes_, polyfem::mesh::Mesh::edge_nodes_, polyfem::mesh::Mesh3DStorage::elements, polyfem::mesh::Mesh::face_nodes_, polyfem::mesh::Mesh3D::get_edges(), polyfem::logger(), mesh_, n_cells(), polyfem::mesh::Mesh3DStorage::points, and val.
operator=() [1/2]
CMesh3D & polyfem::mesh::CMesh3D::operator= (CMesh3D &&) default
operator=() [2/2]
CMesh3D & polyfem::mesh::CMesh3D::operator= (const CMesh3D &) default
point()
RowVectorNd polyfem::mesh::CMesh3D::point (const int global_index) const override virtual
point coordinates
Parameters
[in] global_index global vertex index
Returns
RowVectorNd
Implements polyfem::mesh::Mesh.
Definition at line 1214 of file CMesh3D.cpp.
References mesh_, and polyfem::mesh::Mesh3DStorage::points.
Referenced by barycentric_coords(), cell_barycenter(), edge_barycenter(), face_barycenter(), quad_area(), and triangulate_faces().
quad_area()
double polyfem::mesh::CMesh3D::quad_area (const int gid) const override virtual
area of a quad face of an hex mesh
Parameters
[in] gid global face id
Returns
face area
Reimplemented from polyfem::mesh::Mesh.
Definition at line 1429 of file CMesh3D.cpp.
References polyfem::mesh::Mesh3DStorage::faces, mesh_, n_face_vertices(), n_vertices(), point(), and p_bases::vertices.
refine()
void polyfem::mesh::CMesh3D::refine (const int n_refinement, const double t) override virtual
refine the mesh
Parameters
[in] n_refinement number of refinements
[in] t position of the refinement location (0.5 for standard refinement)
Implements polyfem::mesh::Mesh.
Definition at line 18 of file CMesh3D.cpp.
References polyfem::mesh::BoundaryPolytope, compute_elements_tag(), polyfem::mesh::Mesh3DStorage::elements, polyfem::mesh::Mesh::elements_tag(), polyfem::mesh::InteriorPolytope, mesh_, polyfem::mesh::Mesh::orders_, polyfem::mesh::Navigation3D::prepare_mesh(), polyfem::mesh::MeshProcessing3D::refine_catmul_clark_polar(), polyfem::mesh::MeshProcessing3D::refine_red_refinement_tet(), polyfem::mesh::Tet, and polyfem::mesh::Mesh3DStorage::type.
switch_edge()
Navigation3D::Index polyfem::mesh::CMesh3D::switch_edge (Navigation3D::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 85 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Navigation3D::switch_edge().
Referenced by attach_higher_order_nodes().
switch_element()
Navigation3D::Index polyfem::mesh::CMesh3D::switch_element (Navigation3D::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 87 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Navigation3D::switch_element().
switch_face()
Navigation3D::Index polyfem::mesh::CMesh3D::switch_face (Navigation3D::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 86 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Navigation3D::switch_face().
Referenced by attach_higher_order_nodes().
switch_vertex()
Navigation3D::Index polyfem::mesh::CMesh3D::switch_vertex (Navigation3D::Index idx) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 84 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Navigation3D::switch_vertex().
Referenced by attach_higher_order_nodes().
triangulate_faces()
void polyfem::mesh::CMesh3D::triangulate_faces (Eigen::MatrixXi & tris, Eigen::MatrixXd & pts, std::vector< int > & ranges) const override virtual
generate a triangular representation of every face
Parameters
[out] tris triangles connectivity
[out] pts triangles vertices
[out] ranges connection to original faces
Implements polyfem::mesh::Mesh.
Definition at line 986 of file CMesh3D.cpp.
References polyfem::mesh::Mesh::cell_barycenters(), polyfem::mesh::Mesh3DStorage::elements, elasticity_rhs::f, polyfem::mesh::Mesh::face_barycenters(), polyfem::mesh::Mesh3DStorage::faces, polyfem::mesh::Element::fs, mesh_, n_face_vertices(), n_faces(), n_vertices(), point(), polyfem::mesh::Mesh3DStorage::points, and polyfem::mesh::Element::vs.
vertex_neighs()
std::vector< uint32_t > polyfem::mesh::CMesh3D::vertex_neighs (const int v_gid) const inline override virtual
Implements polyfem::mesh::Mesh3D.
Definition at line 80 of file CMesh3D.hpp.
References mesh_, and polyfem::mesh::Mesh3DStorage::vertices.
Member Data Documentation
mesh_
Mesh3DStorage polyfem::mesh::CMesh3D::mesh_ private
Definition at line 126 of file CMesh3D.hpp.
Referenced by cell_barycenter(), cell_edge(), cell_face(), cell_vertex(), compute_elements_tag(), edge_barycenter(), edge_neighs(), edge_vertex(), face_barycenter(), face_vertex(), get_edge_elements_neighs(), get_index_from_element(), get_index_from_element_edge(), get_index_from_element_face(), get_vertex_elements_neighs(), is_boundary_edge(), is_boundary_element(), is_boundary_face(), is_boundary_vertex(), kernel(), load(), mesh_storge(), n_cell_edges(), n_cell_faces(), n_cell_vertices(), n_cells(), n_edges(), n_face_vertices(), n_faces(), n_vertices(), next_around_edge(), next_around_face(), normalize(), point(), quad_area(), refine(), switch_edge(), switch_element(), switch_face(), switch_vertex(), triangulate_faces(), and vertex_neighs().
The documentation for this class was generated from the following files:
src/polyfem/mesh/mesh3D/CMesh3D.hpp
src/polyfem/mesh/mesh3D/CMesh3D.cpp