coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 75%
        threshold: 5%
        only_pulls: true
ignore:
  - "tests"  # ignore folders and all its contents
  - "src/polyfem/problem"