var hierarchy =
[
    [ "nlohmann::adl_serializer< RowVector< T, dim, max_dim > >", "structnlohmann_1_1adl__serializer_3_01_row_vector_3_01_t_00_01dim_00_01max__dim_01_4_01_4.html", null ],
    [ "nlohmann::adl_serializer< Vector< T, dim, max_dim > >", "structnlohmann_1_1adl__serializer_3_01_vector_3_01_t_00_01dim_00_01max__dim_01_4_01_4.html", null ],
    [ "polyfem::mesh::NCMesh2D::ArrayHasher2D", "structpolyfem_1_1mesh_1_1_n_c_mesh2_d_1_1_array_hasher2_d.html", null ],
    [ "polyfem::mesh::NCMesh3D::ArrayHasher2D", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1_array_hasher2_d.html", null ],
    [ "polyfem::mesh::NCMesh3D::ArrayHasher3D", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1_array_hasher3_d.html", null ],
    [ "polyfem::assembler::Assembler< LocalAssembler >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::BilaplacianAux >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::BilaplacianMain >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::Helmholtz >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::HookeLinearElasticity >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::IncompressibleLinearElasticityDispacement >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::IncompressibleLinearElasticityPressure >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::Laplacian >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::LinearElasticity >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::StokesPressure >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::Assembler< polyfem::assembler::StokesVelocity >", "classpolyfem_1_1assembler_1_1_assembler.html", null ],
    [ "polyfem::assembler::AssemblerUtils", "classpolyfem_1_1assembler_1_1_assembler_utils.html", null ],
    [ "polyfem::assembler::AssemblyValsCache", "classpolyfem_1_1assembler_1_1_assembly_vals_cache.html", null ],
    [ "polyfem::assembler::AssemblyValues", "classpolyfem_1_1assembler_1_1_assembly_values.html", null ],
    [ "polyfem::AutoDiffAllocator< T >", "classpolyfem_1_1_auto_diff_allocator.html", null ],
    [ "polyfem::AutoDiffAllocator< double >", "classpolyfem_1_1_auto_diff_allocator_3_01double_01_4.html", null ],
    [ "polyfem::utils::base64Layer", "classpolyfem_1_1utils_1_1base64_layer.html", null ],
    [ "polyfem::basis::Basis", "classpolyfem_1_1basis_1_1_basis.html", null ],
    [ "polyfem::problem::PointBasedTensorProblem::BCValue", "classpolyfem_1_1problem_1_1_point_based_tensor_problem_1_1_b_c_value.html", null ],
    [ "polyfem::assembler::BilaplacianAux", "classpolyfem_1_1assembler_1_1_bilaplacian_aux.html", null ],
    [ "polyfem::assembler::BilaplacianMain", "classpolyfem_1_1assembler_1_1_bilaplacian_main.html", null ],
    [ "polyfem::assembler::BilaplacianMixed", "classpolyfem_1_1assembler_1_1_bilaplacian_mixed.html", null ],
    [ "polyfem::utils::BoundarySampler", "classpolyfem_1_1utils_1_1_boundary_sampler.html", null ],
    [ "polyfem::mesh::Mesh::CellNodes", "classpolyfem_1_1mesh_1_1_mesh_1_1_cell_nodes.html", null ],
    [ "polyfem::Density", "classpolyfem_1_1_density.html", null ],
    [ "DiffScalarBase", "struct_diff_scalar_base.html", [
      [ "DScalar1< _Scalar, _Gradient >", "struct_d_scalar1.html", null ],
      [ "DScalar2< _Scalar, _Gradient, _Hessian >", "struct_d_scalar2.html", null ]
    ] ],
    [ "polyfem::mesh::Edge", "structpolyfem_1_1mesh_1_1_edge.html", null ],
    [ "polyfem::mesh::Mesh::EdgeNodes", "classpolyfem_1_1mesh_1_1_mesh_1_1_edge_nodes.html", null ],
    [ "polyfem::utils::EdgeSampler", "classpolyfem_1_1utils_1_1_edge_sampler.html", null ],
    [ "polyfem::ElasticityTensor", "classpolyfem_1_1_elasticity_tensor.html", null ],
    [ "polyfem::mesh::Element", "structpolyfem_1_1mesh_1_1_element.html", null ],
    [ "polyfem::assembler::ElementAssemblyValues", "classpolyfem_1_1assembler_1_1_element_assembly_values.html", null ],
    [ "polyfem::basis::ElementBases", "classpolyfem_1_1basis_1_1_element_bases.html", null ],
    [ "polyfem::utils::ExpressionValue", "classpolyfem_1_1utils_1_1_expression_value.html", null ],
    [ "polyfem::mesh::Face", "structpolyfem_1_1mesh_1_1_face.html", null ],
    [ "polyfem::mesh::Mesh::FaceNodes", "classpolyfem_1_1mesh_1_1_mesh_1_1_face_nodes.html", null ],
    [ "polyfem::basis::FEBasis2d", "classpolyfem_1_1basis_1_1_f_e_basis2d.html", null ],
    [ "polyfem::basis::FEBasis3d", "classpolyfem_1_1basis_1_1_f_e_basis3d.html", null ],
    [ "polyfem::utils::FEBioReader", "classpolyfem_1_1utils_1_1_f_e_bio_reader.html", null ],
    [ "polyfem::mesh::NCMesh2D::follower_edge", "structpolyfem_1_1mesh_1_1_n_c_mesh2_d_1_1follower__edge.html", null ],
    [ "polyfem::mesh::NCMesh3D::follower_edge", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1follower__edge.html", null ],
    [ "polyfem::mesh::NCMesh2D::follower_face", "structpolyfem_1_1mesh_1_1_n_c_mesh2_d_1_1follower__face.html", null ],
    [ "polyfem::mesh::NCMesh3D::follower_face", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1follower__face.html", null ],
    [ "polyfem::renderer::FragmentAttributes", "classpolyfem_1_1renderer_1_1_fragment_attributes.html", null ],
    [ "polyfem::renderer::FrameBufferAttributes", "classpolyfem_1_1renderer_1_1_frame_buffer_attributes.html", null ],
    [ "std::hash< Eigen::Matrix< Scalar, Rows, Cols > >", "structstd_1_1hash_3_01_eigen_1_1_matrix_3_01_scalar_00_01_rows_00_01_cols_01_4_01_4.html", null ],
    [ "polyfem::utils::HashPair", "structpolyfem_1_1utils_1_1_hash_pair.html", null ],
    [ "polyfem::utils::HashVector", "structpolyfem_1_1utils_1_1_hash_vector.html", null ],
    [ "polyfem::assembler::Helmholtz", "classpolyfem_1_1assembler_1_1_helmholtz.html", null ],
    [ "polyfem::quadrature::HexQuadrature", "classpolyfem_1_1quadrature_1_1_hex_quadrature.html", null ],
    [ "polyfem::assembler::HookeLinearElasticity", "classpolyfem_1_1assembler_1_1_hooke_linear_elasticity.html", null ],
    [ "polyfem::time_integrator::ImplicitTimeIntegrator", "classpolyfem_1_1time__integrator_1_1_implicit_time_integrator.html", [
      [ "polyfem::time_integrator::BDF", "classpolyfem_1_1time__integrator_1_1_b_d_f.html", null ],
      [ "polyfem::time_integrator::ImplicitEuler", "classpolyfem_1_1time__integrator_1_1_implicit_euler.html", null ],
      [ "polyfem::time_integrator::ImplicitNewmark", "classpolyfem_1_1time__integrator_1_1_implicit_newmark.html", null ]
    ] ],
    [ "polyfem::assembler::IncompressibleLinearElasticityDispacement", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_dispacement.html", null ],
    [ "polyfem::assembler::IncompressibleLinearElasticityMixed", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_mixed.html", null ],
    [ "polyfem::assembler::IncompressibleLinearElasticityPressure", "classpolyfem_1_1assembler_1_1_incompressible_linear_elasticity_pressure.html", null ],
    [ "polyfem::mesh::Navigation3D::Index", "structpolyfem_1_1mesh_1_1_navigation3_d_1_1_index.html", null ],
    [ "polyfem::mesh::Navigation::Index", "structpolyfem_1_1mesh_1_1_navigation_1_1_index.html", null ],
    [ "polyfem::basis::InterfaceData", "structpolyfem_1_1basis_1_1_interface_data.html", null ],
    [ "polyfem::utils::InterpolatedFunction2d", "classpolyfem_1_1utils_1_1_interpolated_function2d.html", null ],
    [ "polyfem::assembler::Interpolation", "classpolyfem_1_1assembler_1_1_interpolation.html", [
      [ "polyfem::assembler::LinearInterpolation", "classpolyfem_1_1assembler_1_1_linear_interpolation.html", null ],
      [ "polyfem::assembler::LinearRamp", "classpolyfem_1_1assembler_1_1_linear_ramp.html", null ],
      [ "polyfem::assembler::NoInterpolation", "classpolyfem_1_1assembler_1_1_no_interpolation.html", null ]
    ] ],
    [ "ISolver", null, [
      [ "cppoptlib::NonlinearSolver< ProblemType >", "classcppoptlib_1_1_nonlinear_solver.html", [
        [ "cppoptlib::LBFGSSolver< ProblemType >", "classcppoptlib_1_1_l_b_f_g_s_solver.html", null ],
        [ "cppoptlib::SparseNewtonDescentSolver< ProblemType >", "classcppoptlib_1_1_sparse_newton_descent_solver.html", null ]
      ] ]
    ] ],
    [ "p_bases.Lagrange", "classp__bases_1_1_lagrange.html", null ],
    [ "q_bases.Lagrange", "classq__bases_1_1_lagrange.html", null ],
    [ "polyfem::LameParameters", "classpolyfem_1_1_lame_parameters.html", null ],
    [ "polyfem::assembler::Laplacian", "classpolyfem_1_1assembler_1_1_laplacian.html", null ],
    [ "polyfem::assembler::LinearElasticity", "classpolyfem_1_1assembler_1_1_linear_elasticity.html", null ],
    [ "polyfem::quadrature::LineQuadrature", "classpolyfem_1_1quadrature_1_1_line_quadrature.html", null ],
    [ "polyfem::solver::line_search::LineSearch< ProblemType >", "classpolyfem_1_1solver_1_1line__search_1_1_line_search.html", [
      [ "polyfem::solver::line_search::ArmijoLineSearch< ProblemType >", "classpolyfem_1_1solver_1_1line__search_1_1_armijo_line_search.html", null ],
      [ "polyfem::solver::line_search::BacktrackingLineSearch< ProblemType >", "classpolyfem_1_1solver_1_1line__search_1_1_backtracking_line_search.html", null ],
      [ "polyfem::solver::line_search::CppOptArmijoLineSearch< ProblemType >", "classpolyfem_1_1solver_1_1line__search_1_1_cpp_opt_armijo_line_search.html", null ],
      [ "polyfem::solver::line_search::MoreThuenteLineSearch< ProblemType >", "classpolyfem_1_1solver_1_1line__search_1_1_more_thuente_line_search.html", null ]
    ] ],
    [ "polyfem::basis::Local2Global", "classpolyfem_1_1basis_1_1_local2_global.html", null ],
    [ "polyfem::mesh::LocalBoundary", "classpolyfem_1_1mesh_1_1_local_boundary.html", null ],
    [ "polyfem::assembler::MassMatrixAssembler", "classpolyfem_1_1assembler_1_1_mass_matrix_assembler.html", null ],
    [ "polyfem::renderer::Material", "structpolyfem_1_1renderer_1_1_material.html", null ],
    [ "polyfem::mesh::Mesh", "classpolyfem_1_1mesh_1_1_mesh.html", [
      [ "polyfem::mesh::Mesh2D", "classpolyfem_1_1mesh_1_1_mesh2_d.html", [
        [ "polyfem::mesh::CMesh2D", "classpolyfem_1_1mesh_1_1_c_mesh2_d.html", null ],
        [ "polyfem::mesh::NCMesh2D", "classpolyfem_1_1mesh_1_1_n_c_mesh2_d.html", null ]
      ] ],
      [ "polyfem::mesh::Mesh3D", "classpolyfem_1_1mesh_1_1_mesh3_d.html", [
        [ "polyfem::mesh::CMesh3D", "classpolyfem_1_1mesh_1_1_c_mesh3_d.html", null ],
        [ "polyfem::mesh::NCMesh3D", "classpolyfem_1_1mesh_1_1_n_c_mesh3_d.html", null ]
      ] ]
    ] ],
    [ "polyfem::mesh::Mesh3DStorage", "structpolyfem_1_1mesh_1_1_mesh3_d_storage.html", null ],
    [ "polyfem::mesh::Mesh_Quality", "structpolyfem_1_1mesh_1_1_mesh___quality.html", null ],
    [ "polyfem::mesh::MeshNodes", "classpolyfem_1_1mesh_1_1_mesh_nodes.html", null ],
    [ "polyfem::assembler::MixedAssembler< LocalAssembler >", "classpolyfem_1_1assembler_1_1_mixed_assembler.html", null ],
    [ "polyfem::assembler::MixedAssembler< polyfem::assembler::BilaplacianMixed >", "classpolyfem_1_1assembler_1_1_mixed_assembler.html", null ],
    [ "polyfem::assembler::MixedAssembler< polyfem::assembler::IncompressibleLinearElasticityMixed >", "classpolyfem_1_1assembler_1_1_mixed_assembler.html", null ],
    [ "polyfem::assembler::MixedAssembler< polyfem::assembler::StokesMixed >", "classpolyfem_1_1assembler_1_1_mixed_assembler.html", null ],
    [ "polyfem::utils::MshReader", "classpolyfem_1_1utils_1_1_msh_reader.html", null ],
    [ "polyfem::assembler::MultiModel", "classpolyfem_1_1assembler_1_1_multi_model.html", null ],
    [ "polyfem::basis::MVPolygonalBasis2d", "classpolyfem_1_1basis_1_1_m_v_polygonal_basis2d.html", null ],
    [ "polyfem::solver::NavierStokesSolver", "classpolyfem_1_1solver_1_1_navier_stokes_solver.html", null ],
    [ "polyfem::assembler::NavierStokesVelocity< full_gradient >", "classpolyfem_1_1assembler_1_1_navier_stokes_velocity.html", null ],
    [ "polyfem::assembler::NavierStokesVelocity< false >", "classpolyfem_1_1assembler_1_1_navier_stokes_velocity.html", null ],
    [ "polyfem::assembler::NavierStokesVelocity< true >", "classpolyfem_1_1assembler_1_1_navier_stokes_velocity.html", null ],
    [ "polyfem::mesh::NCMesh2D::ncBoundary", "structpolyfem_1_1mesh_1_1_n_c_mesh2_d_1_1nc_boundary.html", null ],
    [ "polyfem::mesh::NCMesh3D::ncBoundary", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1nc_boundary.html", null ],
    [ "polyfem::mesh::NCMesh2D::ncElem", "structpolyfem_1_1mesh_1_1_n_c_mesh2_d_1_1nc_elem.html", null ],
    [ "polyfem::mesh::NCMesh3D::ncElem", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1nc_elem.html", null ],
    [ "polyfem::mesh::NCMesh2D::ncVert", "structpolyfem_1_1mesh_1_1_n_c_mesh2_d_1_1nc_vert.html", null ],
    [ "polyfem::mesh::NCMesh3D::ncVert", "structpolyfem_1_1mesh_1_1_n_c_mesh3_d_1_1nc_vert.html", null ],
    [ "polyfem::assembler::NeoHookeanElasticity", "classpolyfem_1_1assembler_1_1_neo_hookean_elasticity.html", null ],
    [ "polyfem::assembler::NLAssembler< LocalAssembler >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::assembler::NLAssembler< polyfem::assembler::LinearElasticity >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::assembler::NLAssembler< polyfem::assembler::MultiModel >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::assembler::NLAssembler< polyfem::assembler::NavierStokesVelocity< false > >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::assembler::NLAssembler< polyfem::assembler::NavierStokesVelocity< true > >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::assembler::NLAssembler< polyfem::assembler::NeoHookeanElasticity >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::assembler::NLAssembler< polyfem::assembler::SaintVenantElasticity >", "classpolyfem_1_1assembler_1_1_n_l_assembler.html", null ],
    [ "polyfem::problem::NodeValues", "classpolyfem_1_1problem_1_1_node_values.html", null ],
    [ "polyfem::utils::NThread", "classpolyfem_1_1utils_1_1_n_thread.html", null ],
    [ "polyfem::utils::OBJReader", "classpolyfem_1_1utils_1_1_o_b_j_reader.html", null ],
    [ "polyfem::utils::OBJWriter", "classpolyfem_1_1utils_1_1_o_b_j_writer.html", null ],
    [ "polyfem::mesh::Obstacle", "classpolyfem_1_1mesh_1_1_obstacle.html", null ],
    [ "polyfem::assembler::OgdenElasticity", "classpolyfem_1_1assembler_1_1_ogden_elasticity.html", null ],
    [ "polyfem::solver::OperatorSplittingSolver", "classpolyfem_1_1solver_1_1_operator_splitting_solver.html", null ],
    [ "polyfem::mesh::Obstacle::Plane", "classpolyfem_1_1mesh_1_1_obstacle_1_1_plane.html", null ],
    [ "polyfem::basis::PolygonalBasis2d", "classpolyfem_1_1basis_1_1_polygonal_basis2d.html", null ],
    [ "polyfem::basis::PolygonalBasis3d", "classpolyfem_1_1basis_1_1_polygonal_basis3d.html", null ],
    [ "polyfem::quadrature::PolygonQuadrature", "classpolyfem_1_1quadrature_1_1_polygon_quadrature.html", null ],
    [ "polyfem::quadrature::PolyhedronQuadrature", "classpolyfem_1_1quadrature_1_1_polyhedron_quadrature.html", null ],
    [ "cppoptlib::Problem", null, [
      [ "polyfem::solver::NLProblem", "classpolyfem_1_1solver_1_1_n_l_problem.html", [
        [ "polyfem::solver::ALNLProblem", "classpolyfem_1_1solver_1_1_a_l_n_l_problem.html", null ]
      ] ]
    ] ],
    [ "polyfem::assembler::Problem", "classpolyfem_1_1assembler_1_1_problem.html", [
      [ "polyfem::assembler::GenericScalarProblem", "classpolyfem_1_1assembler_1_1_generic_scalar_problem.html", null ],
      [ "polyfem::assembler::GenericTensorProblem", "classpolyfem_1_1assembler_1_1_generic_tensor_problem.html", null ],
      [ "polyfem::problem::Airfoil", "classpolyfem_1_1problem_1_1_airfoil.html", null ],
      [ "polyfem::problem::BilaplacianProblemWithSolution", "classpolyfem_1_1problem_1_1_bilaplacian_problem_with_solution.html", null ],
      [ "polyfem::problem::DoubleTorsionElasticProblem", "classpolyfem_1_1problem_1_1_double_torsion_elastic_problem.html", null ],
      [ "polyfem::problem::ElasticCantileverExact", "classpolyfem_1_1problem_1_1_elastic_cantilever_exact.html", null ],
      [ "polyfem::problem::ElasticProblem", "classpolyfem_1_1problem_1_1_elastic_problem.html", null ],
      [ "polyfem::problem::ElasticProblemZeroBC", "classpolyfem_1_1problem_1_1_elastic_problem_zero_b_c.html", null ],
      [ "polyfem::problem::GravityProblem", "classpolyfem_1_1problem_1_1_gravity_problem.html", null ],
      [ "polyfem::problem::Kovnaszy", "classpolyfem_1_1problem_1_1_kovnaszy.html", null ],
      [ "polyfem::problem::MinSurfProblem", "classpolyfem_1_1problem_1_1_min_surf_problem.html", null ],
      [ "polyfem::problem::NodeProblem", "classpolyfem_1_1problem_1_1_node_problem.html", null ],
      [ "polyfem::problem::PointBasedTensorProblem", "classpolyfem_1_1problem_1_1_point_based_tensor_problem.html", null ],
      [ "polyfem::problem::ProblemWithSolution", "classpolyfem_1_1problem_1_1_problem_with_solution.html", [
        [ "polyfem::problem::CompressionElasticProblemExact", "classpolyfem_1_1problem_1_1_compression_elastic_problem_exact.html", null ],
        [ "polyfem::problem::CubicProblem", "classpolyfem_1_1problem_1_1_cubic_problem.html", null ],
        [ "polyfem::problem::ElasticProblemExact", "classpolyfem_1_1problem_1_1_elastic_problem_exact.html", null ],
        [ "polyfem::problem::FrankeProblem", "classpolyfem_1_1problem_1_1_franke_problem.html", null ],
        [ "polyfem::problem::FrankeProblemOld", "classpolyfem_1_1problem_1_1_franke_problem_old.html", null ],
        [ "polyfem::problem::GenericScalarProblemExact", "classpolyfem_1_1problem_1_1_generic_scalar_problem_exact.html", null ],
        [ "polyfem::problem::KernelProblem", "classpolyfem_1_1problem_1_1_kernel_problem.html", null ],
        [ "polyfem::problem::LinearElasticProblemExact", "classpolyfem_1_1problem_1_1_linear_elastic_problem_exact.html", null ],
        [ "polyfem::problem::LinearProblem", "classpolyfem_1_1problem_1_1_linear_problem.html", null ],
        [ "polyfem::problem::QuadraticElasticProblemExact", "classpolyfem_1_1problem_1_1_quadratic_elastic_problem_exact.html", null ],
        [ "polyfem::problem::QuadraticProblem", "classpolyfem_1_1problem_1_1_quadratic_problem.html", null ],
        [ "polyfem::problem::SimpleStokeProblemExact", "classpolyfem_1_1problem_1_1_simple_stoke_problem_exact.html", null ],
        [ "polyfem::problem::SineProblem", "classpolyfem_1_1problem_1_1_sine_problem.html", null ],
        [ "polyfem::problem::SineStokeProblemExact", "classpolyfem_1_1problem_1_1_sine_stoke_problem_exact.html", null ],
        [ "polyfem::problem::TestProblem", "classpolyfem_1_1problem_1_1_test_problem.html", null ],
        [ "polyfem::problem::ZeroBCProblem", "classpolyfem_1_1problem_1_1_zero_b_c_problem.html", null ]
      ] ],
      [ "polyfem::problem::StokesLawProblem", "classpolyfem_1_1problem_1_1_stokes_law_problem.html", null ],
      [ "polyfem::problem::TaylorGreenVortexProblem", "classpolyfem_1_1problem_1_1_taylor_green_vortex_problem.html", null ],
      [ "polyfem::problem::TimeDependentProblem", "classpolyfem_1_1problem_1_1_time_dependent_problem.html", null ],
      [ "polyfem::problem::TimeDepentendStokesProblem", "classpolyfem_1_1problem_1_1_time_depentend_stokes_problem.html", [
        [ "polyfem::problem::ConstantVelocity", "classpolyfem_1_1problem_1_1_constant_velocity.html", null ],
        [ "polyfem::problem::CornerFlow", "classpolyfem_1_1problem_1_1_corner_flow.html", null ],
        [ "polyfem::problem::DrivenCavity", "classpolyfem_1_1problem_1_1_driven_cavity.html", null ],
        [ "polyfem::problem::DrivenCavityC0", "classpolyfem_1_1problem_1_1_driven_cavity_c0.html", null ],
        [ "polyfem::problem::DrivenCavitySmooth", "classpolyfem_1_1problem_1_1_driven_cavity_smooth.html", null ],
        [ "polyfem::problem::Flow", "classpolyfem_1_1problem_1_1_flow.html", null ],
        [ "polyfem::problem::FlowWithObstacle", "classpolyfem_1_1problem_1_1_flow_with_obstacle.html", null ],
        [ "polyfem::problem::Lshape", "classpolyfem_1_1problem_1_1_lshape.html", null ],
        [ "polyfem::problem::TwoSpheres", "classpolyfem_1_1problem_1_1_two_spheres.html", null ],
        [ "polyfem::problem::UnitFlowWithObstacle", "classpolyfem_1_1problem_1_1_unit_flow_with_obstacle.html", null ]
      ] ],
      [ "polyfem::problem::TorsionElasticProblem", "classpolyfem_1_1problem_1_1_torsion_elastic_problem.html", null ],
      [ "polyfem::problem::TransientStokeProblemExact", "classpolyfem_1_1problem_1_1_transient_stoke_problem_exact.html", null ],
      [ "polyfem::problem::WalkProblem", "classpolyfem_1_1problem_1_1_walk_problem.html", null ]
    ] ],
    [ "polyfem::problem::ProblemFactory", "classpolyfem_1_1problem_1_1_problem_factory.html", null ],
    [ "polyfem::renderer::Program", "classpolyfem_1_1renderer_1_1_program.html", null ],
    [ "polyfem::quadrature::QuadQuadrature", "classpolyfem_1_1quadrature_1_1_quad_quadrature.html", null ],
    [ "polyfem::basis::QuadraticBSpline", "classpolyfem_1_1basis_1_1_quadratic_b_spline.html", null ],
    [ "polyfem::basis::QuadraticBSpline2d", "classpolyfem_1_1basis_1_1_quadratic_b_spline2d.html", null ],
    [ "polyfem::basis::QuadraticBSpline3d", "classpolyfem_1_1basis_1_1_quadratic_b_spline3d.html", null ],
    [ "polyfem::quadrature::Quadrature", "classpolyfem_1_1quadrature_1_1_quadrature.html", null ],
    [ "polyfem::utils::RBFInterpolation", "classpolyfem_1_1utils_1_1_r_b_f_interpolation.html", null ],
    [ "polyfem::basis::RBFWithLinear", "classpolyfem_1_1basis_1_1_r_b_f_with_linear.html", null ],
    [ "polyfem::basis::RBFWithQuadratic", "classpolyfem_1_1basis_1_1_r_b_f_with_quadratic.html", null ],
    [ "polyfem::basis::RBFWithQuadraticLagrange", "classpolyfem_1_1basis_1_1_r_b_f_with_quadratic_lagrange.html", null ],
    [ "polyfem::utils::RefElementSampler", "classpolyfem_1_1utils_1_1_ref_element_sampler.html", null ],
    [ "p_bases.ReferenceSimplex", "classp__bases_1_1_reference_simplex.html", null ],
    [ "q_bases.ReferenceSimplex", "classq__bases_1_1_reference_simplex.html", null ],
    [ "polyfem::assembler::RhsAssembler", "classpolyfem_1_1assembler_1_1_rhs_assembler.html", null ],
    [ "polyfem::assembler::SaintVenantElasticity", "classpolyfem_1_1assembler_1_1_saint_venant_elasticity.html", null ],
    [ "polyfem::utils::Selection", "classpolyfem_1_1utils_1_1_selection.html", [
      [ "polyfem::utils::AxisPlaneSelection", "classpolyfem_1_1utils_1_1_axis_plane_selection.html", null ],
      [ "polyfem::utils::BoxSelection", "classpolyfem_1_1utils_1_1_box_selection.html", null ],
      [ "polyfem::utils::PlaneSelection", "classpolyfem_1_1utils_1_1_plane_selection.html", null ],
      [ "polyfem::utils::SpecifiedSelection", "classpolyfem_1_1utils_1_1_specified_selection.html", [
        [ "polyfem::utils::FileSelection", "classpolyfem_1_1utils_1_1_file_selection.html", null ]
      ] ],
      [ "polyfem::utils::SphereSelection", "classpolyfem_1_1utils_1_1_sphere_selection.html", null ],
      [ "polyfem::utils::UniformSelection", "classpolyfem_1_1utils_1_1_uniform_selection.html", null ]
    ] ],
    [ "polyfem::SolutionFrame", "classpolyfem_1_1_solution_frame.html", null ],
    [ "polyfem::utils::SpareMatrixCache", "classpolyfem_1_1utils_1_1_spare_matrix_cache.html", null ],
    [ "polyfem::basis::SpectralBasis2d", "classpolyfem_1_1basis_1_1_spectral_basis2d.html", null ],
    [ "polyfem::basis::SplineBasis2d", "classpolyfem_1_1basis_1_1_spline_basis2d.html", null ],
    [ "polyfem::basis::SplineBasis3d", "classpolyfem_1_1basis_1_1_spline_basis3d.html", null ],
    [ "polyfem::State", "classpolyfem_1_1_state.html", null ],
    [ "polyfem::StepData", "classpolyfem_1_1_step_data.html", null ],
    [ "polyfem::assembler::StokesMixed", "classpolyfem_1_1assembler_1_1_stokes_mixed.html", null ],
    [ "polyfem::assembler::StokesPressure", "classpolyfem_1_1assembler_1_1_stokes_pressure.html", null ],
    [ "polyfem::assembler::StokesVelocity", "classpolyfem_1_1assembler_1_1_stokes_velocity.html", null ],
    [ "polyfem::quadrature::TetQuadrature", "classpolyfem_1_1quadrature_1_1_tet_quadrature.html", null ],
    [ "polyfem::utils::Timer", "classpolyfem_1_1utils_1_1_timer.html", null ],
    [ "polyfem::solver::TransientNavierStokesSolver", "classpolyfem_1_1solver_1_1_transient_navier_stokes_solver.html", null ],
    [ "polyfem::quadrature::TriQuadrature", "classpolyfem_1_1quadrature_1_1_tri_quadrature.html", null ],
    [ "polyfem::renderer::UniformAttributes", "classpolyfem_1_1renderer_1_1_uniform_attributes.html", null ],
    [ "polyfem::mesh::Vertex", "structpolyfem_1_1mesh_1_1_vertex.html", null ],
    [ "polyfem::renderer::VertexAttributes", "classpolyfem_1_1renderer_1_1_vertex_attributes.html", null ],
    [ "polyfem::mesh::VTUWriter", "classpolyfem_1_1mesh_1_1_v_t_u_writer.html", null ]
];