PolyFEM: p_bases Namespace Reference
p_bases Namespace Reference
Classes
class Lagrange
class ReferenceSimplex
Functions
bernstein_space (order, nsd)
create_point_set (order, nsd)
create_matrix (equations, coeffs)
parse_args ()
Variables
x
y
z
args = parse_args()
list dims = [2, 3]
list orders = [0, 1, 2, 3, 4]
str bletter = "b" if args.bernstein else "p"
str cpp = f"#include \"auto_{bletter}_bases.hpp\""
str hpp = "#pragma once\n\n#include <Eigen/Dense>\n#include <cassert>\n"
str suffix = 2 else "3d"
str unique_nodes
str unique_fun
str dunique_fun
list vertices = [[0, 0], [1, 0], [0, 1]]
nbf
N
points
fe = Lagrange(dim, order, args.bernstein)
current_indices = list(range(0, len(fe.points)))
list indices = []
list vv = vertices[i]
int norm = 0
nn = max(0, order - 2)
npts = int(nn * (nn + 1) / 2)
list tmp = []
reverse
str nodes
str func
str dfunc
str default_base = 3 else "p_n_basis_value_2d(p, local_index, uv, val);"
str default_dbase = 3 else "p_n_basis_grad_value_2d(p, local_index, uv, val);"
str default_nodes = 3 else "p_n_nodes_2d(p, val);"
str base = "auto x=uv.col(0).array();\nauto y=uv.col(1).array();"
str dbase = base
list real_index = indices[i]
path = os.path.abspath(args.output)
Function Documentation
bernstein_space()
p_bases.bernstein_space (order, nsd)
Definition at line 39 of file p_bases.py.
Referenced by p_bases.Lagrange.compute_basis().
create_matrix()
p_bases.create_matrix (equations, coeffs)
Definition at line 106 of file p_bases.py.
Referenced by p_bases.Lagrange.compute_basis().
create_point_set()
p_bases.create_point_set (order, nsd)
Definition at line 81 of file p_bases.py.
Referenced by p_bases.Lagrange.compute_basis().
parse_args()
p_bases.parse_args ()
Definition at line 167 of file p_bases.py.
Variable Documentation
args
p_bases.args = parse_args()
Definition at line 178 of file p_bases.py.
base
str p_bases.base = "auto x=uv.col(0).array();\nauto y=uv.col(1).array();"
Definition at line 428 of file p_bases.py.
bletter
str p_bases.bletter = "b" if args.bernstein else "p"
Definition at line 185 of file p_bases.py.
cpp
str p_bases.cpp = f"#include \"auto_{bletter}_bases.hpp\""
Definition at line 187 of file p_bases.py.
current_indices
p_bases.current_indices = list(range(0, len(fe.points)))
Definition at line 257 of file p_bases.py.
dbase
str p_bases.dbase = base
Definition at line 432 of file p_bases.py.
default_base
str p_bases.default_base = 3 else "p_n_basis_value_2d(p, local_index, uv, val);"
Definition at line 424 of file p_bases.py.
default_dbase
str p_bases.default_dbase = 3 else "p_n_basis_grad_value_2d(p, local_index, uv, val);"
Definition at line 425 of file p_bases.py.
default_nodes
str p_bases.default_nodes = 3 else "p_n_nodes_2d(p, val);"
Definition at line 426 of file p_bases.py.
dfunc
str p_bases.dfunc
Initial value:
=  f"void {bletter}_{order}_basis_grad_value_{suffix}" + \
                "(const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)"
Definition at line 412 of file p_bases.py.
dims
list p_bases.dims = [2, 3]
Definition at line 180 of file p_bases.py.
dunique_fun
str p_bases.dunique_fun
Initial value:
=  f"void {bletter}_grad_basis_value_{suffix}" + \
                f"(const int {bletter}, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)"
Definition at line 208 of file p_bases.py.
fe
p_bases.fe = Lagrange(dim, order, args.bernstein)
Definition at line 255 of file p_bases.py.
func
str p_bases.func
Initial value:
=  f"void {bletter}_{order}_basis_value_{suffix}" + \
                "(const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &result_0)"
Definition at line 410 of file p_bases.py.
hpp
str p_bases.hpp = "#pragma once\n\n#include <Eigen/Dense>\n#include <cassert>\n"
Definition at line 194 of file p_bases.py.
indices
list p_bases.indices = []
Definition at line 258 of file p_bases.py.
N
p_bases.N
Definition at line 248 of file p_bases.py.
nbf
p_bases.nbf
Definition at line 246 of file p_bases.py.
nn
p_bases.nn = max(0, order - 2)
Definition at line 341 of file p_bases.py.
nodes
str p_bases.nodes
Initial value:
=  f"void {bletter}_{order}_nodes_{suffix}(Eigen::MatrixXd &res) {{\n res.resize(" + str(
                len(indices)) + ", " + str(dim) + "); res << \n"
Definition at line 398 of file p_bases.py.
norm
int p_bases.norm = 0
Definition at line 264 of file p_bases.py.
npts
p_bases.npts = int(nn * (nn + 1) / 2)
Definition at line 342 of file p_bases.py.
orders
list p_bases.orders = [0, 1, 2, 3, 4]
Definition at line 182 of file p_bases.py.
path
p_bases.path = os.path.abspath(args.output)
Definition at line 493 of file p_bases.py.
points
p_bases.points
Definition at line 251 of file p_bases.py.
real_index
list p_bases.real_index = indices[i]
Definition at line 443 of file p_bases.py.
reverse
p_bases.reverse
Definition at line 390 of file p_bases.py.
suffix
str p_bases.suffix = 2 else "3d"
Definition at line 200 of file p_bases.py.
tmp
list p_bases.tmp = []
Definition at line 365 of file p_bases.py.
unique_fun
str p_bases.unique_fun
Initial value:
=  f"void {bletter}_basis_value_{suffix}" + \
                f"(const int {bletter}, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)"
Definition at line 206 of file p_bases.py.
unique_nodes
str p_bases.unique_nodes
Initial value:
=  f"void {bletter}_nodes_{suffix}" + \
            f"(const int {bletter}, Eigen::MatrixXd &val)"
Definition at line 202 of file p_bases.py.
vertices
list p_bases.vertices = [[0, 0], [1, 0], [0, 1]]
Definition at line 237 of file p_bases.py.
vv
list p_bases.vv = vertices[i]
Definition at line 262 of file p_bases.py.
x
p_bases.x
Definition at line 11 of file p_bases.py.
y
p_bases.y
Definition at line 11 of file p_bases.py.
z
p_bases.z
Definition at line 11 of file p_bases.py.