PolyFEM: polyfem::varform Namespace Reference
polyfem::varform Namespace Reference
Namespaces
namespace internal
Classes
class BilaplacianVarForm
class ElasticVarForm
class FESpace
A finite-element space for one scalar- or vector-valued field.
class FluidVarForm
class GeometryMapping
class IncompressibleElasticVarForm
class LinearElasticVarForm
class NavierStokesVarForm
class NonlinearElasticStaticVarForm
class NonlinearElasticTransientVarForm
class NonlinearElasticVarForm
class ScalarVarForm
class StokesVarForm
class VarForm
struct VarFormBoundaryState
Temporary compatibility wrapper for boundary data belonging to one FE space.
class VarFormFactory
Functions
std::string formulation_from_args (const json &args)
Extracts the formulation type from the given JSON arguments.
bool uses_varform_state (json args)
Checks if the given JSON arguments use a VarForm state.
Function Documentation
formulation_from_args()
std::string polyfem::varform::formulation_from_args (const json & args)
Extracts the formulation type from the given JSON arguments.
this is temporary until legacy state is removed
Parameters
args JSON arguments containing material information.
Returns
The formulation type as a string.
Definition at line 21 of file VarFormFactory.cpp.
References polyfem::assembler::AssemblerUtils::is_elastic_material().
Referenced by polyfem::State::init(), and uses_varform_state().
uses_varform_state()
bool polyfem::varform::uses_varform_state (json args)
Checks if the given JSON arguments use a VarForm state.
this is temporary until legacy state is removed
Parameters
args JSON arguments containing material information.
Returns
True if the JSON arguments use a VarForm state, false otherwise.
Definition at line 54 of file VarFormFactory.cpp.
References polyfem::utils::apply_common_params(), polyfem::varform::VarFormFactory::create(), and formulation_from_args().
Referenced by forward_simulation().