PolyFEM: polyfem::utils::StringUtils Namespace Reference
polyfem::utils::StringUtils Namespace Reference
Functions
std::vector< std::string > split (const std::string &str, const std::string &delimiters=" ")
std::istream & skip (std::istream &in, char x='#')
bool startswith (const std::string &str, const std::string &prefix)
bool endswith (const std::string &str, const std::string &suffix)
std::string replace_ext (const std::string &filename, const std::string &newext)
std::string trim (const std::string &string)
Function Documentation
endswith()
bool polyfem::utils::StringUtils::endswith (const std::string & str, const std::string & suffix)
Definition at line 48 of file StringUtils.cpp.
References p_bases::suffix.
Referenced by polyfem::mesh::Mesh::create(), polyfem::mesh::CMesh3D::load(), polyfem::mesh::NCMesh3D::load(), polyfem::mesh::read_fem_mesh(), and polyfem::mesh::read_surface_mesh().
replace_ext()
std::string polyfem::utils::StringUtils::replace_ext (const std::string & filename, const std::string & newext)
Definition at line 61 of file StringUtils.cpp.
skip()
std::istream & polyfem::utils::StringUtils::skip (std::istream & in, char x = '#')
Definition at line 31 of file StringUtils.cpp.
References x.
split()
std::vector< std::string > polyfem::utils::StringUtils::split (const std::string & str, const std::string & delimiters = " ")
Definition at line 9 of file StringUtils.cpp.
Referenced by polyfem::problem::Flow::set_parameters(), and polyfem::problem::UnitFlowWithObstacle::set_parameters().
startswith()
bool polyfem::utils::StringUtils::startswith (const std::string & str, const std::string & prefix)
Definition at line 42 of file StringUtils.cpp.
trim()
std::string polyfem::utils::StringUtils::trim (const std::string & string)
Definition at line 98 of file StringUtils.cpp.