PolyFEM: tetrahedron Namespace Reference
tetrahedron Namespace Reference
Functions
def integrate_exact (f)
def integrate_approx (f, scheme)
def list_schemes ()
def generate_monomials (order)
def is_valid (scheme, tol=1e-6, relaxed=False)
def pick_scheme (all_schemes, order, relaxed=False)
def generate_cpp (selected_schemes)
def main ()
Function Documentation
generate_cpp()
def tetrahedron.generate_cpp (selected_schemes)
Generate cpp code to fill points & weights.
Definition at line 142 of file tetrahedron.py.
Referenced by main().
generate_monomials()
def tetrahedron.generate_monomials (order)
Generate trivariate monomials up to given order.
Definition at line 70 of file tetrahedron.py.
Referenced by pick_scheme().
integrate_approx()
def tetrahedron.integrate_approx (f, scheme)
Integrate numerically over the reference tetrahedron.
Definition at line 29 of file tetrahedron.py.
Referenced by pick_scheme().
integrate_exact()
def tetrahedron.integrate_exact (f)
Integrate a function over the reference tetrahedron (0,0), (1,0), (0,1).
Definition at line 10 of file tetrahedron.py.
Referenced by pick_scheme().
is_valid()
def tetrahedron.is_valid (scheme, tol = 1e-6, relaxed = False)
A scheme is valid if:
1. All its weights sums up to one;
2. All the weights are positive;
3. All its points are inside the reference tetrahedron;
4. No point lie on an face.
Definition at line 84 of file tetrahedron.py.
Referenced by pick_scheme(), polyfem::mesh::NCMesh2D.refine(), polyfem::mesh::NCMesh3D.refine(), and polyfem::mesh::NCMesh3D.refine_element().
list_schemes()
def tetrahedron.list_schemes ()
List all existing schemes for tetrahedra.
Definition at line 42 of file tetrahedron.py.
Referenced by main().
main()
def tetrahedron.main ()
Definition at line 169 of file tetrahedron.py.
References generate_cpp(), list_schemes(), main(), and pick_scheme().
Referenced by main().
pick_scheme()
def tetrahedron.pick_scheme (all_schemes, order, relaxed = False)
Picks the best scheme for a given polynomial degree, following this strategy:
- Tries all schemes with the same order as required.
- Eliminate schemes with weights that do not sum up to 1, or points that lie
  outside the reference triangle.
- Among the remaining schemes, compare the integration error over all bivariate
  monomials of inferior order.
- Keeps only the scheme with total integration error lower than a certain threshold.
- Among those, keep the one with fewer number of integration points.
- Finally, break ties using the integration error accumulated over the monomials.
Definition at line 101 of file tetrahedron.py.
References generate_monomials(), integrate_approx(), integrate_exact(), and is_valid().
Referenced by main().