PolyFEM: pyramid_bases Namespace Reference
pyramid_bases Namespace Reference
Classes
class Pyramid
Functions
shuffle (a, b)
pyramid_space (order)
create_point_set (order)
create_matrix (equations, coeffs)
parse_args ()
Variables
x
y
z
args = parse_args()
list dims = [3]
list orders = [0, 1, 2, 3, 4]
str bletter = "pyramid"
str cpp = f"#include \"auto_{bletter}_bases.hpp\""
str hpp = "#pragma once\n\n#include <Eigen/Dense>\n#include <cassert>\n"
str suffix = "3d"
str unique_nodes
str unique_fun
str dunique_fun
list vertices = [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 0, 1]]
nbf
N
points
fe = Pyramid(order)
current_indices = list(range(0, len(fe.points)))
list indices = []
list vv = vertices[i]
int norm = 0
nn = max(0, order - 2)
tuple npts_b = (nn + 1)**2
npts = int(nn * (nn + 1) / 2)
list tmp = []
str nodes
str func
str dfunc
str base = "auto x=uv.col(0).array();\nauto y=uv.col(1).array();"
str dbase = base
list real_index = indices[i]
path = os.path.abspath(args.output)
Function Documentation
create_matrix()
pyramid_bases.create_matrix (equations, coeffs)
Definition at line 80 of file pyramid_bases.py.
Referenced by pyramid_bases.Pyramid.compute_basis().
create_point_set()
pyramid_bases.create_point_set (order)
Definition at line 30 of file pyramid_bases.py.
Referenced by pyramid_bases.Pyramid.compute_basis().
parse_args()
pyramid_bases.parse_args ()
Definition at line 128 of file pyramid_bases.py.
pyramid_space()
pyramid_bases.pyramid_space (order)
Definition at line 15 of file pyramid_bases.py.
Referenced by pyramid_bases.Pyramid.compute_basis().
shuffle()
pyramid_bases.shuffle (a, b)
Definition at line 12 of file pyramid_bases.py.
Variable Documentation
args
pyramid_bases.args = parse_args()
Definition at line 137 of file pyramid_bases.py.
base
str pyramid_bases.base = "auto x=uv.col(0).array();\nauto y=uv.col(1).array();"
Definition at line 390 of file pyramid_bases.py.
bletter
str pyramid_bases.bletter = "pyramid"
Definition at line 143 of file pyramid_bases.py.
cpp
str pyramid_bases.cpp = f"#include \"auto_{bletter}_bases.hpp\""
Definition at line 145 of file pyramid_bases.py.
current_indices
pyramid_bases.current_indices = list(range(0, len(fe.points)))
Definition at line 196 of file pyramid_bases.py.
dbase
str pyramid_bases.dbase = base
Definition at line 393 of file pyramid_bases.py.
dfunc
str pyramid_bases.dfunc
Initial value:
=  f"void {bletter}_{order}_basis_grad_value_{suffix}" + \
                "(const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)"
Definition at line 379 of file pyramid_bases.py.
dims
list pyramid_bases.dims = [3]
Definition at line 139 of file pyramid_bases.py.
dunique_fun
str pyramid_bases.dunique_fun
Initial value:
=  f"void {bletter}_grad_basis_value_{suffix}" + \
            f"(const int {bletter}, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)"
Definition at line 165 of file pyramid_bases.py.
fe
pyramid_bases.fe = Pyramid(order)
Definition at line 194 of file pyramid_bases.py.
func
str pyramid_bases.func
Initial value:
=  f"void {bletter}_{order}_basis_value_{suffix}" + \
                "(const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &result_0)"
Definition at line 377 of file pyramid_bases.py.
hpp
str pyramid_bases.hpp = "#pragma once\n\n#include <Eigen/Dense>\n#include <cassert>\n"
Definition at line 151 of file pyramid_bases.py.
indices
list pyramid_bases.indices = []
Definition at line 197 of file pyramid_bases.py.
N
pyramid_bases.N
Definition at line 190 of file pyramid_bases.py.
nbf
pyramid_bases.nbf
Definition at line 188 of file pyramid_bases.py.
nn
pyramid_bases.nn = max(0, order - 2)
Definition at line 302 of file pyramid_bases.py.
nodes
str pyramid_bases.nodes
Initial value:
=  f"void {bletter}_{order}_nodes_{suffix}(Eigen::MatrixXd &res) {{\n res.resize(" + str(
                len(indices)) + ", " + str(dim) + "); res << \n"
Definition at line 365 of file pyramid_bases.py.
norm
int pyramid_bases.norm = 0
Definition at line 203 of file pyramid_bases.py.
npts
pyramid_bases.npts = int(nn * (nn + 1) / 2)
Definition at line 304 of file pyramid_bases.py.
npts_b
tuple pyramid_bases.npts_b = (nn + 1)**2
Definition at line 303 of file pyramid_bases.py.
orders
list pyramid_bases.orders = [0, 1, 2, 3, 4]
Definition at line 141 of file pyramid_bases.py.
path
pyramid_bases.path = os.path.abspath(args.output)
Definition at line 446 of file pyramid_bases.py.
points
pyramid_bases.points
Definition at line 192 of file pyramid_bases.py.
real_index
list pyramid_bases.real_index = indices[i]
Definition at line 404 of file pyramid_bases.py.
suffix
str pyramid_bases.suffix = "3d"
Definition at line 158 of file pyramid_bases.py.
tmp
list pyramid_bases.tmp = []
Definition at line 307 of file pyramid_bases.py.
unique_fun
str pyramid_bases.unique_fun
Initial value:
=  f"void {bletter}_basis_value_{suffix}" + \
            f"(const int {bletter}, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)"
Definition at line 163 of file pyramid_bases.py.
unique_nodes
str pyramid_bases.unique_nodes
Initial value:
=  f"void {bletter}_nodes_{suffix}" + \
            f"(const int {bletter}, Eigen::MatrixXd &val)"
Definition at line 160 of file pyramid_bases.py.
vertices
list pyramid_bases.vertices = [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 0, 1]]
Definition at line 181 of file pyramid_bases.py.
vv
list pyramid_bases.vv = vertices[i]
Definition at line 201 of file pyramid_bases.py.
x
pyramid_bases.x
Definition at line 10 of file pyramid_bases.py.
y
pyramid_bases.y
Definition at line 10 of file pyramid_bases.py.
z
pyramid_bases.z
Definition at line 10 of file pyramid_bases.py.