PolyFEM: polyfem::solver Namespace Reference
polyfem::solver Namespace Reference
Namespaces
namespace AdjointTools
Classes
class AccelerationForm
class AdjointForm
class AdjointNLProblem
struct AdjointOptUtils
class ALSolver
class AMIPSForm
class AugmentedLagrangianForm
Form of the augmented lagrangian.
class BarrierContactForm
class BarycenterTargetForm
class BCLagrangianForm
Form of the augmented lagrangian for bc constraints.
class BodyForm
Form representing body forces.
class BoundarySmoothingForm
class BoundedBiharmonicWeights2Dto3D
class BSplineParametrization1DTo2D
class BSplineParametrization2DTo3D
class CollisionBarrierForm
class ComplianceForm
class CompositeForm
class CompositeParametrization
class ContactForm
Form representing the contact potential and forces.
class DampingCoeffientVariableToSimulation
class DeformedCollisionBarrierForm
class DiffCache
class DirichletEnergyForm
class DirichletNodesVariableToSimulation
class DirichletVariableToSimulation
class DivideForm
class ElasticEnergyForm
class ElasticVariableToSimulation
class ENu2LambdaMu
class ExponentialMap
class Form
class FrictionCoeffientVariableToSimulation
class FrictionForm
Form of the lagged friction disapative potential and forces.
class FullNLProblem
class HomoCompositeForm
class InequalityConstraintForm
class InertiaForm
Form of the inertia.
class InitialConditionVariableToSimulation
class InsertConstantMap
class InversionBarrierForm
class KineticForm
class L2ProjectionForm
class LaggedRegForm
Tikonov regularization form between x and x_lagged.
class LayerThicknessForm
class LinearFilter
class LogCompositeForm
class MacroStrainLagrangianForm
Form of the lagrangian in augmented lagrangian for homogenization.
class MatrixLagrangianForm
Form of the lagrangian in augmented lagrangian.
class MaxStressForm
class MeshTargetForm
class MinJacobianForm
Compute the minimum jacobian of the mesh elements, not differentiable polygon elements not supported!
class MinTargetDistForm
class NavierStokesSolver
class NegativeCompositeForm
class NLHomoProblem
class NLProblem
class NodeTargetForm
class NormalAdhesionForm
Form representing the contact potential and forces.
class OperatorSplittingSolver
class Parametrization
This parameterize a function f : x -> y and provides the chain rule with respect to previous gradients.
class ParametrizationFactory
class ParametrizationForm
class ParametrizedProductForm
class PerBody2PerElem
class PerBody2PerNode
class PeriodicContactForm
Form representing the contact potential and forces on a periodic mesh This form has a different input format of [fluctuation, affine], only can be used in NLHomoProblem.
class PeriodicLagrangianForm
Form of the augmented lagrangian for bc constraints.
class PeriodicMeshToMesh
class PeriodicShapeVariableToSimulation
class PlusConstCompositeForm
class PositionForm
class PowerForm
class PowerMap
class PressureForm
Form representing body forces.
class PressureVariableToSimulation
class ProxyContactForceForm
class ProxyTransientForm
class QuadraticPenaltyForm
Form for quadratic soft constraints.
class RayleighDampingForm
Tikonov regularization form between x and x_lagged.
class ScalarVelocityParametrization
class Scaling
class SDFTargetForm
class ShapeVariableToSimulation
class SliceMap
class SmoothContactForceForm
class SmoothContactForm
class SolveData
class to store time stepping data
class SpatialIntegralForm
class StaticBoundaryNLProblem
class StaticForm
class StressForm
class StressNormForm
class SumCompositeForm
class TangentialAdhesionForm
Form of the lagged tangential adhesion disapative potential and forces.
class TargetForm
class TransientForm
class TransientNavierStokesSolver
class VariableToBoundaryNodes
class VariableToBoundaryNodesExclusive
class VariableToInteriorNodes
class VariableToNodes
class VariableToSimulation
Maps the optimization variable to the state variable.
class VariableToSimulationGroup
A collection of VariableToSimulation.
class VolumeForm
class WeightedVolumeForm
Computes the dot product of the input x (after parametrization) and the volume of each element on the mesh.
Typedefs
typedef DScalar1< double, Eigen::Matrix< double, Eigen::Dynamic, 1 > > Diff
Enumerations
enum class ParameterType {
Shape , LameParameter , FrictionCoefficient , DampingCoefficient ,
InitialCondition , DirichletBC , PressureBC , MacroStrain ,
PeriodicShape
}
enum class SpatialIntegralType { Volume , Surface , VertexSum }
enum class CacheLevel { None , Solution , Derivatives }
enum class ElementInversionCheck { Discrete , Conservative }
Functions
void apply_objective_json_spec (json &args, const json &rules)
Typedef Documentation
Diff
typedef DScalar1<double, Eigen::Matrix<double, Eigen::Dynamic, 1> > polyfem::solver::Diff
Definition at line 236 of file SurfaceTractionForms.cpp.
Enumeration Type Documentation
CacheLevel
enum class polyfem::solver::CacheLevel strong
Enumerator
None
Solution
Derivatives
Definition at line 11 of file DiffCache.hpp.
ElementInversionCheck
enum class polyfem::solver::ElementInversionCheck strong
Enumerator
Discrete
Conservative
Definition at line 14 of file ElasticForm.hpp.
ParameterType
enum class polyfem::solver::ParameterType strong
Enumerator
Shape
LameParameter
FrictionCoefficient
DampingCoefficient
InitialCondition
DirichletBC
PressureBC
MacroStrain
PeriodicShape
Definition at line 19 of file AdjointTools.hpp.
SpatialIntegralType
enum class polyfem::solver::SpatialIntegralType strong
Enumerator
Volume
Surface
VertexSum
Definition at line 32 of file AdjointTools.hpp.
Function Documentation
apply_objective_json_spec()
void polyfem::solver::apply_objective_json_spec (json & args, const json & rules)
Definition at line 570 of file Optimizations.cpp.
References apply_objective_json_spec(), and polyfem::logger().
Referenced by apply_objective_json_spec(), and polyfem::solver::AdjointOptUtils::apply_opt_json_spec().