PolyFEM: polyfem::autogen Namespace Reference
polyfem::autogen Namespace Reference
Functions
void b_basis_value_2d (const int b, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void b_grad_basis_value_2d (const int b, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void b_basis_value_3d (const int b, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void b_grad_basis_value_3d (const int b, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
template<typename T >
T int_pow (T val, int exp)
template<typename T >
void eigs_2d (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > &m, Eigen::Matrix< T, Eigen::Dynamic, 1, 0, 3, 1 > &res)
template<typename T >
void eigs_3d (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > &m, Eigen::Matrix< T, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void linear_elasticity_2d_function (const AutodiffHessianPt &pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void linear_elasticity_3d_function (const AutodiffHessianPt &pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void hooke_2d_function (const AutodiffHessianPt &pt, const assembler::ElasticityTensor &C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void hooke_3d_function (const AutodiffHessianPt &pt, const assembler::ElasticityTensor &C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void saint_venant_2d_function (const AutodiffHessianPt &pt, const assembler::ElasticityTensor &C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void saint_venant_3d_function (const AutodiffHessianPt &pt, const assembler::ElasticityTensor &C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void neo_hookean_2d_function (const AutodiffHessianPt &pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
void neo_hookean_3d_function (const AutodiffHessianPt &pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > &res)
template<>
void generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > &def_grad, Eigen::Matrix< double, 2, 2 > &gradient)
template<>
void generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > &def_grad, Eigen::Matrix< double, 4, 4 > &hessian)
template<>
void generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > &def_grad, Eigen::Matrix< double, 3, 3 > &gradient)
template<>
void generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > &def_grad, Eigen::Matrix< double, 9, 9 > &hessian)
void generate_gradient (const double c1, const double c2, const double c3, const double d1, const Eigen::MatrixXd &def_grad, Eigen::MatrixXd &gradient)
void generate_hessian (const double c1, const double c2, const double c3, const double d1, const Eigen::MatrixXd &def_grad, Eigen::MatrixXd &hessian)
template<int dim>
void generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, dim, dim > &def_grad, Eigen::Matrix< double, dim, dim > &gradient)
template<>
void generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > &def_grad, Eigen::Matrix< double, 2, 2 > &gradient)
template<>
void generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > &def_grad, Eigen::Matrix< double, 3, 3 > &gradient)
template<int dim>
void generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, dim, dim > &def_grad, Eigen::Matrix< double, dim *dim, dim *dim > &hessian)
template<>
void generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > &def_grad, Eigen::Matrix< double, 4, 4 > &hessian)
template<>
void generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > &def_grad, Eigen::Matrix< double, 9, 9 > &hessian)
void p_nodes_2d (const int p, Eigen::MatrixXd &val)
void p_basis_value_2d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void p_grad_basis_value_2d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void p_nodes_3d (const int p, Eigen::MatrixXd &val)
void p_basis_value_3d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void p_grad_basis_value_3d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_grad_basis_value_2d (const int q, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_nodes_2d (const int q, Eigen::MatrixXd &val)
void q_basis_value_2d (const int q, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_0_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_1_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_2_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_3_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_m2_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_grad_basis_value_3d (const int q, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void q_nodes_3d (const int q, Eigen::MatrixXd &val)
void q_basis_value_3d (const int q, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
Eigen::Vector3i convert_local_index_to_ijk (const int local_index, const int p)
Eigen::ArrayXd P (const int m, const int p, const Eigen::ArrayXd &z)
Eigen::ArrayXd P_prime (const int m, const int p, const Eigen::ArrayXd &z)
void p_n_nodes_3d (const int p, Eigen::MatrixXd &val)
void p_n_nodes_2d (const int p, Eigen::MatrixXd &val)
void p_n_basis_value_3d (const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void p_n_basis_value_2d (const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void p_n_basis_grad_value_3d (const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
void p_n_basis_grad_value_2d (const int p, const int local_index, const Eigen::MatrixXd &uv, Eigen::MatrixXd &val)
Function Documentation
b_basis_value_2d()
void polyfem::autogen::b_basis_value_2d (const int b, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 191 of file auto_b_bases.cpp.
References val.
Referenced by p_basis_value_2d().
b_basis_value_3d()
void polyfem::autogen::b_basis_value_3d (const int b, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 486 of file auto_b_bases.cpp.
References val.
Referenced by p_basis_value_3d().
b_grad_basis_value_2d()
void polyfem::autogen::b_grad_basis_value_2d (const int b, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 202 of file auto_b_bases.cpp.
References val.
Referenced by p_grad_basis_value_2d().
b_grad_basis_value_3d()
void polyfem::autogen::b_grad_basis_value_3d (const int b, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 497 of file auto_b_bases.cpp.
References val.
Referenced by p_grad_basis_value_3d().
convert_local_index_to_ijk()
Eigen::Vector3i polyfem::autogen::convert_local_index_to_ijk (const int local_index, const int p)
Definition at line 9 of file p_n_bases.cpp.
Referenced by p_n_basis_grad_value_2d(), and p_n_basis_value_2d().
eigs_2d()
template<typename T > void polyfem::autogen::eigs_2d (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > & m, Eigen::Matrix< T, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 11 of file auto_eigs.hpp.
eigs_3d()
template<typename T > void polyfem::autogen::eigs_3d (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > & m, Eigen::Matrix< T, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 33 of file auto_eigs.hpp.
generate_gradient()
void polyfem::autogen::generate_gradient (const double c1, const double c2, const double c3, const double d1, const Eigen::MatrixXd & def_grad, Eigen::MatrixXd & gradient)
Definition at line 822 of file auto_mooney_rivlin_gradient_hessian.cpp.
Referenced by polyfem::assembler::MooneyRivlin3ParamSymbolic::assign_stress_tensor(), and polyfem::assembler::MooneyRivlin3ParamSymbolic::get_grad_hess_symbolic().
generate_gradient_templated() [1/5]
template<> void polyfem::autogen::generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > & def_grad, Eigen::Matrix< double, 2, 2 > & gradient)
Definition at line 10 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_gradient_templated() [2/5]
template<> void polyfem::autogen::generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > & def_grad, Eigen::Matrix< double, 2, 2 > & gradient)
Definition at line 10 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_gradient_templated() [3/5]
template<> void polyfem::autogen::generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > & def_grad, Eigen::Matrix< double, 3, 3 > & gradient)
Definition at line 177 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_gradient_templated() [4/5]
template<> void polyfem::autogen::generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > & def_grad, Eigen::Matrix< double, 3, 3 > & gradient)
Definition at line 177 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_gradient_templated() [5/5]
template<int dim> void polyfem::autogen::generate_gradient_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, dim, dim > & def_grad, Eigen::Matrix< double, dim, dim > & gradient)
Definition at line 10 of file auto_mooney_rivlin_gradient_hessian.hpp.
generate_hessian()
void polyfem::autogen::generate_hessian (const double c1, const double c2, const double c3, const double d1, const Eigen::MatrixXd & def_grad, Eigen::MatrixXd & hessian)
Definition at line 840 of file auto_mooney_rivlin_gradient_hessian.cpp.
Referenced by polyfem::assembler::MooneyRivlin3ParamSymbolic::get_grad_hess_symbolic().
generate_hessian_templated() [1/5]
template<> void polyfem::autogen::generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > & def_grad, Eigen::Matrix< double, 4, 4 > & hessian)
Definition at line 49 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_hessian_templated() [2/5]
template<> void polyfem::autogen::generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 2, 2 > & def_grad, Eigen::Matrix< double, 4, 4 > & hessian)
Definition at line 49 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_hessian_templated() [3/5]
template<> void polyfem::autogen::generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > & def_grad, Eigen::Matrix< double, 9, 9 > & hessian)
Definition at line 262 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_hessian_templated() [4/5]
template<> void polyfem::autogen::generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, 3, 3 > & def_grad, Eigen::Matrix< double, 9, 9 > & hessian)
Definition at line 262 of file auto_mooney_rivlin_gradient_hessian.cpp.
generate_hessian_templated() [5/5]
template<int dim> void polyfem::autogen::generate_hessian_templated (const double c1, const double c2, const double c3, const double d1, const Eigen::Matrix< double, dim, dim > & def_grad, Eigen::Matrix< double, dim *dim, dim *dim > & hessian)
Definition at line 16 of file auto_mooney_rivlin_gradient_hessian.hpp.
hooke_2d_function()
void polyfem::autogen::hooke_2d_function (const AutodiffHessianPt & pt, const assembler::ElasticityTensor & C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 90 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::HookeLinearElasticity::compute_rhs().
hooke_3d_function()
void polyfem::autogen::hooke_3d_function (const AutodiffHessianPt & pt, const assembler::ElasticityTensor & C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 139 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::HookeLinearElasticity::compute_rhs().
int_pow()
template<typename T > T polyfem::autogen::int_pow (T val, int exp)
Definition at line 8 of file auto_eigs.hpp.
References val.
linear_elasticity_2d_function()
void polyfem::autogen::linear_elasticity_2d_function (const AutodiffHessianPt & pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 7 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::LinearElasticity::compute_rhs().
linear_elasticity_3d_function()
void polyfem::autogen::linear_elasticity_3d_function (const AutodiffHessianPt & pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 37 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::LinearElasticity::compute_rhs().
neo_hookean_2d_function()
void polyfem::autogen::neo_hookean_2d_function (const AutodiffHessianPt & pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 639 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::NeoHookeanElasticity::compute_rhs().
neo_hookean_3d_function()
void polyfem::autogen::neo_hookean_3d_function (const AutodiffHessianPt & pt, const double lambda, const double mu, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 705 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::NeoHookeanElasticity::compute_rhs().
P()
Eigen::ArrayXd polyfem::autogen::P (const int m, const int p, const Eigen::ArrayXd & z)
Definition at line 42 of file p_n_bases.cpp.
References z.
Referenced by p_n_basis_grad_value_2d(), p_n_basis_grad_value_3d(), p_n_basis_value_2d(), and p_n_basis_value_3d().
p_basis_value_2d()
void polyfem::autogen::p_basis_value_2d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 284 of file auto_p_bases.cpp.
References b_basis_value_2d(), p_n_basis_value_2d(), and val.
p_basis_value_3d()
void polyfem::autogen::p_basis_value_3d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 839 of file auto_p_bases.cpp.
References b_basis_value_3d(), p_n_basis_value_3d(), and val.
p_grad_basis_value_2d()
void polyfem::autogen::p_grad_basis_value_2d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 297 of file auto_p_bases.cpp.
References b_grad_basis_value_2d(), p_n_basis_grad_value_2d(), and val.
p_grad_basis_value_3d()
void polyfem::autogen::p_grad_basis_value_3d (const bool bernstein, const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 852 of file auto_p_bases.cpp.
References b_grad_basis_value_3d(), p_n_basis_grad_value_3d(), and val.
p_n_basis_grad_value_2d()
void polyfem::autogen::p_n_basis_grad_value_2d (const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 193 of file p_n_bases.cpp.
References convert_local_index_to_ijk(), P(), P_prime(), val, x, and y.
Referenced by p_grad_basis_value_2d().
p_n_basis_grad_value_3d()
void polyfem::autogen::p_n_basis_grad_value_3d (const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 176 of file p_n_bases.cpp.
References P(), p_n_nodes_3d(), P_prime(), val, x, y, and z.
Referenced by p_grad_basis_value_3d().
p_n_basis_value_2d()
void polyfem::autogen::p_n_basis_value_2d (const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 167 of file p_n_bases.cpp.
References convert_local_index_to_ijk(), P(), val, x, and y.
Referenced by p_basis_value_2d().
p_n_basis_value_3d()
void polyfem::autogen::p_n_basis_value_3d (const int p, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 157 of file p_n_bases.cpp.
References P(), p_n_nodes_3d(), val, x, y, and z.
Referenced by p_basis_value_3d().
p_n_nodes_2d()
void polyfem::autogen::p_n_nodes_2d (const int p, Eigen::MatrixXd & val)
Definition at line 130 of file p_n_bases.cpp.
References val.
Referenced by p_nodes_2d().
p_n_nodes_3d()
void polyfem::autogen::p_n_nodes_3d (const int p, Eigen::MatrixXd & val)
Definition at line 81 of file p_n_bases.cpp.
References val, x, y, and z.
Referenced by p_n_basis_grad_value_3d(), p_n_basis_value_3d(), and p_nodes_3d().
p_nodes_2d()
void polyfem::autogen::p_nodes_2d (const int p, Eigen::MatrixXd & val)
Definition at line 275 of file auto_p_bases.cpp.
References p_n_nodes_2d(), and val.
Referenced by polyfem::io::Evaluator::average_grad_based_function(), polyfem::State::build_basis(), polyfem::io::OutGeometryData::build_high_order_vis_mesh(), polyfem::io::Evaluator::check_scalar_value(), polyfem::io::Evaluator::compute_scalar_value(), polyfem::io::Evaluator::compute_tensor_value(), polyfem::utils::extract_nodes(), polyfem::utils::extract_nodes(), polyfem::io::Evaluator::interpolate_function(), polyfem::io::Evaluator::mark_flipped_cells(), polyfem::io::OutGeometryData::save_volume(), and polyfem::State::solve_transient_navier_stokes_split().
p_nodes_3d()
void polyfem::autogen::p_nodes_3d (const int p, Eigen::MatrixXd & val)
Definition at line 830 of file auto_p_bases.cpp.
References p_n_nodes_3d(), and val.
Referenced by polyfem::io::Evaluator::average_grad_based_function(), polyfem::State::build_basis(), polyfem::io::OutGeometryData::build_high_order_vis_mesh(), polyfem::io::Evaluator::check_scalar_value(), polyfem::io::Evaluator::compute_scalar_value(), polyfem::io::Evaluator::compute_tensor_value(), polyfem::utils::extract_nodes(), polyfem::utils::extract_nodes(), polyfem::io::Evaluator::interpolate_function(), polyfem::io::Evaluator::mark_flipped_cells(), polyfem::io::OutGeometryData::save_volume(), polyfem::State::solve_transient_navier_stokes_split(), and polyfem::basis::LagrangeBasis3d::tet_face_local_nodes().
P_prime()
Eigen::ArrayXd polyfem::autogen::P_prime (const int m, const int p, const Eigen::ArrayXd & z)
Definition at line 57 of file p_n_bases.cpp.
References z.
Referenced by p_n_basis_grad_value_2d(), and p_n_basis_grad_value_3d().
q_0_basis_grad_value_3d()
void polyfem::autogen::q_0_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 4 of file auto_q_bases_3d_grad_0.cpp.
References q_0_basis_grad_value_3d(), val, x, y, and z.
Referenced by q_0_basis_grad_value_3d(), and q_grad_basis_value_3d().
q_1_basis_grad_value_3d()
void polyfem::autogen::q_1_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 4 of file auto_q_bases_3d_grad_1.cpp.
References q_1_basis_grad_value_3d(), val, x, y, and z.
Referenced by q_1_basis_grad_value_3d(), and q_grad_basis_value_3d().
q_2_basis_grad_value_3d()
void polyfem::autogen::q_2_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 4 of file auto_q_bases_3d_grad_2.cpp.
References q_2_basis_grad_value_3d(), val, x, y, and z.
Referenced by q_2_basis_grad_value_3d(), and q_grad_basis_value_3d().
q_3_basis_grad_value_3d()
void polyfem::autogen::q_3_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 4 of file auto_q_bases_3d_grad_3.cpp.
References q_3_basis_grad_value_3d(), val, x, y, and z.
Referenced by q_3_basis_grad_value_3d(), and q_grad_basis_value_3d().
q_basis_value_2d()
void polyfem::autogen::q_basis_value_2d (const int q, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 88 of file auto_q_bases_2d_val.cpp.
References val.
q_basis_value_3d()
void polyfem::autogen::q_basis_value_3d (const int q, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 175 of file auto_q_bases_3d_val.cpp.
References val.
q_grad_basis_value_2d()
void polyfem::autogen::q_grad_basis_value_2d (const int q, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 182 of file auto_q_bases_2d_grad.cpp.
References val.
q_grad_basis_value_3d()
void polyfem::autogen::q_grad_basis_value_3d (const int q, const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 12 of file auto_q_bases_3d_grad.cpp.
References q_0_basis_grad_value_3d(), q_1_basis_grad_value_3d(), q_2_basis_grad_value_3d(), q_3_basis_grad_value_3d(), q_m2_basis_grad_value_3d(), and val.
q_m2_basis_grad_value_3d()
void polyfem::autogen::q_m2_basis_grad_value_3d (const int local_index, const Eigen::MatrixXd & uv, Eigen::MatrixXd & val)
Definition at line 4 of file auto_q_bases_3d_grad_-2.cpp.
References q_m2_basis_grad_value_3d(), val, x, y, and z.
Referenced by q_grad_basis_value_3d(), and q_m2_basis_grad_value_3d().
q_nodes_2d()
void polyfem::autogen::q_nodes_2d (const int q, Eigen::MatrixXd & val)
Definition at line 67 of file auto_q_bases_2d_nodes.cpp.
References val.
Referenced by polyfem::io::Evaluator::average_grad_based_function(), polyfem::State::build_basis(), polyfem::io::OutGeometryData::build_high_order_vis_mesh(), polyfem::io::Evaluator::check_scalar_value(), polyfem::io::Evaluator::compute_scalar_value(), polyfem::io::Evaluator::compute_tensor_value(), polyfem::io::Evaluator::interpolate_function(), polyfem::io::Evaluator::mark_flipped_cells(), polyfem::io::OutGeometryData::save_volume(), and polyfem::State::solve_transient_navier_stokes_split().
q_nodes_3d()
void polyfem::autogen::q_nodes_3d (const int q, Eigen::MatrixXd & val)
Definition at line 149 of file auto_q_bases_3d_nodes.cpp.
References val.
Referenced by polyfem::io::Evaluator::average_grad_based_function(), polyfem::State::build_basis(), polyfem::io::OutGeometryData::build_high_order_vis_mesh(), polyfem::io::Evaluator::check_scalar_value(), polyfem::io::Evaluator::compute_scalar_value(), polyfem::io::Evaluator::compute_tensor_value(), polyfem::basis::LagrangeBasis3d::hex_face_local_nodes(), polyfem::io::Evaluator::interpolate_function(), polyfem::io::Evaluator::mark_flipped_cells(), polyfem::io::OutGeometryData::save_volume(), and polyfem::State::solve_transient_navier_stokes_split().
saint_venant_2d_function()
void polyfem::autogen::saint_venant_2d_function (const AutodiffHessianPt & pt, const assembler::ElasticityTensor & C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 292 of file auto_elasticity_rhs.cpp.
References polyfem::assembler::ElasticityTensor::resize().
Referenced by polyfem::assembler::SaintVenantElasticity::compute_rhs().
saint_venant_3d_function()
void polyfem::autogen::saint_venant_3d_function (const AutodiffHessianPt & pt, const assembler::ElasticityTensor & C, Eigen::Matrix< double, Eigen::Dynamic, 1, 0, 3, 1 > & res)
Definition at line 382 of file auto_elasticity_rhs.cpp.
Referenced by polyfem::assembler::SaintVenantElasticity::compute_rhs().