PolyFEM: polyfem::utils Namespace Reference
polyfem::utils Namespace Reference
Namespaces
namespace StringUtils
Classes
class AxisPlaneSelection
class BoundarySampler
class BoxSelection
class BoxSideSelection
class CylinderSelection
class DenseMatrixCache
class EdgeSampler
struct EqualUnorderedArray
class ExpressionValue
class FileSelection
struct HashMatrix
struct HashPair
struct HashUnorderedArray
Hash function for an array where the order does not matter.
struct HashVector
class InterpolatedFunction2d
class Interpolation
class LinearInterpolation
class LinearRamp
class MatrixCache
class NoInterpolation
class NThread
class PiecewiseConstantInterpolation
class PiecewiseCubicInterpolation
class PiecewiseInterpolation
class PiecewiseLinearInterpolation
class PlaneSelection
class PolygonClipping
class RBFInterpolation
class RefElementSampler
class Selection
class SparseMatrixCache
class SpecifiedSelection
class SphereSelection
class TetrahedronClipping
class Timer
struct Timing
class TriangleClipping
class UniformSelection
Functions
double triangle_area_2D (const Eigen::Vector2d &a, const Eigen::Vector2d &b, const Eigen::Vector2d &c)
Compute the signed area of a 2D triangle defined by three points.
double triangle_area_3D (const Eigen::Vector3d &a, const Eigen::Vector3d &b, const Eigen::Vector3d &c)
Compute the area of a 3D triangle defined by three points.
double triangle_area (const Eigen::MatrixXd V)
Compute the signed area of a triangle defined by three points.
double tetrahedron_volume (const Eigen::Vector3d &a, const Eigen::Vector3d &b, const Eigen::Vector3d &c, const Eigen::Vector3d &d)
Compute the signed volume of a tetrahedron defined by four points.
double tetrahedron_volume (const Eigen::MatrixXd V)
Compute the signed volume of a tetrahedron defined by four points.
Eigen::MatrixXd triangle_to_clockwise_order (const Eigen::MatrixXd &triangle)
Reorder the vertices of a triangle so they are in clockwise order.
std::vector< Eigen::MatrixXd > triangle_fan (const Eigen::MatrixXd &convex_polygon)
Convert a convex polygon to a list of triangles fanned around the first vertex.
Eigen::VectorXd barycentric_coordinates (const Eigen::VectorXd &p, const Eigen::MatrixXd &V)
Compute barycentric coordinates for point p with respect to a simplex.
bool triangle_intersects_disk (const Eigen::Vector2d &t0, const Eigen::Vector2d &t1, const Eigen::Vector2d &t2, const Eigen::Vector2d &center, const double radius)
Determine if a 2D triangle intersects a 2D disk.
bool tetrahedron_intersects_ball (const Eigen::Vector3d &t0, const Eigen::Vector3d &t1, const Eigen::Vector3d &t2, const Eigen::Vector3d &t3, const Eigen::Vector3d &center, const double radius)
Determine if a 3D tetrahedron intersects a 3D ball.
bool are_edges_collinear (const VectorNd &ea0, const VectorNd &ea1, const VectorNd &eb0, const VectorNd &eb1, const double tol=1e-10)
Determine if two edges are collinear.
bool are_triangles_coplanar (const Eigen::Vector3d &t00, const Eigen::Vector3d &t01, const Eigen::Vector3d &t02, const Eigen::Vector3d &t10, const Eigen::Vector3d &t11, const Eigen::Vector3d &t12, const double tol=1e-10)
Determine if two triangles are coplanar.
bool are_aabbs_intersecting (const VectorNd &aabb0_min, const VectorNd &aabb0_max, const VectorNd &aabb1_min, const VectorNd &aabb1_max)
Determine if two axis-aligned bounding boxes intersect.
void triangle_area_2D_gradient (double ax, double ay, double bx, double by, double cx, double cy, double g[6])
Compute the gradient of the signed area of a 2D triangle defined by three points.
void triangle_area_2D_hessian (double ax, double ay, double bx, double by, double cx, double cy, double H[36])
Compute the Hessian of the signed area of a 2D triangle defined by three points.
void tetrahedron_volume_gradient (double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double g[12])
Compute the gradient of the signed volume of a tetrahedron defined by four points.
void tetrahedron_volume_hessian (double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double H[144])
Compute the gradient of the signed area of a 2D triangle defined by three points.
NLOHMANN_JSON_SERIALIZE_ENUM (PiecewiseInterpolation::Extend, {{PiecewiseInterpolation::Extend::CONSTANT, "constant"}, {PiecewiseInterpolation::Extend::EXTRAPOLATE, "extrapolate"}, {PiecewiseInterpolation::Extend::REPEAT, "repeat"}, {PiecewiseInterpolation::Extend::REPEAT_OFFSET, "repeat_offset"}})
void apply_common_params (json &args)
Eigen::Matrix3d to_rotation_matrix (const json &jr, std::string mode)
bool is_param_valid (const json &params, const std::string &key)
Determine if a key exists and is non-null in a json object.
template<typename T >
T deg2rad (T deg)
template<typename T = json>
std::vector< T > json_as_array (const json &j)
Return the value of a json object as an array.
template<typename T >
T json_value (const json &params, const std::string &key, const T &default_value)
Get a parameter from a json object or return a default value if the parameter invalid.
void show_matrix_stats (const Eigen::MatrixXd &M)
template<typename T >
T determinant (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > &mat)
template<typename T >
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > inverse (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > &mat)
Eigen::SparseMatrix< double > sparse_identity (int rows, int cols)
Eigen::VectorXd flatten (const Eigen::MatrixXd &X)
Flatten rowwises.
Eigen::MatrixXd unflatten (const Eigen::VectorXd &x, int dim)
Unflatten rowwises, so every dim elements in x become a row.
void vector2matrix (const Eigen::VectorXd &vec, Eigen::MatrixXd &mat)
Eigen::SparseMatrix< double > lump_matrix (const Eigen::SparseMatrix< double > &M)
Lump each row of a matrix into the diagonal.
void full_to_reduced_matrix (const int full_size, const int reduced_size, const std::vector< int > &removed_vars, const StiffnessMatrix &full, StiffnessMatrix &reduced)
Map a full size matrix to a reduced one by dropping rows and columns.
Eigen::MatrixXd reorder_matrix (const Eigen::MatrixXd &in, const Eigen::VectorXi &in_to_out, int out_blocks=-1, const int block_size=1)
Reorder row blocks in a matrix.
Eigen::MatrixXd unreorder_matrix (const Eigen::MatrixXd &out, const Eigen::VectorXi &in_to_out, int in_blocks=-1, const int block_size=1)
Undo the reordering of row blocks in a matrix.
Eigen::MatrixXi map_index_matrix (const Eigen::MatrixXi &in, const Eigen::VectorXi &index_mapping)
Map the entrys of an index matrix to new indices.
template<typename DstMat , typename SrcMat >
void append_rows (DstMat &dst, const SrcMat &src)
template<typename DstMat >
void append_rows_of_zeros (DstMat &dst, const size_t n_zero_rows)
void maybe_parallel_for (int size, const std::function< void(int, int, int)> &partial_for)
void maybe_parallel_for (int size, const std::function< void(int)> &body)
template<typename LocalStorage >
auto create_thread_storage (const LocalStorage &initial_local_storage)
template<typename Storages >
auto & get_local_thread_storage (Storages &storage, int thread_id)
void par_for (const int size, const std::function< void(int, int, int)> &func)
size_t get_n_threads ()
void regular_2d_grid (const int n, bool tri, Eigen::MatrixXd &V, Eigen::MatrixXi &F)
Generate a canonical triangle/quad subdivided from a regular grid.
void regular_3d_grid (const int nn, bool tet, Eigen::MatrixXd &V, Eigen::MatrixXi &F, Eigen::MatrixXi &T)
Generate a canonical tet/hex subdivided from a regular grid.
std::string resolve_path (const std::string &path, const std::string &input_file_path, const bool only_if_exists=false)
Function Documentation
append_rows()
template<typename DstMat , typename SrcMat > void polyfem::utils::append_rows (DstMat & dst, const SrcMat & src)
Definition at line 143 of file MatrixUtils.hpp.
Referenced by polyfem::mesh::Mesh::append(), polyfem::State::build_collision_mesh(), polyfem::mesh::SizingFieldRemesher< WMTKMesh >::compute_contact_sizing_field(), polyfem::mesh::LocalMesh< M >::LocalMesh(), polyfem::mesh::Remesher::project_quantities(), and polyfem::mesh::Remesher::write_mesh().
append_rows_of_zeros()
template<typename DstMat > void polyfem::utils::append_rows_of_zeros (DstMat & dst, const size_t n_zero_rows)
Definition at line 155 of file MatrixUtils.hpp.
Referenced by polyfem::io::OutGeometryData::save_volume().
apply_common_params()
void polyfem::utils::apply_common_params (json & args)
Definition at line 14 of file JSONUtils.cpp.
References apply_common_params(), polyfem::log_and_throw_error(), and resolve_path().
Referenced by apply_common_params(), and polyfem::State::init().
are_aabbs_intersecting()
bool polyfem::utils::are_aabbs_intersecting (const VectorNd & aabb0_min, const VectorNd & aabb0_max, const VectorNd & aabb1_min, const VectorNd & aabb1_max)
Determine if two axis-aligned bounding boxes intersect.
Parameters
aabb0_min Minimum corner of the first AABB.
aabb0_max Maximum corner of the first AABB.
aabb1_min Minimum corner of the second AABB.
aabb1_max Maximum corner of the second AABB.
Returns
True if the AABBs intersect, false otherwise.
Definition at line 196 of file GeometryUtils.cpp.
Referenced by polyfem::mesh::LocalMesh< M >::ball_selection().
are_edges_collinear()
bool polyfem::utils::are_edges_collinear (const VectorNd & ea0, const VectorNd & ea1, const VectorNd & eb0, const VectorNd & eb1, const double tol = 1e-10)
Determine if two edges are collinear.
Parameters
ea0 First vertex of the first edge.
ea1 Second vertex of the first edge.
eb0 First vertex of the second edge.
eb1 Second vertex of the second edge.
tol Tolerance for collinearity.
Returns
True if the edges are collinear, false otherwise.
Definition at line 169 of file GeometryUtils.cpp.
are_triangles_coplanar()
bool polyfem::utils::are_triangles_coplanar (const Eigen::Vector3d & t00, const Eigen::Vector3d & t01, const Eigen::Vector3d & t02, const Eigen::Vector3d & t10, const Eigen::Vector3d & t11, const Eigen::Vector3d & t12, const double tol = 1e-10)
Determine if two triangles are coplanar.
Parameters
t00 First vertex of the first triangle.
t01 Second vertex of the first triangle.
t02 Third vertex of the first triangle.
t10 First vertex of the second triangle.
t11 Second vertex of the second triangle.
t12 Third vertex of the second triangle.
tol Tolerance for coplanarity.
Returns
True if the triangles are coplanar, false otherwise.
Definition at line 182 of file GeometryUtils.cpp.
References polyfem::assembler::cross().
barycentric_coordinates()
Eigen::VectorXd polyfem::utils::barycentric_coordinates (const Eigen::VectorXd & p, const Eigen::MatrixXd & V)
Compute barycentric coordinates for point p with respect to a simplex.
Parameters
p Query point.
V Verties of the simplex as rows of a matrix.
Returns
The barycentric coordinates for point p with respect to the simplex.
Definition at line 88 of file GeometryUtils.cpp.
Referenced by polyfem::assembler::MassMatrixAssembler::assemble_cross().
create_thread_storage()
template<typename LocalStorage > auto polyfem::utils::create_thread_storage (const LocalStorage & initial_local_storage) inline
Referenced by polyfem::assembler::MassMatrixAssembler::assemble(), polyfem::assembler::NLAssembler::assemble_energy(), polyfem::assembler::NLAssembler::assemble_energy_per_element(), polyfem::solver::TransientForm::compute_adjoint_rhs_unweighted(), polyfem::assembler::RhsAssembler::compute_energy(), polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term(), polyfem::solver::TransientForm::compute_partial_gradient_unweighted(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), polyfem::solver::AdjointTools::dJ_damping_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_du_step(), polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_macro_strain_adjoint_term(), polyfem::solver::AdjointTools::dJ_material_transient_adjoint_term(), polyfem::solver::ElasticForm::force_material_derivative(), polyfem::solver::InertiaForm::force_shape_derivative(), polyfem::solver::BodyForm::force_shape_derivative(), polyfem::solver::ElasticForm::force_shape_derivative(), polyfem::solver::AdjointTools::integrate_objective(), polyfem::solver::InversionBarrierForm::second_derivative_unweighted(), and polyfem::solver::TransientForm::value_unweighted().
deg2rad()
template<typename T > T polyfem::utils::deg2rad (T deg) inline
Definition at line 17 of file JSONUtils.hpp.
References deg2rad().
Referenced by polyfem::mesh::construct_affine_transformation(), deg2rad(), and to_rotation_matrix().
determinant()
template<typename T > T polyfem::utils::determinant (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > & mat)
Definition at line 16 of file MatrixUtils.hpp.
References mat.
Referenced by polyfem::assembler::NeoHookeanElasticity::compute_energy_aux(), polyfem::assembler::AMIPSEnergy::elastic_energy(), polyfem::assembler::MooneyRivlin3ParamElasticity::elastic_energy(), polyfem::assembler::MooneyRivlinElasticity::elastic_energy(), polyfem::assembler::NeoHookeanAutodiff::elastic_energy(), inverse(), and polyfem::third_invariant().
flatten()
Eigen::VectorXd polyfem::utils::flatten (const Eigen::MatrixXd & X)
Flatten rowwises.
Definition at line 34 of file MatrixUtils.cpp.
References x.
Referenced by polyfem::solver::AMIPSForm::AMIPSForm(), polyfem::solver::MeshAffine::apply_jacobian(), polyfem::solver::CollisionBarrierForm::CollisionBarrierForm(), polyfem::solver::BoundarySmoothingForm::compute_partial_gradient_unweighted(), polyfem::assembler::NeoHookeanElasticity::compute_stiffness_value(), polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term(), polyfem::solver::MeshTiling::eval(), polyfem::solver::MeshAffine::eval(), polyfem::io::Evaluator::generate_linear_field(), polyfem::solver::ElasticEnergyForm::get_integral_functional(), polyfem::solver::StressForm::get_integral_functional(), polyfem::solver::ShapeVariableToSimulation::inverse_eval(), and polyfem::mesh::LocalRelaxationData< M >::sol().
full_to_reduced_matrix()
void polyfem::utils::full_to_reduced_matrix (const int full_size, const int reduced_size, const std::vector< int > & removed_vars, const StiffnessMatrix & full, StiffnessMatrix & reduced)
Map a full size matrix to a reduced one by dropping rows and columns.
Parameters
[in] full_size Number of variables in the full system.
[in] reduced_size Number of variables in the reduced system.
[in] removed_vars Indices of the variables (rows and columns of full) to remove.
[in] full Full size matrix.
[out] reduced Output reduced size matrix.
Definition at line 96 of file MatrixUtils.cpp.
References entries, and POLYFEM_SCOPED_TIMER.
Referenced by polyfem::solver::NLProblem::hessian().
get_local_thread_storage()
template<typename Storages > auto & polyfem::utils::get_local_thread_storage (Storages & storage, int thread_id) inline
Referenced by polyfem::assembler::MassMatrixAssembler::assemble(), polyfem::assembler::NLAssembler::assemble_energy(), polyfem::assembler::NLAssembler::assemble_energy_per_element(), polyfem::solver::TransientForm::compute_adjoint_rhs_unweighted(), polyfem::assembler::RhsAssembler::compute_energy(), polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term(), polyfem::solver::TransientForm::compute_partial_gradient_unweighted(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), polyfem::solver::AdjointTools::dJ_damping_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_du_step(), polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_material_transient_adjoint_term(), polyfem::solver::ElasticForm::force_material_derivative(), polyfem::solver::InertiaForm::force_shape_derivative(), polyfem::solver::BodyForm::force_shape_derivative(), polyfem::solver::ElasticForm::force_shape_derivative(), polyfem::solver::AdjointTools::integrate_objective(), and polyfem::solver::TransientForm::value_unweighted().
get_n_threads()
size_t polyfem::utils::get_n_threads () inline
Definition at line 25 of file par_for.hpp.
References polyfem::utils::NThread::get(), and polyfem::utils::NThread::num_threads.
Referenced by par_for(), and polyfem::io::OutStatsData::save_json().
inverse()
template<typename T > Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > polyfem::utils::inverse (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 > & mat)
Definition at line 32 of file MatrixUtils.hpp.
References determinant(), and mat.
Referenced by polyfem::mesh::stitch_mesh().
is_param_valid()
bool polyfem::utils::is_param_valid (const json & params, const std::string & key)
Determine if a key exists and is non-null in a json object.
Parameters
params JSON of parameters
key Key to check
Returns
True if the key exists and is non-null, false otherwise.
Definition at line 131 of file JSONUtils.cpp.
Referenced by polyfem::mesh::LocalRelaxationData< M >::init_assembler(), polyfem::State::init_time(), json_value(), polyfem::State::load_mesh(), polyfem::mesh::read_fem_mesh(), polyfem::mesh::read_obstacle_geometry(), polyfem::mesh::read_obstacle_mesh(), polyfem::State::root_path(), polyfem::State::set_materials(), polyfem::State::set_materials(), polyfem::assembler::GenericTensorProblem::set_parameters(), and polyfem::assembler::GenericScalarProblem::set_parameters().
json_as_array()
template<typename T = json> std::vector< T > polyfem::utils::json_as_array (const json & j)
Return the value of a json object as an array.
If the value is an array return it directly otherwise return a vector with the value.
Parameters
j JSON object
Returns
Array of values
Definition at line 37 of file JSONUtils.hpp.
Referenced by polyfem::assembler::GenericMatParams::add_multimaterial(), polyfem::State::boundary_conditions_ids(), polyfem::State::build_collision_mesh(), polyfem::solver::SolveData::init_forms(), polyfem::State::load_mesh(), polyfem::State::load_mesh(), and polyfem::problem::NodeProblem::set_parameters().
json_value()
template<typename T > T polyfem::utils::json_value (const json & params, const std::string & key, const T & default_value)
Get a parameter from a json object or return a default value if the parameter invalid.
Similar to json::value() but return default value if the parameter is null.
Definition at line 55 of file JSONUtils.hpp.
References is_param_valid().
lump_matrix()
Eigen::SparseMatrix< double > polyfem::utils::lump_matrix (const Eigen::SparseMatrix< double > & M)
Lump each row of a matrix into the diagonal.
Parameters
M Matrix to lump.
Returns
Lumped matrix.
Definition at line 77 of file MatrixUtils.cpp.
Referenced by polyfem::State::assemble_mass_mat(), polyfem::solver::BCLagrangianForm::init_masked_lumped_mass(), and polyfem::solver::BCPenaltyForm::init_masked_lumped_mass().
map_index_matrix()
Eigen::MatrixXi polyfem::utils::map_index_matrix (const Eigen::MatrixXi & in, const Eigen::VectorXi & index_mapping)
Map the entrys of an index matrix to new indices.
Parameters
in Input index matrix.
index_mapping Mapping from old to new indices.
Returns
Mapped index matrix.
Definition at line 216 of file MatrixUtils.cpp.
Referenced by polyfem::mesh::Remesher::project_quantities(), and polyfem::mesh::LocalMesh< M >::reorder_vertices().
maybe_parallel_for() [1/2]
void polyfem::utils::maybe_parallel_for (int size, const std::function< void(int)> & body) inline
maybe_parallel_for() [2/2]
void polyfem::utils::maybe_parallel_for (int size, const std::function< void(int, int, int)> & partial_for) inline
Referenced by polyfem::assembler::MassMatrixAssembler::assemble(), polyfem::assembler::NLAssembler::assemble_energy(), polyfem::assembler::NLAssembler::assemble_energy_per_element(), polyfem::solver::TransientForm::compute_adjoint_rhs_unweighted(), polyfem::assembler::RhsAssembler::compute_energy(), polyfem::solver::AdjointTools::compute_macro_strain_derivative_functional_term(), polyfem::solver::TransientForm::compute_partial_gradient_unweighted(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), polyfem::solver::AdjointTools::dJ_damping_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_du_step(), polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_macro_strain_adjoint_term(), polyfem::solver::AdjointTools::dJ_material_transient_adjoint_term(), polyfem::solver::InversionBarrierForm::first_derivative_unweighted(), polyfem::solver::ElasticForm::force_material_derivative(), polyfem::solver::InertiaForm::force_shape_derivative(), polyfem::solver::BodyForm::force_shape_derivative(), polyfem::solver::ElasticForm::force_shape_derivative(), polyfem::assembler::AssemblyValsCache::init(), polyfem::solver::AdjointTools::integrate_objective(), polyfem::utils::SparseMatrixCache::operator+(), polyfem::utils::SparseMatrixCache::operator+=(), polyfem::solver::InversionBarrierForm::second_derivative_unweighted(), polyfem::solver::AdjointNLProblem::solve_pde(), polyfem::solver::ContactForm::value_per_element_unweighted(), polyfem::solver::TransientForm::value_unweighted(), polyfem::solver::InversionBarrierForm::value_unweighted(), and polyfem::solver::MaxStressForm::value_unweighted_step().
NLOHMANN_JSON_SERIALIZE_ENUM()
polyfem::utils::NLOHMANN_JSON_SERIALIZE_ENUM (PiecewiseInterpolation::Extend , {{PiecewiseInterpolation::Extend::CONSTANT, "constant"}, {PiecewiseInterpolation::Extend::EXTRAPOLATE, "extrapolate"}, {PiecewiseInterpolation::Extend::REPEAT, "repeat"}, {PiecewiseInterpolation::Extend::REPEAT_OFFSET, "repeat_offset"}})
References polyfem::utils::PiecewiseInterpolation::CONSTANT, polyfem::utils::PiecewiseInterpolation::EXTRAPOLATE, polyfem::utils::PiecewiseInterpolation::REPEAT, and polyfem::utils::PiecewiseInterpolation::REPEAT_OFFSET.
par_for()
void polyfem::utils::par_for (const int size, const std::function< void(int, int, int)> & func)
Definition at line 10 of file par_for.cpp.
References get_n_threads(), and x.
regular_2d_grid()
void polyfem::utils::regular_2d_grid (const int n, bool tri, Eigen::MatrixXd & V, Eigen::MatrixXi & F)
Generate a canonical triangle/quad subdivided from a regular grid.
Parameters
[in] n n grid quads
[in] tri is a tri or a quad
[out] V #V x 2 output vertices positions
[out] F F x 3 output triangle indices
Definition at line 31 of file RefElementSampler.cpp.
References polyfem::F.
Referenced by polyfem::utils::RefElementSampler::build().
regular_3d_grid()
void polyfem::utils::regular_3d_grid (const int nn, bool tet, Eigen::MatrixXd & V, Eigen::MatrixXi & F, Eigen::MatrixXi & T)
Generate a canonical tet/hex subdivided from a regular grid.
Parameters
[in] n n grid quads
[in] tet is a tet or a hex
[out] V #V x 3 output vertices positions
[out] F F x 3 output triangle indices
[out] T F x 4 output tet indices
Definition at line 116 of file RefElementSampler.cpp.
References polyfem::F.
Referenced by polyfem::utils::RefElementSampler::build().
reorder_matrix()
Eigen::MatrixXd polyfem::utils::reorder_matrix (const Eigen::MatrixXd & in, const Eigen::VectorXi & in_to_out, int out_blocks = -1, const int block_size = 1)
Reorder row blocks in a matrix.
Parameters
in Input matrix.
in_to_out Mapping from input blocks to output blocks.
out_blocks Number of blocks in the output matrix.
block_size Size of each block.
Returns
Reordered matrix.
Definition at line 155 of file MatrixUtils.cpp.
Referenced by polyfem::State::initial_acceleration(), polyfem::State::initial_solution(), polyfem::State::initial_velocity(), polyfem::mesh::Remesher::project_quantities(), and polyfem::mesh::LocalMesh< M >::reorder_vertices().
resolve_path()
std::string polyfem::utils::resolve_path (const std::string & path, const std::string & input_file_path, const bool only_if_exists = false)
Definition at line 103 of file StringUtils.cpp.
Referenced by apply_common_params(), polyfem::utils::Selection::build(), polyfem::State::build_collision_mesh(), polyfem::utils::Selection::build_selections(), polyfem::mesh::read_fem_mesh(), polyfem::mesh::read_obstacle_geometry(), polyfem::mesh::read_obstacle_mesh(), polyfem::State::resolve_input_path(), polyfem::assembler::GenericTensorProblem::set_parameters(), and polyfem::assembler::GenericScalarProblem::set_parameters().
show_matrix_stats()
void polyfem::utils::show_matrix_stats (const Eigen::MatrixXd & M)
Definition at line 8 of file MatrixUtils.cpp.
References polyfem::logger().
Referenced by polyfem::basis::RBFWithQuadraticLagrange::compute_constraints_matrix_2d_old(), and polyfem::basis::RBFWithQuadraticLagrange::compute_constraints_matrix_3d().
sparse_identity()
Eigen::SparseMatrix< double > polyfem::utils::sparse_identity (int rows, int cols) inline
Definition at line 77 of file MatrixUtils.hpp.
Referenced by polyfem::solver::BCLagrangianForm::init_masked_lumped_mass(), and polyfem::solver::BCPenaltyForm::init_masked_lumped_mass().
tetrahedron_intersects_ball()
bool polyfem::utils::tetrahedron_intersects_ball (const Eigen::Vector3d & t0, const Eigen::Vector3d & t1, const Eigen::Vector3d & t2, const Eigen::Vector3d & t3, const Eigen::Vector3d & center, const double radius)
Determine if a 3D tetrahedron intersects a 3D ball.
Parameters
t0 Tetrahedron first vertex.
t1 Tetrahedron second vertex.
t2 Tetrahedron third vertex.
t3 Tetrahedron fourth vertex.
center Center of the ball.
radius Radius of the ball.
Returns
True if the tetrahedron intersects the ball, false otherwise.
Definition at line 137 of file GeometryUtils.cpp.
Referenced by polyfem::mesh::LocalMesh< M >::ball_selection().
tetrahedron_volume() [1/2]
double polyfem::utils::tetrahedron_volume (const Eigen::MatrixXd V)
Compute the signed volume of a tetrahedron defined by four points.
Parameters
V The vertices of the terahedron as rows of a matrix.
Returns
The signed volume of the tetrahedron.
Definition at line 52 of file GeometryUtils.cpp.
References tetrahedron_volume().
tetrahedron_volume() [2/2]
double polyfem::utils::tetrahedron_volume (const Eigen::Vector3d & a, const Eigen::Vector3d & b, const Eigen::Vector3d & c, const Eigen::Vector3d & d)
Compute the signed volume of a tetrahedron defined by four points.
Parameters
a First point of the tetrahedron.
b Second point of the tetrahedron.
c Third point of the tetrahedron.
d Fourth point of the tetrahedron.
Returns
The signed volume of the tetrahedron.
Definition at line 43 of file GeometryUtils.cpp.
Referenced by polyfem::assembler::MassMatrixAssembler::assemble_cross(), polyfem::utils::TetrahedronClipping::clip(), polyfem::solver::InversionBarrierForm::element_volume(), and tetrahedron_volume().
tetrahedron_volume_gradient()
void polyfem::utils::tetrahedron_volume_gradient (double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double g[12])
Compute the gradient of the signed volume of a tetrahedron defined by four points.
Parameters
ax First point's x coordinate.
ay First point's y coordinate.
ay First point's z coordinate.
bx Second point's x coordinate.
by Second point's y coordinate.
by Second point's z coordinate.
cx Third point's x coordinate.
cy Third point's y coordinate.
cy Third point's z coordinate.
dx Fourth point's x coordinate.
dy Fourth point's y coordinate.
dy Fourth point's z coordinate.
g Output gradient with respect to the four points.
Definition at line 261 of file GeometryUtils.cpp.
Referenced by polyfem::solver::InversionBarrierForm::element_volume_gradient().
tetrahedron_volume_hessian()
void polyfem::utils::tetrahedron_volume_hessian (double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double H[144])
Compute the gradient of the signed area of a 2D triangle defined by three points.
Parameters
ax First point's x coordinate.
ay First point's y coordinate.
ay First point's z coordinate.
bx Second point's x coordinate.
by Second point's y coordinate.
by Second point's z coordinate.
cx Third point's x coordinate.
cy Third point's y coordinate.
cy Third point's z coordinate.
dx Fourth point's x coordinate.
dy Fourth point's y coordinate.
dy Fourth point's z coordinate.
g Output flattened Hessian with respect to the four points.
Definition at line 295 of file GeometryUtils.cpp.
Referenced by polyfem::solver::InversionBarrierForm::element_volume_hessian().
to_rotation_matrix()
Eigen::Matrix3d polyfem::utils::to_rotation_matrix (const json & jr, std::string mode)
Definition at line 61 of file JSONUtils.cpp.
References deg2rad().
Referenced by polyfem::mesh::construct_affine_transformation().
triangle_area()
double polyfem::utils::triangle_area (const Eigen::MatrixXd V)
Compute the signed area of a triangle defined by three points.
Parameters
V The vertices of the triangle as rows of a matrix.
Returns
The signed area of the triangle.
Definition at line 30 of file GeometryUtils.cpp.
References triangle_area_2D(), and triangle_area_3D().
Referenced by polyfem::assembler::MassMatrixAssembler::assemble_cross(), polyfem::solver::InversionBarrierForm::element_volume(), polyfem::mesh::irregular_triangle(), and triangle_to_clockwise_order().
triangle_area_2D()
double polyfem::utils::triangle_area_2D (const Eigen::Vector2d & a, const Eigen::Vector2d & b, const Eigen::Vector2d & c)
Compute the signed area of a 2D triangle defined by three points.
Parameters
a First point of the triangle.
b Second point of the triangle.
c Third point of the triangle.
Returns
The signed area of the triangle.
Definition at line 14 of file GeometryUtils.cpp.
Referenced by polyfem::mesh::WildRemesher< WMTKMesh >::swap_edge_before(), and triangle_area().
triangle_area_2D_gradient()
void polyfem::utils::triangle_area_2D_gradient (double ax, double ay, double bx, double by, double cx, double cy, double g[6])
Compute the gradient of the signed area of a 2D triangle defined by three points.
Parameters
ax First point's x coordinate.
ay First point's y coordinate.
bx Second point's x coordinate.
by Second point's y coordinate.
cx Third point's x coordinate.
cy Third point's y coordinate.
g Output gradient with respect to the three points.
Definition at line 209 of file GeometryUtils.cpp.
Referenced by polyfem::solver::InversionBarrierForm::element_volume_gradient().
triangle_area_2D_hessian()
void polyfem::utils::triangle_area_2D_hessian (double ax, double ay, double bx, double by, double cx, double cy, double H[36])
Compute the Hessian of the signed area of a 2D triangle defined by three points.
Parameters
ax First point's x coordinate.
ay First point's y coordinate.
bx Second point's x coordinate.
by Second point's y coordinate.
cx Third point's x coordinate.
cy Third point's y coordinate.
g Output flattened Hessian with respect to the three points.
Definition at line 221 of file GeometryUtils.cpp.
Referenced by polyfem::solver::InversionBarrierForm::element_volume_hessian().
triangle_area_3D()
double polyfem::utils::triangle_area_3D (const Eigen::Vector3d & a, const Eigen::Vector3d & b, const Eigen::Vector3d & c)
Compute the area of a 3D triangle defined by three points.
Parameters
a First point of the triangle.
b Second point of the triangle.
c Third point of the triangle.
Returns
The signed area of the triangle.
Definition at line 22 of file GeometryUtils.cpp.
Referenced by triangle_area().
triangle_fan()
std::vector< Eigen::MatrixXd > polyfem::utils::triangle_fan (const Eigen::MatrixXd & convex_polygon)
Convert a convex polygon to a list of triangles fanned around the first vertex.
Parameters
convex_polygon The vertices of the convex polygon as rows of a matrix.
Returns
The list of triangles as matrices of rows.
Definition at line 74 of file GeometryUtils.cpp.
Referenced by polyfem::utils::TriangleClipping::clip().
triangle_intersects_disk()
bool polyfem::utils::triangle_intersects_disk (const Eigen::Vector2d & t0, const Eigen::Vector2d & t1, const Eigen::Vector2d & t2, const Eigen::Vector2d & center, const double radius)
Determine if a 2D triangle intersects a 2D disk.
Parameters
t0 Triangle first vertex.
t1 Triangle second vertex.
t2 Triangle third vertex.
center Center of the disk.
radius Radius of the disk.
Returns
True if the triangle intersects the disk, false otherwise.
Definition at line 107 of file GeometryUtils.cpp.
Referenced by polyfem::mesh::LocalMesh< M >::ball_selection().
triangle_to_clockwise_order()
Eigen::MatrixXd polyfem::utils::triangle_to_clockwise_order (const Eigen::MatrixXd & triangle)
Reorder the vertices of a triangle so they are in clockwise order.
Parameters
triangle The vertices of the triangle as rows of a matrix.
Returns
The vertices of the triangle in clockwise order as rows of a matrix.
Definition at line 58 of file GeometryUtils.cpp.
References triangle_area().
Referenced by polyfem::utils::TriangleClipping::clip().
unflatten()
Eigen::MatrixXd polyfem::utils::unflatten (const Eigen::VectorXd & x, int dim)
Unflatten rowwises, so every dim elements in x become a row.
Definition at line 53 of file MatrixUtils.cpp.
References x.
Referenced by polyfem::solver::MeshAffine::apply_jacobian(), polyfem::solver::ContactForm::compute_displaced_surface(), polyfem::State::compute_force_jacobian_prev(), polyfem::solver::CollisionBarrierForm::compute_partial_gradient_unweighted(), polyfem::solver::FrictionForm::compute_surface_velocities(), polyfem::mesh::constrained_L2_projection(), polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term(), polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term(), polyfem::solver::MeshTiling::eval(), polyfem::solver::MeshAffine::eval(), polyfem::io::OutGeometryData::export_data(), polyfem::solver::InversionBarrierForm::first_derivative_unweighted(), polyfem::solver::FrictionForm::force_shape_derivative(), polyfem::solver::ElasticEnergyForm::get_integral_functional(), polyfem::utils::PiecewiseCubicInterpolation::init(), polyfem::State::init_nonlinear_tensor_solve(), polyfem::solver::PeriodicMeshToMesh::inverse_eval(), polyfem::solver::CollisionBarrierForm::is_step_collision_free(), polyfem::solver::AMIPSForm::is_step_valid(), polyfem::solver::InversionBarrierForm::is_step_valid(), polyfem::solver::CollisionBarrierForm::max_step_size(), polyfem::io::OutGeometryData::save_contact_surface(), polyfem::io::OutGeometryData::save_volume(), polyfem::io::OutGeometryData::save_volume_vector_field(), polyfem::solver::InversionBarrierForm::second_derivative_unweighted(), polyfem::solver::CollisionBarrierForm::solution_changed(), polyfem::solver::CollisionBarrierForm::value_unweighted(), polyfem::solver::InversionBarrierForm::value_unweighted(), vector2matrix(), polyfem::mesh::Remesher::write_mesh(), and polyfem::mesh::LocalMesh< M >::write_mesh().
unreorder_matrix()
Eigen::MatrixXd polyfem::utils::unreorder_matrix (const Eigen::MatrixXd & out, const Eigen::VectorXi & in_to_out, int in_blocks = -1, const int block_size = 1)
Undo the reordering of row blocks in a matrix.
Parameters
out Reordered matrix.
in_to_out Mapping from input blocks to output blocks.
in_blocks Number of blocks in the input matrix.
block_size Size of each block.
Returns
Unreordered matrix.
Definition at line 186 of file MatrixUtils.cpp.
Referenced by polyfem::mesh::Remesher::project_quantities().
vector2matrix()
void polyfem::utils::vector2matrix (const Eigen::VectorXd & vec, Eigen::MatrixXd & mat)
Definition at line 69 of file MatrixUtils.cpp.
References mat, unflatten(), and vec.
Referenced by polyfem::solver::ComplianceForm::compute_partial_gradient_unweighted_step(), polyfem::solver::AdjointTools::compute_shape_derivative_functional_term(), polyfem::solver::ElasticForm::force_material_derivative(), polyfem::solver::ElasticForm::force_shape_derivative(), polyfem::solver::StressNormForm::get_integral_functional(), polyfem::solver::ComplianceForm::get_integral_functional(), and polyfem::solver::StressForm::get_integral_functional().