PolyFEM: polyfem::mesh::Navigation3D Namespace Reference
polyfem::mesh::Navigation3D Namespace Reference
Classes
struct Index
Functions
void prepare_mesh (Mesh3DStorage &M)
Index get_index_from_element_face (const Mesh3DStorage &M, int hi)
Index get_index_from_element_face (const Mesh3DStorage &M, int hi, int lf, int lv=0)
Index get_index_from_element_edge (const Mesh3DStorage &M, int hi, int v0, int v1)
Index get_index_from_element_tri (const Mesh3DStorage &M, int hi, int v0, int v1, int v2)
Index switch_vertex (const Mesh3DStorage &M, Index idx)
Index switch_edge (const Mesh3DStorage &M, Index idx)
Index switch_face (const Mesh3DStorage &M, Index idx)
Index switch_element (const Mesh3DStorage &M, Index idx)
Index next_around_2Dface (const Mesh3DStorage &M, Index idx)
Index next_around_2Dedge (const Mesh3DStorage &M, Index idx)
Index next_around_2Dvertex (const Mesh3DStorage &M, Index idx)
Index next_around_3Dedge (const Mesh3DStorage &M, Index idx)
Function Documentation
get_index_from_element_edge()
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::get_index_from_element_edge (const Mesh3DStorage & M, int hi, int v0, int v1)
Definition at line 117 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, eigs::M, polyfem::mesh::Navigation::switch_vertex(), polyfem::mesh::Tet, and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by polyfem::mesh::CMesh3D::get_index_from_element_edge().
get_index_from_element_face() [1/2]
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::get_index_from_element_face (const Mesh3DStorage & M, int hi)
Definition at line 27 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, polyfem::mesh::find(), get_index_from_element_face(), eigs::M, polyfem::mesh::MeshProcessing3D::set_intersection_own(), polyfem::mesh::Tet, and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by polyfem::mesh::CMesh3D::get_index_from_element(), and get_index_from_element_face().
get_index_from_element_face() [2/2]
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::get_index_from_element_face (const Mesh3DStorage & M, int hi, int lf, int lv = 0)
Definition at line 89 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, eigs::M, and polyfem::mesh::Navigation3D::Index::vertex.
get_index_from_element_tri()
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::get_index_from_element_tri (const Mesh3DStorage & M, int hi, int v0, int v1, int v2)
Definition at line 190 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, eigs::M, polyfem::mesh::Navigation::switch_edge(), polyfem::mesh::Navigation::switch_vertex(), polyfem::mesh::Tet, and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by polyfem::mesh::CMesh3D::get_index_from_element_face().
next_around_2Dedge()
Index polyfem::mesh::Navigation3D::next_around_2Dedge (const Mesh3DStorage & M, Index idx) inline
Definition at line 42 of file Navigation3D.hpp.
References eigs::M, switch_face(), and switch_vertex().
next_around_2Dface()
Index polyfem::mesh::Navigation3D::next_around_2Dface (const Mesh3DStorage & M, Index idx) inline
Definition at line 41 of file Navigation3D.hpp.
References eigs::M, switch_edge(), and switch_vertex().
Referenced by polyfem::mesh::CMesh3D::next_around_face().
next_around_2Dvertex()
Index polyfem::mesh::Navigation3D::next_around_2Dvertex (const Mesh3DStorage & M, Index idx) inline
Definition at line 43 of file Navigation3D.hpp.
References eigs::M, switch_edge(), and switch_face().
next_around_3Dedge()
Index polyfem::mesh::Navigation3D::next_around_3Dedge (const Mesh3DStorage & M, Index idx) inline
Definition at line 45 of file Navigation3D.hpp.
References eigs::M, switch_element(), and switch_face().
Referenced by polyfem::mesh::CMesh3D::next_around_edge().
prepare_mesh()
void polyfem::mesh::Navigation3D::prepare_mesh (Mesh3DStorage & M)
Definition at line 19 of file Navigation3D.cpp.
References polyfem::mesh::MeshProcessing3D::build_connectivity(), polyfem::mesh::MeshProcessing3D::global_orientation_hexes(), polyfem::mesh::Hyb, eigs::M, and polyfem::mesh::Tet.
Referenced by polyfem::mesh::CMesh3D::load(), and polyfem::mesh::CMesh3D::refine().
switch_edge()
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::switch_edge (const Mesh3DStorage & M, Index idx)
Definition at line 302 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, eigs::M, and polyfem::mesh::Tet.
Referenced by next_around_2Dface(), next_around_2Dvertex(), and polyfem::mesh::CMesh3D::switch_edge().
switch_element()
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::switch_element (const Mesh3DStorage & M, Index idx)
Definition at line 380 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, eigs::M, and polyfem::mesh::Tet.
Referenced by next_around_3Dedge(), and polyfem::mesh::CMesh3D::switch_element().
switch_face()
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::switch_face (const Mesh3DStorage & M, Index idx)
Definition at line 325 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::element, polyfem::mesh::Navigation3D::Index::element_patch, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, eigs::M, polyfem::mesh::MeshProcessing3D::set_intersection_own(), polyfem::mesh::Tet, and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by next_around_2Dedge(), next_around_2Dvertex(), next_around_3Dedge(), and polyfem::mesh::CMesh3D::switch_face().
switch_vertex()
polyfem::mesh::Navigation3D::Index polyfem::mesh::Navigation3D::switch_vertex (const Mesh3DStorage & M, Index idx)
Definition at line 267 of file Navigation3D.cpp.
References polyfem::mesh::Navigation3D::Index::edge, polyfem::mesh::Navigation3D::Index::face, polyfem::mesh::Navigation3D::Index::face_corner, eigs::M, polyfem::mesh::Tet, and polyfem::mesh::Navigation3D::Index::vertex.
Referenced by next_around_2Dedge(), next_around_2Dface(), and polyfem::mesh::CMesh3D::switch_vertex().