PolyFEM: pyramid_duffy Namespace Reference
pyramid_duffy Namespace Reference
Functions
integrate_exact (f)
duffy_quadrature (order)
verify_duffy (max_order=8)
verify_duffy_rational (max_p=4)
Variables
max_order
max_p
Function Documentation
duffy_quadrature()
pyramid_duffy.duffy_quadrature (order)
Build a pyramid quadrature rule via the Duffy transform:
    x = xi*(1-zeta), y = eta*(1-zeta), z = zeta
    J = (1-zeta)^2
A tensor product of n 1D Gauss-Legendre points (n = ceil((order+1)/2))
integrates the pulled-back polynomial stiffness integrand exactly for
pyramid basis degree p = order//2.
Returns (pts, weights) on the reference pyramid [0<=x,y<=1-z, 0<=z<=1].
Weights sum to 1/3.
Definition at line 13 of file pyramid_duffy.py.
Referenced by verify_duffy(), and verify_duffy_rational().
integrate_exact()
pyramid_duffy.integrate_exact (f)
Exact integral of f over the reference pyramid: 0<=z<=1, 0<=x,y<=1-z.
Definition at line 4 of file pyramid_duffy.py.
Referenced by verify_duffy(), and verify_duffy_rational().
verify_duffy()
pyramid_duffy.verify_duffy (max_order = 8)
Verify that duffy_quadrature integrates all monomials x^i y^j z^k
(i+j+k <= order) exactly over the reference pyramid.
Definition at line 52 of file pyramid_duffy.py.
References duffy_quadrature(), and integrate_exact().
verify_duffy_rational()
pyramid_duffy.verify_duffy_rational (max_p = 4)
Verify Duffy integrates the actual pyramid rational basis products exactly.
Tests xy/(1-z), x^2*y/(1-z)^2, etc. that appear in stiffness integrals.
Definition at line 81 of file pyramid_duffy.py.
References duffy_quadrature(), and integrate_exact().
Variable Documentation
max_order
pyramid_duffy.max_order
Definition at line 116 of file pyramid_duffy.py.
max_p
pyramid_duffy.max_p
Definition at line 119 of file pyramid_duffy.py.