PolyFEM: polyfem::solver::AdjointTools Namespace Reference
polyfem::solver::AdjointTools Namespace Reference
Functions
double integrate_objective (const legacy::State &state, const IntegrableFunctional &j, const Eigen::MatrixXd &solution, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step=0)
void dJ_du_step (const legacy::State &state, const IntegrableFunctional &j, const Eigen::MatrixXd &solution, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step, Eigen::VectorXd &term)
void compute_shape_derivative_functional_term (const legacy::State &state, const Eigen::MatrixXd &solution, const IntegrableFunctional &j, const std::set< int > &interested_ids, const SpatialIntegralType spatial_integral_type, Eigen::VectorXd &term, const int cur_time_step)
void dJ_shape_static_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
void dJ_shape_homogenization_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
void dJ_periodic_shape_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const PeriodicMeshToMesh &periodic_mesh_map, const Eigen::VectorXd &periodic_mesh_representation, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
void dJ_shape_transient_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
void dJ_material_static_adjoint_term (const legacy::State &state, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
void dJ_material_transient_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
void dJ_friction_transient_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
void dJ_damping_transient_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
void dJ_initial_condition_adjoint_term (const legacy::State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
void dJ_dirichlet_static_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
void dJ_dirichlet_transient_adjoint_term (const legacy::State &state, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
void dJ_pressure_static_adjoint_term (const legacy::State &state, const std::vector< int > &boundary_ids, const Eigen::MatrixXd &sol, const Eigen::MatrixXd &adjoint, Eigen::VectorXd &one_form)
void dJ_pressure_transient_adjoint_term (const legacy::State &state, const DiffCache &diff_cache, const std::vector< int > &boundary_ids, const Eigen::MatrixXd &adjoint_nu, const Eigen::MatrixXd &adjoint_p, Eigen::VectorXd &one_form)
Eigen::VectorXd map_primitive_to_node_order (const legacy::State &state, const Eigen::VectorXd &primitives)
Eigen::VectorXd map_node_to_primitive_order (const legacy::State &state, const Eigen::VectorXd &nodes)
Eigen::MatrixXd edge_normal_gradient (const Eigen::MatrixXd &V)
Eigen::MatrixXd face_normal_gradient (const Eigen::MatrixXd &V)
Eigen::MatrixXd edge_velocity_divergence (const Eigen::MatrixXd &V)
Eigen::MatrixXd face_velocity_divergence (const Eigen::MatrixXd &V)
void scaled_jacobian (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, Eigen::VectorXd &quality)
Function Documentation
compute_shape_derivative_functional_term()
void polyfem::solver::AdjointTools::compute_shape_derivative_functional_term (const legacy::State & state, const Eigen::MatrixXd & solution, const IntegrableFunctional & j, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, Eigen::VectorXd & term, const int cur_time_step)
Definition at line 342 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::ass_vals_cache, polyfem::legacy::State::assembler, polyfem::legacy::State::bases, polyfem::IntegrableFunctional::ParameterType::body_id, polyfem::assembler::AssemblyValsCache::compute(), polyfem::assembler::ElementAssemblyValues::compute(), polyfem::IntegrableFunctional::depend_on_gradu(), polyfem::IntegrableFunctional::depend_on_x(), polyfem::IntegrableFunctional::dj_dgradu(), polyfem::IntegrableFunctional::dj_dx(), polyfem::IntegrableFunctional::ParameterType::elem, polyfem::IntegrableFunctional::evaluate(), polyfem::legacy::State::geom_bases(), gvals, polyfem::legacy::State::mesh, polyfem::legacy::State::n_geom_bases, polyfem::quadrature::Quadrature::points, polyfem::legacy::State::problem, quadrature, polyfem::IntegrableFunctional::ParameterType::step, polyfem::IntegrableFunctional::ParameterType::t, polyfem::legacy::State::total_local_boundary, vals, polyfem::utils::vector2matrix(), and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::solver::SpatialIntegralForm::compute_partial_gradient_step().
dJ_damping_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_damping_transient_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 955 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::boundary_nodes, polyfem::solver::SolveData::damping_form, polyfem::legacy::State::solve_data, and polyfem::DiffCache::u().
Referenced by polyfem::solver::DampingVariableToSimulation::compute_adjoint_term().
dJ_dirichlet_static_adjoint_term()
void polyfem::solver::AdjointTools::dJ_dirichlet_static_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form)
Definition at line 1012 of file AdjointTools.cpp.
References polyfem::legacy::State::boundary_nodes, polyfem::DiffCache::gradu_h(), polyfem::legacy::State::mesh, polyfem::legacy::State::ndof(), and polyfem::legacy::State::primitive_to_node().
Referenced by polyfem::solver::DirichletNodesVariableToSimulation::compute_adjoint_term().
dJ_dirichlet_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_dirichlet_transient_adjoint_term (const legacy::State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 1034 of file AdjointTools.cpp.
References polyfem::legacy::State::args, and polyfem::legacy::State::boundary_nodes.
Referenced by polyfem::solver::DirichletBoundaryVariableToSimulation::compute_adjoint_term().
dJ_du_step()
void polyfem::solver::AdjointTools::dJ_du_step (const legacy::State & state, const IntegrableFunctional & j, const Eigen::MatrixXd & solution, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step, Eigen::VectorXd & term)
Definition at line 1124 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::ass_vals_cache, polyfem::legacy::State::assembler, polyfem::legacy::State::bases, polyfem::IntegrableFunctional::ParameterType::body_id, polyfem::assembler::AssemblyValsCache::compute(), polyfem::IntegrableFunctional::depend_on_gradu(), polyfem::IntegrableFunctional::depend_on_gradu_local(), polyfem::IntegrableFunctional::depend_on_u(), polyfem::IntegrableFunctional::dj_dgradu(), polyfem::IntegrableFunctional::dj_du(), polyfem::IntegrableFunctional::ParameterType::elem, polyfem::legacy::State::geom_bases(), polyfem::assembler::AssemblyValues::global, polyfem::assembler::AssemblyValues::grad_t_m, polyfem::legacy::State::mesh, polyfem::legacy::State::n_bases, polyfem::quadrature::Quadrature::points, polyfem::legacy::State::problem, quadrature, polyfem::IntegrableFunctional::ParameterType::step, polyfem::IntegrableFunctional::ParameterType::t, polyfem::legacy::State::total_local_boundary, polyfem::assembler::AssemblyValues::val, val, vals, and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::solver::SpatialIntegralForm::compute_adjoint_rhs_step().
dJ_friction_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_friction_transient_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 889 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::boundary_nodes, polyfem::legacy::State::collision_mesh, polyfem::solver::SolveData::contact_form, polyfem::DiffCache::friction_collision_set(), polyfem::solver::SolveData::friction_form, polyfem::legacy::State::initial_acceleration(), polyfem::DiffCache::initial_condition_override, polyfem::legacy::State::initial_velocity(), polyfem::legacy::InitialConditionOverride::is_empty(), polyfem::legacy::State::mesh, polyfem::legacy::State::solve_data, and polyfem::DiffCache::u().
Referenced by polyfem::solver::FrictionVariableToSimulation::compute_adjoint_term().
dJ_initial_condition_adjoint_term()
void polyfem::solver::AdjointTools::dJ_initial_condition_adjoint_term (const legacy::State & state, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 992 of file AdjointTools.cpp.
References polyfem::legacy::State::boundary_nodes, and polyfem::legacy::State::ndof().
Referenced by polyfem::solver::InitialConditionVariableToSimulation::compute_adjoint_term().
dJ_material_static_adjoint_term()
void polyfem::solver::AdjointTools::dJ_material_static_adjoint_term (const legacy::State & state, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form)
Definition at line 841 of file AdjointTools.cpp.
References polyfem::legacy::State::boundary_nodes, polyfem::solver::SolveData::elastic_form, and polyfem::legacy::State::solve_data.
Referenced by polyfem::solver::ElasticVariableToSimulation::compute_adjoint_term().
dJ_material_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_material_transient_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 852 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::bases, polyfem::legacy::State::boundary_nodes, polyfem::solver::SolveData::elastic_form, polyfem::legacy::State::solve_data, and polyfem::DiffCache::u().
Referenced by polyfem::solver::ElasticVariableToSimulation::compute_adjoint_term().
dJ_periodic_shape_adjoint_term()
void polyfem::solver::AdjointTools::dJ_periodic_shape_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const PeriodicMeshToMesh & periodic_mesh_map, const Eigen::VectorXd & periodic_mesh_representation, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form)
Definition at line 691 of file AdjointTools.cpp.
References polyfem::solver::PeriodicMeshToMesh::apply_jacobian(), polyfem::DiffCache::basis_nodes_to_gbasis_nodes(), polyfem::DiffCache::disp_grad(), dJ_shape_homogenization_adjoint_term(), polyfem::legacy::State::mesh, polyfem::legacy::State::mesh_nodes, polyfem::legacy::State::n_bases, polyfem::solver::SolveData::nl_problem, polyfem::solver::SolveData::periodic_contact_form, polyfem::legacy::State::primitive_to_node(), and polyfem::legacy::State::solve_data.
Referenced by polyfem::solver::PeriodicShapeVariableToSimulation::compute_adjoint_term().
dJ_pressure_static_adjoint_term()
void polyfem::solver::AdjointTools::dJ_pressure_static_adjoint_term (const legacy::State & state, const std::vector< int > & boundary_ids, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form)
Definition at line 1057 of file AdjointTools.cpp.
References polyfem::legacy::State::n_geom_bases, polyfem::solver::SolveData::pressure_form, and polyfem::legacy::State::solve_data.
Referenced by polyfem::solver::PressureBoundaryVariableToSimulation::compute_adjoint_term().
dJ_pressure_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_pressure_transient_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const std::vector< int > & boundary_ids, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 1081 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::boundary_nodes, polyfem::legacy::State::n_geom_bases, polyfem::solver::SolveData::pressure_form, polyfem::legacy::State::solve_data, and polyfem::DiffCache::u().
Referenced by polyfem::solver::PressureBoundaryVariableToSimulation::compute_adjoint_term().
dJ_shape_homogenization_adjoint_term()
void polyfem::solver::AdjointTools::dJ_shape_homogenization_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form)
Definition at line 636 of file AdjointTools.cpp.
References polyfem::DiffCache::basis_nodes_to_gbasis_nodes(), polyfem::DiffCache::collision_set(), polyfem::solver::SolveData::contact_form, polyfem::solver::SolveData::elastic_form, polyfem::legacy::State::is_adhesion_enabled(), polyfem::legacy::State::mesh, polyfem::legacy::State::mesh_nodes, polyfem::legacy::State::n_bases, polyfem::legacy::State::n_geom_bases, polyfem::solver::SolveData::nl_problem, polyfem::DiffCache::normal_adhesion_collision_set(), polyfem::solver::SolveData::normal_adhesion_form, polyfem::legacy::State::primitive_to_node(), polyfem::DiffCache::smooth_collision_set(), and polyfem::legacy::State::solve_data.
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term(), and dJ_periodic_shape_adjoint_term().
dJ_shape_static_adjoint_term()
void polyfem::solver::AdjointTools::dJ_shape_static_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & sol, const Eigen::MatrixXd & adjoint, Eigen::VectorXd & one_form)
Definition at line 576 of file AdjointTools.cpp.
References polyfem::DiffCache::basis_nodes_to_gbasis_nodes(), polyfem::solver::SolveData::body_form, polyfem::legacy::State::boundary_nodes, polyfem::DiffCache::collision_set(), polyfem::solver::SolveData::contact_form, polyfem::solver::SolveData::elastic_form, polyfem::legacy::State::is_adhesion_enabled(), polyfem::legacy::State::is_contact_enabled(), polyfem::legacy::State::mesh, polyfem::legacy::State::n_geom_bases, polyfem::DiffCache::normal_adhesion_collision_set(), polyfem::solver::SolveData::normal_adhesion_form, polyfem::solver::SolveData::pressure_form, polyfem::legacy::State::primitive_to_node(), polyfem::DiffCache::smooth_collision_set(), and polyfem::legacy::State::solve_data.
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term().
dJ_shape_transient_adjoint_term()
void polyfem::solver::AdjointTools::dJ_shape_transient_adjoint_term (const legacy::State & state, const DiffCache & diff_cache, const Eigen::MatrixXd & adjoint_nu, const Eigen::MatrixXd & adjoint_p, Eigen::VectorXd & one_form)
Definition at line 732 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::bases, polyfem::DiffCache::basis_nodes_to_gbasis_nodes(), polyfem::solver::SolveData::body_form, polyfem::legacy::State::boundary_nodes, polyfem::DiffCache::collision_set(), polyfem::solver::SolveData::contact_form, polyfem::solver::SolveData::damping_form, polyfem::solver::SolveData::elastic_form, polyfem::DiffCache::friction_collision_set(), polyfem::solver::SolveData::friction_form, polyfem::legacy::State::geom_bases(), polyfem::solver::SolveData::inertia_form, polyfem::legacy::State::is_adhesion_enabled(), polyfem::legacy::State::is_contact_enabled(), polyfem::legacy::State::mass_ass_vals_cache, polyfem::legacy::State::mass_matrix_assembler, polyfem::legacy::State::mesh, polyfem::legacy::State::n_geom_bases, polyfem::DiffCache::normal_adhesion_collision_set(), polyfem::solver::SolveData::normal_adhesion_form, polyfem::solver::SolveData::pressure_form, polyfem::legacy::State::primitive_to_node(), polyfem::DiffCache::smooth_collision_set(), polyfem::legacy::State::solve_data, polyfem::DiffCache::tangential_adhesion_collision_set(), polyfem::solver::SolveData::tangential_adhesion_form, polyfem::DiffCache::u(), and polyfem::DiffCache::v().
Referenced by polyfem::solver::ShapeVariableToSimulation::compute_adjoint_term().
edge_normal_gradient()
Eigen::MatrixXd polyfem::solver::AdjointTools::edge_normal_gradient (const Eigen::MatrixXd & V)
Definition at line 1388 of file AdjointTools.cpp.
References DiffScalarBase::setVariableCount(), and V.
edge_velocity_divergence()
Eigen::MatrixXd polyfem::solver::AdjointTools::edge_velocity_divergence (const Eigen::MatrixXd & V)
Definition at line 1420 of file AdjointTools.cpp.
References V.
face_normal_gradient()
Eigen::MatrixXd polyfem::solver::AdjointTools::face_normal_gradient (const Eigen::MatrixXd & V)
Definition at line 1404 of file AdjointTools.cpp.
References DiffScalarBase::setVariableCount(), and V.
face_velocity_divergence()
Eigen::MatrixXd polyfem::solver::AdjointTools::face_velocity_divergence (const Eigen::MatrixXd & V)
Definition at line 1425 of file AdjointTools.cpp.
References V.
integrate_objective()
double polyfem::solver::AdjointTools::integrate_objective (const legacy::State & state, const IntegrableFunctional & j, const Eigen::MatrixXd & solution, const std::set< int > & interested_ids, const SpatialIntegralType spatial_integral_type, const int cur_step = 0)
Definition at line 207 of file AdjointTools.cpp.
References polyfem::legacy::State::args, polyfem::legacy::State::ass_vals_cache, polyfem::legacy::State::assembler, polyfem::legacy::State::bases, polyfem::IntegrableFunctional::ParameterType::body_id, polyfem::assembler::AssemblyValsCache::compute(), polyfem::utils::create_thread_storage(), polyfem::assembler::ElementAssemblyValues::det, polyfem::IntegrableFunctional::ParameterType::elem, polyfem::IntegrableFunctional::evaluate(), polyfem::legacy::State::geom_bases(), polyfem::utils::get_local_thread_storage(), polyfem::io::Evaluator::interpolate_at_local_vals(), polyfem::utils::maybe_parallel_for(), polyfem::legacy::State::mesh, polyfem::quadrature::Quadrature::points, polyfem::legacy::State::problem, polyfem::assembler::ElementAssemblyValues::quadrature, quadrature, polyfem::IntegrableFunctional::ParameterType::step, polyfem::solver::Surface, polyfem::IntegrableFunctional::ParameterType::t, polyfem::legacy::State::total_local_boundary, polyfem::assembler::ElementAssemblyValues::val, vals, polyfem::solver::Volume, and polyfem::quadrature::Quadrature::weights.
Referenced by polyfem::solver::SpatialIntegralForm::value_unweighted_step().
map_node_to_primitive_order()
Eigen::VectorXd polyfem::solver::AdjointTools::map_node_to_primitive_order (const legacy::State & state, const Eigen::VectorXd & nodes)
Definition at line 1377 of file AdjointTools.cpp.
References polyfem::legacy::State::mesh, polyfem::legacy::State::n_geom_bases, and polyfem::legacy::State::node_to_primitive().
Referenced by polyfem::solver::AMIPSForm::compute_partial_gradient(), polyfem::solver::CollisionBarrierForm::compute_partial_gradient(), polyfem::solver::DeformedCollisionBarrierForm::compute_partial_gradient(), polyfem::solver::SmoothContactForceForm::compute_partial_gradient_step(), and polyfem::solver::ProxyContactForceForm::compute_partial_gradient_step().
map_primitive_to_node_order()
Eigen::VectorXd polyfem::solver::AdjointTools::map_primitive_to_node_order (const legacy::State & state, const Eigen::VectorXd & primitives)
Definition at line 1366 of file AdjointTools.cpp.
References polyfem::legacy::State::mesh, polyfem::legacy::State::n_geom_bases, and polyfem::legacy::State::primitive_to_node().
Referenced by polyfem::solver::AMIPSForm::compute_partial_gradient(), polyfem::solver::CollisionBarrierForm::get_updated_mesh_nodes(), polyfem::solver::DeformedCollisionBarrierForm::get_updated_mesh_nodes(), and polyfem::solver::AMIPSForm::value_unweighted().
scaled_jacobian()
void polyfem::solver::AdjointTools::scaled_jacobian (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F, Eigen::VectorXd & quality)
Definition at line 1430 of file AdjointTools.cpp.
References V.