PolyFEM: elasticity_rhs Namespace Reference
elasticity_rhs Namespace Reference
Functions
def Det (mat)
def sigma_fun (j, ee, C, dim)
def linear_elasticity (disp_grad, def_grad)
def hooke (disp_grad, def_grad)
def saint_venant (disp_grad, def_grad)
def neo_hookean (disp_grad, def_grad)
def divergence (sigma)
def parse_args ()
Variables
def args = parse_args()
list dims = [2, 3]
list names = ["linear_elasticity", "hooke", "saint_venant", "neo_hookean"]
string cpp = "#include <polyfem/autogen/auto_elasticity_rhs.hpp>\n\n\n"
string hpp = "#pragma once\n\n#include <polyfem/utils/ElasticityUtils.hpp>\n#include <polyfem/utils/AutodiffTypes.hpp>\n#include <Eigen/Dense>\n\n"
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')
X = Matrix([x, y])
f = Matrix([Function('f0')(x, y), Function('f1')(x, y)])
disp_grad = f.jacobian(X)
tuple def_grad = (eye(dim) + disp_grad)
def sigma = hooke(disp_grad, def_grad)
def div = divergence(sigma)
c99 = pretty_print.C99_print(div)
string signature = "void " + name + "_" + str(dim) + "d_function(const AutodiffHessianPt &pt"
path = os.path.abspath(args.output)
Function Documentation
Det()
def elasticity_rhs.Det (mat)
Definition at line 13 of file elasticity_rhs.py.
divergence()
def elasticity_rhs.divergence (sigma)
Definition at line 130 of file elasticity_rhs.py.
hooke()
def elasticity_rhs.hooke (disp_grad, def_grad)
Definition at line 53 of file elasticity_rhs.py.
References sigma_fun().
linear_elasticity()
def elasticity_rhs.linear_elasticity (disp_grad, def_grad)
Definition at line 36 of file elasticity_rhs.py.
neo_hookean()
def elasticity_rhs.neo_hookean (disp_grad, def_grad)
Definition at line 109 of file elasticity_rhs.py.
parse_args()
def elasticity_rhs.parse_args ()
Definition at line 146 of file elasticity_rhs.py.
saint_venant()
def elasticity_rhs.saint_venant (disp_grad, def_grad)
Definition at line 80 of file elasticity_rhs.py.
References sigma_fun().
sigma_fun()
def elasticity_rhs.sigma_fun (j, ee, C, dim)
Definition at line 27 of file elasticity_rhs.py.
Referenced by hooke(), and saint_venant().
Variable Documentation
args
def elasticity_rhs.args = parse_args()
Definition at line 155 of file elasticity_rhs.py.
c99
elasticity_rhs.c99 = pretty_print.C99_print(div)
Definition at line 192 of file elasticity_rhs.py.
cpp
string elasticity_rhs.cpp = "#include <polyfem/autogen/auto_elasticity_rhs.hpp>\n\n\n"
Definition at line 158 of file elasticity_rhs.py.
def_grad
tuple elasticity_rhs.def_grad = (eye(dim) + disp_grad)
Definition at line 179 of file elasticity_rhs.py.
dims
list elasticity_rhs.dims = [2, 3]
Definition at line 156 of file elasticity_rhs.py.
disp_grad
elasticity_rhs.disp_grad = f.jacobian(X)
Definition at line 178 of file elasticity_rhs.py.
div
def elasticity_rhs.div = divergence(sigma)
Definition at line 190 of file elasticity_rhs.py.
f
elasticity_rhs.f = Matrix([Function('f0')(x, y), Function('f1')(x, y)])
Definition at line 173 of file elasticity_rhs.py.
hpp
string elasticity_rhs.hpp = "#pragma once\n\n#include <polyfem/utils/ElasticityUtils.hpp>\n#include <polyfem/utils/AutodiffTypes.hpp>\n#include <Eigen/Dense>\n\n"
Definition at line 159 of file elasticity_rhs.py.
names
list elasticity_rhs.names = ["linear_elasticity", "hooke", "saint_venant", "neo_hookean"]
Definition at line 157 of file elasticity_rhs.py.
path
elasticity_rhs.path = os.path.abspath(args.output)
Definition at line 239 of file elasticity_rhs.py.
sigma
def elasticity_rhs.sigma = hooke(disp_grad, def_grad)
Definition at line 182 of file elasticity_rhs.py.
signature
string elasticity_rhs.signature = "void " + name + "_" + str(dim) + "d_function(const AutodiffHessianPt &pt"
Definition at line 223 of file elasticity_rhs.py.
x
elasticity_rhs.x = Symbol('x')
Definition at line 163 of file elasticity_rhs.py.
X
elasticity_rhs.X = Matrix([x, y])
Definition at line 172 of file elasticity_rhs.py.
y
elasticity_rhs.y = Symbol('y')
Definition at line 164 of file elasticity_rhs.py.
z
elasticity_rhs.z = Symbol('z')
Definition at line 165 of file elasticity_rhs.py.