var namespacepolyfem_1_1varform =
[
    [ "internal", "namespacepolyfem_1_1varform_1_1internal.html", [
      [ "expand_primary_matrix", "namespacepolyfem_1_1varform_1_1internal.html#ade6c7a5b67b520c40a392cdc688cbcbd", null ],
      [ "sample_scalar_field", "namespacepolyfem_1_1varform_1_1internal.html#a5cbcab708d89337eb7f6d6b353232ce0", null ],
      [ "write_matrix_market", "namespacepolyfem_1_1varform_1_1internal.html#a3d809effc778c166eb1b6a9ccb12eecf", null ]
    ] ],
    [ "BilaplacianVarForm", "classpolyfem_1_1varform_1_1_bilaplacian_var_form.html", "classpolyfem_1_1varform_1_1_bilaplacian_var_form" ],
    [ "DifferentiableLinearElasticVarForm", "classpolyfem_1_1varform_1_1_differentiable_linear_elastic_var_form.html", "classpolyfem_1_1varform_1_1_differentiable_linear_elastic_var_form" ],
    [ "DifferentiableNonlinearElasticStaticVarForm", "classpolyfem_1_1varform_1_1_differentiable_nonlinear_elastic_static_var_form.html", "classpolyfem_1_1varform_1_1_differentiable_nonlinear_elastic_static_var_form" ],
    [ "DifferentiableNonlinearElasticTransientVarForm", "classpolyfem_1_1varform_1_1_differentiable_nonlinear_elastic_transient_var_form.html", "classpolyfem_1_1varform_1_1_differentiable_nonlinear_elastic_transient_var_form" ],
    [ "DifferentiableNonlinearElasticVarForm", "classpolyfem_1_1varform_1_1_differentiable_nonlinear_elastic_var_form.html", "classpolyfem_1_1varform_1_1_differentiable_nonlinear_elastic_var_form" ],
    [ "DifferentiableScalarVarForm", "classpolyfem_1_1varform_1_1_differentiable_scalar_var_form.html", "classpolyfem_1_1varform_1_1_differentiable_scalar_var_form" ],
    [ "DifferentiableVarForm", "classpolyfem_1_1varform_1_1_differentiable_var_form.html", "classpolyfem_1_1varform_1_1_differentiable_var_form" ],
    [ "ElasticVarForm", "classpolyfem_1_1varform_1_1_elastic_var_form.html", "classpolyfem_1_1varform_1_1_elastic_var_form" ],
    [ "FESpace", "classpolyfem_1_1varform_1_1_f_e_space.html", "classpolyfem_1_1varform_1_1_f_e_space" ],
    [ "FluidVarForm", "classpolyfem_1_1varform_1_1_fluid_var_form.html", "classpolyfem_1_1varform_1_1_fluid_var_form" ],
    [ "GeometryMapping", "classpolyfem_1_1varform_1_1_geometry_mapping.html", "classpolyfem_1_1varform_1_1_geometry_mapping" ],
    [ "IncompressibleElasticVarForm", "classpolyfem_1_1varform_1_1_incompressible_elastic_var_form.html", "classpolyfem_1_1varform_1_1_incompressible_elastic_var_form" ],
    [ "InitialConditionOverride", "structpolyfem_1_1varform_1_1_initial_condition_override.html", "structpolyfem_1_1varform_1_1_initial_condition_override" ],
    [ "LinearElasticVarForm", "classpolyfem_1_1varform_1_1_linear_elastic_var_form.html", "classpolyfem_1_1varform_1_1_linear_elastic_var_form" ],
    [ "NavierStokesFSIVarForm", "classpolyfem_1_1varform_1_1_navier_stokes_f_s_i_var_form.html", "classpolyfem_1_1varform_1_1_navier_stokes_f_s_i_var_form" ],
    [ "NavierStokesVarForm", "classpolyfem_1_1varform_1_1_navier_stokes_var_form.html", "classpolyfem_1_1varform_1_1_navier_stokes_var_form" ],
    [ "NonlinearElasticStaticVarForm", "classpolyfem_1_1varform_1_1_nonlinear_elastic_static_var_form.html", "classpolyfem_1_1varform_1_1_nonlinear_elastic_static_var_form" ],
    [ "NonlinearElasticTransientVarForm", "classpolyfem_1_1varform_1_1_nonlinear_elastic_transient_var_form.html", "classpolyfem_1_1varform_1_1_nonlinear_elastic_transient_var_form" ],
    [ "NonlinearElasticVarForm", "classpolyfem_1_1varform_1_1_nonlinear_elastic_var_form.html", "classpolyfem_1_1varform_1_1_nonlinear_elastic_var_form" ],
    [ "OperatorSplittingVarForm", "classpolyfem_1_1varform_1_1_operator_splitting_var_form.html", "classpolyfem_1_1varform_1_1_operator_splitting_var_form" ],
    [ "ScalarVarForm", "classpolyfem_1_1varform_1_1_scalar_var_form.html", "classpolyfem_1_1varform_1_1_scalar_var_form" ],
    [ "StokesVarForm", "classpolyfem_1_1varform_1_1_stokes_var_form.html", "classpolyfem_1_1varform_1_1_stokes_var_form" ],
    [ "ThermoElasticVarForm", "classpolyfem_1_1varform_1_1_thermo_elastic_var_form.html", "classpolyfem_1_1varform_1_1_thermo_elastic_var_form" ],
    [ "VarForm", "classpolyfem_1_1varform_1_1_var_form.html", "classpolyfem_1_1varform_1_1_var_form" ],
    [ "VarFormBoundaryState", "structpolyfem_1_1varform_1_1_var_form_boundary_state.html", "structpolyfem_1_1varform_1_1_var_form_boundary_state" ],
    [ "VarFormFactory", "classpolyfem_1_1varform_1_1_var_form_factory.html", null ],
    [ "ForwardStepCallback", "namespacepolyfem_1_1varform.html#a213fe561712fd8d6ce35d6bbc882d31c", null ],
    [ "formulation_from_args", "namespacepolyfem_1_1varform.html#a13760d3cf0705a6cac9d9d5a79011cb3", null ],
    [ "uses_varform_state", "namespacepolyfem_1_1varform.html#aabf6642627c1d8074aebcca490a81f86", null ]
];