PolyFEM: polyfem::mesh::Navigation Namespace Reference
polyfem::mesh::Navigation Namespace Reference
Classes
struct Index
Functions
void prepare_mesh (GEO::Mesh &M)
Index get_index_from_face (const GEO::Mesh &M, const GEO::Attribute< GEO::index_t > &c2e, int f, int lv)
Index switch_vertex (const GEO::Mesh &M, Index idx)
Index switch_edge (const GEO::Mesh &M, const GEO::Attribute< GEO::index_t > &c2e, Index idx)
Index switch_face (const GEO::Mesh &M, const GEO::Attribute< GEO::index_t > &c2e, Index idx)
Index next_around_face (const GEO::Mesh &M, const GEO::Attribute< GEO::index_t > &c2e, Index idx)
Index next_around_edge (const GEO::Mesh &M, const GEO::Attribute< GEO::index_t > &c2e, Index idx)
Index next_around_vertex (const GEO::Mesh &M, const GEO::Attribute< GEO::index_t > &c2e, Index idx)
Function Documentation
get_index_from_face()
Index polyfem::mesh::Navigation::get_index_from_face (const GEO::Mesh & M, const GEO::Attribute< GEO::index_t > & c2e, int f, int lv)
Definition at line 96 of file Navigation.cpp.
References polyfem::mesh::Navigation::Index::edge, elasticity_rhs::f, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, eigs::M, switch_edge(), switch_vertex(), and polyfem::mesh::Navigation::Index::vertex.
Referenced by polyfem::mesh::create_patch_around_singularities(), polyfem::mesh::CMesh2D::get_index_from_face(), polyfem::mesh::refine_polygonal_mesh(), and polyfem::mesh::refine_triangle_mesh().
next_around_edge()
Index polyfem::mesh::Navigation::next_around_edge (const GEO::Mesh & M, const GEO::Attribute< GEO::index_t > & c2e, Index idx) inline
Definition at line 35 of file Navigation.hpp.
References eigs::M, switch_face(), and switch_vertex().
next_around_face()
Index polyfem::mesh::Navigation::next_around_face (const GEO::Mesh & M, const GEO::Attribute< GEO::index_t > & c2e, Index idx) inline
Definition at line 34 of file Navigation.hpp.
References eigs::M, switch_edge(), and switch_vertex().
Referenced by polyfem::mesh::create_patch_around_singularities(), polyfem::mesh::refine_polygonal_mesh(), and polyfem::mesh::refine_triangle_mesh().
next_around_vertex()
Index polyfem::mesh::Navigation::next_around_vertex (const GEO::Mesh & M, const GEO::Attribute< GEO::index_t > & c2e, Index idx) inline
Definition at line 36 of file Navigation.hpp.
References eigs::M, switch_edge(), and switch_face().
prepare_mesh()
void polyfem::mesh::Navigation::prepare_mesh (GEO::Mesh & M)
Definition at line 27 of file Navigation.cpp.
References elasticity_rhs::f, and eigs::M.
Referenced by polyfem::mesh::CMesh2D::build_from_matrices(), polyfem::mesh::CMesh2D::load(), and polyfem::mesh::CMesh2D::refine().
switch_edge()
Index polyfem::mesh::Navigation::switch_edge (const GEO::Mesh & M, const GEO::Attribute< GEO::index_t > & c2e, Index idx)
Definition at line 136 of file Navigation.cpp.
References polyfem::mesh::Navigation::Index::edge, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, eigs::M, and polyfem::mesh::Navigation::Index::vertex.
Referenced by polyfem::mesh::create_patch_around_singularities(), polyfem::mesh::Navigation3D::get_index_from_element_tri(), get_index_from_face(), next_around_face(), next_around_vertex(), polyfem::mesh::refine_polygonal_mesh(), polyfem::mesh::refine_triangle_mesh(), and polyfem::mesh::CMesh2D::switch_edge().
switch_face()
Index polyfem::mesh::Navigation::switch_face (const GEO::Mesh & M, const GEO::Attribute< GEO::index_t > & c2e, Index idx)
Definition at line 159 of file Navigation.cpp.
References polyfem::mesh::Navigation::Index::edge, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, polyfem::logger(), eigs::M, and polyfem::mesh::Navigation::Index::vertex.
Referenced by next_around_edge(), next_around_vertex(), and polyfem::mesh::CMesh2D::switch_face().
switch_vertex()
Index polyfem::mesh::Navigation::switch_vertex (const GEO::Mesh & M, Index idx)
Definition at line 115 of file Navigation.cpp.
References polyfem::mesh::Navigation::Index::edge, polyfem::mesh::Navigation::Index::face, polyfem::mesh::Navigation::Index::face_corner, eigs::M, and polyfem::mesh::Navigation::Index::vertex.
Referenced by polyfem::mesh::create_patch_around_singularities(), polyfem::mesh::Navigation3D::get_index_from_element_edge(), polyfem::mesh::Navigation3D::get_index_from_element_tri(), get_index_from_face(), next_around_edge(), next_around_face(), polyfem::mesh::refine_polygonal_mesh(), polyfem::mesh::refine_triangle_mesh(), and polyfem::mesh::CMesh2D::switch_vertex().