PolyFEM: polyfem::problem Namespace Reference
polyfem::problem Namespace Reference
Classes
class Airfoil
class BilaplacianProblemWithSolution
class CompressionElasticProblemExact
class ConstantVelocity
class CornerFlow
class CubicProblem
class DoubleTorsionElasticProblem
class DrivenCavity
class DrivenCavityC0
class DrivenCavitySmooth
class ElasticCantileverExact
class ElasticProblem
class ElasticProblemExact
class ElasticProblemZeroBC
class Flow
class FlowWithObstacle
class FrankeProblem
class FrankeProblemOld
class GenericScalarProblemExact
class GravityProblem
class KernelProblem
class Kovnaszy
class LinearElasticProblemExact
class LinearProblem
class Lshape
class MinSurfProblem
class NodeProblem
class NodeValues
class PointBasedTensorProblem
class ProblemFactory
class ProblemWithSolution
class QuadraticElasticProblemExact
class QuadraticProblem
class SimpleStokeProblemExact
class SineProblem
class SineStokeProblemExact
class StokesLawProblem
class TaylorGreenVortexProblem
class TestProblem
class TimeDependentProblem
class TimeDepentendStokesProblem
class TorsionElasticProblem
class TransientStokeProblemExact
class TwoSpheres
class UnitFlowWithObstacle
class WalkProblem
class ZeroBCProblem
Functions
template<typename T >
Eigen::Matrix< T, 2, 1 > simple_function_const (T x, T y, const double t)
template<typename T >
Eigen::Matrix< T, 3, 1 > simple_function_const (T x, T y, T z, const double t)
template<typename T >
Eigen::Matrix< T, 2, 1 > simple_function_lin (T x, T y, const double t)
template<typename T >
Eigen::Matrix< T, 3, 1 > simple_function_lin (T x, T y, T z, const double t)
template<typename T >
Eigen::Matrix< T, 2, 1 > simple_function_cub (T x, T y, const double t)
template<typename T >
Eigen::Matrix< T, 3, 1 > simple_function_cub (T x, T y, T z, const double t)
template<typename T >
Eigen::Matrix< T, 2, 1 > simple_function_quad (T x, T y, const double t)
template<typename T >
Eigen::Matrix< T, 3, 1 > simple_function_quad (T x, T y, T z, const double t)
template<typename T >
Eigen::Matrix< T, 2, 1 > sine_function (T x, T y, const double t)
template<typename T >
Eigen::Matrix< T, 3, 1 > sine_function (T x, T y, T z, const double t)
Function Documentation
simple_function_const() [1/2]
template<typename T > Eigen::Matrix< T, 2, 1 > polyfem::problem::simple_function_const (T x, T y, const double t)
Definition at line 907 of file StokesProblem.cpp.
Referenced by polyfem::problem::SimpleStokeProblemExact::eval_fun().
simple_function_const() [2/2]
template<typename T > Eigen::Matrix< T, 3, 1 > polyfem::problem::simple_function_const (T x, T y, T z, const double t)
Definition at line 918 of file StokesProblem.cpp.
simple_function_cub() [1/2]
template<typename T > Eigen::Matrix< T, 2, 1 > polyfem::problem::simple_function_cub (T x, T y, const double t)
Definition at line 953 of file StokesProblem.cpp.
References x, and y.
Referenced by polyfem::problem::SimpleStokeProblemExact::eval_fun().
simple_function_cub() [2/2]
template<typename T > Eigen::Matrix< T, 3, 1 > polyfem::problem::simple_function_cub (T x, T y, T z, const double t)
Definition at line 964 of file StokesProblem.cpp.
References x, and y.
simple_function_lin() [1/2]
template<typename T > Eigen::Matrix< T, 2, 1 > polyfem::problem::simple_function_lin (T x, T y, const double t)
Definition at line 930 of file StokesProblem.cpp.
References x, and y.
Referenced by polyfem::problem::SimpleStokeProblemExact::eval_fun().
simple_function_lin() [2/2]
template<typename T > Eigen::Matrix< T, 3, 1 > polyfem::problem::simple_function_lin (T x, T y, T z, const double t)
Definition at line 941 of file StokesProblem.cpp.
References x, and y.
simple_function_quad() [1/2]
template<typename T > Eigen::Matrix< T, 2, 1 > polyfem::problem::simple_function_quad (T x, T y, const double t)
Definition at line 976 of file StokesProblem.cpp.
References x, and y.
Referenced by polyfem::problem::SimpleStokeProblemExact::eval_fun().
simple_function_quad() [2/2]
template<typename T > Eigen::Matrix< T, 3, 1 > polyfem::problem::simple_function_quad (T x, T y, T z, const double t)
Definition at line 987 of file StokesProblem.cpp.
References x, and y.
sine_function() [1/2]
template<typename T > Eigen::Matrix< T, 2, 1 > polyfem::problem::sine_function (T x, T y, const double t)
Definition at line 999 of file StokesProblem.cpp.
References x, and y.
Referenced by polyfem::problem::SineStokeProblemExact::eval_fun().
sine_function() [2/2]
template<typename T > Eigen::Matrix< T, 3, 1 > polyfem::problem::sine_function (T x, T y, T z, const double t)
Definition at line 1010 of file StokesProblem.cpp.
References x, and y.