PolyFEM: polyfem::assembler Namespace Reference
polyfem::assembler Namespace Reference
Used for test only.
Classes
class AdiabaticProcess
class AMIPSEnergy
class Assembler
abstract class
class AssemblerUtils
class AssemblyValsCache
Caches basis evaluation and geometric mapping at every element.
class AssemblyValues
stores per local bases evaluations
class BilaplacianAux
class BilaplacianMain
class BilaplacianMixed
class Density
class ElasticityAssembler
class ElasticityTensor
class ElementAssemblyValues
stores per element basis values at given quadrature points and geometric mapping
class GenericElastic
class GenericMatParam
class GenericMatParams
class GenericScalarProblem
class GenericTensorProblem
class Helmholtz
class HookeLinearElasticity
class IncompressibleLinearElasticityDispacement
class IncompressibleLinearElasticityMixed
class IncompressibleLinearElasticityPressure
class IncompressibleOgdenElasticity
class IsothermalProcess
class LameParameters
class Laplacian
class LinearAssembler
assemble matrix based on the local assembler local assembler is eg Laplace, LinearElasticity etc
class LinearAssemblerData
class LinearElasticity
class MacroStrainValue
class Mass
class MassMatrixAssembler
class MixedAssembler
class MixedAssemblerData
class MooneyRivlin3ParamElasticity
class MooneyRivlin3ParamSymbolic
class MooneyRivlinElasticity
class MultiModel
class NavierStokesVelocity
class NeoHookeanAutodiff
class NeoHookeanElasticity
class NLAssembler
class NoDensity
class NonLinearAssemblerData
class OperatorSplitting
class OptAssemblerData
class OutputData
class PressureAssembler
class Problem
class RhsAssembler
class SaintVenantElasticity
struct ScalarBCValue
class StokesMixed
class StokesPressure
class StokesVelocity
struct TensorBCValue
class ThermodynamicProcess
class UnconstrainedOgdenElasticity
class ViscousDamping
class ViscousDampingPrev
Typedefs
template<typename T >
using DefGradMatrix = Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 >
template<typename T >
using AutoDiffGradMat = Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3 >
template<typename T >
using AutoDiffVect = Eigen::Matrix< T, Eigen::Dynamic, 1 >
Functions
template<int dim>
Eigen::Matrix< double, dim, dim > hat (const Eigen::Matrix< double, dim, 1 > &x)
template<int dim>
Eigen::Matrix< double, dim, 1 > cross (const Eigen::Matrix< double, dim, 1 > &x, const Eigen::Matrix< double, dim, 1 > &y)
Detailed Description
Used for test only.
Typedef Documentation
AutoDiffGradMat
template<typename T > using polyfem::assembler::AutoDiffGradMat = typedef Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3>
Definition at line 12 of file MooneyRivlin3ParamSymbolic.hpp.
AutoDiffVect
template<typename T > using polyfem::assembler::AutoDiffVect = typedef Eigen::Matrix<T, Eigen::Dynamic, 1>
Definition at line 14 of file MooneyRivlin3ParamSymbolic.hpp.
DefGradMatrix
template<typename T > using polyfem::assembler::DefGradMatrix = typedef Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, 0, 3, 3>
Definition at line 10 of file GenericElastic.hpp.
Function Documentation
cross()
template<int dim> Eigen::Matrix< double, dim, 1 > polyfem::assembler::cross (const Eigen::Matrix< double, dim, 1 > & x, const Eigen::Matrix< double, dim, 1 > & y)
Definition at line 357 of file NeoHookeanElasticity.cpp.
References x, y, and z.
Referenced by polyfem::utils::are_triangles_coplanar(), polyfem::utils::TetrahedronClipping::clip(), and polyfem::mesh::irregular_triangle().
hat()
template<int dim> Eigen::Matrix< double, dim, dim > polyfem::assembler::hat (const Eigen::Matrix< double, dim, 1 > & x)
Definition at line 340 of file NeoHookeanElasticity.cpp.
References x.