PolyFEM: DiffScalarBase Struct Reference
DiffScalarBase Struct Reference
Base class of all automatic differentiation types.
#include <autodiff.h>
Static Public Member Functions
Configuration
static void setVariableCount (size_t value)
Set the independent variable count used by the automatic differentiation layer.
static size_t getVariableCount ()
Get the variable count used by the automatic differentiation layer.
Static Public Attributes
static thread_local size_t m_variableCount
Detailed Description
Base class of all automatic differentiation types.
This class records the number of independent variables with respect to which derivatives are computed.
Definition at line 40 of file autodiff.h.
Member Function Documentation
getVariableCount()
static size_t DiffScalarBase::getVariableCount () inline static
Get the variable count used by the automatic differentiation layer.
Definition at line 60 of file autodiff.h.
References m_variableCount.
Referenced by DScalar1< _Scalar, _Gradient >::DScalar1(), and DScalar2< _Scalar, _Gradient, _Hessian >::DScalar2().
setVariableCount()
static void DiffScalarBase::setVariableCount (size_t value) inline static
Set the independent variable count used by the automatic differentiation layer.
This function must be called before doing any computations with DScalar1 or DScalar2. The value will be recorded in thread-local storage.
Definition at line 54 of file autodiff.h.
References m_variableCount.
Referenced by polyfem::assembler::LinearElasticity::compute_energy_aux(), polyfem::assembler::NeoHookeanElasticity::compute_energy_aux(), polyfem::assembler::OgdenElasticity::compute_energy_aux(), polyfem::assembler::SaintVenantElasticity::compute_energy_aux(), polyfem::problem::KernelProblem::eval_fun(), polyfem::problem::ElasticCantileverExact::exact_grad(), polyfem::problem::ProblemWithSolution::exact_grad(), polyfem::problem::ElasticCantileverExact::neumann_bc(), polyfem::problem::ElasticCantileverExact::rhs(), polyfem::problem::ProblemWithSolution::rhs(), and polyfem::basis::RBFWithQuadratic::setup_monomials_strong_2d().
Member Data Documentation
m_variableCount
thread_local size_t DiffScalarBase::m_variableCount static
Definition at line 73 of file autodiff.h.
Referenced by getVariableCount(), and setVariableCount().
The documentation for this struct was generated from the following file:
src/polyfem/utils/autodiff.h