PolyFEM: polyfem::mesh::NCMesh3D::ncBoundary Struct Reference
polyfem::mesh::NCMesh3D::ncBoundary Struct Reference
#include <NCMesh3D.hpp>
Public Member Functions
ncBoundary (const Eigen::VectorXi vert)
~ncBoundary ()
int n_elem () const
void add_element (const int e)
void remove_element (const int e)
int get_element () const
int find_opposite_element (int e) const
Public Attributes
std::set< int > elem_list
Eigen::VectorXi vertices
bool isboundary = false
int boundary_id = 0
int leader = -1
std::vector< int > followers
int leader_face = -1
std::vector< int > global_ids
Eigen::Vector2d weights
Detailed Description
Definition at line 73 of file NCMesh3D.hpp.
Constructor & Destructor Documentation
ncBoundary()
polyfem::mesh::NCMesh3D::ncBoundary::ncBoundary (const Eigen::VectorXi vert) inline
Definition at line 75 of file NCMesh3D.hpp.
References weights.
~ncBoundary()
polyfem::mesh::NCMesh3D::ncBoundary::~ncBoundary () inline
Definition at line 79 of file NCMesh3D.hpp.
Member Function Documentation
add_element()
void polyfem::mesh::NCMesh3D::ncBoundary::add_element (const int e) inline
Definition at line 86 of file NCMesh3D.hpp.
References elem_list.
find_opposite_element()
int polyfem::mesh::NCMesh3D::ncBoundary::find_opposite_element (int e) const inline
Definition at line 104 of file NCMesh3D.hpp.
References elem_list, and n_elem().
get_element()
int polyfem::mesh::NCMesh3D::ncBoundary::get_element () const inline
Definition at line 97 of file NCMesh3D.hpp.
References elem_list, and n_elem().
n_elem()
int polyfem::mesh::NCMesh3D::ncBoundary::n_elem () const inline
Definition at line 81 of file NCMesh3D.hpp.
References elem_list.
Referenced by find_opposite_element(), and get_element().
remove_element()
void polyfem::mesh::NCMesh3D::ncBoundary::remove_element (const int e) inline
Definition at line 91 of file NCMesh3D.hpp.
References elem_list.
Member Data Documentation
boundary_id
int polyfem::mesh::NCMesh3D::ncBoundary::boundary_id = 0
Definition at line 124 of file NCMesh3D.hpp.
elem_list
std::set<int> polyfem::mesh::NCMesh3D::ncBoundary::elem_list
Definition at line 120 of file NCMesh3D.hpp.
Referenced by add_element(), find_opposite_element(), get_element(), n_elem(), and remove_element().
followers
std::vector<int> polyfem::mesh::NCMesh3D::ncBoundary::followers
Definition at line 127 of file NCMesh3D.hpp.
global_ids
std::vector<int> polyfem::mesh::NCMesh3D::ncBoundary::global_ids
Definition at line 131 of file NCMesh3D.hpp.
isboundary
bool polyfem::mesh::NCMesh3D::ncBoundary::isboundary = false
Definition at line 123 of file NCMesh3D.hpp.
leader
int polyfem::mesh::NCMesh3D::ncBoundary::leader = -1
Definition at line 126 of file NCMesh3D.hpp.
leader_face
int polyfem::mesh::NCMesh3D::ncBoundary::leader_face = -1
Definition at line 129 of file NCMesh3D.hpp.
vertices
Eigen::VectorXi polyfem::mesh::NCMesh3D::ncBoundary::vertices
Definition at line 121 of file NCMesh3D.hpp.
weights
Eigen::Vector2d polyfem::mesh::NCMesh3D::ncBoundary::weights
Definition at line 134 of file NCMesh3D.hpp.
Referenced by ncBoundary().
The documentation for this struct was generated from the following file:
src/polyfem/mesh/mesh3D/NCMesh3D.hpp