PolyFEM: polyfem::mesh::NCMesh2D::ncBoundary Struct Reference
polyfem::mesh::NCMesh2D::ncBoundary Struct Reference
#include <NCMesh2D.hpp>
Public Member Functions
ncBoundary (const Eigen::VectorXi vert)
~ncBoundary ()
int n_elem () const
void add_element (const int e)
void remove_element (const int e)
int get_element () const
int find_opposite_element (int e) const
Public Attributes
std::set< int > elem_list
Eigen::VectorXi vertices
bool isboundary = false
int boundary_id = -1
int leader = -1
std::vector< int > followers
int leader_face = -1
std::vector< int > global_ids
Eigen::Vector2d weights
Detailed Description
Definition at line 55 of file NCMesh2D.hpp.
Constructor & Destructor Documentation
ncBoundary()
polyfem::mesh::NCMesh2D::ncBoundary::ncBoundary (const Eigen::VectorXi vert) inline
Definition at line 57 of file NCMesh2D.hpp.
References weights.
~ncBoundary()
polyfem::mesh::NCMesh2D::ncBoundary::~ncBoundary () inline
Definition at line 61 of file NCMesh2D.hpp.
Member Function Documentation
add_element()
void polyfem::mesh::NCMesh2D::ncBoundary::add_element (const int e) inline
Definition at line 68 of file NCMesh2D.hpp.
References elem_list.
find_opposite_element()
int polyfem::mesh::NCMesh2D::ncBoundary::find_opposite_element (int e) const inline
Definition at line 86 of file NCMesh2D.hpp.
References elem_list, and n_elem().
get_element()
int polyfem::mesh::NCMesh2D::ncBoundary::get_element () const inline
Definition at line 79 of file NCMesh2D.hpp.
References elem_list, and n_elem().
n_elem()
int polyfem::mesh::NCMesh2D::ncBoundary::n_elem () const inline
Definition at line 63 of file NCMesh2D.hpp.
References elem_list.
Referenced by find_opposite_element(), and get_element().
remove_element()
void polyfem::mesh::NCMesh2D::ncBoundary::remove_element (const int e) inline
Definition at line 73 of file NCMesh2D.hpp.
References elem_list.
Member Data Documentation
boundary_id
int polyfem::mesh::NCMesh2D::ncBoundary::boundary_id = -1
Definition at line 106 of file NCMesh2D.hpp.
elem_list
std::set<int> polyfem::mesh::NCMesh2D::ncBoundary::elem_list
Definition at line 102 of file NCMesh2D.hpp.
Referenced by add_element(), find_opposite_element(), get_element(), n_elem(), and remove_element().
followers
std::vector<int> polyfem::mesh::NCMesh2D::ncBoundary::followers
Definition at line 109 of file NCMesh2D.hpp.
global_ids
std::vector<int> polyfem::mesh::NCMesh2D::ncBoundary::global_ids
Definition at line 113 of file NCMesh2D.hpp.
isboundary
bool polyfem::mesh::NCMesh2D::ncBoundary::isboundary = false
Definition at line 105 of file NCMesh2D.hpp.
leader
int polyfem::mesh::NCMesh2D::ncBoundary::leader = -1
Definition at line 108 of file NCMesh2D.hpp.
leader_face
int polyfem::mesh::NCMesh2D::ncBoundary::leader_face = -1
Definition at line 111 of file NCMesh2D.hpp.
vertices
Eigen::VectorXi polyfem::mesh::NCMesh2D::ncBoundary::vertices
Definition at line 103 of file NCMesh2D.hpp.
weights
Eigen::Vector2d polyfem::mesh::NCMesh2D::ncBoundary::weights
Definition at line 116 of file NCMesh2D.hpp.
Referenced by ncBoundary().
The documentation for this struct was generated from the following file:
src/polyfem/mesh/mesh2D/NCMesh2D.hpp