var searchData=
[
  ['laggedregform_0',['LaggedRegForm',['../classpolyfem_1_1solver_1_1_lagged_reg_form.html',1,'polyfem::solver']]],
  ['lagrange_1',['lagrange',['../classp__bases_1_1_lagrange.html',1,'p_bases.Lagrange'],['../classq__bases_1_1_lagrange.html',1,'q_bases.Lagrange']]],
  ['lagrangebasis2d_2',['LagrangeBasis2d',['../classpolyfem_1_1basis_1_1_lagrange_basis2d.html',1,'polyfem::basis']]],
  ['lagrangebasis3d_3',['LagrangeBasis3d',['../classpolyfem_1_1basis_1_1_lagrange_basis3d.html',1,'polyfem::basis']]],
  ['lameparameters_4',['LameParameters',['../classpolyfem_1_1assembler_1_1_lame_parameters.html',1,'polyfem::assembler']]],
  ['laplacian_5',['Laplacian',['../classpolyfem_1_1assembler_1_1_laplacian.html',1,'polyfem::assembler']]],
  ['lbfgsbsolver_6',['LBFGSBSolver',['../classcppoptlib_1_1_l_b_f_g_s_b_solver.html',1,'cppoptlib']]],
  ['lbfgssolver_7',['LBFGSSolver',['../classcppoptlib_1_1_l_b_f_g_s_solver.html',1,'cppoptlib']]],
  ['linearassembler_8',['LinearAssembler',['../classpolyfem_1_1assembler_1_1_linear_assembler.html',1,'polyfem::assembler']]],
  ['linearassemblerdata_9',['LinearAssemblerData',['../classpolyfem_1_1assembler_1_1_linear_assembler_data.html',1,'polyfem::assembler']]],
  ['linearelasticity_10',['LinearElasticity',['../classpolyfem_1_1assembler_1_1_linear_elasticity.html',1,'polyfem::assembler']]],
  ['linearelasticproblemexact_11',['LinearElasticProblemExact',['../classpolyfem_1_1problem_1_1_linear_elastic_problem_exact.html',1,'polyfem::problem']]],
  ['linearfilter_12',['LinearFilter',['../classpolyfem_1_1solver_1_1_linear_filter.html',1,'polyfem::solver']]],
  ['linearinterpolation_13',['LinearInterpolation',['../classpolyfem_1_1utils_1_1_linear_interpolation.html',1,'polyfem::utils']]],
  ['linearproblem_14',['LinearProblem',['../classpolyfem_1_1problem_1_1_linear_problem.html',1,'polyfem::problem']]],
  ['linearramp_15',['LinearRamp',['../classpolyfem_1_1utils_1_1_linear_ramp.html',1,'polyfem::utils']]],
  ['linequadrature_16',['LineQuadrature',['../classpolyfem_1_1quadrature_1_1_line_quadrature.html',1,'polyfem::quadrature']]],
  ['linesearch_17',['LineSearch',['../classpolyfem_1_1solver_1_1line__search_1_1_line_search.html',1,'polyfem::solver::line_search']]],
  ['local2global_18',['Local2Global',['../classpolyfem_1_1basis_1_1_local2_global.html',1,'polyfem::basis']]],
  ['localboundary_19',['LocalBoundary',['../classpolyfem_1_1mesh_1_1_local_boundary.html',1,'polyfem::mesh']]],
  ['lshape_20',['Lshape',['../classpolyfem_1_1problem_1_1_lshape.html',1,'polyfem::problem']]]
];
