var searchData=
[
  ['laggedregform_0',['LaggedRegForm',['../classpolyfem_1_1solver_1_1_lagged_reg_form.html',1,'polyfem::solver']]],
  ['lagrange_1',['Lagrange',['../classp__bases_1_1_lagrange.html',1,'p_bases.Lagrange'],['../classq__bases_1_1_lagrange.html',1,'q_bases.Lagrange']]],
  ['lameparameters_2',['LameParameters',['../classpolyfem_1_1_lame_parameters.html',1,'polyfem']]],
  ['laplacian_3',['Laplacian',['../classpolyfem_1_1assembler_1_1_laplacian.html',1,'polyfem::assembler']]],
  ['lbfgssolver_4',['LBFGSSolver',['../classcppoptlib_1_1_l_b_f_g_s_solver.html',1,'cppoptlib']]],
  ['linearassemblerdata_5',['LinearAssemblerData',['../classpolyfem_1_1assembler_1_1_linear_assembler_data.html',1,'polyfem::assembler']]],
  ['linearelasticity_6',['LinearElasticity',['../classpolyfem_1_1assembler_1_1_linear_elasticity.html',1,'polyfem::assembler']]],
  ['linearelasticproblemexact_7',['LinearElasticProblemExact',['../classpolyfem_1_1problem_1_1_linear_elastic_problem_exact.html',1,'polyfem::problem']]],
  ['linearinterpolation_8',['LinearInterpolation',['../classpolyfem_1_1assembler_1_1_linear_interpolation.html',1,'polyfem::assembler']]],
  ['linearproblem_9',['LinearProblem',['../classpolyfem_1_1problem_1_1_linear_problem.html',1,'polyfem::problem']]],
  ['linearramp_10',['LinearRamp',['../classpolyfem_1_1assembler_1_1_linear_ramp.html',1,'polyfem::assembler']]],
  ['linequadrature_11',['LineQuadrature',['../classpolyfem_1_1quadrature_1_1_line_quadrature.html',1,'polyfem::quadrature']]],
  ['linesearch_12',['LineSearch',['../classpolyfem_1_1solver_1_1line__search_1_1_line_search.html',1,'polyfem::solver::line_search']]],
  ['local2global_13',['Local2Global',['../classpolyfem_1_1basis_1_1_local2_global.html',1,'polyfem::basis']]],
  ['localboundary_14',['LocalBoundary',['../classpolyfem_1_1mesh_1_1_local_boundary.html',1,'polyfem::mesh']]],
  ['lshape_15',['Lshape',['../classpolyfem_1_1problem_1_1_lshape.html',1,'polyfem::problem']]]
];
