var searchData=
[
  ['saintvenantelasticity_0',['SaintVenantElasticity',['../classpolyfem_1_1assembler_1_1_saint_venant_elasticity.html',1,'polyfem::assembler']]],
  ['scalarbcvalue_1',['ScalarBCValue',['../structpolyfem_1_1assembler_1_1_scalar_b_c_value.html',1,'polyfem::assembler']]],
  ['selection_2',['Selection',['../classpolyfem_1_1utils_1_1_selection.html',1,'polyfem::utils']]],
  ['simplestokeproblemexact_3',['SimpleStokeProblemExact',['../classpolyfem_1_1problem_1_1_simple_stoke_problem_exact.html',1,'polyfem::problem']]],
  ['sineproblem_4',['SineProblem',['../classpolyfem_1_1problem_1_1_sine_problem.html',1,'polyfem::problem']]],
  ['sinestokeproblemexact_5',['SineStokeProblemExact',['../classpolyfem_1_1problem_1_1_sine_stoke_problem_exact.html',1,'polyfem::problem']]],
  ['solutionframe_6',['SolutionFrame',['../classpolyfem_1_1io_1_1_solution_frame.html',1,'polyfem::io']]],
  ['solvedata_7',['SolveData',['../classpolyfem_1_1solver_1_1_solve_data.html',1,'polyfem::solver']]],
  ['sparematrixcache_8',['SpareMatrixCache',['../classpolyfem_1_1utils_1_1_spare_matrix_cache.html',1,'polyfem::utils']]],
  ['sparsenewtondescentsolver_9',['SparseNewtonDescentSolver',['../classcppoptlib_1_1_sparse_newton_descent_solver.html',1,'cppoptlib']]],
  ['specifiedselection_10',['SpecifiedSelection',['../classpolyfem_1_1utils_1_1_specified_selection.html',1,'polyfem::utils']]],
  ['sphereselection_11',['SphereSelection',['../classpolyfem_1_1utils_1_1_sphere_selection.html',1,'polyfem::utils']]],
  ['splinebasis2d_12',['SplineBasis2d',['../classpolyfem_1_1basis_1_1_spline_basis2d.html',1,'polyfem::basis']]],
  ['splinebasis3d_13',['SplineBasis3d',['../classpolyfem_1_1basis_1_1_spline_basis3d.html',1,'polyfem::basis']]],
  ['state_14',['State',['../classpolyfem_1_1_state.html',1,'polyfem']]],
  ['stokeslawproblem_15',['StokesLawProblem',['../classpolyfem_1_1problem_1_1_stokes_law_problem.html',1,'polyfem::problem']]],
  ['stokesmixed_16',['StokesMixed',['../classpolyfem_1_1assembler_1_1_stokes_mixed.html',1,'polyfem::assembler']]],
  ['stokespressure_17',['StokesPressure',['../classpolyfem_1_1assembler_1_1_stokes_pressure.html',1,'polyfem::assembler']]],
  ['stokesvelocity_18',['StokesVelocity',['../classpolyfem_1_1assembler_1_1_stokes_velocity.html',1,'polyfem::assembler']]]
];
