var searchData=
[
  ['backtrackinglinesearch_28',['BacktrackingLineSearch',['../classpolyfem_1_1solver_1_1line__search_1_1_backtracking_line_search.html',1,'polyfem::solver::line_search']]],
  ['base64layer_29',['base64Layer',['../classpolyfem_1_1utils_1_1base64_layer.html',1,'polyfem::utils']]],
  ['bases_5fgrads_30',['bases_grads',['../classpolyfem_1_1basis_1_1_r_b_f_with_linear.html#afa40ad3884f69ea106c439bfa9d49d5e',1,'polyfem::basis::RBFWithLinear::bases_grads()'],['../classpolyfem_1_1basis_1_1_r_b_f_with_quadratic.html#a4f23527b0e433b12c941007b6623a099',1,'polyfem::basis::RBFWithQuadratic::bases_grads()'],['../classpolyfem_1_1basis_1_1_r_b_f_with_quadratic_lagrange.html#a14bc20f54259d897845191ba729f93f0',1,'polyfem::basis::RBFWithQuadraticLagrange::bases_grads()']]],
  ['bases_5fvalues_31',['bases_values',['../classpolyfem_1_1basis_1_1_r_b_f_with_linear.html#a5125dbd2cec8ea3a597b3452526bb822',1,'polyfem::basis::RBFWithLinear::bases_values()'],['../classpolyfem_1_1basis_1_1_r_b_f_with_quadratic.html#a423295c4a8d424c9572f15221b4c52e8',1,'polyfem::basis::RBFWithQuadratic::bases_values()'],['../classpolyfem_1_1basis_1_1_r_b_f_with_quadratic_lagrange.html#a443e46941f94f2b8e3dc0398caf2ed0d',1,'polyfem::basis::RBFWithQuadraticLagrange::bases_values()']]],
  ['basis_32',['Basis',['../classpolyfem_1_1basis_1_1_basis.html',1,'polyfem::basis::Basis'],['../classpolyfem_1_1basis_1_1_r_b_f_with_linear.html#ab60f858eefdd193a7e9277f8578e94b2',1,'polyfem::basis::RBFWithLinear::basis()'],['../classpolyfem_1_1basis_1_1_r_b_f_with_quadratic.html#a1707dc6e1745ab4fceb760c690bd8c00',1,'polyfem::basis::RBFWithQuadratic::basis()'],['../classpolyfem_1_1basis_1_1_r_b_f_with_quadratic_lagrange.html#a687de8eec89bd8d5d1c575b4d121d579',1,'polyfem::basis::RBFWithQuadraticLagrange::basis()']]],
  ['bcvalue_33',['BCValue',['../classpolyfem_1_1problem_1_1_point_based_tensor_problem_1_1_b_c_value.html',1,'polyfem::problem::PointBasedTensorProblem']]],
  ['bdf_34',['BDF',['../classpolyfem_1_1time__integrator_1_1_b_d_f.html',1,'polyfem::time_integrator']]],
  ['bdftimeintegrator_35',['BDFTimeIntegrator',['../classpolyfem_1_1time__integrator_1_1_b_d_f_time_integrator.html',1,'polyfem::time_integrator']]],
  ['bilaplacianaux_36',['BilaplacianAux',['../classpolyfem_1_1assembler_1_1_bilaplacian_aux.html',1,'polyfem::assembler']]],
  ['bilaplacianmain_37',['BilaplacianMain',['../classpolyfem_1_1assembler_1_1_bilaplacian_main.html',1,'polyfem::assembler']]],
  ['bilaplacianmixed_38',['BilaplacianMixed',['../classpolyfem_1_1assembler_1_1_bilaplacian_mixed.html',1,'polyfem::assembler']]],
  ['bilaplacianproblemwithsolution_39',['BilaplacianProblemWithSolution',['../classpolyfem_1_1problem_1_1_bilaplacian_problem_with_solution.html',1,'polyfem::problem']]],
  ['boundarysampler_40',['BoundarySampler',['../classpolyfem_1_1utils_1_1_boundary_sampler.html',1,'polyfem::utils']]],
  ['boxselection_41',['BoxSelection',['../classpolyfem_1_1utils_1_1_box_selection.html',1,'polyfem::utils']]],
  ['build_5fbases_42',['build_bases',['../classpolyfem_1_1basis_1_1_f_e_basis2d.html#a6a7728e6ff9fa8c4f4abbdcb9861fe9d',1,'polyfem::basis::FEBasis2d::build_bases(const mesh::Mesh2D &amp;mesh, const int quadrature_order, const int discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector&lt; ElementBases &gt; &amp;bases, std::vector&lt; mesh::LocalBoundary &gt; &amp;local_boundary, std::map&lt; int, InterfaceData &gt; &amp;poly_edge_to_data, std::vector&lt; int &gt; &amp;primitive_to_node)'],['../classpolyfem_1_1basis_1_1_f_e_basis2d.html#a2080f89c2a03f2b895467d82f9460722',1,'polyfem::basis::FEBasis2d::build_bases(const mesh::Mesh2D &amp;mesh, const int quadrature_order, const Eigen::VectorXi &amp;discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector&lt; ElementBases &gt; &amp;bases, std::vector&lt; mesh::LocalBoundary &gt; &amp;local_boundary, std::map&lt; int, InterfaceData &gt; &amp;poly_edge_to_data, std::vector&lt; int &gt; &amp;primitive_to_node)'],['../classpolyfem_1_1basis_1_1_f_e_basis3d.html#af1f9672263a3f17c910d24feb2ccc189',1,'polyfem::basis::FEBasis3d::build_bases(const mesh::Mesh3D &amp;mesh, const int quadrature_order, const int discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector&lt; ElementBases &gt; &amp;bases, std::vector&lt; mesh::LocalBoundary &gt; &amp;local_boundary, std::map&lt; int, InterfaceData &gt; &amp;poly_face_to_data, std::vector&lt; int &gt; &amp;primitive_to_node)'],['../classpolyfem_1_1basis_1_1_f_e_basis3d.html#a231a5333145c1602e2a240c8ea429fad',1,'polyfem::basis::FEBasis3d::build_bases(const mesh::Mesh3D &amp;mesh, const int quadrature_order, const Eigen::VectorXi &amp;discr_order, const bool serendipity, const bool has_polys, const bool is_geom_bases, std::vector&lt; ElementBases &gt; &amp;bases, std::vector&lt; mesh::LocalBoundary &gt; &amp;local_boundary, std::map&lt; int, InterfaceData &gt; &amp;poly_face_to_data, std::vector&lt; int &gt; &amp;primitive_to_node)'],['../classpolyfem_1_1basis_1_1_polygonal_basis2d.html#aa8d348e8e9800d665160b7cc290ea1e6',1,'polyfem::basis::PolygonalBasis2d::build_bases()'],['../classpolyfem_1_1basis_1_1_polygonal_basis3d.html#ac1e4731b8df4d9d529bb995056cbc568',1,'polyfem::basis::PolygonalBasis3d::build_bases()']]]
];
